### ISSUE TITLE
How to get all users, groups and roles that have access to a resource or service ??

### ISSUE THREAD

**Issue by pawanaichra-datagrokr** [cloud-custodian/cloud-custodian#1334]
Does cloud-custodian have this ??
If yes, please give an example.
If no, please give some idea or references how can I implement this.
Thanks

**Comment by pawanaichra-datagrokr** [comment]
@kapilt , @scotwk , @whit537

**Comment by whit537** [comment]
This sounds like the iam simulate work that ... is still stuck in https://github.com/capitalone/cloud-custodian/pull/1084. 😊 Perhaps I will dust that off ...

Still, that only adds the relevant filter for S3 buckets. What resources/services are you looking for, @pawanaichra-datagrokr?

**Comment by pawanaichra-datagrokr** [comment]
@whit537 Thanks for your response.
Actually, I am thinking that we can get all services that have permissions for a policy like in this screenshot [https://i.stack.imgur.com/xBMJP.jpg](url) and we can also get users, groups and roles attached to that policy. so we can get all users, groups and roles that have access to a services or resources by looping over all policies. Is that possible??

**Comment by whit537** [comment]
Inlining image (link is garbled) ...

![](https://user-images.githubusercontent.com/134455/27766166-367a88e4-5e7c-11e7-8453-a4adf1197eb4.jpg)

**Comment by whit537** [comment]
Right, I don't believe we have that presently. @kapilt?

**Comment by kapilt** [comment]
its definitely something thats been on the backlog for a while, basically iam simulate as a user/group/role filter. not sure we would support resource policy evaluations, thats gets more complicated, for s3 as noted it was done as a separate resource level filter.

**Comment by kapilt** [comment]
the new `check-permissions` filter allows this.
