### ISSUE TITLE
Exponential Backoff / Throttling for Rate Limits

### ISSUE THREAD

**Issue by lorenzoaiello** [cloud-custodian/cloud-custodian#1390]
Right now it doesn't look like Custodian is doing exponential back-offs when rate limits are reached which makes it completely unusable when performing bulk actions (like snapshotting all EBS volumes) against the AWS APIs.

The ask is to do one of two things;
- Implement exponential back offs instead of straight retries
- Implement a way to pass a parameter to throttle the number of requests per second

**Comment by kapilt** [comment]
we actually do backoff (geometric not quite exponential), on top of the sdk builtin.

**Comment by kapilt** [comment]
throttle is covered under a separate issue #972

**Comment by lorenzoaiello** [comment]
Thanks, yeah - I figured as much but we keep getting failures due to rate limiting. AWS has recommended we try to spread the requests out more evenly over an extended period of time or implement exponential back offs to resolve the issue. 

I have confirmed with our AWS Enterprise team that token buckets won't work as the rate limiting is done per account, not per account so rotating through keys won't help resolve the issue.

I think the only viable solution would be a way to artificially throttle the connection throughput via something built-in, or using a queue (SQS?) to separate the action execution from identification.

**Comment by kapilt** [comment]
I think there's some misunderstanding on token rate bucket usage here, its meant per account with single credential to limit outbound, which effects a more evenly over longer period.

**Comment by kapilt** [comment]
also I'd recommend checking out tools/c7n_traildb for identifying whats causing api issues in your account.

**Comment by lorenzoaiello** [comment]
I'll definitely have a look at tools/c7n_traildb, but I am not sure what additional information it will provide.

We have confirmed both in the console output, with AWS support, and by viewing the API limit graphs that we are just hitting the rate limits when performing bulk operations and the back-offs currently present in custodian are insufficient to prevent policy completion (rather resulting in partials).

**Comment by kapilt** [comment]
can you share the policy your using? and what sort of resource counts, and which region your processing it in. we regularly do snapshotting of thousands of vols in a single account, but we have noticed some region specific aspects to the rate limits.

**Comment by lorenzoaiello** [comment]
**Sample 1**
Region: us-west-2
Policy:
```
- name: ebs-nightly-backup
  resource: ebs
  actions:
  - type: snapshot
```
EBS Volumes: 1,300

**Sample 2**
Region: us-west-2
Policy:
```
- name: ebs-purge-old
  resource: ebs-snapshot
  filters:
  - type: age
    days: 30
    op: ge
  actions:
  - type: mark-for-op
    op: delete
    days: 7
```
EBS Snapshots: 22,000

**Comment by kapilt** [comment]
rate issues due to seem to be region specific wrt to thresholds, noted.

**Comment by kapilt** [comment]
we do have some retries in custodian, but the best way is actually to handle this via sdk configuration on environment variables

```
export AWS_RETRY_MODE="adaptive"
export AWS_MAX_ATTEMPTS="6"
```
