### ISSUE TITLE
Cloud Custodian for Azure?

### ISSUE THREAD

**Issue by ss1921** [cloud-custodian/cloud-custodian#1442]
Hi guys!

I have used Cloud Custodian for AWS. So far, I had a phenomenal experience! Since I have to deal with Azure as well, I would like to know if there's any update on Cloud Custodian being ready for Azure.

**Comment by kapilt** [comment]
we have a goal for custodian to support both gce and azure by end of year, the degree of that support is going to vary. are there particular resources or features you'd be interested in azure?

**Comment by gpjonesii** [comment]
Hi! Where are you guys at with Azure support?

**Comment by raghavnielsen** [comment]
@kapilt - Is Azure support available any soon. Please let me know your plan/roadmap. We have a need of policy and governance engine for Azure. We are very much interested to work with guys on this. Should we wait on this if it is available soon or we should fork it and contribute back.

**Comment by jdogg89** [comment]
@kapilt The last update you left was in August, is there any change with Cloud Custodian supporting Azure?

**Comment by thisisshi** [comment]
@mahomedalid yes, azure is currently being worked on and you can access azure resources if you install the repo from source. @stefangordon and @aluong can chime in on resource support and other questions related to azure

**Comment by aluong** [comment]
Link to the Azure support: https://cloudcustodian.io/docs/azure/gettingstarted.html
