### ISSUE TITLE
VPC delete action

### ISSUE THREAD

**Issue by JoshRosen** [cloud-custodian/cloud-custodian#1488]
I have a use-case where I would like to delete entire VPCs based on their creation date. It looks like there may already be the capability to apply generic filters to VPCs, but there doesn't appear to be a VPC deletion action (instead we can currently only delete security groups).

**Comment by kapilt** [comment]
deleting a vpc, also means deleting all resources attached to it prior to invoking delete. are the vpcs your looking to delete already empty, or are you looking to delete every vpc attached resource (lambda, ec2, rds, redshift, efs, etc) before deleting the vpc?

**Comment by kapilt** [comment]
at the moment if a vpc is non empty we would just error out in the action and stop that policy's execution.

**Comment by JoshRosen** [comment]
I think that supporting the deletion of empty VPCs would address our use-case. We have an integration test suite which is somehow leaking empty VPCs. There are other layers of attempted cleanup, but I'd like to also be able to use Custodian as an additional safety net to cleanup those resources.

**Comment by sri321** [comment]
we would like this option too , is this request in progress?

**Comment by kapilt** [comment]
its not, contributions welcome
