### ISSUE TITLE
docker image publishing

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#1494]
we stopped doing docker hub images a few weeks ago, by removing it from drone due to secrets regeneration management overhead, we should either re-enable that or enable something as a sidecar to do it. ideally this would also tackle the image tagging for released versions.

**Comment by sstarcher** [comment]
Anything as a user I can do to help this along?

**Comment by sstarcher** [comment]
I went ahead and created an automatic build based on my fork for now.  It will track master here, but only when I get around to bumping it to track master updates.

https://hub.docker.com/r/sstarcher/cloud-custodian

**Comment by kapilt** [comment]
we have an official build setup now auto publishing latest and tags, available here. https://hub.docker.com/r/cloudcustodian/c7n
