### ISSUE TITLE
Feature request - VPC

### ISSUE THREAD

**Issue by myoung34** [cloud-custodian/cloud-custodian#1509]
Being able to check VPC level resources and attributes such as tenancy, tags requirements, etc

**Comment by kapilt** [comment]
sounds good re tenancy/dhcp options, tags filters are already available.

**Comment by jason-riddle** [comment]
This would be extremely useful since elasticsearch now has support for running within a VPC https://aws.amazon.com/about-aws/whats-new/2017/10/amazon-elasticsearch-service-announces-support-for-amazon-virtual-private-cloud-vpc.

**Comment by kapilt** [comment]
afaict this is already possible
