### ISSUE TITLE
Security group diff filter

### ISSUE THREAD

**Issue by Dhruvin1** [cloud-custodian/cloud-custodian#1547]
Hi,
I want to notify the aws account owner when the security group is being changed. I saw that I can use the diff filter. However, I cannot find an example of use case. If you can provide an example, it would be quite easy to figure out the changes. I am getting an internal error related to Tag when I am running the policy.

**Comment by kapilt** [comment]
security group diffing relies on aws config for a historical state db. what does your policy look like? there's an open pull request for a more generic diff across all resources using json patch as a format. the sg diff is currently a custom implementation suitable for inverse patch application by (revert).

**Comment by Dhruvin1** [comment]
Hi Kapil. My policy looks like this:
**policies:
  - name: security-group-diff
    resource: security-group
    filters:
      - type: diff
        selector: date
        selector_value: Thu, 7 Sep 2017**
No matter what date I provide for comparison, it matches no resources. Also I am not being able to know how the "is-locked" filter works.
Thanks.
