### ISSUE TITLE
value filter to support getting value from a key

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#1578]
Enhance value filters by support for retrieving the value of another key instead of having to specify a specific value.  For example:
  - name: DynamoDBLowUtilizationSuspected
    resource: dynamodb-table
    description: |
      Notify if Dynamodb utilization is suspected to be low
    filters:
      - type: value
      	key: ItemCount
        op: less-than
        value_key: ProvisionedThroughput.WriteCapacityUnits

**Comment by kapilt** [comment]
we had a value_type: expr for this but per #1617 there's still an issue that needs resolving with it.

**Comment by ajkerrigan** [comment]
Housekeeping - this is covered by `value_type: expr`
