### ISSUE TITLE
Cloudtrail check set operator among filter conditions - account.py

### ISSUE THREAD

**Issue by ohuk2** [cloud-custodian/cloud-custodian#1678]
HI there, couldn't get the cloudtrail check to work, looks like resources/account.py line 157 needs a small fix:

        if trails:
            return []
        return resources

The first line should say "if not trails:"

Thanks!

**Comment by kapilt** [comment]
so the logic here is meant to be inverted, ie want to return the resources (account in this case) for actions, if our conditions don't hold. if we had matched trails we want the policy to exit out. on actions we would be taking remediation steps.

**Comment by ohuk2** [comment]
OK I see :-) . Unfortunately I'm unable to get the cloudtrail check working no matter what I do, any idea what I am doing wrong below (or whether I have misunderstood something)? 

I have five cloudtrails in a lab environment of various statuses/configs. I've reduced my check-cloudtrail filter to the simplest possible, that should just check "IsLogging".  Toggling "running" true/false should just invert that test, correct?

 $ aws --region us-east-1  --profile lab cloudtrail describe-trails --query 'trailList[*].[Name,IncludeGlobalServiceEvents,IsMultiRegionTrail,LogFileValidationEnabled,KmsKeyId,S3BucketName]' --output text
L[...]     True    False   True    arn:aws:kms:us-east-1:[...]        5[...]
h[...]     True    False   True    arn:aws:kms:us-east-1:[...]        l[...]
**j[...]-cc  True    True    True    arn:aws:kms:us-east-1:[...]        j[...]**
l[...]     False   False   False   None                               a[...]  
l[...]     True    True    True    arn:aws:kms:us-east-1:[...]        a[...]

**Let's take the third trail above and check the status:**

$  aws cloudtrail --profile lab get-trail-status --region us-east-1 --name j[...]-cc
{
    "LatestNotificationTime": 1508576728.862,
    "LatestNotificationAttemptSucceeded": "2017-10-21T09:05:28Z",
    "LatestDeliveryAttemptTime": "2017-10-21T09:05:28Z",
    "LatestDeliveryTime": 1508576728.862,
    "LatestDeliveryAttemptSucceeded": "2017-10-21T09:05:28Z",
    "IsLogging": true,
    "TimeLoggingStarted": "2016-11-25T14:27:15Z",
    "StartLoggingTime": 1480084035.238,
    "LatestDigestDeliveryTime": 1508573501.966,
    "StopLoggingTime": 1480084034.171,
    "LatestNotificationAttemptTime": "2017-10-21T09:05:28Z",
    "TimeLoggingStopped": "2016-11-25T14:27:14Z"
}

**If we now run Custodian and toggle "running":**

$ cat cloudtrail-enabled.yml
policies:
  - name: account-cloudtrail-enabled
    resource: account
    filters:
     - type: check-cloudtrail
       running: true

$ custodian run  --profile lab  --output-dir ./output --region us-east-1  cloudtrail-enabled.yml
2017-10-21 10:17:54,413: custodian.policy:INFO policy: account-cloudtrail-enabled resource:account region:us-east-1 count:0 time:1.85


$ vi cloudtrail-enabled.yml
$ cat cloudtrail-enabled.yml
policies:
  - name: account-cloudtrail-enabled
    resource: account
    filters:
     - type: check-cloudtrail
       running: false

$ custodian run  --profile lab  --output-dir ./output --region us-east-1  cloudtrail-enabled.yml
2017-10-21 10:18:36,496: custodian.policy:INFO policy: account-cloudtrail-enabled resource:account region:us-east-1 count:0 time:1.19

**Comment by kapilt** [comment]
so the filter is to detect when cloudtrail is not running, if you have cloudtrail running, then its not going to match. you can specify additional conditions on the filter to force a match on the account (ie. no trails matched the conditions).

perhaps its worth backing up a step, what's your goal here?

**Comment by ohuk2** [comment]
Hi there, have gone through the logic, as it stands now, if you have many trails but only one is running, you don't get an error. In my case, with five trails, I tried with the following:

  - name: account-cloudtrail-enabled
    resource: account
    filters:
     - type: check-cloudtrail
       global-events: false
       multi-region: true
       running: true

That limited the number of trails to two. I then did "aws-cloudtrail stop-logging" on one, and re-ran custodian. It didn't report on the stopped trail. 

It would have been great when specify "running: true" that the trails that are not running are reported, maybe create a list "not_running", and return that?

**Comment by ohuk2** [comment]
Something like this:

        if self.data.get('running', True):
            running = []
            not_running = []
            for t in list(trails):
                t['Status'] = status = client.get_trail_status(
                    Name=t['TrailARN'])
                if status['IsLogging'] and not status.get(
                        'LatestDeliveryError'):
                    running.append(t)
                else:
                    not_running.append(t)
            trails = running
            resources[0]['c7n:cloudtrails'] = not_running
        if trails and len(resources[0]['c7n:cloudtrails']) == 0:
            return []
        return resources

That returned:
2017-10-25 12:27:52,180: custodian.policy:INFO policy: account-cloudtrail-enabled resource:account region:us-east-1 count:1 time:1.59
 and 

$ cat output/account-cloudtrail-enabled/resources.json
[
  {
    "c7n:cloudtrails": [
      {
        "Status": {
          "LatestNotificationTime": "2017-10-25T11:55:50.048000+01:00",
          "ResponseMetadata": {
            "RetryAttempts": 0,
            "HTTPStatusCode": 200,
            "RequestId": "6d5f8f48-532f-4ddb-abe6-cbea909596a4",
            "HTTPHeaders": {
              "x-amzn-requestid": "6d5f8f48-532f-4ddb-abe6-cbea909596a4",
              "date": "Wed, 25 Oct 2017 11:27:51 GMT",
              "content-length": "523",
              "content-type": "application/x-amz-json-1.1"
            }
          },
          "LatestNotificationAttemptSucceeded": "2017-10-25T10:55:50Z",
          "LatestDeliveryAttemptTime": "2017-10-25T10:55:50Z",
          "LatestDeliveryTime": "2017-10-25T11:55:50.048000+01:00",
          "LatestDeliveryAttemptSucceeded": "2017-10-25T10:55:50Z",
          "IsLogging": false,
          "TimeLoggingStarted": "2017-10-25T10:45:19Z",
          "StartLoggingTime": "2017-10-25T11:45:19.166000+01:00",
          "LatestDigestDeliveryTime": "2017-10-25T12:11:41.820000+01:00",
          "StopLoggingTime": "2017-10-25T11:46:10.616000+01:00",
          "LatestNotificationAttemptTime": "2017-10-25T10:55:50Z",
          "TimeLoggingStopped": "2017-10-25T10:46:10Z"

**Comment by kapilt** [comment]
yeah that makes sense re set operation parameter to ensure that the whole set matches the filters conditions

**Comment by kapilt** [comment]
we've added in additional filters for cloud trail resources, that allow the user to specify more arbitrary filtering beyond what the account resource cloudtrail filters provide.
