### ISSUE TITLE
AWS Config service check not working

### ISSUE THREAD

**Issue by ohuk2** [cloud-custodian/cloud-custodian#1680]
Similar to the previous cloudtrail issue, looks like resources/account.py needs another fix on line 217? The config service check currently does not work, as far as I can tell. 

Thanks again!

**Comment by kapilt** [comment]
same thing as #1678 we want to return the resources when the filter does not find a working config setup per the filter parameters for remediation actions, if we do find a working config setup, we don't return the account for remediation/notification actions.
