### ISSUE TITLE
asg action list in validation doesn't match schema list, something seems broken

### ISSUE THREAD

**Issue by JohnTheodore** [cloud-custodian/cloud-custodian#1683]
Here is the action:
    - type: mark-for-op
      tag: auto:custodian:maid-status-email-only
      op: notify
      days: 7

Here is the error:
Exception: Failed to validate on policy asg-tagging-noncompliance-email-only
 'notify' is not one of [u'suspend', u'resume', u'delete']

Failed validating u'enum' in schema[11][u'properties']['op']:
    {u'enum': [u'suspend', u'resume', u'delete']}

On instance['op']:
    'notify'

here is the current output of schema:
(cloud-custodian) ➜  cloud-custodian-wrapper git:(master) ✗ custodian schema asg
asg:
  actions: [auto-tag-user, delete, invoke-lambda, mark, mark-for-op, notify, propagate-tags,
    put-metric, remove-tag, rename-tag, resize, resume, suspend, tag, tag-trim, unmark,
    untag]
  filters: [and, capacity-delta, event, image, image-age, invalid, launch-config,
    marked-for-op, metrics, network-location, not, not-encrypted, offhour, onhour,
    or, security-group, subnet, tag-count, valid, value, vpc-id]

**Comment by kapilt** [comment]
thanks for the bug report. asg `mark-for-op` action is currently hardcoding a static set of actions in its jsonschema, it should be inspecting the registry of actions dynamically in its `validate` method.

**Comment by kapilt** [comment]
this is fixed, mark-for-op dynamically pulls list of actions.
