### ISSUE TITLE
 An error occurred (RequestLimitExceeded) when calling the CreateTags operation (reached max retries: 4): Request limit exceeded.

### ISSUE THREAD

**Issue by rracterr** [cloud-custodian/cloud-custodian#1813]
running:

  - name: ebs-copy-instance-tags
      resource: ebs
      filters:
       - type: value
         key: "Attachments[0].Device"
         value: not-null
      actions:
       - type: copy-instance-tags
         tags:
          - Name

configuration:

ran via c7n-org across 50 accounts

handled exception:

2017-11-20 17:56:40,770: custodian.actions:ERROR Exception renaming tag set 
 An error occurred (RequestLimitExceeded) when calling the CreateTags operation (reached max retries: 4): Request limit exceeded.

**Comment by jdubs** [comment]
Looks like your account is hitting an aws limit. 
I would recommend extending the filter to only apply when the ebs name is null.

**Comment by kapilt** [comment]
looks like some backoff retry was added to this action (and its intelligent about not copying if the values are current), but in general if account is under stress, we won't continue indefinitely in the face of continuous throttle errors.

**Comment by major0** [comment]
I started running into this recently and was wondering if c7n-org is not doing Exponential back-off, and if so, if the back-off is coordinated across all workers?

Doing something as simple as inspecting the `service-limit` runs into this for me across a relatively few number accounts+regions.
