### ISSUE TITLE
request-limit-increase action (account resource) not creating AWS Support cases correctly

### ISSUE THREAD

**Issue by jfi247** [cloud-custodian/cloud-custodian#1917]
Policy looks like this:

`policies:
  - name: account-service-limits
    resource: account
    filters:
      - type: service-limit
        threshold: 10
    actions:
      - type: request-limit-increase
        percent-increase: 25
        message: "Please raise the below account limit(s); \n {limits}"
        severity: normal`

This creates a Technical case type rather than a Service Limit case type.  Also there is no severity level for Service Limit case (it defaults to General Guidance).  See attached screenshot for example.
![screen shot 2018-01-04 at 3 05 50 pm](https://user-images.githubusercontent.com/22039133/34588544-69f71330-f162-11e7-9ee2-881d6f1567f4.png)

**Comment by kapilt** [comment]
a support case for a limit increase can't be created through the api [0], for accounts using aws support, we typically recommend coordinating with the account support team that you'll be filing limit increases this way. you can configure the severity on the policy

[0] - http://boto3.readthedocs.io/en/latest/reference/services/support.html#Support.Client.create_case

**Comment by kapilt** [comment]
wrt to category, the value is service specific, the only two generic categories across services are general guidance or feature request. the severity level is passed through from the policy value (low, normal, high, urgent, critical), the support console ui, may display that value different.
