### ISSUE TITLE
On-demand execution of policies against targeted resources?

### ISSUE THREAD

**Issue by erickascic** [cloud-custodian/cloud-custodian#1927]
Given c7n is being used by some "operations" or "compliance" group to maintain order in an AWS account, I've seen resources "mysteriously" disappear after a deployment where AWS resources are converged.  Given a delay in scanning resources - even seen smoke tests for the deployment pass and then a few minutes later the app stops working because security groups have had ingress rules removed or the like.

I'm wondering if it's possible to create an API for c7n that allows a development team to run the same policies the "compliance" group will run later, but on-demand in a targeted way against the new resources converged as part of deployment?  This would hopefully minimize the amount of surprise as the resources would be mangled as part of the deployment and smoke tests would likely fail (or any remediation could conservatively cause a deployment failure).

As an aside, to achieve a similar goal with AWS Config - I've done something awkward and after-the-fact - take the physical resource ids from a converged cloudformation stack and take the intersection of the AWS Config Rule results for the account to see if the stack has any non-compliant resources.  It is a bit awkward in implementation though vs. just invoking the same "scans" in a targeted way (which AWS config doesn't allow you to do).

**Comment by kapilt** [comment]
its possible for an app team to incorporate custodian into their pipelines as well, as long as they do so in a targeted fashion (tag filters etc), ie the api is just run the tool as a cli, in jenkins, drone, travis.. etc. in general best practice for the 'operations/compliance' group when modifying resources in a policy is to send notification to the resource owner. custodian supports aws config for policy deployment (as a config rule) or resource query source. there's been some experimental work done on operating custodian directly against cfn and tf templates via mapping those but its not very general purpose.

**Comment by kapilt** [comment]
also it seems like part of the issue is the fragility of cfn vs tf ;-) ymmv
