### ISSUE TITLE
RDS Cluster Filter for VpcId

### ISSUE THREAD

**Issue by wpark94** [cloud-custodian/cloud-custodian#2057]
It would be nice to have a filter for RDS Clusters mimicking that of RDS Instance to filter by VpcId. Can currently only filter by subnet groups.

**Comment by kapilt** [comment]
i think we want to move to a vpc filter instead of just a vpc id, to allow for more flexible filtering, but sounds good.

**Comment by kapilt** [comment]
This (vpc filter) has been around for a while
