### ISSUE TITLE
NFR: Support of aws network load balancer

### ISSUE THREAD

**Issue by prysmakou** [cloud-custodian/cloud-custodian#2099]
There is new type of LB on ec2 - network. It would be great to add it to list of known objects

**Comment by kapilt** [comment]
it is supported, although i can see why thats not readily apparent. The elbv2 api is used for both app and network load balancers, so both can be found at the moment via the `app-elb` resource. Part of that is historical reason (elbv2 was used for app load balancers only then grew network lb support). It would be nice to clean that up and have two resources, but at the moment there isn't any server side filtering when describing load balancers on elbv2 api to distinguish between the load balancer types.

**Comment by prysmakou** [comment]
@kapilt Thank you very much for the clarification. I'm pretty new to Custodian so I just missed it. I was looking for smth having "net" in the name of resource. Well, then it needed to extend documentation and create an alias (I didn't read code so have no idea if it easy to implement).
