### ISSUE TITLE
Nice to have - in 'iam-user' resource filter

### ISSUE THREAD

**Issue by timbo256** [cloud-custodian/cloud-custodian#2162]
It would be nice to have a 'value_from' option in the filter for iam-user - especially to filter out a group of user accounts from a s3 bucket file

e.g 
filters:
  - type: credential
    key: user
    op: not-in
    value_from:
        url: s3//xxxx/xxxx
 
rather than have to use 'value:' with embedded fields.

Or am I missing something?

**Comment by kapilt** [comment]
can't you already do that outside of the credential filter to achieve the same effect
