### ISSUE TITLE
Policy Date Active Field

### ISSUE THREAD

**Issue by mandeepbal** [cloud-custodian/cloud-custodian#2185]
Could we add a activate or deactivate field for the policy DSL? I run my policies on a cron and was wondering if it would be able for `custodian run` to skip over policies that should not be run yet. This would allow me to schedule policy additions to become active at specific times.

**Comment by thisisshi** [comment]
Adding support in: https://github.com/capitalone/cloud-custodian/pull/2186

**Comment by kapilt** [comment]
its an interesting use case, and one makes sense especially for orgs not doing CD with policies (and even for some cases those with).

one minor concern, it also creates some additional reasoning from an audit perspective, on whats actually executing and when it was added. ie, its not per se infrastructure as code anymore with straight audit of version history to active, its a secondary evaluation.
