### ISSUE TITLE
S3 Bucket statement filter high fail rate

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#2200]
When using a s3 filter to check to see if a statement exists on a bucket I tend to get lots of errors that say 'Sid' and looking into this I found it was erroring out because there are a lot of buckets in our environments who have bucket policies without Sids on every statement.  This causes those buckets to be skipped over so  they never get my custodian specified bucket policy applied to them. Ex: https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/s3.py#L888

**Comment by thisisshi** [comment]
Even if a Sid is missing, the comparison would then be `None in required` as `.get()` defaults to `None`, which shouldn't error out, it should just move onto the next statement in the list as the check would return False

```python
>>> sid = {'Sid': 'asdf'}
>>> sidless = {}
>>> policies = [sid, sidless]
>>> required = ['asdf']
>>> for p in policies:
...     if p.get('Sid') in required:
...             required.remove(p.get('Sid'))
...
>>> print required
[]
```

Perhaps I'm not fully understanding your error, could you post a log of the actual issue?

**Comment by kapilt** [comment]
use `has-statement` it allows for more exact filtering based on statement contents, irrespective of sid
