### ISSUE TITLE
Shield support region locked to us-east-1

### ISSUE THREAD

**Issue by LykinsN** [cloud-custodian/cloud-custodian#2218]
Session creation for setting Shield protection through Custodian has been pre-pointed to us-east-1, rather than dynamically detecting whichever account Custodian is running against.

Attempting to set against a different region results in this error, in this example attempting to run against accounts in us-west-2: `ClientError: An error occurred (InvalidSignatureException) when calling the DescribeSubscription operation: Credential should be scoped to a valid region, not 'us-west-2'.`

**Comment by kumarsiyer** [comment]
I don't think shield is a available across all regions. 

https://aws.amazon.com/about-aws/whats-new/2018/01/aws-shield-advanced-and-aws-waf-now-available-in-asia-pacific-sydney-and-eu-frankfurt-regions/

**Comment by kapilt** [comment]
hmmm,  yeah there's something odd here, i think my intent was for around cloudfront for us-east-1 since its a global resource. thanks for filing the issue.
