### ISSUE TITLE
Azure Tests - Improve Documentation

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#2270]
There is a readme.md in the tests\templates folder with a small explanation of how we use ARM templates to ensure we have a repeatable way to regenerate cassettes, and there is a bit of official Custodian documentation about running Tox.

There isn't really anything about Azure tests specifically - how the VCRpy and Cassettes stuff works, when things run and how you should write new tests.  I think we should document this with links to appropriate framework documentation (vcrpy, vcrunittest, etc) in the Azure section of the Sphinx docs to help new people get started.

We might also be able to include pointers on how to run the tests outside of Tox config (does require specific auth environment variables, python paths, etc) - without getting into pycharm/vscode/ide specifics.

**Comment by kapilt** [comment]
Developer docs would are definitely an area of interest, @jonathana is working on some general principles (a bit of zen of python and convergent behavior), but i'd it would be great to see breakouts per cloud provider given there's specific dev workflows and tooling around each.
