### ISSUE TITLE
Azure Storage support for Custodian output

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#2280]
http://capitalone.github.io/cloud-custodian/docs/quickstart/usage.html#s3-logs-records

Custodian supports S3 endpoints for writing its output.  Let's see what is required to get Azure Storage support via the Azure Plugin.

**Comment by kapilt** [comment]
This is a little bit more involved at the moment, I've got a few in progress branches for the prelims. Namely we need to make outputs configurable (move to a registry), second (although i think optional for this one) we should probably move some of the output cli params into the config file (for additional output types and config), third and the part that i'm a bit more unsure on is doing the assembly of the output configuration as we construct the policy execution context. we have a few implicit contracts here, the primary one being the output directory, which is a file/object storage, but some of the others have implicit ordering (remote logging, api call stats, etc).

**Comment by kapilt** [comment]
so realized i'm probably overthinking this, i think easiest for unblocking this is just recognizing that one of the outputs (namely blob/file storage) is special, and just doing a registry for that with uri protocol matching for construction ('s3', 'gcs', 'abs'?) is there a canonical uri prefix for azure blob storage?

**Comment by stefangordon** [comment]
Makes sense.  No common prefix that I am aware of, but we can just use azure:// or asb:// or abs:// whatever.
