### ISSUE TITLE
What IAM actions do lambda functions need?

### ISSUE THREAD

**Issue by zfLQ2qx2** [cloud-custodian/cloud-custodian#2291]
Good evening,

For an EC2 policy that is going to consume cloudwatch events, check attributes of an EC2 instance, and submit a message to SQS for c7n_mailer, what are the minimal set of IAM permissions I would need for the lambda role? 

I am guessing:
logs:CreateLogGroup
logs:CreateLogStream
logs:PutLogEvents
ec2:DescribeInstances
ec2:DescribeTags
sqs:SendMessage

I'm not sure about cloudwatch or what other ec2 actions I might need. Maybe ec2:Describe*

**Comment by kapilt** [comment]
you don't need sts assume role, unless your passing --assume on the cli. if your not doing that you'll need to explicitly set a role on your lambda policy.

wrt to the permissions for a given policy to execute in lambda, its highly dependent on what filters and actions your taking.

**Comment by zfLQ2qx2** [comment]
@thisisshi @kapilt  Thank you for the information!
