### ISSUE TITLE
AWS Security Group Ingress Rule Remediation - bug ::/0 rule remains

### ISSUE THREAD

**Issue by hnakhla** [cloud-custodian/cloud-custodian#2313]
Hello,

Current remediation use-case for 0.0.0.0/0 ingress rule works great. however, I noticed AWS now creates an additional rule entry with source ::/0. I tried modifying the use case to include ::/0 by adding it as a comma delimited value, and also by creating a separate policy. However, no success.

Any ideas/solutions?

**Comment by kapilt** [comment]
hmmm.. not sure how much we've covered off on ipv6, do you have an example of the policy your using?

**Comment by hnakhla** [comment]
"Security Groups-Detect and Remediate Violations" use-case code from the documentation. 
Disclaimer: new to Cloud Custodian and yaml in general

I tried adding IPv6 value
    filters:
      - type: ingress
        Cidr:
            value: "0.0.0.0/0, ::/0"

Tried defining cidrIpv6 key ( key invalid/unknown )
    filters:
      - type: ingress
        CidrIpv6:
            value: "::/0"
or   
    filters:
      - type: ingress
        CidrIpv6: "::/0"

**Comment by zfLQ2qx2** [comment]
I tried the usual remediation policy with this:

`      - or:
        - type: ingress
          Cidr:
            value: 0.0.0.0/0
            op: eq
            value_type: cidr
        - type: ingress
          CidrIpv6:
            value: ::/0
            op: eq
            value_type: cidr`

It validates and does not crash, but only the ipv4 policy is removed.

**Comment by neybar** [comment]
I'm having this same issue.  My rules looks like this:

```
    filters:
      - type: ingress
        Ports: [22, 3389]
        Cidr:
          value:
            - "0.0.0.0/0"
            - "::/0"
          op: in
```

My ipv4 rules is removed just fine.  The ipv6 is still hanging out.

**Comment by kapilt** [comment]
ipv6 requires using CidrV6 to match, merged already

**Comment by arafatheds** [comment]
With this I can able to remove only ipv6 rule not the ipv4

    filters:
     - or:
        - type: ingress
          OnlyPorts: [80,443]
          Cidr:
            value: 0.0.0.0/0
            op: eq
            value_type: cidr
        - type: ingress
          OnlyPorts: [80,443]
          CidrV6:
            value: ::/0
            op: eq
            value_type: cidr
