### ISSUE TITLE
Removing AMIs

### ISSUE THREAD

**Issue by zfLQ2qx2** [cloud-custodian/cloud-custodian#2363]
I've come across a CI setup that has been generating AMIs on every git push for years, but noone has thought to clean it up.

I created a basic policy which will mark unused AMIs (using the unused filter) and then later deregister the AMIs that are marked. This seems to work well.

However, deleting AMIs is usually a two step process where first you have to deregister the AMI, then you have to remove the snapshots that the AMI pointed to. In the AMI resource code I don't see anything that removes the snapshots. In the EBS code I don't see anything that tests if the volume specified for the snapshot is valid. I think that unless snapshots are deleted when the AMI is deregistered you'd have to compute list of snapshots that are not in AMIs or of an exist volume to work out a list of what to remove (but this doesn't count snapshots of ELBs, I don't use that feature, so not sure what their metadata looks like).

**Comment by kapilt** [comment]
we generally just a separate policy for snapshot cleanup, ie. clean up snapshots missing a set of tags and older than n.

**Comment by kapilt** [comment]
a lot of filters get added in generically..

running `custodian schema ebs-snapshot.filters` will show the available, the `value` filter supports alot of options, in this context as a tag based exclusion ie. - "tag:backup": absent along with an age filter and then delete.

**Comment by zfLQ2qx2** [comment]
@kapilt If you have an example of how you are managing the AMI snapshots that is what I'm most interested in - even with the flexibility of the value I don't see how it could be done.

**Comment by sureshbk201** [comment]
@zfLQ2qx2  Are you still looking at a solution for this? I use the resources.json file produced by the first policy and pass it as input to the 2nd one. Cannot use this method with lambda as lambda doesn't support local storage well. Right now using this policy with crontab

`policies:
- name: del-60-automated
  resource: ami
  description: |
    Delete AMI that are older than 60 days and have been created by lambda job[finds it via ML_INSTANCE tag]
  filters:
       - "tag:ML_INSTANCE": present
       - "tag:retained_ami": absent
       - type: value
         value_type: age
         key: CreationDate
         value: 60
         op: greater-than

  description: |
    Deregisters AMIs that are older than 60 days and created by daily backup lambda
  actions:
    - deregister

- name: del-60-automated-snap
  resource: ebs-snapshot
  description: |
    Delete snapshots from previous policy resource json file
  filters:
    - type: value
      key: "SnapshotId"
      op: in
      value_from:
          url: file:/home/ubuntu/custodian/del-60-automated/resources.json
          format: json
          expr: "[].BlockDeviceMappings[].Ebs.SnapshotId"

  description: |
    Deletes snapshots associated with the AMIs deregistered by the del-60-automated policy

  actions:
     - delete`

**Comment by nitrocode** [comment]
@sureshbk201 what is the difference between using this

```
       - type: value
         value_type: age
         key: CreationDate
         value: 30
         op: greater-than
```

and using this

```
custodian schema ami.filters.image-age

Help
----

Filters images based on the age (in days)

:example:

.. code-block:: yaml

        policies:
          - name: ami-remove-launch-permissions
            resource: ami
            filters:
              - type: image-age
                days: 30
                op: greater-than
```

Is the latter new? or is the former better in some way?

**Comment by kapilt** [comment]
so removing amis should generally try to use the `unused` filter for safety on asg launch templates and launch configurations that are in use. 

i've put up a pull request which adds an optional flag to ami deregistration to auto delete the snapshots on the ami in #3599
