### ISSUE TITLE
Implement SendGrid as an MTA for cloud-custodian & c7n-mailer

### ISSUE THREAD

**Issue by johnt337** [cloud-custodian/cloud-custodian#2388]
## Background

The currently implementation of c7n-mailer relies on SES for AWS email notifications. While this work well in general for development and other non-critical workloads. Use of this utility raises a few concerns for my team based on previous issues encountered with production level workloads. 

1. Uses SES requires you either verify each sender/recipient address (or domain) or remove the account from sandbox mode.
2. Turning off SES sandbox mode opens up the account to potential abuse.
3. If an SES enabled account is blacklisted, the entire account's ability to send mail is hindered.
4. SES implements limits, an account generating a large amount of events can essentially "block" its self until an account's limit is increased if not properly pre-planned.

It makes sense that we should split out SendGrid functionality from https://github.com/capitalone/cloud-custodian/issues/2236 in general as it has use with other cloud providers, not just Azure.

## What problem are we trying to solve?

1. Enable high volume mailing notifications
2. Prevent administrative overhead associated with SES verifications
3. Prevent abuse and or account blacklisting associated with running SES in non-sandboxed mode.
4. Leverage SendGrid as the MTA to work around the aforementioned concerns.

## Proposed solution

- Implement SendGrid apart from https://github.com/capitalone/cloud-custodian/issues/2236 as a configuration.
- Add a configuration to either notify action, or the c7n-mailer config to leverage SendGrid as an alternative to SES.

**Comment by kapilt** [comment]
There's strong interest from the sprint crew fwiw.

**Comment by johnt337** [comment]
Hi, Just checking in, did this make it through the pycon sprint? 
If not, I would be willing to take a crack at submitting a PR.

**Comment by kapilt** [comment]
it did make it in, but for some reason thats not clear to me, its setup as specific to the azure provider.

**Comment by kapilt** [comment]
also fwiw, if you do setup ses (w/ dns keys) correctly, it can be used at scale.
