### ISSUE TITLE
Determine of a SG associated with an elb exists

### ISSUE THREAD

**Issue by ctippur** [cloud-custodian/cloud-custodian#2486]
Use case: A security group associated with a load balancer does not exist.

A common workflow wold be to check the sg for each elb and check if it exists (which is a diff resource)

Is there a way to achieve this?

**Comment by kapilt** [comment]
have you seen that case? is that generally possible? elbs generally have enis extant that will strongly reference their security group. we could put up an additional annotation via the related resource filter to record resources not found.

**Comment by kapilt** [comment]
elbs have sg filters now
