### ISSUE TITLE
UnicodeDecodeError when resolving in value_from

### ISSUE THREAD

**Issue by thisisshi** [cloud-custodian/cloud-custodian#2515]
```
$ python --version
Python 2.7.12
```

Traceback:
```
Traceback (most recent call last):
File "/src/c7n/policy.py", line 229, in run
resources = self.policy.resource_manager.resources()
File "/src/c7n/query.py", line 414, in resources
return self.filter_resources(resources)
File "/src/c7n/manager.py", line 90, in filter_resources
resources = f.process(resources, event)
File "/src/c7n/filters/core.py", line 403, in process
return super(ValueFilter, self).process(resources, event)
File "/src/c7n/filters/core.py", line 178, in process
return list(filter(self, resources))
File "/src/c7n/filters/core.py", line 390, in __call__
matched = self.match(i)
File "/src/c7n/filters/core.py", line 430, in match
self.v = values.get_values()
File "/src/c7n/resolver.py", line 132, in get_values
contents, format = self.get_contents()
File "/src/c7n/resolver.py", line 128, in get_contents
contents = text_type(self.resolver.resolve(self.data['url']))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 1098981: ordinal not in range(128)
```

I'm able to resolve the issue with encoding by explicitly casting the str to unicode like so:

```python
contents = text_type(unicode(self.resolver.resolve(self.data['url']), 'utf-8'))
```

I'm not very familiar with six.text_type and text encoding in general, but the explicit cast to unicode here seems to be compatible between 2/3 as python3 strings are unicode by default and let's us drop six.text_type in this line?

**Comment by thisisshi** [comment]
Actually in further discussion with @jonathana this seems to be a larger scope problem than just this single instance, yaml itself is defined as unicode based:

> YAML™ (rhymes with “camel”) is a human friendly, cross language, unicode based data serialization language designed around the common native structures of agile programming languages.

source: http://yaml.org/spec/1.2/spec.html

AWS RESTful responses return back unicode as well from what I've seen in inspecting the json payloads that come back

AWS tags are unicode as well: 
>Maximum key length: 128 Unicode characters
Maximum value length: 256 Unicode characters

source: https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/allocation-tag-restrictions.html

Same thing with GCP labels and their API from what I see
>Keys and values can contain only lowercase letters, numeric characters, underscores, and dashes. All characters must use UTF-8 encoding, and international characters are allowed.

source: https://cloud.google.com/resource-manager/docs/creating-managing-labels

Couldn't find information about text encoding in microsoft azure:
>The tag name can have a maximum of 512 characters and is case insensitive. Tag names created by Azure have prefixes of microsoft, azure, or windows. You cannot create tags with one of these prefixes.


source: https://docs.microsoft.com/en-us/python/api/azure.mgmt.resource.resources.v2017_05_10.operations.tagsoperations?view=azure-python

**Comment by kapilt** [comment]
is this resolved?
