### ISSUE TITLE
Perform action only if filtered resources are less 10% of total unfiltered

### ISSUE THREAD

**Issue by danieleb0101** [cloud-custodian/cloud-custodian#2532]
The scenario is the following:
I have a policy with an action to terminate ec2 intances, however I don't want to terminate more than 10% of the total running instances in my account each time.
For example in case I introduce a bug in my filters in the policy, and it matches 80% of the instances in my account, in the worst case I delete only 10% of the ec2 intances every time I run Cloud Custodian.
1. Is it possible to perform an action based on the number or ratio of filtered resources?

**Comment by thisisshi** [comment]
Right now you can use the `resource_count` filter to limit the blast radius of a policy by providing a count of resources, I would also like to see this extended to a percentage as that's more maintainable as an account goes up/down in resources-- the code for resource_count is in c7n/filters/core.py if you'd like to contribute :)

**Comment by danieleb0101** [comment]
Could I see an example how to use resource_count? 
where does it go? in filter? where exactly? 
Another important thing that can be improved (a lot) with CloudCustodian is documentation, every time I need something I have to do reverse engineering from the code, while having explorable docs which show usage for each statement/keyword/feature would help massively. I am sure there are a lot of things that I couldn't find in the docs that would make my life much easier but hard to spot/find.

**Comment by kapilt** [comment]
its at the policy level as a top level key, ie sibling to filters and actions.

**Comment by danieleb0101** [comment]
Thanks for the example

**Comment by kapilt** [comment]
max-resources supports percentages in addition to cardinality counts now
