### ISSUE TITLE
Azure Functions - Convert to using consumption model

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#2632]
Consumption pricing model for Azure Python Functions is not yet in public preview, however, when it becomes public we want to migrate over to it.  It represents some underlying differences which will enable us to scale to larger numbers of policies deployed.

I don't see any reason to invest any time in supporting both pricing models, we can switch entirely to consumption (although I suspect the code is very similar).

**Comment by jdogg89** [comment]
What are the relative costs of running a consumption pricing function versus running a small ASP? Obviously paying for what you use, and having the ability to scale are the advantages, but how would that compare to running a B1 instance monthly (at approximately a rate of $38)?

**Comment by stefangordon** [comment]
For many people consumption pricing will be free as there is no charge for the first million executions each month (with a cap on total memory gb-seconds).  There is a calculator here you can play with https://azure.microsoft.com/en-us/pricing/details/functions/ 

For example if your policy used 512mb of memory for a full 60 seconds you could still run it 13,000 times per month free.
