### ISSUE TITLE
Azure - Update Tag Action to work with Generic ARM Resource

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#2637]
Update `update_resource_tags` to use `update_by_id` instead of `create_or_update_by_id`.  This also means we stop calling `get` on the resource and only provide the field we want to change (Tags) as parameter. (maybe, what API version do we use?? Does it matter? Needs testing....)

Then remove the check on `armresource` and make sure it safely works if you run a policy of type `azure.armresource` and doesn't break stuff (like deleting NSG rules).

**Comment by aaron-schnieder** [comment]
actions.py was updated to use update_by_id in PR https://github.com/capitalone/cloud-custodian/pull/2727. However, this did not resolve this issue for all resources.

One of the issues we need to address is the way we are getting arm api_version to use
https://github.com/capitalone/cloud-custodian/blob/master/tools/c7n_azure/c7n_azure/session.py#L134
We are grabbing the latest api version returned by the azure arm resource management apis however, not all providers support that version. To tag all generic resources, we need to be more intelligent about the api_version and region to use when calling the generic ARM management API for a particular provider.

**Comment by stefangordon** [comment]
I think we can close this @aluong?
