### ISSUE TITLE
Cloudwatch metrics are not getting generated for all the policy

### ISSUE THREAD

**Issue by nidhigupta12** [cloud-custodian/cloud-custodian#2669]
i ran this policy and enabled the metrics "c7n-org run -c policy/accounts.yml -s output --metrics -u policy/vpcFlowLog.yml" , after this i can see one metrics with name "cloudmaid" on aws console . but when i ran the another policy with enabled metrics then i am not able to see any metrics for that policy. Scrrenshot attached
![image](https://user-images.githubusercontent.com/29300236/43209638-25b8f0d4-8ffb-11e8-9ec9-2dc82cb5a828.png)

**Comment by kapilt** [comment]
do you have the log output for the policy execution (with --verbose).

**Comment by nidhigupta12** [comment]
![image](https://user-images.githubusercontent.com/29300236/43213290-44ab5370-9004-11e8-8659-4d40b220ddc3.png)

**Comment by devops4solutions** [comment]
Any update ?

**Comment by kapilt** [comment]
metrics aren't omitted for lambda policies at provision time appears to be the delta, for lambda policies they are emitted as matching events are found and the policy is executed against.
