### ISSUE TITLE
Filtering "has-allow-all" for inline/managed policies

### ISSUE THREAD

**Issue by michael-misshore** [cloud-custodian/cloud-custodian#2673]
For an IAM resource (specifically users, groups, and roles), is it possible to find inline (and potentially managed) policies that have allow all definitions (or any type of policy statement for that matter)? I looked into the cross account filter to see if this was possible, but it seems like that filter doesn't give has-allow-all type functionality. Please let me know if i'm wrong here. 

My/our specific case here is that we have lambdas that have roles assigned to them. The roles have a managed and inline policy. Going through the `iam-role` resource, it seems the code only looks at the `AssumeRolePolicyDocument` attribute. Likewise, going through the `lambda` resource, the policy being referenced is the lambda policy with no references to the role policies.

It seems to make the most sense to filter these policies through their respective `iam` resources and using the `get-role-policy`, `get-group-policy`, etc. cli/boto commands to retrieve the attached policies for filtering. If this is a welcomed addition, I may be up for implementing.

Please let me know if I need to provide more feedback/context or if you have any questions.

**Comment by kapilt** [comment]
the new `check-permissions` filter allows this.

**Comment by christophetd** [comment]
@kapilt Can you clarify how this is supposed to be done? From your comment I tried:

```yaml
- name: iam-role-allow-all
  resource: aws.iam-role
  filters:
  - type: check-permissions
    match: allowed
    actions: ['*']
```

But this causes a validation error:

```
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid length for parameter ActionNames[0], value: 1, valid range: 3-inf
2020-09-01 22:15:48,575: custodian.commands:ERROR The following policies had errors while executing
 - iam-role-allow-all
```

My use-case is the same as @michael-misshore, identify roles with a policy allowing `*` on `*`, whether it's via an inline or managed policy
