### ISSUE TITLE
Integration with external tools

### ISSUE THREAD

**Issue by SyCode7** [cloud-custodian/cloud-custodian#2692]
I am new here, still trying to figure out things, i got quick two questions:

-  Is there a way to integrate cloud-custodian with external tools, maybe a REST API ? 

- How about visualization, something like ELK stack?

Many thanks.

**Comment by kapilt** [comment]
what does a rest api for a cli look like ? what sort of integration are you looking for? we drop data records and outputs and for aws they can go into s3/object storage, cloud watch metrics, cloud watch logs.. all of which can be picked up for dashboarding by elk, cloud watch dashboards, data dog, etc.

**Comment by SyCode7** [comment]
@kapilt what I am trying to ask is this, supposing I have an existing java application for monitoring my aws resources,  and I wanted to originate commands from this application to `cloud custodian`, is there a way to send such commands across directly ?
For dashboarding, I didn't know that the reports were dropped in s3, so this is clear now that you have mentioned. Thanks.

**Comment by kapilt** [comment]
It would be useful to have a worked complete example, are you generating policies, trying to use custodian as a library of actions?
