### ISSUE TITLE
azure - Access Control docs link to 404 RoleAssignment and RoleDefinition

### ISSUE THREAD

**Issue by billpratt** [cloud-custodian/cloud-custodian#2722]
The following documentation has links to RoleAssignment and RoleDefinition models that result in a 404 Not Found: http://capitalone.github.io/cloud-custodian/docs/azure/policy/resources/accesscontrol.html

It appears to be an issue on the Azure SDK for Python docs site. I have put [this issue](https://github.com/Azure/azure-sdk-for-python/issues/3111) in and will update this ticket once I hear back.

**Comment by yayitserica** [comment]
This issue has been logged by the Azure Docs team and bug has been created: https://dev.azure.com/ceapex/Engineering/_workitems/edit/100531 @dendeli-ms

**Comment by logachev** [comment]
We will remove links to the models from our docs, so closing this issue.
