### ISSUE TITLE
Feature request - Any plans to add DLM via custodian

### ISSUE THREAD

**Issue by kumarsiyer** [cloud-custodian/cloud-custodian#2753]
More info here --> https://boto3.readthedocs.io/en/latest/reference/services/dlm.html

**Comment by kapilt** [comment]
sounds good

**Comment by kapilt** [comment]
tbh, it feels like we already have this functionality covered with the builtins in custodian re snapshot. its pretty basic afaics on the features its adding.

**Comment by bclements** [comment]
I second this feature request. I planned on working on a patch to add it in.  The win is for the use cases where you have thousands of snapshots to manage and you may have hundreds of users hitting the api at the same time. There are times where we hit lambda execution timeouts and/or api limits when the custodian lambda runs.  Yes there are ways around it but the workarounds seem "hacky" and not clean.  Combining the cloud native lifecycle management service and cloud custodian, I can have one tool to write policies in but another to do all of the work for me that isn't beholden to timeouts or api limits.

**Comment by kapilt** [comment]
its a little unclear to me what dlm custodian integration looks like in the context of that use case. custodian isn't a provisioning tool, so if your using dlm, thats great re don't have a set of custodian policies for snapshotting. i went ahead with a standard resource but its unclear thats of any particular utility on its own.
