### ISSUE TITLE
docs - goo.gl decomission

### ISSUE THREAD

**Issue by thisisshi** [cloud-custodian/cloud-custodian#2776]
Consider moving links in docs off of goo.gl as it's being decommissioned soon

https://goo.gl/

>Starting March 30, 2018, we will be turning down support for goo.gl URL shortener. From April 13, 2018 only existing users will be able to create short links on the goo.gl console. You will be able to view your analytics data and download your short link information in csv format for up to one year, until March 30, 2019, when we will discontinue goo.gl. Previously created links will continue to redirect to their intended destination. Please see this blog post for more details.

**Comment by kapilt** [comment]
another goo.gl service bites the dust...

**Comment by kapilt** [comment]
fixed in #3511
