### ISSUE TITLE
kind of question for multiple actions in a policy.

### ISSUE THREAD

**Issue by nitinitare** [cloud-custodian/cloud-custodian#2858]
If i have multiple action items in a policy then how the actions will be performed, all actions at once or one by one.
resource is ec2.
example : 
 actions:
     - type: remove-tag
       tags:
        - LastStoppedBy
     - type: auto-tag-user
       tag: LastStoppedBy1
     - type: rename-tag
       old_key: LastStoppedBy1
       new_key: LastStoppedBy

These 3 actions will be performed parallel or simultaneously. If the answer is parallel how we can perform it serially??

**Comment by thisisshi** [comment]
All actions and filters are performed serially, i.e. in order.

**Comment by nitinitare** [comment]
But it's not happening. If possible can you please check the above scenario and see the result.

**Comment by kapilt** [comment]
its serial, but the cache representation is the same, actions act on the same resource representation that was filtered on regardless of state changes by other actions. also there is no need to remove a tag if just overwriting it.

**Comment by nitinitare** [comment]
But it is not overwriting that's why chose to remove and tag it again.
