### ISSUE TITLE
Policies for Ec2 Instance which are Created by ASG

### ISSUE THREAD

**Issue by agaur123** [cloud-custodian/cloud-custodian#2875]
Hi, I want to write one policy for my Ec2 instance which are created by using ASG actually, I am trying to filter all those Instances which are missing my date tag and the tag which is given by asg and atlast it should eliminate all those resources after some X days. If there any instances which is matching with this filters than automatically those policies should directly apply to that ASG which is attached with the Instance.

**Comment by kapilt** [comment]
why not just have a policy on the asg directly and its tags, its those tags which propagate to the instance.
