### ISSUE TITLE
has_servicelevel_allow_all_policy filter added to iam-policy resource

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#2956]
Same as the existing has_allow_all_policy filter, but instead of all services, scoped to a specific parameterized service.

This would enable writing a policy to support the KMS Best Practice "This includes ensuring that you do NOT include kms:* permissions in an IAM policy." which is on page 4 of https://d1.awsstatic.com/whitepapers/aws-kms-best-practices.pdf

**Comment by kapilt** [comment]
the new `check-permissions` filter allows this.
