### ISSUE TITLE
Regex tag value evaluate with current hour - offhour/onhour policy

### ISSUE THREAD

**Issue by ibasu** [cloud-custodian/cloud-custodian#2976]
Is it possible to parse regex expression in the filter section of a policy and evaluate against current hour for a scheduled cron policy?
E.g 
ASG1 => Tag:Custodian = 7-19|0-4
ASG2 => Tag:Custodian = 8-20|0-5

Is it possible to suspend on 19th hour and 20th hour for ASG1 and ASG2 respectively?

**Comment by kapilt** [comment]
offhour filters support resource supplied values for offhours. see the offhour docs
https://www.capitalone.io/docs/quickstart/offhours.html#offhours
