### ISSUE TITLE
RDS Stop Not working - SQL

### ISSUE THREAD

**Issue by mukavik** [cloud-custodian/cloud-custodian#3000]
Hi 

I am trying to stop RDS instance, based on certain filters. I see the Lambda runs without error but it does not stops the instance (SQL). Do not understand the logs"[DEBUG] 2018-10-15T22:42:14.920Z 8f663a52-d0cb-11e8-9572-5db93c0eb5c4 metric:ApiCalls Count:0 policy:terminate-unencrypted-public-rds-new restype:rds". 

Thanks
Avik

**Comment by kapilt** [comment]
you'll have to produce more of the logs (sanitized, no account numbers) and the policy to help us understand what your seeing. the log line your reporting is an output (only on trunk/master) noting the number of api calls the filters/actions of the policy took.

**Comment by kapilt** [comment]
rds databases can't be stopped for all cases. the rds api only supports `stop` for databases that are already available. Trying to do this in a lambda on create means the database is still in the 'creating' and is not eligible for stop. I'll look at adding some additional logging around that.

**Comment by kapilt** [comment]
re rds stop limitations see docs https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_StopInstance.html the lifecycle limitations aren't explicitly described, but several others are.

**Comment by mukavik** [comment]
OK i get it now. So i should not be triggering on create DB but something other. Is there are way to trigger the Lambda on create but put it into sleep for time till the instance is up and running?

**Comment by kapilt** [comment]
rds can take a long time to come up fully, there's also no way to correct the problem without alot of manual effort (snapshot, encrypt snapshot, restore, etc), so deleting at create is reasonable since there is no data. else you have to move from execution-mode cloudtrail to config-rule, periodic, or poll with an additional state/status filter on available.

**Comment by mukavik** [comment]
OK, So may be I will try using the action mark-for-op on RDS create and then have a following lambda that would check if instance is running and has a mark-for-op tag and stop those.
