### ISSUE TITLE
gcp: BigQuery resource missing

### ISSUE THREAD

**Issue by bclements** [cloud-custodian/cloud-custodian#3007]
This is a feature request for a BigQuery resource. As of now there is no BigQuery resource available within Cloud Custodian to execute a policy such as this:

policies:
  - name: qigquery-test
     resource: gcp.bigquery

Information about the BigQuery API can be found at: https://cloud.google.com/bigquery/docs/reference/rest/v2/

It would be nice to include both datasets and tables in the functionality but most use cases that most enterprises will want to run custodian against will only deal with datasets.

**Comment by kapilt** [comment]
so big table would be both tables and data sets.. mostly i would assume the later due to the ability to make data sets public

**Comment by bclements** [comment]
Mostly datasets. That's what most of our controls are based around but this particular enhancement request is just for the core bigquery gcp resource.

**Comment by kapilt** [comment]
merged in #3280
