### ISSUE TITLE
Expand aws.ecr to provide image tag filtering, lifecycle policy actions

### ISSUE THREAD

**Issue by IDT-kcrook** [cloud-custodian/cloud-custodian#3016]
Feature Request

ECR policy runs only return the following items:
```
  {
    "registryId": "ACCOUNT_ID", 
    "repositoryName": "MY_REPO_NAME", 
    "repositoryArn": "arn:aws:ecr:us-west-2:xxxxxxxxxxx:repository/MY_REPO_NAME", 
    "createdAt": "2017-11-22T12:14:58-07:00", 
    "repositoryUri": "xxxxxxxxxxx.dkr.ecr.us-west-2.amazonaws.com/MY_REPO_NAME"
  }
```

Currently it appears that one can only invoke a lambda function and delete lifecycle policy statements. For cleaning up ECRs in development accounts, it would be helpful to be able to do the following:
* filter on ECR tags
* Put lifecycle policies that expire images without tags

**Comment by FireballDWF** [comment]
Prior to announcement yesterday https://aws.amazon.com/about-aws/whats-new/2018/12/amazon-ecr-now-allows-repository-tagging/ ECR repo's could not be tagged, but now that AWS supports it, support can be added to custodian.

**Comment by kapilt** [comment]
lifecycle management is already supported, leaving this as ecr tags.
