### ISSUE TITLE
lightsail resource support?

### ISSUE THREAD

**Issue by ssteo** [cloud-custodian/cloud-custodian#3050]

**Comment by kapilt** [comment]
lightsail is effectively an abstraction on top of the underlying apis for ec2/rds/etc. while it has its own api, the resources created with lightsail should still show up against the underlying resource apis.

**Comment by ssteo** [comment]
Hi @kapilt apparently that's not the case. Initially I thought the same too. I've tested created several Lightsail instances in the same region but in my EC2/RDS section I can't see them. they are totally isolated resource as it's own product though.

**Comment by ssteo** [comment]
Without the support of Lightsail resource can be a bit of issue when leveraging Cloud Custodian for compliance or security scan, because in many use cases; CC is used to enumerate EC2 instances with outdated AMI or outside of EU region (data protection law), etc.

**Comment by kapilt** [comment]
hmm.. okay i hadn't realized that, yeah we can add in support for lightsail resources.

**Comment by kapilt** [comment]
for most orgs simply restricting lightsail in iam is going to be the simplest path forward.
