### ISSUE TITLE
c7n-mailer [0.3.3] - No module named urllib3

### ISSUE THREAD

**Issue by jonotto** [cloud-custodian/cloud-custodian#3139]
I removed the c7n-mailer Lambda function and redeployed using the new v0.3.3. I am now seeing this error in the CloudWatch logs during runs.

[ERROR]	2018-11-14T19:01:27.535Z	afcd48a8-e83f-11e8-a7dc-6f4a34982269	Error starting mailer MailerSqsQueueProcessor(). 
Error: No module named urllib3 

Traceback (most recent call last):
File "/var/task/c7n_mailer/handle.py", line 46, in start_c7n_mailer
mailer_sqs_queue_processor.run(parallel)
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 128, in run
self.process_sqs_message(sqs_message)
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 173, in process_sqs_message
from .slack_delivery import SlackDelivery
File "/var/task/c7n_mailer/slack_delivery.py", line 16, in <module>
import requests
File "/var/task/requests/__init__.py", line 43, in <module>
import urllib3
ImportError: No module named urllib3

**Comment by mwkaufman** [comment]
Having the same issue with the Slack integration. Looking at the history it looks like urllib3/idna/chardet/certifi were briefly in deploy.py between May 5 and May 15.

Added here: https://github.com/capitalone/cloud-custodian/commit/ad7877888f53d58d06f2ad993a5ac173940c4945#diff-e7b16ce32846452561268dcd399eb20e

Removed here: https://github.com/capitalone/cloud-custodian/commit/99502eaeed416f5ab3f2db4c916d84e5e0bbee60#diff-e7b16ce32846452561268dcd399eb20e

**Comment by Chan9390** [comment]
Having the same issue.

**Comment by bensomogyi** [comment]
I'm getting the same, however reverting some of the files did not seem to help for me.  @Chan9390  was this what you did? 

git clone git://github.com/capitalone/cloud-custodian.git
cd cloud-custodian 
git checkout ad78778 -- \
        c7n/cli.py \
        c7n/mu.py \
        c7n/output.py \
        tests/common.py \
        tests/test_cli.py \
        tests/test_handler.py \
        tests/test_output.py \
        tools/c7n_mailer/c7n_mailer/deploy.py

**Comment by nerdyness** [comment]
I can confirm what @Chan9390 says - changing the c7n-mailer's `deploy.py` to look like this:

```
 42 def get_archive(config):
 43     archive = PythonPackageArchive(
 44         'c7n_mailer',
 45         # core deps
 46         'jinja2', 'markupsafe', 'ruamel', 'ldap3', 'pyasn1', 'redis',
 47         # transport datadog - recursive deps
 48         'datadog', 'simplejson', 'decorator',
 49         # transport slack - recursive deps
 50         'slackclient', 'websocket',
 51         # requests (recursive deps), needed by datadog and slackclient
 52         'requests', 'urllib3', 'idna', 'chardet', 'certifi')
```
and doing a `pip install simplejson` did the trick for me. I now get Slack notifications as expected 👍 Thanks for this

**Comment by davidclin** [comment]
Hoping this gets fixed soon. I'm in the middle up updating all my lamda based policies to support AWS Security Hub via the ec2 post-finding action and came across this very exact issue. Fortunately, the workaround mentioned by Chan9390 and confirmed by nerdyness saved us today and we're getting Slack notifications again.

**Comment by davidclin** [comment]
Thank you. Slack messaging is up and running again and we successfully deployed all our Lambda policies with AWS Security Hub integration along with our existing Slack and email messages. Appreciate the quick response!
