### ISSUE TITLE
aws.ecs - tagging

### ISSUE THREAD

**Issue by thisisshi** [cloud-custodian/cloud-custodian#3147]
ECS now supports tags: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html#ECS.Client.tag_resource

Currently all clusters can be tagged, tasks/services/container-instances can only be tagged if they're opted into the new arn format

**Comment by kapilt** [comment]
additional context on ecs arn, its differential on arn for at least a year due to the migration period https://aws.amazon.com/blogs/compute/migrating-your-amazon-ecs-deployment-to-the-new-arn-and-resource-id-format-2/

**Comment by kapilt** [comment]
went ahead and did everything but task-definition which unfortunately is a bigger stretch as it will require a bit more refactoring due to how ecs tags were exposed. i'll leave this open for now, as we'll still need to add tag actions.
