### ISSUE TITLE
Update Lambda deployments via mu to default to Python 3.7

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#3161]
According to https://pythonclock.org/ support will end 1/1/2020, which is starting to get close enough that upgrading mu.py to at least default of the python 3.7 runtime should be done.

**Comment by kapilt** [comment]
thanks for filing we should definitely start going this way.  i didn't even realize lambda had a 3.7 runtime available. 

there's one last item on 3x that we need to cover off on #3087, its more user experience on the cli though. 

we'll also need to do some testing on migration and cross uploads from different cli language runtimes, probably a manual effort.

**Comment by FireballDWF** [comment]
That news was so 24 hours ago ;-). https://aws.amazon.com/about-aws/whats-new/2018/11/aws-lambda-supports-python-37/
