### ISSUE TITLE
Azure - Event Grid Fuctions - Sample policy does not work

### ISSUE THREAD

**Issue by jdogg89** [cloud-custodian/cloud-custodian#3172]
### Description: 
Running an event grid function successfully deploys all the necessary components to run the functions in a new resource group. When setting up the event grid with the following policy in the docs: 
#### Policy:
```
policies:
    - name: tag-key-vault-creator
      resource: azure.keyvault
      mode:
        type: azure-event-grid
        events: [{
            resourceProvider: 'Microsoft.KeyVault/vaults',
            event: 'write'
          }]
      filters:
        - "tag:CreatorEmail": null
      actions:
        - type: auto-tag-user
          tag: CreatorEmail
```
The policy appears to not actually tag key vaults in the subscription, even a freshly created keyvault in that same RG as the other event grid components. When looking into App insights, this may be expected (as I'm newer to using app insights) but the sample telemetry appears to show the custodian policy running constantly, 1-2 times per second. Let me know what other detail I can provide.

### Desired outcome: 
* Sample policy executes successfully and resource tagged
* Any additional documentation on running event grid functions that may be needed for additional steps beyond initial deployment

**Comment by kapilt** [comment]
^ @aluong @stefangordon @logachev @erwelch  any ideas?

**Comment by stefangordon** [comment]
Hey @jdogg89 this was an early implementation pending event grid filtering support (which came out a few weeks ago) - so it had to see every message instead of subscribing to a specific one.   The functions self-filters but of course this doesn't scale well to large subscriptions.

We are going to try to get the filtering implemented as soon as possible so it uses the new features to subscribe to only the correct events.

Of course a separate question remains as to why it isn't seeing the event you'd like - I'll have to look into that a bit more.

**Comment by stefangordon** [comment]
https://github.com/capitalone/cloud-custodian/pull/3182#pullrequestreview-179603713  

This will get proper filtering in place which may alleviate the reliability issues you saw, then we can investigate further if its still not working on those KV.  I expect it to be merged this morning sometime.

**Comment by jdogg89** [comment]
Just updated to the latest code and I can see that the API calls are not going constantly now, but resources still are not getting tagged. from the logs in app insights it looks like it is finding resources that are missing the tags, and it pulls a message from the storage queue but nothing happens regarding tagging of either a VM or a key vault... (based on examples in the docs).

**Comment by stefangordon** [comment]
If you can grab any log from a run where something like that happened it might be helpful.    If you have configured to log to blob storage it might look something like this

![image](https://user-images.githubusercontent.com/4087345/49247800-04d95f80-f3cd-11e8-8d3a-7d6139da6c4a.png)

**Comment by stefangordon** [comment]
Oh your logs and results are probably going to a temp directory on the container then.  If you want to aggregate them all in a storage account (any storage account in any subscription for which your service principal has `Blob Data Contributor` permissions) you can add it to the policy `execution-options` with an `azure://` prefix - e.g.:

```
policies:
  - name: stopped-vm
    mode:
        type: azure-periodic
        schedule: '0 0 * * * *'
        provision-options:
          servicePlan:
            name: functionshost
        execution-options:
          output_dir: azure://yourstorageaccount.blob.core.windows.net/custodian
     resource: azure.vm
     filters:
      - type: instance-view
        key: statuses[].code
        op: not-in
        value_type: swap
        value: "PowerState/running"
```

The docs for using blob storage at the command line show some of the advanced formatting options:
https://capitalone.github.io/cloud-custodian/docs/azure/advanced/bloboutput.html#azure-bloboutput

**Comment by jdogg89** [comment]
@stefangordon I was not aware of the execution options, or the schedule ability right within the policy, I haven't seen an example like this in the examples but perhaps I didn't dig enough (this is awesome, and may make me think some of my policies in cron schedule in k8s) I'll make this change and see what the output is in the output.

**Comment by stefangordon** [comment]
👍  That one is from this page with general overview of functions features https://capitalone.github.io/cloud-custodian/docs/azure/advanced/azurefunctions.html

**Comment by jdogg89** [comment]
Nothing appears to be written to the blob with the new policy:
```
policies:
  - name: azure-auto-tag-creator
    mode:
      type: azure-event-grid
      events: [{
          resourceProvider: 'Microsoft.Compute/virtualMachines',
          event: 'write'
          }]
      provision-options:
        servicePlan:
          name: cloud-custodian
      execution-options:
        output_dir: azure://myblob.blob.core.windows.net/log-folder
    resource: azure.resourcegroup
    description: |
      Tag all existing virtual machines with the 'CreatorEmail' tag using ARM events.
    actions:
     - type: auto-tag-user
       tag: CreatorEmail
```
The custodian service principal has the contributor role and the Blob Data Contributor role at the subscription level, looking at the app insights log it shows a 403, so not sure if that's referring to writing to the blob store or if that's for trying to tag the vm:
```
Client-Request-ID=XXXX Retry policy did not allow for a retry: Server-Timestamp=Fri, 30 Nov 2018 03:25:28 GMT, Server-Request-ID=XXXXX, HTTP status code=403, Exception=This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.RequestId:XXX</Message></Error>.
```
I'm guessing its some type of AAD issue?

**Comment by jdogg89** [comment]
I deleted the Resource group that is provisioned when not specifying one in the policy and spun up an new one, ensuring that the credentials that were supplied were correct, corresponding to the Cloud-custodian service principal that should have the correct AAD roles. When the functions execute in Azure, from the output I'm assuming that this is a permission issue of whatever SP the function is running under doesn't have the correct permissions? The function starts up correctly when I create a new vm, it sees that, but when it goes to perform the action, the error results. Nothing is written to blob storage and nothing is tagged:
```
prop__{OriginalFormat}
{ "Origin": "Worker", "MessageType": "RpcLog", "WorkerId": "XXSX", "Message": { "RequestId": "XXX", "RpcLog": { "InvocationId": "XXX", "Category": "custodian.azure.functions", "Level": "Error", "Message": "Unable to process policy: azure-auto-tag-creator :: This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure\n<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:XXXX\nTime:2018-11-30T13:38:01.1505006Z</Message></Error>", "EventId": "", "Properties": "" }, "ContentCase": "RpcLog" }, "Name": "RpcLog", "Source": "Rpc" }
```

**Comment by stefangordon** [comment]
The policy above looks like there is a mismatch in resource types `resource: azure.resourcegroup` while events are looking at VM so probably you would not end up with any resources, or if you do the type is going to be mismatched which might result in the errors.

The easiest place to see the log lines that you'd normally see at your console (if storage output is broken) is the "monitor" view of the Azure Function - you can drill into the actual log lines for each run, e.g. 

![image](https://user-images.githubusercontent.com/4087345/49310882-6adcea00-f494-11e8-8c6e-d0f8c9a69b1a.png)

I'm wondering if we are failing to write to storage if custodian exits in an error case, we'll have to track that down.

**Comment by jdogg89** [comment]
yeah I caught that previously, also tried executing a policy where the resource was listed as ```resource: azure.vm``` and the same logs appear in the azure monitor invocation details you point out

**Comment by jdogg89** [comment]
This weekend I've been testing in my personal account with the above policy ^ and with ```resource: azure.vm``` and get the following message: 
```
prop__{OriginalFormat}
{ "Origin": "Worker", "MessageType": "RpcLog", "WorkerId": "XXXX", "Message": { "RequestId": "XXXX, "RpcLog": { "InvocationId": "", "Category": "custodian.azure.actions.auto-tag-user", "Level": "Error", "Message": "Principal type of event cannot be determined.", "EventId": "", "Properties": "" }, "ContentCase": "RpcLog" }, "Name": "RpcLog", "Source": "Rpc" }
```
I've gone into azure AD and given it every type of permission possible to every api, and the service principal running this has Contributor, storage blob contributor, storage queue contributor at the subscription level, with that in place I wouldn't think its an AAD issue, and doing so in my personal acct, that would remove any type of policy set at the EA level of my company causing it not to work.

If there's any other log messages you're looking for let me know and I can enter all of them.

**Comment by stefangordon** [comment]
Good info, agreed seems to rule out basic permissions errors - trying to get someone to look into this more ASAP

**Comment by jdogg89** [comment]
@aluong I followed all the steps and ran the same policy you have listed above. Unfortunately, when running the cli command to create a new resource group, the new RG is not tagged. Here's the queue message: 
```

Id
XXXX
Message body
{ "subject": "/subscriptions/XXXX/resourcegroups/test2", "eventType": "Microsoft.Resources.ResourceWriteSuccess", "eventTime": "2018-12-10T18:44:04.451911Z", "id": "XXXX", "data": { "authorization": { "scope": "/subscriptions/XXXX/resourcegroups/test2", "action": "Microsoft.Resources/subscriptions/resourcegroups/write", "evidence": { "role": "Subscription Admin" } }, "claims": { "aud": "https://management.core.windows.net/", "iss": "https://sts.windows.net/xxxx/", "iat": "xxxx", "nbf": "xxx", "exp": "xxx", "http://schemas.microsoft.com/claims/authnclassreference": "1", "aio": "xxxx", "altsecid": "1:live.com:XXXXXXX", "http://schemas.microsoft.com/claims/authnmethodsreferences": "pwd", "appid": "xxx", "appidacr": "0", "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress": "me@myemail.com", "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname": "xxx", "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname": "xxxx", "groups": "xxxx", "http://schemas.microsoft.com/identity/claims/identityprovider": "live.com", "ipaddr": "xxxxxxxx", "name": "Account", "http://schemas.microsoft.com/identity/claims/objectidentifier": "xxxxxxx", "puid": "xxxxxxx", "http://schemas.microsoft.com/identity/claims/scope": "user_impersonation", "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier": "xxxxxxxx", "http://schemas.microsoft.com/identity/claims/tenantid": "xxxxxx", "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name": "live.com#me@myemail.com", "uti": "xxxxx", "ver": "1.0", "wids": "xxxxxx" }, "correlationId": "xxxxxx", "httpRequest": { "clientRequestId": "xxxx", "clientIpAddress": "xxxxxx", "method": "PUT", "url": "https://management.azure.com/subscriptions/xxxxxx/resourcegroups/test2?api-version=2018-05-01" }, "resourceProvider": "Microsoft.Resources", "resourceUri": "/subscriptions/xxxxxx/resourcegroups/test2", "operationName": "Microsoft.Resources/subscriptions/resourcegroups/write", "status": "Succeeded", "subscriptionId": "xxxxx", "tenantId": "xxxxxx" }, "dataVersion": "2", "metadataVersion": "1", "topic": "/subscriptions/xxxxx" }
Insertion time
Mon, 10 Dec 2018 18:44:33 GMT
Expiration time
Mon, 17 Dec 2018 18:44:33 GMT
Dequeue count
0

```

**Comment by aluong** [comment]
Interesting. I see the issue now. It's because your evidence property is missing some attributes that we expect when parsing our the user principal.
```
"authorization": {
      "scope": "/subscriptions/XXXX/resourcegroups/test2",
      "action": "Microsoft.Resources/subscriptions/resourcegroups/write",
      "evidence": {
        "role": "Subscription Admin"
      }
```

Just to make sure things work, can you try an action that has a static tag value?
```
    actions:
    - type: tag
      tag: Hello
      value: World
```

**Comment by aluong** [comment]
From my investigation, if the action is done by a `Service Administrator` you get a principal that has the `"role": "Subscription Admin"`. I will look into adding support for this in the AutoTagUser action. I would assume if you were to create the resource group via an identity that is not a `Service Administrator`, you will not run into this error. Try creating a new service principal and login into the Azure CLI with it as described [here](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest#sign-in-using-the-service-principal). Then create a resource group using it, I would suspect there will be no issue. 

### Service Administrator in a Susbcription 
![image](https://user-images.githubusercontent.com/1683309/49765195-91fe9d00-fc86-11e8-85d3-717bfd297091.png)

**Comment by jdogg89** [comment]
So what you're saying is that any resources created by a service administrator, in this case the test resource group that I create via me being logged with my personal credentials in the CLI, will run into these issues... that seems like a bug to be resolved, no?

**Comment by stefangordon** [comment]
If this doesn't solve the issue let us know and we will reopen.

**Comment by jdogg89** [comment]
It appears that using the original service principal I have for Cloud-custodian, I'm still not able to run auto-tag-user with the following policy. I pulled the latest from source and ran the following in a new python3 virtualenv: 

```
policies:
  - name: azure-auto-tag-creator
    mode:
      type: azure-event-grid
      events: [ResourceGroupWrite]
    resource: azure.resourcegroup
    description: |
      Tag all new RG with the 'CreatorEmail' tag using ARM events.
    actions:
     - type: auto-tag-user
       tag: CreatorEmail
```
#### Here is the error:
```
prop__{OriginalFormat}
{ "Origin": "Worker", "MessageType": "RpcLog", "WorkerId": "XXXXXXX", "Message": { "RequestId": "XXXXXXX", "RpcLog": { "InvocationId": "", "Category": "custodian.azure.actions.auto-tag-user", "Level": "Error", "Message": "Principal type of event cannot be determined.", "EventId": "", "Properties": "" }, "ContentCase": "RpcLog" }, "Name": "RpcLog", "Source": "Rpc" }
```
Again, the following policy does tag a new RG.:
```
policies:
  - name: tag-resource-groups2
    mode:
      type: azure-event-grid
      events: [ResourceGroupWrite]
      provision-options:
        servicePlan:
          name: eg-test-rg-tagging
    resource: azure.resourcegroup
    actions:
    - type: tag
      tag: CreatorEmail
      value: me@me.com

```
At this point this isn't affecting me and what I want to do, but it appears the auto-tag-user type still isn't working.

**Comment by jdogg89** [comment]
Each time I've tested this, I've actually created brand new resources for everything, brand new cloud-custodian resource group, new function, new policy, but just to humor this, I'll try it one more time and give it a good 20 min after deploying the policy to let it run. I'll keep you updated...

**Comment by jdogg89** [comment]
@aluong here is the message taken from the queue, scrubbed: 
```
Id
XXXXXX
Message body
{ "subject": "/subscriptions/XX/resourcegroups/test3", "eventType": "Microsoft.Resources.ResourceWriteSuccess", "eventTime": "2018-12-17xx", "id": "XX", "data": { "authorization": { "scope": "/subscriptions/XX/resourcegroups/test3", "action": "Microsoft.Resources/subscriptions/resourcegroups/write", "evidence": { "role": "Contributor", "roleAssignmentScope": "/subscriptions/XX", "roleAssignmentId": "xxx", "roleDefinitionId": "xxx", "principalId": "xx", "principalType": "Group" } }, "claims": { "aud": "https://management.core.windows.net/", "iss": "https://sts.windows.net/xx/", "iat": "xx", "nbf": "xx", "exp": "xx", "http://schemas.microsoft.com/claims/authnclassreference": "1", "aio": "xx", "http://schemas.microsoft.com/claims/authnmethodsreferences": "pwd", "appid": "xx", "appidacr": "0", "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname": "xx", "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname": "xx", "groups": "xx, "ipaddr": "xxxx", "name": "XX", "http://schemas.microsoft.com/identity/claims/objectidentifier": "xx", "onprem_sid": "xx", "puid": "xx", "http://schemas.microsoft.com/identity/claims/scope": "user_impersonation", "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier": "xx", "http://schemas.microsoft.com/identity/claims/tenantid": "xx", "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name": "xx", "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn": "xx", "uti": "xx", "ver": "1.0" }, "correlationId": "XX", "httpRequest": { "clientRequestId": "xx", "clientIpAddress": "xx", "method": "PUT", "url": "https://management.azure.com/subscriptions/XX/resourcegroups/test3?api-version=2018-05-01" }, "resourceProvider": "Microsoft.Resources", "resourceUri": "/subscriptions/XX/resourcegroups/test3", "operationName": "Microsoft.Resources/subscriptions/resourcegroups/write", "status": "Succeeded", "subscriptionId": "XX", "tenantId": "xx" }, "dataVersion": "2", "metadataVersion": "1", "topic": "/subscriptions/XX" }
Insertion time
Mon, 17 Dec 2018 19:27:11 GMT
Expiration time
Mon, 24 Dec 2018 19:27:11 GMT
Dequeue count
0

```

**Comment by aluong** [comment]
I see that you are using a different principal here than the one you were using before. You are using a `group`. We can look into adding default logic to attempt look for the **emailaddress** claim first and then the **name** claim before we stop processing.

     "evidence": {
        "role": "Contributor",
        "roleAssignmentScope": "/subscriptions/XX",
        "roleAssignmentId": "xxx",
        "roleDefinitionId": "xxx",
        "principalId": "xx",
        "principalType": "Group"
      }

**Comment by stefangordon** [comment]
I actually wasn't aware you could get a principal type group to show up there.  Interesting.

**Comment by jdogg89** [comment]
I must have tested on my personal account previously, what I pasted in 2 days ago was from a corporate account
