### ISSUE TITLE
ssm/send-command

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#3174]
Purpose is to have an action which results in a call to ssm:SendCommand with the ability to pass DocumentName so scripts can be executed on these ec2 instances based on filters on the ec2 resource.

Potential usage example: in reaction to mode type: ec2-instance-state where events == running, the SendCommand is invoked with DocumentName=
            "Name": "AmazonInspector-ManageAWSAgent" to install Inspector and/or
            "Name": "AWS-RunInspecChecks" to run checks

**Comment by kapilt** [comment]
another interesting usage for memory acquisition on compromised server via sssm command https://github.com/ThreatResponse/ssm-acquire

**Comment by thisisshi** [comment]
closing, resolved in: https://github.com/cloud-custodian/cloud-custodian/pull/3473
