### ISSUE TITLE
0.8.32.1 release zip seems to be incorrect

### ISSUE THREAD

**Issue by eamonnfaherty** [cloud-custodian/cloud-custodian#3202]
I am trying to grab mugc.py version 0.8.32.1 but the release on the releases page seems to not include it - link https://github.com/cloud-custodian/cloud-custodian/archive/0.8.32.1.zip

**Comment by kapilt** [comment]
Apologies, the last repo tag got created on a gh pages branch, we’ll be
cutting a new release this week.

**Comment by eamonnfaherty** [comment]
np,  you are doing a great job on the product!
