### ISSUE TITLE
Documentation not available

### ISSUE THREAD

**Issue by sergiuradulea** [cloud-custodian/cloud-custodian#3205]
Hi,

The link for the docs is dead. i.e. http://capitalone.github.io/cloud-custodian/docs/

I get a site not found from the github pages : "404 There isn't a GitHub Pages site here."

<img width="881" alt="screen shot 2018-12-04 at 1 35 48 pm" src="https://user-images.githubusercontent.com/9967572/49445322-8ebc6a80-f7c9-11e8-8c94-302860318af8.png">

**Comment by kumarsiyer** [comment]
Try http://cloudcustodian.io/

**Comment by kapilt** [comment]
We just moved top level orgs, unfortunately github redirects do not extend
to github pages, if you do see any extant broken links please let us know
where you found them so we can try and correct.
