### ISSUE TITLE
Search for "word" in Resource name

### ISSUE THREAD

**Issue by mason67git** [cloud-custodian/cloud-custodian#3207]
Hi,

So I'm trying to make a rule to delete policies that don't have the team's name in it. 

EG, people in the company constantly make policies without there name in, and this is an issue. I can't search for tags either since policies can't be tagged.

**Comment by kapilt** [comment]
you mean custodian policies?  custodian policies can be tagged, and the policy lambdas /serverless functions can also be tagged.

it sounds almost like you want a meta policy to manage other policies, what would the source for those policies be? files/repos/ ?

**Comment by kapilt** [comment]
generally speaking we try to embrace compliance as code via git repos which track on audit of who/what/when where wrt to policy authoring and changes.

**Comment by kapilt** [comment]
i'm still unclear what this is in reference to, and there hasn't been a response to previous queries, so closing out.
