### ISSUE TITLE
Azure - Include a nice default Log Analytics view 

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#3211]
A prerequisite is #2898 

Once we have proper metrics/logging with insights lets make up a nice Analytics view to monitor custodian.  At a minimum the view supports exporting as an ARM template we can include in the repo for the user as an example.

https://docs.microsoft.com/en-us/azure/azure-monitor/platform/view-designer

**Comment by yayitserica** [comment]
### ACCEPTANCE CRITERIA

1. Create a default Analytics view to monitor custodian.
2. The view should be exportable as an ARM template and included in user repos.

FYI @stefangordon do you still consider this a medium scope item?

**Comment by stefangordon** [comment]
We have decided to leverage the new workbooks feature in #4849
