### ISSUE TITLE
aws - new generic resource action "invoke-stepfunction" enhancement

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#3225]
Enhancement which behaves just like action invoke-lambda but invokes (aka starts execution of) step function state machines for use cases which need sequencing and conditional logic which is more easily implemented in step functions.  

Doc hint: See https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/stepfunctions.html#SFN.Client.start_execution

**Comment by kapilt** [comment]
step functions have fairly limited size limits for inputs, invoke lambda we do as a bulk op, in this context the step function invoke per resource?

**Comment by kapilt** [comment]
limit is 32k for per input https://docs.aws.amazon.com/step-functions/latest/dg/limits.html

**Comment by FireballDWF** [comment]
Yes, invoke per resource would be expected.  The use case coming from the client is for s3 buckets, where the want to set some default policies if a there is no PutBucketPolicy call invoked within a certain time, yet don't want to overwrite any PutBuckeyPolicies which the original creator invokes shortly after creating the bucket.  Intermittently they are getting ErrorCode=OperationAborted from AWS with message " A conflicting conditional operation is currently in progress against this resource. Try again." with their set of custodian policies for S3 buckets.
