### ISSUE TITLE
Azure - Feature Request - Policies based on SKU

### ISSUE THREAD

**Issue by justinhauer** [cloud-custodian/cloud-custodian#3231]
Is there a way to create custodian policies based upon the SKU's of specific resources? Organizations may want to create policy that only supported SKU's of storage accounts, VMs, etc are used. I see that this feature is present in Azure policy: https://docs.microsoft.com/en-us/azure/governance/policy/samples/allowed-skus-storage.

If this type of functionality should be handled separately in Azure governance policy, let me know. If custodian can handle this as well, the ability to manage these aspects of an Azure account in 1 tool may be desired.

**Comment by kapilt** [comment]
as long as the sku is present in the resource json describe/get output, you can do an attribute/value filter on it directly within a custodian policy. you would need to have separate policies by the groups of skus you want to have different policies on.

ie

```
- type: value
   key: "sku"
   value: 
      - F1
      - F2
   op: in
```

or 

``` - sku: XYZ```

**Comment by logachev** [comment]
You can filter VMs SKUs using `properties.hardwareProfile.vmSize` property

```
 - type: value
      key: properties.hardwareProfile.vmSize
      op: ni
      value_type: normalize
      value: ['basic_a0', 'basic_a1', 'basic_a2', 'basic_a3']
```

For the storage accounts key is `sku.name`
