### ISSUE TITLE
s3 bucket issue with finding public buckets

### ISSUE THREAD

**Issue by fidelito** [cloud-custodian/cloud-custodian#3234]
Hi,
I am noticing that the policy I have stop working properly. It doesn't find public facing s3 buckets any more. My custodian version is 0.8.31.2

It was pointed out in the chat that it can be because of how AWS change recently s3 bucket policies.
```yaml
policies:
  - name: s3-global-access
    resource: s3
    filters:
      - or:
        - type: global-grants
        - type: cross-account
          everyone_only: true
      - not:
           - "tag:approved": not-null
```

**Comment by fidelito** [comment]
It finds previous ones if I get rid off the ones I am excluding via the tag. This buckets were created prior to the AWS s3 new changes.

**Comment by timbo256** [comment]
I have also found tha the global-grants does not work for newly created buckets (following the AWS chnages to s3 bucket permissions).

**Comment by timbo256** [comment]
#3146 seems to be related - https://aws.amazon.com/blogs/aws/amazon-s3-block-public-access-another-layer-of-protection-for-your-accounts-and-buckets/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+AmazonWebServicesBlog+%28Amazon+Web+Services+Blog%29

**Comment by kapilt** [comment]
perhaps, but i suspect it has more to do with the console doing additional api calls post bucket creation to shape it per user access. what i'm missing in this issue is what the logs have.. ie what does not work mean?

**Comment by fidelito** [comment]
I have test public s3 bucket and in aws console it shows as them public but cloud custodian is not detecting them. Cloud custodian say no s3 buckets were found due to I don't get no email. It only detects older s3 buckets that is public facing. I have no errors when I run the policy. Do you need the debug logs?

**Comment by fidelito** [comment]
Running policy s3-check.yml against account 000000000000
09:45:31			2018-12-17 14:45:31,119: custodian.commands:DEBUG Loaded file /dev/fd/63. Contains 1 policies
09:45:31			2018-12-17 14:45:31,137: custodian.aws:DEBUG using default region:us-west-2 from boto
09:45:31			2018-12-17 14:45:31,408: custodian.output:DEBUG Storing output with <DirectoryOutput to dir:/home/blah/output/s3-check/000000000000/s3-global-access>
09:45:31			2018-12-17 14:45:31,409: custodian.policy:DEBUG Running policy s3-global-access resource: s3 region:us-west-2 c7n:0.8.31.2
09:45:31			2018-12-17 14:45:31,410: custodian.cache:DEBUG Using cache file /home/rundeck/cache/s3-check/000000000000-cache.file
09:45:31			2018-12-17 14:45:31,411: custodian.resources.s3:DEBUG Using cached c7n.resources.s3.S3: 46
09:45:31			2018-12-17 14:45:31,418: custodian.resources.s3:DEBUG Filtered from 46 to 0 s3
09:45:31			2018-12-17 14:45:31,418: custodian.policy:INFO policy: s3-global-access resource:s3 region:us-west-2 count:0 time:0.01
09:45:31			2018-12-17 14:45:31,419: custodian.output:DEBUG metric:ResourceCount Count:0 policy:s3-global-access restype:s3 scope:policy

**Comment by thisisshi** [comment]
I don't think I'm actually able to reproduce, originally I thought the issue was wrt the public access settings that are available to be set in the console on bucket creation. However, those settings actually do not _enable_ public access, rather they enable/disable setting public access via acl/bucket policy. After enabling public access with the following command:

```shell
aws s3api put-bucket-acl --bucket $bucket --acl public-read
```

the following policy was able to find the bucket:

```yaml
policies:
  - name: s3-bucket-public
    resource: s3
    filters:
      - type: global-grants
```

afaics there is no way to actually enable public access via the console at this point.

**Comment by thisisshi** [comment]
can you provide more information? are the buckets actually showing up in the console as "public"? also, what is the result of a get-bucket-acl api call for those buckets that should be picked up that are not being picked up?

**Comment by fidelito** [comment]
![image](https://user-images.githubusercontent.com/8169250/50185232-3adf7480-02e5-11e9-9be0-a5f1904716f2.png)

this is the bucket policy and its public read access but its hosting a website via cloudfront. I created a new bucket because the other bucket was created for website hosting and I wanted to isolate the problem. But both the return json for get bucket acl is the same.

Policy check is running 0000000000 us-east-1 to find out open s3 buckets
0000000000 us-east-1 {
    "Owner": {
        "DisplayName": "REDACTED", 
        "ID": "REDACTED"
    }, 
    "Grants": [
        {
            "Grantee": {
                "Type": "CanonicalUser", 
                "DisplayName": "REDACTED", 
                "ID": "REDACTED"
            }, 
            "Permission": "FULL_CONTROL"
        }, 
        {
            "Grantee": {
                "Type": "Group", 
                "URI": "http://acs.amazonaws.com/groups/global/AllUsers"
            }, 
            "Permission": "READ"
        }
    ]
}

I re-ran cloud custodian and it found the s3 bucket that i just created (its not hosting a website) with the same policy I mention in the initial post.



Running policy s3-check.yml against account 0000000000
17:11:52			2018-12-18 22:11:52,839: custodian.commands:DEBUG Loaded file /dev/fd/63. Contains 1 policies
17:11:52			2018-12-18 22:11:52,856: custodian.aws:DEBUG using default region:us-west-2 from boto
17:11:53			2018-12-18 22:11:53,160: custodian.output:DEBUG Storing output with <DirectoryOutput to dir:/home/blah/output/s3-check/0000000000/s3-global-access>
17:11:53			2018-12-18 22:11:53,160: custodian.policy:DEBUG Running policy s3-global-access resource: s3 region:us-west-2 c7n:0.8.31.2
17:12:09			2018-12-18 22:12:09,447: custodian.resources.s3:DEBUG Filtered from 47 to 1 s3
17:12:09			2018-12-18 22:12:09,447: custodian.policy:INFO policy: s3-global-access resource:s3 region:us-west-2 count:1 time:16.29
17:12:10			2018-12-18 22:12:10,224: custodian.actions:INFO sent message:02b5738a-678e-4535-acfd-b8b11a707f18 policy:s3-global-access template:default.html count:1
17:12:10			2018-12-18 22:12:10,227: custodian.policy:INFO policy: s3-global-access action: notify resources: 1 execution_time: 0.78
17:12:10			2018-12-18 22:12:10,227: custodian.output:DEBUG metric:ResourceCount Count:1 policy:s3-global-access restype:s3 scope:policy

It looks like the issue is if the s3 bucket is created via cloudfront and its public facing as the same bucket acl as the other s3 bucket cloud custodian doesn't detect the website hosting s3 bucket.

**Comment by fidelito** [comment]
policies:
  - name: s3-global-access
    resource: s3
    filters:
      - or:
        - type: global-grants
          **allow_website: false**
        - type: cross-account
          everyone_only: true
      - not:
           - "tag:approved": not-null

adding kapil comments:

"Ah that’s actually a config option on the filter, it defaults to whitelisting websites" for anyone reading this in the future
