### ISSUE TITLE
SNS Notification

### ISSUE THREAD

**Issue by Shelvey-Kansal** [cloud-custodian/cloud-custodian#3251]
Hello, @kapilt 
I am facing an issue in notification part. I was trying to receive a notification on my email whenever an instance is terminate, with all the details of the instance using SNS. But all I am receiving is encoded message. I installed Custodian mailer tool and used sqs as transport, but still I am receiving the encoded message in SQS as well.

**Comment by kapilt** [comment]
c7n_mailer is intended as the rendering and delivery tool. the payload sent by notify action to either sns/sqs is a data payload (base64 encoded json) for which c7n_mailer is the delivery tool. ie to setup rendered delivery to an sns topic you would need something like the following in your notify action along with c7n_mailer subscribed to sns_arn_my_data_transport

```
to:
  - sns_arn_my_inbox
transport
  - type: sns
     topic: sns_arn_my_data_transport
```
