### ISSUE TITLE
Azure - Resource Graph Evaluation

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#3300]
Azure Resource Graph is in preview.  It provides a very high-speed, no-throttle query of the entire resource graph via a single API.  (They basically own maintaining a database of the graph for you to query)

We should evaluate the current state and look at how our architecture would change if we moved to resource graph for most resource queries.

https://docs.microsoft.com/en-us/azure/governance/resource-graph/overview

**Comment by yayitserica** [comment]
### ACCEPTANCE CRITERIA

1. Evaluation of Azure Resource Graph and recommendations on how C7N architecture would be affected by moving to resource graph for resource queries.
2. Create a new GitHub issue to address next steps on implementing Azure Resource Graph

FYI @stefangordon

**Comment by aluong** [comment]
fixed by #4924
