### ISSUE TITLE
Azure - duplicate packages causing failed download

### ISSUE THREAD

**Issue by joescars** [cloud-custodian/cloud-custodian#3305]
**Issue**

When putting together package lists, duplicates exist in the list causing the following error message during deployment:

```
c7n_mailer.azure.deploy - INFO - Building function package for mailer1-mailer-76d56b36
custodian.azure.function_package - INFO - Cached packages not found or requirements were changed.
custodian.azure.function_package - INFO - Preparing non binary wheels...
custodian.azure.function_package - INFO - Downloading wheels...
c7n_azure.dependency_manager - ERROR - Failed to download wheels!
```

**Root Cause**

Static method get_dependency_packages_list was de-duping the packaeg list but not taking into consideration the version #

**Resolution**

Using regex to match on package name and ignore version. If duplicate package is found it is removed from the list. 

PR shortly to resolve issue

@aluong @logachev

**Comment by justinhauer** [comment]
@joescars I just created a new virtualenv from latest and ran into this same issue. Has this persisted for you at all?

**Comment by joescars** [comment]
@justinhauer - apologies on the late response. the issue has not persisted since submitting the PR with a fix. I can do some testing again locally. Can you let me know what your setup is? Also, are you getting the same exact error.
