### ISSUE TITLE
resize an asg desired/min/max count

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#331]

**Comment by kapilt** [comment]
we've added a very barebones version of this for resizing an asg to its current capacity in #448, leaving this open to track more parameterization around resize.

**Comment by wsoula** [comment]
Would you accept a small change that allows you to specify the desired size?  I've implemented a way to keep the current functionality as well as add the ability to set desired size: https://github.com/wsoula/cloud-custodian/compare/master...wsoula:specify-asg-desired-size

**Comment by wsoula** [comment]
@kapilt ^^^

**Comment by kapilt** [comment]
definitely re pr for desired, thanks

**Comment by nitrocode** [comment]
This seems finished https://cloudcustodian.io/docs/aws/resources/asg.html#aws-asg-actions-resize

**Comment by kapilt** [comment]
fair, thanks, this is extant
