### ISSUE TITLE
Azure - Feature Request - Policy support for HDInsight

### ISSUE THREAD

**Issue by justinhauer** [cloud-custodian/cloud-custodian#3311]
#### Description:
It would be great to managed some cluster operations of HDInsights for non-ephemeral(longer lived) clusters through Custodian. The main thing I can think of is scaling cluster size (amount of vm's) based on a Cron schedule (scale non prod environments down for off hours). The Azure portal doesn't allow for vm instance resizing of head or worker nodes once the cluster is created, perhaps this is also possible.
#### It looks like resizing is supported: 
`https://docs.microsoft.com/en-us/python/api/azure-mgmt-hdinsight/azure.mgmt.hdinsight.operations.clustersoperations?view=azure-python#resize-resource-group-name--cluster-name--target-instance-count-none--custom-headers-none--raw-false--polling-true----operation-config-`

**Comment by stefangordon** [comment]
#4530

**Comment by stefangordon** [comment]
Todo:
1) Add HD Insight core resource support
2) Extend resize action to support HD Insight

**Comment by wsf11** [comment]
I'll take this

**Comment by aluong** [comment]
fixed by #4758 
fixed by #4731
