### ISSUE TITLE
Azure - Running cloud custodian without creating a service principal should fail quickly 

### ISSUE THREAD

**Issue by rguthriemsft** [cloud-custodian/cloud-custodian#3328]
If you run a policy cloud custodian and have not created/set a service principal prior to the run, the script will fail in get_functions_auth_string with a correct error message:
`            raise NotImplementedError(
                "Service Principal credentials are the only "
                "supported auth mechanism for deploying functions.")`

However this check and failure occurs after provisioning/building the policy.  This check should be moved prior to package build so the action fails fast and the user gets feedback quickly instead of waiting for this check.

**Comment by stefangordon** [comment]
Yeah at a minimum we already have these in session

```
        self._is_token_auth = False
        self._is_cli_auth = False
```

Might be worth a minor update with something resembling an enum of all four auth types and a public method to get it, along with validation for functions deployment (there may be other types of validation to do re: python version and OS - or do we really have 100% compatibility there now?)

**Comment by kapilt** [comment]
so I'd recommend adding a validate method to the function mode, so that this can fail fast and early for the user before we even get to policy execution.
