### ISSUE TITLE
Azure - Authentication documentation for Service Principal, steps to grant contributor rights

### ISSUE THREAD

**Issue by rguthriemsft** [cloud-custodian/cloud-custodian#3329]
When I follow the steps to create a service principal (https://github.com/cloud-custodian/cloud-custodian/blob/master/docs/source/azure/authentication.rst), there is guidance to grant the SP contributor rights however when I ran `az ad sp create-for-rbac` this role was granted automatically.  Might consider adding text to indicate check first and if not granted, add the role assignment.

**Comment by stefangordon** [comment]
When addressing this its probably worth taking a clean look and pass over that entire documentation page as its had a lot of ad-hoc updates as things changed.
