### ISSUE TITLE
cli - aws - assume role failure should end policy execution

### ISSUE THREAD

**Issue by steveparker-1984** [cloud-custodian/cloud-custodian#3346]
When I run custodian with `--assume` with a policy file that contains multiple policies, and the role passed can not be assumed, custodian will report:

`custodian.commands:ERROR Error while executing policy <policy-name>, continuing`

for each policy, before eventually exiting with status 2. It would be preferable to be able to exit on the first error. I could achieve this by setting `--debug` judging by the code, but looking how debug is used, this isn't really the solution.

**Comment by kapilt** [comment]
there's a good case to be made for fail on first error in the case of a bad role or inability to use a passed in role for --assume-role as there's no hope of any policy execution succeeding .. for other cases though its not an option to change the default behavior here.

**Comment by steveparker-1984** [comment]
I don't think I'd use the cli flag, I'd prefer to keep the existing behaviour. Treating bad auth as a pre-execution check would be ideal, yeah.
