### ISSUE TITLE
aws.ebs-snapshot - add ability to do server side queries on ebs snapshots

### ISSUE THREAD

**Issue by thisisshi** [cloud-custodian/cloud-custodian#3353]
the desribe_snapshots call allows the usage of user defined filters, this can be useful when writing policies against accounts that have a large number of snapshots (order of magnitude 100k+). currently custodian implicitly filters in only user-created snapshots

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.describe_snapshots

**Comment by kapilt** [comment]
re context #3217
