### ISSUE TITLE
proposal - monolith repository break out

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#3360]
# Introduction

A monolith repository has served custodian well. We currently host the main package, as well a dozen tools including additional core providers (gcp, azure, kube) and various others. Monorepos have some strong benefits wrt to testing, review, common libraries, refactoring. So why change, well we've got a few tools that have more different test requirements (omnissm, c7n_policystream), so while they have tests, we haven't been executing as part of the ci runs, due to a desire to keep ci times fast (~6.5m e2e atm). We've had a number of ci churns on the combined dependencies that have ci blockages. We've also had some pretty good separation of which tools are maintained by different groups. Additionally we've also got widely different coverage requirements across the projects, the providers are typically in the 90%  range, while other tools like c7n_mailer are closer to 35% which drags on the overall coverage numbers for this repo.

The first question is should we split out to multiple repos?

# Considerations

Its important to note where we have some shared knowledge in the monorepo that will need to be accounted for.

 - docker image builds (c7n, c7n_org, c7n_policystream) that want to build across all providers.
 - shared library use of c7n package by various tool folder packages (all the providers, etc)
 - extant prs would be bit rotted if they cross a repo boundary
 - doc building
 
Additionally, we typically want ci for things with a c7n dependency to run both against trunk

  - c7n change -> breaks dependency .. should be caught in ci
  - dependency introduces requirement on something only in c7n release, but changed in trunk.

# Proposal

The next question is how. There's some initial steps with repos that are mostly independent (c7n_mailer, etc) that minimal cross dependency that should be straight forward.  For the cross dependent repos, its an open question of how best to integrate the repos. Relying on releases should suffice for dependencies in most development scenarios. 

 In terms of unified git checkouts we could setup the main repo with subtrees, or we could setup a synthetic repo with all the subtrees. that synthetic repo would represent a downstream build target for any individual repo's ci pipeline, so all merges to any repo would get tested with trunk of all repos.
Git submodules don't feel particularly appropriate as they represent pinned version links, subtrees seem a better fit. https://www.atlassian.com/blog/git/alternatives-to-git-submodule-git-subtree

Contributors to any given repo would just checkout that repo and work per normal, with the caveat that changes across repos will require multiple pull-requests. For dependent changes this may require temporary compatibility modes.

Its worth doing some research into openstack and kubernetes ci, as they deal with similiar issues across many project repos, afaicr kubernetes tried to stay with a monorepo as long as it could.

normalizing repo names would also be nice `provider.azure`, `provider.k8s`, `provider.gcp` re repo names `tools.c7n-org`, `tools.policy-stream`

Its a given any outcome of this proposal should preserve all project history.

 tbh the more I think about it, the less great it seems, ie. i'm not sure we're ready for the complexity, many of our users / contributors seem to have limited git experience, and this might be more confusing for them. but curious for feedback.

**Comment by kapilt** [comment]
given a lack of feedback, or interest on the proposal, coupled with restrictive org permissions, there's no much point in this. closing.

**Comment by bclements** [comment]
@kapilt We have spoken about it internally and I'd like to reopen this. We are all in agreement that micro-repos would be the better way to do this. The concern, similar to what you posted in the original proposal, is the risk associated and the amount of work required.  Can you, me, @thisisshi, and anyone else who is interested circle back on this to discuss a way forward, if at all?

**Comment by kapilt** [comment]
i have no interest in pursuing this with the restrictive org permissions. i can't even add an integration to a repo, but i'm also maintaining all the ci infrastructure.
