### ISSUE TITLE
DeprecationWarnings which need to be handled before Python 3.8 support

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#3363]
AsOf 1/14/2019,  "tox -e py37 ." results in 24 warnings. 

1. 18 of which must be resolved before Python 3.8 can be supported, with fix to be to upgrade (when available) to packages which support the revised package name.  Example message: 
```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 
'collections.abc' is deprecated, and in 3.8 it will stop working
```
Target date for release of Python 3.8 is 10/20/2019 per https://www.python.org/dev/peps/pep-0569/#schedule.
2. 6 remaining are trivial changes of self.assertEquals to self.assertEqual (drop the s)

**Comment by kapilt** [comment]
all the remaining deprecation warnings are from dependencies, those from our codebase/test themselves have been whittled down, last set of fixes for those are #4719
