### ISSUE TITLE
docs - update docs home page to reference multi-cloud support

### ISSUE THREAD

**Issue by thisisshi** [cloud-custodian/cloud-custodian#3368]
https://cloudcustodian.io/docs/index.html

currently docs only make mention of AWS in the first few paragraphs, need to show the multicloud support some love :)

**Comment by kapilt** [comment]
this one is straightforward, and i'm working on automating the doc updates there (per recent drone changes), but frankly much more important than this is fixing #3330, as without that no one will see the content on this page.

**Comment by kapilt** [comment]
doc publishing and builds are updated. its will need a pr to the gh-pages branch to address.

**Comment by kapilt** [comment]
done
