### ISSUE TITLE
Azure

### ISSUE THREAD

**Issue by challs1** [cloud-custodian/cloud-custodian#3390]
Does cloud custodian works for azure policy complaince?

**Comment by kapilt** [comment]
Custodian works with azure, including serverless real-time policies, docs are here 
https://cloudcustodian.io/docs/azure/gettingstarted.htm

Do you have a more specific question or use case in mind?

**Comment by kapilt** [comment]
If you mean verifying/modifying native azure policies it does that as well 
https://cloudcustodian.io/docs/azure/policy/resources/policyassignments.html

**Comment by challs1** [comment]
@kapilt  i am using enterprise red hat linux servers in azure when i  am trying to install  virtualenv custodian and does it check for policy complaince in azure?
 it was giving me as -bash: virtualenv: command not found
