### ISSUE TITLE
Refer a resource matched in one policy in another policy

### ISSUE THREAD

**Issue by skgbox** [cloud-custodian/cloud-custodian#3399]
For example we need to implement the following policy : "Ensure S3 bucket access logging is enabled on the CloudTrail S3 bucket".
In this case we need to have a policy that finds the name of CloudTrail S3 bucket and another one checking if that bucket has logging enabled.

**Comment by skgbox** [comment]
For example we need to implement the following policy : "Ensure S3 bucket access logging is enabled on the CloudTrail S3 bucket".
In this case we need have policy that finds the name CloudTrail S3 bucket and another one to check if that bucket has logging enabled.

**Comment by kapilt** [comment]
the actual policy your trying to achieve, you would do via is-log-target filter on s3 to identify buckets that are cloud-trail targets and then check to see that they have access logging enabled, full relational algebra between policies of different resources won't be supported.

**Comment by skgbox** [comment]
Thank you, kapilt !
