### ISSUE TITLE
Add support for lambda layers as alternative to usage of packages for lambda deployments

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#3405]
1) Add support for lambda layers as alternative to usage of packages for lambda deployments.  
2) include other parts of custodian in a layer as well

**Comment by kapilt** [comment]
trunk and next release do support manual specification of layers on a policy lambda via `layer` key on the execution mode. 

automated creation and publication of layers is something i've explored, but the cli experience still feels a bit odd, in that its a significant delay for layer upload to each region before we even get to policy execution. plus side its automated and worry free, downside it makes things feel slower for small policy sets with one or two lambdas. the layer is formed over the closure of policy lambda specified packages with mandatory inclusion of botocore/boto3.

**Comment by kapilt** [comment]
fwiw, policies can now specify layers in 0.8.41.0 on their mode. layer construction is currently out of band by end user.
