### ISSUE TITLE
deploy c7n-mailer to multiple aws accounts

### ISSUE THREAD

**Issue by jksgit** [cloud-custodian/cloud-custodian#3407]
What is the best way to deploy mailer to multiple accounts?.

**Comment by kapilt** [comment]
mechanically it works the same as deploying it to a single account, setup the config and run the cli

**Comment by jksgit** [comment]
> @jksgit what's the rationale behind deploying to multiple accounts? imo it's better to utilize the resource level iam permissions on sqs queues to enable multiple accounts to send mail to a centralized mailer

I am following the same strategy . I am looking for a c7n-org solution for c7n-mailer deployment.

**Comment by kapilt** [comment]
your question doesn't make a lot of sense. c7n-org executes custodian policies across accounts. c7n-mailer is independent of policy execution, it just setups an sns/sqs listener that delivers messages. you can setup an sns/sqs queue in a single account with a single mailer listening, that other accounts can send to, you'll need to modify the iam policy of the sns or sqs to enable this. Alternatively you can setup copies of mailer in multiple accounts with separate sns/sqs per account (aka deploy to multiple to accounts).

**Comment by jksgit** [comment]
Got it. Thanks
