### ISSUE TITLE
consider removing pyyaml dependency

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#3413]
so we currently use pyyaml its been a long standing foundational library for python built on libyaml c extension, its had a bad default for years of supporting unsafe loading of python objects from user content, custodian explicitly uses the safe loading to avoid an issues there, but that doesn't prevent all the security scanners that trigger off package versions from alerting. 

i started looking into pyyaml repos for what could be done to address re https://github.com/yaml/pyyaml/ the short answer is to pin to 4.2b2, but that was last released almost a year ago, the general state of the project doesn't feel particularly healthy. ie there's no official stable release with fix for a cve from 2017, the last commit on the project was in june 2018, etc. 

ruamel.yaml is a fork of pyyaml that also adds a few features, we ended up using it for c7n_mailer as it uses a common code base between py2 & py3, it might just be worthwhile to switch out to it entirely.

**Comment by kapilt** [comment]
hmm switching to 4.2b4 won't work apparently as azure-cli-core pins to pyyaml 3.12 so its likely we'll still be pulling it due to transitive dependencies

ContextualVersionConflict: (PyYAML 4.2b4 (/Users/kapilt/projects/custodian/.tox/py27/lib/python2.7/site-packages), Requirement.parse('pyyaml~=3.12'), set(['azure-cli-core']))

**Comment by kapilt** [comment]
At the moment, i think the scanners probably just need squelching, custodian actual usage of pyyaml is safe since we only use the safe loader variants.

in terms of looking at a virtualenv that has custodian and other providers loaded, here's the reverse dependency set on pyyaml

```
$ pipdeptree -r -p pyyaml
PyYAML==3.13
  - awscli==1.16.93 [requires: PyYAML>=3.10,<=3.13]
  - azure-cli-core==2.0.40 [requires: pyyaml~=3.12]
    - c7n-azure==0.4 [requires: azure-cli-core<=2.0.40]
  - c7n==0.8.33.1 [requires: pyyaml]
    - c7n-azure==0.4 [requires: c7n]
    - c7n-gcp==0.2.1 [requires: c7n]
    - c7n-kube==0.1 [requires: c7n]
    - c7n-org==0.5.0 [requires: c7n]
  - knack==0.3.3 [requires: pyyaml]
    - azure-cli-core==2.0.40 [requires: knack==0.3.3]
      - c7n-azure==0.4 [requires: azure-cli-core<=2.0.40]
  - kubernetes==7.0.0 [requires: pyyaml>=3.12]
    - c7n-kube==0.1 [requires: kubernetes==7.0.0]
  - vcrpy==1.11.0 [requires: PyYAML]
    - vcrpy-unittest==0.1.7 [requires: vcrpy]
```

**Comment by ingydotnet** [comment]
It is my opinion that the CVE is unwarranted, because this is the documented behavior (since day 1) of the `load` method  of the PyYAML serialization module. This is the exact same situation as the Pickle serialization module. See the red warning here: https://docs.python.org/3/library/pickle.html

PyYAML has been in the wild for 12+ years and we are not going to make a breaking change of this degree. We are working on steps to mitigate this, and load() will become safe, but changing `load` to `safe_load` semantics is not the way to do that.

**Comment by kapilt** [comment]
@ebickle it looks like we're pinned to an older version of azure-cli-core which has this pin, latest trunk there depends on pyyaml 4.2b (https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/setup.py#L71), note this only affects usage when using the c7n_azure cloud provider. Note awscli trunk also has a pin to <=3.13, but its not a direct dependency, just a common install (https://github.com/aws/aws-cli/blob/develop/setup.py#L31)

 @aluong any chance you can look at updating c7n_azure pin on cli-core. If we have that unpinned we can just start requiring >= 4.2b to resolve.
