### ISSUE TITLE
AWS Generic Actions

### ISSUE THREAD

**Issue by cbarensfeld** [cloud-custodian/cloud-custodian#3442]
Is there a doc that explains generic actions, such as tagging a resource? I see examples with "tag" and "mark-for-op" as an action, but where can I find the doc that explains what kinds of actions I can take?

Thanks

**Comment by kapilt** [comment]
the easiest way is to the `custodian schema` command to interactively drill into a given resource, and its individual filters/actions for  docs, schema, and examples.

**Comment by cbarensfeld** [comment]
Thank you this is exactly what I was looking for.
