### ISSUE TITLE
[securityhub] post-findings action for resource=aws.account results in file format conformance issues

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#3443]
1. Current code outputs Resource.Id= "arn:::369510138361" which does not likely comply with end state of file format.  Have asked for Security Hub Product Manager for update to https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-findings-format.html
2. Resource.Type field is currently uses the generic "Other", but likely should use the "AwsAccount" type which the current CIS Benchmark code uses, but is currently not documented in the File Format.  Have also asked for same URL to be updated.

If Insights are created which filter on or group by the Resource.Type=AwsAccount field before this is resolved, then findings posted by CloudCustodian would not show up.  Currently low priority As of 1/25/2019 there are 21 Insights none of which use this field, instead the "Top accounts by count of findings" Insight uses the "finding" level AwsAccountId field rather than the Resource level field.

**Comment by kapilt** [comment]
closing out, this was resolved a few months ago afaik
