### ISSUE TITLE
Govcloud SNS prefix incorrect

### ISSUE THREAD

**Issue by cbarensfeld** [cloud-custodian/cloud-custodian#3453]
Hello,

It seems that cloud custodian is putting the SNS arn prefix incorrectly for govcloud. This is the error I'm getting:

botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameter) when calling the Publish operation: Invalid parameter: TopicArn Reason: A us-gov-west-1 ARN must begin with arn:aws-us-gov, not arn:aws:sns:us-gov-west-1:xxxxxxxxxxx:snsname

policies:
  - name: custodian-tags
    resource: ec2
    filters:
      - or:
        - "tag:CustodianTest": present
        - "tag:CustodianTest2": present
    actions:
      - type: notify
        to:
          - my@email.com
        template: default
        transport:
          type: sns
          region: us-gov-west-1
          topic: snsname

**Comment by kapilt** [comment]
thanks for the bug report, we need to take into account partition when constructing sns arns.

**Comment by kapilt** [comment]
the easy work around here is to specify the full arn in your notify policy, account_id interpolation still works for using policies across accounts.

**Comment by kapilt** [comment]
hmmm.. actually it looks like that won't work, the arn check is qualified with partition.

**Comment by cbarensfeld** [comment]
Correct, when I use the full ARN is still adds the prefix.
