### ISSUE TITLE
Azure - Package cache not being leveraged properly in Windows

### ISSUE THREAD

**Issue by joescars** [cloud-custodian/cloud-custodian#3456]
Unfortunately this issue happens intermittently and I have not yet determined the root cause. 

**Environment**
Windows 10 Enterprise, Using Command Prompt or PowerShell
Packages installed from local repo or pip package 

**Issue**
When running a script locally in Windows more often than not, it will not read from the package cache. The result is a clearing of the cache and re-downloading. This can be time consuming when iterating through versions of a script. 

The message that comes up is as follows:
```
Cached packages not found or requirements were changed.
```
@aluong

**Comment by logachev** [comment]
Fixed with https://github.com/cloud-custodian/cloud-custodian/pull/3341
