### ISSUE TITLE
Azure - Add Documentation for related resources/attributes available for filtering

### ISSUE THREAD

**Issue by helayoty** [cloud-custodian/cloud-custodian#3462]
Need to document where there are related resources, the attributes available for filtering eg, frontend-public-ip on https://cloudcustodian.io/docs/azure/policy/resources/loadbalancer.html is documented, this kind of related resource filter may not be documented for other providers

**Comment by stefangordon** [comment]
I believe all available filters/actions specific to a resource type are accurately listed under the resources now.
