### ISSUE TITLE
Tagging CloudFormation - Error: Parameters must have value

### ISSUE THREAD

**Issue by 011810058** [cloud-custodian/cloud-custodian#3463]
Initially the stack is created with an input parameter.

**c7n policy**
```
policies:
  - name: add-cfn-tag
    resource: cfn
    filters:
      - "tag:testcfn": present
    actions:
      - type: tag
        value: abc
        key: BusinessUnit
```
**Error**
An error occurred (ValidationError) when calling the UpdateStack operation: Parameters: [input_param] must have values

**Comment by kapilt** [comment]
how are you creating a cft with a required parameter? afaics the tooling is a bit opaque around this

**Comment by 011810058** [comment]
Initially when the stack is created it is provided with a list of parameters, example below. Using c7n we need to tag the stack, that is stack update operation. When I am try to do so c7n gives an error
because 'UsePreviousValue': True  is not set while update.

  "Parameters": {
    "CISUserName": {
      "Type": "String",
      "Description": "The access key used to run CIS report utility using Jenkin's target",
      "MinLength": "1",
      "ConstraintDescription": "This parameter is required."
    }
  }

**Comment by 011810058** [comment]
Adding to the previous comment, I tried different ways like using periodic lambda, event based lambda on stack creation ,and using local setup. All give the same error- "Parameters must have value". Almost all of our stacks have input parameters and we need to update tagging only.

**Comment by kapilt** [comment]
thanks, i was able to reproduce with that snippet, fix in pull request #3464

**Comment by 011810058** [comment]
Thanks Kapil for the quick fix.
With above fix it is no more showing parameter issue but it is not working as expected.

1) Previously existing tags are removed, only newly added tags are reflected.

2) If we provide multiple tags to update it only reflect last tag in API sequence  request with an error mentioned below.

policies:
  - name: add-cfn-tag
    resource: cfn
    filters:
      - "tag:BusinessUnit": abc
    actions:
      - type: tag
        value: abc2
        key: BusinessUnit2
      - type: tag
        value: abc1
        key: BusinessUnit1

An error occurred (ValidationError) when calling the UpdateStack operation: Stack:arn:aws:cloudformation:us-west-2:594523226318:stack/test-jsingh-c7n-tagging/b9fb10b0-2416-11e9-95ca-0ae06257a2d8 is in UPDATE_IN_PROGRESS state and can not be updated

3)   If we are updating a stack with CAPABILITY_IAM, below error is being observed.

2019-01-29 14:28:24,262: custodian.actions:ERROR Exception with tags: [{u'Value': 'abc', u'Key': 'BusinessUnit'}] on resources: c7n-custodian-user-policy-and-ops 
 An error occurred (InsufficientCapabilitiesException) when calling the UpdateStack operation: Requires capabilities : [CAPABILITY_IAM]

**Comment by 011810058** [comment]
Kapil, I am not sure does the fix incorporate the changes to avoid previous tags replacement and iam capability in stack. If not, do I need to open an issue to track the same separately.

**Comment by kapilt** [comment]
hmm.. noted, sorry i'll have to do a followup, its very unfortunate syntax that requires providing all the existing state to trigger a tag change.

**Comment by kapilt** [comment]
wrt to tagging with multiple values use syntax

````
type: tag
tags:
    BusinessUnit1: abc2
    BusinessUnit2: abc1
```

**Comment by kapilt** [comment]
new pr #3480 up, additional testing would be appreciated, unit test covers tag merge and added capabilities, notification arns per additional reading on update behavior. its a little unclear if for a sam template, the autoexpand capability needs to be added.

**Comment by 011810058** [comment]
Thanks Kapil, I verified the pr #3480 and it's working as expected. We have never used autoexpand capability so it's hard to comment on same. 

Marking as close. Thanks again!
