### ISSUE TITLE
Azure - Identify expired or expiring keys in Key Vault

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#3470]
KeyVault is an ARM resource we already support.  The keys in it are not ARM resources, but are accessed via the KeyVault API.  

I believe it is a common and important scenario to be able to query these keys so I suggest at a minimum we create something based on ValueFilter that augments the KeyVault resource to include the Keys such that you can query on things like expiration date to alert people of expiring keys, or to enforce expiration policies.

Note, another related scenario is being able to identify keys of certain types.  Maybe you want to find any keys that are not RSA HSM and flag them.

`class InstanceViewFilter(ValueFilter)` for VM is sort of an example of this (although it uses the same API).

Relevant conversation in Azure Policy issue https://github.com/Azure/azure-policy/issues/138

**Comment by kapilt** [comment]
This might be better as a parent/child resource setup, where the parent is the key vault, and the key exists as a child resource. There's support in c7n/query.py for these types of setups, but it will likely need extension. That allows more natural expression of policies like a filter to find expiring keys/aged keys, and delete/rotate/notify on them.
