### ISSUE TITLE
Provide "all" keyword for mode periodic

### ISSUE THREAD

**Issue by SusVlaAlex** [cloud-custodian/cloud-custodian#3485]
Could you please provide the ability to specify special keyword **all** for a periodic run as it provided for cli (`--region all`)? 

Something like this:

```yaml 
mode:
  type: periodic
  schedule: "rate(1 day)"
  role: some_role
  execution-options:
  regions: all
```

Because now, I got error:
```
[ERROR]	2019-01-31T12:42:03.156Z	c45b60e8-9145-41bf-95b7-05b784cb4e86	Error while executing policy
Traceback (most recent call last):
File "/var/task/c7n/policy.py", line 241, in run
resources = self.policy.resource_manager.resources()
...
File "/var/runtime/botocore/retryhandler.py", line 359, in _check_caught_exception
raise caught_exception
EndpointConnectionError: Could not connect to the endpoint URL: "https://ec2.all.amazonaws.com/"
```

**Comment by kapilt** [comment]
hmm.. not sure we should support this, lambdas have limited execution times, its better to deploy across regions for both timeouts and resiliency then trying to execute against many, especially against a data plane as populous as ec2.
