### ISSUE TITLE
IAM-policy action delete cannot delete IAM policy with mutiple versions

### ISSUE THREAD

**Issue by pjshort22** [cloud-custodian/cloud-custodian#3492]
when using iam-policy in cloud custodian to delete iam policy when created or updated with allow * resource *.  using type: has-allow-all

This does not delete policy if it has more than 1 policy
Sample Policy:

- name: custodian-agt-iam-no-used-all-all-policy
    resource: iam-policy
    description: Check polices when created or updated if have *.* permissions.
    mode:
      type: cloudtrail
      events:
        - source: iam.amazonaws.com
          event: CreatePolicy
          ids: "responseElements.policy.policyName"
        - source: iam.amazonaws.com
          event: CreatePolicyVersion
          ids: "requestParameters.policyArn"
   filters:
    - and:
      - type: has-allow-all
      - not:
        - or:
          - type: value
            key: "PolicyName"
            value: AdministratorAccess
    actions:
      - type: delete

Error Message:
This Policy has more than one policy, you must delete the policy's versions.

**Comment by jtroberts83** [comment]
This will need the implementation of list policy versions - https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam.html#IAM.Client.list_policy_versions followed by removing each policy version with - https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam.html#IAM.Client.delete_policy_version ,  EXCEPT for the default version as the default version has to be deleted by the delete_policy command
