### ISSUE TITLE
Run policy against multiple tags

### ISSUE THREAD

**Issue by JorHoyos** [cloud-custodian/cloud-custodian#3496]
Hi all, so the thing is i want to run a policy against multiple tags like the title says, so i was reading and its supposed to be like this:

- c7n-org run -c accounts.yml -s rep04022019 -u policies.yml -t ambiente:dev -t ambiente:cer -p ec2-tag-compliance-mark 

but it doesnt run anything, i usually run it two times like 

- c7n-org run -c accounts.yml -s rep04022019 -u policies.yml -t ambiente:cer -p ec2-tag-compliance-mark 
- c7n-org run -c accounts.yml -s rep04022019 -u policies.yml -t ambiente:dev -p ec2-tag-compliance-mark 
 
is there any way to run the policies against 2 or mores tags? and same thing for policies, how do i do if i want to run 2 policies on the same line?

Thanks

**Comment by kapilt** [comment]
currently the operator for multiple tags is `and` not `or` ie if you specify multiple tags its going to match an account that has both of the tags. we could add in support for `or` but it would have to be an explicit cli switch for backwards compatibility. something like `--tag-op or`

**Comment by JorHoyos** [comment]
Ok thank you very much.
