### ISSUE TITLE
ci - doc building

### ISSUE THREAD

**Issue by thisisshi** [cloud-custodian/cloud-custodian#3504]
seems to coincide with the switch over to azure pipeline? investigating...

Azure Pipelines commit (Dec 16) :https://github.com/cloud-custodian/cloud-custodian/pull/3249

last commit built (Dec 14): https://github.com/cloud-custodian/cloud-custodian/pull/3219

Most recent commit to gh-pages: https://github.com/cloud-custodian/cloud-custodian/commit/5065093a2c67989db7f1805adf126a269c463220

**Comment by thisisshi** [comment]
looks like the cert on ci.cloudcustodian.io is expired, causing webhook pushes to fail

**Comment by thisisshi** [comment]
oh seems like the was turned off at some point and then turned back on, still doesn't explain how the docs were built on dec 14, maybe the move here is just to move it to azure pipelines

**Comment by kapilt** [comment]
also #3350 as original issue. i haven't full vetted azure pipelines secrets for security, was going to resurrect drone, but the initial build failed on the new docs, which requires a followup spelunking of drone sphinx and git bisection per https://github.com/cloud-custodian/cloud-custodian/pull/3355
