### ISSUE TITLE
documentation is severely lacking

### ISSUE THREAD

**Issue by RichieRunner** [cloud-custodian/cloud-custodian#3506]
Where does one see what each of the filter type mean (offhour, onhour, value, etc)? 
Where does one see what each of the mode type mean (scheduled, periodic, etc)?

**Comment by kapilt** [comment]
the cli has some help builtin  `custodian schema ` for available resources, filters, actions

all of that is also published to the docs site, where you will also find docs on mode
https://cloudcustodian.io/docs/policy/lambda.html

if there's something unclear, please be specific, 'severely lacking' isn't very helpful, and of course pull requests welcome.
