### ISSUE TITLE
update min required version of boto3

### ISSUE THREAD

**Issue by ssteo** [cloud-custodian/cloud-custodian#3509]
`custodian schema` returns a list of resources including the below but the following 3 are not usable when used in policy.
- fsx
- fsx-backup
- backup-plan

Returns error *botocore.exceptions.UnknownServiceError: Unknown service: 'fsx'.*
Returns error *botocore.exceptions.UnknownServiceError: Unknown service: 'backup'.*

Version 0.8.40.0

**Comment by kapilt** [comment]
you'll need to update your boto sdk, `$ pip install -U boto3`

leaving this open to update our min version of boto3 in setup.py

**Comment by kapilt** [comment]
fwiw re what it looks when using a current version of boto against a supported or not supported region

```shell
(custodian) kapilt@realms-scythe ~/p/custodian> cat arg.yml 
policies:

  - name: fsx
    resource: fsx

(custodian) kapilt@realms-scythe ~/p/custodian> custodian run -c arg.yml -s out -v
2019-02-07 08:09:59,329: custodian.commands:DEBUG Loaded file arg.yml. Contains 1 policies
2019-02-07 08:09:59,343: custodian.aws:DEBUG using default region:us-east-1 from boto
2019-02-07 08:09:59,508: custodian.output:DEBUG Storing output with <LogFile file://out/fsx/custodian-run.log>
2019-02-07 08:09:59,523: custodian.policy:DEBUG Running policy fsx resource: fsx region:us-east-1 c7n:0.8.40.0
2019-02-07 08:09:59,705: custodian.resources.fsx:DEBUG Filtered from 1 to 1 fsx
2019-02-07 08:09:59,705: custodian.policy:INFO policy: fsx resource:fsx region:us-east-1 count:1 time:0.18
2019-02-07 08:09:59,707: custodian.output:DEBUG metric:ResourceCount Count:1 policy:fsx restype:fsx scope:policy
2019-02-07 08:09:59,707: custodian.output:DEBUG metric:ApiCalls Count:1 policy:fsx restype:fsx
(custodian) kapilt@realms-scythe ~/p/custodian> custodian run -c arg.yml -s out -v -r us-west-1
2019-02-07 08:10:09,723: custodian.commands:DEBUG Loaded file arg.yml. Contains 1 policies
2019-02-07 08:10:09,855: c7n.policies:WARNING policy:fsx resources:fsx not available in region:us-west-1
2019-02-07 08:10:09,855: custodian.commands:WARNING Empty policy file(s).  Nothing to do.
```

**Comment by ssteo** [comment]
I notice the following error even using the latest boto SDK.

2019-02-07 15:38:04,282 - custodian.output - ERROR - Error while executing policy
Traceback (most recent call last):
  File "/var/task/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/var/task/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/var/lang/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/botocore/httpsession.py", line 258, in send
    decode_content=False,
  File "/var/task/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/var/task/urllib3/util/retry.py", line 343, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/var/task/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/var/task/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/var/task/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/var/task/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/var/task/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/var/task/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x7f1ae337e518>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/c7n/policy.py", line 232, in run
    resources = self.policy.resource_manager.resources()
  File "/var/task/c7n/query.py", line 412, in resources
    resources = self.source.resources(query)
  File "/var/task/c7n/query.py", line 226, in resources
    return self.query.filter(self.manager, **query)
  File "/var/task/c7n/query.py", line 88, in filter
    getattr(resource_manager, 'retry', None)) or []
  File "/var/task/c7n/query.py", line 70, in _invoke_client_enum
    data = op(**params)
  File "/var/task/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/botocore/client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "/var/task/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/var/task/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/var/task/botocore/endpoint.py", line 137, in _send_request
    success_response, exception):
  File "/var/task/botocore/endpoint.py", line 231, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/var/task/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/var/task/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/var/task/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/var/task/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/var/task/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/var/task/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/var/task/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/var/task/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/var/task/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/var/task/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/var/task/botocore/endpoint.py", line 244, in _send
    return self.http_session.send(request)
  File "/var/task/botocore/httpsession.py", line 278, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://backup.sa-east-1.amazonaws.com/backup/plans/"

Seems that some certain resource type in region doesn't have a valid hostname and the exception is thrown all the way up to c7n.

**Comment by kapilt** [comment]
Could post one of these policy, and the cli your using to run (sans account info)? Are you deploying the policy sa-east-1 in lambda? or reaching out from a lambda in another region?

**Comment by ssteo** [comment]
Hi, below is the policy I'm using. One of our scan is to look for resources outside of EU regions, so we generate a list of policies based on the list of resources output from `custodian schema`.

```
policies:
  - name: backup
    resource: backup
    filters:
      - "tag:NonExistent": absent
```

Unfortunately, we're not using the cli but programmatically similar with the way how cli invoke run() and we run them in Lambda:

```
    options = argparse.Namespace(
        account_id=aws_account_id,
        assume_role=CUSTODIAN_SCANNER_ROLE_ARN_FORMAT % aws_account_id,
        cache=None,
        cache_period=0,
        command=u'c7n.commands.run',
        config=None,
        configs=['%s%s.yaml' % (LAMBDA_TEMP_PATH, policy_name)],
        debug=False,
        dryrun=True,
        external_id=None,
        log_group=None,
        metrics_enabled=False,
        output_dir=output_path,
        policy_filter=None,
        profile=None,
        quiet=None,
        regions=[region_name],
        resource_type=None,
        subparser='run',
        tracer='default',
        vars=None,
        verbose=None
    )
    run(Config.empty(**vars(options)))
```

We don't deploy the Lambda in all region, only in EU region and assume role into multiple accounts using IAM role with necessary permission to look for resources in non-EU regions.

Does this information help?

**Comment by kapilt** [comment]
As i noted in the other issue you filed about your custom code not working #3494, custodian is distributed as an application, it does not have a public api for library usage. I've already demonstrated in this issue that custodian works as expected for this scenario. If your want to use custodian as a library your welcome to, but its not something that is supported by the project,  please stop filing issues about problems with your custom code. 

If you'd like to contribute to custodian,  then opening issues/prs about supporting new features is a much better way to avoid getting stuck in a dead end wrt to custom integration code. Alternatively use one of the supported integration mechanisms like, invoke-lambda action or value_from.

**Comment by ssteo** [comment]
@kapilt  I'm trying to find alternative way to integrate and run with Lambda but couldn't that's why I looked into cli.py code and integrate it this way. You've mentioned about the `invoke-lambda` and `value_from`, may I know if that's documented somewhere? I didn't see something like this in the documentation.

**Comment by ssteo** [comment]
Anyway, sorry for filing the issue earlier as I didn't know it was caused by custom code integration directly with c7n.commands..

**Comment by kapilt** [comment]
if you want to file an issue with your trying to do/achieve with your custom code that might be a good starting point for discussing a feature that would be useful to other users for the custodian application. At the moment its unclear what your actually trying to do with your custom code, so there

both the integration mechanisms (invoke-lambda action, value_from on `value` filter) are documented in custodian schema, and show up in search on the doc site afaics.

**Comment by ssteo** [comment]
Ok, what we're doing currently is that we have implemented quite a number of security scans on top of c7n and it (our custom code + c7n) runs fully in Lambda. The `invoke-lambda` looks like is used for invoking-lambda and passing the output to it? That's not the kind of integration we're looking for, we are running our custom code + c7n fully in AWS Lambda function not on our local machine or EC2.

We have proper SQS and periodic CloudWatch event trigger that takes job from SQS to scan on target account as we have a significant number of AWS accounts across our org. ( > 100). Whenever the CloudWatch event triggers the Lambda, our code that wraps c7n checks SQS for any job and runs the scan inside Lambda (if job found) and writes the output to Lambda's /tmp storage and we ingest the output from there then our custom code process, reformat and store the output in our central reporting system.

The reason we're implementing on top of c7n.commands module instead of invoking cli.py:run() as a command-line tool is due to the code gets very hackish the moment when we want to run it in Lambda environment.

The policy described above is one of our compliance scan where we look for resources created outside of EU region as to fulfill GDPR requirement by ensuring there is no data being stored/handled outside of EU region. But other than that, we also have implemented a lot of different other scans on S3 bucket, open security groups, etc.

**Comment by kapilt** [comment]
okay so the custom code is to hook up to sqs, invoke periodic mode, and then slurp the output is what i'm hearing. decoupling the custom logic is probably going to be of some help (ie store output to s3, and then have bucket notification trigger lambda ingest into central reporting). 

the other part of that sounds like its satisified by the periodic mode supporting multi account on a more generic basis (similiar to centralized account support we do for trail based policies). 

A couple of other questions, is the sqs stuff meaningful? versus just doing the periodic cwe trigger? decoupling that to just invoking the periodic lambda might be more useful. its also a bit unclear on the scope of a single lambda execution, as a single region and policy?  do you ever get timeouts in lambda due to resource count cardinalities meaning there's too much work for it?

**Comment by ssteo** [comment]
We didn't get timeout as we split our policy to small policies so every resource type and every region are executed as an isolated lambda invocation to run c7n for each resource in each region. The GDPR scan is the scan type we rely most on c7n because it helps us to simplify the task of enumerating all kinds of resources instead of manually finding them out through boto3 API (at the moment Lighsail resource is not supported so this is something we're trying to list/scan those resources manually).

Other than that, a lot of our security scans we just use c7n as a higher level or simplified of boto3 in a way to obtain resources like security groups, ec2, etc. then we parse those output json to look for the stuff we want to report (e.g. security groups attached to ec2 having ingress rule of 0.0.0.0/0 or s3 bucket having bucket permission of Acl-READ/Acl-WRITE for AllUsers or AuthenticatedUsers, etc.).

The architecture is currently decoupled, instead of storing in S3, we are storing them in a DynamoDB table where end of the execution we consolidate all the findings to generate report from the table. The output and ingestion of the c7n findings is not an issue, we intentionally make c7n output to /tmp of Lambda as file then read instead of using S3 due to simplicity of implementation and we do not need to clean up the S3 bucket.

We did try to wrap cli.py before but encountered some issues I could not recall, hence the reason we're wrapping c7n.commands.run directly. At the moment, this implementation runs fine on v0.8.40.0 after we excluded the following resource types. We will debug further later on to find out why and what's the difference of our wrapper compared to cli.py.

    'backup-plan',
    'cloudhsm-cluster',
    'dlm-policy',
    'fsx',
    'fsx-backup',
    'glue-dev-endpoint',
    'lambda-layer',
    'ssm-activation',
    'ssm-managed-instance',
    'transit-attachment',
    'transit-gateway'

The periodic mode trigger is very important to us because enumerating resources across all region involves a lot of AWS API invocation, which also means if we do it too fast we can easily hit the AWS API rate limit. Hence, we intentionally use CloudWatch event to trigger out Lambda periodically to get a job from SQS and to run specific scan on an account and region instead of a concurrent rush to scan every region in parallel.

**Comment by kapilt** [comment]
api rate limits are segmented by account and region, so doing a parallel scan is fine across those boundaries. re lightsail, sounds like an opportunity to contribute, i merged in some basic support for lightsail resources, but in general its straightforward to add in basic support, and if your going to be coding a bunch of custom stuff, getting it into custodian would decrease your support burden 🤷‍♂️

**Comment by ssteo** [comment]
That's cool. I'll try to test out on Lightsail resources and create PRs if I could in the coming weeks. Thanks!

**Comment by kapilt** [comment]
wrt to an api form the closest thing we have that might be appropriate is the c7n/handler buts its not intended as general purpose, and it comes with various caveats that seem roughly equivalent to some of the issues your having today (region resource filtering by availability, etc), but those can be improved in tree.
