### ISSUE TITLE
DynamoDB Policy Error

### ISSUE THREAD

**Issue by mason67git** [cloud-custodian/cloud-custodian#3514]
Hi,

I have made this rule which worked for a few weeks:

```
policies:
  - name: untagged-dynamodb-delete
    resource: dynamodb-table
    mode:
     type: cloudtrail
     events:
     - CreateTable
     role: arn:aws:iam::{account_id}:role/cloudcustodian_lambda_role
     tags:
      Name: Untagged_DDB_Rule
      Role: CloudTeam
      Contact: CloudTeam
      Project: Custodian
      Owner: CloudTeam
      Team: CloudTeam
      Client: CloudTeam
    filters:
     - "tag:Name": empty
     - "tag:Role": empty
     - "tag:Contact": empty
     - "tag:Project": empty
     - "tag:Team": empty
     - "tag:Owner": empty
     - "tag:Client": empty
     - "tag:Environment": empty
    actions:
     - delete
```

But now when this rule finds an untagged table it outputs this error in the cloud watch logs:
"An error occurred (ResourceNotFoundException) when calling the ListTagsOfResource operation: Requested resource not found: ResourcArn: arn:aws:dynamodb:eu-west-1:12345678910:table/ddb-rule-test not found"

**Comment by kapilt** [comment]
first your policy isn't safe to use, DynamoDB tables can't be tagged on create, so this would end up deleting all new tables https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html


second, dynamodb resources are a little different then post in that they don't support being tagged or fetching tags for them till while pending. there's a change in trunk to switch to resource group tagging api which means there wouldn't be an error fetching tags for them. 

There's some discussion if we need to hack in a sleep specific to dynamodb to avoid some of these issues #3177
