### ISSUE TITLE
c7n_mailer GovCloud issue-Incorrect padding

### ISSUE THREAD

**Issue by fidelito** [cloud-custodian/cloud-custodian#3526]
I used the same mailer lambda function from my regular AWS account and copy it into GovCloud account. I made sure that it matches and made the appropriate config changes (use the right gov cloud queues except ses is not available)

I get this errors and please let me know if I forgot to add any info.

[WARNING]	2019-02-14T13:42:35.131Z	Unknown sqs_message or sns format testing
[ERROR]	2019-02-14T13:42:35.131Z	Error starting mailer MailerSqsQueueProcessor(). 
Error: Incorrect padding 

Traceback (most recent call last):
File "/var/task/c7n_mailer/handle.py", line 46, in start_c7n_mailer
mailer_sqs_queue_processor.run(parallel)
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 126, in run
self.process_sqs_message(sqs_message)
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 145, in process_sqs_message
sqs_message = json.loads(zlib.decompress(base64.b64decode(body)))
File "/usr/lib64/python2.7/base64.py", line 78, in b64decode
raise TypeError(msg)
TypeError: Incorrect padding

**Comment by kapilt** [comment]
that looks more like some other piece of software dropped a message in the queue that wasn't from custodian, if you have a dead letter queue it will purge out automatically, else it requires manual removal.
