### ISSUE TITLE
config-rule unable to invoke lambda

### ISSUE THREAD

**Issue by lanejlanejCH** [cloud-custodian/cloud-custodian#3530]
I am obviously doing something badly wrong here.  But, I can't identify what it is.

I have a CloudCustodian policy with a mode statement as follows:  

mode: {role: 'arn:aws:iam::{account_id}:role/CustodianLambdaRole', timeout: 300,
    type: config-rule}

and, the role has 'config:Put*' permissions. But, when I run custodian I see the following sort of error messages:
InsufficientPermissionsException: An error occurred (InsufficientPermissionsException) when calling the PutConfigRule operation: The AWS Lambda function arn:aws:lambda:eu-west-1:<account id>:function:custodian-s3-bucket-encryption-policy-absent cannot be invoked. Check the specified function ARN, and check the function's permissions.

I note that the policy associated with the lambda function has events.amazonaws.com as the only principal for the lambda:InvokeFunction policy statement. Is that right?

BTW the same CloudCustodian policy works fine in periodic mode, when custodian is run in the same way.

Any help/clues appreciated.

**Comment by kapilt** [comment]
the errors is with the permissions of the credentials your invoking the cli with it looks like, which does not have permission to deploy the policy lambda as a config rule, not with the role the lambda will run with.

**Comment by lanejlanejCH** [comment]
Ah. Realised my error. I had modified an existing policy and updated via custodian which doesn't work. Now I have deleted the original policy (and updated via mugc) and created afresh, and all is well. So, I am closing this.

**Comment by mmichee** [comment]
i have the same problem and i don't understand what's permission i need.
on the lambda i put full admin access and my account have full admin acces and i have the same permissions error.
can you help me please?
