### ISSUE TITLE
c7n-mailer - Error InvalidClientTokenId

### ISSUE THREAD

**Issue by c8w** [cloud-custodian/cloud-custodian#3548]
Command executed:
c7n-mailer --config mailer.yml --update-lambda && custodian run -c mailer-test.yml -s .

mailer.yml file:
queue_url: https://sqs.us-east-1.amazonaws.com/<acct>/cloud-custodian-mailer
role: arn:aws:iam::<acct>:role/c7n_lambda
from_address: example@example.com
region: us-east-1

ERROR OUTPUT:
2019-02-19 09:28:52,453: custodian.policy:INFO policy: c7n-mailer-test resource:sqs region:us-east-1 count:3 time:0.87
2019-02-19 09:28:52,769: custodian.output:ERROR Error while executing policy
...
**ClientError: An error occurred (InvalidClientTokenId) when calling the ListAccountAliases operation: The security token included in the request is invalid**

Also, how to best/properly use:  c7n-mailer-reply?

**Comment by kapilt** [comment]
invalid token implies you don't have valid client credentials interact with the aws apis. i would check your local environment variables `env | grep AWS` to make sure their set appropriately.

**Comment by knelyoo** [comment]
working on implementing c7n-mailer in aws gov cloud where  SES service is not available, Fortunately c7n-mailer support splunk HEC. I tried the setup for c7n-mailer with Splunk HEC but i keep getting a similar error 
**botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the ReceiveMessage operation: The security token included in the request is invalid**

aws_default_profile and region is confirmed setup.

Any pointer will be helpful
