### ISSUE TITLE
Azure - Remove AzureWebJobsDashboard from Functions

### ISSUE THREAD

**Issue by aluong** [cloud-custodian/cloud-custodian#3551]
We use App Insights for logging and monitoring, so we can disable the built in logger for Functions:
- https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#disable-built-in-logging
- https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#azurewebjobsdashboard

**Comment by kapilt** [comment]
i'd consider it making an option to retain this, if folks are used to this as part of the native function experience, it might be a general expectation that it will be available for all functions.

**Comment by aluong** [comment]
This is monitoring feature not meant for production workloads and people should be using App Insights.

https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#disable-built-in-logging
