### ISSUE TITLE
Output of one resource be the input for other resource?

### ISSUE THREAD

**Issue by mkadali99** [cloud-custodian/cloud-custodian#3557]
Can filter output on one resource be the input for other resource?
Like filter for EC2 instances which are stopped and encrypt EBS volumes of that stopped instances. Is that possible?

**Comment by kapilt** [comment]
there's a set of related filters that enable these set of use cases, ie. ebs resource has an `instance` filter that pulls information on the attached instance. so you can target unencrypted attached volumes of an stopped instance with that.
