### ISSUE TITLE
dropping support for python 2.7 by end of 2019

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#3558]
python 2.7 is EOL at the end of the year (2020/1/1 officially), we should look at dropping support for it. Given custodian's user population, their will likely be some users that have some pain points for this and are using their  distro supplied python support to use py2.7 for a few more years (aka redhat/ibm ;-). We should direct them to using docker if they want a current version of custodian.

In terms of improvements, it will let us drop some of our six compatibility layers, simplify the build matrix in ci, and potentially look at tools like fastjsonschema for faster validation on the cli.

there isn't any burning need here yet, but its likely that some of our dependencies will start dropping py 2.7 support over the coming year as well, which will force the issue for us to more dependency pinning (tech debt).

the only py 2.7 only program we carry and support atm is tools/c7n_salactus, which will need some updates for py 3 compatibility.

**Comment by nitrocode** [comment]
^ I think you meant

> python 2.7 is EOL at the end of the year **2019** which is **2020**/1/1 officially

**Comment by kapilt** [comment]
updated, thanks

**Comment by thisisshi** [comment]
Docs have been mostly updated to reference python3 where ever possible, additionally moving lint from python2 to python3 in #3996

**Comment by stefangordon** [comment]
Curious about updated thoughts on timing here? 

Are we just going to keep supporting up until New Years Eve then remove the CI builds and start leveraging Py3 syntax wherever our we like? 🤞

**Comment by kapilt** [comment]
The boring version is just that, news year day we remove from ci, and start cleaning up. We note the last release before then as the final version with support for 2.7. Ideally in the next month or two we document the default install via docker and cask. I've looked at the download numbers and frankly its still pretty neck and neck for custodian on 2 vs 3 downloads. One downside to using docker hub is we loose download visibility tracking beyond just a counter, we're also having visibility issues on docker hub due to not publishing for a while with lots of forks extant.

The more interesting version is that our dependencies start dropping support for 2.7 before we do.
Generally that would mean moving to pinned dependencies sets in setup.py which ideally we'd consider doing as well for the final release with support for python 2.7. Unfortunately thats going to be a bit painful without automation, which we can't enable cleanly on this repo due to capitalone's overreach.

**Comment by CMeza99** [comment]
Can we start removing support for py27? This may help simplify some of the code base.

**Comment by kapilt** [comment]
a couple of thoughts on this

- the predominant source of python2.7 in the world is enterprise linux vendors (rhel, suse predominantly, ubuntu's been on python 3 for a few years) that have 5-10 year support setups with their users.
- roughly 10-20% of the c7n downloads on a given day are for python2
- we need to update packaging metadata to denote the required version when publishing (trove classifier, and python_requires)
- the 0.8 release branch is still supported for python 2.7
- we need to produce a 0.8 release w/ 2.7 support that freezes the recursive dependency graph, so those
   packages
- for the 0.8 branch we'll need a python 2.7 test runner
- i'm not sure that we realize that much simplification from py3, but it does allow us to start using py3 features more readily (typing, dataclasses, etc).

**Comment by kapilt** [comment]
interestingly python 3.5 is actually a significant portion of installs (its risen to >50% this month) , even though its not an official supported version :-(

**Comment by nitrocode** [comment]
Couldn't a warning be written that the custodian pip package for pre3.7 will be disabled by XYZ date to get more people to migrate to the python 3.7+ package ?

**Comment by kapilt** [comment]
we do support 3.6, we'll have to play around with message in setup.py re unsupported versions. again most users don't control this stuff, their just using their enterprise linux distro approved in their org, and trying to use custodian.  i've also realized we should be moving things from sdist to also publishing wheels which don't require the code execution on install, and we can add the publishing metadata (trove classifiers, python_requires) such that they only work for supported versions. thats the same transition plan for dropping py3. but i'm concerned if we're orphaning half a users by doing that, and want to procede with some caution.

**Comment by CMeza99** [comment]
FYI: At this time, `pthon_requries` does not have 3.5. https://github.com/cloud-custodian/cloud-custodian/blob/0b8e7d84c0cc18c6e89e126b77e5532cd1590871/setup.py#L29. Nor is it in the trove classifiers.

**Comment by kapilt** [comment]
its done, latest release 0.9.1 no longer supports python 2.7
