### ISSUE TITLE
sensu provider

### ISSUE THREAD

**Issue by benpillet** [cloud-custodian/cloud-custodian#3563]
I'm working in an environment with approximately 5000 sensu clients. I'd love to have a provider for it in cloud custodian. And I'm up for drafting one. Would others find this useful?

My initial thought is that we have stale alerts and stashes that linger and need to be cleaned up.  Filtering/emailing/alerting the owners would be super helpful.

**Comment by kapilt** [comment]
the go version of sensu or ruby? i get the sensu is a fairly minority player in the monitoring space.

**Comment by kapilt** [comment]
i don't know that we really want to go after every platform under the sun. larger platforms from a number of users are probably of more interest. its of course possible to do an out of tree provider as well, and for some of the platforms that are more niche, thats probably a better start point. linux kernel style, less proposals more working code ;-)
