### ISSUE TITLE
EC2 instances detected before tags are propagated from ASG

### ISSUE THREAD

**Issue by cbarensfeld** [cloud-custodian/cloud-custodian#3571]
I have a policy that checks EC2 instance tags on launch using cloudtrail. Is there a way to ignore EC2 instances that are launched from the user AutoScaling? My lambda functions are executing before my auto scaling group can propagate the tags. Thanks.

**Comment by kapilt** [comment]
use the `event` filter to filter resources based on properties/attributes of the invoking event . note that using the event filter will mean the policy is not portable across different policy execution modes (aka non lambda), event filters are ignored during dryrun.
