### ISSUE TITLE
post-finding failed action: maximum of 10 IPv4 addresses

### ISSUE THREAD

**Issue by xgarcias** [cloud-custodian/cloud-custodian#3575]
Hi,

The finding format in Security Hub defines a maximum of 10 IPv4 addresses in `Resource.Details.AwsEc2Instance.IpV4Addresses` but the resource **ec2** (/c7n/resources/ec2.py) doesn't limit the list in the class **InstanceFinding**

See https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-findings-format.html

A dirty workaround is to change the code as below. I ignore if jmespath.search can limit the result:

```
            "IpV4Addresses": jmespath.search(
                "NetworkInterfaces[].PrivateIpAddresses[].PrivateIpAddress", r
            )[0:9]
```

```
FailedFindings': [{'Id': 'eu-central-1/897816849202/61d1691981c34026571dfa7b356f679b/f33f01673d01baefed3cce37deb0b59a', 'ErrorCode': 'InvalidInput', 'ErrorMessage': 'Finding does not adhere to Amazon Finding Format. data.Resources[0].Details.AwsEc2Instance.IpV4Addresses should NOT have more than 10 items'}]
```

**Comment by kapilt** [comment]
thanks for the bug report, `[:10]` should do it, although i'm not a huge fan of arbitrary data omission,  given the service limitation and the relative infrequency of the condition, its unclear that we can do anything else that would be better.
