### ISSUE TITLE
Filter on AMI Name instead of tag:Name ?

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#3581]
Is there a way to filter on the AMI Name instead of the tag:Name ?

**Comment by kapilt** [comment]
the default `value` filter can filter on any attribute of a resource, it has both short form (k: v pair) long forms (type: value for additional configuration like use a regex, sourcing values from s3, etc). See docs https://cloudcustodian.io/docs/filters.html#value-filters

you didn't reference if this was a policy on a ami.  but its quite literally just `Name: Ubuntu1404`

in general these type of getting started help questions, are better serviced by asking on gitter channel, referenced from the project readme.
