### ISSUE TITLE
salactus doesn't scan on unversioned buckets

### ISSUE THREAD

**Issue by wangm8** [cloud-custodian/cloud-custodian#3602]
`c7n-salactus run` doesn't scan buckets with versioning disabled. When calling run with --debug tag, it shows keyset value as 0 when there are items in the bucket. 
<img width="746" alt="screen shot 2019-03-01 at 12 44 52 pm" src="https://user-images.githubusercontent.com/32623164/53652679-d95e4f00-3c1f-11e9-97b9-a1daca4e3bfb.png">
<img width="443" alt="screen shot 2019-03-01 at 12 45 18 pm" src="https://user-images.githubusercontent.com/32623164/53652714-e7ac6b00-3c1f-11e9-8583-49e385ab4051.png">

**Comment by kapilt** [comment]
keycount is picked up from cloud watch metrics, which are a day delayed, that metrics is just used a heuristic for various scanning strategies based on size, its not material to whats actually scanned. ie. that log message is prior to the scan.

**Comment by kapilt** [comment]
also for very large buckets (10s of millions, billions of objects), its recommended to setup s3 inventory, to speed up the scans, salactus should auto detect inventory is available and consume if it if it has access.

**Comment by wangm8** [comment]
Ah, thanks - I checked it this morning and the objects are showing now. And thanks for the suggestion!
