### ISSUE TITLE
aws.asg - not-encrypted filter removed error handling for missing AMI's

### ISSUE THREAD

**Issue by thisisshi** [cloud-custodian/cloud-custodian#3629]
in this commit:

https://github.com/cloud-custodian/cloud-custodian/commit/45d059bccc77df01f79256816038731d2756b12f#diff-8d7e1840f31e642d80e0fe0b85ef0324L266

the error handling for missing AMI's was removed, in the case that AMI's are not found, this will result in the ASG being filtered in as being not-encrypted rather than raising (per the previous behavior)

**Comment by kapilt** [comment]
@jtroberts was noting issues for invalid as well on image.

**Comment by kapilt** [comment]
Are there any logs or trace backs for when this exhibits?

**Comment by kapilt** [comment]
the error handling for missing amis i found was out dated wrt to current api behavior, ie. the api doesn't return errors/exceptions on those anymore the same way that it would on a snapshot. i tested fetching a thousand amis with a single api call (aka no pagination needed), and 5 that were bad ami ids, and it returned all the ones extant and omitted the ones not found. the snapshot not found case was explicitly handled, bad amis just don't get returned by the api. there's definitely an issue here though, but we need more data to correlate to cause and solution.

**Comment by kapilt** [comment]
it looks like there is some region specific behavior to the api response.


in us-east-1 it will just omit the bad image id from the output

```
$ aws ec2 describe-images --owner=self  --image-ids ami-123f000c8c1f9f654  --region us-east-1
{
    "Images": []
}

```

in other regions it will report as an invalid ami id.
```
$ aws ec2 describe-images --owner=self  --image-ids ami-123f000c8c1f9f654  --region us-east-2

An error occurred (InvalidAMIID.NotFound) when calling the DescribeImages operation: The image id '[ami-123f000c8c1f9f654]' does not exist
$ aws ec2 describe-images --owner=self  --image-ids ami-123f000c8c1f9f654  --region us-west-2

An error occurred (InvalidAMIID.NotFound) when calling the DescribeImages operation: The image id '[ami-123f000c8c1f9f654]' does not exist

```
