### ISSUE TITLE
S3 has-statement filter is missing interpolation

### ISSUE THREAD

**Issue by claque2000** [cloud-custodian/cloud-custodian#3650]
When using has-statement filter with Resource parameter, using {bucket_name} in filter makes it fail. During statement parameters comparison, bucket_name is not interpolated and the filter never match.

**Comment by kapilt** [comment]
yeah we only do global interpolation on a handful of variables (account_id, etc). specific filters and actions do support additional ones. it seems useful to add in bucket name, but note that its possible to use various suffixes.

**Comment by claque2000** [comment]
Yes, I saw that the bucket_name interpolation is done on set-statements action.
