### ISSUE TITLE
S3 lifecycle policy transition based on last accessed date

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#3664]
I’m looking into S3 lifecycle policies and found that because we have so much cleanup of tech debt in S3, it would be safer for us to only lifecycle s3 objects if we know they haven’t been accessed in X days. It looks like this is possible using Amazon S3 Storage Class Analysis but we’d have to hit the API to download a CSV, then parse the information, and then apply the s3 life cycle policy based on that.

Source: https://stackoverflow.com/a/53129142/2965993

**Comment by kapilt** [comment]
Also worth looking at intelligent storage class https://aws.amazon.com/about-aws/whats-new/2018/11/s3-intelligent-tiering/

wrt to storage class analysis, per object analysis is data plane analysis, not control plane which is what custodian typically does. for s3 data plane analysis we typically utilize tools/c7n_salactus as it handles distributed scale out. Its also unclear what the heuristic is that would determine the storage class, do you have an example of the logic you would use with a storage class analysis record. salactus is pluggable with visitors, and this sounds like it would be appropriate for that if we can reflect the decision tree on storage class to config.

**Comment by nitrocode** [comment]
I'll take a look at salactus and s3 intelligent tiering then. Thank you.
