### ISSUE TITLE
Policy validation should raise an error if multiple "policies" statement usage

### ISSUE THREAD

**Issue by claque2000** [cloud-custodian/cloud-custodian#3668]
In case of multiple "policies:" statements in a policy file, c7n only deploys those under the last "policies:" and not the one in previous without raising a warning or an error. 
I think this should raise an error in validation phase.
For example:
```
policies:
    - name: some name
    ....
policies:
    - name: another name
   ....
```
Only the policy named "another name" will be deployed/run

**Comment by kapilt** [comment]
That sounds useful, effectively detect and warn/raise on duplicate keys in a mapping.

**Comment by kapilt** [comment]
One other consideration here it may very well lead to flagging some policy files as incompatible/errors. ie. this is likely a place where we should have differential behavior for run and validate (both of which run jsonschema validation). For run its likely that this would lead to compatiblities issues in unattended systems. For validate which is typically run in ci systems for policies this seems okay.

**Comment by claque2000** [comment]
IMHO, if you put multiple "policies:", it should be an error on validate and run. Because, if validate turns to say everything fine, at run, it will run/deploy half of the policies

**Comment by kapilt** [comment]
i definitely understand that perspective but the concern is that with run this is a behavior change that could break extant deployments. ie i upgrade custodian and my policies don't run anymore, except it was a cron job, unattended. i think we can log warnings on run, and errors on validate.
