### ISSUE TITLE
c7n-org Cross Many Accounts, Mugc doesnt support the same accounts.yml file 

### ISSUE THREAD

**Issue by stevegroner** [cloud-custodian/cloud-custodian#3680]
We are currently deploying policies across 50+ aws accounts using c7n-org.  This works great since we can maintain and accounts file and select the policies we want applied.  However, the mugc tool written does not support the same accounts.yml file which means I would have to know which accounts exist in some other way.  Do you have a solution to remove lambdas in my 50+ accounts that is no longer in the policy list I just ran using c7n-org?  I really want to use this but it is going to be difficult having possibly orphaned lambdas in all of the account that is no longer needed.

**Comment by kapilt** [comment]
use `c7n-org run-script` with mugc

**Comment by stevegroner** [comment]
Is it a separate run of c7n-org org can i add run and run script in the same command?


Steve

On Mar 15, 2019, at 4:39 AM, Kapil Thangavelu <notifications@github.com<mailto:notifications@github.com>> wrote:


use c7n-org run-script with mugc

**Comment by Steve-Groner** [comment]
Do you have an example of running mugc.py as a run-script for c7n-org.  I am struggling with the syntax as it seems like parameters overlap.  I simply want to execute c7n-org with the -c accounts.yml and the -u policy.yml.  Then I want mugc to run through the same accounts and remove the lambdas no longer needed .  Thank you in advance.

**Comment by kapilt** [comment]
something like this `c7n-org run-script -r us-east-1 -r us-west-2 -s runoutput -c accounts.yml "$PATH/to/python mugc.py -c config1.yml -c config2.yml --dryrun"`


the quotes are needed due to the overlapped cli params

**Comment by JustinPullen** [comment]
@Steve-Groner Did you ever run Kapilit's example and did it work for you.  I have tried to run it several times and can not seem to get the pattern correct/the script does not take any actions against my environment even when I remove a region from the accounts.yml.

**Comment by kapilt** [comment]
removing regions won't remove cause any changes. regions tells the tooling which regions they should operate to find things to garbage collect.. if you want to see it do work, try removing/commenting out a lambda policy in your policy config file, and do --dryrun to see that it would trigger.

**Comment by JustinPullen** [comment]
@kapilt Thanks for the direction.  I was finally able to get it rolling after a little tweaking and making sure there was more than 1 policy in my config file.

**Comment by ahmadzaikk** [comment]
@kapilt 

I am getting the following error when I try to run 7n-org run-script


c7n-org run-script -r us-east-1  -s output/ -c accounts.yml  "python /home/kh/aws/accounts/cloud-custodian/tools/ops/mugc.py  -c aws-root-login.yml --dryrun "
2021-03-02 15:42:22,805: c7n_org:INFO running script on account:chs-dev region:us-east-1 script: `python /home/kh/aws/accounts/cloud-custodian/tools/ops/mugc.py -c aws-root-login.yml --dryrun`
2021-03-02 15:42:24,394: c7n_org:INFO error running script on account:chs-dev region:us-east-1 script: `python /home/kh/aws/accounts/cloud-custodian/tools/ops/mugc.py -c aws-root-login.yml --dryrun`

**Comment by kapilt** [comment]
you'll have to produce the actual error message from within the output dir re stderr

**Comment by ahmadzaikk** [comment]
@kapilt 
Thanks for the quick respond, following is the error from stderr

Traceback (most recent call last):
  File "/home/khalid/aws/accounts/cloud-custodian/tools/ops/mugc.py", line 221, in <module>
    main()
  File "/home/khalid/aws/accounts/cloud-custodian/tools/ops/mugc.py", line 211, in main
    p for p in load_policies(
  File "/home/khalid/aws/accounts/cloud-custodian/tools/ops/mugc.py", line 29, in load_policies
    policies += policy_load(config, f).filter(options.policy_filter)
  File "/home/khalid/.local/share/virtualenvs/cloud-custodian-demo-pOPjgdmJ/lib/python3.9/site-packages/c7n/policy.py", line 38, in load
    structure.validate(data)
  File "/home/khalid/.local/share/virtualenvs/cloud-custodian-demo-pOPjgdmJ/lib/python3.9/site-packages/c7n/structure.py", line 44, in validate
    raise PolicyValidationError((
c7n.exceptions.PolicyValidationError: `policies` key should be an array/list found: NoneType

**Comment by kapilt** [comment]
your second -c should be a -u re aws-root-logins.yml

**Comment by ahmadzaikk** [comment]
@kapilt 

i changed my second -c to -u now i am getting the following error


(cloud-custodian-demo) khalid@ITS:~/aws/accounts/cloud-custodian/tools/ops$ cat output/chs-dev/us-east-1/stderr
usage: mugc.py [-h] [-c [CONFIG_FILES ...]] [--present] [-r REGION] [--dryrun]
               [--profile PROFILE] [--prefix PREFIX]
               [--policy-regex POLICY_REGEX] [-p POLICY_FILTER]
               [--assume ASSUME_ROLE] [-v]
               [configs ...]
mugc.py: error: unrecognized arguments: -u

**Comment by ahmadzaikk** [comment]
@kapilt 

Thanks Kapilt, issue resolved, i had issue with my policy file.
