### ISSUE TITLE
c7n-org run command error not finding profile

### ISSUE THREAD

**Issue by fidelito** [cloud-custodian/cloud-custodian#3687]
When running c7n-org I get an error that it can't find the profile.
The profile is in ~/.aws/credential
custodian run --profile       works fine in finding the profile

c7n-org run  -c accounts.yml -t type:dev -r eu-west-1  -u /path/policies/ec2-tag-requirement-check.yml -s /path/reports/ -v
2019-03-15 19:02:57,503: c7n_org:DEBUG Running policy:ec2-tag-requirement-check account:ACCOUNT NUMBER region:eu-west-1
2019-03-15 19:02:57,521: c7n_org:ERROR Exception running policy:ec2-tag-requirement-check account:ACCOUNT NUMBER region:eu-west-1 error:The config profile (ACCOUNT NUMBER) could not be found
2019-03-15 19:02:57,559: c7n_org:INFO Policy resource counts Counter()

accounts.yml file

accounts:
- account_id: 'ACCOUNT NUMBER'
  name: 'ACCOUNT NUMBER'
  profile: 'ACCOUNT NUMBER'
  tags:
  - type:dev
  - division:division

ec2-tag-requirement-check-report.yml:

vars:
  tag-filters: &tag-compliance-filters
       - "tag:market": present
       - "tag:product": present
policies:
- name: ec2-tag-requirement-check
  resource: ec2
  filters:
     - or: *tag-compliance-filters
  actions:

**Comment by kapilt** [comment]
is your profile defined in ~/.aws/config or just credentials.. in general this seems like user misconfig, this facility works for others. profile's are names not per se account numbers unless thats how you've named your profiles.

**Comment by fidelito** [comment]
Hi Kapil,

my profile is defined in just the credentials file. I name the profile with the account numbers. The way I have seems to work fine with custodian --profile ACCOUNT_NUMBER

I can try on Monday to split up the credential into config file instead of having it all in one file. 

I am using a python script very similar to the one provided here https://aws.amazon.com/blogs/security/how-to-implement-federated-api-and-cli-access-using-saml-2-0-and-ad-fs/ 

that generates that populates the credential file with everything needed.

**Comment by SamarthUpadhya** [comment]
@fidelito How did you resolve the issue? I am facing similar issue where my profile is not being pulled

Error: no such option: --profile

**Comment by fidelito** [comment]
> @fidelito How did you resolve the issue? I am facing similar issue where my profile is not being pulled
> 
> Error: no such option: --profile

@SamarthUpadhya you need to check  custodian run --help

then you will see --profile as an option
