### ISSUE TITLE
Azure - Feature Request - Firewall rule policies for Storage accounts and Managed services

### ISSUE THREAD

**Issue by justinhauer** [cloud-custodian/cloud-custodian#3690]
### What is being asked
Have the ability to set and enforce firewall policies on managed services (like MSSQL managed instances) and storage accounts via custodian policies. It is my understanding that currently this capability does not exist.

### Why this is important
For consumers of Azure within a given organization, who are looking to utilize managed services, it's hard to enforce correct firewall policies that span storage accounts, and perhaps it shouldn't be expected for all internal customers to get their FW policies correct.

Having this ability to set FW rules on these types of resources would give peace of mind to info sec groups and ensure that solutions created are secure.

**Comment by stefangordon** [comment]
Thanks Justin.  I recently had the same request from another user as well.

**Comment by aluong** [comment]
#3707 should have addressed this feature request. Please re-open if we missed something.
