### ISSUE TITLE
Azure - Feature Request - Effective Route Table

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#3694]
While evaluating network posture filtering on the effective route table is frequently requested data, it may merit a filter.

This is the API:
https://docs.microsoft.com/en-us/python/api/azure-mgmt-network/azure.mgmt.network.v2018_12_01.operations.networkinterfacesoperations?view=azure-python#get-effective-route-table-resource-group-name--network-interface-name--custom-headers-none--raw-false--polling-true----operation-config-

Example use case from user:

> For all network interfaces I need to be able to query the effective routes and validate the following.
> 
> •	That specific virtual network gateway routes exist.
> •	No User defined routes exist

**Comment by wesyao** [comment]
Can't seem to assign this work item to me so...

```
I'm working on it.
```

**Comment by stefangordon** [comment]
Not a contributor yet :)

**Comment by wesyao** [comment]
hey @stefangordon & @logachev , so the effective route table ARM rest API sends back error codes on NICs that fall under these 2 conditions (not exhaustive, I'm sure there are other cases too):
1. NIC is orphans and aren't attached to a VM
2. NIC is attached to a VM, but the VM is off (doesn't have an IP)

There's a couple ways we can handle this within custodian like ignoring these NICs while filtering or printing out the error on the console, but move forward with the other NICs that are working.

What do you guys think?

**Comment by stefangordon** [comment]
Yeah so as a general rule when we are enumerating resources we don't let an error on an individual resource stop us from processing the rest.  In this case it doesn't even sound like an error so much as expected behavior, might just be an `info` level log entry.

That said #1 sounds like an interesting case on its own that I'd want to be able to filter on somehow (orphaned NI) - but likely there are already ways to do this with existing resources/filters.
