### ISSUE TITLE
No documentation for `patch`

### ISSUE THREAD

**Issue by clhefton** [cloud-custodian/cloud-custodian#3699]
I can't figure out how to use `patch` for security groups because there's no documentation so I've resorted to just deleting resources. I can tell it takes a dictionary, but figuring out the required format by reading through the all various functions related to `patch` and `diff` and messing with values is taking more time than it's worth.

**Comment by clhefton** [comment]
Remove-permissions was what I was looking for. (On that note though, I think the docs on the .io site need to be regenerated)

**Comment by kapilt** [comment]
capitalone.io is supposed to be decomm'd but the capitalone folks haven't been able to manage that. cloudcustodian.io are the official docs are autogenerated from source.

**Comment by kapilt** [comment]
#3330
