### ISSUE TITLE
EBS snapshot policy wouldn't delete AMI snapshots

### ISSUE THREAD

**Issue by vikparvat** [cloud-custodian/cloud-custodian#3700]
EBS snapshot policy filters AMI root volume snapshots in spite of setting "skip-ami-snapshots" to 'false'. Resorted to AMI deregister action to delete snapshots going forward, but getting this to work would allow us to clean up old snapshots that don't have AMIs associated with.
### Custodian policy
![image](https://user-images.githubusercontent.com/31968586/54630341-9554b200-4a47-11e9-98ba-4c0e57ae8e5e.png)
### CloudWatch log
![image](https://user-images.githubusercontent.com/31968586/54630581-2c216e80-4a48-11e9-9d16-a51e22d80077.png)

**Comment by kapilt** [comment]
amis strongly reference their snapshots, ie its not possible to delete a snapshot thats in a block device mapping for an ami. you'll need to deregister the ami (latest version of that supports deleting snapshots during deregistration). given this is a service limitation, there's nothing else for custodian to do.
