### ISSUE TITLE
Azure - Feature Request - Tagging resource creator via user mail attribute

### ISSUE THREAD

**Issue by justinhauer** [cloud-custodian/cloud-custodian#3702]
### Description:

Certain organizations may have established use of userprincipalname instead of their mail attribute as the login ID in Azure. Because of this, tagging resources created in azure using the 'creatorEmail' as specified in the documents for custodian Azure does not work  - mail will not be delivered via c7n_mailer as the creator's email specified is incorrect.

#### Example:

I log into o365 and azure with `username@corp.mybusiness.biz` but in actuality, my exchange account/ mail attribute uses `username@mybusiness.com`. 

### What is the ask
having an additional attribute to tag creators of resources based off their mail attribute, so if tagging policies are missed upon resource creation, it is easier to identify the resource owner.

**Comment by justinhauer** [comment]
@stefangordon @aluong Is this too much of an edge case? Having the creator Email piece would be 'a nice to have' and would simplify things, regarding tagging policies.

**Comment by justinhauer** [comment]
#4407 related.

**Comment by stefangordon** [comment]
So it looks like for the event based auto-tagging we give `UPN` priority over emails in the `claims` array - I suspect event based auto-tagging would do what you want then.  If we just do #5297 to use that same function for both event and resource mode then you'd probably get the right behavior.  

That said letting the user pick the field to look at in the action isn't too hard and probably is the best solution for the broadest set of users.

**Comment by justinhauer** [comment]
^ anything that can resolve #4407 would be great, I could reduce a vast amount of my tagging functions and it would really help other policy implementations.
