### ISSUE TITLE
Azure - Feature Request - Ability to define all Azure resource types in AutoTagCreator

### ISSUE THREAD

**Issue by empteSecOps** [cloud-custodian/cloud-custodian#3710]
Our team is looking to implement an Auto Tagging feature however, we can only identify one resource type under the policy. It would be nice to be able to either '*' or 'azure' to select all of the Azure Resource Types. This way tagging is uniform across the entire platform. This can also be ported over to AWS and GCP.

`policies:
  - name: azure-auto-tag-creator
    resource: 'azure.*' or 'azure'
    description: |
      Tag all existing resource groups with the 'CreatorEmail' tag; looking up to 10 days prior.
    actions:
     - type: auto-tag-user
       tag: CreatorEmail
       days: 10`

Thanks!

**Comment by kapilt** [comment]
The current capability/recommend is to write a policy for each resource.

**Comment by empteSecOps** [comment]
Understood but for some companies, it may be worth the installment instead of having to build a policy for every single resource type in Azure. Especially if an organization is standardizing their tagging across the platform, ideally when the code executes, it would be great to have that ability to "select all".

If this isn't of interest in terms of development, please let us know.

**Comment by aluong** [comment]
@empteSecOps you can actually use `azure.armresource`. However, I will note that not all ARM resources support tags and its not clearly documented, so you will need to inspect your logs when you run Custodian. (Ex: OMS workspaces)

**Comment by kapilt** [comment]
Also worth noting you can use yaml anchors and references to remove repetition across a set of policies with similarities. ie. for common filter sets, actions, modes, and even whole policies and then just override on the reference on the specific bits for each policy.

**Comment by empteSecOps** [comment]
We can use anchoring in reducing level of effort in building policies but that still doesn't solve the overall issue I submitted. At the end of the day, tagging on Azure, AWS, or GCP is well documented and should be supported in a seamless uniform policy. If you build the "Azure" resource type to cover all arm resources, then only include resource that support tagging or build a condition that checks for the support of resource tagging.

**Comment by stefangordon** [comment]
Unfortunately the Azure tagging is not quite as clear cut as it should be at this point.  While the tags exist on the generic ARM resource they are not handled consistently, so there has been some struggle to get a universal tagger working the way it should.   The goal is for the resource type `azure.armresource` which correlates to the Generic ARM Resource data type to do this, so I'd recommend testing with that first and we'll file bugs against any issues there.

**Comment by logachev** [comment]
@empteSecOps I merged changes that allow you to write a single policy to auto tag all resources.
Please see an example and read the notes updated in this PR: https://github.com/cloud-custodian/cloud-custodian/pull/4163
