### ISSUE TITLE
aws.workspaces resource support

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#3729]
tag compliance and generic value filter support of attributes from describe_workspaces api

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/workspaces.html

**Comment by ajkerrigan-mdsol** [comment]
Hey @FireballDWF, mind if I take a crack at this one? I've been working with some custom boto3 scripts to fiddle with WorkSpaces recently, and I'd rather replace them with c7n policies :). I don't want to step on your toes if you planned to work on this, but otherwise I'd like to give it a go.

**Comment by kapilt** [comment]
@ajkerrigan-mdsol i talked to @FireballDWF, nutshell, go for it! If you need any help with anything hit me up on gitter or here.

**Comment by ajkerrigan-mdsol** [comment]
Hey @jtroberts83 - I'd definitely like to have that implemented too. I wanted to get some basic functionality up and running first though. At this point it's looking like that basic describe and tag filters are working as expected. I have some docstrings and tests to add though.

I'm thinking that for the connection status info, it probably makes sense to register something like a `connection-status` filter that calls out to `describe_workspaces_connection_status` via `augment`. That way we only pull connection status info when required by the policy filters. Does that seem reasonable @kapilt or @FireballDWF? It seems like that'd work, but even if it does there may be other/better ways to fetch that info that I'm not considering.

**Comment by jtroberts83** [comment]
@ajkerrigan-mdsol  That makes sense to have that as a seperate filter within the resource.  Thanks for your work on this!  Looking forward to getting it tested!

**Comment by kapilt** [comment]
@ajkerrigan-mdsol I'd think it would probably be better as a dedicated filter. Generally we try to limit augments to native attributes or tags, and defer additional api calls to dedicated filters, so the api call usage is only present for policies that actually need it.

**Comment by ajkerrigan-mdsol** [comment]
Hey @jtroberts83 - I've got a draft PR going for the connection status filter. Initial local tests on my end look good, need to pick at it a bit more and add placebo tests though. If you're feeling frisky in the meantime, feel free to give it a spin and let me know if you smell anything burning.
