### ISSUE TITLE
Support for more than one param in URL for  GCP

### ISSUE THREAD

**Issue by mediapills** [cloud-custodian/cloud-custodian#3773]
There are resources with URLs where do we have more than one path parameter and we must have the possibility to manage them in policy definition.  Example Stackdriver Logging resource [here](https://cloud.google.com/logging/docs/reference/v2/rest/v2/billingAccounts.exclusions/list).

There are three options how it  can be implemented:

**Option 1**

- Add additional class **CustomScopeTypeInfo** in tools/c7n_gcp/c7n_gcp/query.py which is represent custom parameters logic for URL where do we have more than one (progect_id, zone_id) parameter in URL.
- Add possibility to manage policy validation schema depend on new additional parameters in URL.
- Add the possibility to extend the scope of parameters for the query.

**[Pull request](https://github.com/mediapills/cloud-custodian/pull/22)**

*Example:*

```python
@resources.register('log-billing-account-exclusion')
class LogBillingAccountExclusion(QueryResourceManager):

    class resource_type(CustomScopeTypeInfo):
        service = 'logging'
        version = 'v2'
        component = 'exclusions'
        enum_spec = ('list', 'exclusions[]', None)
        scope_key = 'parent'
        scope_template = "billingAccounts/{}"
        type_field = 'billing_account_id'
```

**Option 2**

- Add new scope types 'billing_account', 'organization' and 'folder'.
- Extend existing schema for policy validation in a case of usage new scope.
- Add parameters extension for a new scope.

**[Pull request](https://github.com/mediapills/cloud-custodian/pull/23)**

*Example:*

```python
@resources.register('log-billing-account-exclusion')
class LogBillingAccountExclusion(QueryResourceManager):

    class resource_type(TypeInfo):
        service = 'logging'
        version = 'v2'
        component = 'exclusions'
        enum_spec = ('list', 'exclusions[]', None)
        scope_key = 'parent'
        scope = 'billing_account'
        scope_template = "billingAccounts/{}"
        type_field = 'billing_account_id'

        @classmethod
        def extended_policy(cls, schema):
            schema[cls.type_field] = {'type': 'string'}
```

**Option 3**

- Add new resource scope billing_account
- Add new resource scope organization
- Add new resource scope folder

**[Pull request](https://github.com/mediapills/cloud-custodian/pull/24)**

**Example:**

```python
@resources.register('log-billing-account-exclusion')
class LogBillingAccountExclusion(QueryResourceManager):

    class resource_type(TypeInfo):
        service = 'logging'
        version = 'v2'
        component = 'exclusions'
        enum_spec = ('list', 'exclusions[]', None)
        scope_key = 'parent'
        scope = 'billing_account'
        scope_template = "billingAccounts/{}"
        type_field = 'billing_account_id'
```

**Comment by kapilt** [comment]
afaik, stack driver is the only resource where this is extant afaict. although perhaps iam service account as one other, the question then is the org level common to both, and if there are resources in gcp where this exists.. i can't think of any offhand.  Also afaicr we don't have the org id without doing some additional api calls.  i'd suggest extracting scope value retrieval to a new method on resource query. typically for other providers which might have this on a few exceptions, we would just have them do a custom source and resource query class to utilize with their resource manager.

**Comment by mediapills** [comment]
Thanks for checking

**Comment by mediapills** [comment]
Do you have any new ideas on this?
Thanks

**Comment by kapilt** [comment]
i'm finding a bit hard to evaluate among them, because i don't think the problem statement is very clear. its not really about supporting more than one param in a url, its just about additional scopes afaics or different url values, but its still just a single value being passed into url gen afaics. in general for resources that are different from normal, its better to just have a subclasses specific for them. I've mentioned this a few times, but perhaps an example helps.. ie. https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/resources/ecs.py#L78

in this case i think the base class refactoring scope retrieval to a method so it can be overridden would help with the service specific subclass.

**Comment by jondavidi** [comment]
@mediapills I've been looking over this and I agree with what @kapilt has said that this problem statement doesn't seem to be very clear. Further echoing, it is a just a single path parameter that is ultimately queried with (as opposed to having multiple values in the URL), but I think I understand what you're saying about needing the ability to specify this in the policy. 

I think it'd be good to see more focus and explanation about that along with your implementation suggestions (and would be nice for an example policy snippet as well which shows the implementation in action).

I would suggest focusing along the lines with option #1 (and what Kapil suggested) about thinking in terms of sub-classing for resources that fit this scenario. What I do find interesting is that if you look in c7n_gcp/resources/logging.py, there is already a resource that I believe falls into this scenario that has already been implemented, however I think it doesn't solve this problem (and has a resource naming problem) but nevertheless is hardcoded to only allow for querying with the project parent. 

I'd just be curious to know if that was an oversight of the implementer of that code, or if it was deemed appropriate for some reason? I personally think custodian should give the user the flexibility to take full advantage of the API call and not limit them to one instance of a parameter option, so I'm inclined to think it was an oversight.

**Comment by kapilt** [comment]
@jondavidi it was deemed appropriate because the common scope for custodian policy execution is a gcp project. there's also a notion we don't implement things absent concrete use cases, else we'll end up with a big pile of code no one is using, thats a pain maintain. ie custodian isn't an exercise in reflexively touching everything in cloud provider api, but on things that are useful for governance, for which a user has a use case in hand. ie its better to start small, with real uses, and refactor as we go, then try to grand plan something that people never use.

**Comment by mediapills** [comment]
@jondavidi and @kapilt I have been check resources in the base scope, it looks like resources that we have can be replaced by other API calls + filter or nested resources. I will check more detail and provide you more information tomorrow.

**Comment by mediapills** [comment]
Thanks, it looks like we do not have resources for now which is required additional parameters in URL for now.
