### ISSUE TITLE
Trying to run ebs modifyable policy

### ISSUE THREAD

**Issue by kumarsiyer** [cloud-custodian/cloud-custodian#3778]
While running the ebs modifyable policy getting an error message from AWS API

```An error occurred (InvalidParameterValue) when calling the DescribeVolumesModifications operation: The maximum number of filter values specified on a single call is 200```

> policies:
>   - name: ebs-modifyable
>     resource: ebs
>     filters:
>       - modifyable

**Comment by kapilt** [comment]
do you have a bigger traceback ?

we do batching in that method for sets of 200 to fall inline with the filter limit.

**Comment by disfinder** [comment]
I think I have fix for that -could you check that PR please?

**Comment by disfinder** [comment]
@kumarsiyer, @kapilt I think this issue could be marked as resolved, as far as fix is merged to master.

**Comment by kapilt** [comment]
Thanks for the ping
