### ISSUE TITLE
How to Find S3 buckets that are public 

### ISSUE THREAD

**Issue by ishyherts** [cloud-custodian/cloud-custodian#3785]
Hi

I am trying to write a custodian policy to find s3 buckets that are public.
I apologise if this has already been addressed, if not, can someone direct me to any guide or share samples if you have? Thanks

**Comment by anovis** [comment]
you can try using a `has-statement` filter for bucket policies that allow public access. 

``` policies:
              - name: s3-public-policy
                resource: s3
                filters:
                  - type: has-statement
                    statements:
                      - Effect: Allow
                        Action: 's3:*'
                        Principal: '*'
```

**Comment by anovis** [comment]
`custodian schema s3.filters.has-statement` gives you the schema for it.

**Comment by ishyherts** [comment]
Thanks everyone! Found some tips here too: https://github.com/cloud-custodian/cloud-custodian/issues/2125
