### ISSUE TITLE
AWS - Feature Request - Ability to define all AWS resource types using the tagging module

### ISSUE THREAD

**Issue by mattjlubbers** [cloud-custodian/cloud-custodian#3790]
I've submitted an issue previously about this for Azure but didn't seem to get any traction. Tagging is supposed to be uniform across all services and within a cloud platform. Maybe adding a wildcard to selection as well as supporting tagging as a whole would reduce the level of effort for these requests.

https://github.com/cloud-custodian/cloud-custodian/issues/3710

If this something your team is not interested in developing, please let me know.

**Comment by kapilt** [comment]
s/your team/the community.. ie. pull requests welcome as well. 

on the cloud provider level, at least for aws tagging is certainly not uniform, different apis, different semantics, different allowed values.. etc. custodian actions are for tagging do to try to be uniform to the extent possible (asgs tags have some extra bits).

in general the answer here atm is to write a policy for each resource and use yaml anchors and references to keep things DRY.
