### ISSUE TITLE
Empty S3 buckets and no CloudWatch metrics

### ISSUE THREAD

**Issue by jonotto** [cloud-custodian/cloud-custodian#3798]
In looking at earlier issues, it appears that a few questions have been asked about empty S3 buckets and solutions seem to center around using NumberOfObjects in CloudWatch Metrics. However, the use of this filter seems to rely on an assumption that CloudWatch metrics exist for all buckets, but this is not the case of buckets with no objects. The below is from AWS support on the topic:

> If there is no object in the bucket, no data point is pushed to the metric. So if a bucket is newly created, and there is no object, the metric itself will not be created as there is no data point pushed to create the metric. In case of buckets which had some objects and then deleted, no data point will be pushed to the already existing metric after the deletion of all the objects. CloudWatch metrics will also clear off the console if they do not receive any data points for about 14 days, however, should you upload an object, the metric will re-appear on the console.

I'm not sure if it would be possible to add some support for this null matching scenario? i.e. - Custodian would consider null matches with metrics (i.e. - bucket exists in S3 but there are no metrics in CWM) to be a positive result in the detection of empty buckets.

**Comment by kapilt** [comment]
that sounds reasonable, ie. detect the absence of metrics. i can't think of other use cases off hand but it does seem like there would be some.

**Comment by ajkerrigan** [comment]
Hi there @jonotto - in case this is still an issue, the metrics filter added support for a `missing-value` key that lets you specify a fill value when CloudWatch reports no data. We have some documentation and example cases for using it [here](https://cloudcustodian.io/docs/aws/resources/aws-common-filters.html?highlight=missing-value#aws-common-filters-metrics).
