### ISSUE TITLE
lambda - unmark feature is not listed under lambda actions

### ISSUE THREAD

**Issue by KapilTeotia1** [cloud-custodian/cloud-custodian#3821]
Hi Custodian Community,

I could not see any action under lambda resource with name "**unmark**". We basically want this option to exclude the resource if the resource became compliant after we marked the lambda resource as non compliant earlier.

Eg: Suppose we have added an action "mark-for-op" for deletion with 1 day threshold for all those lambda resource which don't have required tags. And if the resource owner has added the required tag within 1 day then we want to exclude the resource and want to keep the resource in system. To exclude the resource, we don't have any action as "unmark" like EC2,ASG,AMI ect. that's why we are not able to exclude the lambda resource and it would be permanently deleted after marking the resource.

Could you please add unmark feature to lambda resource as well?

**Comment by KapilTeotia1** [comment]
Available actions for lambda for the time being:

>custodian schema aws.lambda.actions
aws.lambda:
  actions:
  - auto-tag-user
  - copy-related-tag
  - delete
  - invoke-lambda
  - mark-for-op
  - notify
  - post-finding
  - put-metric
  - remove-statements
  - remove-tag
  - set-concurrency
  - tag

**Comment by kapilt** [comment]
use remove-tag, unmark is a legacy alias for the same.

**Comment by KapilTeotia1** [comment]
Thanks much Kapil. Yes remove-tag worked fine as expected.
