### ISSUE TITLE
c7n mailer not working through cross accounts

### ISSUE THREAD

**Issue by mvenkatesan** [cloud-custodian/cloud-custodian#3825]

**Comment by mvenkatesan** [comment]
here is my mailer.yml
queue_url: account A url ( This queue has persmission of Account B)
role: arn:aws:iam::account B:role/dci-ccustodianrole
from_address: emailid

If i use sqs queue and role in the same account its working fine.
we dont want to use each account sqs queue and email verified. instead of that we want to use one account to use one sqs queue with domain verified(in this account A already SES verified with domain). i just created a sqs queue on this account A and provided permission to account B

This is the policy under Account A queue
{
"Version": "2012-10-17",
"Id": "arn:aws:sqs:us-east-1:accountA:ccustodianmail",
"Statement": [
{
"Sid": "Allow-accountB",
"Effect": "Allow",
"Principal": {
"AWS": "arn:aws:iam::accountB:root"
},
"Action": "SQS:*",
"Resource": "arn:aws:sqs:us-east-1:accountA:ccustodianmail"
}
]
}

**Comment by mvenkatesan** [comment]
Even i tried as AWS suggested to use ses like this
SourceArn='arn:aws:ses:us-east-1:Account A:identity/domainname.com',
ReturnPathArn='arn:aws:ses:us-east-1:Account A:identity/domainname.com',
Source='emailid',
ReturnPath='emailid
but in custodian email says that its validation error
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('X-SES-FROM-ARN', 'X-SES-SOURCE-ARN', 'X-SES-RETURN-PATH-ARN' were unexpected)

Could you please provide insight on this?

**Comment by kapilt** [comment]
first, this does work, but it does need to be setup correctly out of band of custodian wrt to permissions.

second your not really giving any information wrt to the error or output.

So you have queue in account A. That queue lets principals in account B send to it. The permission looks fine. Does custodian output anything when sending a notification to it? If the send succeeds. Then you have to look at your c7n_mailer logs to see it draining from the queue. Do you see the queue metrics change?

**Comment by IngussNeilands** [comment]
hmm, what if policy (account a) -> sqs (account b) -> mailer (account c) -> ses (account c) ?

**Comment by kapilt** [comment]
its not really a custodian question its a does the aws permission model allow this

policy account a -> sqs (account b) generally works and is covered previously in this issue.

so wrt to the specific addition, generally speaking if the mailer role in account C has iam permissions for sqs, and the sqs queue in account B specifically grants account C access to poll/receive messages it works.
