### ISSUE TITLE
tools/c7n_mailer: Support for Date/Time stamp in the email

### ISSUE THREAD

**Issue by sri321** [cloud-custodian/cloud-custodian#3829]
Is there a way we can add date/time stamps in the email sent out automatically based on when the notification was created by the policy

This is because we have a huge backlog on our mailer due to many policies. 

Thank you

**Comment by kapilt** [comment]
pull request open to add execution_start iso utc datestring to the template variables, those can be converted to local timezone via the `date_time_format` template function.

**Comment by sri321** [comment]
hello @kapilt : Thank you for implementing this so soon. 
Can you tell me how to fix the error below?

File "msg-templates/default.html.j2", line 288, in top-level template code
{{date_time_format(execution_start, tz_str='US/Eastern', format='%Y %b
UndefinedError: 'date_time_format' is undefined

currently using mailer version 0.5.0

**Comment by kapilt** [comment]
the date time formatter is a jinja2 filter

**Comment by kapilt** [comment]
It’s pending a release
