### ISSUE TITLE
C7n_mailer - Docker image doesn't work with Azure

### ISSUE THREAD

**Issue by justinhauer** [cloud-custodian/cloud-custodian#3837]
### Issue:
Out of the box, the c7n-mailer docker image doesn't seem to work with Azure. I have reasons to use the docker image versus an Azure function.

When adding in:
```
RUN cd cloud-custodian/tools/c7n_azure && \
    pip install -r ./requirements.txt && \
    pip install -e .
```
the error returned is 
```
unable to execute 'gcc': No such file or directory error: command 'gcc' failed with exit status 1
```
Upon researching, found https://github.com/docker-library/python/issues/312, but the image still does not build successfully when this is added in:
```
RUN apk add --no-cache --virtual .build-deps gcc musl-dev
RUN pip install cython
RUN apk del .build-deps gcc musl-dev
```
#### summary
I have successfully built an image using the stretch python3.7.x docker image, but it would be nice to have this work with the Alpine image, which is significantly smaller.

**Comment by kapilt** [comment]
ic.. I think I missed the part where c7n_mailer had a hard dep on c7n_azure when packaging up the docker image. I'll update momentarily.
