### ISSUE TITLE
Azure - Auto tagging sample update

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#3839]
Auto creator tagging example in the documentation has bugs in it (incorrect resource types) but even if fixed it isn't a very good example.

Could we make a sample that targets `Azure.ArmResource` which should hit all ARM resources and then include a value filter to provide an array of resource types to act on perhaps? 

This issue is for testing different approaches (both event and not-event tagging) with `Azure.ArmResource` for the common user scenario of "Auto Tag new resources for several resource types" and updating the documentation with samples/explanation.

related to #3710  #3830

**Comment by thisisshi** [comment]
so we're now auto validating docstrings in the c7n code base, we should probably also extend this to the actual docs directory as well (https://github.com/cloud-custodian/cloud-custodian/pull/3767, https://github.com/cloud-custodian/cloud-custodian/pull/3809)
