### ISSUE TITLE
Implement Azure Pipeline Cache/Restore Tasks

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#3860]
These should be available in May 2019.  We should immediately implement them to speed up our build.

**Comment by yayitserica** [comment]
### ACCEPTANCE CRITERIA

1.  Azure Pipeline Cache implement per docs [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops).
2. Tests written and passing.
3. Documentation updated and tested for usability.

**Comment by stefangordon** [comment]
I should have updated this a while ago, so first attempt was #4451 

We are currently waiting on this:
https://github.com/microsoft/azure-pipelines-tasks/issues/11013

and this:
https://github.com/microsoft/azure-pipelines-tasks/issues/11045

We'll revisit next month and see if they have made some progress on this thing.

**Comment by stefangordon** [comment]
Seems like https://github.com/microsoft/azure-pipelines-tasks/issues/11013 is fixed.

**Comment by stefangordon** [comment]
Alright and #11045 seems also to be resolved (was a change in key behavior to adapt to).   

So this is ready to take a pass at again, with I think new questions around how to actually use it in a useful way.  Will play with it in the coming weeks.

**Comment by kapilt** [comment]
we've moved entirely to GitHub actions, so closing as its obsolete to work on azure pipelines support.
