### ISSUE TITLE
Azure - Functions Documentation

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#3861]
We need to revisit the functions documentation in the context of it being one of the most challenging aspects of Custodian for users to manage.  There is a lot of words that say a lot of complicated things, some of which are not true, and all of which are organized without considering priority to the user.

* The introduction lists a bunch of limitations that seem out of date
* There are several "walls of text"
* Scrolling over it there isn't any obvious explanation of what you are actually supposed to type at the command line to deploy a function

We should have a simple walk through of how to deploy a scheduled and event function, from policy to CLI commands, along with a picture or explanation of what has actually happened.

Then we can have piles of detail with appropriate headers and TOC links and managable sized paragraphs that explain all the options, provisioning, local package caching, etc.

We should also discuss "Approaches for managing multiple subscriptions"

https://cloudcustodian.io/docs/azure/advanced/azurefunctions.html

**Comment by logachev** [comment]
Blocked until https://github.com/cloud-custodian/cloud-custodian/issues/4121 is resolved

**Comment by stefangordon** [comment]
This will be covered by other work items about documenting incoming hosting features now.
