### ISSUE TITLE
azure - update flight recorder to use plain text json.

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#3870]
Currently the flight recording for azure uses binary encoded strings for responses, which obscures whats actually being recorded from being introspected and commented on during code review. This results in lots of extraneous opaque data that likely contains content not material to tests, and leads to alot of slow tests. Switching this to an embedded json when thats the applicable response content type, will allow for better detection of these issues when reviewing pull requests.

**Comment by stefangordon** [comment]
Related - The Azure SDK has added quite a bit more sophisticated logic to their base test stuff that we can probably adopt.  By default they catch/block large responses, and generally do better cleanup.

https://github.com/Azure/azure-python-devtools/blob/master/src/azure_devtools/scenario_tests/recording_processors.py#L79

**Comment by kapilt** [comment]
while processors are useful, the work for this issue is really about changing the persister implementation https://vcrpy.readthedocs.io/en/latest/advanced.html#register-your-own-cassette-persister which afaics doesn't have any useful analogues in the sdk test pkg referenced.

a quick perusal through vcr on github, looks like it needs a replacement of fs persister and serializer logic to get the desired result. none of the processor stuff actually deals with the serialization its all checkers/mutators.

**Comment by kapilt** [comment]
spent a little more time deep diving on this..  i think we can just use a processor here, basically a response processor that looks for content-encoding gzip, decodes it, deserializes the json, pretty prints (indent=2) serializes it, adjusts the content length. the rest of the vcr stuff still wants a {'body': {'string': ''}} which is buried in their stubs on request/responses of common libs, so this would still hold true to that expectation. one oddity it does look like callbacks are on both record and replay, so distinguishing that its for record will help preserve on compatiblity.

so something along these lines should do the trick

```python
response['body']['string'] = json.dumps(
      json.loads(zlib.decompress(response['body']['string'], 16+zlib.MAX_WBITS)), indent=2)
```


decompressed_data=zlib.decompress(f.read(), 16+zlib.MAX_WBITS)

**Comment by stefangordon** [comment]
I think they even do this natively if you just set `decode_compressed_response=True` - but we'd have to add the whitespace.

I understood your underlying goal to be shrinking the cassette size, is it actually just readability?

**Comment by kapilt** [comment]
i think there are massive amounts of extraneous data in the flight recordings, that there is no visibility into this during the pull request process is part of why this is accumulating. Turning off gzip to make this visible will help us prevent that for the future and help us remove the fat in the present. i'm also looking at switching out in the future to json serialization for speed. thanks for the tip re decompress field.. i think the issue with that by itself is that it embeds up embedding a json string, when for readability it really does need to be part of the overall doc structure. i'm also seeing extraneous headers that are supposed to be filtered in alot of the extant data (but in filter_ignore) including on extant prs.  i'll also probably have a pr in on this shortly, pretty localized to the vcr setup.

**Comment by kapilt** [comment]
ugh.. so filter_headers don't support removal of headers and is a no op with a None value.. lol, callbacks don't know if their being called on saved and load.. the whole vcr package feels like leaky incomplete abstractions.. sigh.. working on a fix.

**Comment by stefangordon** [comment]
Yes the work I had planned was to add significant filtering and rewriting of headers, bodies and requests (we need ability to rewrite resource ID's in the body now too) and then re-record everything with updated scripts that clear out all extraneous resources prior to recording to ensure the smallest responses.

I was also going to revisit fixing the bug in the JSON serializer (or making my own) for performance reasons.  (Not putting JSON in the YAML, but switching to JSON entirely)

**Comment by kapilt** [comment]
ah.. my mistake the reason headers aren't stripped is that we want to strip response headers, but the spec is for request headers..

**Comment by stefangordon** [comment]
Yeah we do both, I need extra headers in a few scenarios and I was going to have a decorator for tests that wanted them unfiltered.

**Comment by kapilt** [comment]
okay.. i've got a pr up that strips x- prefix'd response headers, and decompresses content, i'll hold off though, and we can merge what you have first if you prefer.

**Comment by stefangordon** [comment]
Yeah we'd need to re-record every test and include them in that PR I think also.  But I can deal with that :)

**Comment by kapilt** [comment]
a one off script should be able to handle the conversion, full re-records on all is probably a bit too painful. i tried to structure my changes for backwards compatibility, to avoid affecting existing tests or in flight prs, and then a separate pr for the rewrite on extant, tbd. i'll move on to other things for now, looking forward to seeing the changes, cheers.

**Comment by stefangordon** [comment]
I have them all re-recorded with zero YAML (json serializer plus inline json bodies) and they look nice - so I think this will work well.  Exposed some bad tests that I need to refactor though, should have it all cleaned up by Monday.

**Comment by kapilt** [comment]
re inline bodies, the approach I took with my pr is to have a single json document which I think would be nice for your changes as well is, no embedded json strings, because its much easier to review with a single document with consistent formatting then embedded json strings imo, on cassette load it would serialize the body again for the rest of the rest machinery to use. its an extra json serial/deserial roundtrip but really its milliseconds for a nicer review formatting.

**Comment by stefangordon** [comment]
Yeah agreed.   I have been debugging lots of cassettes today with a single JSON document per your idea and there is a less obvious separation between API results and other response fields but overall it is a time saver.

**Comment by stefangordon** [comment]
Update: Incoming pretty soon - there were just many more related test issues that needed to be dealt with than I expected, should have initial PR in today.
