### ISSUE TITLE
Security Groups - Detect and Remediate Violations lambda function is not working

### ISSUE THREAD

**Issue by mvenkatesan** [cloud-custodian/cloud-custodian#3877]
using no mode without cloudtrail its working but with mode cloudtrail is not working when the security groups modified through console. which mode we need to use for any modification happen through console and api

[ERROR] KeyError: 'eventName'
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 4, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 168, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 909, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 444, in run
    resources = self.resolve_resources(event)
  File "/var/task/c7n/policy.py", line 411, in resolve_resources
    resource_ids = CloudWatchEvents.get_ids(event, mode)
  File "/var/task/c7n/cwe.py", line 159, in get_ids
    resource_ids = cls.get_trail_ids(event, mode)
  File "/var/task/c7n/cwe.py", line 123, in get_trail_ids
    event_name = event['detail']['eventName']
[ERROR]	2019-04-24T19:15:40.101Z	989084ba-a7eb-4990-ac9d-e9f1bd401b90	error during policy execution

**Comment by kapilt** [comment]
whats your policy?

**Comment by kapilt** [comment]
that execution looks like it was triggered by hand without a real trail event, instead of by a cloud trail event...

**Comment by mvenkatesan** [comment]
its the same policy took it from the sample policy.
for to test it i modified the security group through console it didnt trigger the notify. so i just tried as schedule to fixed rate 5 min. then it triggered with the error that i mentioned.

**Comment by mvenkatesan** [comment]
action just to notify 

policies:
  - name: high-risk-security-groups-remediate
    resource: security-group
    description: |
      Remove any rule from a security group that allows 0.0.0.0/0 ingress
      and notify the user  who added the violating rule.
    mode:
        type: cloudtrail
        events:
          - source: ec2.amazonaws.com
            event: AuthorizeSecurityGroupIngress
            ids: "requestParameters.groupId"
          - source: ec2.amazonaws.com
            event: AuthorizeSecurityGroupEgress
            ids: "requestParameters.groupId"
          - source: ec2.amazonaws.com
            event: RevokeSecurityGroupEgress
            ids: "requestParameters.groupId"
          - source: ec2.amazonaws.com
            event: RevokeSecurityGroupIngress
            ids: "requestParameters.groupId"
    filters:
      - type: ingress
        Cidr:
            value: "0.0.0.0/0"
    actions:
        - type: notify
          template: default.html
          priority_header: 1
          subject: "Open Security Group Rule Created-[custodian {{ account }} - {{ region }}]"
          violation_desc: "Security Group(s) Which Had Rules Open To The World:"
          action_desc: |
              "Actions Taken:  The Violating Security Group Rule Have to Be Removed As It
              Violates Our Company's Cloud Policy."
          to:
              - name@domain.com
              - event-owner
          transport:
              type: sqs
              queue: https://sqs.us-east-1.amazonaws.com/account/ccustodianmail
              region: us-east-1

**Comment by kapilt** [comment]
first notifications are setup by deploying c7n-mailer, if you want to check if the policy lambda is working you should be looking at the lambda logs for the policy function, if you want to then check notifications, look at the mailer logs.  you can't take policy lambda thats setup to get events from cloudtrail, and then out of band hook it up to different arbitrary event sources (periodic in this case) and expect it to work, you have to have a separate policy where you change the mode to periodic.

also please use github markdown formatting when doing yaml/code blocks... triple quote to surround content.

**Comment by mvenkatesan** [comment]
In lambda log only i am getting this error:
[ERROR] KeyError: 'eventName'
Traceback (most recent call last):
File "/var/task/custodian_policy.py", line 4, in run
return handler.dispatch_event(event, context)
File "/var/task/c7n/handler.py", line 168, in dispatch_event
p.push(event, context)
File "/var/task/c7n/policy.py", line 909, in push
return mode.run(event, lambda_ctx)
File "/var/task/c7n/policy.py", line 444, in run
resources = self.resolve_resources(event)
File "/var/task/c7n/policy.py", line 411, in resolve_resources
resource_ids = CloudWatchEvents.get_ids(event, mode)
File "/var/task/c7n/cwe.py", line 159, in get_ids
resource_ids = cls.get_trail_ids(event, mode)
File "/var/task/c7n/cwe.py", line 123, in get_trail_ids
event_name = event['detail']['eventName']
[ERROR]	2019-04-24T19:15:40.101Z	989084ba-a7eb-4990-ac9d-e9f1bd401b90	error during policy execution

**Comment by kapilt** [comment]
that log message is from an event that did not originate from cloudtrail which is what the policy is intended to subscribe to, if your injecting arbitrary events, tests, periodic sources, etc. then you'll get errors like this because its a different event stream then what the policy is configured for.

**Comment by jterlecki** [comment]
I am also getting the same - I am creating an unencrypted EBS volume via the console to get the event to trigger.

[INFO]	2019-06-05T20:40:38.37Z	b9d5ff0f-d736-4e17-b989-a963e56424c3	Processing event
{
    "account": "XXXXXXXXXXXX",
    "region": "ca-central-1",
    "detail": {
        "request-id": "78a471d3-42cc-4681-b715-d2acab3d5fc5",
        "cause": "",
        "result": "deleted",
        "event": "deleteVolume"
    },
    "detail-type": "EBS Volume Notification",
    "source": "aws.ec2",
    "version": "0",
    "time": "2019-06-05T20:37:43Z",
    "debug": true,
    "id": "08799351-8964-6c2e-afc7-135d743a1ba4",
    "resources": [
        "arn:aws:ec2:ca-central-1:XXXXXXXXXXXX:volume/vol-0418076922d4e885d"
    ]
}

[ERROR]	2019-06-05T20:40:38.37Z	b9d5ff0f-d736-4e17-b989-a963e56424c3	error during policy execution
Traceback (most recent call last):
File "/var/task/c7n/handler.py", line 168, in dispatch_event
p.push(event, context)
File "/var/task/c7n/policy.py", line 909, in push
return mode.run(event, lambda_ctx)
File "/var/task/c7n/policy.py", line 444, in run
resources = self.resolve_resources(event)
File "/var/task/c7n/policy.py", line 411, in resolve_resources
resource_ids = CloudWatchEvents.get_ids(event, mode)
File "/var/task/c7n/cwe.py", line 159, in get_ids
resource_ids = cls.get_trail_ids(event, mode)
File "/var/task/c7n/cwe.py", line 123, in get_trail_ids
event_name = event['detail']['eventName']
KeyError: u'eventName'
u'eventName': KeyError
Traceback (most recent call last):
File "/var/task/custodian_policy.py", line 4, in run
return handler.dispatch_event(event, context)
File "/var/task/c7n/handler.py", line 168, in dispatch_event
p.push(event, context)
File "/var/task/c7n/policy.py", line 909, in push
return mode.run(event, lambda_ctx)
File "/var/task/c7n/policy.py", line 444, in run
resources = self.resolve_resources(event)
File "/var/task/c7n/policy.py", line 411, in resolve_resources
resource_ids = CloudWatchEvents.get_ids(event, mode)
File "/var/task/c7n/cwe.py", line 159, in get_ids
resource_ids = cls.get_trail_ids(event, mode)
File "/var/task/c7n/cwe.py", line 123, in get_trail_ids
event_name = event['detail']['eventName']
KeyError: u'eventName'

Here is our policy snippet
```
  - name: terminate-unencrypted-ebs
    description: |
      Terminate all unencrypted EBS volumes upon creation
    resource: ebs
    mode:
      type: cloudtrail
      role: arn:aws:iam::XXXXXXXXXXXX:role/CloudCustodianLambdaRole
      events:
      - CreateVolume
    filters:
      - Encrypted: false
    actions:
      - delete
```

**Comment by kapilt** [comment]
@jterlecki that looks like you manually hooked up a different event source to the custodian lambda, and its erroring because thats not a cloud trail event, its an ebs volume notification. if you remove your manual event source from cwe ebs volumes notification, the cloud trail event through cwe should work fine.
