### ISSUE TITLE
azure devops pipelines not triggering on GitHub web hooks 

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#3883]
This has been pretty constant but intermittent for the last few days :-( Constantly pushing and closing and opening prs is for the birds, but afaict its the only resolution at the moment. 

https://developercommunity.visualstudio.com/content/problem/545562/github-ci-builds-not-triggering-with-webhook-avail.html

**Comment by kapilt** [comment]
another support thread on the same topic, where stefan chimes in with the support ticket number he filed on it https://developercommunity.visualstudio.com/content/problem/545643/builds-randomly-stop-triggering.html

**Comment by stefangordon** [comment]
fwiw, I toggled the trigger configuration for the PR webhooks off and back on, so if you do see any difference let me know.

**Comment by kapilt** [comment]
i'm currently 3 out of 4 on pull requests pushes/merges retriggering.. so it seems better but also not quite 100%.. re one that didn't trigger https://github.com/cloud-custodian/cloud-custodian/pull/3855

**Comment by kapilt** [comment]
feels like its resolved now.

**Comment by kapilt** [comment]
nope spoke too soon, its still pretty flakey 60% success rate

**Comment by kapilt** [comment]
my latest round of tests is scoring at 100% success rate (sample size on my tests is min of 5).

**Comment by kapilt** [comment]
seems to be stable, closing out.

**Comment by kapilt** [comment]
sigh.. its happening again, two pull requests that are not triggering builds atm

**Comment by kapilt** [comment]
spoke too soon, looks like it was just delayed. its hard to track this stuff due to the lack of feedback on queuing in response to a web hook on the unhappy path.
