### ISSUE TITLE
account service limits excluding some services

### ISSUE THREAD

**Issue by pendyalal** [cloud-custodian/cloud-custodian#3890]
If I want to exclude any services from an account-service-limits policy, how do I do that?
To give an example - let's say we want to check service limits for all services except VPC, and EC2- m4-16xlarge instances. How can we achieve that?

**Comment by kapilt** [comment]
Wrt to that particular use case, its a reasonable use case, and something we should probably support better. At the moment I guess its a separate policy per limit, but that allows better custodian metric tracking on services that are needing limit increases.

Also re service limits in particular, tbh the underlying code probably needs tlc to use the newer trusted advisor checks to support a wider range of services.
