### ISSUE TITLE
Azure - Action to Trigger Logic App / Functions

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#3905]
I believe the ability to trigger a logic app from an Action would be a good initial approach to allowing users to integrate automation triggering into their policies.

This was based on a user asking about generic script/function triggering capabilities.

**Comment by stefangordon** [comment]
For a logic app we can programmatically get the callback URL so the user does not have to specify any secrets, just the app name:
```
POST https://management.azure.com/{logic-app-resourceID}/triggers/{myendpointtrigger}/listCallbackURL?api-version=2016-06-01
```

And they can provide any number of fields with JMESPATH values for the body.

Something similar should work for Functions.

**Comment by aluong** [comment]
We should look at the current support for AWS to see if there are common logic we can lift.
https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/actions/invoke.py

**Comment by stefangordon** [comment]
The webhook action is in now, so we just need to subclass and add the manual RESTful call with RBAC auth to get the secret endpoint.

**Comment by jainankurp** [comment]
Hello, I am trying to trigger logic app from Actions but somehow connection is getting refused. I can see call were reaching to logic app in the activity log. 
My logic app has http trigger and send email notification actions, which i can trigger manually and working well. 
Any pointers here about the issue will be helpful.

**Comment by stefangordon** [comment]
Hey @jainankurp  - Happy to help you debug.  Can you maybe open a new issue and give us a sample of your policy action?  Also go ahead and mention @stefangordon in the bug so I get notified. 

It is a relatively new action so I'll be eager to find out what the problem is as I'm sure someone else will run into it eventually.

**Comment by jainankurp** [comment]
@stefangordon done, new issue link
https://github.com/cloud-custodian/cloud-custodian/issues/4502
