### ISSUE TITLE
c7n-org isn't working

### ISSUE THREAD

**Issue by amitsehgal** [cloud-custodian/cloud-custodian#3906]
c7n-org run -c accounts.yml -s output -u policy.yml --dryrun
objc[40696]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[40696]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
objc[40697]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[40697]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

**Comment by kapilt** [comment]
This is an osx issue with python, not related to custodian. you can try runnig a recent version of python (say 3.7) or try explicitly setting an env var before running osx

background and workaround in issue i filed against python
https://bugs.python.org/issue33725
