### ISSUE TITLE
Azure - refactor firewall unit tests.

### ISSUE THREAD

**Issue by ivan-shaporov** [cloud-custodian/cloud-custodian#3921]
- From the sqlserver and storage firewall rules tests extract tests that can be run at the abstract class level.
- Create new tests for sqlserver and storage firewall rules that will test only the units themselves.

**Comment by stefangordon** [comment]
Lots of firewall work happening, rather than tracking this old issue I think we'll be looking at the tests fresh as we keep updating them with new features.  I think no one is likely to act on this specific issue.
