### ISSUE TITLE
Azure - Resource Whitelist Filter

### ISSUE THREAD

**Issue by justinhauer** [cloud-custodian/cloud-custodian#3923]
It appears that some resources have a whitelist class where a whitelist can be specified, such as https://github.com/cloud-custodian/cloud-custodian/blob/master/tools/c7n_azure/c7n_azure/resources/key_vault.py. I'd like to do the same with several storage accounts that I want to mark as whitelisted from specific storage account network policies being applied. I'm assuming whitelisting isn't in effect for certain resource types for reasons? Would this be best to handle just filtering on a specific tag?

**Comment by aluong** [comment]
The Whitelist KeyVault filter here was designed specifically to assist with evaluating the the KeyVault ACL (aka permissions for each principal)

Can what you are asking be done with just a normal value filter? I am not sure if a custom filter is needed here? @justinhauer, If you can elaborate on the scenario a bit more with a concrete example, that would also be helpful.

**Comment by justinhauer** [comment]
I'd like to whitelist specific storage accounts that `can` be open to the internet, hence putting them on a white list. I know I could say if they have tag `X` that they can be open, or something to this effect, but was wondering on the whitelisting. Another question I have is, does Azure have tags that can be "locked" or "immutable" after being set? that could stop someone from setting a 'whitelisted tag' to a storage account that shouldn't have a whitelisted tag.

**Comment by logachev** [comment]
For this particular case you can use `value` filter. Unfortunately there is no immutable tags now.
```
filters:
  - type: value
    key: name
    value_type: normalize
   op: not-in
   value: ['storageaccount1', 'storageaccount2'...]
```

**Comment by justinhauer** [comment]
@logachev Thanks. I think this issue can be closed out at this point. When I get a chance to try this out I'll validate it works as expected. Would it be useful to add as an example in the docs page? I can create a PR for that once validated.
