### ISSUE TITLE
AWS - Allow a delay when applying S3 default encryption configuration to allow proper configuration using KMS

### ISSUE THREAD

**Issue by monkeysSuck** [cloud-custodian/cloud-custodian#3924]
Scenario:

Using Terraform, I write code similar to below:

```
resource "s3_bucket" "bucket" {
  ...
  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        kms_master_key_id = "${var.kms_key_arn}"
        sse_algorithm = "${var.sse_algorithm}"
      }
    }
  }
}
```

Using this, I create a new S3 bucket. On creation, policies can get triggered, including setting default encryption configurations. However, when running this Terraform code, the default encryption will be set to AES256. 

Why is this? It's because there's a race between Terraform and CC. Basically, using Terraform/AWSCLI/etc, you can't specify encryption at bucket creation. So step 1 is create the bucket. CC then gets an event from CloudTrail/CloudWatch, and then proceeds to apply default policies. Next, Terraform continues applying the configuration, specifying the default encryption policy set in the code. CC sets a default configuration policy as well. Which gets set can be random, but most likely CC's policy will be the winner.

Because of this current policy, new buckets created using Terraform and a default encryption using KMS will (most likely) not be configured correctly. The bucket will be configured properly upon redeployment.

I propose that the configuration should be as follows:

- Set a policy to say that all PutObject requests need to have encryption. This will ensure that any objects put into the bucket are required to have encryption set.
- Shortly after bucket creation, when other checks are done, we ensure that there's a default encryption policy set. At this time, we can also apply a check to verify that all objects in the bucket have encryption set (not sure if a check already runs for all buckets or not).

**Comment by thisisshi** [comment]
This is a policy authoring issue, not a custodian one.
