### ISSUE TITLE
Azure - Support Azure Policy Monitor and Assign

### ISSUE THREAD

**Issue by Kannancsq** [cloud-custodian/cloud-custodian#3933]
I am looking for option to check whether a specific Azure Built-In / Custom-Policy is assigned to Subscription or not. If not we would need to turn on / assign the Policy to a subscription.

Can you please help me in directing to right documentation or example for the same

**Comment by justinhauer** [comment]
Is this more of a Azure governance policy thing, or a Cloud custodian specific thing?

**Comment by Kannancsq** [comment]
It's more of Azure Governance Policy

**Comment by logachev** [comment]
Hi @Kannancsq, I think you're looking for this feature: https://cloudcustodian.io/docs/azure/policy/resources/subscription.html

Example policy is looking if specified Policy assigned to the current subscription and assigns it if not.

**Comment by Kannancsq** [comment]
Thanks , this is the feature i was exactly looking for .
