### ISSUE TITLE
c7n-org Unable to locate credentials

### ISSUE THREAD

**Issue by mikrammo** [cloud-custodian/cloud-custodian#3962]
Hello,

I've an issue with the new docker images cloudcustodian/c7n-org Image ID : bd0827c8e1e0. with the error message, error:Unable to locate credentials.
It worked fine with the image bellow
REPOSITORY                    TAG                 IMAGE ID                CREATED             SIZE
cloudcustodian/c7n-org   latest              a37a30646649        2 weeks ago         1.48GB

**Comment by kapilt** [comment]
those are the old images, how were you passing credentials, you've omitted your docker run cli.

**Comment by mikrammo** [comment]
Here is my docker run cli : 

AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXXXXXXXXX
AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXXX
orgaccount=accounts.yml
custodianPolicy=tagCompliant.yml

docker run --rm -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} -v ${PWD}/output:/output -v ${PWD}/orgaccounts/${orgaccount}:/orgaccount.yml -v ${PWD}/policies/${custodianPolicy}:/policy.yml cloudcustodian/c7n-org run -c /orgaccount.yml -s /output -u /policy.yml --region="eu-west-1"

**Comment by kapilt** [comment]
and those credentials correspond to an iam-user that has the ability to role assume into the other roles for the accounts in accounts.yml?  if your using sts/instance-role you would also need to pass the session variable? are you seeing the error for each account? does it work for you if you use the c7n instead of c7n-org docker image (ie debugging your iam /credential setup)?

**Comment by mikrammo** [comment]
Yes, it worked well before with the image c7n-org built 2 weeks ago.
As requested, I tested with the image docker cloudcustodian / c7n and it works well

here is the command that works with cloudcustodian/c7n image
docker run --rm -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} -v ${PWD}/output:/output  -v ${PWD}/policies/${custodianPolicy}:/policy.yml cloudcustodian/c7n run --assume arn:aws:iam::XXXXXX:role/path/cloudcustodianRole  -s /output /policy.yml

**Comment by kapilt** [comment]
the main change was in how we propagate the credentials to use env vars, we may need to revisit that to verify some of this.

**Comment by mikrammo** [comment]
I created 2 new images docker c7n_org from 
commit 334abb7c3d7caf1b240ba8cd10cf5d3be3fbdefb (May 1) 
and from commit e8d230946b783719c61d9f3c27df6d03c878b4e3 (May 5)
It work fine with the commit 334abb7c and the error appears on the commit e8d230946b783719c61d9f3c27df6d03c878b4e3 (May 5)

**Comment by kapilt** [comment]
yeah specifically I think its this one https://github.com/cloud-custodian/cloud-custodian/pull/3859

**Comment by kapilt** [comment]
so that means its the stripping of extant AWS environment variables that was added in https://github.com/cloud-custodian/cloud-custodian/commit/e8d230946b783719c61d9f3c27df6d03c878b4e3 

i'll see if i can reproduce and add a test, else i'll just back this part out in the next day or so.

**Comment by kapilt** [comment]
i yanked the AWS_ environ prefix removal, i'm still a little unclear as to the workflow path that triggered this, but that should restore your usage pattern.

**Comment by mikrammo** [comment]
it work better, but I've another error with the new image, 

2019-05-20 10:23:03,693: c7n_org:ERROR Exception running policy:mark-if-nocompliant account:account1 region:eu-west-1 error:[Errno 13] Permission denied: '/output/account1/eu-west-1/mark-if-nocompliant/custodian-run.log'

here is my command
- I share with my container a volume /output
docker run --rm -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} -v ${PWD}/output:/output -v ${PWD}/orgaccounts/${orgaccount}:/orgaccount.yml -v ${PWD}/policies/${custodianPolicy}:/policy.yml ${imageDocker} run -c /orgaccount.yml -s /output -u /policy.yml --region="eu-west-1"

it work fine if I put "-s ."  instead of " -s /output"

**Comment by mikrammo** [comment]
I think the error that I have when I put -s /output it's about this commit ca2c76bd911901f6cdbd59e05cd4bdea55f2bb90
I changed my command to -s /output_org and it's ok

**Comment by kapilt** [comment]
thats related to non root execution in the docker image, if you do -s
/home/custodian/output that should resolve, though I thought we also
chown/chmod on /output for existing examples. I'll have a look

**Comment by kapilt** [comment]
thats odd, that commit your referencing was to enable the custodian user to modify/create on /output.

running locally with docker for Mac, everything seems to work for me using your script

```
$ cat run.sh 
docker run --rm -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
 -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
 -v ${PWD}/output:/output \
 -v ${PWD}/accounts.yml:/orgaccount.yml \
 -v ${PWD}/policies.yml:/policy.yml cloudcustodian/c7n-org:latest run -c /orgaccount.yml -s /output -u /policy.yml 
```

```
$ ./run.sh
2019-05-20 12:55:36,107: c7n_org:INFO Ran account:guard-duty region:us-east-1 policy:lambda-check matched:1 time:0.58
2019-05-20 12:55:36,209: c7n_org:INFO Policy resource counts Counter({'lambda-check': 1})
```

**Comment by mikrammo** [comment]
I use amz-lnx AMI on EC2 with docker version :
Docker version 18.09.6, build 481bc77156
and user : ec2-user
Otherwise it work fine when I use /output_org and it's ok for me

**Comment by kapilt** [comment]
docker images are now under go testing with this scenario before being published.
