### ISSUE TITLE
docs - readme colorize code blocks and include as intro in the sphinx docs

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#3963]

**Comment by EdEngle** [comment]
I will do this.  I found a couple other formatting things.  

@kapilt Do you want me to move the other README.md over?

**Comment by kapilt** [comment]
which other README.md ? the policy stream one should probably go in.

note this was in reference to the main repo's readme which is rst

**Comment by EdEngle** [comment]
Sorry,  I forget 'tools' the question.  Should I move the other tools readme's?

**Comment by thisisshi** [comment]
closed via #3970
