### ISSUE TITLE
Add a feature to specify the region(s) to deploy into the policy document 

### ISSUE THREAD

**Issue by charles545587** [cloud-custodian/cloud-custodian#3992]
As a user, I want to be able to specify in which regions I want to deploy the AWS resources from within the policy rather than using the -r {region} parameter in the command line. 

When using automated CI/CD tools such as Code Pipelines to deploy custodian policies, manipulating the command line to insert variables to specify which regions using the -r flag you want the policies deployed in presents additional challenges. 

A neat way to overcome this would be to be able to specify as an array which regions you want, in the actual policy itself.  I don't believe this is currently possible.

**Comment by kapilt** [comment]
`-r all` on the cli will execute across all regions. we do allow specification within the policy of pinning a policy to a given region for global resources, ie `region: us-east-1`

**Comment by kapilt** [comment]
we don't really want to invert control from the executor of the cli wrt to regions that are being executed, it violates the principal of least surprise imo. i don't really understand why your saying that configuring a command line parameter is a challenge.

**Comment by kapilt** [comment]
this is supported with policy conditionshttps://cloudcustodian.io/docs/quickstart/advanced.html#conditional-policy-execution
