### ISSUE TITLE
Docker Convenience Script

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4009]
Would be cool if we had `custodian-docker.sh` which accepted command lines identical to custodian, and even supported Azure CLI Auth, but ran everything through the docker image.

Bonus points if it automatically grabs and uses the last-known-good tagged image for you also.

Increasingly learning we can't really trust the PyPi ecosystem to provide working packages for us on demand, so it is important we can push users to a docker image with all libraries already installed which doesn't require a big syntax learning curve or giving up CLI features.

Ideally we could just tell people to `wget custodian-docker.sh` and continue on as if they had custodian installed without worrying about making volumes, moving environment variables, etc.

Related to #815

**Comment by kapilt** [comment]
the pypi breakages are fairly transient and relatively rare, ie 360 days of the year its good, and the breakage is good for us to be aware of. I've got a backlog task to ensure the periodic builds file issues on any breakage.  i'd like if we could do some additional functional testing in a separate pipeline with auto filing of issues. Ideally we could test the docker images prior to publishing to docker hub, but there isn't currently a facility i see for that with the automated docker hub builds. another option would be revamping the publishing process to include frozen dependency graph version sets for each of the packages, albeit at the cost of breaking any checksum validations.

wrt to a shell script front end, that seems good, one of the challenges with making the images work as non root was trying to identify all the usage references to understand output directories mounts, having a default shell script front end might alleviate that significantly. Is that going to work on windows (sans WSL)? Do we need a go program?

**Comment by stefangordon** [comment]
If it is simple enough we could just implement a bash and a powershell version I guess.  Or go works too.
