### ISSUE TITLE
Are Cloud Custodian and AWS Organizations providing same features?

### ISSUE THREAD

**Issue by mayankshekhar03** [cloud-custodian/cloud-custodian#4031]
I came across [AWS Organizations](https://aws.amazon.com/organizations/), and by looking at the details it seems like it is somewhat similar to Cloud Custodian. May I know if there is any difference between these two? If yes. How do they differ?

**Comment by kapilt** [comment]
They are orthogonal and cover vastly different feature sets. Organizations is an api for creating accounts and placing them into hierarchy, and then applying iam policy restrictions on them (SCP). Custodian is a rules engine for applying policies that manage resources in an account that integrates with serverless and other management apis for realtime response and reporting. Custdodian can use/leverage organizations (with the c7n-org tool) to apply those policies across accounts. I'd suggest spending a few minutes reading the docs about both topics, if the differences are immediately clear, then post a specific scenario thats of interest.

**Comment by mayankshekhar03** [comment]
Thanks. That was helpful.
