### ISSUE TITLE
cloudtrail filter `is-shadow` always matches all resources

### ISSUE THREAD

**Issue by hinchliff** [cloud-custodian/cloud-custodian#4037]

**Comment by hinchliff** [comment]
In the [`process()`](https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/resources/cloudtrail.py#L57) function, I guess these lines are to deal with the `is_shadow()` returning None if it falls through?
```python
        anded = lambda x: True # NOQA
        op = self.data.get('state', True) and anded or operator.__not__
```

changing the lambda seems to correct the issue:
```python
        anded = lambda x: x # NOQA
```


Although It might make the code easier to understand if `is_shadow()` returns False on the fall through, and then the comparison can be done as a slightly more straightforward boolean:
```python
        trails = [t for t in resources if (self.is_shadow(t) == self.data.get('state', True))]
```

**Comment by hinchliff** [comment]
Related, I think the check for multi-region shadow trails might be incorrect?  I think the `HomeRegion` will always be the region listed in the `TrailARN`?  The comparison should probably be between `{region}` and `HomeRegion` ?

Currently:
```python
        if t.get('IsMultiRegionTrail') and t['HomeRegion'] not in t['TrailARN']:
```

**Comment by kapilt** [comment]
yeah that seems not correct in some brief testing, home region is always the same as trail arn region, so your change here look good to check against currently executing region for a match.
