### ISSUE TITLE
Mailer issue using multiline violation_desc or action_desc.

### ISSUE THREAD

**Issue by gmagella-ca** [cloud-custodian/cloud-custodian#4045]
Hello! I’m having issues with c7n_mailer (Slack), when I use something like this, I get an errors:

```
 action_desc: |
        "Actions Taken:  Notification Only. Please investigate and fix your ASGs
        configuration to prevent you from having any outages or issues" 
```
ERROR:

```
File "/var/task/c7n_mailer/slack_delivery.py", line 189, in send_slack_msg response.status_code, response.text()) TypeError: 'unicode' object is not callable
```
If I remove the line breaks, and use something like this, it works perfectly:

```
action_desc: "Actions Taken: Notification Only. Please investigate and fix your ASGs configuration to prevent you from having any outages or issues”
```

Same goes for violation_desc.

**Comment by kapilt** [comment]
the double quoting your doing is causing some adverse effects, and the error from the slack api is being masked by a log error. As you note, the quickest solution is to just fix the double quoting

ie. in yaml 
```yaml
action_desc: | 
    "xyz"
```
leads to a string with literal quote marks in it.

you probably meant

```yaml
action_desc: |
   foo bar  lorem
   ipsum
```

**Comment by kapilt** [comment]
confirmed via chat this resolved for the user
