### ISSUE TITLE
metrics - use a different namespace for emitting metrics

### ISSUE THREAD

**Issue by thisisshi** [cloud-custodian/cloud-custodian#4055]
the metrics option currently outputs to the default `CloudMaid` namespace, I would like to output metrics to a specific namespace for better organization of metrics, I propose that we modify c7n.output to allow the use of an environment variable for this:

```python
import os
...
DEFAULT_NAMESPACE = os.environ.get('C7N_METRICS_NAMESPACE', 'CloudMaid')
```

Use Case:
- Policies are contributed by multiple teams that may have name conflicts--  these metrics should be put into their own namespaces such that they can be properly attributed to the right policy

This would change would preserve the current default namespace keeping backwards compatibility

**Comment by kapilt** [comment]
thanks for the use case.. given we have configurable metrics via cli  uri, better would just be a cli parameter to that uri... ie these are all separate invocations.l. And it avoids a provider specific namespace grab on env vars.

**Comment by kapilt** [comment]
fwiw, metrics namespace is already configurable via the cli

`-m aws://?namespace=foo`

**Comment by thisisshi** [comment]
Ah, gotcha thanks

I wasn't able to find that info in the cli, I'll submit a patch to add that into the help section and into the docs if it's also missing in there
