### ISSUE TITLE
c7n_mailer - service not known

### ISSUE THREAD

**Issue by magrossm** [cloud-custodian/cloud-custodian#4095]
Dear team,

I deployed a simple ec2 snapshot policy for testing. It works and creates snapshots. I then deployed the mailer and tested it with policy resource type sqs and befilled the queue to my email address. I received the mail by smtp.

When I try to include a notify inside another resource policy (the ec2 snapshot) one, I see the queue befilled with a message and draining but when I check the log of the lambda mailer, I get following output. The message count drops but I never receive anything. I changed the private parts with xxxx instead of the true values.

```
START RequestId: 53387adf-efa0-41d7-af90-22134b9ef906 Version: $LATEST
[WARNING]	2019-06-01T16:40:18.482Z	53387adf-efa0-41d7-af90-22134b9ef906	Error policy:{u'resource': u'ec2', u'name': u'owner-tag-compliance', u'actions': [{u'copy-tags': [u'cloudcustodian'], u'type': u'snapshot'}, {u'to': [u'xxxxxxxx'], u'type': u'notify', u'template': u'default.html', u'transport': {u'queue': u'https://sqs.eu-central-1.amazonaws.com/xxxxxxxxx/c7n-mailer', u'type': u'sqs'}, u'subject': u'snapshot created'}], u'mode': {u'type': u'periodic', u'role': u'arn:aws:iam::xxxxxxxxx:role/cloudcustodian', u'schedule': u'rate(1 day)'}, u'filters': [{u'State.Name': u'running'}, {u'tag:cloudcustodian': u'present'}], u'description': u'Kopiere Tags von Maschine auf snapshot.'} account:xxx-iat sending to:[u'xxxxxxxxx'] 

**error: [Errno -2] Name or service not known**

mailer.yml: {u'from_address': u'xxxxxxxxxxx', u'slack_webhook': None, u'security_groups': None, u'datadog_api_key': None, u'ldap_bind_user': None, u'queue_url': u'https://sqs.eu-central-1.amazonaws.com/xxxxxxxx/c7n-mailer', u'ses_region': u'eu-central-1', u'templates_folders': [u'msg-templates/'], u'smtp_port': 587, u'smtp_server': u'xxxxxxxx', u'role': u'arn:aws:iam::xxxxxxx:role/cloudcustodian', u'memory': 1024, u'ldap_uri': None, u'smtp_username': u'xxxxxxx', u'ldap_bind_password': None, u'subnets': None, u'smtp_password': xxxxxxx', u'contact_tags': [], u'ldap_bind_dn': None, u'slack_token': None, u'smtp_ssl': True, u'region': u'eu-central-1', u'timeout': 300, u'runtime': u'python2.7'}
```

I try to send an email with smtp and it worked when i tested the mailer with SQS resource in the policy, but not when I employ it inside my ec2 resource policy.

Any idea? Is there something I need to handle addtionaly with smtp?

**Comment by magrossm** [comment]
I mean it sounds like a problem with the urlib library. Just dont know where to search exactly....

**Comment by thisisshi** [comment]
sounds like it can't resolve your smtp server, i'm assuming you're running this in a vpc-- do all the subnets in your vpc have access to the smtp server?

**Comment by magrossm** [comment]
On this machine there are regularly Powershellscripts running that also use the send-mail cmdlet regularly and it works. So the subnet where the machine is has access to the smtp. If the others have, should not be relevant to this test case I think.

**Comment by kapilt** [comment]
so chatted on gitter about it, mailer was deployed as a lambda (not vpc attached), it seems to be a dns resolution failure, i'm guessing its a case of the mail server or some or component not being available on the public internet. running it locally (non lambda) seems to have resolved.

**Comment by magrossm** [comment]
got resolved.
