### ISSUE TITLE
ci - intermittent sqlite-related failures

### ISSUE THREAD

**Issue by ajkerrigan-mdsol** [cloud-custodian/cloud-custodian#4102]
I've had a couple CI builds run today associated with #4101 - tests succeed locally but fail intermittently in CI for one or more ubuntu-based python environments. I see similar failures for #4035  and #4090 . The failures are all related to sqlite, which appears to be missing from the build image sometimes. That causes test results to vary across builds.

I don't know if this is a transient issue or not. Is it worth having a script step for ubuntu-based builds to ensure that sqlite is available?

**Comment by kapilt** [comment]
yeah this seems like a regression in the azure pipeline build image that is hitting us intermittently.

**Comment by kapilt** [comment]
filed upstream as https://github.com/microsoft/azure-pipelines-image-generation/issues/996

**Comment by kapilt** [comment]
till its resolved upstream, i think we need to address this directly via package install, i've put up a pr to do that.

**Comment by kapilt** [comment]
unfortunately I'm not clear we can handle this in our pipeline yaml, I've tried a few different things re sqlite install, but its not working :-( I might be missing something though. I'm installing the standard deps for python on xenial/16.04 for sqlite3 and libsqlite3-0 but its not taking.

**Comment by ajkerrigan-mdsol** [comment]
Dang :(. I wonder if some of the python versions in their hosted agent tools cache were built without sqlite support? I was thinking maybe it would need libsqlite3-dev or something, but by the time the pipeline is running maybe it's too late to recover without going to an ugly nuclear option like rebuilding python.

**Comment by kapilt** [comment]
if this doesn't get resolved by eod friday, i'll bite the bullet and switch on ci. our days of dead ci in the past month is approaching a week, ie there have been other incidents this month. While pipelines has been great as a ci tool, its not tenable if its broken this often, as its holding up contributions and activity in the project.

**Comment by ajkerrigan-mdsol** [comment]
That makes sense, understandable. I see that the attrs project worked around it by using deadsnakes python. Don't know if that's more or less attractive than switching ci. I guess that'd only cover 3.7 for us anyway, and for 2.7 we'd need to use the native ubuntu package instead of the one from agent tools? Not great options :(.

python-attrs/attrs#541

**Comment by kapilt** [comment]
for now i've disabled 2.7/3.7 builds to unblock the builds.

**Comment by kapilt** [comment]
unfortunately changing ci isn't viable atm as capitalone has made the organization/repo permissions unusable for changes to ci.

**Comment by kapilt** [comment]
There's a couple of  rather ugly work arounds on the upstream issues, to remove the existing pipeline python version, and install a new python version for 2.7 and 3.7 but for now we'll try and wait it out.

**Comment by kapilt** [comment]
per comments on the azure forums this `1-2 weeks` away  from being rolled out completely :-( i'm gonna work around this.. we need this resolved to get to a release.
