### ISSUE TITLE
Support for 'classifier' in finding types for the 'post-finding' action

### ISSUE THREAD

**Issue by LRuttenCN** [cloud-custodian/cloud-custodian#4115]
In security hub, finding types are formatted as: `namespace/category/classifier`, where the category and classifier are optional.  (https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-findings-format.html) 

Currently in CloudCustodian, only predefined namespaces and categories are supported (e.g. "Effects/Data Exposure", but not a custom classier (e.g. "Effects/Data Exposure/Public Bucket"). This does not allow for granular filtering of Findings in Security Hub's 'Insights' tab. 

One of the problems is that Security Hub's default findings have a trailing slash (e.g. for public buckets, the filter is: "TYPE PREFIX Effects/Data Exposure/". The trailing slash filter out Cloud Custodian's "Effects/Data Exposure" Type, and is therefore not visible as an insight.

**Comment by LRuttenCN** [comment]
One of the problems is that Security Hub's default findings have a trailing slash (e.g. for public buckets, the filter is: "TYPE PREFIX Effects/Data Exposure/". The trailing slash filter out Cloud Custodian's "Effects/Data Exposure" Type, and is therefore not visible as an insight.

**Comment by kapilt** [comment]
merged
