### ISSUE TITLE
c7n-org increase error verbosity

### ISSUE THREAD

**Issue by gmagella-ca** [cloud-custodian/cloud-custodian#4127]
Can the error messages on c7n-org be made more verbose, like it is on "custodian run" ?

```
[Container] 2019/06/10 14:58:51 Running command c7n-org run --dryrun -c c7n-org-policies/accounts.yml -s output -u c7n-org-policies/organization-policies.yml --region us-east-1 --region ca-central-1 --verbose 
2019-06-10 14:58:52,326: c7n_org:DEBUG Running policy:rds-unused-databases-notify-step1 account:AccountNameSecurity region:us-east-1 
<stripped>
2019-06-10 14:58:52,734: c7n_org:WARNING Access denied account:AccountNameMember1 region:ca-central-1 
<stripped>
2019-06-10 14:58:53,014: c7n_org:DEBUG Running policy:rds-unused-databases-notify-step2 account:AccountNameSecurity region:us-east-1 
<stripped>
2019-06-10 14:58:53,074: c7n_org:INFO Policy resource counts Counter({'rds-unused-databases-delete-step4': 0, 'rds-unused-databases-unmark': 0, 'rds-unused-databases-notify-step1': 0, 'rds-unused-databases-stop-and-nag-hourly-step3': 0, 'rds-unused-databases-notify-step2': 0}) 
[Container] 2019/06/10 14:58:53 Command did not exit successfully c7n-org run --dryrun -c c7n-org-policies/accounts.yml -s output -u c7n-org-policies/organization-policies.yml --region us-east-1 --region ca-central-1 --verbose exit status 1 
[Container] 2019/06/10 14:58:53 Phase complete: BUILD State: FAILED 
[Container] 2019/06/10 14:58:53 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: c7n-org run --dryrun -c c7n-org-policies/accounts.yml -s output -u c7n-org-policies/organization-policies.yml --region us-east-1 --region ca-central-1 --verbose. Reason: exit status 1 
```
I don't get any information on what is actually the error and the user/role that got denied.

-----
For reference, while running custodian run, we get this kind of error:

```
2019-06-10 03:28:49,851: custodian.commands:ERROR Error while executing policy high-risk-security-groups-remediate, continuing 
Traceback (most recent call last): 
  File "/usr/local/lib/python2.7/si... <STRIPPED>
ClientError: An error occurred (AccessDeniedException) when calling the DescribeLogGroups operation: User: arn:aws:sts::<accountid>:assumed-role/CloudCustodianPolicyDeploymentProjectRole/AWSCodeBuild-796e2aea-abb5-4a17-a2c8-373bc7e15d1d is not authorized to perform: logs:DescribeLogGroups on resource: arn:aws:logs:us-east-1:<accountid>:log-group::log-stream: 
```

**Comment by kapilt** [comment]
okay how about this
```
c7n_org: WARNING Access denied api:ListBuckets policy:rds-unused-database-notify-step1 account:00111222 region:us-east-1
```

**Comment by gmagella-ca** [comment]
That helps but it doesn't show you which user/role is getting that denied. E.g: After much cloudtrail digging I manage to figure that the role on account A (codebuild) was missing permission allowing it to assume another role in another account. (even though the trust was allowing on the remote account) stupid mistake that would be corrected with a more clear error message.

**Comment by kapilt** [comment]
errors don't per se include the calling identity information. The role should be the one associated with account A per the config file, unless its an Assume call. we already have specific handling for the role assume from the master account to the executing account wrt to the log message on it, ie. that should have something along the lines of

`unable to obtain credentials for account:%s role:%s error:%sa`

**Comment by kapilt** [comment]
i should note that additional log message for credential/roleassume is only in trunk for c7n-org its also enables chained role assumes [role a -> role b -> role c]

**Comment by gmagella-ca** [comment]
My point is that custodian run exposes this...

```
ClientError: An error occurred (AccessDeniedException) when calling the DescribeLogGroups operation: User: arn:aws:sts::<accountid>:assumed-role/CloudCustodianPolicyDeploymentProjectRole/AWSCodeBuild-796e2aea-abb5-4a17-a2c8-373bc7e15d1d is not authorized to perform: logs:DescribeLogGroups on resource: arn:aws:logs:us-east-1:<accountid>:log-group::log-stream:
```

I was just wondering why c7n-org don't. The way I troubleshoot this was switching to run with "custodian run" and finding and fixing the error, seeing that the message goes away and switching back to c7n-org.

**Comment by kapilt** [comment]
thats a service specific error message, there's no guarantee that the principal arn is included in the actual error ie. it will very by service and api, because c7n-org is operating in parallel across many policies/account regions, we don't log the actual error message, just the error code and metadata information to avoid bloating the cli ux with arbitrary long/sized strings.
