### ISSUE TITLE
azure - c7n_azure docker image with Azure Function cache

### ISSUE THREAD

**Issue by logachev** [cloud-custodian/cloud-custodian#4131]
Build & publish docker image with Azure Functions cache zip

**Comment by kapilt** [comment]
Could you clarify the benefits and purpose of the function cache zip.

**Comment by stefangordon** [comment]
A benefit to the user is that the function deploy will be significantly faster if this is already in the image, but the primary reason we want to do it is that it ensures your "known good" docker image stays that way.  

By having the packages pre-cached it means that they aren't coming from PyPi at runtime, and as long as the image works when we publish it then it should still work at a later date even if there are dependency breaks.

Should be a minor tweak to the image to pre-cache,  I'll post a PR with the changes and size impact so we can see.

**Comment by kapilt** [comment]
image publishing is always post ci, so effectively known good, minus race conditions on package publishing from ci to docker hub build. and re no external dependencies, well minus docker hub... tbh I have concerns about the longterm health of docker, inc. gcr is another consideration, I've got an image repo up there, but again blocked by some of the org permissions issues re automating. the dl bandwidth perf is pretty solid, it supports trust, and cve scanning, and short urls. 

but what is actually in the cache, is it just the pip cache from installing custodian and friends? or are there some azure functions specific bits that need install here?

**Comment by stefangordon** [comment]
Oh yeah so it is just the cache we build today the first time you publish a function #3857  

It is basically a zip file with all your wheels ready to be used to make a function.  This way the image comes with everything needed to publish your policy without external dependencies.  

I was just going to add a line to the dockerfile like 
```
RUN python -c "from c7n_azure.function_package import FunctionPackage; FunctionPackage('cache').build(...)
```

**Comment by kapilt** [comment]
if we remove this line in the dockerfile  ` && rm -Rf /root/.cache/ \` we should effectively retain all of the downloads in the pip cache. if we could selectively modify .dockerigore we could add a bunch more savings (tests and docs) that would effectively make the retain the cache fairly neutral.. trying it out locally adding those to docker ignore and removing the cache deletion brought the image up from 418 -> 463mb  .. by itself the retain the cache looks like its ~70mb

**Comment by stefangordon** [comment]
Yeah, for sure I can optimize for a net-reduction in size.
