### ISSUE TITLE
propagate-spot-instance tags to spot-requests

### ISSUE THREAD

**Issue by ndesai15** [cloud-custodian/cloud-custodian#4141]
I have an auto-scaling-group set up & instance that are getting spin up are spot instances. I have marked propagate-tags to instance so my instances part of this group are getting tagged properly but spot-requests associated with these spot-instances are not getting tagged.

I want to create a cloud custodian policy to do so.  Any idea/suggestion on how to do so?
I found "propagate-spot-tags" but this action works from spot requests to spot instances. I am looking from spot instances to spot requests.

Can you provide me any suggestion or help?

**Comment by kapilt** [comment]
the only issue with doing copy-related-tag here is there is no association afaik from the instance attributes back to the spot request?

**Comment by kapilt** [comment]
also curious what the use case is? ie is there tag cost association to the spot request itself? or is this just organizing?

**Comment by ndesai15** [comment]
Yes after a while I came with same as there is no cost associated with spot request so I am closed this ticket now.
