### ISSUE TITLE
Azure - Resource page formatting

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4156]
This crazy look is pretty common.  It isn't clear what you are reading and it looks very unprofessional.

![image](https://user-images.githubusercontent.com/4087345/59394001-e4eb0700-8d32-11e9-8dab-cc655b272d4a.png)

Each filter or action should probably have a proper header with its name, and a description underneath.   CSS issue with schema filed as  #4155.

The AWS ones at least all use the header formatting properly:
https://cloudcustodian.io/docs/aws/policy/resources/ec2.html

This one has some sort of header going on, but it puts the summary in the header instead of under it:
https://cloudcustodian.io/docs/azure/policy/resources/nsg.html

**Comment by stefangordon** [comment]
Should we also remove most of this generic filters stuff?  I don't see the value in duplicating the generic actions on each page.  It can just be a single link to that page like it is under actions.

**Comment by kapilt** [comment]
fwiw, i've got fully autogenerated reference doc setup in progress that does a better job handling common filter/actions (first step was in #4150). The extant aws resource docs will be nuked. Manually maintaining reference material is not viable, trying to move to common convergence of cli schema and docs to use introspection.

**Comment by stefangordon** [comment]
replaced with #4179
