### ISSUE TITLE
Azure - prevent waiting for ARM polling operations while running tests with cassettes

### ISSUE THREAD

**Issue by axis7818** [cloud-custodian/cloud-custodian#4158]
Some azure APIs require the use of ARM polling. The polling happens on the client, so even with recorded cassettes, the polling operation waits for the polling duration. This causes tests to run slowly. 

An example of this is updating the retention policies on SQL Databases where the current work-around is to hand edit the cassette files to remove the polling responses. 

One solution could be to detect if tests are running from pre-recorded cassettes and if they are, mock the poller so that it uses 0 seconds as the polling interval.

**Comment by stefangordon** [comment]
I believe this is what we do today in the `setup` for our `basetest` - we patch the LRO Poller unless you set a decorator telling us not to.  Is this issue still valid?

**Comment by stefangordon** [comment]
Going to close unless it comes up again somewhere as a problem.
