### ISSUE TITLE
azure - event grid mode needs to verify resource type from the event

### ISSUE THREAD

**Issue by logachev** [cloud-custodian/cloud-custodian#4162]
Seems like today Event Grid mode policies don't verify event types and always handle events as-is (e.g. autotag for VM can tag Storage if there is an event grid subscription)

**Comment by yayitserica** [comment]
### ACCEPTANCE CRITERIA

1. Fail Azure functions provisioning if subscribe events are different from the policy resource.

**Comment by stefangordon** [comment]
Before implementing please provide design for how child resources will be handled.  e.g. if you get an event for a SQL Database but the policy targets a SQL server, can you truncate the resource ID and make it work? Should you?
