### ISSUE TITLE
Azure - Docs missing for VM Images

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4176]

**Comment by logachev** [comment]
Seems like resource is supported, just not documented: https://cloudcustodian.io/docs/azure/resources/azure.mgmt.compute.html#azure-image

**Comment by stefangordon** [comment]
I love it when they are easy :) 

If someone is following up ensuring the quality of the auto-generated docs and replacing the manual ones then this would be covered there?  We should close after that is done I guess.
