### ISSUE TITLE
Azure - Filter/Action - Resource Lock

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4177]
Would like the ability to identify a locked resource, and to lock any resource.

This would be a generic ARM filter/action pair.

**Comment by anastasiia-zolochevska** [comment]
```
actions:
      - type: add-resource-lock
        lock-type: read-only/delete
```
```
filters: 
- type: resource-lock
  lock-type: read-only/delete/all
```

**Comment by logachev** [comment]
What about `lock` instead of `add-resource-lock`?

**Comment by kapilt** [comment]
just adding doc url for those curious what this is https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-lock-resources

**Comment by stefangordon** [comment]
> What about `lock` instead of `add-resource-lock`?

Yeah whatever you all think is best.  lock/unlock are fine if it won't be confused with something else (can't think of anything else off hand)

**Comment by anastasiia-zolochevska** [comment]
@logachev Do you think unlock should remove ALL locks or it should take a name of the lock and remove particular lock user specified? There can be as many locks on the resource as you want (but only 2 types)

**Comment by logachev** [comment]
When I'm thinking about it, probably there is no need in the `unlock` action. I think it still worth having filter to find locked\unlocked resources & lock action.

**Comment by anastasiia-zolochevska** [comment]
To find unlocked resources:    
```
filters:
        - not:
          - type: resource-lock
            lock-type: ReadOnly
```
