### ISSUE TITLE
Azure - Automated Docs Design

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4179]
Please review change in approach with #4166 and file detailed issues for the work that needs to be done to get Azure docs automated in a similar way.

Likely includes at least two separate issues
* Update documentation in code
* Switch to auto-generated resource docs in hierarchy

**Comment by logachev** [comment]
Docs are enabled, we should review references & update our code (possible issues with child resources: https://cloudcustodian.io/docs/azure/resources/azure.keyvault.html)

E.g. issue: https://cloudcustodian.io/docs/azure/resources/azure.keyvault.html
