### ISSUE TITLE
Azure mailer

### ISSUE THREAD

**Issue by timbo256** [cloud-custodian/cloud-custodian#4188]
I just want to confirm that SENDGRID is the only email integration currently available for the Azure implementation?

**Comment by thisisshi** [comment]
Smtp support was recently added in #4077

**Comment by timbo256** [comment]
Noted - but do we HAVE to use SENDGRID?

**Comment by thisisshi** [comment]
No

**Comment by timbo256** [comment]
So - in theory we could send smtp to AWS SES?

**Comment by logachev** [comment]
You can use any SMTP server, so yes - you can send smtp to AWS SES from Azure.

**Comment by timbo256** [comment]
Thanks for the confirmation
