### ISSUE TITLE
REQ: cross-account filer for dynamodb-table

### ISSUE THREAD

**Issue by kumarsiyer** [cloud-custodian/cloud-custodian#4193]
Dynamodb has resource based IAM permissions so it would be idle to have a cross-account filter.

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/using-identity-based-policies.html

**Comment by kapilt** [comment]
dynamodb does not have resource iam policies on tables. it allows fine grained access control via statements on user policies, ie identity based policies. cross-account filter is for resource iam policies, which is not what dynamodb does.
