### ISSUE TITLE
Azure - Update docs: Azure > Policy > Resources page - filter "ports-op" is now named "match"

### ISSUE THREAD

**Issue by yayitserica** [cloud-custodian/cloud-custodian#4198]
![image](https://user-images.githubusercontent.com/15487798/59726774-cf208a80-91e7-11e9-8a66-9718bde77b38.png)

The NSG "deny access to ports example" needs to have the "ports-op" filter updated to "match".

https://cloudcustodian.io/docs/azure/policy/resources/nsg.html

**Comment by kapilt** [comment]
we should extend the logic we have for validating policies in class doc strings (tests/test_doc_examples.py) to also do those in the docs folder so we can eliminate this class of errors.

**Comment by yayitserica** [comment]
@kapilt , does your suggestion apply to all docs/policies or is this specific to the Azure docs?

**Comment by kapilt** [comment]
@yayitserica all of the policies in the docs folder, its the same level of effort as doing it just for the azure docs. basically we just need to parse the .rst files in the docs folders for `.. code-block: yaml` and feed them to the validator that we use in tests/test_doc_examples which currently only covers policies in python class doc strings.
