### ISSUE TITLE
tools/mailer - import enum error

### ISSUE THREAD

**Issue by pju-d2si** [cloud-custodian/cloud-custodian#4201]
Hi,
with a 0.8.44, you have add provider(enum) on utils.py, but i can't find this on deploy.py/get_archive() and requirement.txt
(with manual fix, this working again)
with this error, i can't execute update-lambda

could you update the integration of "enum" plz ?

thanks for your help

**Comment by kapilt** [comment]
i assume this is wrt to c7n_mailer?

**Comment by kapilt** [comment]
what version of python are you using? enum has been around since python 2.7 and we don't support older versions.

what error are you seeing?

**Comment by kapilt** [comment]
if you have a manual fix you've already done, feel free to send a pull request...

**Comment by tut949** [comment]
Yesterday the c7n mailer lambda function started failing for me when I redeployed it. The error message in CloudWatch logs was "Unable to import module 'periodic': No module named enum". I rolled back to 
c7n==0.8.43.1
c7n-mailer==0.5.0
and the problem went away.

**Comment by kapilt** [comment]
c7n_mailer 0.5.2 released with fix

**Comment by tut949** [comment]
That worked for me, thanks!
