### ISSUE TITLE
Cask - Binary Releases

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4219]
Working up easy installation techniques for Cask - but we need to figure out where we can release binaries:

Four options I am aware of:

1) Make another full release of custodian, but include `custodian-cask` binaries. 
2) Make a release dedicated to Cask with a cask prefix (what downstream effects are there to this?)
3) Make a Cask repo (easy, but breaks a bit with existing repo convention - maybe exception as releasing a binary is critical to Cask purpose)
4) Punt on this and use https://custodiancask.blob.core.windows.net/cask/ for a bit.

**Comment by stefangordon** [comment]
We are going to setup a pipeline to push releases to storage exposed at https://cloudcustodian.io/downloads

**Comment by kapilt** [comment]
afaik, this is complete
