### ISSUE TITLE
AWS Codecommit - Filter resources based on repo name

### ISSUE THREAD

**Issue by LRuttenCN** [cloud-custodian/cloud-custodian#4233]
I want to do an invoke-lambda event with CloudCustodian triggering on a MergePullRequestByFastforward cloudtrail event. However, for the event does not contain repository ID's (only the name). Therefore, whenever an event occurs it will never be able to trigger my lambda.

Is it possible for cloudtrail mode to NOT filter on resources ('ids': *), but just do an 'event' filter and then an action? 

The alternative would be support for allowing resource filtering by repositoryName instead of ID, but this will cause compatibility issues.. And I guess by allowing 2 keys instead of one (either name or ID) is also a bit of a hassle. 

Any advice on this?

**Comment by kapilt** [comment]
what does your policy look like? in general we always want to fetch a resource for a given cloud trail event. For cases where thats not applicable (resource deleted, etc), we have a synthetic `account` resource which is always present and can be used for those policies. The event filter can then be used to narrow to applicable events.

looking over the code commit resource, it looks like we should be using repo name for the id, as thats what all the apis take.

**Comment by LRuttenCN** [comment]
Does this also work if the event is originating from another account? We forward events from all accounts to one central account, so the account ID of the event might differ from the account processing the event.

```python
policies:
  - name: pullrequest-approved-by-creator
    resource: codecommit
    description: |
      Check if a codecommit pull request has been approved by the creator of the pull request in the ccc source account.
    mode:
      type: cloudtrail
      events:
        - source: codecommit.amazonaws.com
          event: MergePullRequestByFastForward
          ids: "userIdentity.sessionContext.sessionIssuer.userName"
        - source: codecommit.amazonaws.com
          event: MergePullRequestBySquash
          ids: "requestParameters.repositoryName"
        - source: codecommit.amazonaws.com
          event: MergePullRequestByThreeWay
          ids: "requestParameters.repositoryName"
      packages: [boto3, botocore, urllib3] 
#    filters:  # value_type: expr filter does not work yet in current cloud custodian. Write lambda instead.
#      - type: event
#        key: "detail.responseElements.pullRequest.authorArn"
#        value_type: expr
#        op: equal
#        value: "detail.responseElements.pullRequest.pullRequestTargets[0].mergeMetadata.mergedBy"
    actions:
      - type: invoke-lambda
        function: raise_error
        async: false
```

**Comment by kapilt** [comment]
those aren't cloudtrail events they are codecommit cwe events. we haven't historically supported arbitrary cloud watch events, we've added in support for them case by case and currently support ec2/asg instance notification, cloudtrail, phd/health, guard-duty. i'm amenable to adding in some more generic cwe support though, although i'm a bit unclear what the use case in this specific example is, wouldn't it just follow to make it invoke lambda a direct subscriber of the event in question?

wrt to centralized/non centralized and events, if you define a member-role template on your mode (ie arn with `{account_id}`, the cross account sts assume will happen before resource resolution using the account id from the event.

**Comment by kapilt** [comment]
ah ic, it looks like your working around the expr stuff re the custom lambda?, i'll see if i can get that pr resolved in the next day or so.

**Comment by LRuttenCN** [comment]
> ah ic, it looks like your working around the expr stuff re the custom lambda?, i'll see if i can get that pr resolved in the next day or so.

Awesome, thanks!

> wouldn't it just follow to make it invoke lambda a direct subscriber of the event in question

Yes, it would in the current situation

> wrt to centralized/non centralized and events, if you define a member-role template on your mode (ie arn with `{account_id}`, the cross account sts assume will happen before resource resolution using the account id from the event.

True, but then it would try to invoke the lambda in all member accounts. It's easier to govern one central lambda in our security account.

**Comment by kapilt** [comment]
afaics this has been addressed in trunk, value_type: expr works, and code commit now supports fetching by repo names instead of ids. the arbitrary cwe stuff i'm going to defer. feel free to comment/reopen if there's something missing.

**Comment by LRuttenCN** [comment]
perfect! Thank you!!
