### ISSUE TITLE
gcp - cloud function deployment via policy issue

### ISSUE THREAD

**Issue by mediapills** [cloud-custodian/cloud-custodian#4235]
I am trying to deploy gcp cloud function via cloud-custodian policy. Everything works fine except one issue when I am trying to execut this function on gcp via pub/sub.

Here is traceback from stackdriver:

`File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 383, in run_background_function _function_handler.invoke_user_function(event_object) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 217, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 214, in call_user_function event_context.Context(**request_or_event.context)) File "/user_code/main.py", line 21, in run from c7n_gcp.handler import run File "/user_code/c7n_gcp/handler.py", line 24, in <module> from c7n_gcp.entry import initialize_gcp File "/user_code/c7n_gcp/entry.py", line 20, in <module> import c7n_gcp.resources.appengine File "/user_code/c7n_gcp/resources/appengine.py", line 18, in <module> from c7n_gcp.query import QueryResourceManager, TypeInfo, ChildResourceManager, ChildTypeInfo File "/user_code/c7n_gcp/query.py", line 22, in <module> from c7n.actions import ActionRegistry File "/user_code/c7n/actions/__init__.py", line 17, in <module> from .autotag import AutoTagUser File "/user_code/c7n/actions/autotag.py", line 18, in <module> from c7n.manager import resources File "/user_code/c7n/manager.py", line 24, in <module> from c7n.resources.aws import AWS File "/user_code/c7n/resources/aws.py", line 31, in <module> import boto3 ModuleNotFoundError: No module named 'boto3'`

My assumption that somehow boto3 has been removed from requirements but it still needs to be present for gcp provider.

**Comment by alexkarpitski** [comment]
Looks like it all started from this commit: https://github.com/cloud-custodian/cloud-custodian/commit/94c60ff7d5067947026b5216c3d275518c0677ed

**Comment by kapilt** [comment]
boto3 should not be required for runtime execution in serverless environments for azure and gcp, its a bug if it is.
