### ISSUE TITLE
Azure - automatic tagging should support adding "Created date"

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4239]
We can also consider alternatives if there is a better way to implement this.   Perhaps one alternative is just using the normal tag action with an event based policy.

**Comment by kapilt** [comment]
its worth looking at what the aws tag base class does it supports variables interpolation in tags including a date time helper for current or future time (ie now+7d). it's also fairly abstract to the underlying resource and provider..
