### ISSUE TITLE
ci - investigate codecov upload issues

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#4252]
codecov has been failing to upload about 40% of the time, the issue has been reported a few times but no responses.

https://github.com/codecov/codecov-python/issues/196

**Comment by ajkerrigan-mdsol** [comment]
Is it worth giving the [codecov-bash](https://docs.codecov.io/docs/about-the-codecov-bash-uploader) uploader a shot? Seems like it's the way codecov is moving, and pytest's changeover might be a useful reference - pytest-dev/pytest@739f9a4a4b0ae2efe105f3a6561088dac5096941 .

**Comment by kapilt** [comment]
@ajkerrigan-mdsol Thanks! that seems promising and looks like it would let us also drop some of the custom frontends we had to do azure pipelines integration.
