### ISSUE TITLE
Add modify-security-groups action to aws.lambda and aws.app-elb

### ISSUE THREAD

**Issue by dylac** [cloud-custodian/cloud-custodian#4263]
Hi c7n team,

We'd like to be able to use the same action as aws.ec2 but for Lambda and ALBs for changing security groups. Currently we're having to use manual scripts for these resource types. Is this on your roadmap?

Thanks!

**Comment by kapilt** [comment]
s/team/community... pull requests welcome.

**Comment by dylac** [comment]
Hold that thought, taking a crack at it myself... :)

**Comment by kapilt** [comment]
this might be helpful re dev docs https://cloudcustodian.io/docs/developer/tests.html#developer-tests
