### ISSUE TITLE
Security hub - configure Product and Company fields

### ISSUE THREAD

**Issue by JPPienaar** [cloud-custodian/cloud-custodian#4285]
All findings pushed to SecurityHub using the post-finding action results in the Product and Company fields being default. Could this be changed to be configurable?

![image](https://user-images.githubusercontent.com/5518309/60330381-9aa09180-9992-11e9-896c-950082a4ff11.png)

**Comment by kapilt** [comment]
this is a limitation of security hub,  any finding an organization post for itself all show this way (using the default product arn). its worth reaching out to your account representative to file a feature request for this display to be changed. security hub uses a notion of production registration for commercial tools that involves a secret token generation that doesn't mesh well with open source tools.

**Comment by JPPienaar** [comment]
Thanks for reaching out, I will get in touch with our TAM.
