### ISSUE TITLE
Azure - Docs - Logic App Notification Scenario

### ISSUE THREAD

**Issue by aluong** [cloud-custodian/cloud-custodian#4302]
Related to #4142 

This scenario is focused on creating a webhook to an Http Triggered Logic App that can send emails via an Office 365 Connection.

**Comment by Herman-Wu** [comment]
Thanks for the sample scenario. 
Currently the Http Trigger has to be named as "manual" because the name is been hard coded in 'logic_app.py but this is not been mentioned in document.  It will be better if we add a note about this part.
