### ISSUE TITLE
allow absent/present value for metric filters?

### ISSUE THREAD

**Issue by ajkerrigan-mdsol** [cloud-custodian/cloud-custodian#4320]
I'm looking at various ways to use metrics to flag unused ELBs. [The ELB garbage collection example](https://cloudcustodian.io/docs/usecases/elbgarbagecollection.html) covers one type of unused ELB - one with no backing instances. However, it'd be useful to identify other types of inactivity:

* ELBs with no healthy hosts (already possible with the existing metric filter, since CloudWatch always reports the `HealthyHostCount` metric).
* ELBs with low/no requests for a given period. This one is tricky because the `RequestCount` metric only shows up when there are metrics to report.

Is there a way to catch metrics that might be 0 or non-existent with existing policy logic? If not, would it be valuable to allow something like `ValueFilter`'s special `absent` value to identify those cases? Or would that be more confusing/misleading than valuable?

**Comment by kapilt** [comment]
there's a few cases you can run into absent semantics, another which can cause problems with policies like this if the resource is to new (or stopped in the case of ec2 instance). in which case it may not have much metrics history. on a whole though yeah, I'm game for features in regard to this. It would be relatively easy to catch 0 metrics if their reported as such, if their not posted as such, then we need to deal with the absent case, but that has caveats per above that would need documentation.

**Comment by ajkerrigan-mdsol** [comment]
#4348 closes this.
