### ISSUE TITLE
Need to detect who have created the tag

### ISSUE THREAD

**Issue by techsami** [cloud-custodian/cloud-custodian#4330]
Hi,

I have a use case to identify who have created the tag and delete the tag if not created by authorised role/user.

I am trying this usecase on EC2 with following sample code which may be wrong and where I need your help:

policies:
 - name: Detect_EC2_ComplianceException_protected
   resource: ec2
   mode:
     type: cloudtrail
     <<: *role-var
     events:
       - source: ec2.amazonaws.com
         event: CreateTags
         ids: "requestParameters.resourcesSet.items[].resourceId"
       - source: ec2.amazonaws.com
         event: CreateTags
         ids: "userIdentity.sessionContext.sessionIssuer.userName"
   filters:
       - "tag:ComplianceException": present
       - type: value
         key: "userName"
         value: .*AWSOrganisations.*
         op: regex
   actions:
       - type: notify

**Comment by kapilt** [comment]
mode ids always refers to how to get the policy's resource types ids from the event. event attributes can be filtered with the event filter, and events are part of the payload sent in notify and available in templates.

**Comment by techsami** [comment]
Hi Kapil, So in my case, if I wanted to catch the event id and filter it using filter, is there any way?
ids: "userIdentity.sessionContext.sessionIssuer.userName"

**Comment by kapilt** [comment]
you filter an event with the event filter
```
type: event
key: userIdentity.sessionContext.sessionIssuer.userName
value:
   - Bob
   - alice
op: in
```
