### ISSUE TITLE
Support for colon (:) in tag names

### ISSUE THREAD

**Issue by SebastianCelejewski** [cloud-custodian/cloud-custodian#4333]
[AWS Tagging Strategies](https://aws.amazon.com/answers/account-management/aws-tagging-strategies/) document provides examples of tag names that support cost allocation, automation, access control, etc. These sample tag names contain colons (:), e.c. "user:Owner", "user:Stack", "user:CostCenter", etc.

Cloust Custodian filters and actions don't support colons in tag names. Colons are treated as a part of yaml syntax, e.g. here in c7n/filters/core.py:

```python
tk = k.split(':', 1)[1]

**Comment by kapilt** [comment]
is this theoretical? do you have an example policy a resource with a tag with a colon not working?

the python statement your quoting, does  one split on a tag name, since custodian prefixes tags with a tag:Name the name in this line could contain a colon.

**Comment by SebastianCelejewski** [comment]
Sorry. When testing this I have not disabled cache. It is working fine with colons in tag names.

**Comment by mat-santoro** [comment]
Has anyone been able to make this work?
```

Using filters as
 filters:
  - "tag:foo:bar": absent
```

Does not work
