### ISSUE TITLE
attach layer on lambda rules policy

### ISSUE THREAD

**Issue by pju-d2si** [cloud-custodian/cloud-custodian#4334]
Hello,
i use c7n 0.8.44.2, i have read your issues about lambda layer 
- https://github.com/cloud-custodian/cloud-custodian/issues/3405
- https://github.com/cloud-custodian/cloud-custodian/pull/3886

but if i have good understand features added in issue 3886, is for create a layer with cloudcustodian.
i would attached a layer to my lambda with deployment "mode periodic", for use last version of security hub in boto3 on lambda with my layer botolatest already create.

have you already work on this and I would have missed this features ?

actually a best solution is repackage boto3 lambda   
   packages:
        - botocore
        - boto3
   https://github.com/cloud-custodian/cloud-custodian/issues/3510

thank in advanced for your help

**Comment by kapilt** [comment]
you can specify a layer in your mode that will be used for functions, in that case the layer construction is done out of band of custodian.

**Comment by pju-d2si** [comment]
oh thanks, i understand, i have really missed some thing, have you a documentation ? i do not find this, except this docs :
https://cloudcustodian.io/docs/aws/aws-modes.html

**Comment by kapilt** [comment]
its in the schema for the modes on the page referenced minus poll which is a non lambda mode.

```
  layers:
    items:
      type: string
    type: array
```

**Comment by pju-d2si** [comment]
ok many thanks for your support
