### ISSUE TITLE
Any variable for instance type?

### ISSUE THREAD

**Issue by mkadali99** [cloud-custodian/cloud-custodian#4339]
I want to send notifications to Owners where I want to include the instance type and the CPU utilization of the instance. How can we do that?

**Comment by kapilt** [comment]
the full describe output for a resource is available in mailer templates, ie .. {{resources}} is a an array of resources descriptions. if you use a metrics filter in your policy the resource will be annotated with the metrics information queried which can then be used in the message template for rendering emails.
