### ISSUE TITLE
Azure - azure.armresource should include `type` as default report field 

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4340]
Please update report fields so we can see the resource type when we enumerate this generic resource.

**Comment by jomalsan** [comment]
@stefangordon do you want the default report fields for just the `ArmTypeInfo` objects to have the `type` field? A few resources (Cosmos DB) override the default report fields after inheriting from `ArmTypeInfo` so will need to be updated as well to include the `type` field if we want all Arm Resources to have it
