### ISSUE TITLE
Azure - max_resource does not work 

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4347]
Probably not implemented in our query.py

e.g. https://github.com/cloud-custodian/cloud-custodian/pull/2854/files#diff-9e36607e744130a1127b0d4210b50b43R436

~Also, this thing does not appear to be documented.~

**Comment by kapilt** [comment]
its documented over here https://cloudcustodian.io/docs/quickstart/advanced.html#policy-resource-limits
