### ISSUE TITLE
Retain start:/end: policy functionality

### ISSUE THREAD

**Issue by davidkshepherd** [cloud-custodian/cloud-custodian#4359]
Bumping this for consideration: https://github.com/cloud-custodian/cloud-custodian/issues/4278

Can I make a request to keep the current start:/end: policy functionality until the new 'conditional execution at runtime evaluation' method is complete?  I use that function to gradually roll out policies from and initial "Notify Only" Policy to enforcement.  It allows me to set up a set of policies with specific dates/times that policy changes will occur without having to merge/deploy code at a specific date/time. I WISH start: & end: worked with CT, but can work around that. 
Thanks!

**Comment by kapilt** [comment]
we'll retain the functionality subject to a deprecation period (which won't start till their's a replacement), we haven't formally declared what a deprecation period would look like, but I'm guess/thinking six months. wrt to start/stop ct support what about if those ct policies never provisioned if they have a start/stop date that hasn't hit.. the stop date wouldn't work in that scenario but the start date would.

**Comment by kapilt** [comment]
@davidkshepherd do you use the tz functionality here? Its likely not something we'll support as a separate field vs embedding the tz in the start/end values (ie. iso date style).

**Comment by davidkshepherd** [comment]
The TZ is not a deal breaker for me.  No issues moving to iso date style.
Thanks!

**Comment by kapilt** [comment]
cool, thanks for confirming, fwiw, I've put a draft pr that shows what the new conditions might look like, its more proposal for feedback at the moment,  https://github.com/cloud-custodian/cloud-custodian/pull/4466

**Comment by davidkshepherd** [comment]
Nice!  TY

**Comment by kapilt** [comment]
policy conditions support is ready for merge, and includes compatibility for now on start/end syntax, but please consider it deprecated with the new release. tbd on when we can actually yank it but its post a deprecation framework.
