### ISSUE TITLE
azure - update app settings with latest Azure Functions necessary settings

### ISSUE THREAD

**Issue by aluong** [cloud-custodian/cloud-custodian#4370]
1. Use image tag `2.0-python3.6-appservice`
2. Remove AzureWebJobsDashboard setting (#3551)
3. Remove MACHINEKEY_DecryptionKey setting

**Comment by stefangordon** [comment]
Hey @aluong is this still valid/pending?

**Comment by aluong** [comment]
This is fixed with #4411
