### ISSUE TITLE
copy tags to ebs from ec2

### ISSUE THREAD

**Issue by mkadali99** [cloud-custodian/cloud-custodian#4375]
I have this policy to copy tags from ec2 to ebs. 

- name: copy-tags-from-ec2-to-volume
  resource: ebs
  actions:
    - type: copy-related-tag
      resource: ec2
      skip_missing: True
      key: InstanceId
      tags:
        - ["AppID"]
        - ["CostCenter"]
        - ["DataClassification"]
        - ["DR Tier"]
        - ["Name"]
        - ["Origin"]
        - ["Owner"]
        - ["Schedule"]
        - ["ebs lifecycle"]

I don't see the tags are copied when i run the policy. Is it an issue with the policy?

**Comment by kapilt** [comment]
Tags is an array of strings you have here an array of arrays, ideally that wouldn’t pass validation
