### ISSUE TITLE
azure - Refactor API Management Resize action to use API management SDK 

### ISSUE THREAD

**Issue by anastasiia-zolochevska** [cloud-custodian/cloud-custodian#4376]

**Comment by anastasiia-zolochevska** [comment]
The code for the action should be: 
`
    def _prepare_processing(self):
        self.client = self.session.client('azure.mgmt.apimanagement.ApiManagementClient')    

   def _process_resource(self, resource):
        self.client.api_management_service.update(
            resource['resourceGroup'],
            resource['name'],
            ApiManagementServiceUpdateParameters(
                sku=ApiManagementServiceSkuProperties(name=self.tier, capacity=self.capacity))
        )
`

Currently blocked by https://github.com/Azure/azure-sdk-for-python/issues/6335

**Comment by stefangordon** [comment]
Looks like a workaround was recommended in the upstream bug and they don't plan any additional fixes for now, so we should just compare the workaround to our existing code and update.

Don't think we are blocked at this time.
