### ISSUE TITLE
Azure - Update Docs about Periodic Functions

### ISSUE THREAD

**Issue by aluong** [cloud-custodian/cloud-custodian#4377]
The documentation under Functions doesn't do a clear job talking about periodic functions and their cron job syntax.

https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer#cron-expressions

**Comment by stefangordon** [comment]
Yeah we should at least link people to this.

**Comment by jomalsan** [comment]
I will fix these docs
