### ISSUE TITLE
Policy works local but not for multi account

### ISSUE THREAD

**Issue by martinklie** [cloud-custodian/cloud-custodian#4387]
Hi,

We have c7n-org running well with the s3-enable-versioning.yml policy below but when we try unused-sgroups-audit.yml and enable-kms-rotation.yml nothing happens.  We just change the policy name on the CLI.  Output is below

sh-4.2$ cat s3-enable-versioning.yml
policies:
  - name: s3-enable-versioning
    resource: s3
    actions:
      - type: toggle-versioning
        enabled: true

sh-4.2$ cat unused-sgroups-audit.yml
policies:
  - name: unused-sgroups-audit
    resource: security-group
    filters:
      - unused
      - type: value
        key: GroupName
        op: regex
        value: "launch-wizard*"
    actions:
      - delete

sh-4.2$ cat enable-kms-rotation.yml
policies:
  - name: enable-kms-rotation
    resource: kms-key
    filters:
      - type: key-rotation-status
        key: KeyRotationEnabled
        value: false
    actions:
      - type: set-rotation
        state: True

sh-4.2$ c7n-org run -c testacct.yml -s s3://logs-storage-s3 -u unused-sgroups-audit.yml --region us-east-1

Traceback (most recent call last):
  File "/usr/local/bin/c7n-org", line 11, in <module>
    load_entry_point('c7n-org==0.5.3', 'console_scripts', 'c7n-org')()
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/c7n_org/cli.py", line 605, in run
    config, use, debug, verbose, accounts, tags, policy, policy_tags=policy_tags)
  File "/usr/local/lib/python3.7/site-packages/c7n_org/cli.py", line 182, in init
    jsonschema.validate(accounts_config, CONFIG_SCHEMA)
  File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 899, in validate
    raise error
jsonschema.exceptions.ValidationError: [{'account_id': '11111111111111', 'email': 'aws-test-12@br.com', 'name': 'log-archive', 'role': 'arn:aws:iam::11111111111111:role/CloudCustodianRole', 'tags': ['path:/core']}, {'account_id': '11111111111111', 'email': 'aws-test-13@br.com', 'name': 'security', 'role': 'arn:aws:iam::11111111111111:role/CloudCustodianRole', 'tags': ['path:/core']}, {'account_id': '11111111111111', 'email': 'bfs-gto-sbx@br.com', 'name': 'BFS GTO Sbx', 'role': 'arn:aws:iam::11111111111111:role/CloudCustodianRole', 'tags': ['path:/BFS', 'path:/BFS/SBX', 'path:/BFS/SBX/GTO']}] is not of type 'object'

Failed validating 'type' in schema:
    {'$schema': 'http://json-schema.org/schema#',
     'additionalProperties': False,
     'definitions': {'account': {'additionalProperties': True,
                                 'anyOf': [{'required': ['role',
                                                         'account_id']},
                                           {'required': ['profile',
                                                         'account_id']}],
                                 'properties': {'account_id': {'type': 'string'},
                                                'email': {'type': 'string'},
                                                'external_id': {'type': 'string'},
                                                'name': {'type': 'string'},
                                                'profile': {'minLength': 3,
                                                            'type': 'string'},
                                                'regions': {'items': {'type': 'string'},
                                                            'type': 'array'},
                                                'role': {'oneOf': [{'items': {'type': 'string'},
                                                                    'type': 'array'},
                                                                   {'minLength': 3,
                                                                    'type': 'string'}]},
                                                'tags': {'items': {'type': 'string'},
                                                         'type': 'array'},
                                                'vars': {'type': 'object'}},
                                 'type': 'object'},
                     'project': {'additionalProperties': False,
                                 'properties': {'name': {'type': 'string'},
                                                'project_id': {'type': 'string'},
                                                'tags': {'items': {'type': 'string'},
                                                         'type': 'array'},
                                                'vars': {'type': 'object'}},
                                 'required': ['project_id'],
                                 'type': 'object'},
                     'subscription': {'additionalProperties': False,
                                      'properties': {'name': {'type': 'string'},
                                                     'subscription_id': {'type': 'string'},
                                                     'tags': {'items': {'type': 'string'},
                                                              'type': 'array'},
                                                     'vars': {'type': 'object'}},
                                      'required': ['subscription_id'],
                                      'type': 'object'}},
     'id': 'http://schema.cloudcustodian.io/v0/orgrunner.json',
     'oneOf': [{'required': ['accounts']},
               {'required': ['projects']},
               {'required': ['subscriptions']}],
     'properties': {'accounts': {'items': {'$ref': '#/definitions/account'},
                                 'type': 'array'},
                    'projects': {'items': {'$ref': '#/definitions/project'},
                                 'type': 'array'},
                    'subscriptions': {'items': {'$ref': '#/definitions/subscription'},
                                      'type': 'array'},
                    'vars': {'type': 'object'}},
     'type': 'object'}

On instance:
    [{'account_id': '11111111111111',
      'email': 'aws-test-12@br.com',
      'name': 'log-archive',
      'role': 'arn:aws:iam::11111111111111:role/CloudCustodianRole',
      'tags': ['path:/core']},
     {'account_id': '11111111111111',
      'email': 'aws-test-13@br.com',
      'name': 'security',
      'role': 'arn:aws:iam::11111111111111:role/CloudCustodianRole',
      'tags': ['path:/core']},
     {'account_id': '11111111111111',
      'email': 'bfs-gto-sbx@br.com',
      'name': 'BFS GTO Sbx',
      'role': 'arn:aws:iam::11111111111111:role/CloudCustodianRole',
      'tags': ['path:/BFS', 'path:/BFS/SBX', 'path:/BFS/SBX/GTO']}]
sh-4.2$

**Comment by kapilt** [comment]
please don't post account ids to issues, the error here looks like your accounts config file is not validating. the config file is a mapping, with a top level key of `accounts` which contains an array of accounts.
