### ISSUE TITLE
azure - allow users to exclude certain subs from management groups

### ISSUE THREAD

**Issue by logachev** [cloud-custodian/cloud-custodian#4393]
c7n-org, serverless: users should be able to provide list of exceptions for policies.

**Comment by yayitserica** [comment]
### ACCEPTANCE CRITERIA

1. User can exclude specific subscriptions from a management group for a policy run.

**Comment by kapilt** [comment]
There is some ambiguity on what this means, depending on different usage perspectives, it can mean not provisioning in a target account/subscription in a leaf deployment strategy, or it can mean not executing on a subscription/account event in a acentralized deploy setup

**Comment by kapilt** [comment]
policy conditions caters to this use case #4466
