### ISSUE TITLE
azure - reference tag value in actions

### ISSUE THREAD

**Issue by logachev** [cloud-custodian/cloud-custodian#4394]
Would be great if we can reference tag value from actions..

E.g.: scale CosmosDB based on on\off hours and maintain scale state in resource tags.

**Comment by stefangordon** [comment]
This fits into previous discussions on more generic support for substitutions/lookups in all value fields (or at least generic way to support this feature in value fields as needed).  Lets make the action item here writing up a summary of the immediate and future scenarios (tag lookup, secret lookup, jmespath support) and start a Design issue/thread to see if we can make something happen.

**Comment by yayitserica** [comment]
### ACCEPTANCE CRITERIA

1. Write up summary of immediate & future scenarios (tag lookup, secret lookup, jmespath support).
2. Create a new GitHub issue to investigate design of implementing this tag value feature.

FYI @logachev
