### ISSUE TITLE
azure - cosmos db firewall bugs

### ISSUE THREAD

**Issue by logachev** [cloud-custodian/cloud-custodian#4396]
CosmosDB firewall is an opposite: "List of blocked IP addresses". Doesn't work well with empty list, needs investigation.

**Comment by stefangordon** [comment]
I think actually cosmos does work the other way (allow list).  I'm having trouble remembering the exact issue we ran into here, but with the recent enhancements I made to the filter I suspect it is possible to do most queries now, so closing this.
