### ISSUE TITLE
azure - review 'default fields' in c7n report

### ISSUE THREAD

**Issue by logachev** [cloud-custodian/cloud-custodian#4397]
We should review 'default fields' for all Azure resources.

**Comment by kapilt** [comment]
might be worth a meta test for the azure, to assert that all resources have report fields defined.

**Comment by stefangordon** [comment]
We do have a few specific cases where from a user perspective having a filter add a default report field would be the ideal behavior.  E.g. expensive lookups that you almost always want to have in your output like Cost, which can apply to any resource.

Given that most people will never figure out how to use --field on windows to properly escape a `c7n:` prefixed field having them in by default would help :) 

I think if there is a clean way to do this it would be cool.

**Comment by yayitserica** [comment]
### ACCEPTANCE CRITERIA

1. Review all resources to decide what resource-specific fields to include in their respective C7N reports.

**Comment by wsf11** [comment]
I'll look at this
