### ISSUE TITLE
azure - assignment role `scope` filter should support 'Azure', 'Management Group'

### ISSUE THREAD

**Issue by logachev** [cloud-custodian/cloud-custodian#4398]
`scope` filter doesn't support root & management group scopes.

**Comment by logachev** [comment]
@stefangordon do we have any role assignment with 'Azure' scope in our subs?

**Comment by stefangordon** [comment]
If they exist I assume we'd see them when we run the role assignment enumeration.   I actually was not familiar with them so I had assumed the title was erroneous, but I see in your description you definitely intended it on purpose so maybe we missed something here?

**Comment by erwelch** [comment]
Oh missed it in the title - just read 'Azure Management Group' instead of 'Azure', 'Management Group' - I assume it's a small add. I can look at that today.

**Comment by erwelch** [comment]
From the docs it doesn't look like you can provide an 'Azure' scope on RBAC roles: https://docs.microsoft.com/en-us/azure/role-based-access-control/rbac-and-directory-admin-roles

Only the directory admin roles have tenant level scope specifically for AAD permissions, but that's not supported in this scenario.

**Comment by erwelch** [comment]
Although does look like there is 1 scenario where this is possible and the scope appears to be 'Root (inherited)': https://docs.microsoft.com/en-us/azure/role-based-access-control/elevate-access-global-admin

**Comment by erwelch** [comment]
Cool it appears as just a '/' scope - I can add that.
