### ISSUE TITLE
azure - role assignment should cache role name

### ISSUE THREAD

**Issue by logachev** [cloud-custodian/cloud-custodian#4399]
role name is not available via `c7n report` or in `resources.json`

**Comment by stefangordon** [comment]
Lets get the role name (and any other fields we look up there) added to the resource dictionary with a `c7n:` prefix, and maybe include in default report filters array if it makes sense.

**Comment by erwelch** [comment]
The filter in question is a 'Related Resource Filter' - needs investigation into caching on the base class.
