### ISSUE TITLE
azure - Filter on SSL settings of Web App/Function App

### ISSUE THREAD

**Issue by logachev** [cloud-custodian/cloud-custodian#4401]
We need a filter that supports looking at the SSL settings in Azure App Services (and Function Apps) which are Kudu/Webapps. 

You can see these in the portal, but they aren't actually ARM settings, they are a special API that talks to Kudu.  It appears there is a documented REST endpoint for these that is RBAC auth, so we should be able to do this with a custom filter and hand crafted HTTP call - pretty similar to how we call the Functions Zip Deploy code on Kudu to deploy functions.

**Comment by axis7818** [comment]
The basic "Protocol Settings" seem to be available through ARM APIs:

* [minTlsVersion](https://docs.microsoft.com/en-us/rest/api/appservice/webapps/getconfiguration)
* [httpsOnly and clientCertEnabled](https://docs.microsoft.com/en-us/rest/api/appservice/webapps/get) (available directly on the resource)

So, adding a custom value filter on the `Get Configuration` call would be helpful

**Comment by jomalsan** [comment]
@stefangordon If no one else is working on this I will do it

**Comment by stefangordon** [comment]
@jomalsan sure! I believe the Virtual Machine InstanceViewFilter is a similar idea to the subclassed value filter we are talking about here, except it is able to use the SDK to make the call and I'm not sure there is an SDK for this one, it may just be Requests with the auth token (we do this for functions deployment elsewhere).
