### ISSUE TITLE
azure - 'scope' filter includes everything for the Resource Group

### ISSUE THREAD

**Issue by logachev** [cloud-custodian/cloud-custodian#4403]
Searching for the role assignments at RG scope returns all role assignments that have smaller scope (e.g. VM, Storage)

**Comment by kapilt** [comment]
whats the proposed solution? to only query role assignments valid at the root scope of the rg?

**Comment by logachev** [comment]
Yeah, if some SP has access to the Virtual Machine resource only, it should not be marked for Resource Group scope.
