### ISSUE TITLE
Discussion - Add `.env` support?

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4404]
Feels like adding `.env` support would be a big usability win?  

https://github.com/theskumar/python-dotenv

It is only one line to enable it.  But it is one more dependency...

Most interactions I have had with users involve them struggling with the workflow of managing many environment variables and having the environment variables in a `.env` file on disk would make dev easier.

Are people just using scripts to simplify this sort of stuff today?  

I guess you could do `export $(egrep -v '^#' .env | xargs)` natively in Bash, but I always find apps with `.env` support very pleasant to use :)

**Comment by kapilt** [comment]
i've generally regarded this as a property/responsibility of the tool executing custodian. ie systemd unit files or docker or kubernetes, or xyz.. all of the named of which directly support setting a set of environment variables from a file.
