### ISSUE TITLE
Running c7n in cron

### ISSUE THREAD

**Issue by martinklie** [cloud-custodian/cloud-custodian#4415]
Apologies up front if this is not the place for this type of question.

We run the below successfully from command line

 c7n-org run -c /home/ssm-user/cloud-custodian/tools/c7n_org/scripts/accounts.yml -s s3://logs-storage-s3 -u /home/ssm-user/cloud-custodian/tools/c7n_org/scripts/s3-enable-versioning.yml --region us-east-1 --region us-west-2

But when we cron the same we get the below message.  Any thoughts would be appreciated to resolve.

Subject: Cron <ssm-user@ip-10-X-X-X> c7n-org run -c /home/ssm-user/cloud-custodian/tools/c7n_org/scripts/accounts.yml -s s3://logs-storage-s3 -u /home/ssm-user/cloud-custodian/tools/c7n_org/scripts/s3-enable-versioning.yml --region us-east-1 --region us-west-2
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <XDG_SESSION_ID=4>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/1001>
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/home/ssm-user>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=ssm-user>
X-Cron-Env: <USER=ssm-user>
Date: Thu, 18 Jul 2019 14:00:02 +0000 (UTC)
Status: RO

Traceback (most recent call last):
  File "/usr/bin/c7n-org", line 11, in <module>
    load_entry_point('c7n-org==0.5.3', 'console_scripts', 'c7n-org')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/c7n_org/cli.py", line 41, in <module>
    from c7n.provider import get_resource_class
ImportError: cannot import name get_resource_class

**Comment by kapilt** [comment]
you have a mismatched version of custodian and c7n-org. you can upgrade via pip install -U c7n-org and pip install -U c7n ... alternatively use one of our docker images
https://hub.docker.com/u/cloudcustodian

**Comment by martinklie** [comment]
Please see the below prior where pip3 resolved the issue.  Not sure if that changes anything.

https://github.com/cloud-custodian/cloud-custodian/issues/4313

custodian version 0.8.44.3

May we try pip3 install -U c7n-org

**Comment by kapilt** [comment]
your traceback is referencing python2 system paths, you need both c7n-org and c7n installed with the right version and a consistent version of python, if you want to use python3 and pip3 then use that consistently. if your not familiar with python and virtualenvs, i'd highly recommend using the docker images to avoid installation troubles.

**Comment by martinklie** [comment]
adding path /usr/local/bin/c7n-org resolved it.  Thanks

**Comment by mayankmajreti1** [comment]
hiii 
if i have cloudcustodian/mailer image & policy,yml , mailer.yml   , so what will be the commands to run the script that will be use in cronjob ???
