### ISSUE TITLE
AWS - SNS [ERROR] AttributeError: 'SNS' object has no attribute 'list_tags_for_resource'

### ISSUE THREAD

**Issue by tuxinaut** [cloud-custodian/cloud-custodian#4424]
# Background

`Cloud Custodian`: `0.8.44.1`

Event based `SNS` policies (Lambda) for checking tags has a reproducible error:

```
[ERROR] AttributeError: 'SNS' object has no attribute 'list_tags_for_resource'
```

Here the complete log with stack trace:

[sns_issue.txt](https://github.com/cloud-custodian/cloud-custodian/files/3417383/sns_issue.txt)

**Comment by PratMis** [comment]
Do you mind posting a sample of the policy you're trying to execute? Thanks!

**Comment by PratMis** [comment]
Looks like you're running an old version of boto3, https://github.com/boto/boto3/issues/1993

**Comment by kapilt** [comment]
lambda policies may need to upload packages based on old versions adding `packages: [boto3, botocore, urllib3]` to the mode. the lambda version of boto3 was last updated oct 2018, tbd on an update. there's some work in a pr to auto layer boto3 but not merged as of yet.

**Comment by tuxinaut** [comment]
I was on vacation and found just now time to have a look and write back.

@PratMis @kapilt thank you very much for clarification :+1:
