### ISSUE TITLE
azure - should not deploy functions without service principals

### ISSUE THREAD

**Issue by aluong** [cloud-custodian/cloud-custodian#4438]
There seems to be a regression where we are allowed to deploy an Azure Function without the service principal credentials set. The auth file is essentially just has null values. We should stop the deployment, and provide a warning like we did in the past.

**Comment by yayitserica** [comment]
### ACCEPTANCE CRITERIA

1. Azure Functions are not allowed to be deployed without having set service principal credentials.
2. Check for null values in auth files should be occur.
3. If any null values exist, deployment should be stopped and notification/warning should be triggered to user.

FYI @aluong
