### ISSUE TITLE
Docs generating issue

### ISSUE THREAD

**Issue by evhenyshaliov** [cloud-custodian/cloud-custodian#4471]
1. Create a folder with capitalized characters (absolute path to the project has at least 1 capitalized character).
2. Clone the project into the folder.
3. Run tox.
4. Run 'tox -e docs'

Actual result:
It returns an error of docs generation.

Expected result:
The docs are generated

**Comment by kapilt** [comment]
it would help if you could state the actual error you're seeing. doc gen is working fine in ci.

**Comment by evhenyshaliov** [comment]
> it would help if you could state the actual error you're seeing. doc gen is working fine in ci.
> 
> if your referencing your last pull request failure to build docs, its because you have errors in your docs.

Here is a log of the error. The branch is master. It's reproduced only if path contains uppercase characters. For example PycharmProjects has them.

cp README.md docs/source/overview.md
cp tools/c7n_org/README.md docs/source/tools/c7n-org.md
cp tools/c7n_policystream/README.md docs/source/tools/c7n-policystream.md
cp tools/c7n_mailer/README.md docs/source/tools/c7n-mailer.md
cp tools/c7n_trailcreator/readme.md docs/source/tools/c7n-trailcreator.md
mkdir -p docs/source/aws/resources
c7n-sphinxext --provider aws --output-dir docs/source/aws/resources --group-by=resource_type.service
Traceback (most recent call last):
  File "/home/yauhen/PycharmProjects/cloud-custodian/tools/c7n_sphinxext/c7n_sphinxext/docgen.py", line 157, in main
    _main(provider, output_dir, group_by)
  File "/home/yauhen/PycharmProjects/cloud-custodian/tools/c7n_sphinxext/c7n_sphinxext/docgen.py", line 194, in _main
    with open(rpath, 'w') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/yauhen/pycharmprojects/cloud-custodian/docs/source/aws/resources/iam-group.rst'
> /home/yauhen/PycharmProjects/cloud-custodian/tools/c7n_sphinxext/c7n_sphinxext/docgen.py(194)_main()
-> with open(rpath, 'w') as fh:
(Pdb)
