### ISSUE TITLE
[SecurityHub] mode type: hub-finding CWE events not triggering Lambda

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#4497]
While testing the mode type: hubfinding, noticed that while events triggered via "aws guardduty create-sample-findings" were resulting in findings in both GuardDuty and SecurityHub, the Lambda deployed by my policy did not get invoked.  Suspect it's due to the lack of " - Imported" prepended to the detail-type value, which the documentation at https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cloudwatch-events.html#securityhub-cwe-all-findings indicates is part of the expected value.

Actual CWE Rule setup:
```
{
  "source": [
    "aws.securityhub"
  ],
  "detail-type": [
    "Security Hub Findings"
  ]
}
```

Documented expected 
```
{
  "source": [
    "aws.securityhub"
  ],
  "detail-type": [
    "Security Hub Findings - Imported"
  ]
}
```

**Comment by kapilt** [comment]
This seems fair but let’s be clear, security hub broke their api compatibility is the underlying cause.
