### ISSUE TITLE
azure - container host - ACI deployment tooling

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4504]
Scripts/templates/docs/whatever is required to easily use in ACI

**Comment by yayitserica** [comment]
### ACCEPTANCE CRITERIA

1. Research what it takes to make Custodian on ACI work
2. Research any blockers to make Custodian on ACI work
3. Create instructions/docs/scripts on implementation next steps 

FYI @stefangordon
