### ISSUE TITLE
CI - codecov blocking all PRs

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4515]
Seems we are at 100% non-reporting codecov for ~3 days or so? 

Lets use this thread for updates.

I believe all builds in the last 3 days are showing the "missing base report" (and sure enough all the parent commits are missing, even if they were previously there.  e.g. go to the preceding PR and its codecov is gone now)

https://codecov.io/gh/cloud-custodian/cloud-custodian/pulls

**Comment by stefangordon** [comment]
Three options I am aware of:

- Switch to doing simple coverage percentage thresholds in devops pipeline.  I have this working already in a fork.  
- Disable codecov gate entirely
- Switch to Coveralls (The pipeline changes are easy, but I need the repo token and am having trouble accessing it, I suspect @kapilt will have it since he experimented with Coveralls last December and created the repo association)

**Comment by stefangordon** [comment]
This was the last commit/PR https://github.com/cloud-custodian/cloud-custodian/pull/4171

**Comment by stefangordon** [comment]
I'm experimenting with republishing codecov results for the "missing base report" commits.

**Comment by kapilt** [comment]
i'm mostly mia this week, i can disable the gate, and keep it as advisory. we used to use coveralls but had reliability issues with it, and codecov offered a superior ux experience.

**Comment by stefangordon** [comment]
heh, not blocking as we can update the pipeline to fix this, but wanted to note that now coverage publishing to codecov is just outright failing with HTTP 503

/dev/fd/63: line 2: `<head><title>503 Service Temporarily Unavailable</title></head>

**Comment by stefangordon** [comment]
This morning it looks like all builds were failing due to the publish failure now.  Investigating.

**Comment by stefangordon** [comment]
Looks like they fixed it an hour ago.

**Comment by stefangordon** [comment]
So we have had the gate disabled but still I can see that codecov is only successful about half the time.  

In fact it is still failing some of my builds because the builds timeout trying to upload results:

![image](https://user-images.githubusercontent.com/4087345/64541600-01b5bd00-d2d7-11e9-9c7d-9cd3dd897562.png)

https://dev.azure.com/cloud-custodian/cloud-custodian/_build/results?buildId=4045

I am unconvinced their service is this bad, so we should take another pass over how we are doing the uploading and compare with their docs/forums to see if we have done something incorrectly.

**Comment by stefangordon** [comment]
Best I can tell this is still a problem?

**Comment by kapilt** [comment]
thanks for the fix re fetch depth, closing this, fwiw codecov has generally been quite reliable over the last year.
