### ISSUE TITLE
azure - use a prefix in front of GUID for naming the NSG inbound security rule

### ISSUE THREAD

**Issue by erwelch** [cloud-custodian/cloud-custodian#4519]
Allow the user to pass a prefix to generate the new network security rule in the NSG actions. Enables users to adhere to naming conventions.

**Current**
------------
The logic in the 'NetworkSecurityGroupPortsAction' base class uses a hard coded prefix with a GUID post-fix to generate the new rule name.

**Expected**
-------------
Can take in a prefix to generate the new rule name.

**Comment by erwelch** [comment]
Allow the user to pass a prefix to generate the new network security rule in the NSG actions. Enables users to adhere to naming conventions. 

Current: The logic in the 'NetworkSecurityGroupPortsAction' base class uses a GUID to generate the new rule name.

Expected: Can take in a prefix to generate the new rule name.

**Comment by stefangordon** [comment]
This was also raised by a user on Gitter.
