### ISSUE TITLE
c7n - webhook action should support proxy

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4525]
Doesn't seem to pickup default proxies, and doesn't allow you to configure one.

**Comment by stefangordon** [comment]
We should make this work the same way as the Azure SDK
https://github.com/Azure/azure-sdk-for-python/blob/4a03da00385e3c86cce43677db6abc9e21319d64/sdk/core/azure-core/docs/configuration.md#configuring-proxy

We can go see how they implemented it and then do something similar in the URLLIB3 ProxyManager 

```
from urllib3 import ProxyManager, make_headers

default_headers = make_headers(proxy_basic_auth='myusername:mypassword')
http = ProxyManager("https://myproxy.com:8080/", headers=default_headers)

# Now you can use `http` as you would a normal PoolManager
r = http.request('GET', 'https://stackoverflow.com/')
```

**Comment by logachev** [comment]
Fixed: https://github.com/cloud-custodian/cloud-custodian/pull/4726
