### ISSUE TITLE
azure - add HDInsight resource

### ISSUE THREAD

**Issue by erwelch** [cloud-custodian/cloud-custodian#4530]

**Comment by stefangordon** [comment]
Duplicate of #3311 ?

**Comment by yayitserica** [comment]
### ACCEPTANCE CRITERIA

1. Follow steps to add a new resource [see [here]](https://cloudcustodian.io/docs/azure/advanced/contribute.html#adding-new-azure-resources)

FYI @erwelch

**Comment by yayitserica** [comment]
Duplicate of #3311 [Azure Milestone B]

@stefangordon can you please add this work item [4350] to Azure Milestone B, thanks!
