### ISSUE TITLE
c7n-org: Tag filter doesn't work for AWS resources with ListTags API (e.g., Lambda, DynamoDB)

### ISSUE THREAD

**Issue by ericdahl** [cloud-custodian/cloud-custodian#4545]
When running this policy:

```yml
policies:
  - name: lambda_missing_name_tag
    resource: lambda
    filters:
        - "tag:Name": absent
```

It reports different results when using c7n compared to c7n-org. 

For example, c7n correctly reports 110 lambdas without this tag in this account: 
```
# custodian run lambda.yml -s .
2019-08-08 00:51:06,968: custodian.policy:INFO policy:lambda_missing_name_tag resource:lambda region:us-east-1 count:110 time:5.15
```

versus c7n-org incorrectly reporting 248 lambdas. This is the total number of Lambdas, with this tag or without:
```
# c7n-org run --config c7n.yml -u lambda.yml  -s .
2019-08-08 00:53:11,522: c7n_org:INFO Ran account:myaccountname region:us-east-1 policy:lambda_missing_name_tag matched:248 time:0.49
2019-08-08 00:53:11,545: c7n_org:INFO Policy resource counts Counter({'lambda_missing_name_tag': 248})
```

I've observed the same behavior with DynamoDB tables, but not EC2 instances. This suggests it may be related to APIs that have dedicated "ListTags" APIs, rather than those that include tags in the Describe API calls.

this is using versions
```
c7n             0.8.44.3 
c7n-org         0.5.3    
```

**Comment by kapilt** [comment]
this Is fixed in trunk and will be in the next release, lambda execution mode policies in c7n-org were returning bad numbers.

**Comment by kapilt** [comment]
re fixed on master it was regard to c7n-org, it wasn't reporting useful numbers when executing lambda policies. the actual policy effect was the same so your reference to dynamodb tables sounds unrelated, do you have some details wrt to that?

**Comment by ericdahl** [comment]
Hi Kapil

I've created a self-contained test case repo showing the issue here: https://github.com/ericdahl/test-c7n-org-dynamo-tag

I hope it's self-contained and easy to follow. Maybe I'm doing something wrong with c7n-org but this type of thing works with other resources like EC2 instances

**Comment by ericdahl** [comment]
it looks like this was my user-error. We had specified a name rather than an ID for the `account_id` c7n-org field. It seems like in certain causes c7n-org tries to concatenate fields together to create ARNs rather than using the ARN from AWS. This resulted in an invalid ARN which meant a dict lookup didn't work as epxcted - https://github.com/cloud-custodian/cloud-custodian/blob/9003bbbeac451885d46f01ae4f9dec780af502ae/c7n/query.py#L543
