### ISSUE TITLE
azure - sql metrics example does not work

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4548]
SQL/DTU example throws an error
https://cloudcustodian.io/docs/azure/examples/metrics-general-compute.html

If I recall it is missing one of the optional fields that sets the dimension.

**Comment by jomalsan** [comment]
I will fix this

**Comment by jomalsan** [comment]
Successfully reproduced the error trying the example:
`azure.mgmt.monitor.v2018_01_01.models._models_py3.ErrorResponseException: Metric: dtu_consumption_percent does not accept zero dimension case`
