### ISSUE TITLE
CLA Signature Required for Cloud Custodian Contributions

### ISSUE THREAD

**Issue by bclements** [cloud-custodian/cloud-custodian#4551]
Hey folks,

I'm one of the Cloud Custodian organization owners at Capital One. As part of the contribution process to Cloud Custodian, we need each of you to go out and sign the CLA: [CLA](https://docs.google.com/forms/d/19LpBBjykHPox18vrZvBbZUcK6gQTj7qv1O5hCduAZFU/viewform?edit_requested=true). We'd appreciate if you could do this as soon as possible. Please reply once you have signed.

We are currently missing CLA's from the following contributors: 
@vmuraven
@clhefton
@ChrisRx
@grantwwu
@taohungyang
@CallumHibbert
@eschultz17
@X-Guardian
@mikael-lindstrom
@houseofback
@tomarv2
@edonkor1

**Comment by taohungyang** [comment]
**Signed**
Thanks!

**Comment by kapilt** [comment]
This should have been handled by sending an email. Half that list is folks from Capitalone at the time of contribution.

**Comment by kapilt** [comment]
I suggest we close this pending an email discussion, while I appreciate your role, contacting the project maintainers would have more appropriate.
