### ISSUE TITLE
azure - add a check for Function periodic syntax

### ISSUE THREAD

**Issue by aluong** [cloud-custodian/cloud-custodian#4552]
## Actual
If you add a poorly formatted or cron syntax, you will get a host runtime failure in the Azure Function. This can be fairly difficult to debug at face value.

Ex: '* * * * *' (missing one time interval)

## Expected
We should do validation of the syntax to ensure it will be compatible with the Azure Function. We can throw a validation exception here.

**Comment by stefangordon** [comment]
Can do a regex in the json schema for both azure function and container host mode (note one is a 6 part and one is a 5 part).

**Comment by yayitserica** [comment]
### ACCEPTANCE CRITERIA

1. When validating a policy we are able to check if a schedule schema is correct.

FYI @aluong
