### ISSUE TITLE
Azure -  Custodian Report - Running on multiple subscriptions

### ISSUE THREAD

**Issue by justinhauer** [cloud-custodian/cloud-custodian#4555]
Can `custodian report` run across multiple subscriptions? From my initial investigation and looking through the documents it appears it only works on the subscription set in our azure-cli session, and appears to ignore if you're using management groups, or service principal authentication.

**Comment by kapilt** [comment]
c7n-org should do the multi account / multi subscription use case

**Comment by justinhauer** [comment]
Got it! thanks. I'm closing the issue.
