### ISSUE TITLE
As a user, I want an easier way to setup cloud custodian's python environment

### ISSUE THREAD

**Issue by JJediny** [cloud-custodian/cloud-custodian#4557]
**Feature Request:**
Use [pipenv](https://docs.pipenv.org/en/latest/) over raw python3 and virtualenv. FWIW, we've switched over alot of our python projects to using it, and found it saves others alot of headache worrying about whether they've activated their virtualenv on python projects. Happy to submit a PR for a `pipfile`, just wanted to get this on the project's radar.

**Comment by kapilt** [comment]
Pipenv is even more niche, most of users no little about python packaging ecosystem, and frankly they shouldn’t have to. we’re heading down the direction of docker images with a golang frontend to avoid install/upgrade headaches.

**Comment by JJediny** [comment]
thanks much for the explanation; just wanted to document
