### ISSUE TITLE
Feature: allow RDS/EBS snapshots to be removed from being public

### ISSUE THREAD

**Issue by vtomardb** [cloud-custodian/cloud-custodian#4566]
There is option for RDS - `set-public-access`. I would request if we can have something similar for `ebs-snapshots` and `rds-snapshots`. 

Right now we only have `copy` and `delete` option.

**Comment by kapilt** [comment]
generally read/writes policies have gone with deletes around this filter, so it would be useful to understand the scenario where the set access would be preferred.

**Comment by vtomardb** [comment]
this is what i am issue with users are making snapshots public, i dont want to delete them. i just want to remove them from being public and let the snapshot exist.

![Screen Shot 2019-08-09 at 6 20 53 PM](https://user-images.githubusercontent.com/51141202/62815788-73c99500-bad2-11e9-9aeb-429f952b25a5.png)

**Comment by kapilt** [comment]
sure, the question is most of these snapshot scenarios are backups (ie there's a cardinality to the set > 1), so what's the scenario for not just deleting one vs modifying it to remove sharing.

**Comment by vtomardb** [comment]
we can manage without it, or I was thinking taking a copy in a new region and then deleting it..  just a nice to have.. I am sure there are more imp. things we will need than this..

**Comment by nitrocode** [comment]
I was looking for this too. If the snapshot is deleted then we can't use it. If the snapshot is modified to be private, we can secure the snapshot and use it if needed.

**Comment by ajkerrigan** [comment]
The [set-permissions action](https://cloudcustodian.io/docs/aws/resources/ebs-snapshot.html#set-permissions) should address this. It's available for both EBS and RDS snapshots.

To be focused on only detecting/removing public permissions, you can use the `cross-account` filter with `everyone_only: true` and then the `set-permissions` action with `remove: matched`.
