### ISSUE TITLE
azure - investigate cost management exports

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4575]
Customers requests it be possible to trigger an export via a Custodian action
https://docs.microsoft.com/en-us/rest/api/cost-management/exports/createorupdate

Please investigate this part of Cost Management and see if fits into Custodian.  Is there an actual resource type for it (maybe the export schedules?)

Can the action trigger on demand or can we just make export schedules? 

If there is a logical fit with custodian please file issues for new resource/action.

**Comment by yayitserica** [comment]
### ACCEPTANCE CRITERIA

1. Verification of what cost mgmt exports can do and if Custodian can indeed export this.
2. Identify if actions can be triggered or scheduled.
3. Identify any blockers, next steps for work related to this in new Github Issue work items.

FYI @stefangordon
