### ISSUE TITLE
Function Name for AWS S3 filters

### ISSUE THREAD

**Issue by martinklie** [cloud-custodian/cloud-custodian#4608]
In working with the below we are trying to filter for an S3 bucket that accepts http and update the policy.  Is there a list of S3 filter types we can review for options.  Thanks in advance

policies:
  - name: s3-https
    resource: s3
    description: s3 buckets without encryption required
    filters:
      - type: no-encryption-statement
    actions:
      - type: set-statements
        statements:
          - Sid: "DenyHttpAny"
            Effect: "Deny"
            Action: "s3:*"
            Principal: "*"
            Resource: "arn:aws:s3:::{bucket_name}/*"
            Condition:
              Bool:
                "aws:SecureTransport": false

**Comment by kapilt** [comment]
the docs have references on available resources, filters, and actions
https://cloudcustodian.io/docs/aws/resources/s3.html

this help is also builtin into the command line, ie.
`custodian schema aws.s3.filters`

`custodian schema aws.s3.filters.is-log-target`
