### ISSUE TITLE
Question: AWS cross account execution in cloud trail mode 

### ISSUE THREAD

**Issue by gklontza** [cloud-custodian/cloud-custodian#4636]
Hi

I'm trying to set up cloud custodian in a tools account and execute policies in multiple accounts and regions. The idea is to set up an ECS cluster, either Fargate or EC2 in the tools account and execute lambdas in real time in other accounts (dev, staging, etc)

The only mode supported for this is periodic. Are there any plans to support cloud trail mode? 
We need real time remediation and with multiple accounts and regions, it could be quite difficult to maintain a per account setup.

Any suggestions?

**Comment by kapilt** [comment]
both setups are supported for cloud trail mode (centralized and per account), their both fairly straightforward to setup, ie just executing the cli per account handles the per account setup and allows for fine grained mapping of account policies. for centralized setups, you have to setup out of band event bus forwarding on cloud watch events, and then set `member-role` in the policy mode to an Arn string like `arn:aws:iam::{account_id}:role/custodian` which will be runtime substituted from the account generating the event and role assumed by the centralized lambda. fwiw this is covered in a few other issues. note there are tradeoffs on centralized when thinking about blast radius, policies that only execute for particular accounts, metrics/tracing, etc, and you still have to have provision per region.
