### ISSUE TITLE
docs - azure event authentication is confusing to new users

### ISSUE THREAD

**Issue by wesyao** [cloud-custodian/cloud-custodian#4640]
New users have tried to use event azure cli permissions for the azure function to run its policies. It also talks about how environment variables for an rbac enabled service principal are optional.

[Azure Event Permissions](https://cloudcustodian.io/docs/azure/configuration/functionshosting.html#advanced-authentication-options)

**Comment by yayitserica** [comment]
### ACCEPTANCE CRITERIA

1. Documentation clearly states that a service principal needs to be set in environment variables and that it is NOT optional [yellow to be fixed]
![image](https://user-images.githubusercontent.com/15487798/63533260-419c3800-c4c1-11e9-8918-8cf1db72c281.png)

FYI @wsf11 @wesyao
