### ISSUE TITLE
azure - doc- container host 

### ISSUE THREAD

**Issue by jomalsan** [cloud-custodian/cloud-custodian#4651]
The documentation for [Azure Container Hosting](https://cloudcustodian.io/docs/azure/configuration/containerhosting.html) does not mention the prerequisites and steps needed to be able to run the deployment step successfully. I had to do the following before deploying:

- Need an azure storage account of type General Purpose v2 (I tried Blob Storage and it failed)
- Need a cluster that is attached to Kubectl (Helm deploys to whichever cluster that you are currently attached to, so users should be told this. I was confused as to whether it would create a new cluster or attach to my current one)
- Need to have helm and tiller installed
- For tiller I had to [add a RBAC policy for tiller](https://helm.sh/docs/rbac/#role-based-access-control) to create resources 
- I created an Azure Storage Queue before running the script as I was trying to debug, but don't know if that is a needed manual step or not

**Acceptance Criteria**
1. A new user approaching the system should be able to walk through the document and successfully deploy a container instance of custodian

**Comment by axis7818** [comment]
> I created an Azure Storage Queue before running the script as I was trying to debug, but don't know if that is a needed manual step or not

The Container Host will create this queue if it does not exist, so it shouldn't be necessary.

Additionally, the service principal (or managed identity in the case of ACI) will need the following roles:

* Storage Blob Data Contributor (On the policy container's storage account)
* Storage Queue Message Processor (On the queue's storage account)
* Reader (On the storage account) 
* Whatever roles are needed to run the policies

To cover the last 2 bullets, I have always tested with just the Contributor role at the subscription level, but that could be more granular.

**Comment by justinhauer** [comment]
is this running as a deployment or a statefulset that is periodically checking blob storage? I was doing this functionality in the past using a cronjob but abandoned it for the function implementation as I thought it'd have more support from the project. Is the plan for Kube support for azure custodian to have a user experience that's on par with functions?

**Comment by axis7818** [comment]
This runs as single pod deployments (each targeting a subscription) that periodically check blob storage for policies to run. StatefulSets were considered, but to target a different sub per pod, each pod needed its own spec with unique environment variables. CronJobs would work for scheduled execution, but Deployments with this container host execution mode allow for a single pod to run a lot of policies in either periodic or event based modes.

The k8s deployment is pretty new, and we are still exploring it, but my hope is for the user experience to be better for managing a larger number of policies and azure subscriptions.

**Comment by stefangordon** [comment]
Re: plan for support - 

@justinhauer we do plan to support both Functions and this Container Host (docker container) model.  The container host model is 1 container (pod in AKS) per subscription and supports the same event based and scheduled executions.  It monitors the storage container for policy changes and automatically loads them every few minutes. 

You can run in ACI, AKS or even on-premise, anywhere you can run the official docker container with a custom entry point. 

If you want help setting it up at some point we could setup some time to try it out with you.  Documentation should start to be refined over the coming weeks.

**Comment by justinhauer** [comment]
I'll eventually take a crack at it but with the amount of time I have I need to be mindful of re-engineering the same functionality I currently have. ^ This is great though!
