### ISSUE TITLE
azure - event subscription - can only handle 5 events

### ISSUE THREAD

**Issue by jomalsan** [cloud-custodian/cloud-custodian#4669]
Only allowed to specify 5 filters on an Azure Event Grid Subscription. Bug found in the Functions hosting, but this is applicable to Container Hosting where all of the registered event-based policies register with the same event grid subscription.

Message recieved when executing the following policy:
```
2019-08-23 18:45:14,059: custodian.azure.AzureFunctionMode:ERROR Event Subscription creation failed with error: Azure Error: InvalidRequest
Message: The maximum number of values allowed on an advanced filter is 5.
```

Policy for reproducing the error:
```
policies:
  - name: azure-auto-tag-creator-date
    mode:
      type: azure-event-grid
      events:
        - AppServicePlanWrite
        - CognitiveServiceWrite
        - CosmosDbWrite
        - DataFactoryWrite
        - DataLakeWrite
        - DiskWrite
        - KeyVaultWrite
        - ResourceGroupWrite
        - StorageWrite
        - VmWrite
    resource: azure.armresource
    description: |
      Tag all new VMs and StorageAccounts with the tags 'CreatorEmail' and 'CreatedDate'
      Note- 'resource-type' filter is not required because policy is not triggered by other resources.
    actions:
      - type: auto-tag-user
        tag: CreatorEmail
      - type: auto-tag-date
        tag: CreatedDate
        format: "%m-%d-%Y"
```
@stefangordon

**Comment by stefangordon** [comment]
For Azure Functions hosting we can update the JSON schema and documentation to catch this at validation.   For container host we'll need to test removing the advanced filter entirely as we do secondary filtering anyway.

**Comment by jomalsan** [comment]
I have a fix for this on a branch in my fork, however it is going to have a bunch of merge conflicts with PR #4695. Will wait for that PR to get merged, resolve the merge conflicts and then create a PR for the first part of this issue. I will create a new issue now
