### ISSUE TITLE
azure - firewall-rules filter ignores 'default action'

### ISSUE THREAD

**Issue by logachev** [cloud-custodian/cloud-custodian#4729]
We need to update `firewall-rules` filter to understand the meaning of `default action` property if available.

E.g. if default action is `Allow` (Firewall turned off), it should be triggered if you request `only` ip rules (because some IPs not from the list are allowed)

**Comment by stefangordon** [comment]
Needs design/discussion

**Comment by logachev** [comment]
It was fixed with this PR: https://github.com/cloud-custodian/cloud-custodian/pull/4756
