### ISSUE TITLE
CI - Docker Tagging Proposal

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4773]
# Proposed Docker Tagging
With the addition of three new cloud plugins to the repository PR velocity is very high.  To utilize these new clouds customers need access to new images much **more frequently** than manually versioned releases, but with higher stability than master branch.

I'm proposing an achievable first step here which I believe sets us up to keep raising the quality bar on nightly releases.

Tag | Description
-- | --
latest | Pointer to lastest **versioned** release
x.x.x | Versioned releases based on github releases
preview | Builds of master (today's "latest")
nightly | Nightly releases *after* successful E2E test suites
091219 | Retain nightly releases with date tags *

> *we could substitute dates with a semver approach with patch level increases for each nightly if preferred, but I believe it implies some incorrect things to the user.

We have Azure live tests coming online now, and if we configure the pipeline this way it becomes easy to drop in E2E test scripts of various types to do additional live validation prior to releasing a nightly.  For example, we will be adding a live serverless c7n-mailer e2e test run shortly.

The purpose of `latest` is changing to the more common usage, which users expect to be the latest stable/tested build.  

# Implementation
We'll setup the docker builds as part of the CI pipeline such that they gate on all nightly validation tasks.  This will give us a place to add additional validation steps for all clouds, which will all be gates before anything other than a `preview` image is released.

We can implement `nightly` and `preview` first, without changing the way the `latest` tag works, and sign-off on it all before making that breaking change to the existing tag.

**Comment by kapilt** [comment]
we discussed this live yesterday, i think the proposal sounds good, we need to work out details on if docker hub building supports current date strings. we also possibly need to figure out a way to cull old images, and to communicate out the behavior change on latest to the broader community.

**Comment by kapilt** [comment]
also its worth noting that currently we have per commit images tagged with the git sha for using non current/latest images which in live discussions was identified as a pain point (not being able to deploy previous revisions), so just wanted to note it is possible today.

**Comment by kapilt** [comment]
i think we should go ahead with the :lastest  to point to last release, and then switch out current latest to :master or :trunk.. preview is a bit too ambiguous on naming there, we should stick to dev nomenclature rather than release candidate naming for stuff without qa.

**Comment by stefangordon** [comment]
Yeah I prefer `master` to `preview` also.

**Comment by kapilt** [comment]
this is not implemented the  recap of image matrix is
```
|name|label|frequency|mutability|testing|
|----|-----|---------|----------|-------|
|c7n |latest|release|mutable|light-functional|
|c7n |0.9.1|release|immutable|light-functional|
|c7n |nightly|daily|mutable|functional|
|c7n |2020-04-01|daily|immutable|functional|
|c7n |dev|per-commit|mutable|light-functional|
|c7n |distroless-dev|per-commit|mutable|light-functional|
|c7n |distroless-latest|release|mutable|functional|
|c7n |distroless-2020-04-01|daily|immutable|functional|
|c7n |distroless-0.9.1|release|immutable|light-functional|
```
