### ISSUE TITLE
Filter IAM Users with Tag

### ISSUE THREAD

**Issue by snowsky** [cloud-custodian/cloud-custodian#4844]
I know we can filter user names for IAM users. Is there a way to filter IAM users with tag, for example:

        {
            "tag:Tag": "Value"
        }

Or

        {
              "type": "value",
              "key": "tag:Tag",
              "value": "Value"
        }

**Comment by kapilt** [comment]
yes both those examples work

**Comment by snowsky** [comment]
Amazing. if you got some time, could you please shed some lights on where the codes are for this tag filters?

**Comment by kapilt** [comment]
c7n/filters/core.py handles key=value tag filtering.
