### ISSUE TITLE
mailer- custom templates rendering issue with s3.

### ISSUE THREAD

**Issue by shitulg** [cloud-custodian/cloud-custodian#4851]
Hi Team ,

I created a policy that deletes all the s3 buckets which are not properly tagged.
the policy is working fine but , when I try to notify the same using custodian mailer , the name of the bucket is not getting populated in the email.

Below is the configuration for the template I used :

```html
        {% elif policy['resource'] == "s3" %}
            {% if resources[0]['GlobalPermissions'] is defined %}
                {% set columnNames = ['Name','GlobalPermissions'] %}
            {% else %}
                {% set columnNames = ['Name','Project','Component','Environment','OwnerEmail'] %}
            {% endif %}
            {{ createTable(columnNames, resources, '80') }}
```
but its failing to populate the name of the bucket.

I even tried removing the if blocks but still the same.

Can you please help in checking if there is something wrong in this.

Thanks & Regards.

**Comment by shitulg** [comment]
Kindly take a look Its blocking my policy.

**Comment by kapilt** [comment]
try just rendering the {{resources}} to see what the values are that you can use, this isn't something anyone can help you with it, as its very specific to your mailer jinja templates which look heavily customized from anything we ship with custodian. worth looking at the jinja docs.

**Comment by shitulg** [comment]
Hi Kapil ,
Thanks so much. I worked on my template file and it needed some tweaking here and there after which it worked fine.

Also your suggestion to go through the Jinja docs worked for me.

Thanks for your help always.

Regards
