### ISSUE TITLE
AWS - Support OneZone_IA S3 Storage Class

### ISSUE THREAD

**Issue by justinhauer** [cloud-custodian/cloud-custodian#4853]
How hard would it be to support Onezone_ia as an additional storage class for s3 lifecycle policies? For life-cycling certain logs I have, I don't have a need to have this be available in multiple AZ's.

**Comment by kapilt** [comment]
afaict its already supported by custodian, we don't hard code the lifecycle class vocabularies, so if its available you can use it with `configure-lifecycle` action on s3 buckets.
