### ISSUE TITLE
custodian run --region all generates session token error

### ISSUE THREAD

**Issue by charles545587** [cloud-custodian/cloud-custodian#4863]
As a user deplloying to multiple regions using the --region all flag generated the following error

`botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the ListFunctions operation: The security token included in the request is invalid `

To isolate the cause, the ec2.describe_regions() api call was used to return a list of regions.  These were then added using multiple --region flags. This resulted in a sucessful deployment.  

The describe_regions api call does not return new regions which require opt-in.  

A subsequent test to add the Bahrain region me-south-1 was then added, without opt-in.

This sucessfully returned the error above indicating that the generated list of regions includes regions which have not had opt-in.

The work around is to list regions individually rather than the --region all flag.  

The deployment does not fail gracefully by skipping the region and moving on. Suggest that describe_regions is used to generate the list as EC2 is a service which will be deployed in all new regions as they are added.

**Comment by kapilt** [comment]
yeah we need to filter region all with an api call to describe regions, we do that now for c7n-org but need to back port it to c7n as well, this issue exists with both the Hong Kong and Bahrain regions as part of a new region opt-in behavior. Generally multi-region multi-account execution is better via c7n-org as it offers parallelism while the main custodian cli will execute them sequentially.

**Comment by kapilt** [comment]
previous report #4290
