### ISSUE TITLE
c7n_mailer, AWS not installing Lambda, no logs, no errors

### ISSUE THREAD

**Issue by terpmeister** [cloud-custodian/cloud-custodian#4881]
I have tried to setup/install the c7n_mailer lambda on our AWS account according to the docs.  I have tried it from my Mac and from Docker Images (in a Jenkins pipeline) to no avail. The kicker is I am not getting any error, or output. Is there anything I can look at to see if I have an issue from my end our something on the AWS account.  This is the command I am running:
```
c7n-mailer --config mailer.yml --update-lambda
```

**Comment by kapilt** [comment]
are you checking in the same account and region that you have credentials? ie. that cli would error out w/ msg if it wasn't successfully provisioning a function.

**Comment by terpmeister** [comment]
Ah, that was what was missing, I was not setting a region in my `config.yml` so it was defaulting us-east-1, and I was looking in us-west-2.  I wonder how hard it would be to setup some basic logging info when running `--update-lambda`. Thanks for the help!
