### ISSUE TITLE
c7n-mailer - azure sendgrid pinned version not compatible with requirements.txt

### ISSUE THREAD

**Issue by aluong** [cloud-custodian/cloud-custodian#4905]
The requirements.txt is installing sendgrid==6.1.0, but we are pinned to sendgrid==6.0.5.

We should look if it's possible to remove the pin in our setup.py

## Error:
`c7n-mailer 0.5.4 has requirement sendgrid==6.0.5, but you'll have sendgrid 6.1.0 which is incompatible.`

**Comment by kapilt** [comment]
doh.. I can take a look at this in tomorrow early if not addressed before then, it looks like I pissed one Datadog dependency in mailer as well that needs updating. surprised that the tox tests didn't complain on the conflict previously.
