### ISSUE TITLE
proposal - terraform functional testing

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#4912]
## Background 

In order to enable consistent and better functional testing across providers, we want to start using terraform to enable provisioning of resources for functional tests. At least for the AWS provider historically functionally testing has been via decorating tests with the functional decorator, *when* the tests also encode the api calls to setup their pre-conditions (infrastructure resources and state). The AWS functional tests are not exercised regularly. The Azure provider currently does this via a set of deployment manager template that are provisioned pre test execution. The Azure provider tests are now being run nightly in a azure DevOps pipeline. Neither gcp nor k8s providers have functional tests atm.

### Goals 

high level goal is to allow for tests to specify their pre-conditions in terraform modules.

specific goals

 - allow tests to specify independent terraform root modules
 - allow tests to specify shared terraform root modules
 - allow tests to layer a shared and independent terraform root modules (network, security groups)
 - allow for concurrent provisioning and execution of independent tests terraform root modules
 - tests should have access to the resources ids / types of the provisioned resources.
 - supports live/functional and replay tests
 - allow for streaming terraform provisioning output (helpful for debugging resources that take a long time to provision).
- terraform test root modules should be able to references root modules provisioned at higher scopes.

### Challenges

pytest is our current testing tool of choice (and effectively the defacto ecosystem testing tool), but we're looking at some mismatches on feature sets to its builtin capabilities, which need to be worked through. 

 - pytest fixtures injection has poor compatibility with unittest.TestCase derived classes
 - pytest doesn't allow arguments to fixtures, fixture specification to a test is based solely on implicit name matching. 
 - pytest has static scopes (function, module, package, session)
 - coordination of fixture creation has to be done on a global basis with barriers when running distributed / multi-process via pytest-xdist.
  

### Example usage

putting out a straw example for iteration

```python

class SecurityGroupNetworkTest(unitest.TestCase):

     # terraform stack specific to this function
     @terraform_aws('tf_sg', scope='function')
     # terraform shared stack
     @terraform_aws('tf_vpc')
     def test_foobar(self, tf_vpc, tf_sg):
            # probably need to qualify with the name of the terraform resource, might be able to 
            # alias sans the common provider prefix to lesson the repetition.
            vpc_ids = tf_vpc.resources['aws_vpc'].values()
            sg_ids = tf_sg.resources['aws_security_group'].values()
```

underneath the hood the terraform_aws is actually generating and caching fixtures, and ideally these
decorators should also support classes for declaring on a whole set of tests. ala

```python

@terraform_aws('tf_sqs', scope='class')
class SQSTest(unittest.TestCase):
     def test_xyz(self, tf_sqs):
           """ gets class scoped resources"""

     def test_abc(self, tf_sqs):
           """ gets class scoped resources"""

     @terraform_aws('tf_sqs_nmo', scope='function')
     def test_nmo(self, tf_sqs_nmo, tf_sqs):
          """gets function scoped resources and class resources"""
  
```

### Concurrent Provisioning

To enable concurrent provisioning of terraform modules, we'll need to impose one restriction on test execution namely that its single host, so removing support for fully distributed modes. In turn this allows us to trade out a need for a remote network server for coordination, and enables us to use 'simple' file locking.. except file locking isn't particularly simple 

http://0pointer.de/blog/projects/locking.html
https://gavv.github.io/articles/file-locks/
https://dmorgan.info/posts/linux-lock-files/

otoh we could also simply defer to sqlite which allows multi-reader / single writer semantics. The other aspect to enabling test execution concurrency, is generally that we want tests that are mutating resources to get their own copy of the resource, which means we'll have a general guidance against hardcoding resource ids (or using unique ones), and instead introduce some randomness via builtin in terraform capabilities to enable that. in many cases resource ids returned for a resource are autogen'd (vpcs/instance ids/etc) thought not in all, so we'll need to return the provisioned resources back to the test via the fixture return value.

Concurrency also introduces some interesting complications for test scheduling and scope, by using distributed locking the intent is that we don't have to do any additional work/modifications to the builtin scheduling and scope and existing parameters to the xdist scheduler work ootb. this does require us to have a known path for coordination, we'll likely need to use the pytest extension mechanism to hook the initialization and cleanup, and that will need some ordering guarantees around teardown for the lock file cleanup post terraform fixtures teardown.

### Terraform init

all of the independent root modules will require terraform init, which will download the requisite providers. to amortize the cost of that across the root modules, we should do a one time init of all of them, and then copy that directory as a working directory for future terraform executions. we may need to have users specify the full  provider set in config else we'll need to do a complete scan of root terraform modules to determine extant providers.

### Fixture Resources

the tests will need to access fixture provisioned resources, to do so the fixture will return a terraform resources instance for each terraform root module fixture which will have available a mapping of terraform resource type names to terraform resource names to provider ids, which will be inferred from the tfstate.json.

### Replay support

For tests executing with replay we'll need to store the fixture resource id mapping and serialize them to disk from a live provisioning run to enable a replay run. On replay we'll pick up the serialized resource ids and return them as the fixture results. We'll need to do this once per scope instantiation (session, module, package, function). Note this will be effectively be an independent mechanism from the existing one as it needs to handled pre test execution, where as the current record/replay mechanism is done within a test execution. Some of the DRY violation could be addressed by refactoring the existing mechanisms to look at fixture decorated attribute on the test instance.

### Root module references

`terraform_remote_state` can be used to introduce a dependency between a scoped root modules on an individual test, note we are not attempting to support same scope inter fixture dependencies as that imposes additional scheduling constraints outside of pytest native capabilities. The higher scoped root module will need to have output variables to enable this consumption.

### Open Questions

 - need to explore fixture compatibility with unittest derived classes

**Comment by kapilt** [comment]
some interesting prior art that might be useful to explore
 -  bridging of Zope.testrunner's layers concepts to pytest, zope layers are effectively class based fixtures https://zopetestrunner.readthedocs.io/en/latest/testrunner-layers-api.html 
 https://bitbucket.org/gocept/gocept.pytestlayer/src/default/
 - an alternative distributed runner https://github.com/ansible/pytest-mp with shared fixture setup/teardown.
 - fixture ordering while respecting scopes https://pypi.org/project/pytest-fixture-order/0.1.2/#files

**Comment by kapilt** [comment]
one further set of goals though probably not for initial usage would be towards enabling a testing cli tool for user policies, with terraform as provisioning tool

**Comment by kapilt** [comment]
continued exploration of pytest and other testing frameworks (nose2, zope.testlayer), and it looks like supporting unittest class bases is going to be problematic for fixture usage as pytest won't perform injection into unit test derived classes. which means trying to bring up a new pytest native/centric common testing infrastructure. our use off addCleanup in the base test infrastructure (to support flight recording) is particularly problematic for pytest, as it needs to be wired through as a parameter to every test. an alternative is trying to customize the pytest item from unittest collection with additional support in the decorator we're using for fixture injection.

**Comment by kapilt** [comment]
i've put up a pr refactoring the common custodian testing infrastructure to work as a pytest fixture in addition to the extant unittest class support, and moved a few tests over to use it, this enables the use of other pytest fixtures natively.

**Comment by logachev** [comment]
> ### Concurrent Provisioning
Not sure I understand an issue here.. My proposal is to shape templates committed to the repo as Terraform Modules and construct actual deployment unit in tests runtime. That way even if we have multiple tests using same module (e.g. AWS EC2, Azure VM) we don't need any sync between deployments. 

> ### Terraform init

Sounds good.. Lets use `~\.custodian\tests\terraform` as a base folder?

Minor: we don't need to copy this folder, Terraform supports 'init from local directory' mode.

**Additional thoughts**

While I like an idea of provisioning resources for a specific scope (before module class, function execution), I'm really concerned about runtime. We will need to cleanup when we exit the scope and this is expensive, at least in Azure. 

For example, empty Resource Group (which is a basic resource required for any test) provisioning takes ~5 seconds and cleanup can take up to 60 seconds. With 2 core VMs used in DevOps pipelines, it will take forever to run entire tests suite (especially function scoped tests).

So, I think we have to think about provision\cleanup being session scoped piece.

**Comment by kapilt** [comment]
@logachev re concurrent provisioning, at the moment your single threading in a distributed system around provisioning and only performing it at test start. thats kinda of the opposite of concurrent deployments, trying to glom all of those together into a single execution for tf to handle concurrency makes debugging and incrementalism harder since a failure is attached to the entire tf stack execution which has everything as opposed to the test's resources. what I'm aiming for here is independents tests to be able to at runtime in different processes provision the terraform stacks they need in parallel at execution.

the concern around a given resource x taking time y is optimizing for the worst case by penalizing the common case. there are many resources that are quick to create.

I think a good place to start the discussion would be making sure we're in alignment on the goals and discussing if not.

**Comment by logachev** [comment]
> - allow tests to specify independent terraform root modules
> - allow tests to specify shared terraform root modules

Agreed. In my implementation it can be done on the class level via `template` and `scope` variables.
I don't see a value of mixing together tests that share infra with tests that require dedicated infra.. So I believe it is ok to group them within a class. 

In my mind there are 2 large groups of tests:

- Filter tests: shared module, because it is read-only set of operations
- Actions tests: individual modules, because tests will update resource state

> - allow tests to layer a shared and independent terraform root modules (network, security groups)

What is the value of this one? Network, Security Groups are essentially free resources (at least in Azure world), so I'd prefer to structure each module to be self-contained.

> - allow for concurrent provisioning and execution of independent tests terraform root modules

Independent execution -- yes.
Independent provisioning -- no for Azure. Unfortunately in Azure a lot of common resources provisioning\cleanup time is really long. As I mentioned Resource Group is not a one off example, it is essentially resource required for each Azure test. If we do individual provisioning or cleanup it will just take forever.

Yes, we can do fire & forget style of cleanup, however I don't want to have any automation that will go & check if some resources are still deployed.

> - tests should have access to the resources ids / types of the provisioned resources.
Please let me know if this is different in AWS world, but in Azure it is enough to have Name of the provisioned resource to build an id. If AWS\GCP require the full id, lets expose it instead of the name.

What is the reason to have a type? Each test is written for a specific resource type already, so feels like some extra information.

> - supports live/functional and replay tests

Unrelated to the Terraform piece.. I think all tests have notion of live\replay now, so doesn't matter how infrastructure is being created.

> - allow for streaming terraform provisioning output (helpful for debugging resources that take a long time to provision).

Agreed. However, not sure if this is really v1 requirement. It can be an incremental improvement for the test framework.

> - terraform test root modules should be able to references root modules provisioned at higher scopes.

Same as one point before.. Not sure why this is hard requirement. I'd prefer to keep modules self-sufficient.

**Comment by kapilt** [comment]
@logachev and I discussed this offline, nutshell, I'd like to see a more python-terraform plugin that we can reuse for custodian usage/specific decorators as we as reuse ootb. the key aspects to me are 
- respecting all levels of pytest scopes.
- given most test failures are against aggregate, I'd like to see separate executions of terraform and individual test failure so we're not debugging the generated amalgamated output of all 2.5k unit tests.
- I'd like to see these work for unit tests and functional, and I'd like to introduce a provisioned resources abstraction over them vs hardcoding resource names.
- the notion of long to provision resources is a bit moot, many resources are fast to provision,
  this is a actually an argument for nested scope provisioning per respecting pytest scopes.

**Comment by kapilt** [comment]
so i've made some progress on this, for non pytest-xdist usage everything seems to work well. fixture factories as decorators for referencing terraform modules, fixture scopes, loaded resources, etc. 

i'm still working through the implications for fixtures at non function scope to adhere to once per run semantics, instead of once per worker when using xdist. i think i have a solution path

**Comment by kapilt** [comment]
re scope issues, some upstream xdist discussion by way of background https://github.com/pytest-dev/pytest-xdist/issues/271

**Comment by kapilt** [comment]
fwiw the underlying framework this is a separate project that i've opensourced here
https://github.com/cloud-custodian/pytest-terraform

**Comment by JohnHillegass** [comment]
I may have to spend some cycles seeing how to put it together. This plugin would really enable some velocity around writing the tests.

**Comment by kapilt** [comment]
this is now live, and documented in the developer docs https://cloudcustodian.io/docs/developer/tests.html#writing-tests-for-cloud-controlled-resources

many thanks to @marcoceppi for getting this over the finish line.
