### ISSUE TITLE
Dump the resources or policy execution details for audit purpose

### ISSUE THREAD

**Issue by jksgit** [cloud-custodian/cloud-custodian#4938]
Hi,

We have implemented some resource cleanup policies across all AWS accounts. What is the best way to dump/keep track of deleted resources in Centralised DB for audit purpose?

**Comment by kapilt** [comment]
see custodian run --help or the docs on how to configure outputs. use -s s3://mybucket/mypath to a versioned s3 bucket with mfa delete for all executions to get an audit log, you can query it with any of the data lake tech or index it as you wish. -m for publishing metrics into CloudWatch metrics. and cloud watch logs. please see the custodian docs (aws topics) as well for config-rule, ssm ops center, or security hub integration if you want to use one of the native aws dashboards.
