### ISSUE TITLE
Multiple Lambda Triggers in mode section

### ISSUE THREAD

**Issue by Kyle-Newton** [cloud-custodian/cloud-custodian#4956]
# Question
Is there a way to specify multiple triggers within the mode section?

Specifically, I have a recheck for tagging compliance running every hour, once remediated it will untag the maid_status. Another check will stop the instance when the maid_status stop@ is gte the current date. If someone comes along and remediates a stopped instance and starts it again, the maid_status key will stay until the next recheck. I'd like instead for the same recheck policy to ALSO trigger on ec2-instance-state running so that the maid_status gets removed ASAP. 

So if I could set type twice, once for periodic, and once for CloudTrail event based, this would work. Otherwise I have to manually go into lambda and add the 2nd trigger.

**Comment by kapilt** [comment]
first. periodic lambdas are generally not intended for high volume use cases, ie. lambda in general is an event mode, for partial state evaluation, doing it with periodic lambdas as opposed to just cron'ing the cli means not being able to take advantage of the cache. each periodic lambda will query the full resource set (ie. in this case aka all ec2 instances), stacking them means a lot of extraneous api volume.. It seems to be an area that folks seem to regularly get themselves into trouble. if you want to untag when tags are correct, set an event policy on tagging or via config-rule mode, or run on the cli with other hourly policies.

wrt to policies and multiples modes, no.. thats just spelling and dry. you can set common policy attributes (tags, filters, actions, or partials thereof), using anchor schemas and refs in the vars section of a file. ie. we try to keep policies focused on a particular use cases or details there off, lambdas policies are effectively sealed and generate metrics on a given event stream. operationally thats signficantly better then trying to evaluate/interpret the logs/metrics, against totally different worlds.

**Comment by Kyle-Newton** [comment]
A bit of trouble following all this as all my CloudCustodian knowledge comes from reading and looking at examples and just playing around with it last week. However I think I get the gist of what you're telling me.

I think below is the "perfect" set-up that I am looking to achieve and the mode/method for each 
 * We want to make sure all instances get 3 tags, Application, Owner and Project. (Lambda check on RunInstance)
 * Non compliant instances should be shut down in 3 days (or 1 day, or whatever given time frame) (Cron CLI Every :00 on a t2.micro?)
 * Someone should get notified that their instances are going to be stopped (look into c7n mailer)
 * Remediation should be noticed and stop flags should get removed prior to being stopped (mode:config-rule)
** Checks for remediation should happen to only the subset of non-compliant instances and may trigger prior to stop checks 
*  Starting a stopped non-compliant instance again should refresh the flag, or possibly make it 1 hour instead of 3 days (Lambda check on instanceState:Running)
