### ISSUE TITLE
ci - consider official custodian account for docker hub

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4962]
We are doing some docker hub pushes from our pipelines so that we can have more complex coordination in relation to our live functional tests.  The credentials used are in a service connection which is configured in the devops project properties (not variables).

All docker hub access is done through traditional user accounts, we should consider creating a custodian build account and updating the service connection to use that.

We'll need to grant that account access to the custodian org. 

![image](https://user-images.githubusercontent.com/4087345/67103072-5a4f6400-f179-11e9-8259-f24ac0259835.png)

**Comment by kapilt** [comment]
we have one, it was previously used by the drone ci server to upload images. i'll look at reconfiguring the pipeline.

**Comment by stefangordon** [comment]
Yeah if you are able to just update the service connection it should "just work" - otherwise make a new service connection and we can send a PR to change the connection name in the pipeline file.

**Comment by kapilt** [comment]
switched azure pipeline service connection to using the c7nbuild bot creds
