### ISSUE TITLE
azure - drop azure.keyvault package for azure.identity and keyvault clients 

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#4969]
the azure.keyvault package is a large set of modules (189) that gets used in custodian primarily for authentication. the azure.keyvault package is deprecated and hasn't been updated for over a year.  the authentication functionality has been split out to azure.identity which should be used instead. the key vault functionality has been delegated to various separate packages (keyvault-secrets, etc). the keyvault package also throws warning in ci due to use of deprecated python syntax, of the 35 odd warnings currently in ci, 34 of them are from c7n_azure, and 29 of those are from the use of the keyvault package.

the keyvault package usage should be removed/updated to use current libraries.

**Comment by logachev** [comment]
Agreed. When we looked at it last time, new KeyVault SDK didn't have a package to manage Certificates available. It is available now.

There is last piece: Azure KeyVault Managed Storage which is not yet available in new SDK. I'll ping PG about it. 
As soon as it is released, we can replace existing `azure.keyvault` package.

**Comment by stefangordon** [comment]
Closing for #6458
