### ISSUE TITLE
Issue getting email using c7n-mailer

### ISSUE THREAD

**Issue by preetichaturvediappdirect** [cloud-custodian/cloud-custodian#4977]
We have configured c7n-mailer by creating mailer.yml and running c7n-mailer --config mailer.yml --update-lambda.
As many times we run "custodian run -c policy.yml -s . " get the output and message got queued up in SQS, but no email is received.
We are also not able to see the logs in CloudWatch Event as getting an error that the default lambda execution policy is not attached.
The attached policy is only - SQSReadOnly policy.
Please find the attached screenshot of the lambda function created by c7n-mailer.
<img width="1294" alt="Screen Shot 2019-10-23 at 4 02 44 PM" src="https://user-images.githubusercontent.com/53596034/67384476-d77e3d00-f5ae-11e9-931f-c93c288c3b62.png">

**Comment by kapilt** [comment]
it sounds like your iam role isn't sufficient to allow the mailer to log, much less send email, you've left out relevant details as well wrt to your delivery transport. its unlikely you'll be able to fully utilize the mailer if you have a policy that restricted (no VPCs attachment for smtp, ses, sns delivery, in addition to lack of logging). I suggest you fix your iam policies first to get some logs before reporting an issue.
