### ISSUE TITLE
There is a dashboard for cloudcustodian ?

### ISSUE THREAD

**Issue by mikrammo** [cloud-custodian/cloud-custodian#4993]
We want to start using cloudcustodian instead of configrules,
Our organization has ~90 aws accounts,
we would like to have a dashboard which would aggregate the results of the custodian policies that are launched on all accounts, something like what AWS config do.
Is there a dashboard for cloudcustodian or does someone do it before?

**Comment by kapilt** [comment]
for aws there are three native dashboards tools that custodian supports, aws config (using mode: config-rule), ssm ops center (via post-item action), security hub (via post-finding action). additionally custodian outputs metrics to cloud watch metrics for native metrics dashboards.  additionally we support splunk ingest (see mailer docs). Custodian operates with the philosophy that the best dashboard is the one your already using, and most enterprises have hundreds of dashboards. its of course possible to build your own just by indexing the object storage, notify stream, or metrics with grafana/elastic if you want to add another dashboard to your org.

**Comment by mikrammo** [comment]
Thanks for the asnwer, I didn't want to use AWS config, because it does not support all of aws services that custodian support.
I'll look to ops center or security hub.
Otherwise, I think it will be nice if custodian has they own dashboard

**Comment by rachgupt** [comment]
@mikrammo I agree with @kapilt that use whatever the organization is using to display the data from cloud custodian. Old thread, but what did you finally use? Splunk looks good and maybe can be used.
