### ISSUE TITLE
Best practices

### ISSUE THREAD

**Issue by ismferd** [cloud-custodian/cloud-custodian#5003]
Hi,

I would like to know which must be the best practices such as:
 - Split policies
 - create more than one Lambda
 - run one lambda per each policy or create a lambda per policy instead.

and so on.

Probably, you have this information in your documentation but I didn't found it

**Comment by kapilt** [comment]
i'm not sure i understand the questions, i'd suggest checking out our chat channel on gitter 
https://gitter.im/cloud-custodian/cloud-custodian
