### ISSUE TITLE
c7n-org ability to send post-finding to central account

### ISSUE THREAD

**Issue by rodrigocmn** [cloud-custodian/cloud-custodian#5007]
I'm looking for a way to run policies in multiple accounts using c7n-org and send findings to Security Hub on a central account. AFAICT from the test I've run, c7n-org tries to create findings (using the post-finding action) in the same account it's running the policies.

I'm wondering if there's a way to specify the account where the post-finding action creates the Security Hub findings.

**Comment by kapilt** [comment]
I vaguely remember trying this out and finding that security hub was actually checking the account id in the resource arn, and wouldn't allow cross account posting. its probably something we'd have to explicitly support.

to understand are you saying you want

```
AccountA Role -> c7n-org -> policy hunt-post-finding -> assume and detect in AccountB Role 
                                                     -> assume and post in AccountC Role
```
where account C role is assumed by Account A role?  or do you just want to post in Account A?

**Comment by rodrigocmn** [comment]
Yes, your understanding is correct. Giving the choice to post in Account C would give more flexibility, but I think that most cases Account A will be the one aggregating all findings.

I have this currently implemented using Security Hub concept of Master and Member accounts. The only issue is that I need SH enabled in all accounts and sharing findings with a "Master" account.  (I'm writing an article explaining this approach)

I think it would be a neater solution to directly post the finding in the master account.

**Comment by kapilt** [comment]
so security hub supports aggregation naturally via master/member relationship, it doesn't support posting findings directly to master regarding member resources. I'd suggest using what the service natively supports. there isn't anything here for custodian to do.
