### ISSUE TITLE
ci - azure provider - mass failure

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#5017]
[update] the **azure sdk broke compatibility again** resulting in several failures. 

all of a sudden the azure provider dropped coverage significantly in ci, there haven't been any changes to account for so this might be a codecov issue. needs review investigating. there's a few azure tests there aren't being executed because they subclass unittest with a separate __init__ method which is not compatible with pytest runner, but thats been long standing.

**Comment by kapilt** [comment]
@logachev @aluong can you guys have a look at this?, we're trying to get a release out the door before 11/6 .. ci is effectively broken. 

I think its really time to reconsider the use of the azure sdks in light of just building our own ontop of msrest, I don't really understand in what world its okay to regularly break all users of an sdk.

**Comment by logachev** [comment]
Looking

**Comment by logachev** [comment]
I merged a mitigation PR, master branch is health.

I think we should consider pinning major versions of our dependencies. It is expected to have breaking changes with major version update, so I don't see any downsides in this.

It adds a tax to manually update them, but I'd expect it to be better experience than broken builds.

My concern with using raw rest api is it is harder to keep track of new REST api versions being released comapring to new major Python packages.

@kapilt thoughts?

**Comment by kapilt** [comment]
I'm tired of mincing words, so let me try to be clear, I have never seen a project in the python ecosystem break compatibility with this regularity. major releases every other week just incrementing major version to 'ok' breaking compatibility, multiplied by a dependency graph ~ 100 packages. this is extremely user hostile, and its insane imo. yes freezing would resolve the random breakage, at the risk of leaving this entire provider bitrotted, vulnerable to security issues, and unable to take advantage of newer service apis, while not diminishing the work to keep up to date. its a false sense of accomplishment. I'd be happy to have a chat with the azure python sdk team, because I don't understand what their rationale behind continuous breakage is except ensuring they don't have users and devs running amok. At this point, and its been a consideration for months... its easier to be done with them if they want to continue this course without destination/end in sight, and just build a stable api, who knows maybe others user might appreciate that as well.

the raw rest api is not significantly harder to use afaics, 95% of the service api is just the statically generated msrest... there's some bits around auth we can cargo cult (copy) in. A single azure package on top of msrest with bundled amalgated service metadata would suffice for the rest. the service teams that publish apis seem to understand that compatibility matters, the azure python sdk team does not. its a single directory walk down a git checkout to keep up to date on service api metadata.

**Comment by kapilt** [comment]
as a couple of additional examples.

let's take one of the packages you just pinned to avoid ci breakage, azure-storage-blob.. okay let's look at it on pypi [0].. okay the home page for that project takes us to the wrong repo which hasn't been updated in months [1].. okay well we know this just broke yesterday so.. let's play a guessing game of finding the right repo, maybe this one is it [2].. okay let's look at the changelog to see how many versions of the api we had to adapt to in the last month to handle all the breaking changes [3]...  2 breaking changes, so client app needed 3 implementations required in a single month for a single packages in sea of a hundred... nuts.

[0] https://pypi.org/project/azure-storage-blob/
[1] https://github.com/Azure/azure-storage-python
[2] https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage
[3] https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-mgmt-storage/HISTORY.rst

....

okay let's take another example.. the c7n azure provider is already bitrotted because it pinned the key vault auth which throws 2/3 of our warnings in ci and hasn't been updated in months [5].. pins are at best transient work arounds, they are tech debt, and need to be cleared out regularly, but building ontop of unstable apis just makes that worse. thats why enterprises generally wait till something is stable before adopting. at least in custodian we've taken a hardline view of compatibility, and frankly thats pretty common in the python ecosystem for things thats people actually use.

[5]
```
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61
  /home/vsts/work/1/s/.tox/py37/lib/python3.7/site-packages/azure/keyvault/key_vault_authentication.py:61: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
    if len(inspect.getargspec(self._user_callback).args) == 3 \
```

another example of bitrot, we already had a separate issue #4926 because the dependency graph for the azure provider wasn't even valid for months, it just logged an error on install and happened to work for some usages.

...

![this-is-fine 0](https://user-images.githubusercontent.com/21650/68063391-e8355e00-fce6-11e9-83c7-5ccb2dfebbbe.jpg)

no actually its not.

**Comment by logachev** [comment]
This is a fair point. I'll use it to start a conversation with the SDK team to get clarity on their roadmap. 
I'm 100% agree with you about the frequency of major releases, it doesn't make a lot of sense to me.

re: keyvault, as we discussed somewhere else, KeyVault has newer SDK. Unfortunately, one feature is not yet supported. We will switch to the new one asap they add it.

I'll share results of my conversation with the SDK team and we can make a decision to switch to the REST api or not. Do you agree, @kapilt?

**Comment by kapilt** [comment]
fwiw, azure apis are broken again on trunk ci, this time for keyvault auth

**Comment by kapilt** [comment]
another pr breakage from azure sdk breaking change 
https://github.com/cloud-custodian/cloud-custodian/issues/5044

**Comment by justinhauer** [comment]
For anyone affected by this, myself included, I'm assuming the remediation for this is to redeploy all my Azure functions once this is resolved?

**Comment by kapilt** [comment]
@justinhauer this is more a developer tracking issue, as the azure sdks instability is causing a lot of churn and pain for any application using it. **However** it *should* not affect end users of cloud custodian. For the last few releases of c7n_azure package, we freeze all dependencies (transitive dependency graph) when publishing to pypi. 

@logachev can you confirm that python package version restrictions are respected when assembling the function app deployment pkg?

**Comment by kapilt** [comment]
and the azure sdks broke compatibility again and ci / pull requests are broken again.

```
_______________ ResourceLockFilter.test_find_by_lock_type_absent _______________
[gw1] linux -- Python 3.7.5 /home/vsts/work/1/s/.tox/py37/bin/python
Traceback (most recent call last):
  File "/home/vsts/work/1/s/tools/c7n_azure/c7n_azure/query.py", line 51, in filter
    op = getattr(getattr(resource_manager.get_client(), enum_op), list_op)
  File "/home/vsts/work/1/s/tools/c7n_azure/c7n_azure/query.py", line 257, in get_client
    "%s.%s" % (self.resource_type.service, self.resource_type.client))
  File "/home/vsts/work/1/s/tools/c7n_azure/c7n_azure/session.py", line 175, in client
    klass = getattr(svc_module, client_name)
AttributeError: module 'azure.mgmt.cosmosdb' has no attribute 'CosmosDB'
```

https://dev.azure.com/cloud-custodian/cloud-custodian/_build/results?buildId=5044&view=logs

**Comment by justinhauer** [comment]
@kapilt **All** azure functions that are getting invoked started failing for me on 11/2 with the following message - I assumed it was related to this (correlation isn't always causation) but perhaps its not. 
```
Result: Failure
Exception: ModuleNotFoundError: No module named 'azure.common'
Stack:   File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/dispatcher.py", line 242, in _handle__function_load_request
    func_request.metadata.entry_point)
  File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/loader.py", line 66, in load_function
    mod = importlib.import_module(fullmodname)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module'
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/site/wwwroot/ownercontact-absent-vm_mySubscriptionIDHere/function.py", line 25, in <module>
    from c7n_azure import handler, entry
  File "/home/site/wwwroot/c7n_azure/handler.py", line 20, in <module>
    from azure.common import AzureHttpError
```
I'm planning on redeploying them - just bringing this to light as it could be affecting others using the Azure implementation...

**Comment by kapilt** [comment]
@justinhauer i'm not seeing that issue today, although i think that was an unrelated breaking change this time from the azure function team wrt to their execution image as opposed to the sdk concern this issue is about.

**Comment by justinhauer** [comment]
@kapilt Regarding my comment from 9 days ago, no longer seeing that specific error - after redeployment on 11/22 seeing the specific errors (the very sparse log errors) I've mentioned to you and @logachev separately on Gitter.

**Comment by justinhauer** [comment]
I redeployed my functions yesterday (deleted old ones as well), and unfortunately #5114 did not fix issues regarding timeouts after 11/2, all functions time out. Besides the CI that is being run, is anyone on the Azure side of the project tried deploying functions and seeing them run successfully? Specifically anything running on a cron schedule? I have talked to @kapilt and @logachev and my policies shouldn't be long running policies, most of the subscriptions they run on do not have a lot of resources in them, and everything seemed to be fine prior to 11/2. Is it possible for me to work more closely with anyone in the coming week? Custodian has been effectively broken for about a month for me.

**Comment by aluong** [comment]
@justinhauer, ping/email me or @logachev offline we can we setup some time to debug.

**Comment by kapilt** [comment]
another break in ci from an azure sdk backwards incompatible change, https://github.com/cloud-custodian/cloud-custodian/pull/5195

**Comment by kapilt** [comment]
it feels like this has been relatively stable, and we should deal with the one offs as is, unless it becomes an issue more regularly again.
