### ISSUE TITLE
network-addr filter 

### ISSUE THREAD

**Issue by pendyalal** [cloud-custodian/cloud-custodian#5069]
In the network-addr filter, we're passing the alloc id as public ip. we should detect the value and pass as the correct param with a fix

**Comment by kapilt** [comment]
thanks for filing, per discussion on gitter here's some more details


 lpendyala_gitlab 13:50
@kapilt even passing the allocationId getting this error event ids not resolved: ['eipalloc-0a7ac776b3uyg5eeb'] error:An error occurred (InvalidParameterValue) when calling the DescribeAddresses operation: Invalid value 'eipalloc-0a7ac776b3uyg5eeb' for PublicIp. Not a valid IPv4 address

**Comment by pendyalal** [comment]
Kapilt, For the above problem, when I modified this line in the code, it fixed.  Can you please take a look at it, test and merge to the master? 
c7n/resource/vpc.py 
   class resource_type(query.TypeInfo):
        service = 'ec2'
        arn_type = 'eip-allocation'
        enum_spec = ('describe_addresses', 'Addresses', None)
        name = 'PublicIp'
        id = 'AllocationId'
        **filter_name = 'AllocationIds'**
        filter_type = 'list'
        config_type = "AWS::EC2::EIP"
Previously filter_name = 'PublicIps'---- changed to filter_name = 'AllocationIds'. I ran test and that worked for me.

**Comment by kapilt** [comment]
yeah we need to auto detect which value we're being given and pass to the correct parameter name.

**Comment by kapilt** [comment]
also fwiw, this resource is also available using `aws.elastic-ip` , pr up to resolve
