### ISSUE TITLE
n AWS accounts n policies

### ISSUE THREAD

**Issue by letgo-infrastructure** [cloud-custodian/cloud-custodian#5074]
Hi,

I would like to deploy cloud-custodian in n accounts, so I achived that using c7n-org, but what about deploying 'n' policies in each account.

I'm deploying it using the docker container.

**Comment by kapilt** [comment]
pass x policy files to c7n-org to run across n accounts. I'm not getting/seeing the actual question? see `c7n-org  run --help` or the readme file for it.

**Comment by kapilt** [comment]
a single file can have a n policies ... also with docker you can just do -e ENV_NAME and it will source the value automatically. If you want to contribute passing multiple files to c7n-org for a single cli invocation, contributions welcome see #3991

**Comment by letgo-infrastructure** [comment]
thanks for help @kapilt
