### ISSUE TITLE
"mugc.py" not cleaning up resources anymore

### ISSUE THREAD

**Issue by kpdhindsa** [cloud-custodian/cloud-custodian#5089]
I am trying to clean up old policies from our AWS accounts, but mugc.py does not seem to work anymore. It worked ok the last time we updated our policies a month back.

Here i the command i'm using:

`c7n-org run-script -s runoutput -c accounts.yml "python3 mugc.py --prefix=custodian- -c custodian.yml"`

There is no error/output logged in "runoutput" either. The script exits normally with messages confirming that it ran on our AWS accounts. But the old lambda's not included in "custodian.yml" are not deleted.

**Comment by kapilt** [comment]
which version of mugc are you using? there was a change merged earlier today #5067 to support additional options, it looked like it maintained compatibility but thats the only recent change to mugc.

**Comment by kpdhindsa** [comment]
I was using the most recent version. I just tried the version before the commit today and it works just fine, looks like the recent commit broke something.

**Comment by bdwyertech** [comment]
@kpdhindsa are you using the default prefix?

**Comment by kapilt** [comment]
@bdwyertech thanks for the quick fix
