### ISSUE TITLE
Didn't find the action item for password policy 

### ISSUE THREAD

**Issue by cvemula1** [cloud-custodian/cloud-custodian#5094]
I'm trying to set the password policy for aws account using cc rule but i'm unable to find any information on how to call update password policy from action item 
Do we have any other way to set password policy ?

Thanks,
Cvem

**Comment by kapilt** [comment]
we have a filter on it, but its notify on action, with the intent that the perms on this are generally lock down, ofc contributions welcome for a new action.

**Comment by JohnHillegass** [comment]
Closed by #5634
