### ISSUE TITLE
aws.key-pair - unused and tag filter

### ISSUE THREAD

**Issue by aakifshaikh** [cloud-custodian/cloud-custodian#5096]
Objective: 1 ) We would like to identity which EC2 key pairs are not attached to the EC2 instance. This allows us to know the unused key-pairs. The respective team can do further investigation to either delete the extra / additional key-pairs or use it by attaching to the EC2 instance.
2) We are not able to write a policy to identify the missing tags for EC2 key-pairs.

**Comment by KVInventoR** [comment]
Hey all
Any idea about this request?
I would like to have something similar to delete all unused keypairs
