### ISSUE TITLE
aws.kinesis - unused filter

### ISSUE THREAD

**Issue by aakifshaikh** [cloud-custodian/cloud-custodian#5105]
I want to write a policy to identify unused kinesis data stream. Currently, it does not have a filter to support this.

**Comment by kapilt** [comment]
use a metrics filter on kinesis, in general thats the most common way to determine usage.

**Comment by aakifshaikh** [comment]
can you please give me an example of written policy.

**Comment by kapilt** [comment]
see the docs for the metrics filter and the docs for kinesis cloud watch metrics.
