### ISSUE TITLE
c7n-org report fails for any azure policy

### ISSUE THREAD

**Issue by buga2050** [cloud-custodian/cloud-custodian#5118]
When I run an Azure policy using custodian run or report, as well as c7n-org run, everything works fine. I'm having trouble running c7n-org report.

```
]$ c7n-org report -c accounts.yml -s output -u stoppedvms.yml
Traceback (most recent call last):
File "/home/srvcustodian/custodian/bin/c7n-org", line 10, in <module>
sys.exit(cli())
File "/home/srvcustodian/custodian/lib/python2.7/site-packages/click/core.py", line 764, in call
return self.main(args, kwargs)
File "/home/srvcustodian/custodian/lib/python2.7/site-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/home/srvcustodian/custodian/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/srvcustodian/custodian/lib/python2.7/site-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, ctx.params)
File "/home/srvcustodian/custodian/lib/python2.7/site-packages/click/core.py", line 555, in invoke
return callback(args, **kwargs)
File "/home/srvcustodian/custodian/lib/python2.7/site-packages/c7n_org/cli.py", line 359, in report
factory.resource_type,
AttributeError: 'NoneType' object has no attribute 'resource_type'
```

Here is the policy

```yaml
policies:

- name: stopped-vm
   resource: azure.vm
   filters:

      - type: instance-view
         key: statuses[].code
         op: not-in
         value_type: swap
         value: "PowerState/running"
```
Even simpler policies fail to run c7n-org report.

**Comment by kapilt** [comment]
what version of custodian and c7n-org?

**Comment by kapilt** [comment]
granted this is on an empty resource set, but it seems to work for me without issue.
```
$ c7n-org report -c subscriptions.yml  -u azure.yml  -s out
Account,Region,Policy,name,location,resourceGroup,properties.hardwareProfile.vmSize
```

**Comment by buga2050** [comment]
custodian 0.8.45.1
How do I check the c7n-org version?

**Comment by kapilt** [comment]
```pip freeze | grep c7n_org```

**Comment by buga2050** [comment]
$ pip freeze | grep c7n_org
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

**Comment by kapilt** [comment]
so after that warning should be an actual value. in the mean time you could try updating your c7n-org version with `pip install -U c7n_org` from within your virtualenv.

**Comment by buga2050** [comment]
That did it, thanks!
