### ISSUE TITLE
mu - set MaximumRetryAttempts

### ISSUE THREAD

**Issue by thisisshi** [cloud-custodian/cloud-custodian#5125]
AWS just added MaximumRetryAttempts as an attribute that can be set when creating event source mappings per previous discussion:

https://github.com/cloud-custodian/cloud-custodian/issues/3454

this way rather than catching errors and losing the cloudwatch metrics with C7N_CATCH_ERR, we can just limit the retry

docs: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lambda.html#Lambda.Client.create_event_source_mapping

should just be a oneliner in c7n.mu

**Comment by thisisshi** [comment]
also note that destiantionconfig was also added, perhaps allow that to be set with

`C7N_ONSUCCESS_DESTINATION`

`C7N_ONFAILURE_DESTINATION`?

**Comment by kapilt** [comment]
so event source mappings aren't actually very common in custodian policies, while mu supports them they aren't exposed for policies as they are data integration pumps as opposed to events sources. The one place we could use them is mailer, but thats currently not on a continuous data feed setup from sqs but a periodic afaicr.

**Comment by thisisshi** [comment]
ah gotcha, I thought the cloudwatch event triggers were set up with CreateEventSourceMapping

**Comment by kapilt** [comment]
The destination stuff looks interesting though Need to see how it interacts with certain style integrations most of those services manage their own delivery retry setups. Event mappings are lambda service pulling data from a source, it’s all perhaps fits on the table re exposing implementation distinctions on event sources.

https://aws.amazon.com/blogs/compute/introducing-aws-lambda-destinations
