### ISSUE TITLE
AWS: SNS Topic - Does not support "has-statement" filter

### ISSUE THREAD

**Issue by aakifshaikh** [cloud-custodian/cloud-custodian#5145]
AWS: SNS Topic - Does not support "has-statement" filter to identify for publicly exposed sns topics. I want to check on Principal”: {“AWS”: “*”}  to determine is sns topic are exposed.
Please advise.

**Comment by kapilt** [comment]
use `cross-account` filter to detect public access, has-statement is a very weak mechanism to check as its a literal / exact match.
