### ISSUE TITLE
config-rule support even when resource not supported by config

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#5154]
Enable Cloud Custodian's support for Config Rules when AWS Config doesn't support the resource type.  Currently Cloud Custodian will produce an error "... error: policy:post-ebs-snapshot-public AWS Config does not support resource-type:ebs-snapshot" as EBS Snapshots are not supported Resource Types.  However, Config rules can still be written on such resources as seen below where the Scope attribute is actually empty in the following AWS Managed Rule.
```
$ aws configservice describe-config-rules --config-rule-names ebs-snapshot-public-restorable-check
{
    "ConfigRules": [
        {
            "ConfigRuleName": "ebs-snapshot-public-restorable-check",
            "ConfigRuleArn": "arn:aws:config:us-east-1:369510138361:config-rule/config-rule-ku1e5n",
            "ConfigRuleId": "config-rule-ku1e5n",
            "Description": "Checks whether Amazon Elastic Block Store (Amazon EBS) snapshots are not publicly restorable. The rule is NON_COMPLIANT if one or more snapshots with RestorableByUserIds field are set to all, that is, Amazon EBS snapshots are public.",
            "Scope": {},
            "Source": {
                "Owner": "AWS",
                "SourceIdentifier": "EBS_SNAPSHOT_PUBLIC_RESTORABLE_CHECK"
            },
            "InputParameters": "{}",
            "MaximumExecutionFrequency": "TwentyFour_Hours",
            "ConfigRuleState": "ACTIVE"
        }
    ]
}
```

**Comment by kapilt** [comment]
i think custodian not supporting config rules for things that config does not support is an important safety belt for users. else the config rule is effectively a poll and evaluate separately, ie the config infrastructure is mostly useless outside of reporting and the operational semantics of the policy are very different then normal config rules, additionally the policy will fail for any signficant cardinality, so the example ebs policy will hit lambda timeouts typically. 

using ssm ops center or security hub for reporting aggregation seems like a better usage for resources not supported by config.
