### ISSUE TITLE
Multi user access simultaneously custodian

### ISSUE THREAD

**Issue by Chinmayan** [cloud-custodian/cloud-custodian#5158]
I want to install custodian in EC2 and want multiple people to use it simultaneously, is it possible? As per my understanding custodian takes the Access key and secret key from aws cli itself. So just curious on how multiple people can access providing their access key and secret key simultaneously to a single installation. Please advice

**Comment by kapilt** [comment]
its a bit unclear what your referencing wrt to multi-user access. its a cli, so yes multiple folks can use it, the --cache* settings would need to be configured if their targeting the same account/region. best practice is infrastructure as code, so they'll commit to a set of central repos (with code review and ci), that the runtime/ec2 would pull from to execute.

**Comment by Chinmayan** [comment]
Thanks Kapil, Let me explain a bit further.

We have installed custodian on ec2. We have written some policies. We want multiple users (User X for Account-XYZ and User A for Account-ABC) to run policies simultaneously. 
Now for running a policy, we need the Access key and secret access key.

**AWS_ACCESS_KEY_ID="foo" AWS_SECRET_ACCESS_KEY="bar" custodian run --output-dir=. custodian.yml**

And if if aws cle is configured , we dont need it. Now if multiple users are there, we cant set the access key and secret access key in EC2. 
We want the users to give their access key and secret access key when executing the policy for the same installation of custodian. 


so how can we have multiple user accessing when their accesskey and secret access key are different. We dont want to store their accesskey and secret access key in EC2. 

Thanks Again

**Comment by kapilt** [comment]
1.  if you want an ec2 to run across multiple accounts, then you should be using ec2 instance role with sts role assumption across accounts, ie --assume on the cli. static credentials are verboten from a security perspective. 
2. the recommend way for an ec2 instance to run across accounts / regions is via the c7n-org tool which executes in parallel and uses sts role assumption.
2. if you want humans manually to be executing custodian policies from an ec2 instance. first, it might be worth taking a step back, and understanding that custodian is intended as an automated compliance as code tool, institutionalizing manual usage is really not a best practice, in fact its probably bad in practice. 
3. if you still really want humans sharing the same instance manually executing policies, understand you have no isolation boundary between those users, and you need to assume a very high degree of trust between them both into the accounts and between the users. ie any user on the box has access to all the other accounts and users, locking down a multi-tenant unix user box is a devops exercise outside of the scope of this project.
4. if you really want humans manually executing policies,  should really be using some sort of sso/saml/federated setup with users and let them install locally with credential access. ie auth into provider and get temporary credentials. again using long lived static iam user credentials is considered a bad practice and a high risk posture in any environment.
5. if you really, really, want to have a bunch of humans executing custodian policies manually across accounts, you can just set the env vars transiently when executing on the cli. again this is broken from a security perspective in many, many ways, and assume they all have access to each others accounts.

**Comment by kapilt** [comment]
generally speaking when hearing about these sorts of implementations decisions, its best to take a step back and ask whats are the goals, aka the why, not the how.
