### ISSUE TITLE
Add custodian_snapshot tag to aws.ebs.actions.snapshot?

### ISSUE THREAD

**Issue by bb1314** [cloud-custodian/cloud-custodian#5163]
I've noticed EBS snapshot created using **aws.ec2.actions.snapshot** automatically gets tagged **custodian_snapshot**. But snapshot created using **aws.ebs.actions.snapshot** doesn't have that tag. That tag is actually quite useful for when making a decision on deleting a snapshot based on whether or not the snapshot was originally created by Cloud Custodian. Can we add that to aws.ebs.actions.snapshot?

This existing logic that adds that tag in ec2.py: https://github.com/cloud-custodian/cloud-custodian/blob/0.8.45.3/c7n/resources/ec2.py#L1379

Happy to contribute if we think this is useful!

**Comment by kapilt** [comment]
ebs snapshot was recently extended to support copy-tag style syntax. the custodian marker tag was a bit of an accident wrt to value, but yeah game for the addition.

**Comment by kapilt** [comment]
ideally this would be a tags: mapping that the user could also specify their own tags/values.
