### ISSUE TITLE
azure - How can config it support for ‘AzureChinaCloud’ environment?

### ISSUE THREAD

**Issue by chinapsu** [cloud-custodian/cloud-custodian#5166]
### How can config it support for ‘AzureChinaCloud’ environment? 

I have an Azure China subscription account. I want to support it in China. How do I configure it?

**Comment by kapilt** [comment]
@logachev @aluong any ideas on this? i assume this also requires configuring to target different api endpoints? per https://docs.azure.cn/en-us/articles/guidance/developerdifferences

**Comment by kapilt** [comment]
we'll need to keep an endpoint mapping in the codebase and then use --region cli flag to distinguish on the endpoint mapping to use.

**Comment by logachev** [comment]
Yeah, it shouldn't be a very complex change to add the support.

One thing, I'd prefer not to reuse AWS cli flags because it might be confusing to the users.. Region is not an Azure terminology, so I'd prefer us to have some extensible flags for the cli and let providers configure theirs.. 

So, as a first step I'd probably prefer to use environment variables, same way users already control tenant\subscription.

Added this request to the backlog, will have a prototype shortly.. Need to figure out a way to actually test it.

**Comment by sdfengw** [comment]
@logachev  good news! I also have same question from my customer. The requirement is to manage Azure@China (www.azure.cn) using custodian.  
Looking forward to hearing from your further exciting a prototype shortly that you mentioned. 
thanks!

**Comment by sdfengw** [comment]
@logachev @kapilt if a prototype will be released shortly, we'd like to test it on azure china. thanks!

**Comment by sdfengw** [comment]
@logachev as you said "as a first step I'd probably prefer to use environment variables, same way users already control tenant\subscription.",   whether or not some user has done to control tenant/subscription on AzureChinaCloud using this way？ if sure, could you please give some guidance to  us？ thanks a lot.

**Comment by logachev** [comment]
I can't comment about Azure China Cloud at the moment, I have never worked with it. Let me do some research on our side with people who have an experience.

**Comment by stefangordon** [comment]
In terms of terminology, region for us means region within a cloud (East/West) - whereas China is actually a type of "Cloud".    In Azure CLI you'd pass `--cloud AzureChinaCloud` (or `government`, etc) - and for environment variable something like `AZURE_CLOUD = AzureChinaCloud` (which is probably fine to use for the first implementation in custodian).

We are working on figuring out how to get access to China cloud to test.

**Comment by wsf11** [comment]
Update: It seems that this could be implemented by passing in the Cloud Endpoint names as the `base_url` when initializing the client, as well as passing in the correct Cloud Name when creating credentials. An example for targeting other Clouds using the Python Azure MGT SDK is found [here](https://github.com/Azure/azure-sdk-for-python/blob/6f0f899b6ff7387b35a9fe81a6b2455ed48935fc/doc/sphinx/multicloud.rst#using-predeclared-cloud-definition). 

However, this will prove hard to implement without a test account into these Clouds. Being based in the US, it does not seem easy to get access to a test account.

**Comment by kapilt** [comment]
it won't be hard to implement... unless you want to see it actually working in china yourself...

--region azure-china, internal mapping of region to uri endpoints, pass through on endpoint, and wait for feedback from those interested.

**Comment by stefangordon** [comment]
You OK with overloading region for Cloud?  Options for `region` would then be:

AzureCloud (default, worldwide Azure)
AzureUSGovernment
AzureChinaCloud
AzureGermanCloud

Each of those clouds of course actually has multiple regions, but we have no reason to ever pass those regions in the CLI.  We can also just use an `env` for now if we don't want to overload region.

Each of the clouds has different supported services/API versions - so we'll have to get a bit more advanced to support them all well, but just allowing users to connect to them might unblock a lot of scenarios.

**Comment by kapilt** [comment]
so overloading region, feels fine to me and exactly targeted to this exact purpose, as a sanity check I think we need an explicit check that we're not executing across a multi-provider policy file or set of multi-provider policies files on a single execution should error, ie. the following shouldn't run or validate.

```
policies:
   - name: x
     resource: azure.vm
   - name: y
     resource: aws.ec2
```

re different regions/different supported apis, aws provider currently deals with provider initialize_policies method re available regions on a given service etc, that method is intended to give the provider implementation the ability to filter/error etc on exactly this problem.

**Comment by stefangordon** [comment]
Great.  Sounds like a plan.

**Comment by sdfengw** [comment]
good news, thanks for your hard working.
