### ISSUE TITLE
AWS:  Use of Security Group_Name Vrs Security Group_ID result differs

### ISSUE THREAD

**Issue by knelyoo** [cloud-custodian/cloud-custodian#5169]
am currently working on a use case to the attach a special security group to newly provisioned EC2 in a vpc.

See custodian policy details below.

> - name: auto-remediate-sg
       resource: aws.ec2
-mode:
     type: cloudtrail
    role: arn:aws:iam::role
-events:
    - RunInstances
-filters:
    - "State.Name": pending
actions:
     - type: modify-security-groups
     add: ["Security group_Id01","Security group_Id02"] 

When security Group_Id is used in the add[ ] action
result is as expected.

However when Security Group_Name is used in the add[ ] action 
> add: ["Security group_Name01","Security group_Name02"] 

the result is a trace back error from the lambda below.

> groups = super(EC2ModifyVpcSecurityGroups, self).get_groups(interfaces)
File "/var/task/c7n/actions/network.py", line 227, in get_groups
r, self._get_array('isolation-group'), resolved_groups)
File "/var/task/c7n/actions/network.py", line 162, in resolve_group_names
vpc_id = self.vpc_expr.search(r)
AttributeError: 'NoneType' object has no attribute 'search'

**Comment by kapilt** [comment]
it wasn't clear what version of custodian this was, but that was from validation not being run on the policy when running in serverless mode, which has been true for all versions of custodian from 2019/05.
