### ISSUE TITLE
azure - failed at first run policy 

### ISSUE THREAD

**Issue by sdfengw** [cloud-custodian/cloud-custodian#5171]
hello，
I am interested in custodian and think its useful for multi-cloud management. So I decide to experience once.
Below is my environment, and I refer to "https://cloudcustodian.io/docs/azure/gettingstarted.html" to install custodian.
1. Azure Global
2. client: Linux (centos 7.5.1804)
All seems ok but I tested first policy as "Resource Groups - Remove empty Resource Groups" and met errors as below:
![QQ截图20191214212928](https://user-images.githubusercontent.com/13249823/70849416-f1564500-1eb8-11ea-96a1-8337f8764c41.png)

highly appreciated if you could give me favor to resolve this issue!

feng

**Comment by kapilt** [comment]
it appears your using an unreleased version of python, 3.6-3.8 are supported, 2.7 is supported till end of 2019.

**Comment by sdfengw** [comment]
@kapilt  thanks a lot.
