### ISSUE TITLE
memory usage increase - 0.8.45.0 upgrade

### ISSUE THREAD

**Issue by vigneshthi** [cloud-custodian/cloud-custodian#5182]
Previously, the cloud custodian version 0.8.33.1 was running in a t2.micro ec2 instance. we have a crontab scheduled to run in off-hours to generated reports on some 50+ accounts and send it to s3. The memory consumptions during the scheduled run were around 500mb.

Recently, upgraded the cloud custodian deployment to version 0.8.45.0 from .0.8.33.1.
whenever the scheduled event starts the instance throws out of memory and become unavailable.
I have changed the instance type to t2.small and it still the same. 

[10237.242813] [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
[10237.638692] [28987]     0 28987   299435   113209     315       5        0             0 custodian
[10237.646544] [29326]     0 29326   298292   111152     308       4        0             0 custodian
[10237.654740] [29759]     0 29759   297356    98523     292       4        0             0 custodian
[10237.662545] [29777]     0 29777   296076    92086     276       4        0             0 custodian
[10237.669984] [29910]     0 29910   264088    41130     177       4        0             0 custodian
[10237.677380] Out of memory: Kill process 28987 (custodian) score 215 or sacrifice child
[10237.684866] Killed process 28987 (custodian) total-vm:1197740kB, anon-rss:452836kB, file-rss:0kB, shmem-rss:0kB
[10238.794021] oom_reaper: reaped process 28987 (custodian), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

why is there a drastic change in the memory consumption for the new version?
how can I fix it?

**Comment by vigneshthi** [comment]
@kapilt

**Comment by kapilt** [comment]
so without, any notion of how many resources custodian is processing, or what the policies are or the changes in those policies, or the cli options its unclear how to even analyze this. ie has the resource count in these 50 accounts changed significantly, like if its doubled then that might explain things right there.  given your upgrade was across such a large range of versions (13) from a year ago, if you think its custodian, then it would be helpful to narrow down by trying bisecting and identifying a specific version, in addition to the above information.

**Comment by vigneshthi** [comment]
Thanks for your response. 

I tried installing the older versions of custodian in our latest hardenAMI but I was getting this below-mentioned error. [error is displayed for version 0.8.33.1 to version 0.8.43.1]
(custodian) [root@ip-10-30-10-123 cloudcustodian]# custodian schema
Traceback (most recent call last):
  File "/opt/cloudcustodian/custodian/bin/custodian", line 8, in <module>
    sys.exit(main())
  File "/opt/cloudcustodian/custodian/local/lib/python2.7/site-packages/c7n/cli.py", line 368, in main
    command(config)
  File "/opt/cloudcustodian/custodian/local/lib/python2.7/site-packages/c7n/commands.py", line 380, in schema_cmd
    load_resources()
  File "/opt/cloudcustodian/custodian/local/lib/python2.7/site-packages/c7n/resources/__init__.py", line 96, in load_resources
    import c7n.resources.vpc
  File "/opt/cloudcustodian/custodian/local/lib/python2.7/site-packages/c7n/resources/vpc.py", line 29, in <module>
    from c7n.filters.locked import Locked
  File "/opt/cloudcustodian/custodian/local/lib/python2.7/site-packages/c7n/filters/locked.py", line 82, in <module>
    class SignatureAuth(requests.auth.AuthBase):
AttributeError: 'module' object has no attribute 'auth'
------------------

using latest hardenAMI, From version 0.8.44.0, this error is not showing up. 
might be due to PR - https://github.com/cloud-custodian/cloud-custodian/pull/4071

pip freeze -
argcomplete==1.10.3
attrs==19.3.0
boto3==1.10.44
botocore==1.13.44
c7n==0.8.44.0
certifi==2019.11.28
configparser==4.0.2
contextlib2==0.6.0.post1
docutils==0.15.2
functools32==3.2.3.post2
futures==3.3.0
importlib-metadata==1.3.0
jmespath==0.9.4
jsonpatch==1.24
jsonpointer==2.0
jsonschema==3.2.0
more-itertools==5.0.0
pathlib2==2.3.5
pyrsistent==0.15.6
python-dateutil==2.8.1
PyYAML==5.2
s3transfer==0.2.1
scandir==1.10.0
six==1.13.0
tabulate==0.8.2
urllib3==1.25.7
zipp==0.6.0


for the older hardenAMI, with custodian verison 0.8.33.1 - working without any error. The cpu utilization is less than 500 mb for the scheduled policy executions.
pip freeze
argcomplete==1.10.0
attrs==19.1.0
boto3==1.9.198
botocore==1.12.198
c7n==0.8.33.1
docutils==0.14
functools32==3.2.3.post2
futures==3.3.0
jmespath==0.9.4
jsonpatch==1.24
jsonpointer==2.0
jsonschema==3.0.1
pyrsistent==0.15.4
python-dateutil==2.8.0
PyYAML==5.1.1
s3transfer==0.2.1
six==1.12.0
tabulate==0.8.3
urllib3==1.25.3

**Comment by kapilt** [comment]
okay, thats useful, re pip issues on some older versions, thats mostly due to not doing hard pinning/locking at time of publishing, which is something we're going to address in 2020, in that particular case it looks like it needs an older version of boto3 to be installed first in the virtualenv (pip install boto3==1.9.74 ). did 0.8.44.0 issue have the memory growth?

questions
 - how many policies are you running across which resource types? 
 - whats the highest cardinality of resource your dealing with (one million ebs snapshots), is the issue
    specific to a particular account/region?
 - are you running across accounts with c7n-org (ie in parallel, which needs more memory)?

**Comment by vigneshthi** [comment]
@kapilt  1. I'm running 10 policies in an interval of 30 mins.
2. Our previously deployment with cloudcustodian v0.8.33 take around around 15 mins / about 500 mb for s3 write report, and that is the highest of all the reports. 
3. We are not running it parallelly. 

recently tried using t2 medium for the new cloudcustodian v0.8.44. Before the job started the memory util was less 150mb, and when the cron job started the memory utilization went upto 3.5-4 gb and stayed using that much memory even after the report is run.

**Comment by kapilt** [comment]
i'm not sure what basis your reporting memory utilization, especially if your reporting high utilization after the report/cron job is finished? what custodian commands and cli flags are you using (no account ids) in this cron report? the comment about s3 write report is odd, since custodian report command doesn't write to s3.
