### ISSUE TITLE
r53domain throttling exception

### ISSUE THREAD

**Issue by jyrkiput** [cloud-custodian/cloud-custodian#5197]
I'm getting following error when trying to use r53domain -resource

`An error occurred (ThrottlingException) when calling the ListTagsForDomain operation (reached max retries: 4): Rate exceeded`

That account has a lot domains, most of our accounts works perfectly.

Any tips/help?

**Comment by kapilt** [comment]
what's the policy (sanitized) look like?

**Comment by jyrkiput** [comment]
I'm just listing all domains, so

`
policies:
  - name: route53-domains # List all registered domains
    resource: r53domain
`

**Comment by kapilt** [comment]
okay, looks like we're missing a throttling retry here, though it also looks like r53domains are supported by the resource group tagging api
