### ISSUE TITLE
Release cycles for PyPi

### ISSUE THREAD

**Issue by myoung34** [cloud-custodian/cloud-custodian#5199]
Is there a release cycle for PyPi?

There are no tags/releases in a while

Latest tag: 0.8.45.3 (11/11/19)
Latest PyPi: 0.8.45.3 (11/11/19)
Latest Github release: 0.8.45.0 (9/23/19)

There are commits i need in prod and dont want to have to change all of our pipelines in lieu unless I need to

**Comment by kapilt** [comment]
all tags are github releases (ie show on releases page), they just don't post that way unless created explicitly as a release which we don't typically do except for minors.

yeah, we're due for a release.

**Comment by kapilt** [comment]
getting ready for new release in #5205

**Comment by kapilt** [comment]
0.8.45.4 released on pypi and tagged on the repo.

**Comment by myoung34** [comment]
Thanks @kapilt !
