### ISSUE TITLE
Python - botocore requests libraries need replacing in code as it's being removed

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#5200]
the botocore vendored requests is going away - https://aws.amazon.com/blogs/developer/removing-the-vendored-version-of-requests-from-botocore/  - https://github.com/boto/botocore/pull/1829

Looks like it would affect the following c7n files:

https://github.com/cloud-custodian/cloud-custodian/blob/a1de629e1e02e78dda17c415b3ddacc4e96ce453/tools/c7n_sentry/c7n_sentry/c7nsentry.py#L70

https://github.com/cloud-custodian/cloud-custodian/blob/b243bef1f2c37ccdc8f21714197a90b1a1608b77/tools/c7n_salactus/c7n_salactus/worker.py#L80
https://github.com/cloud-custodian/cloud-custodian/blob/41c562a81503fd7b14d9b5ba798cda5ebba5d7a9/c7n/resources/s3.py#L63

**Comment by kapilt** [comment]
thanks for reporting this, the later one is a fallback improt path that can safely be removed now that botocore is updated in lambda. the first two will require adjustment, the first to use a separate dependency on requests, the second it looks like to use urllib3.
