### ISSUE TITLE
Supports additional filters for convert timestamp to date time format

### ISSUE THREAD

**Issue by KVInventoR** [cloud-custodian/cloud-custodian#5203]
Hi All,

I would like to request a new feature which will get a possibility to convert unix timestamp, like this:   1564467134.05 to normal utc time like this: Tuesday, July 30, 2019 6:12:14.050 AM

This timestamp is returned by cloudwatch logs (date when log group was created)

**Comment by kapilt** [comment]
the default value filter has builtin support for conversion. note log groups are not a std unix timestamp.

**Comment by KVInventoR** [comment]
hm,

do you have any example how it possible to convert?

**Comment by kapilt** [comment]
so we normalized log groups to seconds since epoch instead of milliseconds https://github.com/cloud-custodian/cloud-custodian/pull/4194

in terms of the filter, here's one to find all log groups older than 90 days.

```
type: value
key: creationTime
value: 90
op: greater-than
value_type: age
```
