### ISSUE TITLE
ecr set-scanning action

### ISSUE THREAD

**Issue by adamcanzuk** [cloud-custodian/cloud-custodian#5209]
I'm still learning Cloud Custodian, so this could be a knowledge gap on my side.
 
The goal of the policy is to set vulnerability scanning on ECR repos that do not have it enabled.

It seems like the schema for ecr is not updated to include "set-scanning" as the documentation suggests. https://cloudcustodian.io/docs/aws/resources/ecr.html

**Policy:**
policies:
  - name: ecr-vulnerability-scanning-enabled
    resource: aws.ecr
    filters:
      - type: value
        key: imageScanningConfiguration.scanOnPush
        value: false
    actions:
      - set-scanning

**Output**
custodian.commands:ERROR invalid policy file: ../policies/SHARED/regional-resource-policies-read-only/ecr-read-only-test.yml error: Failed to validate policy ecr-vulnerability-scanning-enabled 
 Error on policy:ecr-vulnerability-scanning-enabled resource:aws.ecr
'set-scanning' is not valid under any of the given schemas

Failed validating 'anyOf' in schema[59]['allOf'][1]['properties']['actions']['items']:
    {'anyOf': [{'$ref': '#/definitions/actions/aws.auto-tag-user'},
               {'$ref': '#/definitions/actions/aws.invoke-lambda'},
               {'$ref': '#/definitions/actions/aws.invoke-sfn'},
               {'$ref': '#/definitions/actions/aws.mark-for-op'},
               {'$ref': '#/definitions/actions/aws.notify'},
               {'$ref': '#/definitions/actions/aws.post-finding'},
               {'$ref': '#/definitions/actions/aws.post-item'},
               {'$ref': '#/definitions/actions/aws.put-metric'},
               {'$ref': '#/definitions/resources/aws.ecr/actions/remove-statements'},
               {'$ref': '#/definitions/actions/aws.remove-tag'},
               {'$ref': '#/definitions/resources/aws.ecr/actions/set-lifecycle'},
               {'$ref': '#/definitions/actions/aws.tag'},
               {'$ref': '#/definitions/actions/aws.webhook'},
               {'enum': ['notify',
                         'webhook',
                         'tag',
                         'remove-tag',
                         'mark-for-op',
                         'set-lifecycle',
                         'remove-statements',
                         'auto-tag-user',
                         'invoke-lambda',
                         'put-metric',
                         'post-finding',
                         'invoke-sfn',
                         'post-item']}]}

On instance['actions'][0]:
    'set-scanning'
2020-01-08 09:11:07,570: custodian.commands:ERROR Found 1 errors.  Exiting.

**Comment by kapilt** [comment]
the ecr scanning actions, are available in trunk only atm, there will be a new release out this week with them (0.8.45.4)

**Comment by adamcanzuk** [comment]
Thank you!
