### ISSUE TITLE
add python3.8 to the enum for runtime

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#5218]
python3.8 is supported by lambda per https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html and since their is a ci for python3.8 this should be easy

**Comment by kapilt** [comment]
currently the default is python 3.7, any thoughts on switching the default to python 3.8?

**Comment by FireballDWF** [comment]
Makes sense to change the default, as python3.8 runtime is the first based on amzn2, which will be supported for 3 years longer than amzn1.  python3.7 (and earlier) runtime uses amzn1, which according to https://aws.amazon.com/amazon-linux-ami/faqs/  security support ends June 30, 2020.
