### ISSUE TITLE
Add resource support for AWS Serverless Application Support

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#5265]
SAR allows customers to share/publish serverless functions as well as access public function code.  We would like to put some controls around this to detect if our customers are publishing things and maybe even limit the customers to consume the verified AWS customer functions.

**Comment by kapilt** [comment]
fwiw, limit publishing would best be served by limiting in iam, but yeah we should enable checking and disabling this stuff
