### ISSUE TITLE
Non-utf json from GCP

### ISSUE THREAD

**Issue by mrsujeet** [cloud-custodian/cloud-custodian#5293]
I am creating GCP's route and trying to process the event in Cloud Function. I am constantly getting json parsing error as below. I chatted with Kapil about it. It seems like GCP is passing non utf json

Looking forward for your quick response on it.

Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 383, in run_background_function _function_handler.invoke_user_function(event_object) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 217, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 214, in call_user_function event_context.Context(**request_or_event.context)) File "/user_code/main.py", line 17, in run event = json.loads(base64.b64decode(event['data']).decode('utf-8')) UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte

payload:

Event: {'insertId': '-naoi1tdc862', 'logName': 'projects/bold-hallway-258919/logs/cloudaudit.googleapis.com%2Factivity', 'operation': {'id': 'operation-1578614395820-59bbdce4cdb98-efcc6fb2-cd3fdc8c', 'last': True, 'producer': 'compute.googleapis.com'}, 'protoPayload': {'@type': 'type.googleapis.com/google.cloud.audit.AuditLog', 'authenticationInfo': {'principalEmail': 'xxx.x...@gmail.com'}, 'methodName': 'v1.compute.routes.insert', 'request': {'@type': 'type.googleapis.com/compute.routes.insert'}, 'requestMetadata': {'callerIp': '', 'callerSuppliedUserAgent': 'google-cloud-sdk gcloud/273.0.0 command/gcloud.compute.routes.create invocation-id/f794c079d1a64dd69f017bcb58b06f5d environment/None environment-version/None interactive/True from-script/False python/2.7.10 term/xterm-256color (Macintosh; Intel Mac OS X 18.7.0),gzip(gfe)'}, 'resourceName': 'projects/bold-hallway-258919/global/routes/myroutetencommandline', 'serviceName': 'compute.googleapis.com'}, 'receiveTimestamp': '2020-01-10T00:00:00.383651222Z', 'resource': {'labels': {'project_id': 'bold-hallway-258919', 'route_id': '123658669026574483'}, 'type': 'gce_route'}, 'severity': 'NOTICE', 'timestamp': '2020-01-09T23:59:59.675Z'}

here is the policy:

policies:
  - name: disable-internetgateway
    resource: gcp.route
    mode:
      type: gcp-audit      
      methods:
       - beta.compute.routes.insert
    filters:
     - type: value
       key: nextHopGateway
       op: contains
       value: default-internet-gateway
    actions:
     - type: notify
       to:
         - xxx.yyy@gmail.com
       format: json
      # which template for the email should we use
       template: policy-template
       transport:
         type: pubsub
         topic: projects/bold-hallway-258919/topics/custodian-auto-audit-disable-internetgateway

**Comment by kapilt** [comment]
so per the conversation in #5292 it looks like gcp is occasionally sending us odd content (variably), and we need some additional logging here to see whats the issue with the log payload.

**Comment by kapilt** [comment]
let's keep the discussion on #5292 closing this as a duplicate
