### ISSUE TITLE
aws - ec2 set-traffic-mirror-session enhancement

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#5295]
Add an action to the ec2 resource which invokes the create-traffic-mirror-session passing the ec2 instances network-interface-id.  Also add the delete-taffic-mirror-mession action.

Use Case: Based on a finding on a Production instance, enable traffic mirroring on that instance.  For findings with confidence less than that which justifies immediate isolation/termination/stopping, enabling traffic mirroring can supply the responder with additional data, while not having traffic mirroring enabled full time supports cost optimization.

**Comment by kapilt** [comment]
we don't do enable/disable separate actions anymore, this would be spelled `set-traffic-mirror` which has a state boolean

**Comment by kapilt** [comment]
also this should also be on an action on an eni, although I'm curious if this is allowed on non owned enis.
