### ISSUE TITLE
custodian validate failed with latest docker image

### ISSUE THREAD

**Issue by sean-zou** [cloud-custodian/cloud-custodian#5296]
We are using cloudcustodian/c7n:latest, and getting errors below:

> 09:39:41 + custodian validate policy.yaml
> 09:39:41 Traceback (most recent call last):
> 09:39:41   File "/usr/local/bin/custodian", line 8, in <module>
> 09:39:41     sys.exit(main())
> 09:39:41   File "/usr/local/lib/python3.7/site-packages/c7n/cli.py", line 374, in main
> 09:39:41     command(config)
> 09:39:41   File "/usr/local/lib/python3.7/site-packages/c7n/commands.py", line 204, in validate
> 09:39:41     load_resources()
> 09:39:41   File "/usr/local/lib/python3.7/site-packages/c7n/resources/__init__.py", line 113, in load_resources
> 09:39:41     initialize_azure()
> 09:39:41   File "/usr/local/lib/python3.7/site-packages/c7n_azure/entry.py", line 21, in initialize_azure
> 09:39:41     import c7n_azure.policy
> 09:39:41   File "/usr/local/lib/python3.7/site-packages/c7n_azure/policy.py", line 28, in <module>
> 09:39:41     from c7n_azure.resources.arm import ArmResourceManager
> 09:39:41   File "/usr/local/lib/python3.7/site-packages/c7n_azure/resources/arm.py", line 24, in <module>
> 09:39:41     from c7n_azure.query import QueryResourceManager, QueryMeta, ChildResourceManager, TypeInfo, \
> 09:39:41   File "/usr/local/lib/python3.7/site-packages/c7n_azure/query.py", line 397, in <module>
> 09:39:41     resources.subscribe(QueryResourceManager.register_actions_and_filters)
> 09:39:41 TypeError: subscribe() missing 1 required positional argument: 'func'

**Comment by kapilt** [comment]
i'd recommend using a release tag for the moment (ie. cloudcustodian/c7n:0.8.46.1)

debugging this is showing some oddities in the docker build, in that the custodian version in latest image seems to be the last version published to pypi instead of the local version.

**Comment by kapilt** [comment]
the fallback version we're using c7n setup.py is not being recognized (0.9.0-unreleased), which is causing the setuptools to pickup the last pypi published version
```
  Found existing installation: c7n 0.9.0-unreleased                                                                                  
    Uninstalling c7n-0.9.0-unreleased:                                                                                                  
      Successfully uninstalled c7n-0.9.0-unreleased     
```
simply changing that value to `0.9.0dev` seems to do the trick.
