### ISSUE TITLE
support for CrossAccount/Account Iam Roles unused

### ISSUE THREAD

**Issue by pendyalal** [cloud-custodian/cloud-custodian#5301]
It's an enhancement if custodian can check unused iam roles in the account and if the roles are cross account roles check when they are last being used and take an action based on the findings.
Currently, our use case is we are reaching AWS IAM Role hard limits. It's becoming very hard to find the unused IAM Roles.

**Comment by kapilt** [comment]
you can already do that, re cross-account to find cross account roles and unused via usage filter.
