### ISSUE TITLE
Question: aws - notify action schema question

### ISSUE THREAD

**Issue by Lucas-Irvine** [cloud-custodian/cloud-custodian#5304]
Is there any reason that Cloud Custodian requires a "to" or "to_from" field when using the notify action? I am trying to send data to an SNS topic (not using the c7n-mailer tool) and the "to" field seems redundant since the "transport" field already contains the ARN of the sns topic I want to notify.

**Comment by kapilt** [comment]
transports are used to move data, the mailer runs on the other side to pickup messages, render them, and deliver them. if your only interested in data, then putting a dead address in `to` suffices. given its the majority use case of notify action to send a message to humans, having a destination required in schema fits.
