### ISSUE TITLE
Needed assistance on getting c7n-org working with azure service principal

### ISSUE THREAD

**Issue by rturnbull1977** [cloud-custodian/cloud-custodian#5313]
Hello,

I have been working for the last couple of days trying to get c7n-org working with azure.  For c7n-org in aws I had working in under 30 minutes. The azure c7n-org documentation is not very clear at all.  

I have created a service principal in both my azure tenants.  I have confirmed that via login with Azure cli - az login --service-principal --username <client_id> --tenant <tenant id sp is created> --password < password value>, I can login to one of the Azure tenants I have and for instance perform 'az vm list' and it lists VMs. I then issue "az logout" and then "az login --service-principal --username <same client id as first> --tenant <the other tenant id> --password < password value >, I can login to the alternate tenant and again perform az vm list, no issues.

Now when I set the azure service principal environment variables.
export AZURE_TENANT_ID=<value>
export AZURE_SUBSCRIPTION_ID=<value>
export AZURE_CLIENT_ID=<value>
export AZURE_CLIENT_SECRET=<value>

Have a azure_subscriptions.yml file created in the format:
subscriptions:
- name: NAME1
  subscription_id: <id 1>
- name: NAME2
  subscription_id: <id 2>

Create a simply policy for testing:
azure_vm_list.yml
policies:
  - name: azure_vm_list
    resource: azure.vm

And then attempt to execute:

c7n-org run -c ./azure_subscriptions.yml -s ./OUTPUT -u ./azure_vm_list.yml

I get the following error(s):

Type: azure.vm.
Error: Azure Error: InvalidAuthenticationTokenTenant
Message: The access token is from the wrong issuer 'https://sts.windows.net/<tenant id 1>/'. It must match the tenant 'https://sts.windows.net/<tenant id 2>/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/<tenant id 1>' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.
2020-02-04 16:23:41,138: c7n_org:ERROR Exception running policy:azure_vm_list account:PAYG region:global error:Failed to query resources.

Some help would be appreciated in what I'm doing wrong.  Thanks

**Comment by kapilt** [comment]
@stefangordon @logachev ping

**Comment by stefangordon** [comment]
I'll get this scenario tested this morning @rturnbull1977 and get back to you.

**Comment by rturnbull1977** [comment]
Sounds good @stefangordon .  From what I have tested out, because service principal login in azure requires tenant, in this case there is two tenants and each have their own subscription.  The azure_subscriptions.yml file I have only contains the subscription ids for the two tenants.

**Comment by rturnbull1977** [comment]
@stefangordon Question on this topic.  Would cloud custodian c7n-org expect for azure subscriptions file, that the "tenant" contains multiple subscriptions underneath?  I think that is where I'm going wrong, as I have 2 tenants each with their own subscription.  In order to make this work with cloudcustodian I would need to transfer the subscription from #2 tenant into #1 tenant?  Then with the service principals created under each SUBSCRIPTION within the single tenant. Then when using the environment variables: AZURE_CLIENT_ID, AZURE_CLIENT_SECRET, AZURE_TENANT_ID when c7n-org logs in, the subscriptions listed in the accounts.yml file can now be connected to... as the subscriptions in Azure would be under the same tenant.?  Is the assumption correct that c7n-org needs to have all the subscriptions for Azure existing in the same tenant.

**Comment by stefangordon** [comment]
Ah, Yes I understand the scenario you were trying now and you are correct that it isn't currently possible, we'd need to add a feature to c7n-org to let it set different credentials (or at least tenant id) per subscription. 

We expect most organizations only have a single tenant so this had not come up before.

When you have a single tenant for all subscriptions then all the users and service principals are common across all subscriptions, so a single authentication configuration (your environment variables) will work for all subscriptions listed in your `c7n_org` config.    `c7n_org` is roughly the equivalent of you just running `custodian` at the command line once for each of the subscription values.

If you are just running a few subscriptions you could also work around this by just creating a shell script with similar functionality instead of `c7n_org`.   Loop through your subscriptions and call `custodian`, but in your script you could adjust the auth variables as needed for each sub.

**Comment by rturnbull1977** [comment]
Thank you @stefangordon for confirming.  In the meantime I wrote a shell script performing the same operation as you have mentioned above.  I may revisit this later as I have been talking with other members on the team to see if we can simply move the subscription from tenant B to tenant A, therefore being in alignment to what c7n-org expects.  

Could this be stated in the cloud custodian documentation for c7n-org and Azure?
