### ISSUE TITLE
ci - investigate transient py 2.7 tox failure wrt to iam permissions

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#5316]
https://dev.azure.com/cloud-custodian/cloud-custodian/_build/results?buildId=5534&view=logs&jobId=1fc2e071-3735-5446-375d-4a9ead60c2c3&j=1fc2e071-3735-5446-375d-4a9ead60c2c3&t=46946717-7d1a-5609-1f4f-564b9ccd6573

```
___________________ TestIamGen.test_iam_permissions_validity ___________________
[gw1] linux2 -- Python 2.7.17 /home/vsts/work/1/s/.tox/py27/bin/python
Traceback (most recent call last):
  File "/home/vsts/work/1/s/tests/test_iamgen.py", line 97, in test_iam_permissions_validity
    "invalid permissions \n %s" % ('\n'.join(sorted(map(str, invalid)))))
ValueError: invalid permissions 
 ('asg.filters.invalid', [u'elasticloadbalancing:DescribeTargetGroups'])
('asg.filters.valid', [u'elasticloadbalancing:DescribeTargetGroups'])
```

this looks like an issue in the test itself

**Comment by kapilt** [comment]
seems to be very transient only one occurrence ever afaics

**Comment by CMeza99** [comment]
shouldn't py27 support be dropped?

**Comment by kapilt** [comment]
we have to maintain python 2.7 support for 0.8 release series (major bugfix only) till there's drop off on the volume of installs, likely for one year. for trunk we should drop it, but there's some test infra and release infra that needs updating, I'd like to get things switched out to poetry (#5320) as part of that.
