### ISSUE TITLE
aws - health-event DescribeOpsItems Length Restriction

### ISSUE THREAD

**Issue by arunkmarcse** [cloud-custodian/cloud-custodian#5323]
I'm trying to get the list of health-events in our account by using the below custodian policy.  But, getting an exception error. Itseems that there is some restriction in the length of 'ResourceId'. It looks similar to https://github.com/cloud-custodian/cloud-custodian/issues/5024

`botocore.exceptions.ClientError: An error occurred (OpsCenterInvalidArgumentException) when calling the DescribeOpsItems operation: Filter 'ResourceId': 'arn:aws:health:us-east-1::event/RDS/AWS_RDS_CUSTOMER_ENGAGEMENT/AWS_RDS_CUSTOMER_ENGAGEMENT_eb630af4-5934-4ef5-abf6-ac435aec8688' - length of the value must be between 2 and 20.`

The code i have used as below.
`policies:
  - name: test-health-event-new
    resource: health-event
    filters:
      - type: ops-item
        status: ['Open','In progress','Resolved']`

**Comment by kapilt** [comment]
why are you filtering health events on by ssm ops center items? if you want to filter on an attribute of the health event just use a value filter. ssm ops center doesn't support findings/items on health events.
