### ISSUE TITLE
Mailer - Sendgrid - issues sending to multiple recipients

### ISSUE THREAD

**Issue by justinhauer** [cloud-custodian/cloud-custodian#5346]
When using c7n_Mailer with the sendgrid/Azure implementation, having multiple email recipients doesn't seem to work. For example: 
```
    to:
      - tag:OwnerContact
      - me@myemail.com
```
will only send to the hard coded address, not the tag:OwnerContact value.

If you look at the output of the mailer run, you will see something like the following: 

```
2020-02-14 14:54:16,580 - custodian-mailer - INFO - Sending account:a policy:add-storage-firewall azure.storage:1 email:default.html to {('me@me.com', 'secondemail@me.com'): <email.mime.text.MIMEText object at 0x7f51559e1b38>}
```
Unfortunately when looking at the messages sent in sendgrid, you will see the first email address being sent to multiple times (me@me.com has two messages sent to this address while secondemail@me.com has none).

It appears for Azure, the only way to send to multiple recipients in a policy at the time being is to have multiple `type: notify` blocks, one for each recipient.

**Comment by stefangordon** [comment]
Thanks for the details, definitely sounds like a bug with multiple emails.  

Just a quick glance at it makes me think there is an assignment missing here:
https://github.com/cloud-custodian/cloud-custodian/blob/master/tools/c7n_mailer/c7n_mailer/azure_mailer/sendgrid_delivery.py#L92

I see it looping over the `to` addresses but not actually updating the mail message object before sending it. 

Will try to find someone available to fix this and add a unit test.
