### ISSUE TITLE
Mugc error - File "mugc.py", line 200     options.policy_regex = f"^{options.prefix}.*"

### ISSUE THREAD

**Issue by wallabyies** [cloud-custodian/cloud-custodian#5347]
I'm having an issue getting mugc to run on Custodian build 0.8.46.0.   Python version is:  2.7.15rc1

Running mugc results in this error:

$ python mugc.py -c policy.yml --dryrun
```
File "mugc.py", line 200
    options.policy_regex = f"^{options.prefix}.*"
```

Pylint reports this problem:

```
************* Module mugc
E:200, 0: invalid syntax (<string>, line 200) (syntax-error)
```

**Comment by kapilt** [comment]
python 2.7 is past end of life, the recommend would be to upgrade.

it looks like mugc is using a newer format string

**Comment by kapilt** [comment]
fwiw, we're maintaining the 0.8 release branch on the repo, to support python 2.7 users (bug fix only), and i anticipate at least one more release of 0.8, that freezes the dependency graph fully. a pr that targets that branch and fixes mugc seems like a good fix. currently our migration plan (to py3 only) is scattered across comments in a few issues (#3558), getting something into the official docs would also be good.

**Comment by kapilt** [comment]
pushed a pr for the 0.8 release branch that addresses 2.7 mugc compatibility

**Comment by kapilt** [comment]
fix merged
