### ISSUE TITLE
Feature Request - update-distribution action for CloudFront resource

### ISSUE THREAD

**Issue by Lucas-Irvine** [cloud-custodian/cloud-custodian#5357]
---
name: Feature request
about: Implement a new action for the CloudFront distribution resource
title: 'update-distribution action for CloudFront resource'
labels: kind/enhancement
---

**Is your feature request related to a problem? Please describe.**
I want to make sure that CloudFront has logging enabled for compliance reasons. 

**Describe the solution you'd like**
Create an update-distribution action so that a policy can automatically enable logging (and any other changes to a CloudFront distribution resource). This would use the update_distribution boto call here: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudfront.html#CloudFront.Client.update_distribution

**Comment by Lucas-Irvine** [comment]
Working on this now

**Comment by JohnHillegass** [comment]
Closed by #5390
