### ISSUE TITLE
Identifying deleted policies using c7n-policystream diff 

### ISSUE THREAD

**Issue by harinim-coda** [cloud-custodian/cloud-custodian#5364]
Hi,

Below is the command I am using to identify policy differences made via git with **--source** as the last before commit and **--target** as the last commit - 

`c7n-policystream diff --source $(git log --format="%H" -n 2 | tail -n 1) --target $(git log --format="%H" -n 1)`

The output has only policies that are added or modified. I also want to get deleted/remove policies - which also includes deleting single policy in a modified file and also if I delete an entire file.

NOTE: c7n-policystream stream displays the list of all added/modified/deleted history in the repo.

I am new to the custodian and it will be very helpful if I get some input on this. Thanks In Advance!

**Comment by kapilt** [comment]
policy stream does support showing removes and shows an example of that in the readme. 

wrt to the usage of diff, I suggest you look at the readme again. its intent is to output only the policies modified suitable for a ci system to dry run. a deleted policy would not be dry run by a ci.  also if your on the master you don't need to pass --source / --target for HEAD^1 -> HEAD diff, as thats the default. 

ie. if you want to see delete policies, use stream.

**Comment by harinim-coda** [comment]
Thanks for the note!

I wanted to get deleted policies to remove Lambda functions. After this, I came across mugc tool which is used to clean up lambda functions.

NOTE: The documentation  - https://cloudcustodian.io/docs/tools/c7n-policystream.html here does not state anything about diff just displaying the modified ones.
