### ISSUE TITLE
c7n-policystream not scanning .yml files in sub-directories

### ISSUE THREAD

**Issue by m-harini** [cloud-custodian/cloud-custodian#5366]
Hi,

My custodian repository contains the following folder structure:

```
 directory
     |_ dev-policies
         |_ dev-policy-1.yml
         |_ dev-policy-2.yml
     |- prod-policies
         |_ prod-policy.yml
     |- baselinepolicies.yml
 
```

The command `c7n-policystream diff` output provides only policies modified in baselinepolicies.yml. It is not giving new added policies in any of the dev-policy-1.yml, dev-policy-2.yml, prod-policy.yml. Whereas, `c7n-policystream stream` displays <policy-add> in those files.

NOTE: I am running the `c7n-policystream diff` in master branch.

Thanks In Advance!

**Comment by kapilt** [comment]
as noted on gitter, you'll need to provide a test git repository exhibiting the issue, stream and diff using the same underlying mechanism, and there's unit tests around the same.

fwiw, policy stream is an advanced tool, typically used by folks with significant experience around using custodian to optimize ci setups. you've mentioned your just getting started..

**Comment by m-harini** [comment]
@kapilt  Here is the link to github, where issue can be reproduce. 

https://github.com/m-harini/custodian-starter.git

Following is the output for stream and diff - 

```
$ c7n-policystream stream
<policy-add policy:wp-baseline-account-service-limit-increase provider:aws resource:aws.account date:2020-02-20T17:39:04+05:30 author:Harini Muralidharan commit:5a4753>
<policy-add policy:Test-Custodian provider:aws resource:account date:2020-02-20T17:40:36+05:30 author:Harini Muralidharan commit:62d22a>
2020-02-20 18:34:30,497: c7n.policystream:INFO Streamed 2 policy repo changes

$ c7n-policystream diff
policies: []
```

**Comment by kapilt** [comment]
thanks for the sample repo, confirmed the issue, its a one line fix, I'll have a pr up in a bit, but would like to add a unit test case as well

```diff
@@ -287,7 +287,7 @@ class PolicyRepo(object):
         while q:
             t, prefix = q.popleft()
             for fent in t:
-                if fent.type == 'tree':
+                if fent.type == pygit2.GIT_OBJ_TREE:
```
