### ISSUE TITLE
copy-related-tags issue

### ISSUE THREAD

**Issue by kristentestgithubaccount** [cloud-custodian/cloud-custodian#5380]
I was wondering if you might be able to take a look at the following code snippet to see if there is something that I am doing wrong in order to get the copy-related-tags function to work from rest-apis to rest-stages? I have tried multiple variations with no success. https://gist.github.com/khapp/51adbba0236a6bafe67cdfd5fe8d1bd5

**Comment by kapilt** [comment]
what version of custodian and boto, please add output of `custodian version --debug` to the gist

**Comment by khapp** [comment]
The gist has been updated with the requested information.  Thanks!
