### ISSUE TITLE
Kafka emails causing c7n mailer to error out

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#5397]
**Describe the bug**
Any emails coming from the kafka resources are causing the mailer to error out due to what appears to be a get tags issue.

**To Reproduce**
any notify action appears to trigger this with the kafka resourcde

**Expected behavior**
Expecting the emails to send

See gist for policy and error
 https://gist.github.com/jtroberts83/68b2f98bbd4f5255821b13160eebfb23

**Comment by kapilt** [comment]
thanks for the bug report, afaics the service started adding tags, in a different format then what we expect, and we should a) modify how it looks to the rest of custodian b) update mailer to support both styles in case it happens again for a different resource.
