### ISSUE TITLE
core - AWS Notify action is registered for all providers

### ISSUE THREAD

**Issue by logachev** [cloud-custodian/cloud-custodian#5403]
AWS Notify action is registered for all providers while it has a lot of AWS specifics.. 

We need to think about the good strategy for actions that share the name, but differ in their schemas for different providers..

**Comment by kapilt** [comment]
we don't really need a strategy, its supported by default. i thought previously that the azure resources would automatically register their notify overtop of the existing registration. ie this seems mostly inconsequential and only apparent in tests that are not using properly initialized resources.

**Comment by kapilt** [comment]
actually this seems to be an issue for normal cli usage independent of the tests.
