### ISSUE TITLE
Mugc and policy name prefixes.

### ISSUE THREAD

**Issue by wallabyies** [cloud-custodian/cloud-custodian#5407]
**Describe the bug**
When I deploy a policy in Lambda mode, Custodian will take the policy name and prefix the lambda with **custodian**-.     That's expected and working fine.

But, what I'm seeing with mugc, is that it looks at the policy file where the policy name doesn't have the prefix of **custodian-**, but the deployed lambda has the **custodian-** prefix. Mugc doesn't match these up and a dryrun reports that it would delete the lambda.

**To Reproduce**
1) Deploy a policy via lambda mode.    Policy name in yml file doesn't start with **custodian-**.   Custodian adds **custodian-** prefix to lambda name upon deployment.
2) Run mugc.      Mugc doesn't match up the deployed lambda that starts with **custodian-**, with the policy file where the policy name doesn't start with **custodian-**.
3) Mugc reports **mugc:INFO Region:us-east-1 Removing custodian-yourpolicy**.

**Expected behavior**
I would expect mugc to match up the policy file where the names are not prefixed with **custodian-** with the deployed lambdas that do have the **custodian-** prefix.

I have tried a workaround of having policy names start with **custodian-**, but then upon deployment, Custodian adds another custodian- to the policy name.     This looks a big ugly, as then all the policy names start with **custodian-custodian-**.

**Background (please complete the following information):**
- Current master branch of Custodian.

**Comment by kapilt** [comment]
as discussed on gitter, this was a problem of passing an invalid policy file.

**Comment by wallabyies** [comment]
Yes, this can be closed out.

The root cause was found to be that concatenating multiple policy files into one created an invalid policy file.   (Due to multiple occurrences of "policies:" in the file.)

Some sed magic was able to clean that up, and mugc is working as expected.

It would be better if mugc did validation on the file before running.    In this case, mugc did run with the policy file in the problem format, but it would have deleted all custodian lambdas.

**Comment by kapilt** [comment]
added separate issue re validation
