### ISSUE TITLE
Can CloudCustodian operate over Azure Blobs?

### ISSUE THREAD

**Issue by leoblanc** [cloud-custodian/cloud-custodian#5420]
Hi, I'm trying to delete Azure Blobs that doesn't have the mandatory tags.

I have been checking the available resources: https://cloudcustodian.io/docs/azure/resources/group-storage.html.

So, I can retrieve every [Storage Account](https://cloudcustodian.io/docs/azure/resources/storage.html). I can also list all the [Containers](https://cloudcustodian.io/docs/azure/resources/storage-container.html) inside of each Storage Account. 

But, are there any ways to list all the Blob objects stored on the Containers?

Thank you very much in advance.

**Comment by kapilt** [comment]
that sort of data plane scanning is something we've moved to dedicated tools that support scale out capabilities, like tools/c7n_salactus which can be deployed on a cluster for 500k keys/s type of scans for populations in the billions, we originally had that stuff in custodian but as key counts grew into the large cardinality, it didn't scale, hence the buildout of a separate scalable tool. note it doesn't support azure blob store, but if there's interest in contributing, I think there are others who would like to collaborate, @cloud-custodian/azure

**Comment by stefangordon** [comment]
Regarding tags specifically, I don't believe Azure supports any tagging for Blobs since they are not ARM resources.  Blobs do have metadata so you could set key/value pairs, but as mentioned this isn't planned for support in core custodian tooling.

**Comment by leoblanc** [comment]
@kapilt @stefangordon Thanks a lot for your feedback! This info is very useful, got it now. Closing this issue.
