### ISSUE TITLE
GCP: Written Policy Example for CIS Benchmarks

### ISSUE THREAD

**Issue by aakifshaikh** [cloud-custodian/cloud-custodian#5439]
Can we have the written policy examples for CIS Benchmarks for GCP. We are having a difficult time to write any.

**Comment by kapilt** [comment]
the custodian project does not distribute policies in this repo beyond documentation of how to author a policy, ie. if you want to contribute examples of how to author a policy this is a good place,  If you want to consume some set of policies that claims to map to a standard this isn't the right repo.

**Comment by mvanholsteijn** [comment]
https://github.com/GoogleCloudPlatform/inspec-gcp-cis-benchmark
