### ISSUE TITLE
c7n: generic filter to limit and sort resources

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#5469]
**Is your feature request related to a problem? Please describe.**

I have over 500 resources returning when filtering for old unused AMIs and these are batched up in 3 different slack messages for 8 different regions which spams email and slack with 24 messages once a week.

I'd like to only use a subset of the resources like the top 10 oldest AMIs per region which should be less than the 250 batch limit which should decrease the 24 slack messages down to 8 slack messages (1 per region). I want to use `max-resources` but this option fails the policy. I'd like to limit the resources and sort them if possible.

**Describe the solution you'd like**
A `sort` filter to sort my resources and then a `max-resources` filter to limit the number of resources returned. This way I can sort by `CreationDate` and then set the `max-resources` to 10 resources

Is there a jmespath query to do this as a value filter in the policy itself?

**Describe alternatives you've considered**
I've tried filtering in the jinja template using python subset but this is applied after the batch limit so my jinja filtering happens on batched messages which is what I'm trying to avoid.

**Additional context**

Similar issue https://github.com/cloud-custodian/cloud-custodian/issues/4997 which uses `max-resources` but the resources aren't sorted.

**Comment by kapilt** [comment]
max-resources isn't for just taking an arbitrary partial set from the filtered resources. its a safety breaker that stops policy execution before actions.

what i'm reading is that you want per say sql, you want to have the set ordered with a limit.

the reason why is because of wanting to limit reporting though which seems more akin to #5436 and that the requested filter is itself just a work around.

**Comment by nitrocode** [comment]
Ah ok I see that the `max-resources` is a safety breaker as in the policy will through ResourceLimitExceeded exception if there are more resources than the limit defined.

Is there some jmespath magic I can use with a `value` filter that can allow me to only grab a subset of resources?

**Comment by JohnHillegass** [comment]
Hey @nitrocode, you may have some luck with jmespath [slicing](https://jmespath.org/tutorial.html#slicing) and [functions](https://jmespath.org/tutorial.html#filter-projections) though I haven't played around with them enough to know if it will sort datetimes correctly.

**Comment by nitrocode** [comment]
@JohnHillegass I believe these would only work within the template. Can this be used to limit the number of resources from the policy itself?

**Comment by csabella** [comment]
The AWS CLI allows for `--query`, which, with the suggestion from @JohnHillegass, would use this to return the oldest 10 images.
```
aws ec2 describe-images --query "sort_by(Images[], &CreationDate)[0:10]"
```
However, it appears to be a cli-level filter and not an aws api filter, so I don't think that would translate to a policy.

**Comment by tjstansell** [comment]
I'm looking for something similar ... in our case we're thinking about using it to introduce some chaos engineering.  would love to be able to just select a random 10 instances and shoot them in the head.  but we want a way to be able to make sure they're not all part of the same autoscaling group or something like that.  I was thinking about having a `reduce` filter that would allow you to `group` the instances, `sort` each group (or even randomize), and then `select` some number from each group (which might be an absolute count or percentage).  Something like:
```yaml
policies:
  - name: chaos
    resource: ec2
    filters:
      - "State.Name": "running"
      - "tag:aws:autoscaling:groupName": present
      - type: reduce
        group: "tag:aws:autoscaling:groupName"
        sort:
          key: "LaunchTime"
          order: asc
        select: 1
      - type: reduce
        sort: randomize
        select: 10%
    actions:
      - terminate
```
which would find the oldest instance from of each autoscaling group... then randomly select 10% of them, then terminate them.  Sound interesting to others here?

**Comment by akv3132** [comment]
I'm looking to filter AWS AMI with tags and I have used value filters. 
`policies:
  - name: golden-ami-policy
    resource: ami
    filters:
      - type: value
        key: "tag:golden-ami"
        value: "true"
      - type: value
        key: "tag:app"
        value: "base"
      - type: value
        key: "tag:owner"
        value: "devops"
      - type: value
        key: "tag:approved-ami"
        value: "true"
      - type: reduce
        sort-by: "CreationDate"
        group-by: "tag:al2-base"
        order: asc
        limit: 10
    actions:
      - type: deregister
        delete-snapshots: true
`
I want to use reduce filter but I figured reduce filter won't work where when I tried to use it I see following error. 

`2020-08-08 20:47:13,741: root:ERROR specific_error failed, traceback, followed by fallback
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/c7n/schema.py", line 54, in validate
    resp = policy_error_scope(specific_error(errors[0]), data)
  File "/usr/local/lib/python3.6/site-packages/c7n/schema.py", line 126, in specific_error
    return specific_error(e)
  File "/usr/local/lib/python3.6/site-packages/c7n/schema.py", line 136, in specific_error
    elif 'type' in v and t in v['properties']['type']['enum']:
KeyError: 'type'
2020-08-08 20:47:13,815: custodian.commands:ERROR invalid policy file: /home/policies/policy2.yaml error: Failed to validate policy 'reduce' is not one of ['cross-account']

Failed validating 'enum' in schema[0]['properties']['type']:
    {'enum': ['cross-account']}

On instance['type']:
    'reduce' 
 {'name': 'golden-ami-policy', 'resource': 'ami', 'filters': [{'type': 'value', 'key': 'tag:golden-ami', 'value': 'true'}, {'type': 'value', 'key': 'tag:app', 'value': 'base'}, {'type': 'value', 'key': 'tag:owner', 'value': 'devops'}, {'type': 'value', 'key': 'tag:approved-ami', 'value': 'true'}, {'type': 'image-age', 'days': 13, 'op': 'gt'}, {'type': 'reduce', 'sort-by': 'CreationDate', 'group-by': 'tag:base', 'order': 'asc', 'limit': 10}]} is not valid under any of the given schemas

Failed validating 'anyOf' in schema['properties']['policies']['items']:
    {'anyOf': [{'$ref': '#/definitions/resources/aws.ami/policy'},
               {'$ref': '#/definitions/resources/aws.ec2/policy'},
               {'$ref': '#/definitions/resources/aws.ec2-reserved/policy'},
               {'$ref': '#/definitions/resources/aws.iam-certificate/policy'},
               {'$ref': '#/definitions/resources/aws.iam-group/policy'},
               {'$ref': '#/definitions/resources/aws.iam-policy/policy'},
               {'$ref': '#/definitions/resources/aws.iam-profile/policy'},
               {'$ref': '#/definitions/resources/aws.iam-role/policy'},
               {'$ref': '#/definitions/resources/aws.iam-user/policy'},
               {'$ref': '#/definitions/resources/aws.launch-template-version/policy'},
               {'$ref': '#/definitions/resources/aws.ops-item/policy'},
               {'$ref': '#/definitions/resources/aws.ssm-activation/policy'},
               {'$ref': '#/definitions/resources/aws.ssm-managed-instance/policy'},
               {'$ref': '#/definitions/resources/aws.ssm-parameter/policy'},
               {'$ref': '#/definitions/resources/aws.step-machine/policy'}]}

On instance['policies'][0]:
    {'filters': [{'key': 'tag:golden-ami',
                  'type': 'value',
                  'value': 'true'},
                 {'key': 'tag:app', 'type': 'value', 'value': 'base'},
                 {'key': 'tag:owner',
                  'type': 'value',
                  'value': 'devops'},
                 {'key': 'tag:approved-ami',
                  'type': 'value',
                  'value': 'true'},
                 {'days': 13, 'op': 'gt', 'type': 'image-age'},
                 {'group-by': 'tag:base',
                  'limit': 10,
                  'order': 'asc',
                  'sort-by': 'CreationDate',
                  'type': 'reduce'}],
     'name': 'golden-ami-policy',
     'resource': 'ami'}`
any method to filter the 10 ami's based on creation date or any sorting method to find AMI's.

**Comment by tjstansell** [comment]
@akv3132 The error implies the version you're using doesn't support this filter yet.  No releases have been made since this was merged, so it would only work if you're using something based off the master branch in github instead of an official release.

FYI, your filter will delete the oldest 10 AMIs ... but there's no protection against it deleting all of the AMIs.  You could do the inverse and delete all but the latest N (e.g. N=5) with:
```
    filters:
      - type: reduce
        sort-by: "CreationDate"
        group-by: "tag:al2-base"
        order: desc
        discard: 5
```
