### ISSUE TITLE
Release dates

### ISSUE THREAD

**Issue by gelouko** [cloud-custodian/cloud-custodian#5470]
Hi, looks like the last release of the repo was in January...

Is there a release schedule for the project?
Or requirements before a release, etc?

Thanks!

**Comment by kapilt** [comment]
re release, their were some large changes (lazy loading, dropping python 2.7 support, packaging change to poetry) that needed time to bake, plus their happened to be some macro events in the real world that proved disruptive.. as a project we're pretty conservative on compatibility.. as we're oft use in unattended systems. wrt to next release, now that #5320 is landed, we're in pretty good shape. was there something specific you were looking for in the new release?

**Comment by kapilt** [comment]
fwiw, we're looking at trying to get a release (0.9) out the door in the next week .

**Comment by PratMis** [comment]
Great! Would be really helpful if we can merge these PRs #5326 #5319 too before the release 🙏 Thank you!!

**Comment by kapilt** [comment]
we've had a few releases since then.
