### ISSUE TITLE
Restrict policy execution to only a specified account

### ISSUE THREAD

**Issue by dsw88** [cloud-custodian/cloud-custodian#5471]
I have several AWS accounts, and I just executed an AWS EC2 policy against the wrong account. This resulted in the deletion of EC2 instances in that account that should not have been deleted due to differences in tagging that caused them to be selected by the policy. The policy ran correctly; I just ran it against the wrong account because I didn't remember that I was logged in under a different account.

Is there a way in Cloud Custodian to prevent this kind of mistake from happening? Terraform's AWS provider supports an "allowed_account_ids" variable that allows you to require a given module only be executed against a particular set of accounts. If it runs against any other account (usually by mistake on the part of the person running the template) it will refuse to do anything.

Does Cloud Custodian have anything similar? I would like to protect myself against this mistake again, but can't find anything in the Cloud Custodian docs that indicate such a feature.

**Comment by kapilt** [comment]
so policy conditions can be used to express that sort of thing #4466  also we have max-resources ie fail policy if it would touch more than 10% of resource population.

**Comment by dsw88** [comment]
Excellent, that seems like it's just what I'm looking for. Thanks!
