### ISSUE TITLE
docs - investigate alternatives to sphinx

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#5474]
i'm noticing that we're starting to spend a fairly significant amount of time in ci, just on building and validating doc changes. even locally modifying the docs takes multiple minutes to render/preview a simple change. This situation seems to have gotten worse over time, and feels detrimental to contributing more documentation which we want to encourage. moreover though we support markdown, the use of restructured text is feeling anachronistic at best. we do have significant customizations/extensions to sphinx  for reference docs, so ideally a replacement tool is useful for both reference material as well narrative docs.

some options
  - hugo 
  - gitbook
  - mkdocs
  - mdbook
?

**Comment by kapilt** [comment]
actually the speed issue for sphinx seems to have come up as a regression on the switch to poetry, 5m -> 18m. what's odd is that doc ci builds are effectively unchanged, minus a version increment on sphinx. its worth investigating if we need to downgrade sphinx and file an upstream issue.

**Comment by kapilt** [comment]
filed https://github.com/sphinx-doc/sphinx/issues/7343 about the 3x+ speed regression going from sphinx 2.3 -> 2.4

also downgrading sphinx (to ~2.3) in #5475 to restore build ci times to ~5m.

**Comment by JohnHillegass** [comment]
Awesome! I’m glad that this has been added. Since I’m newer to contributing I was not quite sure about it but definitely noticed that the docs build taking a long time. If I have some free time today I’ll try to investigate as well.

**Comment by kapilt** [comment]
doc builds in ci are fixed speedwise, was a bad sphinx release afaics. its perhaps worth keeping this open as alternatives doc tooling might be useful still.

**Comment by kapilt** [comment]
looks like this particular regression in 2.4.0 sphinx series is addressed in the sphinx 3.0 series (pre-release only atm).

**Comment by JohnHillegass** [comment]
I did some research on this and had a hard time finding anyone that recommended anything besides sphinx. [Hitchhikers guide to python ](https://docs.python-guide.org/writing/documentation/) also has a very definitive 'You'll see these things in the wild. Use Sphinx' in it lol. 

An issue with using these other tools is that it's not going to build as easily and will have high learning curves. Its probably best to just stick to Sphinx and wait for the 3.0 release. Though looks like 2.4 is patched not too.. https://github.com/sphinx-doc/sphinx/pull/7344 https://github.com/sphinx-doc/sphinx/issues/7343 wow, that was fast!

**Comment by kapilt** [comment]
also https://github.com/rust-lang/mdBook

we're really just using sphinx for a build tool, we're not using any of the its inline reference capabilities or extraction from code. we have separate tooling i built that does that for us outside of sphinx.. hence our coupling is loose and unrelated to everything you read in hitchhiker's guide. if sphinx is slow, bloated, and causing doc writing pain, we should absolutely be open to other options options. that said there's two things we can do to alleviate some of the current slowness aspects. ie. its worth trying 3.0 to see if its better, but alot of the underlying speed issues are docutils related and aren't likely to change.  its also worth trying, a build cache to see if we can do proper incremental doc builds.. but after that its about looking at a change.

**Comment by peterdemin** [comment]
It looks like the project migrated to MkDocs. Do you think the issue can be closed now?
Also, I wonder if you can share any context on the migration (pros/cons/challenges).

**Comment by kapilt** [comment]
we use mkdocs on the root and sphinx on the actual docs. re sphinx at scale, generating content is faster then using extensions/directives, and caching is key to fast doc builds in ci.

**Comment by kapilt** [comment]
closing, as I think at this point, its not clear there's a whole lot of value on switching tooling, versus just improving the docs.
