### ISSUE TITLE
invoke-sfn | Pass custom json input to the step function

### ISSUE THREAD

**Issue by PratMis** [cloud-custodian/cloud-custodian#5495]
**Is your feature request related to a problem? Please describe.**
Yes, we're planning to have custodian invoke a step function and would like to have custom JSON input data for the execution

**Describe the solution you'd like**
We can add an external field called `input` to action `invoke-sfn` which will be an optional field and if used the value would be pass to start_execution api call(https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/stepfunctions.html#SFN.Client.start_execution) in the form of params

**Describe alternatives you've considered**
Can't think of any alternatives as of now

**Comment by kapilt** [comment]
invoke-sfn is typically for an integration use case, you haven't actually explained a use case but an implementation detail, ie. why do you want static metadata?

**Comment by PratMis** [comment]
Tbh, even I'm not very clear on the use case here. From what I was told, there's some attempt to use cloud custodian to evaluate compliance of non-cloud native resources. Afaik, its still getting explored. Putting custom events to cwe default event bus which goes ahead and triggers a lambda(custodian native). Custodian lambda would then trigger a step function passing it some static key value pairs, depending on what the cwe looks like. Not sure if its a valid use case though

**Comment by PratMis** [comment]
Spent some time on it, doesn't seem to be very useful. @kapilt i'm closing this issue. Thanks!

**Comment by kapilt** [comment]
that sounds like a Rube Goldberg machine.. non custodian resource being injected into an event stream just to have custodian send it to a step function, lol why?
