### ISSUE TITLE
Option to skip mode to run policies locally without having to comment it out

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#5497]
**Is your feature request related to a problem? Please describe.**
I'd like to test my lambda policies locally without having to run them from the command line and then run from the aws console. I want to run them locally without having to comment out the `mode` yaml key.

**Describe the solution you'd like**
Perhaps a `--run-local` or `--skip-mode` switch

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kapilt** [comment]
interesting, --dryrun does skip mode as well and lets folks check filters for the applicable set, but for checking actions, this seems useful to test e2e local.

**Comment by kapilt** [comment]
from discussion on gitter, it seems like --dryrun flags resolved the use case here?
