### ISSUE TITLE
Alias --dry-run to --dryrun so it's consistent with other options

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#5498]
**Is your feature request related to a problem? Please describe.**
A dry run is technically 2 words

https://en.wikipedia.org/wiki/Dry_run_(testing)

It would be nice to keep dry run consistent with the other switches with multiple words by hyphenating it. Other switches that hyphenate multiple words include

```
--external-id
--metrics-enabled
--skip-validation
--cache-period
--output-dir
--log-group
```

**Describe the solution you'd like**
To keep things backwards compatible and consistent, I propose an alias named `--dry-run` that should be the same as `--dryrun`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JohnHillegass** [comment]
Seems like a decent point. I had never really thought of the grammar or patterns being used for these switches. There is definitely a good argument for consistency here and I have submitted a PR that will add the alias if everyone agrees it is a meaningful addition.
