### ISSUE TITLE
docs - auto generate mode documentation from source

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#5507]
for cloud reference docs we're automatically generating on resources, filters, and actions.

we should do the same for execution modes.

**Comment by JohnHillegass** [comment]
just picked this up and have a WIP on https://github.com/JohnHillegass/cloud-custodian/tree/5507-docs-autogen-modes. I has some issues running sphinx and am doing a fresh reinstall from there I should be cleared to submit a PR, hopefully by tomorrow.

**Comment by JohnHillegass** [comment]
Any tips on getting sphinx setup? I had a tox install, doing a poetry one now to see if that resolves.

**Comment by JohnHillegass** [comment]
Oh sorry, just seeing you started one the other day. I'll drop this for now.

**Comment by kapilt** [comment]
> Any tips on getting sphinx setup? I had a tox install, doing a poetry one now to see if that resolves.

if your on poetry it requires adjusting the makefile to remove the sphinx bin qualifier, then just `make sphinx` at the top level. I've noted sphinx building is super slow on incremental (ie its equiv to full) which looks like something that should be investigated, as it only should be rebuilding changed.

**Comment by kapilt** [comment]
fwiw my branch for this also restores incremental building

wrt to doc building the recommended options are  `tox -e docs`   or if using poetry do a one time `cd tools/c7n_sphinxext && poetry install `  and thereafter `make sphinx` to build.

**Comment by JohnHillegass** [comment]
nice! Thanks Kapil, I was able to get it running. In regards to incremental builds being slow, do you think its worth trying the upgrade to 3.0.2? seems like they fixes some slow build issues last week on the 19th. 

https://www.sphinx-doc.org/en/master/changes.html

**Comment by kapilt** [comment]
my pull request addresses it. 3.0.2 release is not about speed, its about fixing regressions I reported in 2.4. incremental is about how we generate. anyways, have a look at the pr if your interested in the details.

**Comment by JohnHillegass** [comment]
Oh nice! Good call with adding the hash checks. I see what you are saying now!!
