### ISSUE TITLE
network-addr report fails for "classic" scoped EIPs

### ISSUE THREAD

**Issue by jweede** [cloud-custodian/cloud-custodian#5510]
Running reports on `network-addr`s with standard scope (instead of vpc) fails with an exception.
Since "standard" eips don't have AllocationIds, this makes sense.

 - OS: ubuntu 18.04
 - Python Version: python3.6
 - Custodian Version: 0.8.46.1
 - Cloud Provider: aws
```yaml
policies: 
     - name: eip-unassociated-release-mark
    resource: network-addr
    filters:
      - AssociationId: absent
      - "tag:c7n_eip_unassociated_release": absent
      - "tag:c7n_eip_unassociated_release_exempt": absent
    actions:
      - type: mark-for-op
        tag: c7n_eip_unassociated_release
        op: release
        days: 90
```
 - Traceback: 
```
Traceback (most recent call last):                                                                           
  File "/home/jweede/.local/bin/custodian", line 10, in <module>                         
    sys.exit(main())                                                            
  File "/home/jweede/.local/lib/python3.6/site-packages/c7n/cli.py", line 374, in main          
    command(config)                                                                 
  File "/home/jweede/.local/lib/python3.6/site-packages/c7n/commands.py", line 141, in _load_policies
    return f(options, list(policies))                                             
  File "/home/jweede/.local/lib/python3.6/site-packages/c7n/commands.py", line 311, in report
    policies, begin_date, options, sys.stdout, raw_output_fh=options.raw)      
  File "/home/jweede/.local/lib/python3.6/site-packages/c7n/reports/csvout.py", line 99, in report
    rows = formatter.to_csv(records)                                           
  File "/home/jweede/.local/lib/python3.6/site-packages/c7n/reports/csvout.py", line 215, in to_csv
    uniq = self.uniq_by_id(records)                                            
  File "/home/jweede/.local/lib/python3.6/site-packages/c7n/reports/csvout.py", line 197, in uniq_by_id
    rec_id = rec[self._id_field]                                               
KeyError: 'AllocationId' 
```

**Comment by kapilt** [comment]
how old is this account? and the elastic ip in question? allocation ids are not to a vpc, they are to an account. ie to create an elastic ip, you allocate it [0].  ie I'm not sure what your referencing by standard vs vpc [1] as elastic ips aren't vpc associated unless bound an instance. is there a doc your referencing? Is this ip from a customer owned ip block or part of a network border group? if you can paste a sanitized reference to it from the resources.json output that would be useful.

[0] https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.allocate_address
[1] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html

**Comment by jweede** [comment]
Thanks for responding @kapilt. This is definitely an old account, old eips. 

It looks like if I allocate a new EIP with `Domain="standard"`, then there's no `AllocationId` and I'll get the above exception on `custodian report` with any output matching this resource. Here's an example resource from the output like you requested:

```
  {
    "InstanceId": "",
    "PublicIp": "3.233.1.69",
    "Domain": "standard",
    "PublicIpv4Pool": "amazon",
    "c7n:MatchedFilters": [
      "AssociationId",
      "AllocationId",
      "tag:c7n_eip_unassociated_release",
      "tag:c7n_eip_unassociated_release_exempt"
    ]
}
```

**Comment by kapilt** [comment]
per my understanding, that implies a pre-vpc elastic ip, which is several years old (as in no accounts created in the last few years support it), since it only applies to accounts with `classic` (ancient) pre vpc networking. i'm not sure why its worth supporting as its very much a legacy notion, and in particular here would need additional foundation support as it changes the id attributes of the resource and requires switching parameters on every api call based on which id attribute is being used, which is significant rework for a strictly legacy consideration.
