### ISSUE TITLE
glue-dev-endpoint age filter

### ISSUE THREAD

**Issue by PratMis** [cloud-custodian/cloud-custodian#5511]
**Is your feature request related to a problem? Please describe.**
Yes
The chances of the SSH key used to protect the development endpoint being brute forced increase as the up time of the endpoint increases. If the key became compromised, an attacker would gain access to all data that the development endpoint was granted access to.
The custodian policy will examine the creation date of the Glue development endpoint and ensure that it is less than X days old

**Describe the solution you'd like**
Add `filter: age` to glue dev endpoints

**Comment by kapilt** [comment]
the use case is already supported by builtin functionality of the value filter which supports date comparisons on any resource attribute.

```
type: value
key: CreatedTimestamp
value_type: age
value: 90
ops: greater-than
```

**Comment by PratMis** [comment]
Cool, got it! Thanks
