### ISSUE TITLE
Investigate opportunities to 'fail early' and improve stack trace

### ISSUE THREAD

**Issue by JohnHillegass** [cloud-custodian/cloud-custodian#5516]
Related to:
https://github.com/cloud-custodian/cloud-custodian/pull/5451

I am submitting this card as a reminder to check for opportunities to `raise future.exception()` now that we are no longer supporting py2x. @kapilt, feel free to assign me as accountable and I will work on it in my free time.

**Comment by kapilt** [comment]
its a bit subtle on some of the usages, the primary thing we need to enable this is revisiting using executor.map to using submit to have a future, however that also needs to makes sense around the surrounding usage which is possibly a context specific evaluation.

**Comment by kapilt** [comment]
if you want to work on this, sounds great, ping me on gitter if you have any questions. it might be worth breaking up into smaller prs, instead of a mass refactoring, there's alot of call sites to modify.

**Comment by kapilt** [comment]
Another one to keep in mind calling exception() if it’s going to access result() is superfluous as that will raise

**Comment by kapilt** [comment]
this isn't really actionable as an issue.

**Comment by JohnHillegass** [comment]
Agreed! Originally, I thought it would be nice to go through every resource and update where it seems fit but it has more or less become an internal reminder for me in new contributions.
