### ISSUE TITLE
releng - switch from ruamel.yaml to pyyaml in mailer

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#5517]
the reasons we where using ruamel was due to the python2/3 separate package nature of pyyaml and wanting to cross install into serverless. now that we're python3 only we can drop ruamel to simplify our dependency set and use pyyaml inmailer.

**Comment by JohnHillegass** [comment]
I has some more free time today than I thought I would so submitted a PR that addresses this #5521
