### ISSUE TITLE
EMR resource query does not  provide data on Security Configurations

### ISSUE THREAD

**Issue by sixer101** [cloud-custodian/cloud-custodian#5522]
By using cloud custodian, it wasn't possible to get results on security configurations.
Using the AWS cli it is possible to get these by running the commands:

aws emr list-security-configurations
aws emr describe-security-configuration --name My-EMR-Security-Config

Is it possible to do this with cloud custodian? 
Thank you

**Comment by kapilt** [comment]
generally given the very wide scope of emr security configurations, most orgs find it best to define a known good baseline, and then just verify the use of that (along with iam permissions to limit the modifications of the known good config), rather than to try regexing strings in the config.
