### ISSUE TITLE
Permissions Boundary Policy support for AWS IAM Roles

### ISSUE THREAD

**Issue by marcpret** [cloud-custodian/cloud-custodian#5524]
Problem Statement:
There doesn't appear to a c7n action that can manage permissions boundary policies for IAM roles.  

Proposed Solution:
A solution to this would likely look very similar to the aws.iam-role action called set-policy where instead of making calls like "client.attach_role_policy" and "client.detach_role_policy" it would call "client.put_role_permissions_boundary" and client.delete_role_permissions_boundary". 

Ideally, this would also support IAM users but there doesn't appear to be an existing aws.iam-user action for set-policy (likely due to best practice of not assigning policies directly to users).  The boto actions for that would be:
put_user_permissions_boundary()
delete_user_permissions_boundary()

**Comment by kapilt** [comment]
sounds good, related #5530 (per recent support for boundaries in simulate permissions)
