### ISSUE TITLE
aws.s3 resource filter check-public-block does not work consistently in combination with tag filter

### ISSUE THREAD

**Issue by hammer2j2** [cloud-custodian/cloud-custodian#5567]
**Describe the bug**
In my testing I have found that the aws.s3 resource filter such as

```
policies:
  - name: nonsecs3nopublic
    resource: aws.s3
    mode:
      type: pull
    filters:
      - type: check-public-block
        scope: Any
        enabled: False

```
appears to work, but if adding a tag present filter after the check-public-block element, the filter finds no results.  So, the same thing, except add a tag present filter such as the below:
```
policies:
  - name: nonsecs3nopublic
    resource: aws.s3
    mode:
      type: pull
    filters:
      - type: check-public-block
        scope: Any
        enabled: False
      - "tag:some-testing-demo-s3plcy1-0": present
```
does not find any results, even though there is that exact tag on the s3 bucket.

**To Reproduce**
1 Add an s3 bucket with a unique tag like `some-testing-demo-s3plcy1-0` and some value.  Make sure the bucket has no public access block settings.
2 Make a policy shown above with a tag following the three lines beginning with `check-public-block`
3 run custodian in dryrun mode (non dryrun mode also exhibits)
"custodian run --dryrun policy.yaml -s custout --cache-period 0
The found buckets will be 0:
```  "metrics": [
    {
      "MetricName": "ResourceCount",
      "Timestamp": "2020-04-08T11:45:05.678265",
      "Value": 0,
      "Unit": "Count"
    },
```

**Expected behavior**

The found buckets should be 1 (assuming a unique tag)
  "metrics": [
    {
      "MetricName": "ResourceCount",
      "Timestamp": "2020-04-08T11:44:34.577200",
      "Value": 1,
      "Unit": "Count"
    },
```

I have found on occasion, that repositioning the tag line filter to precede the line beginning with the `check-public-block` filter and rerunning the policy works, but, I have not always been able to reproduce it working as such.
But for example, you might try the below change and see it work.
```
policies:
  - name: nonsecs3nopublic
    resource: aws.s3
    mode:
      type: pull
    filters:
      - "tag:some-testing-demo-s3plcy1-0": present
      - type: check-public-block
        scope: Any
        enabled: False

```
I build cc off the master branch today.  I also tried from commit ID 2bc598f994c389a145b2fb00b104627114461ada.

We are building and running in Docker.

See below for our Dockerfile.

**Background (please complete the following information):**
 - OS: [e.g. OSX 10.15]
 - Python Version: [e.g. python 3.8.1]
 - Custodian Version: [e.g. 0.8.46.1]
 - Tool Version: [if applicable]
 - Cloud Provider: [e.g. gcp, aws, azure]
 - Policy: [please exclude any account/sensitive information]
```yaml
policies: 
   - name: check-buckets
      resource: aws.s3
```
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output

**Additional context**

Dockerfile:

FROM cloudcustodian/c7n:0.8.46.1
--
  |  
  | LABEL description="for BMX" \
  | org="Cloud Project" \
  | maintainer="lcx"
  | USER root
  |  
  | # General OS Update and Tools ------------------------------------
  | RUN apt-get update -y && apt-get upgrade -y \
  | && apt-get install -y git wget vim unzip zip jq awscli
  |  
  | # Python modules -------------------------------------------------
  | COPY requirements.txt /tmp/requirements.txt
  | RUN pip3 --disable-pip-version-check --no-cache-dir \
  | install -r /tmp/requirements.txt \
  | && rm /tmp/requirements.txt
  |  
  | #
  | # begin update c7n with s3-public-block version from master branch
  | #
  | RUN  apt-get install -y gcc \
  | && apt-get install -y make
  | RUN  git clone https://github.com/cloud-custodian/cloud-custodian.git \
  | && cd cloud-custodian \
  | && git checkout 2bc598f994c389a145b2fb00b104627114461ada \
  | && make \
  | && make install \
  | && mv /usr/local/lib/python3.7/site-packages/c7n /usr/local/lib/python3.7/site-packages/c7n.old \
  | && tar czf - c7n \| ( cd /usr/local/lib/python3.7/site-packages/ && tar xzf - )

**Comment by kapilt** [comment]
first this seems to be using some commit off trunk. the s3 resource public filter isn't in a release (only the account level filter). its currently being rewritten in a separate pr #5520, and its syntax will change (no compatibility considerations given it wasn't in a release).

**Comment by JohnHillegass** [comment]
Hey, thanks for reporting this! I will make sure to investigate the issue as part of the #5520 update.

**Comment by kapilt** [comment]
its also interesting re-use of our docker images as a base image... this is going to break with the latest images we're publishing which are significantly more minimal using the distro less container. given #5560  it makes me wonder if we just need to start publishing the distro less ones as slim variants, and stick to a deb/ubuntu base for the existing images.

**Comment by hammer2j2** [comment]
Ah, yes.  That's a good call-out about the docker build we have - this was strung together to test this new feature, normally we just have 
```
  | FROM cloudcustodian/c7n:0.8.46.1
  |  
  | LABEL description="for BMX"
  | org="Cloud Project"
  | maintainer="lcx"
  | USER root
  |  
  | # General OS Update and Tools ------------------------------------
  | RUN apt-get update -y && apt-get upgrade -y
  | && apt-get install -y git wget vim unzip zip jq awscli
  |  
  | # Python modules -------------------------------------------------
  | COPY requirements.txt /tmp/requirements.txt
  | RUN pip3 --disable-pip-version-check --no-cache-dir
  | install -r /tmp/requirements.txt
  | && rm /tmp/requirements.txt
```

**Comment by hammer2j2** [comment]
Not sure if it's related but we also get these strange access denied errors, which are for buckets we don't have:

s3-role-restrict
commvault-storage

I.e., `2020-04-08 14:35:34,934 - custodian.s3 - WARNING - Bucket:s3-role-restrict unable to invoke method:get_bucket_website error:Access Denied `

Is this test code?  We are on the master branch.
Thanks.

**Comment by kapilt** [comment]
those bucket names are whats being returned by the s3 api for your account. the warnings are about custodian being unable to access them due to permissions.

I'm looking at revamping the docker builds to restore the deb/ubuntu as the base for the standard ones.

**Comment by hammer2j2** [comment]
these errors (same bucket names) occur in different accounts.  I’ve tried two so far.  We don’t have these buckets.  Maybe it’s picking up some x-account share.
