### ISSUE TITLE
Cannot set Owners for aws.ami resource

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#5568]
**Describe the bug**
My intent is to search all canonical public AMIs and return the most recent ones that match my filter. 

I'm unable to set the `Owners` key for `aws.ami`.

I'm also unable to find documentation on `Owners` key.

**To Reproduce**

Run policy

```
custodian-cask run -c test-policies/ami-new.yml --dryrun -s out --region us-east-1 --verbose --cache-period 0
```

**Expected behavior**
Search not my account but canonical's account to find the latest AMI

**Background (please complete the following information):**
 - Policy: [please exclude any account/sensitive information]
```yaml
policies:
  - name: ami-latest-canonical
    resource: ami
    query:
      # canonical owner
      Owners: ["099720109477"]
    filters:
      - type: image-age
        days: 60
        op: lte
```

```
2020-04-08 20:30:00,023: custodian.commands:ERROR invalid policy file: /home/custodian/ami-new.yml error: Failed to validate policy ami-new 
 Error on policy:ami-new resource:ami
{'Owners': ['099720109477']} is not of type 'array'

Failed validating 'type' in schema[14]['allOf'][0]['properties']['query']:
    {'items': {'type': 'object'}, 'type': 'array'}

On instance['query']:
    {'Owners': ['099720109477']}
2020-04-08 20:30:00,024: custodian.commands:ERROR Found 1 errors.  Exiting.
```

**Additional context**

**Comment by kapilt** [comment]
query is an array of mappings for histerical raisons

```yaml
policies:
  - name: ami-latest-canonical
    resource: ami
    query:
      # canonical owner
      - Owners: ["099720109477"]
    filters:
      - type: image-age
        days: 60
        op: lte
```

**Comment by rb-nr** [comment]
Used `custodian-cask` which uses the latest custodian and when I use the same policy you posted, it's only grabbing my own AMIs instead of the ones owner by the one defined in the `Owners` array

**Comment by nitrocode** [comment]
Used `custodian-cask` which uses the latest custodian and when I use the same policy you posted, it's only grabbing my own AMIs instead of the ones owner by the one defined in the `Owners` array
