### ISSUE TITLE
Permisson issue on /home/custodian

### ISSUE THREAD

**Issue by sl-erictravers** [cloud-custodian/cloud-custodian#5581]
Hello,

I have an issue with CircleCi. 
It seems that CircleCi cannot create directory in /home/custodian anymore. 
(It creates a 'project' directory to checkout the code inside).

It works 25days before.

Is it a regression or something that you changed on purpose ? 

EDIT: 

In circleCI, I fixed the version with 0.8.46.1, and my workflow is now fully working.
Latest image has a permission issue on custo hom dir.

Thank you.

REgards,

Eric

**Comment by kapilt** [comment]
can you share what commands you were using to running the container. we had switched out a few weeks ago to distroless based containers, for some significant size savings. i'm looking to switch the images back to standard linux distro containers in #5571 and publish the distroless containers as a separate set of images for compatibility with the various odd ways people were using the containers.

it sounds like for your usage, quick work around is to volume mount /home/custodian but that's a guess as there's really not enough context here around the issue your facing or your usage.

**Comment by kapilt** [comment]
the other option is to just pass a --cache=path_to_volume_mount when running

**Comment by kapilt** [comment]
fwiw, i am classifying this as a regression, there's a fix and some more comprehensive changes in #5571 to avoid in the future (functional smoke test on images), and a regression test .. i'll note that this just affected cache usage, not policy execution, and the work around per previous comments is trivial (volume mount /home or pass different cache path).. but again lacking any context

**Comment by sl-erictravers** [comment]
hey, I dont have the exact command launched, because it's somthing that CircleCi is doing by itself, when I specify the "checkout" action. 

It seems it creates the "project" dir in /home/custodian then it checkout my repository inside this folder.

The error appears when it tries to create the folder. 

Using an older Custo image, it works.

**Comment by kapilt** [comment]
so the default :latest images have switched back to an ubuntu distro instead of distroless which should resolve (switch back was for other reasons, re compatibility around existing user workflows). I've revamped some our docker building, so we now have some lightweight functional tests around using the docker images as well (tests/test_docker.py), and also captured this case (not mounting /home/custodian) as a unit test. trying to get it all documented up, and rolled out on build infrastructure this week.
