### ISSUE TITLE
Can I use c7n-mailer on AWS for Azure rules?

### ISSUE THREAD

**Issue by leoblanc** [cloud-custodian/cloud-custodian#5586]
Hi, we are using CloudCustodian on AWS: we have deployed c7n-mailer and some CloudCustodian rules (using Lambda functions) and everything works as expected: the rules are executed and they push the notifications to the AWS SQS queue. Then, the AWS Lambda function for the c7n-mailer pulls the items and sends the email notifications correctly. So far so good.

Now I want to also use CloudCustodian on Azure (for the same organization). I know that I can deploy c7n-mailer on Azure but, can I "reuse" the c7n-mailer already deployed on AWS? In other words, if I create some Azure rules as Azure Functions, could they be able to push the notifications to the SQS queue in AWS? (by configuring the transport to use SQS). Or am I forced to deploy c7n-mailer again in Azure for the Azure rules?

Thank you very much in advance!

**Comment by kapilt** [comment]
nutshell, you should do a separate deployment of mailer.. it keeps functions smaller to not cross install extra cloud provider sdks, and gives better resilience instead of creating dependencies across providers.

**Comment by leoblanc** [comment]
Thanks for your info!
