### ISSUE TITLE
Custodian as Lambda function with AWS Cloudformation

### ISSUE THREAD

**Issue by RizwanDG** [cloud-custodian/cloud-custodian#5619]
Hi,

I have launched a Custodian policy as a Lambda function in my AWS account. So the functionality of my policy is to delete the Cloudformation stacks which are older than 7 days and it will also delete the stacks which do not have a specific tag which I'll be describing in my policy. I have written the policy in such a way that it will be triggered on a particular day using Cloudwatch rule.
The issue I was facing was certain stacks would go to 'DELETE FAILED' state saying that the custodian lambda function's IAM Role does not have enough permissions. So, I provided all the permissions for the IAM Role and the stack deletion was successful. 
But still certain stacks were not detected by the custodian policy and in 'DELETE FAILED' state which were older than 7 days and it did not have the specific tag which I have mentioned in the policy. When I checked those stacks they were not triggered by custodian and they were older than 7 days and did not have the tag.
Could you please let me know why it is not detecting my stacks ?
I am attaching the policy which I'm using with this issue.
[custodian.txt](https://github.com/cloud-custodian/cloud-custodian/files/4504360/custodian.txt)

Thank you!

**Comment by kapilt** [comment]
CloudFormation executes commands/apis on stacks with the permissions of the invoking user, so if the custodian role does not have permissions to do the api calls for deleting the resources in the stack you'll see that failure. Same as if a user without iam create user tried to create a user with the stack. fundamentally this is a question of updating/fixing the iam permissions for your custodian execution role to reflect on the cfn stack provisioned resources it will be deleting.

**Comment by RizwanDG** [comment]
Hi Kapil,
As cloudformation deals with creation and and deletion of multiple resources I have provided Full Admin access for the custodian lambda execution role.
My custodian policy succeeded in deleting the recent stacks , but failed to delete the stacks which are older , like from previous year. So, if my policy is able to delete some stacks, then we can confirm that everything is fine with IAM permissions.

So since I have provided a filter to delete the stacks older than 7 days it should be deleting the ones from last year as well. Any suggestions why this is happening?

**Comment by kapilt** [comment]
what's the error message in the policy lambda logs? is delete protection enabled on the stack?

**Comment by RizwanDG** [comment]
So the delete protection is disabled, but the policy lambda logs has thrown an error,
' ClientError: An error occurred (Throttling) when calling the DeleteStack operation (reached max retries: 4): Rate exceeded '

**Comment by RizwanDG** [comment]
Hi Kapil,

Any updates on this issue?

**Comment by kapilt** [comment]
we've moved to resource group tagging api here which should resolve as that code path has retries builtin.
