### ISSUE TITLE
rds-cluster-snapshot

### ISSUE THREAD

**Issue by pendyalal** [cloud-custodian/cloud-custodian#5631]
**Is your feature request related to a problem? Please describe.**
No, It's an enhancement

**Describe the solution you'd like**
Need Cross-account filters on AWS RDS Cluster Snapshots.

**Describe alternatives you've considered**
I modified custodian code until it gets fixed.

**Additional context**

from c7n.filters import CrossAccountAccessFilter

@RDSClusterSnapshot.filter_registry.register('cross-account')
class CrossAccountAccess(CrossAccountAccessFilter):

    permissions = ('rds:DescribeDBClusterSnapshotAttributes',)

    def process(self, resources, event=None):
        self.accounts = self.get_accounts()
        results = []
        with self.executor_factory(max_workers=2) as w:
            futures = []
            for resource_set in chunks(resources, 20):
                futures.append(w.submit(
                    self.process_resource_set, resource_set))
            for f in as_completed(futures):
                if f.exception():
                    self.log.error(
                        "Exception checking cross account access\n %s" % (
                            f.exception()))
                    continue
                results.extend(f.result())
        return results

    def process_resource_set(self, resource_set):
        client = local_session(self.manager.session_factory).client('rds')
        results = []
        for r in resource_set:
            attrs = {t['AttributeName']: t['AttributeValues']
             #for t in client.describe_db_cluster_snapshot_attributes(
             for t in self.manager.retry(
                client.describe_db_cluster_snapshot_attributes,
                DBClusterSnapshotIdentifier=r['DBClusterSnapshotIdentifier'])[
                    'DBClusterSnapshotAttributesResult']['DBClusterSnapshotAttributes']}
            r['c7n:attributes'] = attrs
            shared_accounts = set(attrs.get('restore', []))
            delta_accounts = shared_accounts.difference(self.accounts)
            if delta_accounts:
                r['c7n:CrossAccountViolations'] = list(delta_accounts)
                results.append(r)
        return results

**Comment by kapilt** [comment]
thanks, I'll see if can get this converted into a pr with some tests.

**Comment by pendyalal** [comment]
sure, Thank you, Kapilt
