### ISSUE TITLE
Add support for elasticsearch filter type config-compliance

### ISSUE THREAD

**Issue by charles545587** [cloud-custodian/cloud-custodian#5635]
**Is your feature request related to a problem? Please describe.**
When trying to write a policy to use the config managed rule "elasticsearch-encrypted-at-rest" there is no filter for the type: config-compliance

**Describe the solution you'd like**
Added support for the filter type: config-compliance for the elasticsearch resource.

**Describe alternatives you've considered**
Using c7n to create the config rule.

**Additional context**
Relates to a thread on gitter raised  @charles545587 Apr 21 16:08

aws.elasticsearch:
  filters:
  - event
  - finding
  - marked-for-op
  - metrics
  - ops-item
  - security-group
  - subnet
  - value
  - vpc

**Comment by kapilt** [comment]
yeah.. its a fairly trivial filter for custodian
```EncryptionAtRestOptions.enabled: false```

wrt to config config-compliance filter its triggered off custodian having marked the resource type metadata with the config type. there's some work in #5408 which should address on the new resources in config.

**Comment by kapilt** [comment]
its also worth noting that we discovered that config has started doing partial support for resources, ie able to define a config rule against them but not able to query them from config using selectresources.
