### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#5639]
**Is your feature request related to a problem? Please describe.**
I'd like to install custodian using homebrew on osx

**Describe the solution you'd like**
```
brew install c7n
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kapilt** [comment]
sounds good to me, can probably use `brew edit awscli` as a reference

**Comment by kapilt** [comment]
https://docs.brew.sh/Formula-Cookbook

**Comment by mithun** [comment]
Please consider maintaining an official [tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap). This might make it easier to control releasing a new version, for e.g., a new version is released to pypi, dockerhub and the brew-tap at the same time.

The `custodian-cask` binary might be a good first candidate to distribute via brew-cask.

**Comment by kapilt** [comment]
@mithun its unclear if the custodian-cask binary is a good candidate since it depends on docker, while most people are installing docker via docker desktop on Mac, and its unclear if they conflict.. if you have time to research that might help to validate if its a good target.

**Comment by mithun** [comment]
@kapilt It is possible to use a custom [`Requirement`](https://rubydoc.brew.sh/Requirement.html) in the formula to detect if `docker`(cli) is installed.

If an installation is not detected:
* For macOS, a docker _cask_ dependency can be added
* For other supported OSes, raise an error informing the user to install Docker for their OS.

**Comment by nitrocode** [comment]
I'm a fan of the `custodian-cask` but every time I've used it, it downloads the latest update which leads me to believe that it is bleeding edge.

If this method was used to create the `custodian` homebrew formula, I'd like to be able to pin it down to a released version.

**Comment by mithun** [comment]
>I'm a fan of the custodian-cask but every time I've used it, it downloads the latest update which leads me to believe that it is bleeding edge.

According to the [docs](https://cloudcustodian.io/docs/tools/cask.html#run), you should be able to set the `CUSTODIAN_IMAGE` environment variable to pin it to a specific version.

**Comment by mithun** [comment]
@kapilt I've started an initial custom tap at https://github.com/mithun/custodian-homebrew-tap that can be transferred to the `cloud-custodian` org

**Comment by nitrocode** [comment]
Would the pin have to be declared in my `~/.*rc` file?

What are the benefits of a custom tap vs putting it in homebrew directly?

**Comment by kapilt** [comment]
> I'm a fan of the `custodian-cask` but every time I've used it, it downloads the latest update which leads me to believe that it is bleeding edge.
> 

actually we just switched `:latest` image alias to point to the last release since 0.9.1

so custodian-cask by default will use releases ..    `:dev` alias now points to trunk

**Comment by kapilt** [comment]
this seems like a useful tool in this regard https://github.com/tdsmith/homebrew-pypi-poet

**Comment by mithun** [comment]
> https://github.com/tdsmith/homebrew-pypi-poet

I don't think this tool is required. We can essentially run `pip install c7n` via `homebrew`. See: https://github.com/mithun/custodian-homebrew-tap/blob/master/Formula/c7n.rb
