### ISSUE TITLE
c7n-mailer docker image release versions so it can be pinned

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#5646]
**Describe the bug**
I can pin down custodian using `docker pull cloudcustodian/c7n:0.8.45.4` but I cannot pin down the custodian mailer. I used to be able to do this for the custodian mailer version `0.5.7`.

**To Reproduce**

```
# for custodian
docker pull cloudcustodian/c7n:0.8.45.4
# for custodian mailer
docker pull cloudcustodian/c7n:0.5.7
```

**Expected behavior**
Container is downloaded according to the released version

**Additional context**
N/A

**Comment by kapilt** [comment]
so thats not the mailer image re second image, the mailer image tags are not by mailer version but by git repo tag which is the custodian version. 

there's a few changes to this coming with the next release. nutshell there will be daily images that can be used for pinning, latest will be an alias to the last release, and dev will be trunk build.

**Comment by kapilt** [comment]
fwiw the image matrix we're publishing is current listed here https://github.com/cloud-custodian/cloud-custodian/pull/5617

**Comment by kapilt** [comment]
our current build matrix, all images are built out of ci, latest now points to last release. 
```
|name|label|frequency|mutability|testing|
|----|-----|---------|----------|-------|
|c7n |latest|release|mutable|light-functional|
|c7n |0.9.1|release|immutable|light-functional|
|c7n |nightly|daily|mutable|functional|
|c7n |2020-04-01|daily|immutable|functional|
|c7n |dev|per-commit|mutable|light-functional|
|c7n |distroless-dev|per-commit|mutable|light-functional|
|c7n |distroless-latest|release|mutable|functional|
|c7n |distroless-2020-04-01|daily|immutable|functional|
|c7n |distroless-0.9.1|release|immutable|light-functional|
```

**Comment by nitrocode** [comment]
Ah ok so c7n-mailer can now be pinned using the same versions as custodian. Perfect. Thank you

**Comment by nitrocode** [comment]
Wait but this has a different version set for c7n-mailer as `0.6.0` ?

https://pypi.org/project/c7n-mailer/#history
