### ISSUE TITLE
Auto tagging on DMS endpoint creation

### ISSUE THREAD

**Issue by classickar** [cloud-custodian/cloud-custodian#5661]
**Is your feature request related to a problem? Please describe.**

Auto tagging is correctly not suppoted for DMS endpoint and throws Schema error.

 Error on policy:dms-Endpoints-autotag-user resource:dms-endpoint
{'type': 'auto-tag-user', 'update': True, 'tag': 'User'} is not valid under any of the given schemas

Failed validating 'anyOf' in schema[49]['allOf'][1]['properties']['actions']['items']:
    {'anyOf': [{'$ref': '#/definitions/resources/aws.dms-endpoint/actions/delete'},
               {'$ref': '#/definitions/actions/aws.invoke-lambda'},
               {'$ref': '#/definitions/actions/aws.invoke-sfn'},
               {'$ref': '#/definitions/resources/aws.dms-endpoint/actions/modify-endpoint'},
               {'$ref': '#/definitions/actions/aws.notify'},
               {'$ref': '#/definitions/actions/aws.post-finding'},
               {'$ref': '#/definitions/actions/aws.post-item'},
               {'$ref': '#/definitions/actions/aws.put-metric'},
               {'$ref': '#/definitions/actions/aws.webhook'},
               {'enum': ['notify',
                         'webhook',
                         'modify-endpoint',
                         'delete',
                         'invoke-lambda',
                         'put-metric',
                         'post-finding',
                         'invoke-sfn',
                         'post-item']}]}

On instance['actions'][0]:
    {'tag': 'User', 'type': 'auto-tag-user', 'update': True}
2020-04-27 18:31:19,984: custodian.commands:ERROR Found 1 errors.  Exiting.

**Describe the solution you'd like**
Support Auto tagging on DMS endpoint creation

**Describe alternatives you've considered**

**Additional context**

**Comment by JohnHillegass** [comment]
Thanks for submitting. I'll start working on it briefly. Are you just looking for the auto-tag functionality? What about generic tag/untag actions?

**Comment by classickar** [comment]
auto-tag functionality will help solving my current issue , it will be good to have generic tag/untag actions supported.

**Comment by JohnHillegass** [comment]
Hey @classickar after looking into this, it does seem to be implemented already in the trunk and will be included in the next custodian release. Can you confirm which version you are using? Did you install using pip? The next version should be out this week but if you need this immediately, you could try a developer install https://cloudcustodian.io/docs/developer/installing.html in the mean time.

**Comment by kapilt** [comment]
if you want to try out trunk, use docker ...

```docker run --rm cloudcustodian/c7n:dev```

see the docs for more examples.

**Comment by classickar** [comment]
Thank you @JohnHillegass @kapilt for helping with the fixes and releasing the new version.
