### ISSUE TITLE
aws - Allow config-compliance filter on all resource types supported by CloudFormation

### ISSUE THREAD

**Issue by mithun** [cloud-custodian/cloud-custodian#5666]
**Background**

AWS Config [supports](https://docs.aws.amazon.com/config/latest/developerguide/evaluate-config_develop-rules_nodejs.html#creating-custom-rules-for-additional-resource-types) custom rules that evaluate _Additional Resource Types_.

_Additional Resource Types_ a types of resources that are **not** yet [supported by AWS Config](https://docs.aws.amazon.com/config/latest/developerguide/resource-config-reference.html), but are valid [AWS CloudFormation Resource Types](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html).

**Use Case**

I'm looking at a use-case where we will be deploying various AWS Config custom rules that are, in some cases, evaluating _Additional Resource Types_. Note that these custom rules are _not managed by Custodian_. However, we will be using Custodian policies that uses [`type: config-compliance`](https://cloudcustodian.io/docs/aws/resources/aws-common-filters.html#config-compliance) filter to find resources marked as non-compliant by these custom rules.

**Feature Request**

Currently, for all resources supported by AWS Config, the Custodian `resource_type` has the appropriate `config_type` defined and therefore has the `config-compliance` filter registered.

In order to support to use-case described above, the appropriate `config_type` will need to be defined for all resources supported by AWS CloudFormation as well.

**Caveats**

* [Config Source](https://cloudcustodian.io/docs/aws/topics/config.html#config-source) would only work for _AWS Config Supported Resource Types_.
* [Config Rule](https://cloudcustodian.io/docs/aws/topics/config.html#config-rule) would only work for _AWS Config Supported Resource Types_.
* [Config Filter](https://cloudcustodian.io/docs/aws/topics/config.html#filter) would work for both _AWS Config Supported Resource Types_ and _Additional Resource Types_.

**Comment by mithun** [comment]
>In order to support to use-case described above, the appropriate config_type will need to be defined for all resources supported by AWS CloudFormation as well.

On second thought, maybe this requires a new `config_type_partial` (or similar) attribute that distinguishes between a resource that is only _partially supported_.

**Comment by kapilt** [comment]
the use case isn't entirely clear, that sounds more like an implementation aspect your describing.

ie. you saying config doesn't support something, except your planning on doing a user defined resource type.. ie. something arbitrary and custom.. how does that map to custodian? and why woud custodian support something thats only useful only for a single deployment? is your mapping of cfn to config opensource? have you thought about contributing support to custodian to do the same re mapping to custom resources?

**Comment by mithun** [comment]
>the use case isn't entirely clear

Maybe I can provide a better example:

```yaml
policies:
- name: ecs-check-using-custom-rule
  resource: aws.ecs-service
  filters:
  - type: config-compliance
    rules:
    - my-custom-ecs-config-rule
    states:
    - NON_COMPLIANT
```

In the policy above, I'm using a valid custodian resource (`aws.ecs-service`). However, the policy is not valid because `aws.ecs-service` custodian resource does not support the `config-compliance` filter since an ECS Service is not a _fully supported_ resource type by AWS Config.

However, AWS Config **does support** creating a custom rule that evaluates the resource type [`AWS::ECS::Service`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html).  See [this AWS Config documentation](https://docs.aws.amazon.com/config/latest/developerguide/evaluate-config_develop-rules_nodejs.html#creating-custom-rules-for-additional-resource-types). Particularly, the snippet:

> You can create custom rules to run evaluations for resource types not yet recorded by AWS Config. This is useful if you want to evaluate compliance for additional resource types, such as Amazon S3 Glacier vaults or Amazon SNS topics, that AWS Config doesn't currently record. For a list of additional resource types that you can evaluate with custom rules, see AWS Resource Types Reference.

It looks like custodian is deciding on whether the `config-compliance` filter is available to a resource based on [`resource_class.resource_type.config_type`](https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/filters/config.py#L126).

The `resource_class.resource_type.config_type` is currently set for each _supported_ resource listed here: https://docs.aws.amazon.com/config/latest/developerguide/resource-config-reference.html

What I'm proposing is that a new attribute `resource_class.resource_type.config_type_partial` (or similar) be introduced for resources that are listed [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html) but **not** listed [here](https://docs.aws.amazon.com/config/latest/developerguide/resource-config-reference.html). Resources with this attribute should also support the `config-compliance` filter, so that the example policy show above is valid.

Hope this helps clarify.

**Comment by kapilt** [comment]
I think your missing the part for custom resources, where you have to post all state changes, additions, deletions yourself to the config service (afaics).. its not simply a question of provisioning the rule on the custom resource. the reference to cfn, isn't about cfn supporting config, its that its using the cfn schema registry for types, and you can register custom types in there which have could refer to anything (including stuff unrelated to aws).  config needs a data pump for those.

**Comment by mithun** [comment]
>I think your missing the part for custom resources, where you have to post all state changes, additions, deletions yourself to the config service (afaics).. its not simply a question of provisioning the rule on the custom resource. the reference to cfn, isn't about cfn supporting config, its that its using the cfn schema registry for types, and you can register custom types in there which have could refer to anything (including stuff unrelated to aws). config needs a data pump for those.

What you are describing is [Record Configurations for Third-Party Resources](https://docs.aws.amazon.com/config/latest/developerguide/customresources.html). But that is not the use-case I'm referring to.

The use-case I'm referring to is [Evaluating Additional Resource Types](https://docs.aws.amazon.com/config/latest/developerguide/evaluate-config_develop-rules_nodejs.html#creating-custom-rules-for-additional-resource-types).

**Comment by kapilt** [comment]
> What you are describing is [Record Configurations for Third-Party Resources](https://docs.aws.amazon.com/config/latest/developerguide/customresources.html). But that is not the use-case I'm referring to.
> 
> The use-case I'm referring to is [Evaluating Additional Resource Types](https://docs.aws.amazon.com/config/latest/developerguide/evaluate-config_develop-rules_nodejs.html#creating-custom-rules-for-additional-resource-types).

interesting.. what sort of guarantees on liveness does this offer (ie. eta on change detection), I'm assuming its closer to 15m+ poll.. its a little unclear to be honest from the docs, ie. "not yet recorded by AWS Config." implies you have to record yourself, but in the absence of docs banging on the api to observe seems required.

wrt to support, I've added in cfn_type to resources in #5681

**Comment by mithun** [comment]
> what sort of guarantees on liveness does this offer (ie. eta on change detection)

There is no liveness guarantee. Rules created with these types of resources are "triggered at a periodic frequency" (https://docs.aws.amazon.com/config/latest/APIReference/API_ConfigRule.html#config-Type-ConfigRule-MaximumExecutionFrequency)




On Apr 30, 2020, at 5:29 PM, Kapil Thangavelu <notifications@github.com> wrote:

﻿
What you are describing is Record Configurations for Third-Party Resources. But that is not the use-case I'm referring to.

The use-case I'm referring to is Evaluating Additional Resource Types.

interesting.. what sort of guarantees on liveness does this offer (ie. eta on change detection), I'm assuming its closer to 15m+ poll.. its a little unclear to be honest from the docs, ie. "not yet recorded by AWS Config." implies you have to record yourself, but in the absence of docs banging on the api to observe seems required.

wrt to support, I've added in cfn_type to resources in #5681

**Comment by kapilt** [comment]
okay so this isn't really different then a periodic policy except now we have to contend with config's janky idiosyncratic bespoke attribute normalization... which frankly is a problem sans verification per resource.  generally speaking custodian attempts to normalize that so that policies are isomorphic on execution mode, instead of having lockin on config. 

afaics the primary benefit for supporting this is groups that want to use config's dashboards which are pretty basic? else a custodian periodic policy using cwe or a cron job is effectively doing the same and provides choice of dashboard re sechub, cloudwatch, grafana, etc and supports centralization much better then config. ie c7n-org on a cron job/container is going to be simpler to operate/update. ie. the value chain seems to be on being able to claim use of config even though its not really the best solution here afaics. could you clarify what you see as the benefit? 

wrt to normal config support and these partially supported resources. does config maintain history timelines on these resources? can they be queried via select resource config? 

the config rule mode would need updating on provisioning for these config fake/partially supported resources, that have nothing to do with the rest of config. at min requiring a periodicity specification on the mode.

you also mentioned using config rules not implemented by custodian, could you clarify what their doing? i'm just curious why not implement them in custodian, as i haven't seen any config rules that weren't easier to express (20x code reduction) when implemented in custodian.

**Comment by kapilt** [comment]
> The use-case I'm referring to is [Evaluating Additional Resource Types](https://docs.aws.amazon.com/config/latest/developerguide/evaluate-config_develop-rules_nodejs.html#creating-custom-rules-for-additional-resource-types).

its worth pointing how bad the documentation here is, the example resource, a glacier vault..  isn't even supported as resource by CloudFormation 🤷 

as additional example, config says they support aws secrets manager in the docs (https://docs.aws.amazon.com/config/latest/developerguide/resource-config-reference.html#awssecretsmanager) , but the aws sdks haven't been updated to denote that as a supported resource type 😭 https://github.com/boto/botocore/blob/develop/botocore/data/config/2014-11-12/service-2.json#L5972

**Comment by mithun** [comment]
>okay so this isn't really different then a periodic policy

Correct.

>wrt to normal config support and these partially supported resources. does config maintain history timelines on these resources? can they be queried via select resource config?

No. Config does not maintain configuration history, timelines or support querying these resources since they are _partially supported_ and not first-class services in Config.

>the config rule mode would need updating on provisioning for these config fake/partially supported resources, that have nothing to do with the rest of config. at min requiring a periodicity specification on the mode.

Actually, if you look at the _caveats_ listed in the original request, the only thing that would work in this scenario is the `config-compliance` filter. The config-rule mode and config-source would not work for these resource types.

>you also mentioned using config rules not implemented by custodian, could you clarify what they're doing? i'm just curious why not implement them in custodian, as i haven't seen any config rules that weren't easier to express (20x code reduction) when implemented in custodian.

The initial use-cases we are looking at is to evaluate a resource's compliance based on some complex relationship with multiple other resources (_resource hopping_?). For e.g., Determine if a glue-dev-endpoint/rds-instance lives in a private subnet by examining the endpoint->subnet->route-table relationship and configurations.

One other initial use-case is what is listed in #5671, where the configuration of a resource needs to be examined based on some other configuration within the same resource.

Essentially, what this feature request is asking for is to support _more_ number of resources to be able to use the `config-compliance` filter. It also serves as an escape hatch to offload compliance evaluation for complex scenarios that are either (a) not currently supported by Custodian or (b) not really recommended for a Custodian policy implementation since it would serve only a single customer.

**Comment by mithun** [comment]
>its worth pointing how bad the documentation here is, the example resource, a glacier vault.. isn't even supported as resource by CloudFormation 🤷

I agree. There is a lot left to be clarified in the documentation.

**Comment by kapilt** [comment]
> > its worth pointing how bad the documentation here is, the example resource, a glacier vault.. isn't even supported as resource by CloudFormation 🤷
> 
> I agree. There is a lot left to be clarified in the documentation.

this goes beyond just docs issues.. to broken service guarantees.. ie. what's even worse with secrets manager, even though its documented as **fully** supported you can't query for it using select resource config.. its showing up in the *config* console..  but querying for it via select resources for even a basic query like

```
select
  configuration,
  configurationItemCaptureTime,
  configurationItemStatus
where
  resourceType = 'AWS::SecretsManager::Secret'
```

will turn up no results. so it's really unclear exactly what a fully supported config resource even means, if the basics are arbitrarily broken.

**Comment by kapilt** [comment]
> 
> > the config rule mode would need updating on provisioning for these config fake/partially supported resources, that have nothing to do with the rest of config. at min requiring a periodicity specification on the mode.
> 
> Actually, if you look at the _caveats_ listed in the original request, the only thing that would work in this scenario is the `config-compliance` filter. The config-rule mode and config-source would not work for these resource types.
> 

why wouldn't we also want to support a config rule in custodian here for these partially resources, ie thats the basis for these partially config supported resources.

> > you also mentioned using config rules not implemented by custodian, could you clarify what they're doing? i'm just curious why not implement them in custodian, as i haven't seen any config rules that weren't easier to express (20x code reduction) when implemented in custodian.
> 
> The initial use-cases we are looking at is to evaluate a resource's compliance based on some complex relationship with multiple other resources (_resource hopping_?). For e.g., Determine if a glue-dev-endpoint/rds-instance lives in a private subnet by examining the endpoint->subnet->route-table relationship and configurations.
> 

cool, I think we can probably add a network reachability filter to custodian, we already do one ho evals on all network attached resources to subnets. thats probably best discussed in a separate issue though.

> One other initial use-case is what is listed in #5671, where the configuration of a resource needs to be examined based on some other configuration within the same resource.

could you add some concrete examples to that issue, it sounds like a value filter thats just comparing against a resource attribute instead of a policy value.

> 
> Essentially, what this feature request is asking for is to support _more_ number of resources to be able to use the `config-compliance` filter. It also serves as an escape hatch to offload compliance evaluation for complex scenarios that are either (a) not currently supported by Custodian or (b) not really recommended for a Custodian policy implementation since it would serve only a single customer.


we generally the safety valve support those by using value_from and maintain an external data dictionary in s3 etc.

wrt to this feature request afaics it should be both config-rule and compliance-filter for resources with cfn types defined. ie the later implies the former can be defined, and there's no reason not to enable both afaics.

**Comment by mithun** [comment]
>why wouldn't we also want to support a config rule in custodian here for these partially resources, ie thats the basis for these partially config supported resources.

We cannot. Partially supported resources are **not** recorded by AWS Config. The [config-rule implementation](https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/policy.py#L749) relies on the resource being a `configurationItem` - which partially supported resources are **not**.

>we generally the safety valve support those by using value_from and maintain an external data dictionary in s3 etc.

The `value_from` doesn't work really well with dynamic values, or values that change very often. It just puts the responsibility of keeping the data-dictionary up to date on a different process.

>wrt to this feature request afaics it should be both config-rule and compliance-filter for resources with cfn types defined. ie the later implies the former can be defined, and there's no reason not to enable both afaics.

Like I mentioned above. Partially supported resources are not recorded by AWS Config and are not considered as configurationItems. This means we cannot trigger a config-rule execution based on changes to a resource, and we cannot query AWS Config for any information regarding these partially supported resources.

**Comment by mithun** [comment]
>could you add some concrete examples to that issue, it sounds like a value filter thats just comparing against a resource attribute instead of a policy value

The use-case defined in #5671 wants to be able to use the value filter type where _both_ the `key` and `value` are JMESPath expressions.

**Comment by kapilt** [comment]
> > why wouldn't we also want to support a config rule in custodian here for these partially resources, ie thats the basis for these partially config supported resources.
> 
> We cannot. Partially supported resources are **not** recorded by AWS Config. The [config-rule implementation](https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/policy.py#L749) relies on the resource being a `configurationItem` - which partially supported resources are **not**.
> 

ic, thanks for clarifying so it really is a different mode, config-poll-rule thats akin to the existing periodic in execution, except also posting to config. 

> > we generally the safety valve support those by using value_from and maintain an external data dictionary in s3 etc.
> 
> The `value_from` doesn't work really well with dynamic values, or values that change very often. It just puts the responsibility of keeping the data-dictionary up to date on a different process.
> 

value_from can pull from a url, ie its no different then hitting a rest endpoint for a data dictionary. 

> > wrt to this feature request afaics it should be both config-rule and compliance-filter for resources with cfn types defined. ie the later implies the former can be defined, and there's no reason not to enable both afaics.
> 
> Like I mentioned above. Partially supported resources are not recorded by AWS Config and are not considered as configurationItems. This means we cannot trigger a config-rule execution based on changes to a resource, and we cannot query AWS Config for any information regarding these partially supported resources.

if your using this config capability to push evaluations in, its trivial to have custodian do the same.

**Comment by kapilt** [comment]
> > could you add some concrete examples to that issue, it sounds like a value filter thats just comparing against a resource attribute instead of a policy value
> 
> The use-case defined in #5671 wants to be able to use the value filter type where _both_ the `key` and `value` are JMESPath expressions.

thats not what I read in #5671 it would be good to file a separate issue with example for that use case.

**Comment by mithun** [comment]
>so it really is a different mode, config-poll-rule thats akin to the existing periodic in execution, except also posting to config

I agree. But I think this new mode should be a different feature.

>value_from can pull from a url, ie its no different then hitting a rest endpoint for a data dictionary.

Good point.

>thats not what I read in #5671 it would be good to file a separate issue with example for that use case.

You are right. I misread #5671 as well. I'll open a new issue.
