### ISSUE TITLE
Azure: webhook returning 400

### ISSUE THREAD

**Issue by tomarv2** [cloud-custodian/cloud-custodian#5670]
I am testing webhook action for azure and was following this example: https://gist.github.com/aluong/acebbd1691b4375e5e0d02dde9cd040b

```
policies:
  - name: auto-owner-storage-account
    resource: azure.storage
    mode:
      type: azure-event-grid
      events: [{
          resourceProvider: 'Microsoft.Storage/storageAccounts',
          event: 'write'
        }]
    filters:
      - "tag:Owner": null
    description: |
      Tag all new StorageAccounts with the 'Owner email' tag.
    actions:
      - type: auto-tag-user
        tag: Owner
      - *notify
      - type: webhook
        url: https://c7ntest1.azurewebsites.net/api/HttpTrigger?code=abc==
        batch: false
        method: POST
        body: >
          {
            "PolicyName": "policy.name"
            "PolicyDescription": "policy.location"
            "Resource": "policy.type"
          }
```

Error:
```
POST got response 400 with URL https://c7ntest1.azurewebsites.net/api/HttpTrigger?code=abc==
```

If I do a curl it works:

```
curl --header "Content-Type: application/json" \
    --request POST \
    --data '{"PolicyName":"demo-policy", "PolicyDescription":"demo policy", "Resource": "demo resource"}' \
  https://c7ntestxxxxx.azurewebsites.net/api/HttpTrigger?code=xxxxxx==
```

Any pointers? @aluong @stefangordon

**Comment by tomarv2** [comment]
updated policy to this:

```
        batch: true
        method: POST
        body: >
          {      
            PolicyName: 'policy.name'
            PolicyDescription: 'policy.name'
            Resource: 'policy.name'   
```

it's returning 200 but looking at the `Application Insights` variables are not getting values.

<img width="532" alt="Screen Shot 2020-04-29 at 1 12 25 AM" src="https://user-images.githubusercontent.com/11890959/80574358-85333400-89b6-11ea-87d2-c13696f5b4ae.png">

**Comment by stefangordon** [comment]
I find using https://webhook.site/ is very convenient for testing and debugging these.

There should not be any quotes of any sort on the values in your JMESPath query.  `policy.name` and `resource.name` should work.  

Or just put `policy` or `resource` to get the full element and see the fields.

**Comment by tomarv2** [comment]
Thanks @stefangordon it worked, closing.
