### ISSUE TITLE
Run CloudCustodian for custom events

### ISSUE THREAD

**Issue by KVInventoR** [cloud-custodian/cloud-custodian#5696]
Hi All,

Our company started migration from CloudTrail in each our account to CloudTrails in 1 base account and send all notification over sns topic.
Each account who would like to get notifications from CloudTrail should make a SQS and subscribe to SNS topic where was published CloudTrail events.
Why it's important for us? 1 Trail in account is free, we have huge amount of accounts and I am really like to use CloudCustodian.

Do you have any way to do this integration?  Like as sent custom message with data to cloudtrail or something another.

**Comment by kapilt** [comment]
I'm not even sure what your asking, your describing a rube goldberg machine, with mistaken assumptions on cost. first cloudtrail s3 logs and cloud watch events are two completely different services. custodian doesn't use the former, except for specialized things in the tools directory. custodian lambda policies use cloud watch events which doesn't even require cloudtrail actively logging in the account.
