### ISSUE TITLE
glue-catalog filter error when using "not" 

### ISSUE THREAD

**Issue by Thirugovindaraj** [cloud-custodian/cloud-custodian#5716]
**Describe the bug**
when using "not"  operator in filter condition, custodian produces the following error;
KeyError: 'CatalogId'

**To Reproduce**
Perform a dry run of a policy using -not on resource glue-catalog 

**Expected behavior**
Expected to see the filters working based on CatalogEncryptionMode and SseAwsKmsKeyId as shown in boto3 documentation:
'EncryptionConfiguration': {
            'S3Encryption': [
                {
                    'S3EncryptionMode': 'DISABLED'|'SSE-KMS'|'SSE-S3',
                    'KmsKeyArn': 'string'
                },
            ]

**Background (please complete the following information):**
 - OS:  macOS Cataline version 10.15.4
 - Python Version: 3.8.2
 - Custodian Version: 0.9.1
 - Tool Version:  N/A
 - Cloud Provider: aws
 - Policy: [please exclude any account/sensitive information]
policies:
  - name: glue-catalog-customerCMK-encryption
    resource: glue-catalog
    description:
      applicable description
    tags:
      - "tag1"
      - "tag2"
    filters:
      - not:
        - type: glue-security-config
          SseAwsKmsKeyId: alias
        - type: glue-security-config
          CatalogEncryptionMode: SSE-KMS
    actions:
      ...
```
 - Traceback: [if applicable, please exclude sensitive/account information]
2020-05-05 16:02:19,224: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/c7n/policy.py", line 291, in run
    resources = self.policy.resource_manager.resources()
  File "/usr/local/lib/python3.7/site-packages/c7n/resources/glue.py", line 516, in resources
    return self.filter_resources(self._get_catalog_encryption_settings())
  File "/usr/local/lib/python3.7/site-packages/c7n/manager.py", line 109, in filter_resources
    resources = f.process(resources, event)
  File "/usr/local/lib/python3.7/site-packages/c7n/filters/core.py", line 299, in process
    return self.process_set(resources, event)
  File "/usr/local/lib/python3.7/site-packages/c7n/filters/core.py", line 314, in process_set
    resource_map = {r[rtype_id]: r for r in resources}
  File "/usr/local/lib/python3.7/site-packages/c7n/filters/core.py", line 314, in <dictcomp>
    resource_map = {r[rtype_id]: r for r in resources}
KeyError: 'CatalogId'


 - `custodian version --debug` output

**Additional context**
Add any other context about the problem here.

**Comment by PratMis** [comment]
Same as #5702

**Comment by JohnHillegass** [comment]
@PratMis, yep possibly related!
