### ISSUE TITLE
aws - ebs-snapshot remove permission action

### ISSUE THREAD

**Issue by pendyalal** [cloud-custodian/cloud-custodian#5720]
**Is your feature request related to a problem? Please describe.**
For Shared AMI, we have remove-launch-permissions actions, in the same way can we have removing volume permissions for the specified user for EBS snapshots.

**Describe the solution you'd like**
policies:
- name: ebs-shared-snapshot
  resource: ebs-snapshot
  description: |
    Detects if a EBS is made public/shared outside org and removes volume permissions and notifies CloudTeam.

  mode:
    type: cloudtrail
    
    events:
        - source: "ec2.amazonaws.com"
          event: "ModifySnapshotAttribute"
          ids: "requestParameters.snapshotId"
    
  filters:
       - type: cross-account
         whitelist_from:
                 url: s3://accounts_test
                 format: txt
  actions:
   - remove-volume-permissions

**Comment by kapilt** [comment]
generally people use delete action here

**Comment by pendyalal** [comment]
why deleting the entire snapshot. Instead Remove permissions would be enough right.

**Comment by kapilt** [comment]
so there's all kinds of ways to approach remediation (mark-for-op workflows, notify, fix etc), it also depends as well on your backup posture, if you have many regular snaps then simply removing the problematic one is viable, and one posture I've seen before. wrt to the feature request in this issue, I think its fine, just pointing out available alternatives that may or may not work for your org.

**Comment by pendyalal** [comment]
aws - action to remove create volume permissions from a snapshot #6203
