### ISSUE TITLE
Issue with schema file when both aws and azure installed 

### ISSUE THREAD

**Issue by tarunaroraonline** [cloud-custodian/cloud-custodian#5723]
**Schema IDE Integration**
i have both c7n and c7n_azure installed, when i generate schema and configure in vscode i don't get intellisense support. I see the following error showing up in the IDE output window... 

``` 
[Error - 22:20:11] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property '$ref' of null
  Code: -32603 
```

When I uninstall c7n_azure package and generate the schema again and add it to the IDE, i start to get the intellisense support. 

on running pip freeze, i can see i have the following version of the packages installed, 
c7n==0.9.1
c7n-azure==0.7.0

**To Reproduce**
- Install c7n and c7n_azure 
- run `custodian schema --json > schema.json` 
- add
``` yaml
"yaml.schemas": {
  "./schema.json": "*yml"
},
```

**Expected behavior**
Intellisense support should work when both aws and azure packages are installed. 

**Background (please complete the following information):**
 - OS: [e.g. OSX 10.15]
 - Python Version: [e.g. python 3.8.1]
 - Custodian Version: [e.g. 0.8.46.1]
 - Tool Version: [if applicable]
 - Cloud Provider: [e.g. gcp, aws, azure]
 - Policy: [please exclude any account/sensitive information]
```yaml
policies: 
   - name: check-buckets
      resource: aws.s3
```
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output

**Additional context**

**Comment by kapilt** [comment]
afaics thats a bug in visual studio code, the schema is valid, I just did a quick unit test for all providers installed to resolve all refs and that works without issue, and the schema validates with various language json schema tools

**Comment by kapilt** [comment]
it might be worth trying again (with trunk or docker cloudcustodian/c7n:dev ) as i did make a change to normalize schema output generation across schema --json > export.json. i'll see if i can reproduce to  report upstream.

**Comment by tarunaroraonline** [comment]
Is it possible to install a pre-release version of the package for testing? I can't seem to find the pre-release version of c7n or c7n_azure on pypi for testing the fix to the above issue?

**Comment by kapilt** [comment]
re dev/pre-release ... via docker `docker run cloudcustodian/c7n:dev schema --json`or install via git.. fresh virtualenv, pip install -r requirements-dev.txt  or poetry install in root and tools/c7n_azure

**Comment by tarunaroraonline** [comment]
Sorry @kapilt  struggling to get it to setup... 

setup a new virtual env, cloned the git repo and tried to install the requirements-dev.txt, ran into this issue...

`pip3 install -r ./cloud-custodian/requirements-dev.txt --user`

Error... 

`ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /Users/xxx/repos/temp`

Trace...

```
Ignoring atomicwrites: markers 'sys_platform == "win32"' don't match your environment
Ignoring cffi: markers 'sys_platform == "linux"' don't match your environment
Ignoring colorama: markers 'sys_platform == "win32" or platform_system == "Windows"' don't match your environment
Ignoring cryptography: markers 'sys_platform == "linux"' don't match your environment
Ignoring importlib-resources: markers 'python_version < "3.7"' don't match your environment
Ignoring jeepney: markers 'sys_platform == "linux"' don't match your environment
Ignoring pycparser: markers 'sys_platform == "linux"' don't match your environment
Ignoring pywin32-ctypes: markers 'sys_platform == "win32"' don't match your environment
Ignoring secretstorage: markers 'sys_platform == "linux"' don't match your environment
Ignoring pyreadline: markers 'sys_platform == "win32"' don't match your environment
Ignoring pywin32: markers 'platform_system == "Windows"' don't match your environment
```

**Comment by kapilt** [comment]
you also need to be in the checkout directory as current working directory when install from via pip install -r requirements-dev.txt .. aka `cd cloud-custodian`

**Comment by kapilt** [comment]
we've fixed a few bugs in the azure schema from custodian in the interim. its worth retrying. if it doesnt work pls reopen.
