### ISSUE TITLE
Schema error with `aws.network-addr`

### ISSUE THREAD

**Issue by JonGilmore** [cloud-custodian/cloud-custodian#5760]
**Describe the bug**
Schema error with `aws.network-addr`. 

**To Reproduce**
Attempt to get the schema, notice `aws.network-addr` is in the list. Next, try to get the schema for `aws.network-addr`, notice that custodian throws an error.

```bash
# custodian schema
resources:
... snipped...
- aws.network-acl
- aws.network-addr
- aws.ops-item
...
# custodian schema aws.network-addr
2020-05-14 13:50:11,216: custodian.commands:ERROR aws.network-addr is not a valid resource
```

**Expected behavior**
I would expect the schema to load.

**Background (please complete the following information):**
 - OS: ubuntu 18.0.4
 - Python Version: 3.7.5
 - Custodian Version: 0.9.1
 - Tool Version: [if applicable]
 - Cloud Provider: aws
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output:

```
# custodian version
0.9.1
(venv) root@ip-10-66-150-45:/opt/stickler# custodian version --debug

Please copy/paste the following info along with any bug reports:

Custodian:   0.9.1
Python:      3.7.5 (default, Nov  7 2019, 10:50:52)
             [GCC 8.3.0]
Platform:    posix.uname_result(sysname='Linux', nodename='ip-10-66-150-45', release='5.3.0-1017-aws', version='#18~18.04.1-Ubuntu SMP Wed Apr 8 15:12:16 UTC 2020', machine='x86_64')
Using venv:  True
Docker: False
Installed:

argcomplete==1.11.1
attrs==19.3.0
boto3==1.12.47
botocore==1.15.47
docutils==0.15.2
importlib-metadata==1.6.0
jmespath==0.9.5
jsonschema==3.2.0
pyrsistent==0.16.0
python-dateutil==2.8.1
pyyaml==5.3.1
s3transfer==0.3.3
setuptools==46.2.0
six==1.14.0
tabulate==0.8.7
urllib3==1.25.9
zipp==3.1.0
```

**Additional context**

**Comment by kapilt** [comment]
thanks for filing an issue, we switched network-addr to an alias recently so that it was mainly known by elastic-ip as network-addr naming seemed to cause some confusion, but in either case both names should be resolvable in the schema command.
