### ISSUE TITLE
How to find buckets with no objetcs

### ISSUE THREAD

**Issue by karhub90** [cloud-custodian/cloud-custodian#5768]
I am relatively new to cloud custodian and would like to know if there is a way to find out s3 buckets with no objects.

**Comment by kapilt** [comment]
using a metrics filter on s3 NumberOfObjects with a missing value set to zero. note that this metric only updates once per day so also wants an age filter on the bucket creationdate for those older than a day.

**Comment by kapilt** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/dev/cloudwatch-monitoring.html
