### ISSUE TITLE
notify should include the execution trigger of the lambda

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#5772]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to differentiate between an event triggered by a cloudwatch cron and by a person manually running a lambda function. At the moment, if either triggers the lambda, there is no way to know who triggered it. It would be nice to know so it can be included directly in Slack.

**Describe the solution you'd like**
If it's possible, include what triggered the lambda directly in the SQS message, so the key can be reused within the jinja2 templates for slack, email, etc.

**Describe alternatives you've considered**
¯\_(ツ)_/¯

**Additional context**
N/A

**Comment by kapilt** [comment]
notify includes the triggering event for the lambda and can be accessed from mailer templates `{{event}}`
