### ISSUE TITLE
c7n_gcp - authentication with bearer token

### ISSUE THREAD

**Issue by C6H6** [cloud-custodian/cloud-custodian#5777]
I have python script which run custodian for multiple projects (using subprocesses). 
But I only have bearer tokens to authenticate my requests. 
Is there any method to use c7n_gcp having bearer token for authentication?

**Comment by kapilt** [comment]
c7n-org is what we recommend and support for multi-project execution. typically thats done with a service account app credentials. are you using a service account? if so you should be able to set the standard sdk metadata for it to have picked up, custodian will fallback to cli auth if its not present. I did notice on a recent pr for asset inventory support, that gcp tooling seems to have arbitrarily changed their env keys naming standards so it could be that we need to update the compatible set of keys with their current spelling of the month.
