### ISSUE TITLE
aws - trim description on serverless policies to max size 256

### ISSUE THREAD

**Issue by llange** [cloud-custodian/cloud-custodian#5786]
(Similar to #5753)

AWS lambda function descriptions have a [maximum length of 256 characters](https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-Description). Currently if a description is greater than 256, an error occurs on policy execution, not on validation:
In this case, it doesn't seem to me that this would be a breaking change considering the policies that are in violation of the max description length would not be able to be deployed and instead return an error:
```
2020-05-20 11:20:17,264: c7n_org:ERROR Exception running policy:<policy name>:<account name> error:An error occurred (ValidationException) when calling the CreateFunction operation: 1 validation error detected: Value '<description>' at 'description' failed to satisfy constraint: Member must have length less than or equal to 256
```

Policy validation should assert that the length of the policy description is less than 256 characters - maybe only when the policy is deployed with Lambda.

**Comment by kapilt** [comment]
afaics, there is zero correlation to #5753 was there something else you are referencing? or could you explain what relevance you see?

the intent is that users are using custodian validate prior to running c7n-org. serverless policy are validated on policy name length. c7n-org does not perform validation when running, though it something thats been discussed wrt to changes there.

**Comment by llange** [comment]
You're right, it's a copy/paste error, I meant #3352 ! Sorry for the error.

Same as the name length validation before serverless policy deployment, but validating the description length.

**Comment by kapilt** [comment]
gotcha, I think in this context I'm okay with just eliding/cutting the description to the max character length vs throwing a validation error, and perhaps just warning during validation. seem reasonable?

**Comment by llange** [comment]
Seems perfectly reasonable - truncation will ensure that a deploy is always possible (currently it fails) and a warning will allow those that pre-validate their policies (like us) to be alerted for action.

**Comment by IngussNeilands** [comment]
Any progress on this?

**Comment by kapilt** [comment]
merged
