### ISSUE TITLE
Reporting on Total Number of Resources

### ISSUE THREAD

**Issue by metaldart** [cloud-custodian/cloud-custodian#5795]
**A clear and concise description of what your trying to do, as well as the underlying use case.**

I am trying to write a cloudcustodian script that will achieve some action if the total number of resources exceed some arbitrary number

So for example, if the number of EC2 instances is over N, number of security groups is over X, number of RDS instances is over Y, etc. I have used jq and I know I could get the length of the top level object to find the size, but I do not see how to achieve this in CloudCustodian. Any insight is welcome, thank you!

**Comment by kapilt** [comment]
use a value filter with value_type resource_count example, for matching a set of resources if the total count is greater than 20

```
type: value
value_type: resource_count
op: greater-than
value: 20
```
