### ISSUE TITLE
Azure: Error with auto-tagging keyvault

### ISSUE THREAD

**Issue by tomarv2** [cloud-custodian/cloud-custodian#5797]
**c7n version 0.8.46.1**

**Policy:**

```
policies:
  - name: auto-owner-key-vault
    resource: azure.keyvault
    mode:
      type: azure-event-grid
      events: [{
          resourceProvider: 'Microsoft.KeyVault/vaults',
          event: 'write'
        }]
    filters:
      - "tag:Owner": null
    description: |
      Tag all new key-vault with the 'Owner Email' tag.
    actions:
      - type: auto-tag-user
        tag: Owner  
```

So, I can see the event is getting triggered but it's not tagging:

**Error:**

```
Job "Host.update_policies (trigger: interval[0:01:00], next run at: 2020-05-25 04:56:45 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/c7n_azure/container_host/host.py", line 166, in update_policies
    self.unload_policy_file(policy_path, policies_copy)
  File "/usr/local/lib/python3.7/site-packages/c7n_azure/container_host/host.py", line 263, in unload_policy_file
    removed = [policies.pop(p['name']) for p in policy_config.get('policies', [])]
  File "/usr/local/lib/python3.7/site-packages/c7n_azure/container_host/host.py", line 263, in <listcomp>
    removed = [policies.pop(p['name']) for p in policy_config.get('policies', [])]
KeyError: 'auto-owner-key-vault'
```

**Comment by h-dub** [comment]
Thank you for the report.
I verified auto owner tagging is working in the lab with current master branch with both service principal and user assigned idents. While slow, it did eventually work and apply the correct owner tag.

Let us know if you are still seeing this problem.
Thanks!

**Comment by h-dub** [comment]
This might have been fixed with 
https://github.com/cloud-custodian/cloud-custodian/pull/5737

**Comment by kapilt** [comment]
> Thank you for the report.
> I verified auto owner tagging is working in the lab with current master branch with both service principal and user assigned idents. While slow, it did eventually work and apply the correct owner tag.
> 
> Let us know if you are still seeing this problem.
> Thanks!

the issue here isn't really on the policy its on container host though

**Comment by kapilt** [comment]
> This might have been fixed with
> #5737

yeah this looks like it does address, especially if an invalid policy gets loaded.
