### ISSUE TITLE
AWS Config - type: config-compliance not working 

### ISSUE THREAD

**Issue by manitmalik** [cloud-custodian/cloud-custodian#5799]
Use Case: Use the AWS Config rule of security hub for filtering the non-compliant resources. 

Description or Steps to reproduce 
1) Identify the config rule name via security hub 
2) Create the policy using the config rule name and verify the results of the config rule via policy and security hub match each other. 

Policy sample : 
policies:
#This policy is to mark the IAM users who has keys active and not being used from more than 80 days
- name: iam-user-remediate-non-compliant
  resource: aws.iam-user
  filters:
  - type: config-compliance
    rules: [securityhub-iam-user-unused-credentials-check-nv6rb]
    states: [NON_COMPLIANT]

**Comment by kapilt** [comment]
this appears to be an issue with security hub wrt to non consistency in some cases using resourceId as an arn in some cases reporting it with a string id, and then config accepting both but not normalizing, accepting both, and then returning whatever it was passed instead of per its api contract.
