### ISSUE TITLE
Does --dry-run always exit with code 2?

### ISSUE THREAD

**Issue by migueleliasweb** [cloud-custodian/cloud-custodian#5813]
I've been testing cloud custodian for a little bit and I found that every time I add `--dry-run` to the command, it exits with code 2.

This has caused me a couple of hours of head scratching as I check if  the run was successful with the return code. 

Is this an intended behaviour? If so, I couldn't find any docs about it.

**Comment by kapilt** [comment]
--dryrun does not cause an exit code behavior change.

custodian uses exit code 2 for signaling policy failures, as one policy may fail out of the set.
https://github.com/cloud-custodian/cloud-custodian/pull/817

**Comment by kapilt** [comment]
on a side note, the use of exit code 2 here feels like a poor choice, due to potential mis identification from other uses of that value http://www.tldp.org/LDP/abs/html/exitcodes.html. unfortunately we have compatibility constraints wrt changes to it now.

**Comment by migueleliasweb** [comment]
Thanks for clarifying @kapilt !

I will double check my output for errors! Something must have failed amongst a few hundred lines of the debug output =P.

**Comment by kapilt** [comment]
for usability seems like we should log the failed policy names before we exit, pr in #5816

**Comment by migueleliasweb** [comment]
Awesome work! I just found that file with the `exit_code = 2`. That improvement will be more than welcomed! 

If I could I would approve and merge that PR myself!

**Comment by migueleliasweb** [comment]
Just thinking out loud here but in debug mode will that code halt the policy processing in the first error?

```python
    errored_policies = []
    for policy in policies:
        try:
            policy()
        except Exception:
            exit_code = 2
            errored_policies.append(policy.name)
            if options.debug:
                raise
            log.exception(
                "Error while executing policy %s, continuing" % (
                    policy.name))
```

**Comment by kapilt** [comment]
yeah debug mode is a developer thing, it drops into a post mortem debugger
session, its not really for unattended usage.

**Comment by migueleliasweb** [comment]
Got it! I actually confused the `verbose mode` with the `debug mode`... :sweat_smile:
