### ISSUE TITLE
Allow CloudCustodian to have configuration for Splunk sourcetype

### ISSUE THREAD

**Issue by willjw1** [cloud-custodian/cloud-custodian#5854]
Description of problem:
splunk_handler enforces all sourcetypes to be '_json'  If you want the sourcetype to be distinguished against all your other sourcetypes that doesn't help so much.

Describe the solution:
Take a configuration option which would then be passed down to the sourcetype in the splunk_handler call.

Describe alternatives you've considered:
I haven't, please if you have a better way of doing this, reach out.

**Comment by kapilt** [comment]
thanks for the issue and pull request, do you have a link to any documentation on source types?

**Comment by willjw1** [comment]
https://docs.splunk.com/Documentation/Splunk/8.0.4/Data/Aboutdefaultfields
https://docs.splunk.com/Documentation/Splunk/8.0.4/Data/Whysourcetypesmatter

sourcetype - The source type of an event is the format of the data input from which it originates, such as access_combined or cisco_syslog. The source type determines how your data is to be formatted. For more information on source types, see Why source types matter.

So the example is that I want to define how my aws:cloudcustodian sourcetype is defined and has certain fields available to it.  This will enable me to have the events show up with the information already categorized and indexed.

**Comment by willjw1** [comment]
@kapilt , so is that the kind of information you were looking for?  Is there something else I can provide to move this forward?
