### ISSUE TITLE
azuresubs.py dependancies

### ISSUE THREAD

**Issue by cr-gstirling** [cloud-custodian/cloud-custodian#5857]
When trying to generate a configuration file using `azuresubs.py` it appears it has a dependancy on `azure.common` python library. This common library has been deprecated and such fails to generate the required configuration file.
I continue to get the error:

```Traceback (most recent call last):
  File "azuresubs.py", line 16, in <module>
    from c7n_azure.session import Session
  File "/Users/**[removed]**/.pyenv/versions/3.6.5/lib/python3.6/site-packages/c7n_azure-0.7.2-py3.6.egg/c7n_azure/session.py", line 26, in <module>
    from azure.common.credentials import (BasicTokenAuthentication,
ModuleNotFoundError: No module named 'azure.common'
```

If I check for that package it appears to be statisfied that it exists:

```
pip install azure-common
Requirement already satisfied: azure-common in /Users/**[removed]**/.pyenv/versions/3.6.5/lib/python3.6/site-packages/azure_common-1.1.26-py3.6.egg (1.1.26)
```

Am I missing something here?

**Comment by kapilt** [comment]
seems to work fine for me in a clean virtualenv (also tried with pyenv)

ie. 
```
python3 -m venv azureenv
source azureenv/bin/activate
pip install c7n_azure
python3 tools/c7n_org/scripts/azuresubs.py
```

I did note that it installed azure-common-1.1.25 

our pypi published packages are done with fully frozen dependency trees for reproducible installs.
