### ISSUE TITLE
include alias name in kms-key for filtering and notifications

### ISSUE THREAD

**Issue by tjstansell** [cloud-custodian/cloud-custodian#5859]
**Is your feature request related to a problem? Please describe.**
I'd like the `AliasName` available in the kms-key resource information for more enriched notifications.

**Describe the solution you'd like**
We could do this one of two ways:
1. augment all the resources with the alias info when the resources are queried.  list-aliases is just one additional api call.
2. only pull in alias info if an `alias` filter is used. to use the alias in a notification, we'd need an extra no-op filter to trigger the extra info.

It seems a lot easier and simpler to go with option 1, but I know you've been leaning away from additional api calls and augmentations by default... thoughts?

**Comment by tjstansell** [comment]
Looking through the existing code, there are already two mechanisms for filtering on kms keys and aliases ... one is via the `KmsRelatedFilter` class which pulls in the kms key and augments it with a `c7n:AliasName` key if there's an alias.  The other is the `ResourceKmsKeyAlias` class which embeds the entire kms alias structure under the `KeyAlias` key.  Given that these are both pulling in alias information when requesting related kms keys, it seems appropriate that the kms key itself should just always include it's alias in the `c7n:AliasName` key to maintain some consistency with the related-keys functionality.  The `ResourceKmsKeyAlias` filter is only used by ebs and rds resources and looks like the anti-pattern these days.
@kapilt thoughts?

**Comment by tjstansell** [comment]
Honestly, now I'm thinking we should just augment the keys with an `AliasName` field instead of `c7n:AliasName`.  The colon really makes simple name filtering annoying because you have to quote it for jmespath to process it correctly: (`"key": "'c7n:AliasName'"`).  So, I think I advocate that for a `kms-key` resource type, we just use `AliasName`.

**Comment by kapilt** [comment]
thanks for the pr on this. if its just additional notification context, isn't that just a question of doing enrichment at the notification, instead of paying costs for each kms policy regardless of the usage of the alias?  costs seems mostly mitigated in the pr though by using resource manager, so they'll be catched, as you say its just one additional paginated list operation verse the fact we're already doing per key api calls to describe. agreed on c7n:aliasname being a little akward. 

probably the more salient point/question is its possible to have many aliases to a single key.

**Comment by tjstansell** [comment]
Wow. you're absolutely right.  I didn't realize you could have multiple aliases pointing to a key.  That's interesting and I guess we should just always represent it as a list... and maybe instead call it `Aliases` or `AliasNames` to indicate there's potentially more than one.  Of course, the other places in the code doesn't handle this case either. `c7n/filters.kms.py` just takes the first one.   I'll update the PR to switch to `AliasNames` as a list.

Regarding loading this in the notifier, I think there's potential usefulness to be able to filter (out) keys by their alias as well, so it seems useful to load the aliases from the resource manager.
