### ISSUE TITLE
AWS common filters page has a link pointing to 404 link

### ISSUE THREAD

**Issue by edwardmoon** [cloud-custodian/cloud-custodian#5864]
On this page: https://cloudcustodian.io/docs/aws/resources/aws-common-filters.html#aws-common-filters-config-compliance

There is a bit.ly link: https://bit.ly/2mblVpq

The bit.ly link points to a non-existent capitalone.github.io link (throws 404): http://capitalone.github.io/cloud-custodian/docs/policy/lambda.html#config-rules

I believe the bit.ly link should be updated to point to this page in the cloud custodian docs: https://cloudcustodian.io/docs/policy/lambda.html#config-rules

**Comment by kapilt** [comment]
thanks, for the bug report
