### ISSUE TITLE
Add new resource log-stream

### ISSUE THREAD

**Issue by PratMis** [cloud-custodian/cloud-custodian#5889]
**Is your feature request related to a problem? Please describe.**
Yes, we're trying to delete/clean up all log stream older than x days

**Describe the solution you'd like**
Create a resource log-stream and use age filter followed by delete action

**Describe alternatives you've considered**

**Additional context**
As per delete_log_stream(https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/logs.html#CloudWatchLogs.Client.delete_log_stream) it deletes one at a time. There are chances we might get throttled. So I'm thinking of adding a retry logic around the delete action

**Comment by PratMis** [comment]
@kapilt any tip on how to handle millions of log streams getting loaded into the cache?

**Comment by kapilt** [comment]
what's the use case/value proposition? 

this is a really painful one to deal with, it will definitely get throttled its a very large data set coming through a small straw (api rate limits). it shouldn't be a resource, it just be action on log-group, even then i'd like to understand the why first.

also this is a dupe on #5858

**Comment by PratMis** [comment]
Yea, I was thinking about the amount of data. Thinking more about it, we can use setting up retention period on log group which custodian already supports today. I'll go ahead and close this. Thanks
