### ISSUE TITLE
Mailer broken in current master - ImportModuleError: Unable to import module 'periodic': No module named 'ellipticcurve'

### ISSUE THREAD

**Issue by jantman** [cloud-custodian/cloud-custodian#5899]
**Describe the bug**

c7n_mailer fails from current master (or at least as of https://github.com/cloud-custodian/cloud-custodian/commit/26ba07ea569dfe320682f7509082fc9bead0ca4c). This appears to be an import/dependency issue in mailer.

**To Reproduce**

Provision and then run the c7n_mailer Lambda function.

**Background**

[manheim-c7n-tools 1.2.1 docker container](https://github.com/manheim/manheim-c7n-tools/releases/tag/1.2.1) running Python 3.7.3.

**Traceback**

We've modified the deployed Lambda function's ``periodic.py`` to log exception tracebacks. The result is:

```
[ERROR] 2020-06-26T14:41:04.180Z  Exception: No module named 'ellipticcurve'
Traceback (most recent call last):
File "/var/task/periodic.py", line 9, in <module>
from c7n_mailer import handle
File "/var/task/c7n_mailer/handle.py", line 21, in <module>
from .sqs_queue_processor import MailerSqsQueueProcessor
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 25, in <module>
from .email_delivery import EmailDelivery
File "/var/task/c7n_mailer/email_delivery.py", line 18, in <module>
import c7n_mailer.azure_mailer.sendgrid_delivery as sendgrid
File "/var/task/c7n_mailer/azure_mailer/sendgrid_delivery.py", line 16, in <module>
import sendgrid
File "/var/task/sendgrid/__init__.py", line 21, in <module>
from .helpers.eventwebhook import * # noqa
File "/var/task/sendgrid/helpers/eventwebhook/__init__.py", line 1, in <module>
from ellipticcurve.ecdsa import Ecdsa
ModuleNotFoundError: No module named 'ellipticcurve'
[ERROR] Runtime.ImportModuleError: Unable to import module 'periodic': No module named 'ellipticcurve'
```

**Comment by jantman** [comment]
FYI it appears that this is or was an upstream bug in the `sendgrid` package - https://github.com/sendgrid/sendgrid-python/issues/913

Supposedly this should be fixed in sendgrid==6.4.1

**Comment by jantman** [comment]
Looking into this a bit deeper, while c7n_mailer's requirements.txt specifies ``sendgrid==6.3.1``, the setup.py has ``'sendgrid>=6.1.1,<7.0.0'``. The [fix](https://github.com/sendgrid/sendgrid-python/pull/914) for the upstream bug in sendgrid-python was adding ``starkbank-ecdsa>=1.0.0`` to sendgrid's install_requires dependencies. I _believe_ that what's needed for c7n_mailer is to bump our sendgrid dependency to 6.4.1, and then add starkbank-ecdsa as a mailer dependency [in deploy.py](https://github.com/cloud-custodian/cloud-custodian/blob/b62af99171bf1163413d7f7411e4a0db8a50f27e/tools/c7n_mailer/c7n_mailer/deploy.py#L53-L54)

**Comment by kapilt** [comment]
thanks for the analysis, that seems sound, we already have some better tooling around dependency set calculations (via importlib metadata) that we use for packaging and serverless that we should also add in here instead of trying to capture a static dep graph in deploy.py

**Comment by buzz-b** [comment]
Hi, I know this is closed but I'm seeing this same failure in our Lambda script for c7n_mailer. Is it possible that these libraries are not getting updated or added to the Lambda code when the --update-lambda option is used? I've checked my virtualenv has the correct versions of sendgrid (v6.4.4) and starkbank-ecdsa (v1.0.0). 

[ERROR] Runtime.ImportModuleError: Unable to import module 'periodic': No module named 'ellipticcurve' Is there another way to update the Lambda function "cloud-custodian-mailer"
