### ISSUE TITLE
Linter error on conditions prop [VSCode]

### ISSUE THREAD

**Issue by eggei** [cloud-custodian/cloud-custodian#5904]
**Description:**
I get a linter error on the `conditions` prop. The error is not explanatory, so I can't debug. I have regenerated the schema to see anything changes, but the error persists. See the image below. (This policy is an example from the docs)

<img width="300" alt="Screen Shot 2020-06-29 at 11 52 40 AM" src="https://user-images.githubusercontent.com/52514315/86030945-26fcee80-ba03-11ea-820c-c13961601209.png">

**Steps to reproduce the behavior:**
1. Create the schema by running `custodian schema --json > schema.json`
2. Install **YAML** plugin to Visual Studio code editor
3. Specify the schema path like this in VSCode `setting.json`:
```
  "yaml.schemas": {
    "Absolute/path/to/schema.json": "*yml"
  }
```
4. Copy the policy written here and paste it to a new .yml file: https://cloudcustodian.io/docs/quickstart/advanced.html#conditional-policy-execution

5. Observe the linter error on `conditions` prop

**Expected behavior**
Not to see any linter error.

**Background (please complete the following information):**
 - OS: [e.g. OSX 10.15]
 - Python Version: [e.g. python 3.8.1]
 - Custodian Version: [e.g. 0.8.46.1]

**Comment by kapilt** [comment]
you need to upgrade your custodian version, conditions is only supported in versions 0.9+, you'll need to regenerate your schema file as well.

**Comment by eggei** [comment]
Thanks @kapilt
