### ISSUE TITLE
Error while running the script to fetch which lambda function is configured within a vpc

### ISSUE THREAD

**Issue by arjungoel** [cloud-custodian/cloud-custodian#5913]
import boto3
from botocore.exceptions import ClientError

account_number = input("Enter the account number:")
regions = ['ap-northeast-1', 'ap-southeast-1',
           'ca-central-1', 'us-east-1', 'us-east-2']

#lambda_in_vpc = []
for region_val in regions:
    session = boto3.session.Session()
    client = session.client(service_name='lambda', region_name=region_val)
    response = client.list_functions()
    #result = response.get('Functions')
    # print(result)
    for lambda_func in response['Functions']:
        result = lambda_func.get('VpcConfig')
        try:
            func = client.get_function_configuration(
                FunctionName=lambda_func['FunctionName'])
        # print(config)
            vpc = func['VpcConfig']['VpcId']
            print(f"Function:{lambda_func['FunctionName']} and vpc: {vpc}")
        except ClientError as e:
            if e.response['Error']['Code'] == 'VpcConfigNotFoundError':
                print(f"function not in vpc:{lambda_func['FunctionName']}")

**Comment by arjungoel** [comment]
I am trying to write a script to find which lambda function is configured within a vpc, disconnected from a vpc or not configured withing a vpc. But the problem is whenever the script goes into the 'except' block it is getting terminated with the following error i.e.
Traceback (most recent call last):
  File ".\list_lambda_functions.py", line 21, in <module>
    vpc = func['VpcConfig']['VpcId']
KeyError: 'VpcConfig'


can someone please find the cause of this issue. It would be really helpful as the ouput i want looks something like if the lambda is within vpc it will print:-
the lambda function 'xyz' is in vpc 'vpc-1234'
except:
the lambda function 'abc' is disconnected from a vpc []
else:
the lambda function 'efg' is not in vpc which means None.

Please tell me the cause of the error.

Thanks

**Comment by kapilt** [comment]
this repo is not an appropriate location for general questions on how to use cloud sdks. its for the development and support of the cloud custodian project - https://cloudcustodian.io

**Comment by arjungoel** [comment]
@kapilt where I will put this code in order to get my issue resolved?
