### ISSUE TITLE
Help regarding the working of Cloud Custodian

### ISSUE THREAD

**Issue by mpradeep23** [cloud-custodian/cloud-custodian#5921]
Hi All,
I need help regarding cloud custodian. I followed the documentation and set up custodian on my ec2 instance, and wrote an ec2 auto tag policy yaml file and did a custodian run. I would like to understand how is this policy implemented using custodian. The policy works fine and new ec2 instances are getting tagged with the creator name too. But I do not understand its internal working. I cannot see any lambda function created. Could someone help me understand the basic workflow? Here is the policy-

policies:
  - name: ec2-auto-tag-ownercontact
    resource: ec2
    description: |
      Triggered when a new EC2 Instance is launched. Checks to see if
      it's missing the OwnerContact tag. If missing it gets created
      with the value of the ID of whomever called the RunInstances API
    mode:
      type: cloudtrail
      role: arn:aws:iam::xxxxxxxxxx:role/cpa-role-auto-build
      events:
        - RunInstances
    filters:
     - tag:creator: absent

    actions:
     - type: auto-tag-user
       tag: creator

**Comment by wildbinaryforest** [comment]
It looks for an API call event matching RunInstances. This particular resource is outlined in cwe.py You should be able to see a lambda function in your cloudwatch logs with the name of the policy.

**Comment by mpradeep23** [comment]
> It looks for an API call event matching RunInstances. This particular resource is outlined in cwe.py You should be able to see a lambda function in your cloudwatch logs with the name of the policy.

Thanks @wildbinaryforest  for the explaination. Though I am not able to see the lambda in the cloudwatch rule. Also, how should I stop the running policy? I could not find any documentation for that.

**Comment by kapilt** [comment]
a lambda function is created with a prefix `custodian` and then the policy name.

**Comment by mpradeep23** [comment]
> a lambda function is created with a prefix `custodian` and then the policy name. and a cloud watch/event hub rule for the trail event and target that references the lambda function.

Thanks for the explanation @kapilt . I have another question- how should I stop the running policy? I could not find any documentation for that.

**Comment by kapilt** [comment]
you can use tools/ops/mugc.py in the repo to remove a deployed serverless policy

**Comment by mpradeep23** [comment]
> you can use tools/ops/mugc.py in the repo to remove a deployed serverless policy

Hey @kapilt , I am a little confused here, which repo are you referring to? Can you elaborate as to where can I find this mugc.py file?

**Comment by kapilt** [comment]
https://github.com/cloud-custodian/cloud-custodian/blob/master/tools/ops/mugc.py

**Comment by mpradeep23** [comment]
> https://github.com/cloud-custodian/cloud-custodian/blob/master/tools/ops/mugc.py

This should help! Thanks @kapilt

**Comment by mpradeep23** [comment]
Hey @kapilt I have another question. So I see that the lambda function created with custodian prefix isnt attached to any vpc or security group. So is it possible to add vpc and sg in our policy yaml file?
