### ISSUE TITLE
New Cloudtrail option - listening for starting instances

### ISSUE THREAD

**Issue by wildbinaryforest** [cloud-custodian/cloud-custodian#5922]
**Is your feature request related to a problem? Please describe.**
Was looking to add an action anytime an instance is restarted as that option didn't exist.

**Describe the solution you'd like**
Add a cloudtrail option listening for API call events that are lsitening for "StartInstances"

**Describe alternatives you've considered**
Came up with a few round about ways of going around this but this seemed like the easiest solution.

**Additional context**
Ran local tests and this worked when added to cwe.py under cloudtrail options.

'StartInstances': {
            'ids': 'responseElements.instancesSet.items[].instanceId',
            'source': 'ec2.amazonaws.com'}

**Comment by kapilt** [comment]
a policy can subscribe to any api call, it doesn't need to be listed in the event shortcuts. See the documentation https://cloudcustodian.io/docs/aws/lambda.html#cloudtrail-api-calls for how to specify an event using ids, source, event. We stopped adding shortcuts in preference of policies specifying what they want to subscribe to fully, as there are thousands of api calls, and listing them explicitly doesn't really add value.
