### ISSUE TITLE
Azure "set-public-access" action not working as expected

### ISSUE THREAD

**Issue by ajmsra** [cloud-custodian/cloud-custodian#5932]
**Describe the bug**
`set-public-access` action is not setting the containers private  

**To Reproduce**
 custodian run --output-dir=. custodian.yml

**Expected behavior**
Set container to private

**Background (please complete the following information):**
 - OS: mac OS
 - Python Version: Python 3.7.7
 - Custodian Version: 0.9.3
 - Tool Version: [if applicable]
 - Cloud Provider: azure
 - Policy: [please exclude any account/sensitive information]
```yaml
policies:
  - name: storage-container-public
    description: |
      Find all containers with public access enabled
    resource: azure.storage-container
    filters:
      - type: value
        key: properties.publicAccess
        op: not-equal
        value: None
    actions:
      - type: set-public-access
        value: None

```
 - Traceback: 
```
2020-07-07 14:38:50,658: custodian.policy:INFO policy:storage-container-public resource:azure.storage-container region: count:1 time:2.50
2020-07-07 14:38:50,660: custodian.azure.AzureBaseAction:ERROR set-public-access failed for 'test'.
Traceback (most recent call last):
  File "/Users/spoloj081/myfolder/github/cloud-custodian/tools/c7n_azure/c7n_azure/actions/base.py", line 79, in _process_resources
    message = self._process_resource(r)
  File "/Users/spoloj081/myfolder/github/cloud-custodian/tools/c7n_azure/c7n_azure/resources/storage_container.py", line 110, in _process_resource
    public_access=self.data['value']
TypeError: update() missing 1 required positional argument: 'blob_container'
2020-07-07 14:38:50,661: custodian.policy:INFO policy:storage-container-public action:storagecontainersetpublicaccessaction resources:1 execution_time:0.00
```
 - `custodian version --debug` output

**Additional context**

**Comment by ajmsra** [comment]
Hey @kapilt whenever you get some time can you take a look at this issue, please

**Comment by rachgupt** [comment]
Is there a way to identify non geo-redundant storage

**Comment by h-dub** [comment]
@ajmsra 
I verified set-public-access is working correctly in the lab on the master branch.
The error reported indicates that the container name that should be in resource['name'] was missing.
I don't have anything other than wild guesses as to why it would be missing. Its a basic field that should always be around.

Let us know if you are still seeing this problem and we can investigate further.
Thanks!

**Comment by h-dub** [comment]
@rachgupt 
Here is one that detects LRS storage accounts:
```
policies:
  - name: storage-not-georedunant
    description: |
      Find all stoage accounts that are not using a georedunant SKU
    resource: azure.storage
    filters:
      - type: value
        key: sku.name
        op: equal
        value: Standard_LRS
```

**Comment by kapilt** [comment]
@stefangordon can we close this ?

**Comment by stefangordon** [comment]
Yep, I believe this is resolved, if there is any more trouble feel free to file a new issue.
