### ISSUE TITLE
Controlling verbosity of notifications from aws.ami cross-account filters

### ISSUE THREAD

**Issue by lithiumoxide** [cloud-custodian/cloud-custodian#5993]
I'm using `aws.ami` to find AMIs shared with other accounts using the `cross-account` filter. I send the findings to a Slack channel, where a team can check and respond to the findings where necessary. This works great.

However, the message sent to Slack contains a significant amount of JSON. Is there any way to control the verbosity or what parts of the JSON block are sent to the notification recipient? In my case, it would be great to get the `c7n:CrossAccountViolations`, `ImageId`, and `Tags` blocks sent, with everything else stripped out. If this isn't possible, can the JSON part of the notification be suppressed entirely (i.e. the notification would simply tell me that there _is_ a shared AMI, but would not supply any details)?

I know I could potentially send the findings to a Lambda function and strip out unneeded JSON there, but it would be great if this was possible to control from within the Custodian policy itself.

**Comment by kapilt** [comment]
you can create custom mailer templates to control the exact formatting of content to your slack channels with a jinja template.

**Comment by lithiumoxide** [comment]
Ah, nice one @kapilt. I'll check that out, thanks!
