### ISSUE TITLE
Ability to remove individual account IDs from the AMI launch permissions with aws.ami

### ISSUE THREAD

**Issue by lithiumoxide** [cloud-custodian/cloud-custodian#6008]
**Is your feature request related to a problem? Please describe.**
I have a use case where I want Cloud Custodian to find AMIs that are shared with accounts not in a whitelist, but in many cases, the AMI might be shared with both authorised and unauthorised accounts. When I use Cloud Custodian to remediate this (i.e. `remove-launch-permissions`) the permissions for _all_ accounts are removed, including the accounts that do have valid access to the AMI.

**Describe the solution you'd like**
I'd like the remediation available in Cloud Custodian to remove launch permissions to the AMI for accounts that are _not_ defined in the whitelist; all other accounts (i.e. the ones that _are_ in the whitelist) should not have their launch permissions removed.

**Describe alternatives you've considered**
I haven't tried it yet, but a Lambda function may be useful here to remove individual account IDs from the launch permissions. I'm not sure how much I like the idea of maintaining both a Cloud Custodian policy _and_ a Lambda function just to remove individual account IDs from the launch permissions rather than all of them.

**Comment by kapilt** [comment]
thanks, i've added a pr that tries to address that use case.

**Comment by lithiumoxide** [comment]
> thanks, i've added a pr that tries to address that use case.

Fantastic, thanks!
