### ISSUE TITLE
Is there a way to match (filter) on an 'app-elb' that no longer has a target-group or listener attached to it?

### ISSUE THREAD

**Issue by 85matthew** [cloud-custodian/cloud-custodian#6015]
I've found a way to work around removing unused 'app-elb-target-groups' but now I'm not able to find a way to remove an unused 'app-elb'. If I have already deleted all the target-groups/listneners... I can't find a way to match against the 'null' or 'empty' list returned using the 'load-balancer' or 'listener' filters.

Have tried many variations of something like this:

  - name: delete-unused-alb
    resource: app-elb
    filters:
      - type: listener
        key: Port
        value: 80
        op: not-equal

  - name: delete-unused-alb
    resource: app-elb
    filters:
      - type: listener
        key: Port
        value: 'null'

  - name: delete-unused-alb
    resource: app-elb
    filters:
      - type: listener
        key: DefaultActions
        value: 'null'

  - name: delete-unused-alb
    resource: app-elb
    filters:
      - type: listener
        key: DefaultActions
       value: 0
       value_type: count

  - name: delete-unused-alb
    resource: app-elb
    filters:
      - type: listener
        key: DefaultActions
       value: 0
       value_type: resource_count

Also many variations like this utilizing the filter type 'target-group' also.

Any guidance on if something like this is even possible. I imagine the data type being returned by the empty json is probably matching as a different data type.

aws elbv2 describe-listeners --load-balancer-arn arn:aws:elasticloadbalancing:us-east-1:111111111111:loadbalancer/app/TestALB/798b9asdfgedd5f0
{
    "Listeners": []
}

**Comment by kapilt** [comment]
the default value filter covers this use case
```
filters:
 - Listeners: []
```
or
```
 - Listeners: empty
```

the listener filter is for matching on enriched attributes of a listener, in this case your just matching on the lack of one (not attributes of one).

**Comment by 85matthew** [comment]
Thanks for the response Kapil.

I had tried the first suggestion above with the empty array.  I just
re-tested again to make sure.

For the "- Listeners: []" - It just doesn't match. It shows no resources
matching when I have. With just that filter, it shows "count:0".

On the - Listeners: empty- I had not tried this one and was hopeful
because it does match when the listeners are empty... BUT... when I attach
a listener and re-run it... it still shows a match for some reason.

Any other thoughts? Thanks again

**Comment by kapilt** [comment]
I think your getting confused by the default cache, if your modifying the environment live you need to pass --cache-period=0 else custodian will by default use a 15m cache.

**Comment by 85matthew** [comment]
Thanks again for responding Kapil. I think there is still an issues and
it's not related to cache. Hopefully the details below capture what I'm
seeing a little better for you to see. I'm using the latest container build
of c7n. Any suggestions on how to get lower level debugs or different
approaches to try are greatly suggested. Also if you can direct me to where
in the code this is occurring & if there is a doc for development/debugging
I'm happy to pursue a potential bug. Any help is greatly appreciated!

Is there a way to see more detailed debug aside from the -v flag?  (Like
the boto api calls). I've been running it with the cache disabled as I did
notice early on that was interfering.

Hopefully this walks through the strange behavior I'm seeing. I'm testing
your 2 suggested configuration methods to potentially match ALBs (app-elb)
that have no target-groups attached.

1st Method:
#####

  - name: app-elb-mark-unused-for-deletion
    resource: app-elb
    description: |
      Mark any ELB with no instances attached for deletion in 14 days.
      Also send an email to the ELB resource owner informing them its unused.
    filters:
#      - "tag:maid_status": absent
#      - Type: application
      - Listeners: []
    actions:
      - type: mark-for-op
        tag: maid_status
        op: delete
        days: 14


2nd Method:
####

  - name: app-elb-mark-unused-for-deletion
    resource: app-elb
    description: |
      Mark any ELB with no instances attached for deletion in 14 days.
      Also send an email to the ELB resource owner informing them its unused.
    filters:
#      - "tag:maid_status": absent
#      - Type: application
      - Listeners: empty
    actions:
      - type: mark-for-op
        tag: maid_status
        op: delete
        days: 14

And I have an ALB with no listeners attached for these tests.

[image: Screen Shot 2020-08-07 at 7.35.43 AM.png]
Here's the debug from the first one. Note that it doesn't match and
therefore doesn't try to tag the ALB (using "Listeners: []")

bash-3.2$ docker run -it   -v $(pwd)/output:/home/custodian/output  -v
$(pwd)/:/home/custodian/   --env-file <(env | grep "^AWS\|^AZURE\|^GOOGLE")
  cloudcustodian/c7n run -c elb-cleanup.yml -s output --cache-period 0 -v

2020-08-07 13:41:32,778: custodian.cache:DEBUG Disabling cache

2020-08-07 13:41:32,779: custodian.commands:DEBUG Loaded file
elb-cleanup.yml. Contains 1 policies

2020-08-07 13:41:32,790: custodian.aws:DEBUG using default region:us-east-1
from boto

2020-08-07 13:41:33,127: custodian.output:DEBUG Storing output with
<LogFile file://output/app-elb-mark-unused-for-deletion/custodian-run.log>

2020-08-07 13:41:33,143: custodian.policy:DEBUG Running
policy:app-elb-mark-unused-for-deletion resource:app-elb region:us-east-1
c7n:0.9.4

2020-08-07 13:41:33,790: custodian.resources.appelb:DEBUG Filtered from 1
to 0 appelb   *<----- *****THIS HERE SHOWS NO MATCH ON "Listeners: []"
******

2020-08-07 13:41:33,791: custodian.policy:INFO
policy:app-elb-mark-unused-for-deletion resource:app-elb region:us-east-1
count:0 time:0.65

2020-08-07 13:41:33,810: custodian.output:DEBUG metric:ResourceCount
Count:0 policy:app-elb-mark-unused-for-deletion restype:app-elb scope:policy

2020-08-07 13:41:33,810: custodian.output:DEBUG metric:ApiCalls Count:2
policy:app-elb-mark-unused-for-deletion restype:app-elb


Using the "empty" method to match. I DO see that it matches and the log
tells me that it is tagging the ALB. But... unfortunately, the ALB never
gets tagged for some reason

bash-3.2$ docker run -it   -v $(pwd)/output:/home/custodian/output  -v
$(pwd)/:/home/custodian/   --env-file <(env | grep "^AWS\|^AZURE\|^GOOGLE")
  cloudcustodian/c7n run -c elb-cleanup.yml -s output --cache-period 0 -v

2020-08-07 13:41:42,448: custodian.cache:DEBUG Disabling cache

2020-08-07 13:41:42,451: custodian.commands:DEBUG Loaded file
elb-cleanup.yml. Contains 1 policies

2020-08-07 13:41:42,466: custodian.aws:DEBUG using default region:us-east-1
from boto

2020-08-07 13:41:42,799: custodian.output:DEBUG Storing output with
<LogFile file://output/app-elb-mark-unused-for-deletion/custodian-run.log>

2020-08-07 13:41:42,812: custodian.policy:DEBUG Running
policy:app-elb-mark-unused-for-deletion resource:app-elb region:us-east-1
c7n:0.9.4

2020-08-07 13:41:43,383: custodian.resources.appelb:DEBUG Filtered from 1
to 1 appelb  *<------ **** DOES SHOW A MATCH HERE *****

2020-08-07 13:41:43,384: custodian.policy:INFO
policy:app-elb-mark-unused-for-deletion resource:app-elb region:us-east-1
count:1 time:0.57

2020-08-07 13:41:43,389: custodian.actions:INFO Tagging 1 resources for
delete on 2020/08/21  *<----- **** DOES SHOW THAT IT IS APPLYING A TAG HERE
*****

2020-08-07 13:41:43,669: custodian.policy:INFO
policy:app-elb-mark-unused-for-deletion action:appelbmarkforopaction
resources:1 execution_time:0.28

2020-08-07 13:41:43,675: custodian.output:DEBUG metric:ResourceCount
Count:1 policy:app-elb-mark-unused-for-deletion restype:app-elb scope:policy

2020-08-07 13:41:43,676: custodian.output:DEBUG metric:ApiCalls Count:3
policy:app-elb-mark-unused-for-deletion restype:app-elb



Now the weirdest thing... With the "empty" configuration (2nd example) that
seemed to match above...

  - name: app-elb-mark-unused-for-deletion
    resource: app-elb
    description: |
      Mark any ELB with no instances attached for deletion in 14 days.
      Also send an email to the ELB resource owner informing them its unused.
    filters:
#      - "tag:maid_status": absent
#      - Type: application
      - Listeners: empty
    actions:
      - type: mark-for-op
        tag: maid_status
        op: delete
        days: 14


When I attach a Listener/TargetGroup, it STILL matches the ALB & it DOES
successfully tag it for deletion.

[image: Screen Shot 2020-08-07 at 7.49.48 AM.png]

bash-3.2$ docker run -it   -v $(pwd)/output:/home/custodian/output  -v
$(pwd)/:/home/custodian/   --env-file <(env | grep "^AWS\|^AZURE\|^GOOGLE")
  cloudcustodian/c7n run -c elb-cleanup.yml -s output --cache-period 0 -v

2020-08-07 13:50:23,072: custodian.cache:DEBUG Disabling cache

2020-08-07 13:50:23,073: custodian.commands:DEBUG Loaded file
elb-cleanup.yml. Contains 1 policies

2020-08-07 13:50:23,087: custodian.aws:DEBUG using default region:us-east-1
from boto

2020-08-07 13:50:23,427: custodian.output:DEBUG Storing output with
<LogFile file://output/app-elb-mark-unused-for-deletion/custodian-run.log>

2020-08-07 13:50:23,442: custodian.policy:DEBUG Running
policy:app-elb-mark-unused-for-deletion resource:app-elb region:us-east-1
c7n:0.9.4

2020-08-07 13:50:24,059: custodian.resources.appelb:DEBUG Filtered from 1
to 1 appelb *<----- **** SUCCESSFUL MATCH WHEN IT SHOULDN'T BE. *****

2020-08-07 13:50:24,060: custodian.policy:INFO
policy:app-elb-mark-unused-for-deletion resource:app-elb region:us-east-1
count:1 time:0.62

2020-08-07 13:50:24,066: custodian.actions:INFO Tagging 1 resources for
delete on 2020/08/21 <---- ***** DOES SUCCESSFULLY TAG THE ALB AS I WOULD
HAVE EXPECTED WITHOUT TG ATTACHED*

2020-08-07 13:50:24,318: custodian.policy:INFO
policy:app-elb-mark-unused-for-deletion action:appelbmarkforopaction
resources:1 execution_time:0.25

2020-08-07 13:50:24,325: custodian.output:DEBUG metric:ResourceCount
Count:1 policy:app-elb-mark-unused-for-deletion restype:app-elb scope:policy

2020-08-07 13:50:24,325: custodian.output:DEBUG metric:ApiCalls Count:3
policy:app-elb-mark-unused-for-deletion restype:app-elb


With the other configuration "Listeners: []" It still fails to match the
ALB with a target group attached (This would be expected behaior)

  - name: app-elb-mark-unused-for-deletion
    resource: app-elb
    description: |
      Mark any ELB with no instances attached for deletion in 14 days.
      Also send an email to the ELB resource owner informing them its unused.
    filters:
#      - "tag:maid_status": absent
#      - Type: application
      - Listeners: []
    actions:
      - type: mark-for-op
        tag: maid_status
        op: delete
        days: 14


bash-3.2$ docker run -it   -v $(pwd)/output:/home/custodian/output  -v
$(pwd)/:/home/custodian/   --env-file <(env | grep "^AWS\|^AZURE\|^GOOGLE")
  cloudcustodian/c7n run -c elb-cleanup.yml -s output --cache-period 0 -v

2020-08-07 13:52:05,088: custodian.cache:DEBUG Disabling cache

2020-08-07 13:52:05,088: custodian.commands:DEBUG Loaded file
elb-cleanup.yml. Contains 1 policies

2020-08-07 13:52:05,098: custodian.aws:DEBUG using default region:us-east-1
from boto

2020-08-07 13:52:05,460: custodian.output:DEBUG Storing output with
<LogFile file://output/app-elb-mark-unused-for-deletion/custodian-run.log>

2020-08-07 13:52:05,476: custodian.policy:DEBUG Running
policy:app-elb-mark-unused-for-deletion resource:app-elb region:us-east-1
c7n:0.9.4

2020-08-07 13:52:06,111: custodian.resources.appelb:DEBUG Filtered from 1
to 0 appelb *<---- STILL NO MATCH HERE WITH TARGET GROUP ATTACHED NOW
(EXPECTED)*

2020-08-07 13:52:06,112: custodian.policy:INFO
policy:app-elb-mark-unused-for-deletion resource:app-elb region:us-east-1
count:0 time:0.64

2020-08-07 13:52:06,123: custodian.output:DEBUG metric:ResourceCount
Count:0 policy:app-elb-mark-unused-for-deletion restype:app-elb scope:policy

2020-08-07 13:52:06,124: custodian.output:DEBUG metric:ApiCalls Count:2
policy:app-elb-mark-unused-for-deletion restype:app-elb

**Comment by 85matthew** [comment]
FYI: Those screen captures don't show up as well in the Issue. Let me know if you would like me to forward you the email directly.

**Comment by 85matthew** [comment]
Hey again.

Just touching base to see if you had a chance to look at this. Wanted to
make sure what I showed in the last email makes sense where it's not quite
working correctly.

Like I said, I can email you screen captures directly if you want. They
print much easier to read via email. Thanks again.

Matt
