### ISSUE TITLE
RedShift Parameters Group

### ISSUE THREAD

**Issue by aakifshaikh** [cloud-custodian/cloud-custodian#6021]
**Enable Redshift User Activity Logging**
I want cloud custodian to identify if AWS Redshift clusters is enabled for user activity logging. 

Ensure that user activity logging is enabled for your AWS Redshift clusters in order to log each query before it is performed on the clusters database. To enable this feature, set the "enable_user_activity_logging" database parameter to true within your Amazon Redshift non-default parameter groups. In order to make "enable_user_activity_logging" parameter to work, you must first enable database audit logging for your clusters. The AWS Redshift database audit creates three types of logs: connection and user logs (activated by default), and user activity logs (activated by the "enable_user_activity_logging" parameter).

AWS Redshift user activity logging is primarily useful for troubleshooting purposes. Once enabled, the feature tracks information about the types of queries that both the users and the system perform within the cluster database.

Refer to Cloud Conformity link here-https://www.cloudconformity.com/knowledge-base/aws/Redshift/user-activity-log.html

Note: this is different than the audit logging of AWS Redshift cluster.

**Comment by kapilt** [comment]
this can be done with param filter on redshift resource
