### ISSUE TITLE
Policy Test Framework (PTF)

### ISSUE THREAD

**Issue by JohnHillegass** [cloud-custodian/cloud-custodian#6023]
**Is your feature request related to a problem? Please describe.**
A way to run policies through a recorded test suite would be a really useful feature. The main problem this solves for me is regression testing but I could also see value looking at it from a policy release perspective as well. For example, at code check-in, a reviewer could look for related tests and CI could also be used to present a pass/fail message. 

**Describe the solution you'd like**
I am thinking we can make use of the pytest and placebo setup that we have, along with some metadata attribute on the policy itself i.e metadata.unittest = testfile/class/method etc. Maybe we could call it c7n_pdk? Seems like this could fit nicely in the tools directory.

**Comment by SafaTinaztepe** [comment]
+1

Excellent idea.  I can also see myself executing a command like `custodian test a_policy.yml --testfile testsuite.yml` locally or have it be incorporated as a CI build step.

**Comment by kapilt** [comment]
this is already in the works, the first step is pytest-terraform, see the original proposal https://github.com/cloud-custodian/cloud-custodian/issues/4912.

**Comment by JohnHillegass** [comment]
Nice, I may have to spend some cycles seeing how to put it together. That plugin would really enable some velocity around writing the tests.

**Comment by kapilt** [comment]
cool, just to flush out the next steps, the second step is some executing functional tests against the three providers daily, the third step is followup on a testing proposal, either as a builtin cli test sub command or a standalone, fourth step is an implementation of that proposal. the iaac asset testing proposal and tf pr is related wrt to cli / ci integrations as its intended to be more geared towards exposing results in ci integration formats and executing against source assets.

**Comment by JohnHillegass** [comment]
I see that @marcoceppi made a move towards step 2 https://github.com/cloud-custodian/cloud-custodian/pull/6040 linking for visibility. Awesome work getting it integrated :) I'll keep in mind adding azure and gcp soon.

**Comment by marcoceppi** [comment]
I'm working through a GCP branch at the moment, but haven't planned out azure yet!

**Comment by kapilt** [comment]
we should move discussion to the proposal issue
