### ISSUE TITLE
AWS - Lambda Edge Filter

### ISSUE THREAD

**Issue by Lucas-Irvine** [cloud-custodian/cloud-custodian#6034]
Creating this issue for more visibility/discussion on this PR as suggested: https://github.com/cloud-custodian/cloud-custodian/pull/5999. I'm not sure which approach is the better one.

**Is your feature request related to a problem? Please describe.**
The use case is to enforce specific rules on lambda@edge functions, such as limiting their access to other AWS resources.

**Describe the solution you'd like**
Create a lambda@edge filter, perhaps also creating a new resource type for lambda versions. This is because lambda triggers are unique for each published function version (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-edge-edit-function.html), and so we would like to be able to filter for the lambda function versions that have cloudfront event triggers.

**Describe alternatives you've considered**
The main alternative would be to consider a lambda function a lambda@edge function if it has at least one version that is lambda@edge. This sacrifices some precision of controls in return for not having to make a new lambda version resource.

**Comment by kapilt** [comment]
what do you mean by limiting access to other resources? do you have an example policy (filters, actions)? do you mean the iam role in use for the function? the iam access policy for the function spans versions.

**Comment by Lucas-Irvine** [comment]
Ah, ok I hadn't realized that. Yes, one use case would be enforcing rules on the iam access policy. The other main use case is we would like to make sure that all lambda functions are run within a VPC (ie their Configuration.VpcConifg is not null). However, lambda@edge functions cannot be placed within a VPC, so they would be exempt from this requirement.

**Comment by kapilt** [comment]
but thats re use of lambda edge not an argument for versions, thats an argument for a source filter on lambda. exposing versions multiplies needlessly a lot under management. even in the gc versions work which does need to process versions, the goal is to simplify management and expression of that by exposing it on a function.

**Comment by Lucas-Irvine** [comment]
ok sounds good I'll implement it without exposing version then

**Comment by soncaocc** [comment]
I support the enhancement for adding recognition of lambda versions/aliases to ```resource: lambda```. Looking through @Lucas-Irvine 's commits, he had this written but then backed out. 

The use case I encounter can be read in more detail in this issue: https://github.com/cloud-custodian/cloud-custodian/issues/6058

Thanks!
