### ISSUE TITLE
releng - randomize test will ocassionally fail

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#6039]
**Describe the bug**

there's a randomize test in reduce that will randomly fail because randomly two sets might have the same order

[gw0] linux -- Python 3.8.5 /home/runner/work/cloud-custodian/cloud-custodian/.tox/py38-cov/bin/python
Traceback (most recent call last):
  File "/home/runner/work/cloud-custodian/cloud-custodian/tests/test_filters.py", line 1232, in test_randomize
    self.assertNotEqual(
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/unittest/case.py", line 921, in assertNotEqual
    raise self.failureException(msg)
AssertionError: ['D', 'C', 'B', 'A', 'E', 'F'] == ['D', 'C', 'B', 'A', 'E', 'F']

@tjstansell

**Comment by tjstansell** [comment]
hm... do we just reduce the likelihood by running it like 5 times in a row and making sure all 5 are not the same?

**Comment by kapilt** [comment]
good question, a simpler option is to set the random seed explicitly in this test.

**Comment by howbazaar** [comment]
Alternatively you have the randomize function ensure that the lists aren't the same before it returns.

**Comment by kapilt** [comment]
fix merged
