### ISSUE TITLE
Tagging Policy Check

### ISSUE THREAD

**Issue by NagaSamyuktha** [cloud-custodian/cloud-custodian#6042]
I am trying to create a policy which will pass through all the aws resources (ec2,s3,ebs,.. etc) to check proper tags.
If any of the resource is failing me meet certain tags, need to send all resource id's to particular email at once.

Is it possible in cloud custodian? if yes, please explain.

**Comment by kapilt** [comment]
use a yaml anchor/reference syntax to define the tag policy as a set of filters that find those missing the tags in question and notify action as common bits in the vars section, then for each resource you want to enforce on have a policy on it, that references those common bits.

**Comment by NagaSamyuktha** [comment]
Hi Kapilt, Thanks for your quick reply, I am doing this, but no use. I am new to cloud custodian. can you give me small example how to achieve this? I need all the resources(ec2, s3 and ebs) details in single mail?

```vars:
  tag-filters: &resource_filter
    - type: value
      key: tag:test
      op: regex
      value: "[a-zA-z0-9]*"

policies:

- name: test
  resource: [s3, ec2, ebs]
  region: eu-west-1
  filters:
      *resource_filter
  actions:
    - type: notify
      to:
        - xyz@test.com
      template: policy-template
      subject: test
      transport:
        type: sqs
        queue: custodian_Sqs
        region: us-east-1
```
