### ISSUE TITLE
AWS - access-analyzer-enabled filter for resource: account

### ISSUE THREAD

**Issue by Lucas-Irvine** [cloud-custodian/cloud-custodian#6054]
**Is your feature request related to a problem? Please describe.**
As an alternative to adding a singleton Access Analyzer resource, we would like to be able to filter accounts for those that have access analyzers present and active, since we would like an access analyzer to be functioning in every account.

**Describe the solution you'd like**
Create an access-analyzer-enabled filter for the resource: account, which will list analyzers in that account and check that the analyzer's status is active, and if so then return that account.

**Describe alternatives you've considered**
We've discussed previously that an access-analyzer resource probably doesn't make sense, but we would still like to have support for checking if access analyzers are enabled in accounts.

**Comment by kapilt** [comment]
sounds reasonable, what about analyzers flowing from org setups? do they count for the purpose of this filter?

**Comment by kapilt** [comment]
merged
