### ISSUE TITLE
Store ID in Variable ( or text file).

### ISSUE THREAD

**Issue by NagaSamyuktha** [cloud-custodian/cloud-custodian#6078]
Hi,
I am new to cloud custodian. I have two questions.
1. I am working with AWS services, in action part can I get ID of AWS service? like below:

2. If yes, In Action can I store ID in a text file. so that I can user later?

```
policies:

- name: test
  resource: ec2
  region: eu-west-1
  filters :
    - "tag:test ": absent 
  actions:
<save EC2 id in some file(test.txt)>
```

**Comment by kapilt** [comment]
the resources the policies matched are stored in the output directory ( -s output) will have `output/test/resources.json` with the resources json representation which includes ids
