### ISSUE TITLE
Add CodeBuild as resource to scan for unused security-group filter

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#6081]
**Is your feature request related to a problem? Please describe.**
We recently found that our unused security-group filter was marking security groups used by Codebuild projects as unused.  Some of the codebuild projects security groups got deleted and then the codebuild projects failed. Looking at the code I see it is not set to check CodeBuild for security group group ids to see if they are using them - https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/resources/vpc.py#L699

**Describe the solution you'd like**
On this section of code https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/resources/vpc.py#L699 it would be good to have it check if codebuild projects are using any of the security groups before stating they are unused.

**Describe alternatives you've considered**
I thought about writing another policy to look for security group attachements to codebuild and tagging them with an identifier but then cleanup becomes an issue as once the codebuild project is gone it would then need another policy to remove the tag from the SG so it gets complex

**Additional context**
Nope, it would just be good to have to avoid breaking codebuild projects by mistake

**Comment by pjshort22** [comment]
Yes I agree and would like to see this included to stop CodeBuild Projects that don't run that often from Breaking due to Security Group being deleted.

**Comment by kapilt** [comment]
closed in #6153
