### ISSUE TITLE
Best place to insert function to input results to database?

### ISSUE THREAD

**Issue by imgroot1391** [cloud-custodian/cloud-custodian#6082]
By default, Custodian will create directories and output the data to .json files. However If I have a database table, I'd like to run all my policies and save the results to a database table. 

Im wondering where in the code is the best place to "re-route" the results data (from multiple policies ran) and input it into a database by calling my custom function?

**Comment by imgroot1391** [comment]
Ideally it is a place that won't break on future releases of Cloud Custodian as well...

**Comment by kapilt** [comment]
ingest into your tables from the output directories.
