### ISSUE TITLE
c7n 0.9.5 - custodian version return 0.9.4 when c7n is installed from whl file

### ISSUE THREAD

**Issue by jmwaks** [cloud-custodian/cloud-custodian#6098]
**Describe the bug**
I installed c7n 0.9.5 using c7n-0.9.5-py3-none-any.whl from https://pypi.org/project/c7n/#files. Running custodian version returns 0.9.5. 
On checking c7n/version.py , version is set to '0.9.4'
**To Reproduce**
* Install c7n 0.9.5 using c7n-0.9.5-py3-none-any.whl from https://pypi.org/project/c7n/#files
* Run custodian version

**Expected behavior**
Custodian version should return '0.9.5' 

**Background (please complete the following information):**
 - OS: [e.g. OSX 10.15.6]
 - Python Version: [e.g. python 3.8.1]
 - Custodian Version: [e.g. 0.9.5]
 - Tool Version: [if applicable]
 - `custodian version --debug` output

**Comment by kapilt** [comment]
yeah, we had to switch from setuptools_scm when going to poetry, importlib_metadata would return the write answer, but we're not quite ready to depend on that yet, so we're still writing out a version.py, thats automated in trunk, and a 0.9.6 release is imminent

**Comment by jmwaks** [comment]
Thank for the update @kapilt . Does this mean this issue will be fixed in 0.9.6 ?

**Comment by kapilt** [comment]
it will be fixed in 0.9.6 via automation to prevent in future.
