### ISSUE TITLE
Filter aws.ebs-snapshot with deleted volumes

### ISSUE THREAD

**Issue by IngussNeilands** [cloud-custodian/cloud-custodian#6131]
When I delete instance or volume, snapshot still has Volume ID `vol-1234567890123456789`

I would like to be able to filter all aws.ebs-snapshot created for deleted volumes.

**Comment by kapilt** [comment]
afaics we would need to implement a related filter for an ebs volume on the snapshot, and then you could do a not: filter block on it to find snapshots without an extant volume.

**Comment by IngussNeilands** [comment]
One more potential use case for this filter – it would allow clean-up of Lifecycle Manager created snapshots for terminated instances and deleted volumes, unfortunately DLM does not provide clean-up feature…
