### ISSUE TITLE
Feature: allow RDS/EBS snapshots to be removed from being public

### ISSUE THREAD

**Issue by mini1989** [cloud-custodian/cloud-custodian#6149]
Need to have a feature to request filter for  ebs-snapshots and rds-snapshots public detection.
Currently we just have delete and copy. Can u please to get something directly rather than using crossacount s3 url filter, which does not work if format of objects is different in s3.

Please help to get a direct filter .. something  like -set public access in rds

**Comment by mini1989** [comment]
@kapilt .. Can you please help on this or advise something

**Comment by pentagonal-proboscis** [comment]
I am also interested in a feature to enable setting RDS snapshots to be private.

It seems like some kind of action would need to be added to the rds-snapshot resource: https://cloudcustodian.io/docs/aws/resources/rds-snapshot.html#actions

In the AWS console this is exposed as an action on a snapshot of "Share" and you can choose to share publicly or privately. Ideally something reflecting this capability would be made available.

Maybe it would need to call something like:
https://docs.aws.amazon.com/cli/latest/reference/rds/modify-db-snapshot-attribute.html

**Comment by mini1989** [comment]
Can we have filter options apart from S3 bucket for finding ebs/rds snapshot directly rather than through csv data.

**Comment by kapilt** [comment]
@mini1989 you'll have to elaborate on the question, as i don't understand what your referencing. you can add additional filters to any policy.
