### ISSUE TITLE
cloud custodian policy for dedicated hosts with no running instances

### ISSUE THREAD

**Issue by veenagurram** [cloud-custodian/cloud-custodian#6156]
**Is your feature request related to a problem? Please describe.**
cloud custodian policy for dedicated hosts with no running instances. Not able to get complete record of dedicated hosts with no running instances

**Describe the solution you'd like**
need to get a list of dedicated host with no instances running or the count of instances running

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by gelouko** [comment]
I've checked the repo and looks like there're still no filters for aws dedicated hosts.

I guess it could be a **sub resource** in `ec2`.

It would use the [DescribeHosts API](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeHosts.html) to fetch the hosts, which fetches the Host object with `availableCapacity`, `instances`, and [some other attributes from the host](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Host.html).

Then, you would be able to use the value filter to get the information you want.

Would that satisfy your needs?

Could someone verify if this would be a good solution?
If so, I'd be happy to contribute with a PR

**Comment by kapilt** [comment]
a new dedicated host resource and a filter on it for finding those sans instances/vms sounds like a good fit.

**Comment by gelouko** [comment]
Hi @veenagurram , could you kindly post a response from boto3's `describe_hosts` operation?

Feel free to fake ids and values (but keep the value types and structures)
I want to check if https://github.com/cloud-custodian/cloud-custodian/pull/6165/files#diff-c3c9d06d124fb6301c8e145f50c7d675 is a valid return value from the API :)

If it is correct, then I'll request for the PR review!

**Comment by kapilt** [comment]
merged per 6165, and released in 0.9.7
