### ISSUE TITLE
Are Custom boto3 API calls supported by Custodian?

### ISSUE THREAD

**Issue by al3pht** [cloud-custodian/cloud-custodian#6158]
Would it be possible to make any custom boto3 API calls with Cloud Custodian? For example, I am trying to write policies around checking/analyzing Scaling Policies for Autoscaling Groups. With the current “- resources: asg” I am not able to see any information regarding the scaling policies of ASGs. Is there another way for me to retrieve this information or would this have to be an addition to the asg.py in resources directory?

**Comment by kapilt** [comment]
the best way to achieve that would be to contribute to custodian to allow for filtering on scaling policies associated to asgs.

**Comment by al3pht** [comment]
# Questions
## About contributing:

I'm interested in contributing. Is there something else I should know besides what is shown in [this guide](https://cloudcustodian.io/docs/contribute.html)?

## About usefulness:

How useful and/or interesting could this be for the community related to this project?

## About custom resources, filters and actions:

Per my understanding `custodian` covers a subset of API calls available via `boto3` (in the case of AWS). Does it makes any sense to work on a generic solution that could accept resources (and maybe filters and actions) not covered by `custodian` but covered by `boto3`?

> Please excuse my ignorance with what may be a very silly question. I'm very new with Cloud Custodian and with the Open Source in general, but I'm very interested on contributing.

**Comment by kapilt** [comment]
its an interesting thought re generic solution, however at least for this particular situation i think the bigger thing is just modeling app scaling policies as resources and then having a related resource filter for asgs that allow examining there respective scaling policy. could you clarify what your looking to examine about the scaling policy?

**Comment by al3pht** [comment]
## What I'm looking for

### EC2 Autoscaling

I want to tag EC2 auto scaling groups without scaling policy as non compliant. But the boto3 api used in `asg.py` is [`describe_auto_scaling_groups`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/autoscaling.html#AutoScaling.Client.describe_auto_scaling_groups) and excludes information about scaling policies. I want to leverage the boto3 API [`describe_policies`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/autoscaling.html#AutoScaling.Client.describe_policies) given that implicitly includes a mapping `PolicyName <--> AutoScalingGroupName`.

### Other potential solutions in mind: Application Autoscaling

I've noted that Application autoscaling covers [multiple services](https://docs.aws.amazon.com/autoscaling/application/userguide/what-is-application-auto-scaling.html). The only reference I was able to find in the [source code](https://github.com/cloud-custodian/cloud-custodian/tree/master/c7n) so far is about EC2 ASGs (resource: asg), but none referring to [`application-autoscaling`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/application-autoscaling.html). 

Because of what I mentioned above I'm not sure if Cloud Custodian already covers this service. Depending on the answer I'm thinking on contributing with new code for Application Autoscaling if that's not covered yet, or if it needs more work.
