### ISSUE TITLE
azure-event-grid policy Error related to function_app_name

### ISSUE THREAD

**Issue by bhvkrishna90** [cloud-custodian/cloud-custodian#6163]
Created a simple policy as mentioned below url. 
[event-grid-functions](https://cloudcustodian.io/docs/azure/advanced/azurefunctions.html#event-grid-functions)

When I tried to run the policy I am getting below error:
**region:global error:'FunctionAppInfrastructureParameters' object has no attribute 'function_app_name'
2020-09-29 16:12:11,300: c7n_org:INFO Policy resource counts Counter()**

applying policies using below command.
**c7n-org run -c .\subscriptions.yml -s output -u .\event_policy.yml**

Versions:
c7n-org : 0.6.5
c7n-azure: 0.7.5
c7n: 0.9.6

**Comment by bhvkrishna90** [comment]
Policy Snippet as below:

policies:
  - name: tag-key-vault-creator
    resource: azure.keyvault
    mode:
      type: azure-event-grid
      events: [{
          resourceProvider: 'Microsoft.KeyVault/vaults',
          event: 'write'
        }]
      provision-options:
        identity:
          type: UserAssigned
          id: cloudcustdianFunApp
    filters:
      - "tag:CreatorEmail": null
    actions:
      - type: auto-tag-user
        tag: CreatorEmail

**Comment by kapilt** [comment]
what version of custodian please include of output of .. `custodian version --debug`

**Comment by bhvkrishna90** [comment]
The output of **custodian version --debug** as follows.

Custodian:   0.9.6
Python:      3.8.5 (v3.8.5:580fbb018f, Jul 20 2020, 12:11:27) 
             [Clang 6.0 (clang-600.0.57)]
Platform:    posix.uname_result(sysname='Darwin', nodename='EPW0367', release='19.6.0', version='Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64', machine='x86_64')
Using venv:  False
Docker: False
Installed: 

PyJWT==1.7.1
adal==1.2.4
applicationinsights==0.11.9
apscheduler==3.6.3
argcomplete==1.12.0
attrs==20.2.0
azure-cli-core==2.12.0
azure-cli-telemetry==1.0.6
azure-common==1.1.25
azure-core==1.8.1
azure-cosmos==3.2.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.3.1
azure-graphrbac==0.61.1
azure-keyvault==1.1.0
azure-mgmt-apimanagement==0.1.0
azure-mgmt-applicationinsights==0.2.0
azure-mgmt-authorization==0.60.0
azure-mgmt-batch==7.0.0
azure-mgmt-cdn==4.0.0
azure-mgmt-cognitiveservices==5.0.0
azure-mgmt-compute==10.0.0
azure-mgmt-containerinstance==1.5.0
azure-mgmt-containerregistry==2.8.0
azure-mgmt-containerservice==8.3.0
azure-mgmt-core==1.2.0
azure-mgmt-cosmosdb==0.11.0
azure-mgmt-costmanagement==0.1.0
azure-mgmt-databricks==0.1.0
azure-mgmt-datafactory==0.8.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-dns==3.0.0
azure-mgmt-eventgrid==2.2.0
azure-mgmt-eventhub==3.1.0
azure-mgmt-hdinsight==1.7.0
azure-mgmt-iothub==0.10.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-logic==3.0.0
azure-mgmt-managementgroups==0.2.0
azure-mgmt-monitor==0.7.0
azure-mgmt-network==9.0.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==0.4.0
azure-mgmt-rdbms==1.9.0
azure-mgmt-redis==6.0.0
azure-mgmt-resource==6.0.0
azure-mgmt-resourcegraph==2.0.0
azure-mgmt-search==2.1.0
azure-mgmt-sql==0.16.0
azure-mgmt-storage==7.2.0
azure-mgmt-subscription==0.5.0
azure-mgmt-web==0.44.0
azure-nspkg==3.0.2
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-queue==2.1.0
bcrypt==3.2.0
boto3==1.15.3
botocore==1.18.3
c7n==0.9.6
certifi==2020.6.20
cffi==1.14.3
chardet==3.0.4
click==7.1.2
colorama==0.4.3
cryptography==3.1.1
distlib==0.3.1
docutils==0.15.2
humanfriendly==8.2
idna==2.10
importlib-metadata==1.7.0
isodate==0.6.0
jmespath==0.10.0
jsonpickle==1.4.1
jsonschema==3.2.0
knack==0.7.2
msal==1.0.0
msal-extensions==0.1.3
msrest==0.6.19
msrestazure==0.6.4
netaddr==0.7.20
oauthlib==3.1.0
paramiko==2.7.2
pkginfo==1.5.0.1
portalocker==1.7.1
pycparser==2.20
pygments==2.7.1
pynacl==1.4.0
pyopenssl==19.1.0
pyrsistent==0.16.0
python-dateutil==2.8.1
pytz==2020.1
pyyaml==5.3.1
requests==2.24.0
requests-oauthlib==1.3.0
s3transfer==0.3.3
setuptools==47.1.0
six==1.15.0
tabulate==0.8.7
tzlocal==2.1
urllib3==1.25.10
zipp==3.1.0

**Comment by kapilt** [comment]
resolved in #6169
