### ISSUE TITLE
KeyError on several replication bucket configs

### ISSUE THREAD

**Issue by amitsehgal** [cloud-custodian/cloud-custodian#6187]
**Describe the bug**
I have been getting several different keyerror in policy which just checks mandatory tags. These are mostly occurring in 
 def handle_BucketReplicationConfiguration(self, resource, item_value): 
where destination config returns varied response e.g.

{'bucketARN': 'arn:aws:s3:::bucket-west2', 'encryptionConfiguration': {'replicaKmsKeyID': 'arn:aws:kms:us-west-2:xxxxx:alias/alias-name'}}

This breaks at 
[ERROR] KeyError: 'storageClass'
if r['destinationConfig']['storageClass']: | [ERROR] KeyError: 'storageClass' Traceback (most recent call last):   File "/var/task/custodian_policy.py", line 4, in run     return handler.dispatch_event(event, context)   File "/var/task/c7n/handler.py", line 166, in dispatch_event     p.push(event, context)   File "/var/task/c7n/policy.py", line 1134, in push     return mode.run(event, lambda_ctx)   File "/var/task/c7n/policy.py", line 850, in run     resources = super(ConfigRuleMode, self).run(event, lambda_context)   File "/var/task/c7n/policy.py", line 434, in run     resources = self.resolve_resources(event)   File "/var/task/c7n/policy.py", line 832, in resolve_resources     return [source.load_resource(self.cfg_event['configurationItem'])]   File "/var/task/c7n/resources/s3.py", line 125, in load_resource     method(resource, v)   File "/var/task/c7n/resources/s3.py", line 294, in handle_BucketReplicationConfiguration     if r['destinationConfig']['storageClass']:

Another bucket breaks it at prefix where destination config is:

destinationconfig: {'bucketARN': 'arn:aws:s3:::bucket-replica'}
--

[ERROR] KeyError: 'prefix'Traceback (most recent call last):  File "/var/task/custodian_policy.py", line 4, in run    return handler.dispatch_event(event, context)  File "/var/task/c7n/handler.py", line 166, in dispatch_event    p.push(event, context)  File "/var/task/c7n/policy.py", line 1134, in push    return mode.run(event, lambda_ctx)  File "/var/task/c7n/policy.py", line 850, in run    resources = super(ConfigRuleMode, self).run(event, lambda_context)  File "/var/task/c7n/policy.py", line 434, in run    resources = self.resolve_resources(event)  File "/var/task/c7n/policy.py", line 832, in resolve_resources    return [source.load_resource(self.cfg_event['configurationItem'])]  File "/var/task/c7n/resources/s3.py", line 125, in load_resource    method(resource, v)  File "/var/task/c7n/resources/s3.py", line 288, in handle_BucketReplicationConfiguration    'Prefix': r['prefix'],
--

i did fix one on accountId...but it seems they have breaking on other configs too.

-- | --

--

**To Reproduce**
Have buckets replicated in different regions

**Expected behavior**
need to check the key values and handle varied non required response type values

**Background (please complete the following information):**
 - OS: [e.g. OSX 10.15]
Python Version: [e.g. python 3.8.1] 3.8
 - Custodian Version: [e.g. 0.8.46.1] 0.96.0
 - Tool Version: [if applicable]
 - Cloud Provider: [e.g. gcp, aws, azure] aws
 - Policy: [please exclude any account/sensitive information]
```yaml
policies: 
  mandatory tag checks
```
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output

**Additional context**

**Comment by kapilt** [comment]
you'll need to provide a sanitized view of the config history. config basically does a lot of inconsistent garbage mangling of a resource's attributes, we'll need a copy of the config view of the resource (sanitized). from the cli 
```aws configservice get-resource-config-history --resource-id bucket_name --resource-type AWS::S3::Bucket```

**Comment by amitsehgal** [comment]
Thanks for prompt response. here you go.
[prefix.txt](https://github.com/cloud-custodian/cloud-custodian/files/5342433/prefix.txt)
[storage-class.txt](https://github.com/cloud-custodian/cloud-custodian/files/5342434/storage-class.txt)

**Comment by kapilt** [comment]
fix merged
