### ISSUE TITLE
S3 Object Ownership

### ISSUE THREAD

**Issue by pendyalal** [cloud-custodian/cloud-custodian#6190]
**Is your feature request related to a problem? Please describe.**
   Enforce Object Ownership at S3 bucket level.

**Describe the solution you'd like**
New objects uploaded to the bucket with bucket-owner-full-control canned ACL will be owned by the bucket owner. This does not affect ownership of existing objects.

**Describe alternatives you've considered**
If you want to enforce object ownership, update your bucket policy to allow other AWS accounts to upload objects only when the PUT request includes the bucket-owner-full-control canned ACL. This would cause client PUT requests to fail if they do not include this ACL.

**Additional context**
              - name: s3-bucket-ownership
                resource: s3
                region: us-east-1
                filters:
                  - type: check-bucket-ownership
                    state: false
                actions:
                  - type: toggle-bucket-ownership
                    ExpectedBucketOwner: BucketOwnerPreferred

**Comment by kapilt** [comment]
suggested names filter ~ ownership  for action ~ set-ownership with param value: [BucketOwnerPreferred, ObjectWriter]

expected bucket ownership is actually smething else entirely afaict

https://awsapichanges.info/archive/changes/dcfed1-s3.html

**Comment by pendyalal** [comment]
Yes, you are right Kapit, ExpectedBucketOwnership is different from OwnershipControls.

**Comment by kapilt** [comment]
you can already do this via statement enforcment on a bucket policy.

**Comment by pendyalal** [comment]
@kapilt , For the newly created objects we can set the object ownership with the bucket policy. What happens to the existing objects?
