### ISSUE TITLE
aws.event-rule features needed

### ISSUE THREAD

**Issue by dlut2** [cloud-custodian/cloud-custodian#6199]
Problem: too many stale cloudwatch event rules in AWS account.  I want to clean up unused rules with custodian.
running on version 0.9.6

**Describe the solution you'd like**
 For the aws.event-rule resource:
1) I need a "delete" action, and there might need to be a "force" option for this (remove Targets), because boto3 will not delete event rules with targets.
2) I want to be able to filter event rules having no Targets, or "Invalid" Targets. In the context of rule cleanup, it is desirable to: a) remove rules that have no targets
b) remove rules that point at non-existent Lambdas

I have a policy to find rules that are "DISABLED" and also query cloudwatch metrics to determine if the rules have not been invoked/triggered for the past X days. I was surprised there was no "delete" action after writing this wonderful filter 👍 

Thanks!

**Comment by kapilt** [comment]
sounds useful

**Comment by kapilt** [comment]
so we would need a generic capability to resolve an arn to a custodian resource type to be able to detect the invalid listener targets. we'll effectively need to disable lazy loading for this filter, as we'll need to load the full resource set. looking over our extant resource metadata we don't always collect the arn type which we'll need to do universally to enable resource resolution.  a quick script shows 131 resources with arn type metadata, and about 44 without, in this context afaics the only valid target missing arn metadata for event bridge/cwe is ecs.

**Comment by kapilt** [comment]
so the full list of things we would need to check wrt to validity of the event target, afaics the only thing we don't have a resource for atm is batch queue

        sqs="arn:{Partition}:sqs:{Region}:{Account}:{QueueName}",
        function="arn:{Partition}:lambda:{Region}:{Account}:function:{FunctionName}",
        function_qual="arn:{Partition}:lambda:{Region}:{Account}:function:{FunctionName}:{Version}",
        ecs_cluster="arn:{Partition}:ecs:{Region}:{Account}:cluster/{ClusterName}",
        ecs_task="arn:{Partition}:ecs:{Region}:{Account}:task-definition/{TaskDefinitionFamilyName}:{TaskDefinitionRevisionNumber}",
        kinesis="arn:{Partition}:kinesis:{Region}:{Account}:stream/{StreamName}",
        log="arn:{Partition}:logs:{Region}:{Account}:log-group:{LogGroupName}",
        ssm_adoc="arn:{Partition}:ssm:{Region}:{Account}:automation-definition/{AutomationDefinitionName}:{VersionId}",
        batch_job_def="arn:{Partition}:batch:{Region}:{Account}:job-definition/{JobDefinitionName}:{Revision}",
        batch_queue="arn:{Partition}:batch:{Region}:{Account}:job-queue/{JobQueueName}",
        step_func="arn:{Partition}:states:{Region}:{Account}:stateMachine:{StateMachineName}",
        code_pipe="arn:{Partition}:codepipeline:{Region}:{Account}:{PipelineName}",
        code_build="arn:{Partition}:codebuild:{Region}:{Account}:project/{ProjectName}",
        sns_topics="arn:{Partition}:sns:{Region}:{Account}:{TopicName}",
        sqs_queue="arn:{Partition}:sqs:{Region}:{Account}:{QueueName}"
