### ISSUE TITLE
Extract policies from usecases to separate yml file

### ISSUE THREAD

**Issue by jason-riddle** [cloud-custodian/cloud-custodian#62]
Right now it looks like policies are being embedded directory into .rst files. An example of this can be found here: https://github.com/capitalone/cloud-custodian/blob/master/docs/source/usecases/usecases/amicomp.rst

Can these be extracted into a separate yaml file and then inlined into the .rst file? This would be nice because then as a part of the tests you could validate that the examples are still valid for regression tests if cloud-custodian decides to implement a big change.

**Comment by kapilt** [comment]
sounds reasonable, what we need for that is also some way of embedding the yaml back into the docs. there's probably some restructured text directive/syntax for this.

**Comment by whit537** [comment]
Validating doc yaml is a first step. Ideally we'd actually _run_ the policies automatically to make sure the examples still work, but that would require probably another yaml block specifying a fixture policy to put AWS into the state assumed by the target yaml itself.

**Comment by kapilt** [comment]
a few users expressed interest in having a policy test runner, which would actually do something like that, by giving some fixtures (terraform or cfn) and then being able to run the policy and assert actions. 

for this issue, i think if we get back to distributing some sample policies it will go along way to helping users get started. the cis benchmark is a good target imo.

**Comment by whit537** [comment]
> a few users expressed interest in having a policy test runner

Looks like that is https://github.com/capitalone/cloud-custodian/issues/455.
