### ISSUE TITLE
azure - Error with schema and VS Studio Code

### ISSUE THREAD

**Issue by gussj** [cloud-custodian/cloud-custodian#6211]
**Describe the bug**
I tried a lot of times even with different schemas but I always receive:
`[Error - 1:15:59 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property '$ref' of null
  Code: -32603 `
or `Unable to parse content from '(working directory deleted for issue reporting but file is there)\schemu.json': Parse error at offset 0.`

**To Reproduce**
$ python3 -m venv custodian
$ source custodian/bin/activate
(custodian) $ pip install c7n
(custodian) $ pip install c7n_azure
custodian schema --json > schema.json

**Expected behavior**
Auto completion working in VS Studio Code

**Background (please complete the following information):**
 - OS: W10
 - Python Version: 3.9 but tried with 3.8 too
 - Custodian Version: 0.9.6
 - Cloud Provider: aws and azure

**Comment by kapilt** [comment]
what's your user configuration file for the jsonschema look like in vscode? you may have to give an absolute path to the file

**Comment by gussj** [comment]
![image](https://user-images.githubusercontent.com/12020620/95987907-71617a00-0dfe-11eb-914d-484bfed25ffb.png)

**Comment by kapilt** [comment]
just to note in your example you have the file called `schema.json` in your vscode config you have it called `schemu.json` which are different names.

**Comment by gussj** [comment]
just changed the name because I was testing with different files but is the same file.

**Comment by gussj** [comment]
Tried with the 0.9.7 and the same error appears. 
![image](https://user-images.githubusercontent.com/12020620/96183744-bb855100-0f0d-11eb-9282-ae13ce92b1d3.png)

**Comment by jtroberts83** [comment]
@gussj I will take a look at this tonight or tomorrow as I have never set the VS Code integration and this would be a good time for me to test it out

**Comment by gussj** [comment]
Thanks so much for taking this into account. Really appreciate the effort and work on this project :)

**Comment by jtroberts83** [comment]
> Thanks so much for taking this into account. Really appreciate the effort and work on this project :)
@gussj 
I worked on this last night and found the issue to be within the c7n_azure tool.  If I uninstalled c7n_azure and then outputted my schema.json for VS Code it works.  Not sure what exactly in the Azure schema is causing an issue but if you want to get it working for AWS and GCP now you can, we just need to further investigate the azure issue piece

**Comment by gussj** [comment]
Thanks so much. I will check to see if you found the error in the future since I'm really interested in this schema for azure.

**Comment by jtroberts83** [comment]
Once I got it working in VS Code I played around with it some and while it is useful in the sense that it shows you what options there are, it doesn't allow you to write policies without referring to the docs as it doesn't format the syntax properly when building filters/actions with it and it doesn't provide what different fields are under certain actions and filters so I still found referencing the docs more useful.  I could seeing it being useful to auto-complete some things for you which are simple 1 value options such as resource: or single value actions/filters like ** - delete** etc.  I have thought about reinventing this wheel and making it easier to install (maybe just via a VS Code extension) and adding additional functionality, notes on schemas for the different filters/actions etc but that would be down the road a ways.  If you have any experience building VS Code extensions or schemas, you are more than welcome to contribute and make the process smoother and better

**Comment by jtroberts83** [comment]
Also another thing to note is that it only worked with .yaml file extensions with the way it is setup via the custodian docs and it doesn't work with .yml files.  Not sure why but if you are having issues getting it to work without the azure bits that could be a cause

**Comment by kapilt** [comment]
through a lot of trial and error i was able to narrow this down to the logic app action which appears to have a broken schema.

**Comment by PoeBlu** [comment]
just a note I was able to get intelli-sense to work with VSCode and neovim with the COC-TSServer running in node.
