### ISSUE TITLE
aws - add whitelist for organization units in cross account filter

### ISSUE THREAD

**Issue by gelouko** [cloud-custodian/cloud-custodian#6243]
**Is your feature request related to a problem? Please describe.**
It's not possible to check cross-account resources while whitelisting specific Organization Units. One example of use-case is  to enable cross account in the organization BUT only for specific Organization Units (OUs from the same Business Unit, for example).

**Describe the solution you'd like**
A parameter in the cross-account filter called whitelist_org_unit_ids (or something similar) where we could have a list of org units to allow cross-account access.

**Describe alternatives you've considered**
I've considered allowing cross-account within the organization, but doing another level of blocks outside of custodian

**Comment by kapilt** [comment]
its pretty common to do enumeration of sets of accounts within orgs by id using cross-account filter, ie dev shouldn't talk to prod etc. thats best done by just maintaining a list of accounts and using value_from support in cross-account filter. 

supporting native ou semantics would be interesting, effectively this would be handling the additional global iam condition principalorgpath, and letting folks specify ou paths as prefixes. it **would** only be effective if *aws:PrincipalOrgPaths* was being using in the policy statement, we have no way in a leaf account to assume organization api access to resolve an ou id to its accounts for other conditions.

[0] https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-principalorgpaths

**Comment by gelouko** [comment]
But that solution adds quite some overhead if we have daily new accounts in the OUs/Org

Because it'd be necessary to add the new accounts to the filter and then if you're using mode: cloudtrail, you'd have to redeploy custodian to update the lambdas, right?

**Comment by kapilt** [comment]
you use an external data dictionary / aka json file in s3, and ref in your policy via whitelist_from, ie you don't update the policy you update the json data file.
