### ISSUE TITLE
KeyError exception for kms-key policies when there insufficient permissions to describe at least one key

### ISSUE THREAD

**Issue by griffint61** [cloud-custodian/cloud-custodian#6245]
**Describe the bug**
A Python `KeyError `exception is thrown for kms-key policies when the policy is run under an IAM role for which there is at least one KMS key that may not be described due to insufficient permissions.

Trouble started in version 0.9.2 when in `class Key()` of kms.py the value of `arn` was changed from "KeyArn" to "Arn". Things have not worked right since because some parts of the code are still using "KeyArn".

In class `DescribeKey()`, in method `augment()`, in kms.py, in understandably catches `AccessDeniedException` exceptions and logs a warning. Unfortunately in that case `r['Arn']` never gets populated which causes a `KeyError` exception in method `get_arns()` of class `class QueryResourceManager()`

**To Reproduce**
1. Create a kms-key CloudCustodian policy.
2. Create an IAM role under which to run that policy.
3. Create at least one KMS key that is such that `DescribeKey` API call will fail with an `AccessDeniedException` for that IAM role.
4. Run the policy.

**Expected behavior**
No Python `KeyError` exception is thrown. Indescribable are keys ignored (other than the warning messages). All other KMS keys are acted on appropriately.

**Background (please complete the following information):**
 - OS: CentOS 8.2
 - Python Version: 3.6.8
 - Custodian Version: 0.9.7.0
 - Cloud Provider: aws
 - Policy:
```yaml
policies:
  - name: cis-benchmark-2-8
    resource: kms-key
    mode:
      type: pull
    filters:
      - type: value
        key: KeyManager
        value: CUSTOMER
      - type: value
        key: KeyState
        op: not-equal
        value: PendingDeletion
      - type: key-rotation-status
        key: KeyRotationEnabled
        value: False
    actions:
      - type: set-rotation
        state: True
```
 - Traceback: 
Traceback (most recent call last):
  File "/home/griffint61/.local/lib/python3.6/site-packages/c7n-0.9.7-py3.6.egg/c7n/commands.py", line 272, in run
    policy()
  File "/home/griffint61/.local/lib/python3.6/site-packages/c7n-0.9.7-py3.6.egg/c7n/policy.py", line 1179, in __call__
    resources = mode.run()
  File "/home/griffint61/.local/lib/python3.6/site-packages/c7n-0.9.7-py3.6.egg/c7n/policy.py", line 285, in run
    resources = self.policy.resource_manager.resources()
  File "/home/griffint61/.local/lib/python3.6/site-packages/c7n-0.9.7-py3.6.egg/c7n/query.py", line 509, in resources
    resources = self.augment(resources)
  File "/home/griffint61/.local/lib/python3.6/site-packages/c7n-0.9.7-py3.6.egg/c7n/query.py", line 565, in augment
    return self.source.augment(resources)
  File "/home/griffint61/.local/lib/python3.6/site-packages/c7n-0.9.7-py3.6.egg/c7n/resources/kms.py", line 79, in augment
    return universal_augment(self.manager, resources)
  File "/home/griffint61/.local/lib/python3.6/site-packages/c7n-0.9.7-py3.6.egg/c7n/tags.py", line 97, in universal_augment
    for arn, r in zip(self.get_arns(resources), resources):
  File "/home/griffint61/.local/lib/python3.6/site-packages/c7n-0.9.7-py3.6.egg/c7n/query.py", line 596, in get_arns
    arns.append(r[arn_key])
 - `custodian version --debug` output
Custodian:   0.9.7
Python:      3.6.8 (default, Apr 16 2020, 01:36:27) 
             [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
Platform:    posix.uname_result(sysname='Linux', nodename='el8-64', release='4.18.0-193.19.1.el8_2.x86_64', version='#1 SMP Mon Sep 14 14:37:00 UTC 2020', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

argcomplete==1.11.1
attrs==19.3.0
boto3==1.12.39
botocore==1.15.39
docutils==0.15.2
importlib-metadata==1.6.0
jmespath==0.9.5
jsonpickle==1.3
jsonschema==3.2.0
pyrsistent==0.16.0
python-dateutil==2.8.1
pyyaml==5.3.1
s3transfer==0.3.3
setuptools==39.2.0
six==1.14.0
tabulate==0.8.7
urllib3==1.25.8
zipp==3.1.0

**Additional context**
Also reproduced with master branch as of commit ba827c6d0704a560b156a860ab0bd89c2b750eec.

From 0.9.2 to 0.9.6 the failure mode was different. For some reason the exception thrown by the `DescribeKey` API call was not getting caught at all.

**Comment by ajkerrigan** [comment]
This was addressed in #6624. Going forward you should see the expected behavior for the AccessDenied case - you'll be able to see an alias and its target key ID, but not match any other key details.
