### ISSUE TITLE
Any filters for Azure Subnets association with Network security groups

### ISSUE THREAD

**Issue by farookhus** [cloud-custodian/cloud-custodian#6254]
I'm looking for the filters to list the azure subnets that are missing the network security group association.  Unfortunately there are no direct  filters under Vnet for filtering the subnets. I was able to use the generic " Value " filter to list the resources that are missing subnet association with network security groups. Below is the filter that I used, but the results are not matching as expected and during the review I found the filter missed to list a resource that has multiple subnets on which few are associated with security group and few not.

Any suggestion would be much appreciate 

    resource: azure.vnet
    filters:
      - type: value
        key: properties.subnets[*].properties.networkSecurityGroup
        op: contains
        value: empty

**Comment by stefangordon** [comment]
Your JMESPath is returning a list of network security groups, so when you have multiple subnets and some are missing NSG then those elements are simply omitted, you won't get empty values in the list.   

There are a few ways you could do it, one way would be to use a more sophisticated JMESPath that swaps in a default value if there is no `networkSecurityGroup`

For example this will return the Network Security Group value, or the string `missing` if there isn't one.
```
key: map(&(networkSecurityGroup || `missing`), properties.subnets[*].properties)
``` 
So you can do a `value: missing` with your `op: contains` (or `op: in` and `value-type: swap`).

**Comment by djghosthd** [comment]
C:\Windows\system32>az network public-ip list --query "{address: [1].ipAddress||'0'}
{"address": "0"}
C:\Windows\system32>az network public-ip list --query "{address: [0].ipAddress||'0'}
{ "address": "40.117.32.110" }
C:\Windows\system32>az network public-ip list --query "{address: [*].ipAddress||'0'}
{ "address": ["40.117.32.110"]} 

could you please help me out with this for individual index the output is coming as expected but when trying by using wildcard expression the output is not as expected

**Comment by stefangordon** [comment]
@djghosthd looks like a question for https://github.com/Azure/azure-cli? 

Closing this issue as I think we resolved the original request.
