### ISSUE TITLE
aws - cross account doesn't understand AROA:i-*

### ISSUE THREAD

**Issue by PratMis** [cloud-custodian/cloud-custodian#6255]
**Is your feature request related to a problem? Please describe.**
Yes, we have a situation where we have `'AROAXXXXX:i-XXXX` as one of the Principal in kms key resource based policy and cross-account filter is throwing an IndexError while it parses the Principal
https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/filters/iamaccess.py#L38

**Describe the solution you'd like**
Check if the length is greater than 4 then return

**Describe alternatives you've considered**
just return if the value in the list starts with `AROA`

**Additional context**

**Comment by PratMis** [comment]
@kapilt , would it make sense to whitelist AROA numbers here i.e. mark them as compliant? Since, they represent deleted IAM roles/users. Putting an AROA number for existing role/user converts itself to the real arn automatically

**Comment by kapilt** [comment]
with the fix in #7062 we'll treat aroa principals as having an explicit account id of none, you can explicitly white list that account id if you want that behavior in this context.
