### ISSUE TITLE
gcp-periodic mode using http gets permission error when scheduler job tries to trigger cloud function

### ISSUE THREAD

**Issue by ethanwlo** [cloud-custodian/cloud-custodian#6266]
**Describe the bug**
Not sure if it's a bug or a feature request since GCP is still beta. I ran a gcp-periodic mode policy which deployed a Cloud Scheduler job and Cloud Function with Http trigger successfully. But Cloud Scheduler job did not have auth header setup so it gets permission error when scheduler job tries to trigger cloud function via HTTP.

**To Reproduce**
Ran this policy
`
policies:
  - name: custodian-periodic-test
    resource: gcp.sql-instance
    mode:
      type: gcp-periodic
      service-account: 'testing123@project-id.iam.gserviceaccount.com'
      schedule: '0 0 * * 1-5'
`

**Expected behavior**
I've played around with it. If I manually setup Auth header by adding OIDC token to the Cloud Scheduler job using the service-account 'testing123@project-id.iam.gserviceaccount.com', permission issue goes away and scheduler job triggers cloud function correctly.

**Comment by ethanwlo** [comment]
Perhaps add to this code here https://github.com/cloud-custodian/cloud-custodian/blob/3fcb56a5a28deb2815d39be97487e6c8e5b0f2c1/tools/c7n_gcp/c7n_gcp/mu.py#L575?

Cloud Scheduler job supports OAuth and OIDC. But OAuth didn't work. So maybe it doesn't make sense to make auth a configurable thing in policy in this case since there's only one option that works with http?

**Comment by kapilt** [comment]
gcp switched out authentication modes on functions last year, we need to switch from doing periodics via http to using pub/sub to avoid the pain points.

**Comment by ethanwlo** [comment]
This is the pretty good article written in August of this year about how to setup Cloud Scheduler Job to trigger private cloud function via HTTP. https://cloud.google.com/community/tutorials/using-scheduler-invoke-private-functions-oidc

_To use a private Cloud Function, you need to send the request with sufficient authentication identification. Cloud Scheduler automates this for you by allowing you to specify multiple kinds of authentication headers. An OpenID Connect (OIDC) token is the most general way to provide this. By creating a service account that has only the ability to invoke functions, then assigning that as the identity of the function and as the OIDC service account, you can implement authentication scheduled invocation of your function._

**Comment by kapilt** [comment]
that requires us generating a separate service account, we don't generally do that in custodian, because iam is typically walled of separate on provisioning/api access for creation, alternatively would be policies with embedded credentials, again not something we do. we're just going to ditch http and move to pub/sub for cloud scheduler periodic.

**Comment by ethanwlo** [comment]
My thought process on this was the service account would've been pre-created outside of custodian and the gcp-periodic policy would simply reference it? In fact, there's already **service-account** in the schema for the Cloud Function side.

About embedding credentials, it seems like if I chose OIDC on the Cloud Scheduler, I only needed to provide the name of the service-account (same one the Cloud Function is assuming) and don't need to use any private key or any additional credentials. This is all I had to set up to trigger the function.

![Screen Shot 2020-11-03 at 2 14 51 PM](https://user-images.githubusercontent.com/33111973/98030562-3809a200-1ddf-11eb-8182-ed8917cf6d4f.png)

**Comment by kapilt** [comment]
thats fair re reference to service account and that sounds reasonable to support, but i think we'll still want to switch to default pub/sub as its less to configure for the user, is there a concern with pub/sub, just wondering why http endpoint is useful.

**Comment by ethanwlo** [comment]
Would the pub/sub option require one pub/sub topic per gcp-periodic policy or it can re-use the same pub/sub topic for multiple? If it's one topic per gcp-periodic policy, I suppose we have to add Custodian support to actually create the pubsub topic as well?

No concern really from security or operations standpoint. In fact having a queue sitting between would make handling concurrency more predictable. Just one more component that a mugc-like service will need to clean up if policy is no longer needed.

**Comment by kapilt** [comment]
its one topic per periodic policy, custodian already has support for creating the pub/sub topic as we use it for doing api audit log response (cloudtrail style) policies. at least for gcp serverless we already have support for deleting things, we do need to wire processing gcp serverless policies that into mugc though, but its a relatively light lift.

**Comment by kapilt** [comment]
#6362 fixes functions execution with periodic and trigger type pub-sub.
