### ISSUE TITLE
SQS messages are not delivering to email/SNS

### ISSUE THREAD

**Issue by pattem1986** [cloud-custodian/cloud-custodian#6275]
Messages in SQS queue are not processing messages for delivery. Can you please let me know whats wrong with my template?
I am using below mailer template 

"type":"notify",
"template":"default",
"subject":"testing the c7n mailer",
"priority_header":"2",
"to":[
   "name@xyz.com"
],
"transport":{
   "type":"sqs",
   "queue":"https://sqs.eu-central-1.amazonaws.com/12345678923/custodian-tagging-test"

PS: Lambda running successfully

**Comment by pattem1986** [comment]
@kapilt Hi Kapil, can you please help me.

**Comment by kapilt** [comment]
what's in your logs for the c7n-mailer lambda

**Comment by pattem1986** [comment]
[custodian logs.txt](https://github.com/cloud-custodian/cloud-custodian/files/5511821/custodian.logs.txt)

**Comment by pattem1986** [comment]
my python code which gets tag policy for all aws resources


import os
from c7n import handler
import json


config = dict()
config['policies'] = list()
config['execution-options'] = dict()

role_arn = os.environ['ROLE_ARN']

config['execution-options']['metrics_enabled'] = "aws://?namespace=Custodian"

resources = ['aws.acm-certificate', 'aws.ami', 'aws.app-elb', 'aws.app-elb-target-group', 'aws.asg', 'aws.cache-cluster', 'aws.cache-snapshot', 'aws.cfn', 'aws.cloud-directory', 'aws.cloudhsm-cluster', 'aws.codebuild', 'aws.customer-gateway', 'aws.dax', 'aws.directory', 'aws.distribution', 'aws.dms-instance', 'aws.dynamodb-table', 'aws.ebs', 'aws.ebs-snapshot', 'aws.ec2', 'aws.ec2-reserved', 'aws.ecr', 'aws.ecs', 'aws.ecs-container-instance', 'aws.ecs-service', 'aws.ecs-task', 'aws.ecs-task-definition', 'aws.efs', 'aws.elasticbeanstalk-environment', 'aws.elasticsearch', 'aws.elb', 'aws.emr', 'aws.eni', 'aws.fsx', 'aws.fsx-backup', 'aws.glacier', 'aws.glue-crawler', 'aws.glue-dev-endpoint', 'aws.glue-job', 'aws.healthcheck', 'aws.hostedzone', 'aws.iam-role', 'aws.iam-user', 'aws.internet-gateway', 'aws.kinesis', 'aws.kms-key', 'aws.lambda', 'aws.launch-template-version', 'aws.log-group', 'aws.message-broker', 'aws.nat-gateway', 'aws.network-acl', 'aws.network-addr', 'aws.peering-connection', 'aws.rds', 'aws.rds-cluster', 'aws.rds-snapshot', 'aws.redshift', 'aws.redshift-snapshot', 'aws.rest-api', 'aws.rest-stage', 'aws.route-table', 'aws.s3', 'aws.sagemaker-endpoint', 'aws.sagemaker-endpoint-config', 'aws.sagemaker-job', 'aws.sagemaker-model', 'aws.sagemaker-notebook', 'aws.sagemaker-transform-job', 'aws.secrets-manager', 'aws.security-group', 'aws.sns', 'aws.sqs', 'aws.ssm-parameter', 'aws.step-machine', 'aws.streaming-distribution', 'aws.subnet', 'aws.transit-attachment', 'aws.transit-gateway', 'aws.vpc', 'aws.vpn-connection', 'aws.vpn-gateway', 'aws.workspaces']
filters = [{'and': [{'tag:Owner': 'absent'},
                    {'tag:owner': 'absent'}]},
                      {'and': [{'tag:aws:cloudformation:stack-name': 'absent'},
                               {'tag:aws:cloudformation:stack-id': 'absent'},
                               {'tag:aws:cloudformation:logical-id': 'absent'}]}]
actions = [{"type": "notify",
            "template": "default",
            "subject": "testing the c7n mailer",
            "priority_header": "2",
            "to":["email@gmail.com"],
            "transport": {
                "type": "sqs",
                "queue": "https://sqs.eu-central-1.amazonaws.com/12345678934/custodian-tagging-test"}}]
# actions = []
mode = {"type": "periodic",
        "schedule": "rate(24 hours)",
        "role": role_arn}

for resource in resources:
    policy = dict()
    policy['name'] = f"{resource}-tag-compliancy"
    policy['resource'] = resource
    policy['filters'] = filters
    policy['actions'] = actions
    policy['actions'][0]['subject'] = f"{resource} is not compliant"
    policy['mode'] = mode
    config['policies'].append(policy)

def run(event, context):
    handler.policy_config = config
    return handler.dispatch_event(event, context)

**Comment by pattem1986** [comment]
issue resolved. error was due to mailer lambda absent and not processing SQS queue messages.
