### ISSUE TITLE
Mugc ignored Global Services policy with region and did not remove policy from other regions

### ISSUE THREAD

**Issue by IngussNeilands** [cloud-custodian/cloud-custodian#6289]
**Describe the bug**
According to documentation `https://cloudcustodian.io/docs/aws/examples/accountservicelimit.html` added region to one of our policies. Did redeploy and pipeline c7n-org step did update policy in specified us-east-1 region, but mugc step did not remove from us-east-2

**To Reproduce**
deploy policy for resource s3 in 2 regions: us-east-1 and us-east-2
add region: us-east-1 to the policy
deploy using c7n-org
run mugc

**Expected behavior**
I would expect mugc to remove policy from all other regions

**Background (please complete the following information):**
 - Python Version: [e.g. python 3.8.1] virtual environment CPython3.8.3.final.0-64
 - Custodian Version: [e.g. 0.8.46.1] c7n 0.9.6, c7n-mailer 0.6.5, c7n-org 0.6.5
 - Tool Version: [if applicable] codebuild pipeline
 - Cloud Provider: [e.g. gcp, aws, azure] aws
 - Policy: [please exclude any account/sensitive information]
```yaml
policies: 
   - name: list-buckets
      resource: s3
      region: us-east-1
```

**Additional context**

**Comment by kapilt** [comment]
the cli params here a little unclear, are you doing --region all, if you targeted to a particular region ie. --region us-east-2 does it do the right thing?

**Comment by IngussNeilands** [comment]
sorry, I am using c7n-org with multiple accounts each with own set of regions. then i combine all policies in single file to make mugc command possible. in that context region is added to policy and c7n-org correctly deploys it in marked region.

**Comment by kapilt** [comment]
adding region to a policy pins it to one region.

my previous question was i'm looking for the parameters that your using to invoke mugc.py (sans role)

your steps to reproduce note two different deploys which seems odd, mugc doesn't look at the policy region its using the regions that are passed to it on the cli. are you executing mugc with c7n-org?

**Comment by rymancl** [comment]
Any chance of getting #6989 merged so that this can be fixed?

I'm running into this issue. Short synopsis:
* run c7n-org to deploy policies to multiple regions (us-west-2, us-east-2)
* remove region us-east-2 from my c7n-org accounts.yml files
* run mugc

Policy functions in us-east-2 are not removed.

I tried three options:
> c7n-org run-script -s tmp -c $config "$(which python3) $(pwd)/scripts/mugc.py -c $FILES"

and

> c7n-org run-script -r all -s tmp -c $config "$(which python3) $(pwd)/scripts/mugc.py -c $FILES"

and

> c7n-org run-script -r us-east-2 -s tmp -c $config "$(which python3) $(pwd)/scripts/mugc.py -c $FILES"

($FILES is a string of policy files)
