### ISSUE TITLE
aws.elasticsearch - Add cross-account filter and remove-statements actions

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#6304]
**Is your feature request related to a problem? Please describe.**
As a cloud security engineer I would like to be able to run a c7n policy which checks my elasticsearch domains resource policy for cross-account permissions and remediates any overly permissive cross-account permissions via a remove-statements action. (See SNS cross-account filter and remove-statements action for example)

**Describe the solution you'd like**
A very similar filter and action to SNS cross-account filter and remove-statements actions

**Describe alternatives you've considered**
No other solutions I can think of to achieve this currently without going outside of c7n

**Additional context**
Thank you

**Comment by kapilt** [comment]
closed in #6225
