### ISSUE TITLE
AWS - elasticsearch cross-cluster-search-connections Value Filter

### ISSUE THREAD

**Issue by Lucas-Irvine** [cloud-custodian/cloud-custodian#6319]
**Is your feature request related to a problem? Please describe.**
We want to limit the aws accounts that elasticsearch domains are able to connect with. More specifically, we want to ensure that elasticsearch cross cluster search connections only connect between internal elasticsearch domains

**Describe the solution you'd like**
Extend the value filter on the results of describe_inbound_cross_cluster_search_connections and describe_outbound_cross_cluster_search_connections so that we can enforce checks on the SourceDomainInfo.OwnerId and ConnectionStatus.StatusCode.

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by kapilt** [comment]
sounds good

**Comment by Lucas-Irvine** [comment]
@kapilt Do you think this makes sense as two filters, one for inbound connections and one for outbound connections, or one filter? My concern with one filter is that it might be hard to distinguish which are inbound and which are outbound connections, and that outbound connections seem to have an extra field called ConnectionAlias.

**Comment by kapilt** [comment]
i would do it as one filter but with an "cross-connections" with an 'inbound' and 'outbound' section although potentially its just `connections` if there's utility in determining in filtering on in account connections. note the cross-account filter here should also be able to detect cross cluster connections going across accounts as it requires resource iam policy modification.

**Comment by ajkerrigan** [comment]
Closed via #7230
