### ISSUE TITLE
importlib-metadata conflict between c7n-mailer 0.6.8 and c7n 0.9.9

### ISSUE THREAD

**Issue by jantman** [cloud-custodian/cloud-custodian#6359]
**Describe the bug**

When attempting to install the latest releases (c7n==0.9.9 and c7n-mailer==0.6.8), there is a conflict between the importlib-metadata requirement versions. 

**To Reproduce**

```
virtualenv --python=python3.8 foo
source foo/bin/activate
pip install c7n c7n-mailer
...
ERROR: c7n-mailer 0.6.8 has requirement importlib-metadata==3.1.1; python_version >= "3.6", but you'll have importlib-metadata 1.7.0 which is incompatible.
```

If I run this install with a requirements file and under Python 3.9.1 instead, it's quite a bit worse, as the install fails:

```
ERROR: Cannot install -r requirements.txt (line 1) and -r requirements.txt (line 2) because these package versions have conflicting dependencies.

The conflict is caused by:
    c7n 0.9.9 depends on importlib-metadata==1.7.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0"
    c7n-mailer 0.6.8 depends on importlib-metadata==3.1.1; python_version >= "3.6"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

**Expected behavior**

No version conflicts would be found.

**Background (please complete the following information):**
 - OS: Arch Linux and Alpine 3.12 docker
 - Python Version: 3.8.5 on Arch, 3.9.1 on Alpine/docker
 - Custodian Version: 0.9.9
 - Tool Version: mailer 0.6.8

**Additional context**

I really don't know much about Poetry, or the poetry.lock and pyproject.toml files. But I can confirm that the importlib-metadata versions in poetry.lock conflict between c7n and c7n-mailer.

I believe this may be related to #6178

**Comment by kapilt** [comment]
ugh.. we'll need to cut a new release to address. my functional test against test-pypi pre push to prod pypi was just c7n_azure and custodian packages, i'll add c7n_mailer to the mix.

**Comment by jantman** [comment]
Heh, ok, thanks. I'm sure the releng side of things is getting pretty crazy with... what is it... 10 packages now?!?!

**Comment by kapilt** [comment]
mostly automated out of the makefile thankfully, make pkg-increment, make pkg-publish-wheel, make pkg-rebase (update deps) ... the challenge has actually been this importlib-metadata has been causing some conflicts the last two releases and needs manual addressing.

**Comment by jantman** [comment]
@kapilt I know this is a weird time of year for many of us - I was just on vacation for two weeks - but I was wondering if there is any chance of getting a fix for this?

**Comment by kapilt** [comment]
fix is merged on trunk, looking at next monday for a release.

**Comment by jantman** [comment]
Cool, thanks!!!

**Comment by kapilt** [comment]
mailer - 0.6.9 released with fix

**Comment by jantman** [comment]
Yay! Thank you so much!
