### ISSUE TITLE
feat: Generic Helm Chart?

### ISSUE THREAD

**Issue by desponda** [cloud-custodian/cloud-custodian#6367]
**Is your feature request related to a problem? Please describe.**
After some googling I am unable to find a generic helm chart that runs cloud custodian on kubernetes via a job or cron job type schedule. It would be great if there was an open source way community supported helm chart to deploy cloud custodian to kubernetes clusters. I might have missed one if one already exists but if not I'm happy to PR/contribute one that I'm am starting on.

**Describe the solution you'd like**
A helm 3 chart that provides an easy, opinionated way to deploy cloud custodian using kubernetes cron jobs and config maps

**Describe alternatives you've considered**
Cloud custodian already provides ways to deploy to ec2 instances and lambdas but as user of a multi-cloud solutions (AWS, Azure, GCP) would like to use a unified way of deploy cloud custodian to my already-existing kubernetes clusters

**Additional context**
If this is something that is wanted, would be happy to open a PR to this repo or new repo for this deployment

**Comment by kapilt** [comment]
hey continuing the discussion from gitter, I think this would be useful, I'll start a separate helm repo in the GitHub org re where a dedicated repo for it.

**Comment by kapilt** [comment]
here's a repo for a pr https://github.com/cloud-custodian/helm-charts

**Comment by desponda** [comment]
@kapilt opened up https://github.com/cloud-custodian/helm-charts/pull/1 will probably go through a couple of iterations before merge ready but welcome feedback on structure / initial features
