### ISSUE TITLE
azure - network security group - filter rules from source or to destination

### ISSUE THREAD

**Issue by lkakarla** [cloud-custodian/cloud-custodian#6379]
**Is your feature request related to a problem? Please describe.**
The use case is to find ingress rules allowed from specific/any source as well as egress rules allowed to specific/any destination for specific port.

**Describe the solution you'd like**
Add an optional argument to ingress/egress type filters to provide source and destination as a parameter to filter NSG rules.

**Describe alternatives you've considered**
I used value filter to get source (properties.securityRules[].properties.sourceAddressPrefix) and destination(properties.securityRules[].properties.destinationAddressPrefix) values. But it's not helping me to fulfil my use case. I need to filter port & source/destination values in same filter condition.

**Comment by h-dub** [comment]
@lkakarla Can you clarify the use case with an example policy? I want to make sure we fully understand what variations you need to locate. 

We should be able to stack value filters together to get simple string filtering against the address /port fields. For more advanced CIDR style matching we would need to think about adding some code to the NSG filter so it works like other areas of custodian.

Thanks!
-Hugh

**Comment by h-dub** [comment]
Looks rational to me.
Would be happy to assist you with getting this committed next week.
Can you sign the contrib agreement?
https://cloudcustodian.io/docs/contribute.html

Thanks!
-Hugh

**Comment by lkakarla** [comment]
@h-dub Thanks for your reply and assistance. I already submitted/signed the Individual Agreement couple of hours ago.

Thanks,
--Lakshmi

**Comment by kapilt** [comment]
fwiw, the default value filter supports cidr math, the extant implementation of nsg filter is odd in that its not reusing that support and is manual reimplementing matches instead of just subclassing that.

**Comment by kapilt** [comment]
merged on the pr, thanks
