### ISSUE TITLE
Content supply chain security

### ISSUE THREAD

**Issue by h-dub** [cloud-custodian/cloud-custodian#6382]
C7N's supply chain attack vectors can be divided into two major categories: Software and Content.

* The Software vector concerns all C7N direct dependencies of code and platform. All of the libraries consumed, all of the OS run on.
* The Content vector concerns user authored policy content executed by C7N

Only the Content vector is in scope for this discussion.

## What and Why

* C7N is a domain specific scripting language sourced through yaml policy elements
* All modern scripting languages require a method to protect script source against tampering
* C7N has no intrinsic tamper protection for policy elements

Assuming a basic source controlled setup. The current policy chain of custody is:

``` engineer -> PR -> master -> clone -xx-> execute ```

After the clone link, you can no longer prove the origin or authenticity of the policy using C7N directly. All content security is assumed to be provided by the platform C7N is running on. In the common case, this is just the ACL on the directory containing the policy files. Advanced cases may be doing their own signing/hashing verification scheme using platform tools.

proposed policy chain of custody:

``` engineer -> PR -> sign -> master -> clone -> load -> verify -> execute ```

The policy chain of custody is maintained from creation to execution. The platform security requirements for content are reduced to securing the public key and command line arguments going into C7N execution.

## How 

The user interface would look something like the following commands:
```
# Generate key pair
openssl genrsa -des3 -out foo.pem 4096
openssl rsa -in foo.pem -outform PEM -pubout -out foo-public.pem

# Sign a policy
custodian sign --signed foo.pem foo.yaml

# Require a policy being ran is signed by a known public key
custodian run -s foo --signed foo-public.pem foo.yaml

# Verify a policy's signature
custodian validate --signed foo-public.pem foo.yaml

```

The signature goes into the policy as a watermark:
```
# Policy-Signature: <SOME SIGNATURE>
policies:
  - name: offhours-stop
    resource: ec2
    filters:
      - type: offhour
        weekends: false
        default_tz: pt
        tag: downtime
        opt-out: true
        onhour: 8
        offhour: 20
```

Implementation outside of command line stuff. No new deps are added. RSA support comes from the existing cryptography reference.
* utils.load_file()
  * gets a new argument named keys which is an array of paths to public keys used for verification.
  * if keys are supplied and the file being loaded is yaml, check signature and raise an error if invalid.
* cli._default_options
  * adds --signing <keyfile> to options
* policy.load()
  * sends the keys specified in options to the updated utils.load_file()
* sign_file() added to utils and plumbed through to cli
* verify_file() added to utils and plumbed through to cli

## When
Now :)

## Notes

* Tamper protection enforcement has to be optional
* Policy signing would be done by a CI task with access to protected signing keys
* Signing keys should also be loadable from env variable directly. Enables secrets manager scenarios that eliminates most security concerns around key handling.
* Policy signing might be part of a CI's logical publish step
* Signing might need an interactive path for PEM password entry
* Runtime supports multiple keys for transparent key rotation
* Some enveloping with key identification would make it nicer

**Comment by kapilt** [comment]
this isn't custodian's responsibility. this is the responsibility of the invoker/caller of custodian to provide trusted policy files. ie. custodian policy files are trusted assets from custodian's perspective, the basic threat model this is attempting to protect against is broken if the attacker is already on the system with write access to policy files on disk, they already have access to the api credentials (instance metadata server) which renders the entire exercise moot imo.  

the basic premise here "All modern scripting languages require a method to protect script source against tampering" is faulty as afaics no scripting languages provide for this.

**Comment by h-dub** [comment]
Browsers implement it via CSP
Powershell via codesign
Windows native via authenticode
.Net via strong naming

**Comment by kapilt** [comment]
again its unclear what this is attempting to protect against, the threat model that's in the issue reads to me like its effectively closing the window after the fox is in the hen house. custodian follows a unix design philosophy of composable tools with discrete purposes. this is even more important in the context of security, where there are dozens of signing tools which have been audited by security professionals for this exact purpose.  browser csp its not about cryptographic verification of the source its to prevent cross site requests, but the origin site's content is not verified in any manner. the other examples from windows, .net strong naming and windows native presuppose third party binary distribution channels without source access which is not the case with custodian policies. moreover the docs for .net strong naming make it clear this is not really a security mechanism afaics https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named which has these gems, lol 
- "For .NET Core, strong-named assemblies do not provide material benefits.",
- "If you are an open-source developer and you want the identity benefits of a strong-named assembly for better compatibility with .NET Framework, consider checking in the private key associated with an assembly to your source control system." 
 
anyways, if we look at common  languages (ruby, python, javascript, julia, rust, golang,) none of them do source signing. moreover the implementation proposal here ends up just shifting the attack surface to the ci system as a privileged holder of key material, a much better approach is to use something like tuf (https://theupdateframework.com/) which is designed to survive ci system compromise in these exact scenarios. but again, none of this is custodian's responsibility.
