### ISSUE TITLE
Try running c7n-org on local machine.

### ISSUE THREAD

**Issue by gohackfelipe** [cloud-custodian/cloud-custodian#6385]
Hi all, 

I'm trying to run my first policy using c7n-org as the documentation but unfortunately i'd received the error below:

`Access denied api:AssumeRole policy:my-first-policy account:account-name region:us-east-1`

I'd already created an IAM user attaching a policy as the link [https://cloudcustodian.io/docs/deployment.html](https://cloudcustodian.io/docs/deployment.html)

``` json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "CustodianLambdaPermissions",
            "Effect": "Allow",
            "Action": [
                "cloudwatch:PutMetricData",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DeleteNetworkInterface",
                "ec2:CreateNetworkInterface",
                "events:PutRule",
                "events:PutTargets",
                "iam:PassRole",
                "lambda:CreateFunction",
                "lambda:TagResource",
                "lambda:CreateEventSourceMapping",
                "lambda:UntagResource",
                "lambda:PutFunctionConcurrency",
                "lambda:DeleteFunction",
                "lambda:UpdateEventSourceMapping",
                "lambda:InvokeFunction",
                "lambda:UpdateFunctionConfiguration",
                "lambda:UpdateAlias",
                "lambda:UpdateFunctionCode",
                "lambda:AddPermission",
                "lambda:DeleteAlias",
                "lambda:DeleteFunctionConcurrency",
                "lambda:DeleteEventSourceMapping",
                "lambda:RemovePermission",
                "lambda:CreateAlias",
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "logs:CreateLogGroup"
            ],
            "Resource": "*"
        }
    ]
}
```

What is missing? What i should do ?

That's my version being used toc7n==0.9.8  and c7n-org==0.6.8.

**Comment by kapilt** [comment]
the trust document on the iam role in the target account as configured in accounts.yml config needs to allow for the c7n-org executing user/principal to be able to access it via sts assume role. there are several examples in the aws documentation for how to do  multi-account access best practice via sts.

**Comment by gohackfelipe** [comment]
Yeah, i got it. I found one.

[https://aws.amazon.com/pt/premiumsupport/knowledge-center/iam-assume-role-cli/](https://aws.amazon.com/pt/premiumsupport/knowledge-center/iam-assume-role-cli/)

Problem solved. Thanks @kapilt .
