### ISSUE TITLE
Add AWS "event-selector" filter 

### ISSUE THREAD

**Issue by yathi-sysdig** [cloud-custodian/cloud-custodian#6392]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to filter cloudtrail trails based on `IncludeManagementEvents` and `ReadWriteType`. This filter will enable implementing controls in `CIS Amazon Web Services Foundations Benchmark version 1.3.0` (https://www.cisecurity.org/benchmark/amazon_web_services/). 

**Describe the solution you'd like**
We propose adding an `event-selector` filter to the existing AWS `cloudtrail` resource. 
The proposal is to be able to do something like,

```
    """Filter a cloudtrail by its related Event Selectors.
    :Example:
    .. code-block:: yaml
        policies:
          - name: cloudtrail-event-selectors
            resource: aws.cloudtrail
            filters:
            - type: event-selectors
              key: EventSelectors[].IncludeManagementEvents
              value: True
    """
```    

**Describe alternatives you've considered**
We implemented this using the AWS CLI call.
```
aws cloudtrail get-event-selectors --trail-name <trailname shown in describe- trails>
```
This forces us to use the CLI on top of cloud-custodian whereas a simple extension to cloud-custodian will address the issue.

**Additional context**
We will be opening a PR on this issue. Specifically, we would like to implement this control from CIS benchmark. For example,

```
3.1 Ensure CloudTrail is enabled in all regions 
Ensure there is at least one Event Selector for a Trail with IncludeManagementEvents set to true and ReadWriteType set to All
```

**Comment by kapilt** [comment]
thanks for the pr.

**Comment by marfasegal** [comment]
bumping this up - any timeline for this one?

**Comment by kapilt** [comment]
merged
