### ISSUE TITLE
Add Execution Summary to Outputs, Streaming Support

### ISSUE THREAD

**Issue by whoami-zhangster** [cloud-custodian/cloud-custodian#6395]
**Is your feature request related to a problem? Please describe.**

We need to store output for archival purposes (and debugging), to accomplish this we are currently using the `--output-dir` flag in order to output logs and resource records for this purpose. With a large amount of executions, storing multiple files per execution is costly and debugging for issues across multiple files is cumbersome. 

**Describe the solution you'd like**
* Everything proposed below is fully backwards compatible and will not affect any current users. 

1) For an `--execution-summary` flag to be added, when this flag is included an execution summary is included at exit in logs and directory output. 

Execution summary can be derived within ctx.py where the log, metadata, and resource information can be serialized to JSON. 

Default `--execution-summary` flag would expose log, metadata, and resource information. If you don't require (for example) the resource information you can do the following:
`--summary-include logs --summary-include metadata`

2) Would also like to add a streaming output for durability and to have a mechanism to batch the archival of execution runs. With execution summary this could store thousands of executions in one blob drastically decreasing the number of blobs need to be stored. 

example running `-stream-output kinesis://<stream-name> --execution-summary --summary-include logs --summary-include metadata`

would create an execution summary JSON including logs and metadata, then output the summary to the respective stream. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kapilt** [comment]
so let me try and recap, your saying the primary pain point is dealing with large number of objects.

1. we could provide an alternate storage format that is more execution oriented, a blob object per execution, configured via url parameter
2. you could setup archival rules to clean out older executions no longer via blob store lifecycle mgmt
3. streaming has a number of challenges wrt to trying to simply drop extant blob content into it, you would lose audibility of executions wrt to resource state (if you drop resources) or have to deal with packetization of stream outputs across multiple resources, etc, oddly the most common technique for arbitrary sized stream packets is to drop a ref to a storage blob in the stream packet.  streams are also not archival in most usage contexts so it presumes a bunch of custom one off code implemented per user to do something useful with the stream, which doesn't sound useful either.

**Comment by whoami-zhangster** [comment]
Yes

1. Sounds great, I have already started a change and have gotten a working execution-output format that is essentially the log output, metadata, and resources all within one blob. This is tied to the flyweight ctx and essentially is flushed by the output at close, following the same pattern that is currently being used. However, I have accomplished this via flags, is there a specific url param format which you would prefer?

2. We have archival rules, however we still have a lot of files being written/stored and it is becoming quite costly.  

3. Definitely 100% agree with you on all the challenges to stream processing. However for a more execution oriented storage format/output you could have one entry reflective of one execution, not having the need to deal with packetization; each entry in the stream would be reflective of one execution event. In terms of archiving I am not sure any custom one off code is required, I believe the 3 major cloud providers all provide solutions to accomplish this: AWS has Kinesis which can pipe to Kinesis Firehose and then aggregate messages to S3, Azure works in a similar fashion with Event Hubs and Blob storage, and (not 100% sure) GCP provides pub/sub message to their cloud blob storage using Dataflow. Very interested to hear your perspective on this, but I think this can provide configurable windowing of archival (per n hours, per day).

**Comment by kapilt** [comment]
1. i saw the implementation, that's not what i'm referencing. an execution can span max stream packet size, ie 256kb. i'm simply referencing the extant blob store impl with a different transfer which is a different in that the impl you have will have fragmentation issues.
2. noted, but what's the magnitude here, ie can you clarify cost concern in this context? cost is based on usage and scales linearly to it per extant impl.
3. again streaming fragmentation is within an execution, which renders non aware downstream somewhat moot.

**Comment by kapilt** [comment]
1. your right kinesis is 1mb on packet/record limit, sqs/sns/cwe are 256kb, gcp is 10mb, azure is wacky it can go as low as 40k for a storage queue but depends on your pricing tier, event hub std is 256kb, to 1mb based for premium pricing.
2. the enclosure would just be a zip file of the current files as a single blob per execution
3. it might not be for your environment and use cases, but it would definitely cause fragmentation in other envs and usages.

**Comment by kapilt** [comment]
this seems like an issue best handled downstream wrt to aggregating records by sending output to a staging area for post processing, notionally the only thing for upstream here is an optional alternative enclosure, which i'll file as a separate issue. there isn't any real utility on streaming that i can see given the difficulties of doing anything useful for the outputs (custom), and breaking common workflows on reporting. the utility here seems pretty marginal in comparision to the carry cost and seems very specific to a particular deployment usage needs.

**Comment by whoami-zhangster** [comment]
Hi @kapilt I had forgotten to mention that another reason we would like to add the new output format as well as streaming is regards to collection information on policies executing on Lambda. 

- Having to join on the current output format would be complicated and all the data required isn't available to output. 
- We have a number of accounts each with a large number of these Lambdas running, aggregating on these log groups would be very difficult; we were thinking a unified sink like a stream could be a good bus for this data.

What are your thoughts on this? Do you think I should open a separate issue on this topic?

**Comment by kapilt** [comment]
streaming support has a number of issues which i've already tried to outline, the output format changes would work for lambda as well. you seem to be overly focused on a particular set of non public use cases and with pre-disposition on implementation on those. 1. all the output is in the format, and your join comment needs elaboration. 2. we're not talking about log groups, we're talking about blob storage. its not really my place to design your custom stuff, its to help folks contributing to the project and community.

**Comment by whoami-zhangster** [comment]
I am not talking about blob storage in the message from today, sorry if I wasn't more clear; I was trying to point out there was also another reason for the output change other than blob storage. And that is for getting the same set of data from the lambda executions and I believe another output format would benefit the project and the community. 

The reason being is that when Lambda executes and writes to a respective log group, the data is split up and written line by line, each prefixed with a uuid. To be able to store/archive information WRT a Lambda Execution, we would have to join on these. I believe it would be helpful to other users to have an execution summary they can basically utilize for this purpose.
