### ISSUE TITLE
Custodian Policy deployment from inside CloudFormation Stack

### ISSUE THREAD

**Issue by IngussNeilands** [cloud-custodian/cloud-custodian#6398]
Hi,

I am kinda trying to find a solution here.

The environment:
  Control Tower provisioned Multi-account AWS environment covering multiple regions per account
  Some accounts have different set of regions

  Custodian has 100+ policies
  Some account / region combinations have specific policies on top of regular ones

Pipeline nicely deploys required policies in all account/region targets, but it takes more than 1 hour to complete ...

First challenge: complete time is over 1 hour and grows when new policies are added.

Second challenge: Since accounts are added automatically (using Control Tower), Custodian requires accounts config update and pipeline rebuild.

So I am wondering if there is a way how to deploy Custodian using StackSets?

Starting small - what would be the way to put Custodian Policy deployment from inside CloudFormation Stack?

**Comment by kapilt** [comment]
re 2, its fairly easy to automate update of accounts.yml as accounts are created (lambda), or just to run the generator script before each run. as a project we don't assume or dictate how people do deployments, there are myriads of ways organizations approach devops wrt to tools and procedures. which also means its unclear what your setup is. 

re 1 wrt to pipeline exec time, its unclear how your setup or why an account change requires a 'pipeline rebuild'. if your using c7n-org it will go parallel based on compute resources. ie 1 hr over n accounts, y regions, with x policies, using z compute resources, are they lambda policies or poll policies, etc. is 1hr a problem, if so why? and what's the target. 

re 3, its not officially supported but we do have a cloud formation script for policy resource provisioning in tools/dev
