### ISSUE TITLE
cloud custodian to use updated jsonpickle 1.4.2

### ISSUE THREAD

**Issue by mloa7** [cloud-custodian/cloud-custodian#6399]
Does cloud custodian have plan to support jsonpickle 1.4.2. Security scans that I run are flagging jsonpickle 1.3 with a critical vulnerability.

**Comment by kapilt** [comment]
jsonpickle isn't a direct dependency of custodian, its a downstream dependency for aws-xray-sdk ie. no code in this repo uses it directly. we currently ship frozen dep sets to ensure repeatable installs, it will get updated for the next release when we rebase/update deps.

**Comment by mloa7** [comment]
> jsonpickle isn't a direct dependency of custodian, its a downstream dependency for aws-xray-sdk ie. no code in this repo uses it directly. we currently ship frozen dep sets to ensure repeatable installs, it will get updated for the next release when we rebase/update deps.
