### ISSUE TITLE
azure - keyvault - enumeration does not include common fields

### ISSUE THREAD

**Issue by lkakarla** [cloud-custodian/cloud-custodian#6420]
**Describe the bug**
resources.json file content is having only limited information about cloud resource. For example, Azure Key vault latest template has a lot more attributes as mentioned in https://docs.microsoft.com/en-us/azure/templates/microsoft.keyvault/vaults link.

But when we run custodian policy for keyvault resource, it's generating resources.json file with following limited info.

{
    "id": "/subscriptions/<value>/resourceGroups/<value>/providers/Microsoft.KeyVault/vaults/<value>",
    "name": "<value>",
    "type": "Microsoft.KeyVault/vaults",
    "location": "eastus",
    "tags": {
      "environment": "<value>"
    },
    "resourceGroup": "<value>"
}

**To Reproduce**
Create a key vault resource in Azure Portal and run following policy to pull the information.

policies:
  - name: az-keyvault-list
    resource: azure.keyvault

**Expected behavior**
Its expected to pull information about resource as per latest ARM template

**Background (please complete the following information):**
 - OS: Ubuntu
 - Python Version: 3.6.9
 - Custodian Version: 0.9.10
 - Tool Version: NA
 - Cloud Provider: Azure
 - Policy: [please exclude any account/sensitive information]
```yaml
policies:
  - name: az-keyvault-list
    resource: azure.keyvault
```

 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output

Custodian:   0.9.10
Python:      3.6.9 (default, Oct  8 2020, 12:12:24)
             [GCC 8.4.0]
Platform:    posix.uname_result(sysname='Linux', nodename='demo-vm02', release='5.4.0-1039-azure', version='#41~18.04.1-Ubuntu SMP Mon Jan 18 14:00:01 UTC 2021', machine='x86_64')
Using venv:  True
Docker: False
Installed:
PyJWT==1.7.1
adal==1.2.5
applicationinsights==0.11.9
apscheduler==3.6.3
argcomplete==1.12.2
attrs==20.3.0
azure-cli-core==2.16.0
azure-cli-telemetry==1.0.6
azure-common==1.1.25
azure-core==1.8.2
azure-cosmos==3.2.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.4.0
azure-graphrbac==0.61.1
azure-keyvault==1.1.0
azure-mgmt-apimanagement==0.1.0
azure-mgmt-applicationinsights==0.2.0
azure-mgmt-authorization==0.60.0
azure-mgmt-batch==7.0.0
azure-mgmt-cdn==4.0.0
azure-mgmt-cognitiveservices==5.0.0
azure-mgmt-compute==10.0.0
azure-mgmt-containerinstance==1.5.0
azure-mgmt-containerregistry==2.8.0
azure-mgmt-containerservice==8.3.0
azure-mgmt-core==1.2.1
azure-mgmt-cosmosdb==0.11.0
azure-mgmt-costmanagement==0.1.0
azure-mgmt-databricks==0.1.0
azure-mgmt-datafactory==0.8.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-dns==3.0.0
azure-mgmt-eventgrid==2.2.0
azure-mgmt-eventhub==3.1.0
azure-mgmt-hdinsight==1.7.0
azure-mgmt-iothub==0.10.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-logic==3.0.0
azure-mgmt-managementgroups==0.2.0
azure-mgmt-monitor==0.7.0
azure-mgmt-msi==1.0.0
azure-mgmt-network==9.0.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==0.4.0
azure-mgmt-rdbms==1.9.0
azure-mgmt-redis==6.0.0
azure-mgmt-resource==6.0.0
azure-mgmt-resourcegraph==2.0.0
azure-mgmt-search==2.1.0
azure-mgmt-sql==0.16.0
azure-mgmt-storage==7.2.0
azure-mgmt-subscription==0.5.0
azure-mgmt-web==0.44.0
azure-nspkg==3.0.2
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-queue==2.1.0
bcrypt==3.2.0
boto3==1.16.59
botocore==1.19.59
c7n==0.9.10
certifi==2020.6.20
cffi==1.14.3
chardet==3.0.4
click==7.1.2
colorama==0.4.4
cryptography==2.9.2
distlib==0.3.1
humanfriendly==8.2
idna==2.10
importlib-metadata==3.4.0
importlib-resources==3.3.0
isodate==0.6.0
jmespath==0.10.0
jsonpickle==1.3
jsonschema==3.2.0
knack==0.7.2
msal==1.0.0
msal-extensions==0.1.3
msrest==0.6.19
msrestazure==0.6.4
netaddr==0.7.20
oauthlib==3.1.0
paramiko==2.7.2
pkginfo==1.6.1
portalocker==1.7.1
pycparser==2.20
pygments==2.7.2
pynacl==1.4.0
pyopenssl==19.1.0
pyrsistent==0.17.3
python-dateutil==2.8.1
pytz==2019.1
pyyaml==5.4.1
requests==2.24.0
requests-oauthlib==1.3.0
s3transfer==0.3.4
setuptools==52.0.0
six==1.15.0
tabulate==0.8.7
typing-extensions==3.7.4.3
tzlocal==2.1
urllib3==1.26.2
zipp==3.4.0

**Additional context**
NA

**Comment by stefangordon** [comment]
By default custodian calls the list API endpoint for the resource, which returns the data you are seeing:
https://docs.microsoft.com/en-us/rest/api/keyvault/vaults/list

We have several child resources too for enumerating the keys and secrets, and a few custom actions and filters.   Let me know more about your scenario and I can tell you if it is possible today.

It may be that we need to enhance the key vault resource with the ability to augment with individual `GET` calls to retrieve the rest of the data since a few important fields like the `URI` aren't available in the enumeration.

**Comment by stefangordon** [comment]
Tracked in #6485 as a feature request, will close this.
