### ISSUE TITLE
aws - config-poll-rule mode - Resource type event-rule-target 

### ISSUE THREAD

**Issue by guptavishal4** [cloud-custodian/cloud-custodian#6425]
**Describe the bug**
Resource type aws.event-rule-target does not work.

**To Reproduce**
1. Create below policy
2. Execute dryrun

**Expected behavior**

**Background (please complete the following information):**
 - Custodian Version: 0.9.10
 - Cloud Provider: aws
 - Policy: 
```yaml
policies:
  - name: XXXX
    resource: event-rule-target
    description: Target policy
    mode:
      type: config-poll-rule
      role: CloudCoreCustodianRole
      schedule: TwentyFour_Hours
```
```
custodian run --dryrun --profile XXXX --cache-period 0 -s ./tmp EventBridge.yaml 
2021-02-02 15:54:57,296: custodian.commands:ERROR invalid policy file: EventBridge.yaml error: policy:%s resource:%s does not have a cloudformation type and is there-fore not supported by config-poll-rule
2021-02-02 15:54:57,297: custodian.commands:ERROR Found 1 errors.  Exiting.
```

**Comment by kapilt** [comment]
config only supports recording issues against things which are represented in cloudformation schema registry, an event rule target is not an independent cfn resource. it only exists as a property of an event rule.

**Comment by guptavishal4** [comment]
Can you point me to a sample policy for this resource type?

**Comment by kapilt** [comment]
simply ditch your mode, the rest of the policy is orthogonal
