### ISSUE TITLE
AWS Backup Vault resource needs a cross-account filter to analyze resource policy permissions

### ISSUE THREAD

**Issue by matt-hutchins** [cloud-custodian/cloud-custodian#6426]
**Is your feature request related to a problem? Please describe.**

Currently cloud custodian does not return the resources policy so an analyst cannot check permission configurations at this time.

**Describe the solution you'd like**

I would like to have a cross-account filter added so that I can perform permission checks to ensure a properly configured Backup Vault

**Describe alternatives you've considered**

NA

**Additional context**

This is for writing a policy that would prevent accidental or intentional deletion of backups from the vault.

**Comment by kapilt** [comment]
backup vaults only support cross-account access within an organization and additionally require an access policy on the customer managed key as an additional constraint.

**Comment by kapilt** [comment]
iotw traditional use of cross-account policy makes little sense for this usage.
