### ISSUE TITLE
public api gateway -  delete action on rest api 

### ISSUE THREAD

**Issue by pingoleon108** [cloud-custodian/cloud-custodian#6429]
Hello, I'm planning to make all future created API gateways are private and terminate/modify all non-private (public & regional) gateways.

I was able to find the resources with the following policy
policies:
  - name: security-api-public
    resource: rest-api
    description: Remediate a public API and notify infosec. 
    mode:
      type: cloudtrail
      events:
        - source: apigateway.amazonaws.com
          event: CreateRestApi
          ids: requestParameters.createRestApiInput.endpointConfiguration.types
      role: arn:aws:iam::{account_id}:role/security-role
    filters:
      - type: event
        key: endpointConfiguration.types
        value:
          - REGIONAL
          - EDGE
        op: intersect
    actions:
      - delete

However the resource API is not deleted.

Cloudwatch logs:
`SNIP...
        "requestParameters": {
            "createRestApiInput": {
                "name": "api-test",
                "endpointConfiguration": {
                    "types": [
                        "EDGE"
                    ],
SNIP...
[WARNING]	2021-02-03T19:52:15.704Z	69b95359-ede8-49f4-a1c0-d79213f8ccbf	Custodian reserves policy lambda tags starting with custodian - policy specifies custodian-info

SNIP...
[INFO]	2021-02-03T19:52:15.704Z	69b95359-ede8-49f4-a1c0-d79213f8ccbf	Found resource ids:['EDGE']

SNIP..
[INFO]	2021-02-03T19:52:15.942Z	69b95359-ede8-49f4-a1c0-d79213f8ccbf	Resources []`

Could you help me to understand if there is a bug or if my policy is not properly created?
Also is there any way to repeat this for WebSocket API and HTTP API?

Please let me know if you need further context on this matter or any questions. Thanks in advanced.

**Comment by kapilt** [comment]
the ids expression in the mode should point to the api gateway id in the response, your currently pointing the ids expression to the literal array ['EDGE'] which doesn't correspond to a gateway instance.

**Comment by pingoleon108** [comment]
Awesome! This made the trick

  - name: security-api-public
    resource: rest-api
    description: Remediate a public API and notify infosec. This will remove the non compliance resource.
    mode:
      type: cloudtrail
      events:
        - source: apigateway.amazonaws.com
          event: CreateRestApi
          ids: responseElements.restapiUpdate.restApiId
      role: arn:aws:iam::{account_id}:role/role
      - type: value
        key: endpointConfiguration.types
        value:
          - REGIONAL
          - EDGE
        op: intersect
    actions:
     -type: delete

Thanks a lot

**Comment by pingoleon108** [comment]
Closing this.
