### ISSUE TITLE
Allow For Richer Policy Metadata

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#6445]
**Is your feature request related to a problem? Please describe.**
I would like to be able to store richer metadata in my policies metadata field.  Currently it supports a string 

**Describe the solution you'd like**
Allow objects/arrays to be used in the metadata field so I can use a more advanced data structures

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by kapilt** [comment]
to be fair currently metadata field supports a dictionary of strings to simple types. that said richer fields sounds reasonable.

**Comment by JohnHillegass** [comment]
@jtroberts83 I was just thinking about this the other day. Originally @kapilt and I were thinking the basic dict types would be enough but having the ability to do mappings/objects really opens up a new world of opportunity there.

**Comment by JohnHillegass** [comment]
You guys ok with me taking this one up? I've been aching to make a contribution lately and this seems like a good starter.

**Comment by JohnHillegass** [comment]
Resolved in #6509
