### ISSUE TITLE
aws - cloud watch alarm - tag support

### ISSUE THREAD

**Issue by aambikapathi** [cloud-custodian/cloud-custodian#6454]
Currently AWS Cloud watch alarm tags are not supported. Please include support for Cloud watch alarm tags. This would help us to validate and take action on the alarm creation.

**Comment by kapilt** [comment]
any interest in contributing?

**Comment by aambikapathi** [comment]
Yes. I am trying to setup in windows environment. It has only ubuntu instructions is there any windows instruction to setup developer environment?

**Comment by kapilt** [comment]
i haven't used windows in a few decades.. easiest might just be doing it in a virtual machine or using vscode with a devcontainer, @stefangordon any tips wrt ^

**Comment by stefangordon** [comment]
Hi @aambikapathi  - I do lots of Custodian development on Windows so happy to help.   

One option is certainly just to leverage WSL (Windows Subsystem for Linux) and work entirely in Ubuntu.  VSCode and PyCharm both work fine in this scenario.  VSCode requires you to use this [extension ](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) to run inside WSL.

Most everything also works fine directly in Windows, except a few of the scripts or `makefile` shortcuts.  On Windows I usually use Conda for my virtual environment (but `virtualenv` can work too).    Just clone, create and environment, and `pip install -r requirements-dev.txt`.  

You can run `pytest` there just fine as the custodian docs mention, and if you want to do a full `tox` test run I'd recommend just running the included docker container with the command:

```
docker build -t tox_linux . -f tools/dev/docker_tox_linux/Dockerfile && docker run -it tox_linux
```

**Comment by PratMis** [comment]
@aambikapathi we have added tagging support for CW Alarms. Closing this
