### ISSUE TITLE
Issues running dynamodb as a config rule

### ISSUE THREAD

**Issue by jmahowald-slalom** [cloud-custodian/cloud-custodian#6470]
**Describe the bug**
Running a simple tag filter on dynamodb does not work when running as a config-rule, while  the same policies run locally or in lambda periodic do work

**To Reproduce**
Have some dynamodb table in an account, apply policy.  Failure manifests in the created lambdas logs

**Expected behavior**
Policy to run and either find a match or none

**Background (please complete the following information):**

 - Custodian Version: 0.9.10

 - Cloud Provider: aws
 - Policy: [please exclude any account/sensitive information]
```yaml
policies:
- name: dynamodb-tag-config-compliance
  resource: aws.dynamodb-table
  mode:
    type: config-rule
    role: custodian
  filters:
  - or:
    - "tag:Name": absent
    - "tag:Contact": absent
    - "tag:Environment": absent

```
 - Traceback: [if applicable, please exclude sensitive/account information]

```
[ERROR] TypeError: unsupported operand type(s) for /: 'datetime.datetime' and 'float'
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 4, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 165, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 1140, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 853, in run
    resources = super(ConfigRuleMode, self).run(event, lambda_context)
  File "/var/task/c7n/policy.py", line 437, in run
    resources = self.resolve_resources(event)
  File "/var/task/c7n/policy.py", line 835, in resolve_resources
    return [source.load_resource(self.cfg_event['configurationItem'])]
  File "/var/task/c7n/resources/dynamodb.py", line 23, in load_resource
    resource['CreationDateTime'] = datetime.fromtimestamp(resource['CreationDateTime'] / 1000.0)
```

**Comment by kapilt** [comment]
yeah.. this hack was added before we ended up handling datetime conversion generically in the config source, we can effectively just remove all that code.
