### ISSUE TITLE
Add config support for ECS

### ISSUE THREAD

**Issue by PratMis** [cloud-custodian/cloud-custodian#6506]
**Is your feature request related to a problem? Please describe.**
We have a lot of ecs task definitions(100K+) in our environment and are running into api throttling issue for controls around task definitions.

**Describe the solution you'd like**
AWS recently rolled out Config support for ECS resources(https://aws.amazon.com/about-aws/whats-new/2021/02/aws-config-supports-amazon-container-services/)

**Describe alternatives you've considered**

**Additional context**

**Comment by kapilt** [comment]
what percent of those ecs task definitions are just garbage (not used) lying around? is that something that would be helpful wrt to cleanup. re config support sure.

**Comment by JohnHillegass** [comment]
Based off of some preliminary testing, about 90% are unused. It's hard to gauge though because while we can scan services, task sets and scheduled tasks to extract the definition arns and extrapolate which ones are in use, the list_tasks api (when scanning for stopped status) will only spit out that last hour or so of runs. That list_tasks scan limitation is an issue because of the potential for one off tasks, or things created from external processes like lambda. 

We have a PFR out for adding a lifecycle rule on the definitions to track last used date and help with cleanup but there is no ETA yet.

**Comment by kapilt** [comment]
intriguing challenge ;-) so basically due to the possibility of adhoc one off tasks, there's no clear mechanism to apriori safely clean out tasks defs. i think there's still some utility in a cleanup here, with guidance to app teams to reuse ref'd defs for those tasks (aka command override). 

anyways... regardless of that we should move forward with config support.

**Comment by PratMis** [comment]
Doesn't seem to be saving us re: number of api calls being made :( . I had never looked up the config code but looks like it still makes one api call per resource to get the data?
```
“api-stats”: {
    “config.SelectResourceConfig”: 1,
    “config.ListDiscoveredResources”: 217,
    “config.GetResourceConfigHistory”: 21699
  },
```

**Comment by kapilt** [comment]
The value is not making the call to the service api and applications using
it for other purposes, like say deploying ;)

**Comment by kapilt** [comment]
actually that's a good question, what's the actual policy (sanitized, ofc)? we will generally do a select on the resource in the policy, but for related filters, we'll use get_resources which typically does a getresourceconfighistory.

**Comment by PratMis** [comment]
The policy I ran for testing was:

```
policies:
  - name: ecs-task-defn-filter
     resource: ecs-task-definition
     source: config
```
It didn't have any filters. Reading the code, I found that we make one api call per resourceId to config to get the configuration of the underlying resource 
Code: https://github.com/cloud-custodian/cloud-custodian/blob/f855016a3e8289c5179c26b2851a8aa32b25b317/c7n/query.py#L295

**Comment by kapilt** [comment]
aha.. this more brokenness from config :-)  we try to do select resources which can give us everything in a single shot.. but config is so broken in what resources they claim to support, but do so differentially by each api in the service, that we automatically failover to do a listing if select returns nothing. another piece of feedback you can take to your tam.. re config should support selectresourceconfig for all services they purport/pretend to support.

**Comment by kapilt** [comment]
we should probably log this with a warning, and feedback in custodian cli runs. also you can self confirm this broken support for selectresources in the ui by attempting to do a query on that  resource type.

**Comment by PratMis** [comment]
I think to use the select resource api we would need a mandatory query field as stated in the docs? Else it falls back to the list api

**Comment by kapilt** [comment]
what docs and fields are you referencing?

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/config.html#ConfigService.Client.select_resource_config
https://docs.aws.amazon.com/config/latest/developerguide/query-components.html

for select resources we do have an expression with fields ie  type.. ie. this works for lots of resource types, it doesn't work for anything config team has added in the last year / 18+ months.

**Comment by PratMis** [comment]
yep, understood what you're saying here!! I tested the query in the console also, it's returning returning some random number of resources every time I test it. With falling back to the GetResourceConfigHistory api, it beats the purpose atleast in our use case. Bumped it up to our TAM to see what's going on :)

**Comment by kapilt** [comment]
so you had linked this repo in a separate issue, but it effectively lists the resources which are actually supported by config for select resources, https://github.com/awslabs/aws-config-resource-schema/tree/master/config/properties/resource-types

**Comment by PratMis** [comment]
AWS got back to me, looks like they prematurely released the Config ECS support document lol. Technically, as per them Config Cmdb should show 0 resources and I just verified that. Last week we got back resources(ecs-task-definition) from config cmdb but this week its showing 0 resources
