### ISSUE TITLE
S3 BucketKey set to True

### ISSUE THREAD

**Issue by pendyalal** [cloud-custodian/cloud-custodian#6536]
**Is your feature request related to a problem? Please describe.**
Configuring your bucket to use an S3 Bucket Key with SSE-KMS for new objects to reduce the cost of sse-kms

**Describe the solution you'd like**
- name: s3-enable-default-encryption-kms
            resource: s3
            actions:
              - type: set-bucket-encryption
              # enabled: true <------ optional (true by default)
                crypto: aws:kms
                key: 1234abcd-12ab-34cd-56ef-1234567890ab
                **bucketkey: true**

**Describe alternatives you've considered**

**Additional context**

**Comment by thisisshi** [comment]
This looks straight forward here, docs: https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucket-key.html

Only caveat is that users need to be aware that the calling principal also needs kms:Decrypt permissions, but with the default key and SSE it's not an issue

**Comment by kapilt** [comment]
i'm somewhat shocked this wasn't the service default here, most other services naturally enable this for their kms integration, espcially data plane heavy ones (sqs for an example). we should do this post-haste :-)
