### ISSUE TITLE
Assess Potential Github Action Vulnerabilty

### ISSUE THREAD

**Issue by slott56** [cloud-custodian/cloud-custodian#6541]
Github recommend that you audit for both unwanted pull requests and abuse by the GITHUB_TOKEN.

1. Assess commits made during the bug window, February 4,2021 18:42 UTC to February 5, 2021 13:35 UTC.
2. Assess workflow files for unauthorized injection during the bug window.
3. Assess pull_request_target and pull_request workflow runs, and examine those pull requests during the bug window to look for unauthorized activity. Ignore pull requests from known users with write permissions.
4. Assess release history for any that may have been deployed via unauthorized GITHUB_TOKEN activity during the bug window.
5. Assess package history for any that may have been deployed via unauthorized GITHUB_TOKEN activity during the bug window.

**Comment by kapilt** [comment]
@slott56 i'm not sure what this in reference to, but please use security contact address (security@cloudcustodian.io) per the readme or contact me directly if this something related to custodian github org. afaics, this a user token advisory, but there's no notion about which user this in regards to, is this re your own access key?
