### ISSUE TITLE
azure - sqlserver - add more filters

### ISSUE THREAD

**Issue by lkakarla** [cloud-custodian/cloud-custodian#6551]
**Is your feature request related to a problem? Please describe.**
custodian unable to filter azure sqlservers with properties like azureADOnlyAuthentications, privateEndpointConnections etc.

**Describe the solution you'd like**
enhance azure.sqlserver resource to filter with foresaid options.

**Describe alternatives you've considered**
Alternative solution to use Azure CLI to directly filter resources without using custodian

**Comment by stefangordon** [comment]
Looks like these are separate arm resources that are children of the SQL server.  You'll get an array of private endpoint connections in our SQL Server response but its likely just an identifier and not the fields you want.

We'll need to add all of these child resources so you can query them.  We might also need some new child/parent filter options to make the policies easier to write.

**Comment by aakifshaikh** [comment]
Ikakarla- Can you please share your repository on AZURE cloud custodian policies. We recently deployed into Azure and we are trying to see what others have done so far.

**Comment by stefangordon** [comment]
SQL has many potential child resources that require custom filters.  The ones mentioned in this issue are now implemented so I will close this issue and we can open specific feature requests for any new fields we need in the future.
