### ISSUE TITLE
Does c7n-org run in parallel for AWS accounts? 

### ISSUE THREAD

**Issue by jcyriac-synamedia** [cloud-custodian/cloud-custodian#6570]
We are planning to replace our current AWS Config setup with Cloud Custodian. Our AWS Organization has 120+ accounts. 

c7n-org is a life saver for us. We are planning to run c7n-org once everyday in AWS Fargate. 

My question is, does c7n-org run in parallel for accounts? I can see that it runs in parallel for all regions, and all policies but does it run in parallel for the accounts?  

Any tips for running this for 120 accounts, 16 regions, and 18 policies? 

```
$ cat accounts.yml

accounts:
- account_id: '12321xxx'
  display_name: stage-blahh
  email: fblahh@blah.com
  name: '12321xxx'
  org_id: o-cccc
  regions:
  - all
  role: arn:aws:iam::12321xxx:role/ReadRole

- account_id: '585xxxxx'
  display_name: stage-blahh2
  email: finops-stage-blahh@blahh.com
  name: '585xxxxx'
  org_id: o-ccccc
```

```
$ cat policy.yml

policies:
  - name: redshift-cluster-public-access-check
    resource: redshift
    filters:
      - type: value
        key: PubliclyAccessible
        value: true
  - name: rds-snapshots-public-prohibited
    resource: rds-snapshot
    filters:
      - type: cross-account
        everyone_only: true
  - name: encrypted-volumes
    resource: aws.ebs
    filters:
      - type: value
        key: Encrypted
        value: false
```

**Comment by kapilt** [comment]
it runs in parallel for each account * region,  and serially / in order through the policies in a file, concurrency defaults to 4 * cpu cores, you can control that via environment variable C7N_ORG_PARALLEL
