### ISSUE TITLE
error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by advancedwebdeveloper** [cloud-custodian/cloud-custodian#6578]
Hi. I caught such bugs:

> Collecting vcrpy-unittest==0.1.7
>   Using cached vcrpy_unittest-0.1.7-py2.py3-none-any.whl (6.8 kB)
> Collecting parameterized==0.7.4
>   Using cached parameterized-0.7.4-py2.py3-none-any.whl (25 kB)
> Collecting fakeredis==1.4.1
>   Using cached fakeredis-1.4.1-py3-none-any.whl (34 kB)
> Requirement already satisfied: zipp>=0.5 in ./lib/python3.8/site-packages (from importlib-metadata==3.7.3->-r requirements.txt (line 21)) (3.4.1)
> Requirement already satisfied: setuptools in ./lib/python3.8/site-packages (from jsonschema==3.2.0->-r requirements.txt (line 28)) (44.0.0)
> Collecting sortedcontainers
>   Using cached sortedcontainers-2.3.0-py2.py3-none-any.whl (29 kB)
> Building wheels for collected packages: grpcio, retrying, netifaces, python-http-client, starkbank-ecdsa, lark-parser, python-hcl2
>   Building wheel for grpcio (setup.py) ... error
>   ERROR: Command errored out with exit status 1:
>    command: /home/oceanfish81/cloud-custodian/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t5ecr2q1/grpcio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t5ecr2q1/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-s8gknppk
>        cwd: /tmp/pip-install-t5ecr2q1/grpcio/
>   Complete output (8 lines):
>   ASM Builds for BoringSSL currently not supported on: linux-aarch64
>   Found cython-generated files...
>   usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>      or: setup.py --help [cmd1 cmd2 ...]
>      or: setup.py --help-commands
>      or: setup.py cmd --help
> 
>   error: invalid command 'bdist_wheel'
>   ----------------------------------------
>   ERROR: Failed building wheel for grpcio
>   Running setup.py clean for grpcio
>   Building wheel for retrying (setup.py) ... error
>   ERROR: Command errored out with exit status 1:
>    command: /home/oceanfish81/cloud-custodian/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t5ecr2q1/retrying/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t5ecr2q1/retrying/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-2944a7ja
>        cwd: /tmp/pip-install-t5ecr2q1/retrying/
>   Complete output (6 lines):
>   usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>      or: setup.py --help [cmd1 cmd2 ...]
>      or: setup.py --help-commands
>      or: setup.py cmd --help
> 
>   error: invalid command 'bdist_wheel'
>   ----------------------------------------
>   ERROR: Failed building wheel for retrying
>   Running setup.py clean for retrying
>   Building wheel for netifaces (setup.py) ... error
>   ERROR: Command errored out with exit status 1:
>    command: /home/oceanfish81/cloud-custodian/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t5ecr2q1/netifaces/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t5ecr2q1/netifaces/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-xlz09eg4
>        cwd: /tmp/pip-install-t5ecr2q1/netifaces/
>   Complete output (6 lines):
>   usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>      or: setup.py --help [cmd1 cmd2 ...]
>      or: setup.py --help-commands
>      or: setup.py cmd --help

Here is my environment:

> $ uname -a
> Linux ams1-c1-large-arm-01 5.4.0-40-generic #44-Ubuntu SMP Mon Jun 22 23:59:48 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

> $ cat  /etc/os-release
> NAME="Ubuntu"
> VERSION="20.04.2 LTS (Focal Fossa)"
> ID=ubuntu
> ID_LIKE=debian

> $ python3 --version
> Python 3.8.5

. The version of the project is

> $ git log -1
> commit 76e6b3aa3dc9fce6c05f213a3af2865e441cc92f (HEAD -> master, tag: 0.9.11.0, origin/master, origin/HEAD)
> Author: Stefan Gordon <stefan@stefangordon.com>
> Date:   Mon Mar 22 12:44:40 2021 -0700
> 
>     azure - fix dnszone tagging (#6563)
>

**Comment by kapilt** [comment]
Which command causes this error? Afaics your also running on arm64 Linux and grpc does not distribute binaries for this, see https://github.com/grpc/grpc/issues/21283 from a custodian perspective that should only impact the gcp provider.
