### ISSUE TITLE
resources needing tag support

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#660]
- [ ] emr
- [x] kinesis streams

**Comment by alfredgamulo** [comment]
EMR has tag but is still missing auto-tag-user
Kinesis Streams done with universal_taggable

**Comment by alfredgamulo** [comment]
@mandeepbal wanna take this one?

**Comment by FireballDWF** [comment]
This issue appears to be resolved as least by 0.27.2
