### ISSUE TITLE
GCP- dataflow deprecated view and now doesn't return complete information

### ISSUE THREAD

**Issue by anovis** [cloud-custodian/cloud-custodian#6600]
Looks like gcp deprecated the dataflow list ability to get all dataflow job information. It only returns `JOB_VIEW_SUMMARY `

https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.jobs/list

In order to get the required information a get call on every resource will be required. Should this be done on the resource level as an augmentation or in an additional filter since the jobs could be filtered on state in a value filter before the extra api calls.

**Comment by kapilt** [comment]
not quite sure i'm understanding the delta on the api. re the question, it would depend on if the summary metadata is useful by itself to express a policy against, if it is then it would be appropriate as a filter with annotation for the extended data, if its not then doing the augment works.

**Comment by anovis** [comment]
the `jobs.list` api now only returns `JOB_VIEW_SUMMARY` which returns Project ID, Job ID, job name, job type, job status, start/end time, and Cloud SDK version details, whereas the the` jobs.get` returns the full response (below) . Since so much information is missing I think it makes sense to augment.

```
{
  "id": string,
  "projectId": string,
  "name": string,
  "type": enum (JobType),
  "environment": {
    object (Environment)
  },
  "steps": [
    {
      object (Step)
    }
  ],
  "stepsLocation": string,
  "currentState": enum (JobState),
  "currentStateTime": string,
  "requestedState": enum (JobState),
  "executionInfo": {
    object (JobExecutionInfo)
  },
  "createTime": string,
  "replaceJobId": string,
  "transformNameMapping": {
    string: string,
    ...
  },
  "clientRequestId": string,
  "replacedByJobId": string,
  "tempFiles": [
    string
  ],
  "labels": {
    string: string,
    ...
  },
  "location": string,
  "pipelineDescription": {
    object (PipelineDescription)
  },
  "stageStates": [
    {
      object (ExecutionStageState)
    }
  ],
  "jobMetadata": {
    object (JobMetadata)
  },
  "startTime": string,
  "createdFromSnapshotId": string,
  "satisfiesPzs": boolean
}
```

**Comment by kapilt** [comment]
Sounds good we should probably do a default server side filter for active
as well to limit the query volume.
