### ISSUE TITLE
AWS - Add filter support for checking CloudWatch Log Metrics filters and alarms

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#6601]
**Is your feature request related to a problem? Please describe.**
I would like the ability to check and verify my AWS CloudWatch Log Metric filters and alarms to ensure they are setup correctly

**Describe the solution you'd like**
Within CloudWatch Logs I would like to check for the presence of certain log metric filters and alarms to meet security best practices

**Describe alternatives you've considered**
Currently this info isn't pulled into c7n so there isn't an alternative within c7n.

**Additional context**
Thank you!

**Comment by ajkerrigan** [comment]
The `aws.log-metric` resource and its associated `alarm` filter are available as of custodian 0.9.12.
