### ISSUE TITLE
AWS: event-rule resource type is missing for CloudWatch

### ISSUE THREAD

**Issue by aakifshaikh** [cloud-custodian/cloud-custodian#6604]
**Is your feature request related to a problem? Please describe.**
I am using the cloud custodian to identify both the number of insight-rule and event-rule. Feels like we have a resource type for insight-rule and not for event-rule. I tried using this insight-rule for EVENT-RULE and it didn't work.

**Describe the solution you'd like**
Want the count on event-rule. We want to know all the cloud custodian-created event rules so we can do cleanup tasks.

**Comment by kapilt** [comment]
aws.event-rule and aws.event-rule-target are extant custodian resources.
