### ISSUE TITLE
azure - multi-cloud missing credential scope and c7n-org doesn't set cloud endpoints

### ISSUE THREAD

**Issue by d-van** [cloud-custodian/cloud-custodian#6613]
**Describe the bug**
When running `custodian run`  targeting a non-public cloud will produce an error even with the correct credentials. This happens because cloud custodian is not setting the `credential_scopes` for the given cloud. It always defaults to the commercial endpoint which will cause failures for non-public clouds

When running `c7n-org`, it never sets the cloud endpoints for non-public clouds. 

These 2 go hand in hand as c7n-org will fail if the credential scopes are not set properly during a run.

**To Reproduce**
`custodian run`
1. Set your credentials via `az login` or environment vars
2. Attempt to run `custodian run` against a simple policy
    - `custodian run -s . --region=AzureUSGovernment simple_policy.yml`
3. An error will be produced:
```
The access token has been obtained for wrong audience or resource 'https://management.azure.com'. It should exactly match with one of the allowed audiences 'https://management.core.usgovcloudapi.net/','https://management.core.usgovcloudapi.net','https://management.usgovcloudapi.net/','https://management.usgovcloudapi.net'.
```

`c7n-org run`
1. Set your credentials via environment vars
2. Attempt to run `c7n-org run` against a single subscription within azure gov with a simple policy
    - `c7n-org run -c azure_gov_account.yml -s output -u simple_policy.yml --region=AzureUSGovernment`
3. An error will be produced:
```
Error: (SubscriptionNotFound) The subscription 'xyz' could not be found.
2021-04-06 11:12:20,665: c7n_org:ERROR Exception running policy:simple_policy.yml account:subscription_name region:AzureUSGovernment error:(SubscriptionNotFound) The subscription 'xyz' could not be found.
```

**Expected behavior**
Both `custodian run` and `c7n-org run` runs against azure gov or other non-public clouds.

**custodian run** 
```
custodian.azure.session:INFO Authenticated [Principal | xyz]
custodian.policy:INFO policy:simple_policy resource:azure.vm region:AzureUSGovernment count:3 time:9.45
```

**c7n-org run**
```
c7n_org:INFO Ran account:subscription_name region:AzureUSGovernment policy:simple_policy matched:3 time:5.60
c7n_org:INFO Policy resource counts Counter({'policy:simple_policy': 3})
```

**Background:**
 - OS: OS Big Sur 11.2.3
 - Python Version: python 3.9.2
 - Custodian Version: 0.9.11
 - Cloud Provider: azure
 - Policy:
```yaml
---
policies:
  - name: all-vms
    resource: azure.vm
```
```
Custodian:   0.9.11
Python:      3.9.2 (default, Feb 24 2021, 13:26:09) 
             [Clang 12.0.0 (clang-1200.0.32.29)]
Platform:    posix.uname_result(sysname='Darwin', release='20.3.0', version='Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

PyJWT==1.7.1
adal==1.2.6
applicationinsights==0.11.9
apscheduler==3.7.0
argcomplete==1.12.2
attrs==20.3.0
azure-common==1.1.26
azure-core==1.12.0
azure-cosmos==3.2.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.6.0
azure-graphrbac==0.61.1
azure-identity==1.5.0
azure-keyvault==4.1.0
azure-keyvault-certificates==4.2.1
azure-keyvault-keys==4.3.1
azure-keyvault-secrets==4.2.0
azure-mgmt-apimanagement==1.0.0
azure-mgmt-applicationinsights==1.0.0
azure-mgmt-authorization==1.0.0
azure-mgmt-batch==15.0.0
azure-mgmt-cdn==10.0.0
azure-mgmt-cognitiveservices==11.0.0
azure-mgmt-compute==19.0.0
azure-mgmt-containerinstance==7.0.0
azure-mgmt-containerregistry==8.0.0b1
azure-mgmt-containerservice==15.0.0
azure-mgmt-core==1.2.2
azure-mgmt-cosmosdb==6.1.0
azure-mgmt-costmanagement==1.0.0
azure-mgmt-databricks==1.0.0b1
azure-mgmt-datafactory==1.1.0
azure-mgmt-datalake-store==1.0.0
azure-mgmt-dns==8.0.0b1
azure-mgmt-eventgrid==8.0.0
azure-mgmt-eventhub==8.0.0
azure-mgmt-hdinsight==7.0.0
azure-mgmt-iothub==1.0.0
azure-mgmt-keyvault==8.0.0
azure-mgmt-logic==9.0.0
azure-mgmt-managementgroups==1.0.0b1
azure-mgmt-monitor==2.0.0
azure-mgmt-msi==1.0.0
azure-mgmt-network==17.1.0
azure-mgmt-policyinsights==1.0.0
azure-mgmt-rdbms==8.0.0
azure-mgmt-redis==12.0.0
azure-mgmt-resource==16.0.0
azure-mgmt-resourcegraph==7.0.0
azure-mgmt-search==8.0.0
azure-mgmt-sql==1.0.0
azure-mgmt-storage==17.0.0
azure-mgmt-subscription==1.0.0
azure-mgmt-web==2.0.0
azure-nspkg==3.0.2
azure-storage-blob==12.8.0
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-file-share==12.4.1
azure-storage-queue==12.1.5
boto3==1.17.33
botocore==1.20.33
cachetools==4.2.1
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
click==7.1.2
cryptography==3.4.6
distlib==0.3.1
google-api-core==1.26.1
google-api-python-client==1.12.8
google-auth==1.28.0
google-auth-httplib2==0.1.0
google-cloud-core==1.6.0
google-cloud-logging==1.15.1
google-cloud-monitoring==0.34.0
google-cloud-storage==1.36.2
google-crc32c==1.1.2
google-resumable-media==1.2.0
googleapis-common-protos==1.53.0
httplib2==0.19.0
idna==2.10
importlib-metadata==3.7.3
isodate==0.6.0
jmespath==0.10.0
jsonpickle==1.3
jsonschema==3.2.0
kubernetes==10.0.1
msal==1.10.0
msal-extensions==0.3.0
msrest==0.6.21
msrestazure==0.6.4
netaddr==0.7.20
oauthlib==3.1.0
packaging==20.9
portalocker==1.7.1
protobuf==3.15.6
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
pytz==2021.1
pyyaml==5.4.1
ratelimiter==1.2.0.post0
requests==2.25.1
requests-oauthlib==1.3.0
retrying==1.3.3
rsa==4.7.2
s3transfer==0.3.6
setuptools==54.2.0
six==1.15.0
tabulate==0.8.9
typing-extensions==3.7.4.3
tzlocal==2.1
uritemplate==3.0.1
urllib3==1.26.4
websocket-client==0.58.0
zipp==3.4.1
```

**Additional context**

**Comment by logachev** [comment]
Hi @d-van , sorry, I was looking at the docs yesterday.. Your solution makes sense to me. 
Unfortunately, I don't have access to non-public Azure cloud, so I can't really test it. 
If you could test proposed change and prepare a PR, we can work on merging it.

**Comment by d-van** [comment]
@logachev are you familiar with c7n-org code base? I'm curious about where the best place is to set the cloud endpoints. Any insight?

**Comment by logachev** [comment]
@d-van I would suggest extending `c7n-org` schema to allow `region` for Azure subscriptions (like here: https://github.com/cloud-custodian/cloud-custodian/blob/master/tools/c7n_org/c7n_org/cli.py#L80).. Probably region is not the best keyword, but it is consistent with `c7n` cli.

I haven't used `c7n-org` for a long time, but I would expect if you replace this: https://github.com/cloud-custodian/cloud-custodian/blob/ebbc7cf7e00412b1810993a1bb27eb4d65cd3b9f/tools/c7n_org/c7n_org/cli.py#L521 with value from the config file, it should be enough to pass proper region to the `c7n`.

**Comment by d-van** [comment]
@logachev I had to do a little bit extra in order for c7n-org to set the correct cloud endpoints. I have tested locally using my IDE and did the following:

**custodian**
azure commercial - `custodian run -s . simple_policy.yml --cache-period 0`
```
custodian.azure.session:INFO Authenticated [Principal | xyz-commercial]
custodian.policy:INFO policy:simple-policy resource:azure.vm region:AzureCloud count:13 time:1.09
```

azure us gov - `custodian run -s . simple_policy.yml --region=AzureUSGovernment --cache-period 0`
```
custodian.azure.session:INFO Authenticated [Principal | xyz]
custodian.policy:INFO policy:simple-policy resource:azure.vm region:AzureUSGovernment count:3 time:0.79
```

**c7n-org**
azure commercial - `c7n-org run -c azure_commercial_subscriptions.yml -s output -u simple_policy.yml --cache-period 0`
```
c7n_org:INFO Ran account:subscription_1 region:global policy:simple-policy matched:13 time:1.15
c7n_org:INFO Policy resource counts Counter({'simple-policy': 13})
```

azure us gov - `c7n-org run -c azure_gov_subscriptions.yml -s output -u simple_policy.yml --cache-period 0`
```
c7n_org:INFO Ran account:subscription_1 region:AzureUSGovernment policy:simple-policy matched:3 time:0.86
c7n_org:INFO Ran account:subscription_2 region:AzureUSGovernment policy:simple-policy matched:1 time:0.74
c7n_org:INFO Policy resource counts Counter({'simple-policy': 4})
```

azure_commercial_subscriptions.yml
```
subscriptions:
- name: subscription_1
  subscription_id: xyz
```

azure_gov_subscription.yml contents:
```
subscriptions:
- name: subscription_1
  subscription_id: xyz
  region: AzureUSGovernment
- name: subscription_2
  subscription_id: xyz
  region: AzureUSGovernment
```

I should have a pull request soon.

**Comment by d-van** [comment]
@logachev I just signed the individual agreement. How long does it take in order to get access to push changes out to my branch and to submit a pull request?

**Comment by d-van** [comment]
@logachev do you know who can give me write access to push my branch up?

**Comment by logachev** [comment]
@d-van you need to create a fork & you can create a PR from your fork into this repo

**Comment by d-van** [comment]
doh, got it.

PR is here: https://github.com/cloud-custodian/cloud-custodian/pull/6614

**Comment by d-van** [comment]
@logachev can this ticket be closed since the PR has been merged?

**Comment by logachev** [comment]
Yes, thank you for the reminder!
Fixed with https://github.com/cloud-custodian/cloud-custodian/pull/6614
