### ISSUE TITLE
SQS policy

### ISSUE THREAD

**Issue by Jimmyd84** [cloud-custodian/cloud-custodian#6617]
I was using an older version of c7n until morning and I got an SQS policy working. In the afternoon after I upgraded c7n to the latest version and I tried to deploy the same policy but now I am getting an error

ParamValidationError(report=report.generate_report()) botocore.exceptions.ParamValidationError: Parameter validation failed: Unknown parameter in input: "ResourceARNList", must be one of: PaginationToken, TagFilters, ResourcesPerPage, TagsPerPage, ResourceTypeFilters, IncludeComplianceDetails, ExcludeCompliantResources

**Comment by Jimmyd84** [comment]
I got the same policy working on  c7n version =0.9.8

**Comment by wallabyies** [comment]
I'm having a similar error with an acm-certificate policy when it executes.     The policy worked fine with 0.9.1.0, but broke when we went from 0.9.1.0 > 0.9.11.   Policies with other resources work just fine.

A similar error is discussed here:   https://github.com/cloud-custodian/cloud-custodian/issues/6515

**Comment by JonGilmore** [comment]
i'm seeing a similar error while tagging custodian log groups

**Comment by kapilt** [comment]
we need a more recent version of boto sdk  then what's supported by lambda by default atm. we're using resource group tagging apis, which recently allowed us to fetch tags for an individual resource, which meant we could drop custom work arounds for the lack of this. there's some work about if we can auto manage our own layer, in the interim adding packages: [boto3, botocore] under mode will address.
