### ISSUE TITLE
aws glue-connections hide password

### ISSUE THREAD

**Issue by PratMis** [cloud-custodian/cloud-custodian#6703]
**Is your feature request related to a problem? Please describe.**
When running a policy on `resource: glue-connection` the api returns a password as part of metadata. 

**Describe the solution you'd like**
Set `HidePassword=True` while making the api call https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.get_connections

**Describe alternatives you've considered**

**Additional context**

**Comment by kapilt** [comment]
sounds good
