### ISSUE TITLE
[EKS][Node Group] Delete only node groups, not EKS Cluster

### ISSUE THREAD

**Issue by Paladin-Dranser** [cloud-custodian/cloud-custodian#6735]
I'd like to have possibility to only remove EKS node groups, not EKS Cluster.

Add a separate resource type for EKS node groups and add **delete** action for it.

PRs:
- https://github.com/cloud-custodian/cloud-custodian/pull/6737

**Comment by kapilt** [comment]
merged, thanks for the pr
