### ISSUE TITLE
Invalid type for parameter Tags.SampleTag, value: 1234, type: <class 'int'>, valid types: <class 'str'>

### ISSUE THREAD

**Issue by IngussNeilands** [cloud-custodian/cloud-custodian#6768]
I am getting these type of errors:

```
c7n_org:ERROR Exception running policy - error:Parameter validation failed:
Invalid type for parameter Tags.SampleTag, value: 1234, type: <class 'int'>, valid types: <class 'str'>
```

Is there a way to specify what value type to expect or is there a way to disable validation ?

**Comment by kapilt** [comment]
what's the policy?

**Comment by kapilt** [comment]
also run with c7n-org with --serial to produce a proper traceback or run with regular custodian

**Comment by IngussNeilands** [comment]
this can be closed, after modifying some of our pipeline code, we where setting lambda tag with int value instead of string - fixed by adding ""
