### ISSUE TITLE
AWS Lambda: Wrong result of subsequent run with different input (Cache Issue)

### ISSUE THREAD

**Issue by asimb123** [cloud-custodian/cloud-custodian#6778]
Hi Team,

I have deployed c7n as lambda and running policy e.g. list all VPC for which I have account_id and region as parameter which get set in execution-options.

Running lambda first time for Account A gives correct result, however when running for Account B in a quick span returns the result of Account A instead of Account B. 

Following is example of execution-options. Second run works good if I run after sometime. All cache options are disabled but still somehow it uses cache. Can someone help on this please?

`{'region': 'us-east-2', 'regions': [], 'cache': '', 'profile': None, 'account_id': '111111111111', 'assume_role': 'arn:aws:iam::111111111111:role/cloud-custodian-task-role', 'external_id': None, 'log_group': None, 'tracer': None, 'metrics_enabled': None, 'metrics': None, 'output_dir': '/tmp', 'cache_period': 0, 'dryrun': False, 'authorization_file': None, 'subparser': 'run', 'config': None, 'configs': None, 'policy_filters': [], 'resource_types': ['aws.*'], 'verbose': None, 'quiet': None, 'debug': True, 'skip_validation': False, 'command': 'c7n.commands.run', 'vars': None}
`

In first run, I see following log entry but subsequent run does not show this.

`[DEBUG]	2021-06-30T15:17:14.418Z	492f4356-f9f9-48e8-a8fe-cc5ad4ad7a83	Disabling cache`

Second run execution-options

`{'region': 'us-east-2', 'regions': [], '**cache**': '', 'profile': None, 'account_id': '222222222222', 'assume_role': 'arn:aws:iam::222222222222:role/cloud-custodian-task-role', 'external_id': None, 'log_group': None, 'tracer': None, 'metrics_enabled': None, 'metrics': None, 'output_dir': '/tmp', 'cache_period': 0, 'dryrun': False, 'authorization_file': None, 'subparser': 'run', 'config': None, 'configs': None, 'policy_filters': [], 'resource_types': ['aws.*'], 'verbose': None, 'quiet': None, 'debug': True, 'skip_validation': False, 'command': 'c7n.commands.run', 'vars': None}
`

Regards,
AB

**Comment by kapilt** [comment]
there's a few things unclear from your bug report

what version of custodian? 
what's the policy? 
did you deploy the policy as a lambda using custodian run ?

what do you mean running for account A and account B, a separate lambda deployed in each? by running custodian cli in each account?

**Comment by asimb123** [comment]
Hi @kapilt,
Thanks for your response, here are more details
#1 Cloud Custodian version: c7n-0.9.10
#2 Policy

`policies:
  - name: vpc
    resource: vpc`

Above policy, I am trying to get all VPCs for inventory purpose so there is no filter.

#3 All my policies are part of Lambda Layer and I just give policy name as input and in Lambda I load them from /opt folder and pass to custodian

#4 I have lambda in one account and trying to run policies against another account by assuming role from other account.

This setup is working good except this particular issue.

Regards,
Asim

**Comment by kapilt** [comment]
it sounds like your not using custodian to deploy, policies are never part of a lambda layer, so its unclear what your doing. its clear that your not using custodian or supported tooling to deploy the lambdas. custodian is an application, use as a library isn't supported, there aren't any compatibility guarantees on apis or public interfaces. the community can't debug adhoc idiosyncratic setups.
