### ISSUE TITLE
ELBV2 Unmark Action Support

### ISSUE THREAD

**Issue by jtcarnes** [cloud-custodian/cloud-custodian#6779]
**Is your feature request related to a problem? Please describe.**

Currently, ELBV2 can be marked for op but cannot be unmarked for op.

**Describe the solution you'd like**

Adding the unmark action for elbv2 so I can easily unmark my elbv2s based on a condition, similar to how many other resources work.

**Describe alternatives you've considered**

You could call remove-tag that mark-for-op puts, but that is cumbersome.

**Comment by kapilt** [comment]
unmark and untag are legacy names for remove-tag, and only exist in some resource for policy compatibility, you should use remove-tag.

**Comment by jtcarnes** [comment]
Fair enough, thanks for the info!
