### ISSUE TITLE
cloud-custodian.cache err: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ebattat** [cloud-custodian/cloud-custodian#6799]
Why I am getting this error each time that I run cloud custodian ?

custodian.cache:WARNING Could not save cache /root/.cache/cloud-custodian.cache err: [Errno 2] No such file or directory: custodian.cache:INFO Generating Cache directory: /root/.cache.

Trying to create this file/folder cloud-custodian.cache under /root/.cache but didnt help 

Can anyone please assist ?

**Comment by kapilt** [comment]
that sounds like something idiosyncratic to your deployment, are you running in docker or an instance? what's your invocation cli look like?  what user is custodian running .. that looks like your running it as a unix user but haven't changed the $HOME env var so it points to /root/ and the unix user the cli is running as doesn't have write access to that folder. you can explicitly set --cache file to point to a location that user has write access to.

**Comment by ebattat** [comment]
Hi,

I run it as root, but looks like its a new issue that was entered in your last version.
is there any chance that you test it in your side.
Is there a way to disable the caching feature ? 

Best regards,
Eli Battat.

**Comment by kapilt** [comment]
```
❯ custodian run --help | grep cache
                     [--cache-period CACHE_PERIOD] [-d] [--skip-validation]
  -f CACHE, --cache CACHE
                        Cache file (default ~/.cache/cloud-custodian.cache)
  --cache-period CACHE_PERIOD
```
--cache-period=0  will disable cache.
