### ISSUE TITLE
rds-snapshot policies in lambda execution mode describe ALL rds snapshots for each resource, causing throttling and timeouts

### ISSUE THREAD

**Issue by kylejohnson514** [cloud-custodian/cloud-custodian#6811]
**Describe the bug**
See https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/resources/rds.py#L984
The `rds-snapshot` resource has `enum_spec` making a boto call to `describe_db_snapshots` without a resource identifier, so `describe_db_snapshots` retrieves detailed information about _all_ snapshots in the account. When we run this in a lambda, this is triggered once for each snapshot, ultimately making a ton of API calls that causes throttling and execution timeouts.

**Expected behavior**
Provide the unique snapshot identifier in the call to `describe_db_snapshots` so we no longer retrieve info about all snapshots when we're only trying to act upon one of them

**Comment by kylejohnson514** [comment]
There's no `list_db_snapshots` API available to find the snapshot identifier we care about.

Looking at the `LambdaMode` class https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/policy.py#L415 ... this line _does_ retrieve the name of the `DBSnapshotIdentifier` we would like to provide for the `describe_db_snapshots` call. Is there a way we can toggle the `rds-snapshot` resource to use one `enum_spec` with this provided value when running from lambda mode, vs. the default `enum_spec` when running elsewhere?

**Comment by kapilt** [comment]
We just need to override get_resources on the query resource manager for snapshot, it doesn’t need to do an enumeration in can just fetch against the ids

**Comment by kapilt** [comment]
was looking more closely at this, it should be describe_db_snapshot with the explicit snapshot id from the event. if your not seeing that its probably because of a bad events expression

**Comment by kylejohnson514** [comment]
Thanks!

Are there any docs to help explain what some of those fields mean when we define a new resource? Can't find anything in https://cloudcustodian.io/docs/contribute.html but would be really helpful when contributing new resources to c7n

**Comment by kapilt** [comment]
we've got a separate pr up that adds type info attributes to the docs, i'll try and add a meta lint unit test to #6814 that detects these being incorrectly/partially specified .

**Comment by PratMis** [comment]
@kapilt the policy is looking good. AWS backup job takes up snapshots in bulk triggering the policy. I think the lambda in that case evaluates all those snapshots. We could potentially add a condition on the event itself?
