### ISSUE TITLE
aws.iam-policy - fetch only local policies by default

### ISSUE THREAD

**Issue by ajkerrigan** [cloud-custodian/cloud-custodian#6815]
> > i do wonder if we want to do a follow up branch to default to only customer managed policies wrt to server side query.

> I cannot comment for all users of this but I'm certainly filtering down to just my customer policies when I am running my policies. A default or some intuitive way to do this would be welcome.

Agreed - the Config source will fetch only local policies by default, that seems intuitive (and much more performant) for the Describe source too. Implementation-wise, it seems that we'd want to:

* Allow the policy to specify `Scope` to [list_policies](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam.html#IAM.Client.list_policies)
* Default to `Local`

This feels similar to how we've handled the [`ClusterStates` server-side filter for EMR](https://github.com/cloud-custodian/cloud-custodian/blob/4239c2fb37077afa9d38968e0f2032cee89bb9ca/c7n/resources/emr.py#L65-L95). Perhaps we could handle this in a similar way?

_Originally posted by @trastle in https://github.com/cloud-custodian/cloud-custodian/issues/6751#issuecomment-875302456_

**Comment by kapilt** [comment]
we can add the static query on to the enumeration as a simpler option, i'm just not clear what use cases there are for custodian on managed policies.

**Comment by ajkerrigan** [comment]
This is done (using the static query unless/until there's a need to support managed policies).
