### ISSUE TITLE
AWS: Add interpolation to the kms-key tag action

### ISSUE THREAD

**Issue by griffint61** [cloud-custodian/cloud-custodian#6821]
**Is your feature request related to a problem? Please describe.**
I'm not able to use '{now}' in the value when using the tag action for kms-key resources.

**Describe the solution you'd like**
I would like to be able to use '{now}' when tagging kms-key resources.

**Additional context**
I looked at the code a bit. The kms-key resource is using the `UniversalTag` class in `tags.py`, which unlike the `Tag` class in the same file that is used by many other AWS resource types, does not have an `interpolate_values` method. It's not a simple as just replicating that method in `UniversalTag` because the content of the `tags` variable is not in the same format in the two cases.

**Comment by ajkerrigan** [comment]
Thanks @griffint61 for flagging this. The idea of supporting more interpolation during tagging has come up before, and you're raising a good point about consistency among tagging operations also. This may be a good issue to talk through during our weekly community meetings. I'll look to get this on the agenda for the next meeting (Tuesday 8/17 at 2:00 PM Eastern). The agenda will be available [here](https://hackmd.io/@c7n).

**Comment by griffint61** [comment]
I guess I should have mentioned in the original post, if you do attempt to use "{now}" during KMS tagging, it's not that it simply doesn't give the desired result. It blows up on you because the curly braces get passed through to the API, and AWS doesn't like the curly braces in tag values. The result is an exception.
