### ISSUE TITLE
kms-key access denied on AWS Managed KMS Keys

### ISSUE THREAD

**Issue by vishalsparmar** [cloud-custodian/cloud-custodian#6847]
I am trying to add tags and normalise them for each of customer managed KMS Keys but Cloudcustodian policies is trying to add tags to AWS Managed KMS keys. I dont know how to filter out customer managed KMS keys in my filter.

below is my policy 

# Normailse environment tag
  - name: kms-normalise-environment-tag 
    resource: kms-key
    mode:
      type: periodic
      schedule: "rate(1 hour)"
      role: "arn:aws:iam::{account_id}:role/CloudCustodianLambdaRole"

    description: |
      Normalise "environment" tag

    filters:
      - or:
        - "tag:env": present
        - "tag:enviroment": present
        - "tag:Environment": present
        - "tag:environment": absent
        - type: value
          key: "tag:environment"
          op: ne
          value:
            - "{environment}"

    actions:
      - type: remove-tag
        tags: [env, enviroment, Environment]
      - type: tag
        tags:
          environment: "{environment}"

**Comment by ajkerrigan** [comment]
Hi @vishalsparmar - you can distinguish between AWS and customer-managed keys with the `KeyManager` field:

```
filters:
  - KeyManager: CUSTOMER
```

There's some relevant documentation on the `KeyManager` field [here](https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#customer-cmk):

> Customer managed CMKs appear on the Customer managed keys page of the AWS Management Console for AWS KMS. To definitively identify a customer managed CMK, use the DescribeKey operation. For customer managed CMKs, the value of the KeyManager field of the DescribeKey response is CUSTOMER.
