### ISSUE TITLE
Missing schema item for aws.log-group retentionInDays

### ISSUE THREAD

**Issue by ryanash999** [cloud-custodian/cloud-custodian#6877]
**Describe the bug**
The schema output for aws.log-group should include a filter for retentionInDays

**To Reproduce**
custodian schema aws.log-group.filters

**Policy example**

```yaml
policies:
  - name: log-group
    resource: aws.log-group
    filters:
      - retentionInDays: absent
```

**Expected behavior**
Schema output should indicate the existence of a filter for retentionInDays. See below...missing

```
(custodian) testing$ custodian schema aws.log-group.filters
aws.log-group:
  filters:
  - config-compliance
  - cross-account
  - event
  - finding
  - kms-key
  - last-write
  - marked-for-op
  - metrics
  - ops-item
  - reduce
  - tag-count
  - value

```

**Version information**

 - `custodian version --debug` output

```
(custodian) /testing$ custodian version --debug

Custodian:   0.9.13
Python:      3.7.8 (default, Oct  2 2020, 09:01:25) 
             [Clang 11.0.0 (clang-1100.0.20.17)]
Platform:    posix.uname_result(sysname='Darwin', nodename='MacBook-Pro.local', release='20.6.0', version='Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

argcomplete==1.12.3
attrs==21.2.0
boto3==1.17.102
botocore==1.20.102
importlib-metadata==4.6.0
jmespath==0.10.0
jsonschema==3.2.0
pyrsistent==0.18.0
python-dateutil==2.8.1
pyyaml==5.4.1
s3transfer==0.4.2
setuptools==47.1.0
six==1.16.0
tabulate==0.8.9
typing-extensions==3.10.0.0
urllib3==1.26.6
zipp==3.4.1
```

**Comment by ajkerrigan** [comment]
Hi @ryanash999 - thanks for the issue report! This is a good call-out, something that we may be able to clarify in the documentation. Your filter:

```
filters:
  - retentionInDays: absent
```

Is shorthand for this equivalent [value filter](https://cloudcustodian.io/docs/filters.html#value-filter):

```
filters:
  - type: value
    key: retentionInDays
    value: absent
```

Because `retentionInDays` is already present and usable in the base `aws.log-group` data, we can use a value filter instead of needing a separate custom filter.

**Comment by ryanash999** [comment]
@ajkerrigan Sounds good.  Are you saying this shorthand version is a default and would exist for any value key?  If so, it totally makes sense that the schema output would not need to list it.  Thanks.

**Comment by ajkerrigan** [comment]
Yes, custodian tries to let you get away with less typing for some common cases. If you don't specify a `type` for a filter, it tries to figure out what you mean.

If you give just a string:

```
filters:
  - bucket-encryption
```

It assumes you're providing a filter `type` and are OK with default options for that filter. That expands to:

```
filters:
  - type: bucket-encryption
```

If you provide a key:value pair as in your example:

```
filters:
  - retentionInDays: absent
```

It assumes you're providing the `key` and `value` of a value filter. This short form breaks down when you need to specify additional parameters for a filter or action, but it's handy in the simple cases!

**Comment by kapilt** [comment]
yeah this seems more like mis understanding / documentation around the default value filter aliasing around attributes, which aren't part of our docs.
