### ISSUE TITLE
Is there a has-no-statement ?

### ISSUE THREAD

**Issue by herrsergio** [cloud-custodian/cloud-custodian#6878]
We are using Terraform to deploy our infrastructure in AWS, and we have created some default S3 policies for new buckets.

But there are some specific use cases, where buckets are created using the CLI or AWS Console and users are not setting the needed policies.

I have created a custodian policy for new S3 buckets; where I am using a `set-statements`. But how can I avoid to duplicate the policy statement in buckets ? I was looking for a `has-no-statement` type, but I can't find it, or how can I achieve this?

Thanks

**Comment by ajkerrigan** [comment]
Hi @herrsergio - if you want to check for missing statements by ID you can use the [missing-policy-statement](https://cloudcustodian.io/docs/aws/resources/s3.html#aws-s3-filters-missing-policy-statement) filter.

That sounds likely to cover your case here and is probably the cleanest option. It's also possible to put a [has-statement](https://cloudcustodian.io/docs/aws/resources/s3.html#aws-s3-filters-has-statement) filter inside a `not` block. That covers cases where you want to check for missing statements that have certain principals or actions, regardless of the statement ID.

**Comment by herrsergio** [comment]
Hi @ajkerrigan thanks for your answer and tips, I will take a look to those options
