### ISSUE TITLE
c7n-org: List S3 bucket Tag

### ISSUE THREAD

**Issue by bth8939** [cloud-custodian/cloud-custodian#6891]
### Describe the bug

Hi, 

I want to list all Bucket S3 which do not have certain tags defined in all region: 

### s3.yml
<pre><code>
policies:
  - name: s3-tag-policy
    resource: aws.s3
    filters:
      - or:
        - "tag:Team": absent
        - "tag:Name": absent
</code></pre>

### account.yml
<pre><code>
accounts:
- account_id: 'xxxxx'
  name: monitoring
  regions:
  - all
  role: arn:aws:iam::xxxxx:role/xxxxxrolewxxxxxx
</code></pre>

In my case, I have 2 buckets in this account (one region eu-west-3) and when I launch c7n-org. 

It shows me the buckets that do not exist in another region  ...

<pre><code>
bash-3.2$  c7n-org run -c accounts.yml -u policies/s3.yml -s output/
2021-09-11 09:39:47,300: c7n_org:INFO Policy resource counts Counter({'s3-tag-policy': 17})

bash-3.2$  c7n-org report -c accounts.yml -u policies/s3.yml -s output/
"Account","Region","Policy","Name","CreationDate"
"monitoring","us-west-2","s3-tag-policy","monitoring-s3","2021-08-02T10:01:34+00:00"
"monitoring","ap-southeast-2","s3-tag-policy","monitoring-s3","2021-08-02T10:01:34+00:00"
"monitoring","us-east-2","s3-tag-policy","monitoring-s3","2021-08-02T10:01:34+00:00"
"monitoring","us-east-1","s3-tag-policy","monitoring-s3","2021-05-03T14:59:12+00:00"
"monitoring","us-west-1","s3-tag-policy","monitoring-s3","2021-08-02T10:01:34+00:00"
"monitoring","ap-northeast-3","s3-tag-policy","monitoring-s3","2021-08-02T10:01:34+00:00"
"monitoring","ca-central-1","s3-tag-policy","monitoring-s3","2021-08-02T10:01:34+00:00"
"monitoring","eu-west-3","s3-tag-policy","monitoring-s3","2021-08-02T10:01:34+00:00"
"monitoring","ap-northeast-1","s3-tag-policy","monitoring-s3","2021-08-02T10:01:34+00:00"
"monitoring","eu-central-1","s3-tag-policy","monitoring-s3","2021-08-02T10:01:34+00:00"
"monitoring","eu-west-2","s3-tag-policy","monitoring-s3","2021-08-02T10:01:34+00:00"
"monitoring","ap-northeast-2","s3-tag-policy","monitoring-s3","2021-08-02T10:01:34+00:00"
"monitoring","ap-southeast-1","s3-tag-policy","monitoring-s3","2021-08-02T10:01:34+00:00"
"monitoring","eu-west-1","s3-tag-policy","monitoring-s3","2021-08-02T10:01:34+00:00"
"monitoring","sa-east-1","s3-tag-policy","monitoring-s3","2021-08-02T10:01:34+00:00"
"monitoring","eu-north-1","s3-tag-policy","monitoring-s3","2021-08-02T10:01:34+00:00"
"monitoring","ap-south-1","s3-tag-policy","monitoring-s3","2021-08-02T10:01:34+00:00"
</code></pre>

Can you help me to understand ? 

### What did you expect to happen?

List one bucket(monitoring-s3) in eu-west-3

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
bash-3.2$ custodian version --debug

Please copy/paste the following info along with any bug reports:

Custodian:   0.9.13
Python:      3.9.5 (default, Jun 23 2021, 18:49:53) 
             [Clang 10.0.0 (clang-1000.10.44.4)]
Platform:    posix.uname_result(sysname='Darwin', nodename='MacBook-Pro.local', release='17.7.0', version='Darwin Kernel Version 17.7.0: Fri Oct 30 13:34:27 PDT 2020; root:xnu-4570.71.82.8~1/RELEASE_X86_64', machine='x86_64')
Using venv:  False
Docker: False
Installed: 

argcomplete==1.12.3
attrs==21.2.0
boto3==1.17.102
botocore==1.20.102
importlib-metadata==4.6.0
jmespath==0.10.0
jsonschema==3.2.0
pyrsistent==0.18.0
python-dateutil==2.8.1
pyyaml==5.4.1
s3transfer==0.4.2
setuptools==56.0.0
six==1.16.0
tabulate==0.8.9
typing-extensions==3.10.0.0
urllib3==1.26.6
zipp==3.4.1
```

### Policy

```shell
policies:
  - name: s3-tag-policy
    resource: aws.s3
    filters:
      - or:
        - "tag:Team": absent
        - "tag:Name": absent
```

**Comment by ajkerrigan** [comment]
Hi @bth8939 - while S3 buckets have a location associated with them, they are global resources. If you run an S3 policy in 10 regions you'll get the same results 10 times. To avoid that duplication, you can use a [policy condition](https://cloudcustodian.io/docs/quickstart/advanced.html#conditional-policy-execution) to restrict your policy to a single region:

```
policies:
  - name: s3-tag-policy
    resource: aws.s3
    conditions:
      - region: us-east-1
    filters:
      - or:
        - "tag:Team": absent
        - "tag:Name": absent
```

**Comment by bth8939** [comment]
Hi @ajkerrigan,

Thanks you for your response.
