### ISSUE TITLE
Exception when copy-volume-tags is used with volumes having tag keys starting with "aws:"

### ISSUE THREAD

**Issue by griffint61** [cloud-custodian/cloud-custodian#6952]
### Describe the bug

I tried to use `copy-volume-tags: true` with the `type: snapshot` action on an EBS volume that was created by CloudFormation. Being owned by CloudFormation, the volume had tags keys starting with `aws:` This resulted in the following error:

12:53:35  2021-10-20 19:53:35,789: custodian.output:ERROR Error while executing policy
12:53:35  Traceback (most recent call last):
12:53:35    File "/src/c7n/policy.py", line 317, in run
12:53:35      results = a.process(resources)
12:53:35    File "/src/c7n/resources/ebs.py", line 1356, in process
12:53:35      retry(self.process_volume, client=client, volume=vol_id, tags=tags)
12:53:35    File "/src/c7n/utils.py", line 444, in _retry
12:53:35      return func(*args, **kw)
12:53:35    File "/src/c7n/resources/ebs.py", line 1360, in process_volume
12:53:35      client.create_snapshot(VolumeId=volume, TagSpecifications=tags)
12:53:35    File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
12:53:35      return self._make_api_call(operation_name, kwargs)
12:53:35    File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
12:53:35      raise error_class(parsed_response, operation_name)
12:53:35  botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the CreateSnapshot operation: Tag keys starting with 'aws:' are reserved for internal use.

### What did you expect to happen?

I expected all of the volume tags _not_ starting with `aws:` to get copied to the snapshot, and no errors.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.12
Python:      3.6.8 (default, Sep 23 2021, 07:23:00) 
             [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
Platform:    posix.uname_result(sysname='Linux', nodename='el8-64', release='4.18.0-305.19.1.el8_4.x86_64', version='#1 SMP Wed Sep 15 11:28:53 EDT 2021', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

argcomplete==1.12.3
attrs==21.2.0
boto3==1.17.96
botocore==1.20.96
importlib-metadata==4.5.0
jmespath==0.10.0
jsonschema==3.2.0
pyrsistent==0.17.3
python-dateutil==2.8.1
pyyaml==5.4.1
s3transfer==0.4.2
setuptools==39.2.0
six==1.16.0
tabulate==0.8.9
typing-extensions==3.10.0.0
urllib3==1.26.5
zipp==3.4.1
```

### Policy

```shell
policies:
  - name: date-to-archive-ebs-volume
    resource: ebs
    filters:
      - type: value
        key: State
        value: available
      - type: marked-for-op
        tag: date-to-archive
        op: delete
    actions:
      - type: snapshot
        copy-volume-tags: true
      - type: delete
```

**Comment by ajkerrigan** [comment]
Fixed via PR (thanks!)
