### ISSUE TITLE
Expansion of AWS Lambda states to all functions

### ISSUE THREAD

**Issue by TomJKing** [cloud-custodian/cloud-custodian#6968]
### Ask your question

AWS have announced this change to their lambdas: https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/

This is due to be implemented on 6 Dec 2021. Is there a plan to account for this change to AWS lambdas in CloudCustodian?

The reason I ask is because I have been testing our CloudCustodian lambda deployments using the suggested method by AWS, of adding the `aws:states:opt-in` paramater to the description of the lambda. When this is in place the CloudCustodian deployment fails with the following error message:

`botocore.errorfactory.ResourceConflictException: An error occurred (ResourceConflictException) when calling the UpdateFunctionConfiguration operation: The operation cannot be performed at this time. An update is in progress for resource: {arn of the lambda being updated}`

This appears to be an issue in the _create_or_update function in mu_py: https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/mu.py#L455

I have been able to fix this locally by adding a waiter function to the code to ensure the lambda is in the "updated" state before proceeding with the deployment, as follows:
```
... rest of code ... 
result = self.client.update_function_code(**params) function_updated_waiter.wait( FunctionName=func.name ) 
changed = True 
... rest of code ...
```

**Comment by kapilt** [comment]
closing this per discussion in #6945 and pr
