### ISSUE TITLE
Creating an EC2 Resource for Capacity Reservations

### ISSUE THREAD

**Issue by seanocca** [cloud-custodian/cloud-custodian#6976]
### Describe the feature

I am always frustrated when I cannot create a Cloud Custodian rule to alert me on the usage and creation of the EC2 Capacity Reservations. 

This is different from the EC2 Reserved Instance request. As Reserved Instance is a payment of currently running instances and the Capacity Reservation is the hold on instances for use later on.

### Extra information or context

The AWS CLI has the command available to get details relating to it.

https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-capacity-reservations.html

Context: We need an alarm on unfulfilled Capacity Reservations. So that we can track our spending on these AWS resources

**Comment by dehamzah** [comment]
hi, I'm also interested in this feature. is there a guide to help us contribute to the code? or maybe a PR that is easy to understand and how to test it. thank you in advance.

**Comment by dehamzah** [comment]
I am trying to create the PR here https://github.com/cloud-custodian/cloud-custodian/pull/9147
