### ISSUE TITLE
mailer / default formater support elasticsearch

### ISSUE THREAD

**Issue by sri321** [cloud-custodian/cloud-custodian#698]
Tried to email the resource-owner for the ESS domain. Even though there was a OwnerContact tag in the ESS domain , the action fails. the error message is "Unknown resource type elasticsearch" , when clearly it has that resource type. 

i tried using a specific email address in the "To:" section of notify , and it works fine, but that wont do any good.

can you let me know whats going on, or can you help resolve this?

**Comment by kapilt** [comment]
thats because the mailer formatter needs to be made elasticsearch aware afaik

**Comment by kapilt** [comment]
it would be helpful to have the traceback, its unclear if your talking about the mailer or custodian.

**Comment by sri321** [comment]
its about the mailer

**Comment by kapilt** [comment]
the mailer should auto fall back to an ugly json representation, there's really not enough details here to understand what your referencing.

**Comment by sri321** [comment]
Would this help?

14:43:28
[INFO] 2016-12-08T14:43:28.615Z ae6696a6-bd54-11e6-8c58-f94bb7d2db37 Got account:cof-sts-dev message:17a9c3da-3062-4ba3-b036-5e0549e50b9f elasticsearch:2 policy:elasticsearch-delete recipients:resource-owner, event-owner

14:43:28
Unknown resource type elasticsearch
 
[INFO] 2016-12-08T14:43:28.616Z ae6696a6-bd54-11e6-8c58-f94bb7d2db37 No resource owner found for
{
    "ElasticsearchClusterConfig": {
        "DedicatedMasterEnabled": false,
        "InstanceCount": 1,
        "ZoneAwarenessEnabled": false,
        "InstanceType": "t2.micro.elasticsearch"
    },

**Comment by kapilt** [comment]
re elasticsearch unknown type, thats just a warning, before it defaults to json on the mailer, not an issue.
