### ISSUE TITLE
CloudCustodian.io - Docs Search Functionality Not Working

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#6999]
### Describe the bug

When I try searching the docs page - [https://cloudcustodian.io/docs/index.html](https://cloudcustodian.io/docs/index.html) it says Searching... and spins forever without returning results. This has been occurring for about 2 weeks or so.

### What did you expect to happen?

Before the issue started, search results would be returned when searching a valid string

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
https://cloudcustodian.io/docs/index.html
```

### Policy

```shell
N/A
```

### Relevant log/traceback output

```shell
searchtools.js:158 Uncaught ReferenceError: Stemmer is not defined
    at Object.query (searchtools.js:158)
    at Object.setIndex (searchtools.js:98)
    at <anonymous>:1:8
    at b (jquery.js:2)
    at Function.globalEval (jquery.js:2)
    at text script (jquery.js:2)
    at jquery.js:2
    at l (jquery.js:2)
    at XMLHttpRequest.<anonymous> (jquery.js:2)
```

### Extra information or context

Thank you!

**Comment by ajkerrigan** [comment]
With the theme updates live, search seems to be working again. Thanks for reporting this!
