### ISSUE TITLE
GCP Unencrypted DiskDetection Failure

### ISSUE THREAD

**Issue by khalilnkhaliln** [cloud-custodian/cloud-custodian#7001]
### Describe the bug

For the policy below - basically gcp.disk checking for the absence of diskEncryptionKey.kmsKeyName - i.e. when a disk is created trap if customer encryption not present - the following error shows up in the error logs -

TypeError: Got an unexpected keyword argument "resourceId"
File "/workspace/c7n_gcp/policy.py", in line 131, in resolve_resources resource = self.policy.resource_manager.get_resource(resource_info['labels']})

### What did you expect to happen?

Expected parsing of the event by the policy cloud function - to work properly. All the pertinent data is in the event.
However when obtaining the GCP resource - a failure occurs due to a mismatched type.

### Cloud Provider

Google Cloud (GCP)

### Cloud Custodian version and dependency information

```shell
$ custodian version --debug
 
Please copy/paste the following info along with any bug reports:
 
Custodian:   0.9.13
Python:      3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
Platform:   win32
Using venv:  False
Docker: False
Installed:
 
argcomplete==1.12.3
attrs==21.2.0
boto3==1.17.102
botocore==1.20.102
c7n==0.9.13
cachetools==4.2.2
certifi==2021.5.30
cffi==1.14.5
chardet==4.0.0
google-api-core==1.30.0
google-api-python-client==1.12.8
google-auth==1.32.0
google-auth-httplib2==0.1.0
google-cloud-core==1.7.1
google-cloud-logging==1.15.1
google-cloud-monitoring==0.34.0
google-cloud-storage==1.40.0
google-crc32c==1.1.2
google-resumable-media==1.3.1
googleapis-common-protos==1.53.0
grpcio==1.38.1
httplib2==0.19.1
idna==2.10
importlib-metadata==4.6.0
jmespath==0.10.0
jsonschema==3.2.0
packaging==20.9
protobuf==3.17.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pyparsing==2.4.7
pyrsistent==0.18.0
python-dateutil==2.8.1
pytz==2021.1
pyyaml==5.4.1
ratelimiter==1.2.0.post0
requests==2.25.1
retrying==1.3.3
rsa==4.7.2
s3transfer==0.4.2
setuptools==56.0.0
six==1.16.0
tabulate==0.8.9
typing-extensions==3.10.0.0
uritemplate==3.0.1
urllib3==1.26.6
zipp==3.4.1
```

### Policy

```shell
policies:
  - name: compute-restrict-unencrypted-disks-audit
    description: |
      Detects disks created without customer provided encryption key.
    resource: gcp.disk
    mode:
      type: gcp-audit
      methods:
        - beta.compute.disks.insert
        - v1.compute.disks.insert
    filters:
      - type: value
        key: diskEncryptionKey.kmsKeyName
        value: absent
    actions:
      - delete
```

### Extra information or context

I was able to resolve this with a small update to the get method in the disk class in c7n_gcp/resources/compute.py -

from:
@staticmethod
def get(client, resource_info):
    return client.execute_command(
        'get', {'project': resource_info['project_id'],
                'zone': resource_info['zone'],
                'resourceId': resource_info['disk_id']})

to:
@staticmethod
def get(client, resource_info):
    return client.execute_command(
        'get', {'project': resource_info['project_id'],
                'zone': resource_info['zone'],
                'disk': resource_info['disk_id']})

**Comment by khalilnkhaliln** [comment]
Alternate title -
TypeError retrieving disk_id from event.protoPayload.labels

**Comment by kapilt** [comment]
fix merged, thanks for the pr
