### ISSUE TITLE
Enable AWS IAM set-policy action to use policy name instead of ARN similar to set-boundary action

### ISSUE THREAD

**Issue by mcripps9** [cloud-custodian/cloud-custodian#7017]
### Describe the feature

Add the same logic to the IAM set-policy action that is present in the IAM set-boundary action to allow use of a policy name instead of a full ARN to make the policies more portable across accounts.

**Comment by mcripps9** [comment]
Added pull request 7018 with fix

**Comment by kapilt** [comment]
thanks, merged
