### ISSUE TITLE
value_type transformation: json

### ISSUE THREAD

**Issue by ajkerrigan** [cloud-custodian/cloud-custodian#7043]
### Describe the feature

We've gotten some questions [in Gitter](https://gitter.im/cloud-custodian/cloud-custodian?at=61cdafac5dc6213cd4b9bc13) and in [other issues](https://github.com/cloud-custodian/cloud-custodian/issues/6619), where folks are trying to match specific values deep inside stringified JSON blobs (such as S3 bucket policies or SQS/SNS access policies). Custodian often has filters (such as `cross-account` or `has-statement`) that implicitly parse those JSON blobs. But I'm wondering if it'd also be valuable to have something like a `value_type: json` transformation that would allow arbitrary [value filters](https://cloudcustodian.io/docs/filters.html#value-filter) to work directly against those fields.

### Extra information or context

The added complexity of a change like this feels pretty small, but I'm wondering if the whole train of thought is a bit misguided. In which case adding this feature would risk pulling others into the same misguided thinking!

**Comment by kapilt** [comment]
I think it might be better to resurrect the fuzzy match on has statement pr as its pretty specific to the policy use case, and iam needs normalization behavior versus strict matching due to various expansion/shortcut syntaxes that need to be taken into account.

**Comment by ajkerrigan** [comment]
That makes sense, good call :+1:
