### ISSUE TITLE
AWS.ASG save-options-tag not working properly (on AWS.LAMBDA)

### ISSUE THREAD

**Issue by gabfelp** [cloud-custodian/cloud-custodian#7064]
### Describe the bug

Hello everybody. 

I'm running the Cloud Custodian tool from the container (https://hub.docker.com/r/cloudcustodian/c7n) as an AWS LAMBDA and I'm having a problem using save-options-tag from ASG resource.

If I have an ASG instance running, which has max = 2, min = 1, and desired = 2 and I run this policy below on it

  - name: offhours-asg-off
    resource: asg
    filters:
      - type: offhour
        opt-out: true
        default_tz: pt
        weekends: true # leave resources off for the weekend
        offhour: 13
    actions:
      - type: resize
        save-options-tag: OffHoursPrevious
        min-size: 0
        desired-size: 0
      - type: tag
        tags: 
          stopped-by-custodian: "true"

I expect OffHoursPrevious tag to be:  
OffHoursPrevious = "DesiredCapacity=2;MaxSize=2;MinSize=1" (saving previous values)
but I'm having:
OffHoursPrevious = "DesiredCapacity=0;MaxSize=2;MinSize=0" as the new ones.

THIS PROBLEM ONLY HAPPENS BY running cloud custodian as an AWS lambda (container)

Is this some kind of error? I've tried to change the order of items on actions and nothing works. I'm thinking that it saves the information after changing, hence this problem.

The variables max, min and desired changed as needed, but the tag kept the new values instead of the old ones.

Thank you!

### What did you expect to happen?

  - name: offhours-asg-off
    resource: asg
    filters:
      - type: offhour
        opt-out: true
        default_tz: pt
        weekends: true # leave resources off for the weekend
        offhour: 13
    actions:
      - type: resize
        save-options-tag: OffHoursPrevious
        min-size: 0
        desired-size: 0
      - type: tag
        tags: 
          stopped-by-custodian: "true"

I expect OffHoursPrevious tag to be:  
OffHoursPrevious = DesiredCapacity=2;MaxSize=2;MinSize=1
but I'm having:
OffHoursPrevious = DesiredCapacity=0;MaxSize=2;MinSize=0.

THIS PROBLEM ONLY HAPPENS BY running cloud custodian as an aws lambda (container)

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.14
Python:      3.8.10 (default, Sep 28 2021, 16:10:42) 
             [GCC 9.3.0]
Platform:    posix.uname_result(sysname='Linux', nodename='6bd0fe0f96d0', release='5.11.0-46-generic', version='#51~20.04.1-Ubuntu SMP Fri Jan 7 06:51:40 UTC 2022', machine='x86_64')
Using venv:  True
Docker: True
Installed: 

PyJWT==1.7.1
PyYAML==5.4.1
adal==1.2.7
appdirs==1.4.4
applicationinsights==0.11.10
apscheduler==3.8.1
argcomplete==1.12.3
attrs==21.2.0
azure-common==1.1.27
azure-core==1.20.0
azure-cosmos==3.2.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.7.2
azure-graphrbac==0.61.1
azure-identity==1.7.0
azure-keyvault==4.1.0
azure-keyvault-certificates==4.3.0
azure-keyvault-keys==4.4.0
azure-keyvault-secrets==4.3.0
azure-mgmt-advisor==9.0.0
azure-mgmt-apimanagement==1.0.0
azure-mgmt-applicationinsights==1.0.0
azure-mgmt-authorization==1.0.0
azure-mgmt-batch==15.0.0
azure-mgmt-cdn==10.0.0
azure-mgmt-cognitiveservices==11.0.0
azure-mgmt-compute==19.0.0
azure-mgmt-containerinstance==7.0.0
azure-mgmt-containerregistry==8.0.0b1
azure-mgmt-containerservice==15.1.0
azure-mgmt-core==1.3.0
azure-mgmt-cosmosdb==6.4.0
azure-mgmt-costmanagement==1.0.0
azure-mgmt-databricks==1.0.0b1
azure-mgmt-datafactory==1.1.0
azure-mgmt-datalake-store==1.0.0
azure-mgmt-dns==8.0.0b1
azure-mgmt-eventgrid==8.0.0
azure-mgmt-eventhub==8.0.0
azure-mgmt-frontdoor==1.0.0
azure-mgmt-hdinsight==7.0.0
azure-mgmt-iothub==1.0.0
azure-mgmt-keyvault==8.0.0
azure-mgmt-logic==9.0.0
azure-mgmt-managementgroups==1.0.0b1
azure-mgmt-monitor==2.0.0
azure-mgmt-msi==1.0.0
azure-mgmt-network==17.1.0
azure-mgmt-policyinsights==1.0.0
azure-mgmt-rdbms==8.1.0
azure-mgmt-redis==12.0.0
azure-mgmt-resource==16.1.0
azure-mgmt-resourcegraph==7.0.0
azure-mgmt-search==8.0.0
azure-mgmt-servicefabric==1.0.0
azure-mgmt-sql==1.0.0
azure-mgmt-storage==17.1.0
azure-mgmt-subscription==1.0.0
azure-mgmt-trafficmanager==0.51.0
azure-mgmt-web==2.0.0
azure-nspkg==3.0.2
azure-storage-blob==12.9.0
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-file-share==12.6.0
azure-storage-queue==12.1.6
backports.zoneinfo==0.2.1
boto3==1.19.12
botocore==1.22.12
cachetools==4.2.4
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.7
click==8.0.3
cryptography==35.0.0
decorator==5.1.0
distlib==0.3.3
docutils==0.17.1
dogpile.cache==1.1.4
google-api-core==2.2.2
google-api-python-client==2.29.0
google-auth==2.3.3
google-auth-httplib2==0.1.0
google-cloud-appengine-logging==1.1.0
google-cloud-audit-log==0.2.0
google-cloud-core==2.1.0
google-cloud-logging==2.7.0
google-cloud-monitoring==2.6.0
google-cloud-storage==1.42.3
google-crc32c==1.3.0
google-resumable-media==2.1.0
googleapis-common-protos==1.53.0
grpc-google-iam-v1==0.12.3
grpcio==1.41.1
httplib2==0.20.2
idna==3.3
importlib-metadata==4.8.1
iso8601==0.1.16
isodate==0.6.0
jmespath==0.10.0
jsonpatch==1.32
jsonpointer==2.2
jsonschema==3.2.0
keystoneauth1==4.4.0
kubernetes==10.0.1
msal==1.16.0
msal-extensions==0.3.0
msrest==0.6.21
msrestazure==0.6.4
munch==2.5.0
netaddr==0.7.20
netifaces==0.11.0
oauthlib==3.1.1
openstacksdk==0.52.0
os-service-types==1.7.0
packaging==21.2
pbr==5.7.0
portalocker==1.7.1
proto-plus==1.19.7
protobuf==3.19.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pyparsing==2.4.7
pyrsistent==0.18.0
python-dateutil==2.8.2
pytz==2021.3
pytz-deprecation-shim==0.1.0.post0
pyyaml==5.4.1
ratelimiter==1.2.0.post0
requests==2.26.0
requests-oauthlib==1.3.0
requestsexceptions==1.4.0
retrying==1.3.3
rsa==4.7.2
s3transfer==0.5.0
setuptools==44.0.0
six==1.16.0
stevedore==3.5.0
tabulate==0.8.9
tzdata==2021.5
tzlocal==4.1
uritemplate==4.1.1
urllib3==1.26.7
websocket-client==1.2.1
zipp==3.6.0
```

### Policy

```shell
- name: offhours-asg-off
    resource: asg
    filters:
      - type: offhour
        opt-out: true
        default_tz: pt
        weekends: true # leave resources off for the weekend
        offhour: 13
    actions:
      - type: resize
        save-options-tag: OffHoursPrevious
        min-size: 0
        desired-size: 0
      - type: tag
        tags: 
          stopped-by-custodian: "true"
```

### Extra information or context

THIS PROBLEM ONLY HAPPENS BY running cloud custodian as an AWS lambda (container)

**Comment by kapilt** [comment]
custodian cli provisions lambda functions for policies, but the cli is not intended to be used as a lambda nor is attempting to use that way supported. i would guess that your triggering multiple invocations of the lambda and don't have an appropriate filter to guard against the resize action being used multiple times.

**Comment by gabfelp** [comment]
Thanks kapilt, it looks like the action was being performed more than once as you said.
