### ISSUE TITLE
Docker Container in Dockerhub not up to date.

### ISSUE THREAD

**Issue by AniGarikipati** [cloud-custodian/cloud-custodian#7088]
### Describe the bug

Container tagged latest in dockerhub registry https://hub.docker.com/r/cloudcustodian/c7n  is 3 months old and does not include the newest changes. 

### What did you expect to happen?

Dockerhube Container reflects newest version of c7n/cloudcustodian in Github

### Cloud Provider

Amazon Web Services (AWS)

**Comment by kapilt** [comment]
latest in docker hub is an alias to the last release, and yes that is up to date with the last release. we are due for another release.

there is also a 'dev' alias which points to the latest trunk.
