### ISSUE TITLE
Invoke Lambda Function using variable name

### ISSUE THREAD

**Issue by gabfelp** [cloud-custodian/cloud-custodian#7130]
### Describe the feature

Hi!

Thanks for the tool, it has been very helpful. 

About my difficulty:

I would like to **invoke a lambda function** that has a name that depends on the instance being filtered.

For example, if I correctly filtered an ECS-Service resource, I would like to invoke a function with the name:

{clusterArn}_Controller, where clusterArn is exactly the data that is present in resources.json. (What I really need is the cluster name, but from clusterArn I get it)

Something like:
 
 policies:
  - name: Ecs
    resource: aws.ecs-service
    actions: 
      - type: invoke-lambda
        function: {clusterArn}_Controller
        
If that's not possible, is it possible to pass the clusterArn as a Lambda variable?

for example: 

 policies:
  - name: Ecs
    resource: aws.ecs-service
    actions: 
      - type: invoke-lambda
        function: default_Controller
        vars:
          arn_from_cluster: {clusterArn}.
         
 If that's also not possible, how can I help you to make a workaround for this? @kapilt 
 
Thank you!

### Extra information or context

 I would like to invoke functions that vary depending on the filtered resource, like:
 
 
 policies:
  - name: Ecs
    resource: aws.ecs-service
    actions: 
      - type: invoke-lambda
        function: {clusterArn}_Controller

**Comment by ajkerrigan** [comment]
Hi @gabfelp - when Custodian invokes your Lambda function, it includes a bunch of information as part of the [event](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-concepts.html#gettingstarted-concepts-event) so that it will be available to your handler. From the `invoke-lambda` [docs](https://cloudcustodian.io/docs/aws/resources/aws-common-actions.html#invoke-lambda), that includes:

```
        resources / collection of resources
        policy / policy that is invoke the lambda
        action / action that is invoking the lambda
        event / cloud trail event if any
        version / version of custodian invoking the lambda
```

Where `resources` will be a batch of up to 250 resources by default, and will have the same data you can see in `resources.json` after a policy run so you can pull out ARNs as needed. Hope that helps!

**Comment by gabfelp** [comment]
Hi @ajkerrigan, thank you for the explanation! It will definitely help!

If possible, could you clarify how I can be accessing this information from the handler? 

I mean, are they environment variables? How can I be accessing the "resources.clusterArn", for example?

Thank you!

**Comment by ajkerrigan** [comment]
Not variables, no, they're passed into the event which is a Python dict available inside your handler function. So if you had a Lambda handler like...

```python
import json


def lambda_handler(event, context):
    print("Received event: " + json.dumps(event, indent=2))
    print("Resource batch: " + json.dumps(event.get('resources'), indent=2))
    return event
```

And you used that function as an `invoke-lambda` target, you would see both the full event and the subset of resource data in your logs. And you can pick out any resource details you need. So if you wanted to print the cluster ARN for each service for example, you might do something like this:

```python
for resource in event['resources']:
    print(resource['clusterArn'])
```

**Comment by gabfelp** [comment]
Thanks again, @ajkerrigan !
