### ISSUE TITLE
Filter to ensure that no EC2 has a security group with certain ports open

### ISSUE THREAD

**Issue by SteveL1** [cloud-custodian/cloud-custodian#7132]
### Ask your question

I'm trying to get custodian to alert if there is an AWS EC2 that has a security group that, say, has port 22 or 3389 open.  The thing I can't figure out how to do is to be able to add instance IDs to the filter to exclude those notification/action.

Is this possible at all? It sounds like it's too specific for general tool but i'm hoping not!

Thanks

**Comment by L3m0nb4tt3ry** [comment]
I would suggest to use tags instead, this way you can filter/ignore resource based on a specific tags rather than hard coding instance IDs.

**Comment by SteveL1** [comment]
I'll probably actually do that and exclude EC2s with a specific tag.

The problem is how can I confirm the confirm the configuration of security groups that are attached to EC2s and use tags on the EC2 for the filter?

**Comment by SteveL1** [comment]
I'll most likely do just that and exclude EC2s based on tags.

The problem is how confirm the security group rules but have the EC2 details in the filter.

**Comment by ajkerrigan** [comment]
Yes @SteveL1 , you got it! That's good feedback about the `security-group` filter too. The [existing docs](https://cloudcustodian.io/docs/aws/resources/aws-common-filters.html#aws-common-filters-security-group) only mention the schema, so examples would help highlight some possibilities.
