### ISSUE TITLE
remove resources attachments

### ISSUE THREAD

**Issue by SteveL1** [cloud-custodian/cloud-custodian#7148]
### Ask your question

I have a policy that removes security groups if the tags on it are not correct.

However you can't remove a security group if it's being used by some another resource like an EC2 or RDS.  Is there a way to remove the associations between the security group and those resources so that it can be deleted?

**Comment by ajkerrigan** [comment]
>  Is there a way to remove the associations between the security group and those resources so that it can be deleted?

Not directly as a security group action, no. The details of removing security group associations varies a bit by resource and can take some time. There are some things you can do as you prepare for a security group deletion though, like:

* Remove ingress and/or egress rules (so the security group still exists but doesn't allow additional traffic)
* Tag the group as pending deletion via the `mark-for-op` or `tag` actions (this allows you to combine the `security-group` filter with the `modify-security-groups` action on resources like EC2 or RDS, to remove security groups based on their tags)

**Comment by SteveL1** [comment]
Thanks for replying!

Shame it's not a function of custodian, that would be really useful!

Good ideas though, thanks :)
