### ISSUE TITLE
Azure: Not able to see anything under Functions/Functions

### ISSUE THREAD

**Issue by aakifshaikh** [cloud-custodian/cloud-custodian#7160]
### Ask your question

I am deploying cloud custodian policies to azure subscriptions via terminal. It looks like the function gets deployed but I don't see anything inside the Function/Functions (no code, no timer, etc).

I am not able to see any results in the output directory. Not sure what's wrong but it is happening for all the policies.

I have attached the message received from in the terminal.
![Screen Shot 2022-03-14 at 5 11 11 PM](https://user-images.githubusercontent.com/27826591/158269701-73be7b06-2fda-41b0-a555-92e46b16add0.png)
@stefangordon - Please Help.

### Policy

```shell
policies:
  - name: sec-n-resourcegroup-orphaned
    resource: azure.resourcegroup
    description: |
      Find all Resource Groups that have no resources in the subscription. 
      This policy runs every 10 minutes to check for the orphaned resources.
    filters:
      - type: empty-group
    mode:
      type: azure-periodic
      schedule: 0 */10 * * * *
      provision-options:
        identity:
          type: UserAssigned
          id: xxxxxxxxx
      execution-options:
        output_dir: azure://cloudcxxxxxxxxxxnet/custodianlogs/xxxx/xxxx/{policy_name}
```

**Comment by kapilt** [comment]
@logachev any ideas ^

**Comment by aakifshaikh** [comment]
Any help is appreciated? I am working under tight timelines and have pressure to make this work. @logachev

**Comment by logachev** [comment]
@aakifshaikh I'm looking into this right now, trying to reproduce it.

**Comment by logachev** [comment]
Minor update:
I can see this issue in my environment.
It is working with Dedicated App Service Plan, but is not working with Consumption functions.
So, it is likely an issue with Azure or the way we use Azure Function APIs rather an issue with the c7n package.

Looking if there were any recent changes on the Azure side in their APIs since it happened earlier.
