### ISSUE TITLE
IMDSv1 Disabled Affected Cloud Custodian

### ISSUE THREAD

**Issue by haiauth** [cloud-custodian/cloud-custodian#7174]
### Ask your question

Is there a better way to run Cloud Custodian without having IMDSv1 enabled? I inadvertently discovered that Cloud Custodian failed to run and gave me an error when I tried to disable IMDSv1 on my instance where Cloud Custodian lives: 

```
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2022-03-18 22:13:31,168: custodian.commands:ERROR The following policies had errors while executing
 - ec2-require-imdsv2
```

### Policy

```shell
policies:
- name: ec2-require-imdsv2
  resource: ec2
  comment: |
    This policy is used to search for instances that have IMDSv1 enabled, then disabled it and turn on IMDSv2. 
  filters:
    - MetadataOptions.HttpTokens: optional
    - MetadataOptions.HttpEndpoint: enabled    
  actions:
      - type: notify
        slack_msg_color: danger  
        violation_desc: |
          IMDSv1 Is Being Used, Please Update to IMDSv2 As Soon As Possible. 
        action_desc: |
          Nothing has been changed but we need to change the IMDS version.          
        to:
          - webhook
        transport:
          type: sqs
          queue: https://sqs.us-east-2.amazonaws.com/<account_ID>/<sqs_name>
```

**Comment by ajkerrigan** [comment]
Custodian leans on AWS SDK packages under the hood (boto3, botocore). Current versions of those packages support IMDSv2, so by extension we do too. There are a couple things you can check that might help sort out what's going on though:

* Do you get a similar credential error if you run `aws sts get-caller-identity` from that instance with imdsv1 disabled?

* What is the output of `custodian version --debug` on that instance?

**Comment by haiauth** [comment]
- I do. Here is the error: 
`Unable to locate credentials. You can configure credentials by running "aws configure".`
- Outputs of `custodian version --debug` is: 
`Custodian:   0.9.14
Python:      3.6.9 (default, Dec  8 2021, 21:08:43) 
             [GCC 8.4.0]
Platform:    posix.uname_result(sysname='<OS>', nodename='<ip-address>', release='5.4.0-1068-aws', version='#72~18.04.1-Ubuntu SMP Thu Mar 3 08:49:49 UTC 2022', machine='<system>')
Using venv:  True
Docker: False
Installed: 

argcomplete==1.12.3
attrs==21.2.0
boto3==1.19.12
botocore==1.22.12
docutils==0.17.1
importlib-metadata==4.8.1
jmespath==0.10.0
jsonschema==3.2.0
pyrsistent==0.18.0
python-dateutil==2.8.2
pyyaml==5.4.1
s3transfer==0.5.0
setuptools==39.0.1
six==1.16.0
tabulate==0.8.9
typing-extensions==3.10.0.2
urllib3==1.26.7
zipp==3.6.0`

**Comment by ajkerrigan** [comment]
Ok those versions are current enough to work with IMDSv2. But if the AWS CLI isn't able to see active credentials, Custodian won't either. It may be worth trying to hit the metadata service with [IMDSv2 style requests](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html#instance-metadata-v2-how-it-works) to see if you get credentials back:

```bash
export TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"`
curl -H "X-aw-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/iam/security-credentials
curl -H "X-aw-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/iam/security-credentials/<your-instance-profile-name>
```

If you get nothing back, it's worth checking to see if the metadata endpoint was disabled entirely for that instance (as opposed to just requiring tokens). If those curl calls bring back some credentials, it suggests the metadata service is OK and the next spot to look would be the AWS CLI configuration.

**Comment by ajkerrigan** [comment]
Glad you got it sorted out, and thank you for reporting back!
