### ISSUE TITLE
Add action to deprecate an AWS AMI

### ISSUE THREAD

**Issue by jrbeilke** [cloud-custodian/cloud-custodian#7232]
### Describe the feature

AWS now supports marking AMIs for deprecation, and it would be helpful if we could do this with Cloud Custodian to automatically deprecate outdated and unused AMIS
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ami-deprecate.html

**Comment by thisisshi** [comment]
closed via: https://github.com/cloud-custodian/cloud-custodian/pull/7974
