### ISSUE TITLE
Support for AWS Organizations

### ISSUE THREAD

**Issue by ss2523** [cloud-custodian/cloud-custodian#7239]
### Describe the feature

It would be nice to have if custodian supports AWS Organizations.

### Extra information or context

Custodian should trigger an alert if any user tries to attach/detach SCP. Alert should continue until the issue is fixed.

**Comment by kapilt** [comment]
support for this added, we have resources for orgs, units, accounts (per organizations api), and attaching/detaching and asserting scps on the org.
