### ISSUE TITLE
How do you deal with 'false positives'? 

### ISSUE THREAD

**Issue by vancentle1996** [cloud-custodian/cloud-custodian#7244]
### Ask your question

I have a situation where there are certain resources that have to violate Cloud Custodian policies in order to work properly. For example, certain S3 buckets cannot be private because they won't work properly if they're private, but Cloud Custodian S3 policies will catch these. How do I add such buckets to a 'whitelist' so Cloud Custodian skips them? 

### Policy

```shell
n/a
```

### Relevant log/traceback output

```shell
n/a
```

**Comment by jtroberts83** [comment]
I would suggest using the value filter with the value_from: parameter to point to a s3 allow list file in the format of JSON, CSV, TXT etc. Then you would just keep the S3 file updated with your current list of S3 bucket exceptions. The file could contain the S3 bucket names being that they are globally unique.

**Comment by vancentle1996** [comment]
Would you mind writing me a sample one? I'd really appreciate your help as always (I have another name as haiauth).

**Comment by vancentle1996** [comment]
I found it. :)

**Comment by vancentle1996** [comment]
If I store unique names of buckets in the text file below, what would go into the key: {BucketName}? Also, do I need to add any expression if I am using a text file? 

```
- type: value
   key: {BucketName}
   op: not-in
   values_from:
       url: s3://mybucket/whitelist.txt
```
