### ISSUE TITLE
Add Owner Tag to AWS Accounts 

### ISSUE THREAD

**Issue by haiauth** [cloud-custodian/cloud-custodian#7257]
### Ask your question

Is there any way I could add an owner tag to an AWS account? I know we can easily add an owner tag to a resource such as EC2, S3 , and so. I am wondering if there's a way to do the same to an account?

We're having a bunch of accounts that have an owner tag pointing to different teams but we want to take ownership of those accounts, therefore, we want to change those owner tags on the account level to our team's name. 

I tried the policy below but I got an error even though it is valid. 

### Policy

policies:	
  - name: ec2-tag-compliance-nag-stop
    resource: aws.account
    comment: |
        Stop all instances marked for termination every hour
        starting 1 day before their termination.
    filters:
      - or: 
        - "tag:owner": absent
        - "tag:Owner": absent
    actions:
      - type: tag
        tags:
            key: Owner
            value: cloud-sec-ops

### Relevant log/traceback output

2022-05-12 17:20:26,224: custodian.commands:ERROR Configuration invalid: accoutn-tag-compliance.yml
2022-05-12 17:20:26,225: custodian.commands:ERROR Error on policy:ec2-tag-compliance-nag-stop resource:aws.account
{'type': 'tag', 'tags': {'key': 'Owner', 'value': 'cloud-sec-ops'}} is not valid under any of the given schemas

Failed validating 'anyOf' in schema[0]['allOf'][1]['properties']['actions']['items']:
    {'anyOf': [{'$ref': '#/definitions/resources/aws.account/actions/enable-cloudtrail'},
               {'$ref': '#/definitions/resources/aws.account/actions/enable-data-events'},
               {'$ref': '#/definitions/actions/aws.invoke-lambda'},
               {'$ref': '#/definitions/actions/aws.invoke-sfn'},
               {'$ref': '#/definitions/actions/aws.notify'},
               {'$ref': '#/definitions/actions/aws.post-finding'},
               {'$ref': '#/definitions/actions/aws.post-item'},
               {'$ref': '#/definitions/actions/aws.put-metric'},
               {'$ref': '#/definitions/resources/aws.account/actions/request-limit-increase'},
               {'$ref': '#/definitions/resources/aws.account/actions/set-ebs-encryption'},
               {'$ref': '#/definitions/resources/aws.account/actions/set-emr-block-public-access'},
               {'$ref': '#/definitions/resources/aws.account/actions/set-password-policy'},
               {'$ref': '#/definitions/resources/aws.account/actions/set-s3-public-block'},
               {'$ref': '#/definitions/resources/aws.account/actions/set-shield-advanced'},
               {'$ref': '#/definitions/resources/aws.account/actions/set-xray-encrypt'},
               {'$ref': '#/definitions/actions/aws.webhook'},
               {'enum': ['webhook',
                         'set-password-policy',
                         'request-limit-increase',
                         'post-finding',
                         'enable-cloudtrail',
                         'enable-data-events',
                         'set-shield-advanced',
                         'set-xray-encrypt',
                         'set-ebs-encryption',
                         'set-s3-public-block',
                         'set-emr-block-public-access',
                         'invoke-lambda',
                         'put-metric',
                         'notify',
                         'invoke-sfn',
                         'post-item']}]}

On instance['actions'][0]:
    {'tags': {'key': 'Owner', 'value': 'cloud-sec-ops'}, 'type': 'tag'}
2022-05-12 17:20:26,226: custodian.commands:ERROR ec2-tag-compliance-nag-stop

**Comment by ajkerrigan** [comment]
Sorry, `tag` isn't a supported action for `aws.account`. As far as I can tell supporting this would require either an AWS Organization resource with a tag action, or support for tagging arbitrary resource via the Resource Groups Tagging API (which seems like an extension of #7223).
