### ISSUE TITLE
Cloud Custodian Only Performs Scans in Us-East-1 and Us-West-2

### ISSUE THREAD

**Issue by haiauth** [cloud-custodian/cloud-custodian#7259]
### Ask your question

Doesn't Cloud Custodian suppose to scan regions that I have AWS resources live there? I just reviewed my scan results and all of them are only for `us-east-1` and `us-west-2` even though a few accounts that we have don't even have anything in those regions. 

### Policy

```shell
N/A
```

### Relevant log/traceback output

```shell
N/A
```

**Comment by ajkerrigan** [comment]
Hi @haiauth - Cloud Custodian will scan the region(s) that you tell it to. If you don't explicitly provide a region, it falls back to the current region (as determined by the AWS CLI) for `custodian run`, or `us-east-1` and `us-west-2` for `c7n-org`.

**Comment by haiauth** [comment]
Thanks @ajkerrigan . How do I specify multiple regions at the same time when running `c7n-org`?

**Comment by haiauth** [comment]
...Or should I specify the region in the config file?

**Comment by ajkerrigan** [comment]
You can use the `-r` command-line option multiple times at runtime (described in the docs [here](https://cloudcustodian.io/docs/tools/c7n-org.html#selecting-accounts-regions-policies-for-execution)) or specify regions in your configuration file as you mentioned (described in the docs [here](https://cloudcustodian.io/docs/tools/c7n-org.html#installation)).

Or... both! You can specify your most common regions in a config file and use one or more `-r` options to override that at runtime when you need to.

**Comment by haiauth** [comment]
Can I do something like `-r all`?

**Comment by ajkerrigan** [comment]
Yep that'll work too.
