### ISSUE TITLE
Do you have sample output for below policies? 

### ISSUE THREAD

**Issue by haiauth** [cloud-custodian/cloud-custodian#7266]
### Ask your question

I am trying to scan our resources and find violations for the policies below but no luck. I need the sample outputs so I can query data in the `resources.json` file to create issues out of it. I have three policies that I need outputs for: 

- 1.2 – Ensure multi-factor authentication (MFA) is enabled for all IAM users that have a console password
- 1.3 – Ensure credentials unused for 90 days or greater are disabled
- 1.5-10 - Password policy 

The policies are respectively posted below: 

### Policy

```shell
First Policy 

policies: 
  - name: iam-root-keys-no-mfa-audit
    comment: |
      Determine if an account has either not been enabled with root MFA or has root API keys.
    resource: account
    filters:
      - type: iam-summary
        key: AccountMFAEnabled
        value: false
        op: eq
        value_type: swap
    actions: 
      - type: notify

Second Policy 

policies: 
  - name: iam-unused-creds-audit
    resource: iam-user
    comment: |
      Ensure credentials unused for 90 days or greater are disabled
    filters:
      - and:
        - type: credential
          key: password_enabled
          value: true
        - type: credential
          key: password_last_used
          value_type: age
          value: 90
          op: gt
        - type: credential
          key: access_keys.active
          value: true
        - type: credential
          key: access_keys.last_used_date
          value_type: age
          value: 90
          op: gt
    actions: 
      - type: notify

Third Policy 

policies: 
  - name: iam-password-audit
    comment: |
      Check password policies. Ensure that account password meets the requirements.
    resource: account
    filters:
      - type: password-policy
        key: MinimumPasswordLength
        value: 14
        op: lt
      - type: password-policy
        key: RequireUppercaseCharacters
        value: false
      - type: password-policy
        key: RequireLowercaseCharacters
        value: false
      - type: password-policy
        key: RequireNumbers
        value: false
      - type: password-policy
        key: RequireSymbols
        value: false
      - type: password-policy
        key: PasswordReusePrevention
        value: 24
        op: lt
    actions: 
      - type: notify
```

**Comment by ajkerrigan** [comment]
You have options here - either intentionally create some resources that will match your policy. Or loosen the restrictions of your policy filters so even your compliant resources show up in `resources.json`. So if you have root user MFA enabled everywhere, great! Change your filter to something like `value: present` or `value: true` instead of `value: false` to see what the match data would look like.

As a general rule, removing or loosening filters is a good way to get sample output in your `resources.json` file.

**Comment by haiauth** [comment]
@ajkerrigan You're the best. Thank you so much!!!
