### ISSUE TITLE
c7n_mailer - allow additional parameters to be passed via mailer.yml to use AWS SES

### ISSUE THREAD

**Issue by PendragonDay** [cloud-custodian/cloud-custodian#7272]
### Describe the feature

Hi there,

Our environment is a large organization (Using AWS orgs). We are constrained in the use of SES. 

SES send-email API calls must include a source-arn. The source-arn is not in the same AWS account as the AWS account where c7n_mailer is deployed. 

By default c7n_mailer is trying to use the default local account source-arn, which would look like this: 

arn:aws:ses:us-east-1:{this_AccountId}:identity/mydomain.com

However, in our environment all accounts must use the SES source-arn that is in the Master AWS account: 

arn:aws:ses:us-east-1:{Master_AccountId}:identity/mydomain.com

Is it possible to add the source-arn as a property in the config schema so it can be passed to the c7n_mailer Lambda? 
https://github.com/cloud-custodian/cloud-custodian/blob/b611e5addd5c91f10897b23e7917e37ed8299c05/tools/c7n_mailer/c7n_mailer/cli.py#L34

**Comment by ajkerrigan** [comment]
Thanks @PendragonDay , good question. It looks like there's a potential feature request here to explicitly support specifying a source ARN. However I'm also wondering if this is achievable today (a bit awkwardly) by tweaking your mailer [configuration](https://cloudcustodian.io/docs/tools/c7n-mailer.html#usage-configuration). I'm looking at how we set email headers and I see a [reference](https://github.com/ajkerrigan/cloud-custodian/blob/6f3608087b9fe5e76adc19a60ad62eb8f792d6c5/tools/c7n_mailer/c7n_mailer/utils_email.py#L122) to a mailer config key called `additional_email_headers`. Given that the boto3 docs for [send_raw_email](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ses.html?highlight=send_raw_email#SES.Client.send_raw_email) mention that you can specify source ARN as an X-header, I'm wondering if you could add something like this to your mailer config:

```yaml
additional_email_headers:
  X-SES-SOURCE-ARN: "arn:aws:ses:us-east-1:{Master_AccountId}:identity/mydomain.com"
```

to allow those mails to go through. Seems worth a shot in any case.

**Comment by PendragonDay** [comment]
@ajkerrigan very interesting! Let me give this a try. I will update here.

**Comment by PendragonDay** [comment]
@ajkerrigan,

This was a great suggestion. It works! However, I had to pass all these for send_raw_email to work. They are all required parameters: https://docs.aws.amazon.com/ses/latest/dg/sending-authorization-delegate-sender-tasks-email.html

X-SES-SOURCE-ARN:
X-SES-FROM-ARN: 
X-SES-RETURN-PATH-ARN:

Which should be the same arn  for all three. So my configuration file (mailer.yml) looks like this:

```
additional_email_headers:
  X-SES-SOURCE-ARN: "arn:aws:ses:us-east-1:{Master_AccountId}:identity/mydomain.com"
  X-SES-FROM-ARN: "arn:aws:ses:us-east-1:{Master_AccountId}:identity/mydomain.com"
  X-SES-RETURN-PATH-ARN: "arn:aws:ses:us-east-1:{Master_AccountId}:identity/mydomain.com"
```

**Comment by ajkerrigan** [comment]
That's great news! Glad you got it working, nice job sorting out the details, and thank you so much for sharing them here afterward. :star:
