### ISSUE TITLE
Allow config-poll-rules to support resources without a CFN template

### ISSUE THREAD

**Issue by DuckieHo** [cloud-custodian/cloud-custodian#7462]
### Describe the feature

I am always frustrated when a native c7n resource cannot be utilized in config-poll-rule mode. This requires me to duplicate efforts to write a custom policy code.

In config-poll-rule mode, a validation checks if the the resource type is supported by a [CFN template](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html). However, we would like to run policies for AWS resources that are not supported by CFN.

### Extra information or context

An example would be the [account resource](https://cloudcustodian.io/docs/aws/resources/group-account.html). In config-poll-rule mode, the validation fails with: `ERROR Policy: guardduty-enabled is invalid: policy:%s resource:%s does not have a cloudformation type and is there-fore not supported by config-poll-rule`. The resource type does exists and the policy would run.

A suggested least impactful enhancement would be:
- Provide an additional flag to bypass the CFN support validation
- Enhance [account resource](https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/resources/account.py) to be aware that is is the resource type of "AWS::::Account"

**Comment by DuckieHo** [comment]
Hi @thisisshi, @ajkerrigan and I discussed this in the gitter channel.

That feature allows you to utilize "AWS Config Rules supported resources" in config-poll-rule mode.  Rather than using the event-driven approach of Config Rules, a user wants to run it in periodically.  Before the 0.9.16.0 release, c7n would force you to run it in event-driven Config Rules.

This request is for a resource that is neither supported by AWS Config Rules nor CFN.  c7n has native resources (e.g. account) that I would like to access as a periodic Config Rule.  An example would be: Does this account have Guard Duty enabled?  If not, throw a Config Rule compliance error for the resource type of "aws::::account".

**Comment by DuckieHo** [comment]
To further elaborate, there are quite a few AWS resources that do not have CFN interface.  (The doc describes what resources that can be tagged through Tag Editor but through CFN.  Since I assume if a CFN interface exists, it would have provided a tag function.)
https://docs.aws.amazon.com/ARG/latest/userguide/supported-resources.html#services-organizations

**Comment by DuckieHo** [comment]
The underlying issue is there is mismatch between:
- What is being monitored?  (config-rule = AWS Config, config-poll-rule = CFN)
- What is compliant?  (Any AWS resource)

Since config-poll-rule is periodic-based and not resource/event-based, there shouldn't be a need to validate CFN support.

**Comment by kapilt** [comment]
Cfn support is the vocabulary used by the config service to report results against a resource, in this case they also extended the cfn type registry vocabulary with a custom entry for account. The referenced pr in #7476 supports the use case you have, But you can’t say post against an arbitrary string, ie. Config’s Resource type when posting evaluations has to be registered with the cloudformation type registry (which does support third party/custom types incidentally). Ie,  cfn type is mandatory for the aws config side service even in poll mode.
