### ISSUE TITLE
Add a way to filter out dead-letter-queues from list of SQS queues

### ISSUE THREAD

**Issue by stepkirk** [cloud-custodian/cloud-custodian#7463]
### Describe the feature

We are looking [for](url) a way to cleanup our unused AWS SQS queues. We have a policy that filters down to queues that have not been used in the past year. Now we need to be able to filter out dead-letter-queues (DLQs) from the list. We do not want to inadvertently remove any DLQs that are still needed but not receiving messages (because everything works so well).

We had a quick discussion about this in Gitter on May 26-27 and @ajkerrigan gave us a way to identify the DLQs using jq. Hopefully something can be added to custodian to allow us to filter out the DLQs directly from the policy?

### Extra information or context

Here is a bit of what @ajkerrigan had to say in Gitter:

>  this sounds like a feature request for a filter that checks for dead letter source queues. It could use list-dead-letter-source-queues under the hood (alternatively since we already have redrive policies cached for all queues in the region, may be able to leverage that data and save on API calls). It's worth filing as an issue to sort it out though. Ananth's workaround looking for the queue twice in resources.json is interesting though in the meantime.

**Comment by thisisshi** [comment]
This doesnt actually require any additional api calls as we can inspect the redrive policy on the resources directly, I'll put up a PR for this

**Comment by thisisshi** [comment]
PR: https://github.com/cloud-custodian/cloud-custodian/pull/7466

**Comment by stepkirk** [comment]
Thanks for the quick work on this @thisisshi ! 

Can/should the code ignore duplicate DLQs or do I need to address that in the policy?

In one of our accounts, there are three different non-DLQs that each point to the same single DLQ and that DLQ shows up three times in the results after deploying the code in the associated PR 7466

**Comment by stepkirk** [comment]
Latest code is working fine for us. Dedupes the list of DLQs like a champ.  Thanks again @thisisshi .
