### ISSUE TITLE
[Doc] Installation failed as I don't have "python" executablre

### ISSUE THREAD

**Issue by patrocinio** [cloud-custodian/cloud-custodian#7521]
### Describe the bug

I'm following the steps at https://cloudcustodian.io/docs/developer/installing.html#on-macos-with-homebrew:~:text=Own%20Virtual%20Environment-,%C2%B6,-Running%20directly%20from.
When I run the following command:
``
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
``
it fails, as I don't have a python executable, only python3.

### What did you expect to happen?

I expected the command to work with python3.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
N/A. I am still installing it.
```

### Policy

```shell
N/A
```

**Comment by ajkerrigan** [comment]
Thanks for filing, there are a few updates we can make to install docs. The most direct update for this case is to follow [Poetry's guidance](https://python-poetry.org/docs/master/#installing-with-the-official-installer) for installing. They're deprecating the install script we show in the docs, and the reference docs to mention `python3` for Mac.

**Comment by ajkerrigan** [comment]
FYI I was working on some developer install quality-of-life improvements that became too big to handle as a single change. Extracting just the documentation update piece in #7522 . If you're going through a developer install now and seeing issues, I'd be curious to see if those doc changes have any effect (whether positive or not).

**Comment by ajkerrigan** [comment]
> Hello @ajkerrigan So should we clean up the documentation and point to the poetry's way?

Yep, I think so. #7522 includes that change and a couple other minor things I came across at the time (some minor version numbers, and we've largely moved away from tox as the default test runner, for example).
