### ISSUE TITLE
Issue with mismatch-s3-origin filter for aws.distribution resource

### ISSUE THREAD

**Issue by ajkerrigan** [cloud-custodian/cloud-custodian#7529]
### Discussed in https://github.com/orgs/cloud-custodian/discussions/7527

<div type='discussions-op-text'>

<sup>Originally posted by **vgsachin88** June 27, 2022</sup>
There is an issue with the mismatch-s3-origin filter for aws.distribution resource. I am getting the below

**Policy**
`policies:
  - name: mismatch-s3-origin
    resource: distribution
    filters:
      - type: mismatch-s3-origin
        check_custom_origins: true`
 
**Error**
`[ec2-user]$ c7n-org run -c ../accounts.yml -s out -u ./testpolicy.yml --cache-period 0 -r us-east-1 --debug
    resources = self.policy.resource_manager.resources()    resources = self.filter_resources(resources)
-> if target_bucket is not None and target_bucket not in buckets:
Traceback (most recent call last):
    sys.exit(cli())
    return ctx.invoke(self.callback, **ctx.params)
    resources = mode.run()
    resources = self.policy.resource_manager.resources()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/c7n/query.py", line 532, in resources
    resources = self.filter_resources(resources)
    resources = f.process(resources, event)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/c7n/resources/cloudfront.py", line 330, in process
    if target_bucket is not None and target_bucket not in buckets:
UnboundLocalError: local variable 'target_bucket' referenced before assignment`

I guess it is due to the way the RegEx pattern matching is happening, my S3 Origin domain name is like this mytestbucket25jun.s3.us-east-1.amazonaws.com which is not getting matched by the below regex

`s3_prefix = re.compile(r'.*(?=\.s3(-.*)?\.amazonaws.com)')
s3_suffix = re.compile(r'^([^.]+\.)?s3(-.*)?\.amazonaws.com')`

</div>

**Comment by vgsachin839** [comment]
@ajkerrigan Any update on when this issue will be fixed ?
