### ISSUE TITLE
aws.ec2 returns terminated instances

### ISSUE THREAD

**Issue by alpana17** [cloud-custodian/cloud-custodian#7554]
My config.yml is:
`policies:
    - name: ec2-underutilized
    resource: ec2
    filters:
      - type: metrics
        name: CPUUtilization
        days: 4
        period: 86400
        value: 2
        op: less-than
     `

It is returning terminated instances as well. Why is it so?

**Comment by thisisshi** [comment]
Can you include your policy here? You can add a filter to remove terminated resources from the results
