### ISSUE TITLE
NoneType Issue

### ISSUE THREAD

**Issue by jwtdrjj** [cloud-custodian/cloud-custodian#7567]
I dropped a yaml file into a new OU/SubOU and its not working, though it works in other OUs just fine.   Nothing was changed in the file but I am still getting this error, not sure why.

```
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.12/bin/custodian", line 8, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/c7n/cli.py", line 363, in main
    command(config)
  File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/c7n/commands.py", line 219, in validate
    structure.validate(data)
  File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/c7n/structure.py", line 48, in validate
    self.validate_policy(p)
  File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/c7n/structure.py", line 78, in validate_policy
    for a in p.get('actions', ()):
TypeError: 'NoneType' object is not iterable
```

**Comment by kapilt** [comment]
which command are you using here?  does the policy file validate? 

that reads like a null acitons in the policy array in the file.  try actions: [] if you don't want actions or removing the actions part entirely. 

that said, it does seem like a bug in our structural validation prior to doing jsonschema validation, it does check for null right before this but as it does so as a default vs an explicit null value set.

**Comment by jwtdrjj** [comment]
The biggest issue is I am taking over for the person who set this up and I am not sure of all the ins and outs.   

1. I created new OUs under policies/OU that haven't been used before.
2. I copied existing policy yamls into those new /OU/OUs
3. I then get the above error when running validation.
4. I removed the actions parameter and still got the error in validation
5. I removed the yaml that it was erroring on and received the exact same error on the next yaml in the list.  
6. These yamls work in existing /OU/OUs


I noticed a few things

`       if [ "$VALIDATION" != true ] ; then
          python3 create_c7n-org_configs.py
        fi 
`

if we are running validation then create_c7n-org_configs.py doesn't run.   

The error occurs when this runs.

`        if [ "$VALIDATION" = true ] ; then
          for PARENT in $(find ./policies/ou/ -mindepth 1 -type d)
          do
              find $PARENT -maxdepth 1 -name "*.yml" ! -name "accounts-*" -exec python3 tag_c7n-policy.py {} \; -exec custodian validate {} \; -exec custodian run {} -s output --assume Role --region us-east-1 --region us-west-2 --region us-east-2 \;
          done
        else
          for PARENT in $(find ./policies/ou/ -mindepth 1 -type d)
          do
            find $PARENT -maxdepth 1 -name "*.yml" ! -name "accounts-*" -exec python3 tag_c7n-policy.py {} \; -exec custodian validate {} \; -exec c7n-org run -c $PARENT/accounts-$(basename $PARENT).yml -s output -u {} --region us-east-1 --region us-west-2 --region us-east-2 \;
          done
        fi`

**Comment by thisisshi** [comment]
It looks like you're running a python script to generate your custodian policies, can you post a sample policy, aka the output of the line:

```
find $PARENT -maxdepth 1 -name "*.yml" ! -name "accounts-*" -exec python3 tag_c7n-policy.py {} 
```

**Comment by jwtdrjj** [comment]
@thisisshi The error above is the output.  When I remove the yaml policy files and leave the file structure, it just has this for all the policies in the other OUs.

`
2022-07-19 18:17:59,154: custodian.policy:INFO Provisioning policy lambda: Governance-redshift-mandatory-tag-check-rem region: us-west-2
--
933 | 2022-07-19 18:18:00,440: custodian.policy:INFO Provisioning policy lambda: Governance-redshift-mandatory-tag-pass region: us-west-2
`

@kapilt are there any changes I need to make to make sure we are using the latest commit.
