### ISSUE TITLE
APIGateway resources returned are tuples

### ISSUE THREAD

**Issue by harishachappa** [cloud-custodian/cloud-custodian#7573]
### Describe the bug

DynamoDB resources which are being returned are tuples. This causes https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/query.py#L103 to throw an exception.

Full traceback:
```
[ERROR] TypeError: tuple indices must be integers or slices, not str
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 4, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 165, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 1143, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 438, in run
    resources = self.resolve_resources(event)
  File "/var/task/c7n/policy.py", line 633, in resolve_resources
    return super().resolve_resources(event)
  File "/var/task/c7n/policy.py", line 421, in resolve_resources
    resources = self.policy.resource_manager.get_resources(resource_ids)
  File "/var/task/c7n/query.py", line 565, in get_resources
    resources = self.source.get_resources(ids)
  File "/var/task/c7n/query.py", line 226, in get_resources
    return self.query.get(self.manager, ids)
  File "/var/task/c7n/query.py", line 109, in get
    resources = [r for r in resources if r[m.id] in identities]
  File "/var/task/c7n/query.py", line 109, in <listcomp>
    resources = [r for r in resources if r[m.id] in identities]
```
    
Active Response policy which throws the above error:
```
  - name: apigw-activeresponse-policy
    resource: rest-stage
    description: apigw activeresponse policy
    mode:
      type: cloudtrail
      timeout: 300
      events:
        - source: apigateway.amazonaws.com
          event: CreateStage
          ids: "responseElements.deploymentId"
      role: arn:aws:iam::<<<aws_account_id>>>:role/<<some_role_name>>
      mode: "debug"
```
I will submit a PR to fix this issue

### What did you expect to happen?

No exception and apigateway resources were fetched successfully

### Cloud Provider

Amazon Web Services (AWS)

**Comment by kapilt** [comment]
This relates to the change of done on deployment id from #7519 ?

**Comment by kapilt** [comment]
rest-stage is a child resource, in this case nested in an api gateway, child resources don't natively support event based modes, without explicit support in the resource. if I try to run that policy with custodian, I'll get a validation error affirming the lack of support.
<img width="1434" alt="Screen Shot 2022-07-21 at 9 03 07 AM" src="https://user-images.githubusercontent.com/21650/180220266-dcac612b-be50-49f2-bc8b-54e523f8c047.png">

**Comment by harishachappa** [comment]
> rest-stage is a child resource, in this case nested in an api gateway, child resources don't natively support event based modes, without explicit support in the resource. if I try to run that policy with custodian, I'll get a validation error affirming the lack of support. <img alt="Screen Shot 2022-07-21 at 9 03 07 AM" width="1434" src="https://user-images.githubusercontent.com/21650/180220266-dcac612b-be50-49f2-bc8b-54e523f8c047.png">

https://github.com/cloud-custodian/cloud-custodian/pull/7574 should fix this issue and provide support for cloudtrail mode

**Comment by ajkerrigan** [comment]
It looks like the tuple issue stems from using a child resource with `capture_parent_id` enabled (which `aws.rest-stage` sets [here](https://github.com/cloud-custodian/cloud-custodian/blob/a38464e809db68f76983ce9779d8712c4b19a525/c7n/resources/apigw.py#L271)). That combination causes a resource list to show up in the form `[(parent id, resource)]`.
