### ISSUE TITLE
GCP mark(ed)-for-op support op that contains hyphen

### ISSUE THREAD

**Issue by kentnsw** [cloud-custodian/cloud-custodian#7623]
### Describe the bug

The below filter works as expected. But if change the op to anything contains hyphen, eg `set-public-access-prevention`, it won't work because the way we split the label value, `msg, action, action_date_str = v.rsplit('-', 2)` at line 89 of _tools/c7n_gcp/c7n_gcp/filters/labels.py_.
```yaml
      - type: marked-for-op
        label: custodian_status
        op: notify
```
I revised it in my folk and here are [the changes](https://github.com/newscorp-ghfb/cloud-custodian/pull/124/files). It is not backward compatible so no PR will be summited.
```python
msg, action, action_date_str = v.rsplit('--', 2)
```
On the other hand, I wonder how Cloud Custodian handles this kind of non-backword-compatible changes?

### What did you expect to happen?

I expect it to support all actions.

### Cloud Provider

Google Cloud (GCP)

### Cloud Custodian version and dependency information

```shell
0.9.17, macOS
```

**Comment by kapilt** [comment]
hmm.. thanks for the bug report, in terms of maintaining compatibility, I think it would be best for us to build an action vocabulary set, and do a split('-', 1) with longest prefix match to determine action. Its also worth reviewing the behavior here in other providers.
