### ISSUE TITLE
Cloud custodian v0.9.18.0 is not able to find our policy file in the container

### ISSUE THREAD

**Issue by Glen-Tigera** [cloud-custodian/cloud-custodian#7656]
### Describe the bug

My team has been using Cloud Custodian running in Semaphore CI for about 6 months without any issues to help cleanup our cloud resources. Recently, we noticed that the latest release of Cloud Custodian (v0.9.18.0) broke our CI jobs.

We run cloud custodian docker image in our CI/CD as follows:
```
docker run -it --user $(id -u):$(id -g) \
  -v $(pwd)/output:/home/custodian/output \
  -v $(pwd)/cleanup/cloud-custodian/policy.yml:/home/custodian/policy.yml \
  -e AWS_DEFAULT_REGION="us-west-2" \
  -e AWS_SECRET_ACCESS_KEY=$AWS_NUKE_KEY_SECRET \
  -e AWS_ACCESS_KEY_ID=$AWS_NUKE_KEY_ID \
  --env-file <(env | grep "^AWS\|^AZURE\|^GOOGLE") \
  --net=host \
  cloudcustodian/c7n run \
  -v -s /home/custodian/output \
  /home/custodian/policy.yml
```
We bind a volume mount to where our policy file is on the machine to the container at **/home/custodian/policy.yml**.
This works on v0.9.17.0 fine but for v0.9.18.0 image we get this in the logs:

```
Unable to find image 'cloudcustodian/c7n:latest' locally
latest: Pulling from cloudcustodian/c7n
Status: Downloaded newer image for cloudcustodian/c7n:latest
2022-08-15 17:36:52,215: custodian.commands:ERROR policy file does not exist (/home/custodian/policy.yml)
2022-08-15 17:36:52,215: custodian.commands:ERROR Found 1 errors.  Exiting.
```

Our workaround is to go back to using 0.9.17.0 just doing **docker run -it ... cloudcustodian/c7n:0.9.17.0 run...**, but we'd like to use the latest if possible. Let me know if there is anything else I can provide to help with this. Thank you!

### What did you expect to happen?

I expected it to find the policy file which contains our cloud custodian cleanup policies.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
v0.9.18.0
```

### Policy

```shell
N/A
```

### Relevant log/traceback output

```shell
Unable to find image 'cloudcustodian/c7n:latest' locally
latest: Pulling from cloudcustodian/c7n
Status: Downloaded newer image for cloudcustodian/c7n:latest
2022-08-15 17:36:52,215: custodian.commands:ERROR policy file does not exist (/home/custodian/policy.yml)
2022-08-15 17:36:52,215: custodian.commands:ERROR Found 1 errors.  Exiting.
```

### Extra information or context

N/A

**Comment by ajkerrigan** [comment]
Interesting, not sure offhand what would cause that. I've tried running a similar command on my end just to see if this was a global issue, but the policy ran fine with the 0.9.18.0 docker image. Some steps that might provide some useful troubleshooting detail:

* Let us know the platform you're running on and the output of `docker --version` in case it helps reproduce the issue
* Try temporarily using absolute paths in your mount rather than `$(pwd)` - I can't see how this would break only 0.9.18.0, but when something weird is happening being explicit can be helpful
* Add `--entrypoint=/bin/bash` to your `docker run` command, then:
  * From inside the running container, look in `/home/custodian` to see if you're missing everything or just the policy file

  * From another terminal pane/window on your host machine, run a command like `docker inspect -f '{{range .Mounts}}{{json . | println}}{{end}}' $(docker ps -f ancestor=cloudcustodian/c7n -q)` to see if the bind mounts are showing up as you expect

Hopefully something in there will help find a troubleshooting thread to pull on.

**Comment by kapilt** [comment]
that sounds fairly strange, the only significant container change with 0.9.18.0 was an update to ubuntu 22.04 as a base for all images, fwiw, but that shouldn't be relevant, this is just a volume point. if you do go interactive, it would be interesting to check the permissions on the policy file in the container.

**Comment by Glen-Tigera** [comment]
Thanks for your thoughts @ajkerrigan and @kapilt. The CI system is using `Docker version 20.10.17, build 100c701`. Here are the permissions for the policy file:
```
-rw-rw-r-- 1 semaphore semaphore 4491 Aug 18 22:04 policy.ym
```

I narrowed it down as this seems related to running the container in CI as a non-root user since we pass in the `--user $(id -u):$(id -g)` flag to run it. Both $(id -u) and $(id -g) evaluate to 1001, which is the id of the Semaphore CI user which seems to no longer work as of v0.9.18.0.

So I changed this to use the root id which is zero like below, and the policy file could be found and ran just fine.
```
semaphore@semaphore-vm:$ docker run -it --user 0   -v $(pwd)/output:/home/custodian/output   -v $(pwd)/cleanup/cloud-custodian/policy.yml:/home/custodian/policy.yml   -e AWS_DEFAULT_REGION="us-west-2"   -e AWS_SECRET_ACCESS_KEY=$AWS_NUKE_KEY_SECRET   -e AWS_ACCESS_KEY_ID=$AWS_NUKE_KEY_ID   --env-file <(env | grep "^AWS\|^AZURE\|^GOOGLE")   --net=host   cloudcustodian/c7n run --dryrun  -v -s /home/custodian/output   /home/custodian/policy.yml
2022-08-18 22:07:28,448: custodian.commands:DEBUG Loaded file /home/custodian/policy.yml. Contains 21 policies
2022-08-18 22:07:28,454: custodian.aws:DEBUG using default region:us-west-2 from boto
```

**Comment by kapilt** [comment]
custodian doesn't run as a root in the container, but it does run as a different non privileged user 'custodian' 
https://github.com/cloud-custodian/cloud-custodian/blob/master/docker/cli#L55

which is likely causing the permission issue your seeing wrt to accessing the policy file.

**Comment by ajkerrigan** [comment]
Coming back to this, looks like it can be closed. But just to review what seems to have actually changed, here are the permissions on `/home/custodian` in `0.9.17.0`:

```
$  stat /home/custodian
  File: /home/custodian
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: fd01h/64769d    Inode: 10872077    Links: 2
Access: (0755/drwxr-xr-x)  Uid: ( 1000/custodian)   Gid: ( 1000/custodian)
```

And here's 0.9.18.0:

```
$ stat /home/custodian
  File: /home/custodian
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: fd01h/64769d    Inode: 10872077    Links: 2
Access: (0750/drwxr-x---)  Uid: ( 1000/custodian)   Gid: ( 1000/custodian)
```

So running as uid `1001` would have worked in 0.9.17.0 but not in 0.9.18.0. Running as uid `1000` (the `custodian` user in the container) or uid `0` (root) allows access to files under `/home/custodian` to continue working.

Let us know if there are any unresolved aspects of this issue. And thanks for opening it! it'll be a helpful reference for anyone else in a similar situation.

**Comment by Glen-Tigera** [comment]
Sounds good, I will try running the container with the custodian user id and get back to you @ajkerrigan. Appreciate your support on this!

**Comment by Glen-Tigera** [comment]
@ajkerrigan from a quick test I ran with passing in --user 1000 in my docker run command, so non-root. It looks like it can run the policy but the output gives permission creating folders from the results. Have you ran into this issue before? thanks

PermissionError: [Errno 13] Permission denied: '/home/custodian/output/eip-del'00:20
2022-09-06 17:59:37,357: custodian.commands:ERROR Error while executing policy igw-mark, continuing00:20
Traceback (most recent call last):00:20
  File "/src/c7n/commands.py", line 301, in run00:20
    policy()00:20
  File "/src/c7n/policy.py", line 1286, in __call__00:20
    resources = mode.run()00:20
  File "/src/c7n/policy.py", line 282, in run00:20
    with self.policy.ctx as ctx:00:20
  File "/src/c7n/ctx.py", line 74, in __enter__00:20
 00:20
  File "/src/c7n/ctx.py", line 48, in initialize00:20
    self.output = blob_outputs.select(self.options.output_dir, self)00:20
  File "/src/c7n/output.py", line 54, in select00:20
    return self[k](ctx, parse_url_config(selector))00:20
  File "/src/c7n/output.py", line 450, in __init__00:20
    os.makedirs(self.root_dir)00:20
  File "/usr/lib/python3.10/os.py", line 225, in makedirs00:20
    mkdir(name, mode)

**Comment by Glen-Tigera** [comment]
I will find a way to resolve the file permissions internally. I think it should be straightforward if I play around with the docker volume mounts. Thanks!

**Comment by ajkerrigan** [comment]
Gah, apologies I had an unsent reply sitting here. Essentially saying what you said but with more words :joy: . In case it's useful...

If you're going to running the container as uid 1000 (with `--user 1000` or rolling with the defaults), you'll want your _host's_ uid 1000 and/or gid 1000 to be able to write to that `output` directory on your host. One way would be to let group id 1000 own that directory and grant group write permissions:

```
mkdir output
chmod 0775 output
chown --recursive :1000 output
```

Like you said, sounds like a matter of fiddling with volume ownership and permissions at this point. Good luck!
