### ISSUE TITLE
Any way to filter on tags for Cognito identity-pool or user-pool?

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#7660]
### Discussed in https://github.com/orgs/cloud-custodian/discussions/7616

<div type='discussions-op-text'>

<sup>Originally posted by **stepkirk** August  5, 2022</sup>
We normally enforce tags on AWS resources by using Custodian to look for certain required tags on a resource and then, if the tags don't exist or aren't in the correct format, we mark the resource for deletion after a certain grace period. With the Cognito identity-pool and user-pool resources, it doesn't look like we can check for tags the normal way and it doesn't look like we can mark a resource for later deletion. Is that true or am I missing something?

Any plans to add tagging/marking support in the future for these Cognito resources?</div>

**Comment by linuxananth1976** [comment]
Couple of things raised above is tagging and marking i.e, filter and action for marked-for-op and mark-for-op respectively. Believe tag is completed is there any idea on marking side, or it was missed one that time?  Please let's know any new issue needs to be create as separately?
