### ISSUE TITLE
consider lazy evaluate tag augmentation on various resources

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#768]
various resources don't include tags by default in responses, we often default to augmenting them for ease of use and consistency on tags, but we should ideally only do tag augmentation by default if the resource policy is using tags.

there's some subtleties wrt to cache, as we cache augmented resources across multiple policies, and the cache key would need to reflect that (layered use of cache to avoid extraneous resource set lookup on policy with tags).

**Comment by kapilt** [comment]
in particular the default augment behavior is problematic on rds/rds-snapshots where the api requires per resource api calls to fetch the needed metadata.

**Comment by kapilt** [comment]
currently custodian augments any taggable resource to ensure tags are present on the resource, to ease a common case of tag policies, for services that include tags in resource outputs, or have bulk tag fetch apis, thats not an issue, for db resources, this is becoming an issue, as they require fetching tags per resource, and we have tens of thousands of snapshots.  i think going forward for rds in particular we need to make a value filter subclass that on tag resolution retrieves tags and stores under a different cache key.

**Comment by kapilt** [comment]
the recent addition of support for querying/polling from config as an alternate source alleviates this, as config stores the tags alongside the resource as supplementary config, completing #907 will effectively give a viable solution for this.

**Comment by alfredgamulo** [comment]
The universal tag api also solves the concern on Jan 23 about the individual calls needed for db resources. 
http://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/Welcome.html

**Comment by kapilt** [comment]
agreed universal tags aka resource group tagging api is probably the best we'll be able to do, lazy evaluation here involves a bunch of meta evaluation logic of a policy that would make things much more complicated.
