### ISSUE TITLE
Add Glue Connections tagging filter and action

### ISSUE THREAD

**Issue by peterheo** [cloud-custodian/cloud-custodian#7690]
### Describe the feature

I would like to implement a tagging filter and action for the glue connection resource type.

### Extra information or context

For this implementation, I'm wondering if just adding the universal_taggable parameter to the resource_type would be sufficient. Please let me know your thoughts!

**Comment by thisisshi** [comment]
Looks like glue crawler, job, and trigger are available in the resourcegroupstagging api. It doesn't look like connection is one of the resources you can tag in glue see: https://docs.aws.amazon.com/glue/latest/dg/monitor-tags.html

**Comment by peterheo** [comment]
Yes so I saw that you could tag glue connections when creating them but I see that there really isn't a way to get the tag information or otherwise do anything with those tags. Sorry about the misunderstanding.

**Comment by PratMis** [comment]
@peterheo I guess if you're still interested you would be able to implement tagging actions on glue-connections outside of resourcegrouptagging. Potentially an augment function to retrieve tags and modify them into custodian's format if required
