### ISSUE TITLE
Distroless images are not getting built

### ISSUE THREAD

**Issue by ericofusco** [cloud-custodian/cloud-custodian#7776]
### Describe the bug

Last image built and pushed with distroless happened 2 years ago with the tag distroless-0.9.6.0.

### What did you expect to happen?

I expected distroless images available with a recent updated distroless base image and latest cloud custodian versions.

### Cloud Provider

Amazon Web Services (AWS)

**Comment by kapilt** [comment]
we don't publish distroless images anymore, as they weren't seeing much if any usage, and we wanted to reserve our ci  utilization (multi arch images take a bit of time). we do still retain the distroless docker files for those that want to build themselves in our docker/ directory. in practice the size difference on the images was negligible.
