### ISSUE TITLE
AWS - global resource cloudfront runs on multiple regions

### ISSUE THREAD

**Issue by ericofusco** [cloud-custodian/cloud-custodian#7814]
### Describe the bug

cloudfront is a global service (meaning us-east-1) and client responds with the same resources from any region, where a policy is created with cloudfront and I have other policies that checks on regional resources so I need to run across multiple regions, it causes cloudfront policies to be executed multiple times on the same resource.

### What did you expect to happen?

I was able to workaround that by using:

```
    conditions:
      - region: us-east-1
```

But seems a better option would be enforcing us-east-1 for cloudfront. 

### Cloud Provider

Amazon Web Services (AWS)

### Extra information or context

Using container image `cloudcustodian/c7n-org:0.9.18.0`.

**Comment by kapilt** [comment]
you want to use policy conditions to limit global resources to a single region, such that executing the containing file across multiple regions, only has a single policy execution.  custodian itself doesn't know if the policy is going to be run against multiple regions across cli invocations..using a condition makes the intent explicit by binding the resource to a single region that the policy will be executed against. https://cloudcustodian.io/docs/quickstart/advanced.html#conditional-policy-execution
