### ISSUE TITLE
Lambda does not have filter to check on policy statements that allow public access.

### ISSUE THREAD

**Issue by BinduHK** [cloud-custodian/cloud-custodian#7831]
### Describe the bug

Lambda does not have filter to check on policy statements that allow public access.

### What did you expect to happen?

Please let me know whether i have any filter to detect those policy statements that allow public access.

### Cloud Provider

Amazon Web Services (AWS)

**Comment by kapilt** [comment]
because it doesn't have a feature you want, doesn't make it a bug re correct label.

further more the filter your asking about already does exist.. would recommend looking at the reference docs (either online) or built in to the cli

```
$ custodian schema aws.lambda

Help
----

A Cloud Custodian resource

aws.lambda:
  actions:
  - auto-tag-user
  - copy-related-tag
  - delete
  - invoke-lambda
  - invoke-sfn
  - mark-for-op
  - modify-security-groups
  - notify
  - post-finding
  - post-item
  - put-metric
  - remove-statements
  - remove-tag
  - set-concurrency
  - set-xray-tracing
  - tag
  - trim-versions
  - webhook
  filters:
  - check-permissions
  - config-compliance
  - cross-account
  - event
  - event-source
  - finding
  - iam-analyzer
  - kms-key
  - marked-for-op
  - metrics
  - network-location
  - ops-item
  - reduce
  - reserved-concurrency
  - security-group
  - subnet
  - value
  - vpc
```

the cross-account one is the one you want.
