### ISSUE TITLE
Use case-insensitive checks for allowed conditions in `cross-account` filters

### ISSUE THREAD

**Issue by ajkerrigan** [cloud-custodian/cloud-custodian#7837]
### Describe the feature

Today the `cross-account` filter has a `whitelist_conditions` parameter that skips matching resources if certain condition keys exist (by default, this list includes `aws:username` and `aws:userid`).

When evaluating condition keys against the allow list, we [lowercase resource data as part of a normalization pass](https://github.com/cloud-custodian/cloud-custodian/blob/772f5461ac851a1b4ad4b1e8e82068d50c3270bc/c7n/filters/iamaccess.py#L206). But we don't also lowercase the `whitelist_conditions` items in the policy. Normalizing both sides (possibly as part of the property defined [here](https://github.com/cloud-custodian/cloud-custodian/blob/772f5461ac851a1b4ad4b1e8e82068d50c3270bc/c7n/filters/iamaccess.py#L73-L75)) would avoid some usability bumps when matching on mixed-case condition keys.

### Extra information or context

While we're at it, it's probably worth adding aliases like `allow*` for the existing `whitelist*` parameters (opening the door for deprecating `whitelist*` going forward). _This is possibly/probably best left as a separate work item, but the idea does naturally come up when you find yourself typing whitelist so many times into an issue description!_

**Comment by kapilt** [comment]
that makes sense, alternatively doc string to specify conditions on lower, but auto convert does make it non dependent on user/author so net win.

**Comment by Rajath-55** [comment]
Hello, can I work on this issue?

**Comment by ajkerrigan** [comment]
Sure @Rajath-55 - go for it! A couple resources that might be helpful along the way:

- [Contributor Guide](https://cloudcustodian.io/docs/contribute.html)
- [Community Slack](https://communityinviter.com/apps/cloud-custodian/c7n-chat)
  - The #development channel would be a good place to ask questions if you hit any bumps getting set up or making changes
