### ISSUE TITLE
Automatically filter out automated snapshots from rds-snapshot resource.

### ISSUE THREAD

**Issue by khapp** [cloud-custodian/cloud-custodian#7838]
### Describe the feature

Automatically filter out automated snapshots from rds-snapshot resource so that a manual filter does not need to be applied to the policies to exclude them. 

Example of current filter:
- not: 
    - "SnapshotType": "automated"

When rds-snapshot tries to delete automated snapshots the following errors are received:

ERROR - Exception deleting snapshot set
An error occurred (InvalidDBSnapshotState) when calling the DeleteDBSnapshot operation: automated snapshots cannot be deleted.

**Comment by kapilt** [comment]
hmm.. that's tricky, some use cases on the policy want to count automated, but at least for the delete action it does make sense to auto filter them out as not actionable on.

**Comment by khapp** [comment]
Closed via #7938
