### ISSUE TITLE
Unable to Copy tags from EC2 to Security Groups.

### ISSUE THREAD

**Issue by Brahmaji1123** [cloud-custodian/cloud-custodian#7847]
### Describe the bug

I am using mentioned policy to copy tags from EC2 to Security Groups but not copied so could you please help me to create policy.

### What did you expect to happen?

Unable to Copy tags from EC2 to Security Groups so could you please help me to create policy or please share me policy for copy tags to Security Groups.

### Cloud Provider

Amazon Web Services (AWS)

### Policy

```shell
policies:
  - name: copy-instance-tags-on-securitygroup-action
    resource: ec2
    actions:
      actions:
    - type: copy-related-tag
      resource: security-group
      key: "GroupId"
      tags: "*"
```

**Comment by thisisshi** [comment]
the `copy-related-tag` action doesn't operate that way. The action copies the tags from the resource specified in the action onto the resource.
