### ISSUE TITLE
Lambdas aren't deprovisioned after policies are removed

### ISSUE THREAD

**Issue by ericofusco** [cloud-custodian/cloud-custodian#7856]
### Describe the bug

I had policies running in `cloudtrail` mode with `c7n-org` script and these policies were removed completely.

But cloud custodian only handles provisioning the lambdas, if a policy is deleted, the lambda and cloudwatch/eventbrdige rule are kept in the AWS account with no changes in the original policy configuration, which results in the actions being triggered even though they're no longer configured.

I haven't tested policy name updates, but since the lambda references the policy name. I guess if a policy is renamed, the lambda with the old policy name would be kept in the account unmanaged with a new lambda provisioned.

### What did you expect to happen?

Expect deleted policies in cloudtrail mode to be actually removed from the environment.

### Cloud Provider

Amazon Web Services (AWS)

### Policy

```shell
- name: s3-bucket-creation
    resource: s3
    comment: s3 bucket creating example
    description: s3 bucket created
    mode:
      type: cloudtrail
      role: arn:aws:iam::{account_id}:role/cloud-custodian
      events:
        - event: CreateBucket
          source: s3.amazonaws.com
          ids: requestParameters.bucketName
```

**Comment by thisisshi** [comment]
Hi @ericofusco this is expected, check out the mugc tool in tools/ops: https://github.com/cloud-custodian/cloud-custodian/tree/master/tools/ops
