### ISSUE TITLE
Add more flexible 'set-permissions' action to aws.ami to manage AMI sharing policies

### ISSUE THREAD

**Issue by mcripps9** [cloud-custodian/cloud-custodian#7972]
### Describe the feature

AWS now supports AMI sharing to organizations and OUs.  The 'remove-launch-permissions' action does not support this, nor is there an action to add specific launch permissions.  To rectify both, I propose deprecating 'remove-launch-permissions' and replacing it with a more flexible 'set-permissions' action similar to other services that supports adding and removing accounts, organizations, OUs, and removing permissions matched by the 'ami.cross-account' filter.

A PR is forthcoming.

**Comment by ajkerrigan** [comment]
Thanks @mcripps9 - this is somewhat related to #7031 (that's covering the detection side) :+1:

**Comment by mcripps9** [comment]
Yes, and the PR will cover this, #7031, and #7232

**Comment by thisisshi** [comment]
closed via: https://github.com/cloud-custodian/cloud-custodian/pull/7974
