### ISSUE TITLE
Policies using AWS resource "security-group" logging wrong c7n version in CloudWatch logs.

### ISSUE THREAD

**Issue by wallabyies** [cloud-custodian/cloud-custodian#7976]
### Describe the bug

Reviewing CloudWatch logs, it appears that c7n policies using resource "security-group" log version 0.9.19  despite being deployed with 0.9.20.    I've noticed this with multiple policies using security-group resources.

Policies using other resources log the expected Custodian version, 0.9.20.

### What did you expect to happen?

Custodian version 0.9.20 to be shown in log records instead of 0.9.19

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
0.9.20
```

**Comment by cgoxo** [comment]
Can I work on this??
I don't know a lot about this. Can you help me with how to proceed?

**Comment by thisisshi** [comment]
Hi @wallabyies this should be resolved in the next release

**Comment by wallabyies** [comment]
I confirmed this is resolved in later releases, thanks!
