### ISSUE TITLE
Add AWS MSK (Kafka) V2 Serverless Support

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#7997]
### Describe the feature

Currently the aws.kafka resource can only see the older provisioned Kafka Clusters and does not see the newer Serverless Kafka Clusters as this requires implementing the list_clusters_v2 API to be called (This pulls back serverless AND provisioned Kafkas). Currently custodian is only calling the list_clusters API. So we are not able to check the tagging or compliance of the newer serverless Kafkas.

### Extra information or context

No workarounds for this in Custodian.

**Comment by thisisshi** [comment]
started working on this but then quickly realized that this will actually break extant policies as many of the underlying attributes have moved in the new `list_clusters_v2` call. I have a branch where i've started the work so I'll push that up but I think we actually may need a v2 resource here a la `kafka-v2`. Alternatively it kind of seems like the main thing that's changed is that most of the resource data has moved under the `Provisioned` top level key. So if we augment and move what's inside `Provisioned` to the top level that may preserve backwards compat

**Comment by Monalisha1991** [comment]
kafka auto tagging policy please
