### ISSUE TITLE
Mailer - question about send mail to gcp target

### ISSUE THREAD

**Issue by kentnsw** [cloud-custodian/cloud-custodian#8010]
### Describe the bug

Below code https://github.com/cloud-custodian/cloud-custodian/blob/ab4626825526abfe48b0f9fd3fe792b66168a6b8/tools/c7n_mailer/c7n_mailer/email_delivery.py#L46
in
```python
    def get_valid_emails_from_list(self, targets):
        emails = []
        for target in targets:
            if target in ('resource-owner', 'event-owner'):
                continue
            for email in target.split(':'):
                if is_email(target):
                    emails.append(target)
                # gcp doesn't support the '@' character in their label values so we
                # allow users to specify an email_base_url to append to the end of their
                # owner contact tags
                if not is_email(target) and self.config.get('email_base_url'):
                    target = "%s@%s" % (target, self.config['email_base_url'])
                    if is_email(target):
                        emails.append(target)
        return emails
```

It looks like the `email` should be used here rather than `target`. If target = 'abc:def', will line 46 be run twice, add `abc:def@xxx.xxx` to the emails?

### What did you expect to happen?

add emails `abc@xxx.xxx` and `def@xxx.xxx`

### Cloud Provider

Google Cloud (GCP)

**Comment by thisisshi** [comment]
@kentnsw thanks for the bug report, i've opened a pr to address it here: #8074

**Comment by thisisshi** [comment]
actually looking at this again, the `:` character actually isn't a valid character, only `-` `_` and a-z 0-9. The bug here is valid but it never would've worked in the first place

**Comment by kentnsw** [comment]
Understand, in the gcp context.

In my customised version, the : has been replaced with , and ; to support multiple emails. It is more intuitive and useful to my requirements.
