### ISSUE TITLE
Python 3.11 dependency issues

### ISSUE THREAD

**Issue by ajkerrigan** [cloud-custodian/cloud-custodian#8057]
### Describe the bug

There are a couple issues with upstream dependencies that break installs under Python 3.11:

- [x] `c7n-gcp` had a known issue related to ratelimiter (see also https://github.com/RazerM/ratelimiter/issues/10)
- [x] `c7n-policystream` is currently pinned to 1.9.x which prevents it from making use of 3.11-compatible wheels that became available starting with 1.10.1

Feels like a dependency bump should cover us for policystream. The c7n-gcp/ratelimiter issue has more history than I was aware of, and the best next step isn't clear to me.

### What did you expect to happen?

Pip installs of releases and poetry installs at dev time should work under Python 3.11.

### Cloud Provider

Amazon Web Services (AWS)

**Comment by kapilt** [comment]
I think we need to manually excise rate limiter in favor of a more current package. which one I'm not sure, there's a lot of them out there.

**Comment by ajkerrigan** [comment]
As far as I can tell we're good here now - with the 0.9.21 release I'm seeing clean installs from pip and poetry on 3.11. I've got no real allegiance to a specific ratelimiter package, but [pyrate](https://pyratelimiter.readthedocs.io/) seemed to be actively maintained with solid docs and minimal code changes on our side.
