### ISSUE TITLE
Add support for tagging of aws.user-pool resources

### ISSUE THREAD

**Issue by stepkirk** [cloud-custodian/cloud-custodian#8102]
### Describe the feature

This is related to issue #7660 

It looks like tagging support was recently added to the Cognito identity pool (aws.identity-pool) resources.
Would it be possible to do the same for the Cognito user pool (aws.user-pool) resources?

I think that means adding support for the marked-for-op filter as well as the following actions:
mark-for-op
tag
remove-tag

This would get us one step closer to tagging nirvana.

**Comment by stepkirk** [comment]
Hey @thisisshi , do you know if #7660 was supposed to fix this issue (or maybe it did and I am missing something obvious)?

**Comment by thisisshi** [comment]
#7660 started retrieving tags, but you're right the actions are still missing i'll open a pr to address that
