### ISSUE TITLE
 Request for api-gateway-stages-x-ray-tracing-enabled Feature

### ISSUE THREAD

**Issue by pareshcc** [cloud-custodian/cloud-custodian#8121]
### Describe the feature

 I can see a set-xray-tracing action for Lambda functions, but not API Gateway stages. Please enable this options as well.

**Comment by ajkerrigan** [comment]
These references should be useful for anyone interested in a contribution:

- #7722
- [AWS docs on enabling tracing](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-enabling-xray.html)
- [update_stage() docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/apigateway.html#APIGateway.Client.update_stage)

**Comment by Vishal-Chdhry** [comment]
Hi @ajkerrigan! may I give this a try?

**Comment by ajkerrigan** [comment]
Sure @Vishal-Chdhry go for it! If you have questions along the way, feel free to raise them here or in the #development channel in the Custodian Slack. (Links for that and other resources at https://cloudcustodian.io/community/)
