### ISSUE TITLE
dns - Add dns redirect for slack.cloudcustodian.io

### ISSUE THREAD

**Issue by castrojo** [cloud-custodian/cloud-custodian#8205]
Please add a redirect so that slack.cloudcustodian.io points to:  https://communityinviter.com/apps/cloud-custodian/c7n-chat

This way we can use that shorthand everywhere instead of that scary url. If you're in there anyway please consider k8s. and c7n-left. as well, just point them to their respective set of docs.

**Comment by kapilt** [comment]
done as s3 bucket website redirection, as we need to add path to the domain.

http://slack.cloudcustodian.io now redirects, note there is no https redirect since s3 doesn't support website serving with ssl.
