### ISSUE TITLE
ValueError: Invalid endpoint: https://ec2..amazonaws.com

### ISSUE THREAD

**Issue by rutabanavalikar** [cloud-custodian/cloud-custodian#8220]
### Describe the bug

When I run these commands and use policy listed below (defaulttest.yml), I get an error -

`pip install c7n 

custodian validate ./policies/defaulttest.yml

custodian run -s out --region=all ./policies/defaulttest.yml --cache-period=0`

**defaulttest.yml file as below;**

`policies:
  - name: s3-terminate-non-standard-region-policy-2
    resource: S3
    mode:
      type: cloudtrail
      role: "arn:aws:iam:xxxxxxxxxx:role/CloudCustodian"   
      events:
        - source: s3.amazonaws.com
          event: CreateBucket
          ids: requestParameters.bucketName
          timeout: 200
    description: |
           Detect when a new S3 Bucket is created in a non-standard
           region and delete it
    filters:
      - type: event
        key: "detail.awsRegion" #from cloudwatch INFO
        op: not-in
        value: 
                - eu-west-1
                - eu-west-2
    actions:
      - type: delete
        remove-contents: true`

I get the following error; ValueError: Invalid endpoint: https://ec2..amazonaws.com

### What did you expect to happen?

We expect the policy to be deployed to all relevant regions for the S3 service.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
c7n-0.9.22
```

### Policy

```shell
**defaulttest.yml file as below;**

`policies:
  - name: s3-terminate-non-standard-region-policy-2
    resource: S3
    mode:
      type: cloudtrail
      role: "arn:aws:iam:xxxxxxxxxx:role/CloudCustodian"   
      events:
        - source: s3.amazonaws.com
          event: CreateBucket
          ids: requestParameters.bucketName
          timeout: 200
    description: |
           Detect when a new S3 Bucket is created in a non-standard
           region and delete it
    filters:
      - type: event
        key: "detail.awsRegion" #from cloudwatch INFO
        op: not-in
        value: 
                - eu-west-1
                - eu-west-2
    actions:
      - type: delete
        remove-contents: true`
```

### Relevant log/traceback output

```shell
Traceback (most recent call last):
  File "/home/circleci/.local/bin/custodian", line 8, in <module>
    sys.exit(main())
  File "/home/circleci/.local/lib/python3.10/site-packages/c7n/cli.py", line 363, in main
    command(config)
  File "/home/circleci/.local/lib/python3.10/site-packages/c7n/commands.py", line 99, in _load_policies
    policies += provider.initialize_policies(
  File "/home/circleci/.local/lib/python3.10/site-packages/c7n/resources/aws.py", line 670, in initialize_policies
    get_profile_session(options).client('ec2').describe_regions(
  File "/home/circleci/.local/lib/python3.10/site-packages/boto3/session.py", line 299, in client
    return self._session.create_client(
  File "/home/circleci/.local/lib/python3.10/site-packages/botocore/session.py", line 976, in create_client
    client = client_creator.create_client(
  File "/home/circleci/.local/lib/python3.10/site-packages/botocore/client.py", line 155, in create_client
    client_args = self._get_client_args(
  File "/home/circleci/.local/lib/python3.10/site-packages/botocore/client.py", line 485, in _get_client_args
    return args_creator.get_client_args(
  File "/home/circleci/.local/lib/python3.10/site-packages/botocore/args.py", line 129, in get_client_args
    endpoint = endpoint_creator.create_endpoint(
  File "/home/circleci/.local/lib/python3.10/site-packages/botocore/endpoint.py", line 402, in create_endpoint
    raise ValueError("Invalid endpoint: %s" % endpoint_url)
ValueError: Invalid endpoint: https://ec2..amazonaws.com
```

**Comment by kapilt** [comment]
it looks like you have an invalid AWS_REGION / AWS_DEFAULT_REGION environment variable set.

**Comment by rutabanavalikar** [comment]
Thank you very much. That helped. I added below to the config file and it works.

export AWS_REGION=eu-west-2 
export AWS_DEFAULT_REGION=eu-west-2

**Comment by abinshihab** [comment]
Thanks it work for me also :)
