### ISSUE TITLE
Plugin-able architecture for resources, filters and actions

### ISSUE THREAD

**Issue by kentnsw** [cloud-custodian/cloud-custodian#8296]
### Describe the feature

When working with open-source projects, it can be challenging to customize them without diverging too far from the original project or losing time-sensitive functionality. It can be a burden if the customizations are not accepted. So that will prevent users to change anything, especially new features.

For example, last year I customized c7n-mailer to include Jira integration, but this change is not merged back into the original repository. When the huge GCP mailer change released, it was difficult to merge because the design ideas were different. If c7n-mailer had a plugin-able architecture, I could have added my Jira integration as a plugin, making it easier to maintain and integrate with future updates.

**Comment by kapilt** [comment]
we tried this previously, it had a number of issues both on technical and community, that led to the decision to remove this ability.

- the plugin mechanism was slow (setuptools entry points required effectively full scans on every dir on python path at startup)
- it can issues on refactorings as their isn't much of a defined public api

the community issues were more significant

 - it lead to a lot of poor user community support interactions, because of the use of plugins, effectively obviated the discussion around an issue causing wasted support time because it was behavior from a private plugin.
 
 - it lead to a plethora of organizations continually accruing changes that they weren't contributing back, which defeats the purpose of having the project as open source. we want to encourage users to participate in the community and contribute back. the project's move to cncf was to better facilitate that as many organizations are also using and contributing to other projects within the cncf ecosystem.

wrt to the c7n-mailer jira support, I don't see any issues or pull requests filed against this repo. Generally the right way to engage about a new feature is to file an issue and or come to the community office hours meeting or engage in the developer or general channel on http://slack.cloudcustodian.io  The community meeting is also used to raise pull requests for review prioritization. https://cloudcustodian.io/community/ for calendar, meeting minutes, recordings etc.

incidentally @kentnsw if your interested in being a maintainer, I tried connecting on LinkedIn, since I didn't find you on the community slack.

**Comment by kentnsw** [comment]
Thanks for such a informative reply. hmmm, now I see there are some trade offs to make. I will see if I could have a better idea. At the moment, 3 things make me hesitate to make changes:
- the code formatting 
- the testing framework 
- the risk of not being merged (in time), note: a few weeks would be too long for a task in a sprint.

**Comment by kapilt** [comment]
could you clarify on the aspects wrt to hesitation, on code formatting and testing? we've generally tried to make testing relatively easy (flight record with automatic anonymization of accounts), and we're not currently using a code formatter (see #8281  for a proposal on moving to one). on the merge timeline, that's really comes out to a few things, first, we release monthly. we've got about a dozen maintainers but volunteer hours are at individual discretion, we use the community to help folks suggest things that they would like prioritized in terms of review. generally speaking trying to align any oss contribution to an internal org structure's schedule is likely to be a pain point without additional consideration of what that should mean. some of other maintainers might be able to speak to this in more detail, if you'd like to discuss more.

wrt to responsibilities, its fairly informal, review pull requests, attend community meetings as time permits, etc. there's mailing list for the group at cncf, but we generally just hang out in slack. wrt to more formal specification of extant governance structure.  https://github.com/cloud-custodian/cloud-custodian/issues/7149#issuecomment-1134951042

**Comment by kentnsw** [comment]
@kapilt Thank you for your reply, and I apologize for my 2-week absence. There have been some unexpected developments in my new role that have kept me fully occupied. That's also the reason why I was curious about the responsibilities of being a maintainer. I enticipated I could be busy at the beginning of the new role. I feel honored to have been offered the opportunity to become a maintainer of such a famous and exceptional project.

- Code formatting: It's not a big deal. It's more like a mosquito that buzzes around when I am trying to relax. Formatting is supposed to be a quick, automatic process, but often I've found myself being prompted by Github that the PR doesn't pass the formatting check due to some errors like a space at the end of a note. Another issue is that when I read or change the code in an effort to learn and understand c7n, I feel a strong urge to reformat code that isn't consistent. However, I can't do this because it would make reviewing the changes more difficult by mixing feature changes with code reformatting.

- Testing: From a c7n point of view, the current testing framework is probably the best option, as it needs to be generic enough to cover all resource types and scenarios. However, I have become so accustomed to the testing framework that I created for my c7n policy testing. Please refer to the example below. The Ec2PolicyTest is a helper that uses moto to mock AWS and load the target policy file to execute. Some people might question the need to test such a simple policy, given that c7n already has many test cases in place to ensure the filters and actions are functioning as intended. This is true, but my reality is that the use cases I deal with are much more complex than this example, and sometimes the process involves chaining several policies together to meet business requirements. Therefore, I need to test the combined logic.
- (continue) I know the example above may seem off-topic, but once I became accustomed to this framework, there was no going back. With this approach, I no longer need to create real resources in AWS, and I don't have to re-create those resources when I need to change the logic several months later. In a sense, I can travel through time and simulate a wide range of scenarios to cover edge cases.

```yaml
policies:
  - name: gc_ebs_snapshot_delete
    resource: ebs-snapshot
    description: older than 1 year, un-preserved and unused should be deleted
    filters:
      - "tag:Preserve": absent
      - type: age
        op: gt
        days: 365 # need to update test case as well when it changes
      - type: unused
        value: true
    actions:
      - type: delete
```

```python
def test_gcebssnapshot_basecase(aws_credentials):
  pt = Ec2PolicyTest()
  volIds = pt.create_volumes(pt.requiredTags)
  sid = pt.client.create_snapshot(VolumeId=volIds[0])["SnapshotId"]

  with freeze_time(nDaysLater(365)):
      pt.run_policy(policy)
      assert sid not in [r["SnapshotId"] for r in pt.client.describe_snapshots()["Snapshots"]]
```

Additionally, I would like to take this opportunity to bring up a new scenario that I recently discovered. Some employers may not allow their staff to fork any open-source projects, which completely rules out the possibility of customizing c7n. However, they may still have customization requirements, such as sending notifications to Jira. My solution to this issue is to develop a decorator that allows for Jira integration, as shown below.
The downside is that it's a bit unconventional, but the good news is that there is no need to fork the project and maintain the fork. If and when the Jira Integration PR gets accepted, the decorator can simply be removed. Without this option, the employer may have to develop a standalone Jira Integration code that may never be incorporated into c7n.

```python
# my_cli.py
# use my_cli to execute the c7n-mailer.

import wrapt
from jira_integration import handle_jira
from c7n_mailer.cli import main as c7n_mailer_main()

@wrapt.decorator
def wrap_handle_targets(wrapped, inst, args, kwargs):
    handle_jira(wrapped, inst, args, kwargs)
    return wrapped(*args, **kwargs)

MessageTargetMixin.handle_targets = wrap_handle_targets(MessageTargetMixin.handle_targets)

if __name__ == "__main__":
    c7n_mailer_main()
```

**Comment by kapilt** [comment]
no worries, and good luck on the new gig.

Code formatting - it’s a review for contributors and reviewers. First step on being a maintainer, engaging on other prs your care about re https://github.com/cloud-custodian/cloud-custodian/pull/8378 would be glad for additional reviews, current strategy on automated formatting per current community standards is https://github.com/cloud-custodian/cloud-custodian/issues/8281 there are a number of prs extant.. that could use a review.

Testing - not sure I understand that, recording is pretty simple, mocking is generally testing happy path, that said Moto is definitely useful, happy to discuss in community meeting or separate call If that’s not convenient on tz. Also fwiw, we have Moto testing also in org-accounts pr for test dependencies, hint re reviews ;-) https://github.com/cloud-custodian/cloud-custodian/pull/8194

For functional tests, that we can run out of GitHub actions for release and also fit in extant flight record setup, pytest-terraform provides a simple and flexible pytest fixture that is currently the basis functional tests, goal is to add more providers and more scenarios, Moto tests are fine but never validate actual behavior in for that context. https://github.com/cloud-custodian/pytest-terraform

**Comment by kentnsw** [comment]
Thanks for your reply.

I will try to review some of those PRs.

True, I use record and replay approach to test my GCP policies. I'm not very familiar with the testing design of c7n yet. I will keep digging.
