### ISSUE TITLE
Security Group Grouping Issue

### ISSUE THREAD

**Issue by dykemasarah** [cloud-custodian/cloud-custodian#834]
Similar to this issue: https://github.com/capitalone/cloud-custodian/issues/807

When looking to remove permissions 
*If the IpProtocol == -1 (or All Traffic) CC is doing grouping based on All Traffic*

When looking for all 0.0.0.0/0, it will match ANY statement when it is "ALL TRAFFIC."  The issue before seem to resolve all other issues outside of "All Traffic".

resource: security-group
filters:
      - type: ingress
        Cidr:
          value: 0.0.0.0/0
          op: eq
          value_type: cidr

For example:
DELETES --> ALL TRAFFIC | ALL | ALL | 10.1.23.2/32
DELETES --> ALL TRAFFIC | ALL | ALL | 0.0.0.0/0
KEEPS --> HTTP| TCP | 22 | 10.1.23.2/32

For example:
"MatchedIpPermissions": [
{
"IpProtocol": "-1",
"PrefixListIds": [],
"IpRanges": [
{
"CidrIp": "0.0.0.0/0"
},
{
"CidrIp": "10.1.23.2/32"
}
],
"UserIdGroupPairs": [],
"Ipv6Ranges": []
},
{
"PrefixListIds": [],
"FromPort": 22,
"IpRanges": [
{
"CidrIp": "0.0.0.0/0"
}
],
"ToPort": 22,
"IpProtocol": "tcp",
"UserIdGroupPairs": [],
"Ipv6Ranges": []
}
],

**Comment by kapilt** [comment]
sorry i missed your last comment on the previous issue, i'll see if i can get to this later this week.

**Comment by ajkerrigan** [comment]
This was fixed at some point, closing as part of housekeeping.
