### ISSUE TITLE
Support Aurora RDS for Offhours Policy

### ISSUE THREAD

**Issue by robosung** [cloud-custodian/cloud-custodian#8391]
### Describe the feature

It appears that RDS Offhours policy doesn't cover aurora (`aurora-postgresql` and `aurora-mysql`) RDS engines.   Curious if it's just an omission as it's not included in the list of engines here.

https://github.com/cloud-custodian/cloud-custodian/blob/main/c7n/resources/rds.py#L452

**Comment by kapilt** [comment]
aurora is an rds-cluster which uses different apis to stop and has a different resource type in cloud custodian then an rds instance (aka single server). also note that aurora support for stopping has a list of caveats https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-cluster-stop-start.html#aurora-cluster-stop-limitations
