### ISSUE TITLE
releng - remove distutils version usage from the code base

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#8394]
distutils has been removed from the python standard lib for python 3.12, simplest option for us is to simply vendor the package, https://github.com/python/cpython/blob/a7a450f84a087421603170c2dad226bb881d4d9a/Lib/distutils/version.py

alternatively look at separate packages (packaging, semver), most seem to have a longer transitive dep chain then ideal.

**Comment by ajkerrigan** [comment]
Missed this issue until reviewing 8392 :see_no_evil: . I was leaning toward packaging because:

1. It's explicitly called out in the deprecation warnings, so seems like a safe default
2. It's already in our dep tree (courtesy of docker, pytest & sphinx) and is available for all the Python versions we support  

Agreed on semver introducing too many new deps. Vendoring distutils is an interesting alternative too though.

**Comment by ajkerrigan** [comment]
Huh neat, [pipdeptree](https://pypi.org/project/pipdeptree/) added mermaid output. I hit some issues using the packages+reverse+mermaid options at the same time (will file an issue for guidance there), but after some local fiddling we can see `packaging`'s reverse dep tree in our codebase:

```mermaid
flowchart TD
    classDef missing stroke-dasharray: 5
    c7n-sphinxext["c7n-sphinxext\n1.1.23"]
    docker["docker\n6.0.1"]
    myst-parser["myst-parser\n1.0.0"]
    packaging["packaging\n23.0"]
    pytest-cov["pytest-cov\n3.0.0"]
    pytest-forked["pytest-forked\n1.4.0"]
    pytest-recording["pytest-recording\n0.12.2"]
    pytest-socket["pytest-socket\n0.6.0"]
    pytest-sugar["pytest-sugar\n0.9.6"]
    pytest-terraform["pytest-terraform\n0.6.4"]
    pytest-testmon["pytest-testmon\n1.4.5"]
    pytest-xdist["pytest-xdist\n3.2.0"]
    pytest["pytest\n7.2.2"]
    recommonmark["recommonmark\n0.7.1"]
    sphinx-rtd-theme["sphinx-rtd-theme\n1.2.0"]
    sphinx["sphinx\n5.3.0"]
    myst-parser -- "any" --> c7n-sphinxext
    packaging -- "any" --> docker
    packaging -- "any" --> pytest
    packaging -- "any" --> pytest-sugar
    packaging -- "any" --> sphinx
    pytest -- "any" --> pytest-cov
    pytest -- "any" --> pytest-forked
    pytest -- "any" --> pytest-recording
    pytest -- "any" --> pytest-socket
    pytest -- "any" --> pytest-sugar
    pytest -- "any" --> pytest-terraform
    pytest -- "any" --> pytest-testmon
    pytest -- "any" --> pytest-xdist
    pytest-xdist -- "any" --> pytest-terraform
    recommonmark -- "any" --> c7n-sphinxext
    sphinx -- "any" --> c7n-sphinxext
    sphinx -- "any" --> myst-parser
    sphinx -- "any" --> recommonmark
    sphinx -- "any" --> sphinx-rtd-theme
    sphinx-rtd-theme -- "any" --> c7n-sphinxext
```

**Comment by kapilt** [comment]
packaging isn't in our dependency tree for runtime or regular installs (pip install c7n), only for developer installs. for runtime inclusive of serverless environments, it represents a net new dependency, that we would need to distribute/upload as well.
