### ISSUE TITLE
AWS route53 ARC cluster tagging exception

### ISSUE THREAD

**Issue by jerryhxu** [cloud-custodian/cloud-custodian#8397]
### Describe the bug

There is an issue with Python boto3 library (https://github.com/boto/botocore/issues/2886). It will impact Route53 ARC cluster tagging since custodian uses boto3 api call. I write this issue to keep track of boto3 fix. No action needs to be taken on custodian yet. Once the fix for boto3 is released, I can alert the team to incorporate that release into custodian.

### Cloud Provider

Amazon Web Services (AWS)

**Comment by kapilt** [comment]
this isn't a custodian issue afaics, but an underlying service issue, we already update the boto sdk every month, so there is nothing actionable on this issue. we don't generally use this project issues to document underlying cloud provider service issues.
