### ISSUE TITLE
jinja2 dependency error with mailer 0.6.23

### ISSUE THREAD

**Issue by wallabyies** [cloud-custodian/cloud-custodian#8432]
### Describe the bug

After installing mailer 0.6.23 with pip, executing mailer returns this error:

`ModuleNotFoundError: No module named 'jinja2'`

The workaround is to install jinja2 before executing mailer, but I thought this dependency would have been take care of during installation of mailer automatically.

### What did you expect to happen?

Mailer to execute without errors.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
c7n==0.9.24
```

**Comment by kapilt** [comment]
I can confirm this was addressed as part of the #8429 and will be in the next release.
