### ISSUE TITLE
Dependency pinning with 0.9.25 still has an issue

### ISSUE THREAD

**Issue by howbazaar** [cloud-custodian/cloud-custodian#8483]
### Describe the bug

Created a fresh project directory, and initialised poetry:

Ran `poetry add c7n=^0.9.25`

It added:

```
  • Installing six (1.16.0)
  • Installing jmespath (1.0.1)
  • Installing python-dateutil (2.8.2)
  • Installing urllib3 (1.26.15)
  • Installing botocore (1.29.111)
  • Installing attrs (22.2.0)
  • Installing pyrsistent (0.19.3)
  • Installing s3transfer (0.6.0)
  • Installing zipp (3.15.0)
  • Installing argcomplete (3.0.5)
  • Installing boto3 (1.26.111)
  • Installing docutils (0.18.1)
  • Installing importlib-metadata (5.2.0)
  • Installing jsonschema (4.17.3)
  • Installing pyyaml (6.0)
  • Installing tabulate (0.9.0)
  • Installing c7n (0.9.25)
```

Exported to a requirements.txt, and attempted to create a new venv based on that file:

```
poetry export  --without-hashes > requirements.txt
poetry run python -m venv test-env 
. test-env/bin/activate
pip install -r requirements.txt 
```

This still errors with:

```
ERROR: Cannot install -r requirements.txt (line 5) and boto3==1.26.111 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested boto3==1.26.111
    c7n 0.9.25 depends on boto3==1.26.109; python_version >= "3.7" and python_version < "4.0"
```

### What did you expect to happen?

I expected to be able to create a new virtual environment and install the packages exported by poetry.

### Cloud Provider

Amazon Web Services (AWS)

**Comment by howbazaar** [comment]
Looks like when poetry installs c7n, it isn't using the exact version that should be frozen for c7n.

**Comment by kapilt** [comment]
the upstream issue was noted as https://github.com/python-poetry/poetry/issues/7723

effectively we freeze metadata, but poetry uploads using the wrong metadata, instead of that which is in the file.

that gets compounded on install since pip uses the metadata in the file, poetry uses the pypi json api, which has the incorrect metadata uploaded (non frozen). moving to twine fro publishing will resolve.
