### ISSUE TITLE
Cache lookup doesn't return correct results with kms key alias

### ISSUE THREAD

**Issue by PratMis** [cloud-custodian/cloud-custodian#8504]
### Describe the bug

When the below shown policies are run with cache set, custodian returns incorrect results

```
policies:
  - name: kms-key-all-resources
    resource: aws.kms-key
  - name: sns-encryption-with-key-alias
    resource: aws.sns
    filters:
      - or:
        - type: value
          key: KmsMasterKeyId
          op: eq
          value: null
        - not:
          - or:
            - type: kms-key
              key: c7n:AliasName
              value: alias/tes/pratyush
            - type: kms-key
              key: c7n:AliasName
              op: regex
              value: ^(alias\/tes\/pratyush\/.*)
```
Output:
```
(cloud-custodian) ➜  policies custodian run -c kms.yml -s output --region us-east-1 --cache-period=25
2023-04-18 23:08:59,944: custodian.policy:INFO policy:kms-key-all-resources resource:aws.kms-key region:us-east-1 count:49 time:4.32
2023-04-18 23:09:01,062: custodian.filters:WARNING Resource sns:arn:aws:sns:us-east-1:644160558196:test123 references non existant Key: alias/tes/pratyush
2023-04-18 23:09:01,064: custodian.filters:WARNING Resource sns:arn:aws:sns:us-east-1:644160558196:test123 references non existant Key: alias/tes/pratyush
2023-04-18 23:09:01,064: custodian.policy:INFO policy:sns-encryption-with-key-alias resource:aws.sns region:us-east-1 count:1 time:1.11
```
The key `alias/tes/pratyush` is present but looks like it's not found in the cache. I did some investigation and found that cache lookup returns correct results only when the looked up via key arn and key id.

### What did you expect to happen?

The policy should not filter any resources since the key is present and the topic is encrypted with the key

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

0.9.26

### Policy

Posted above

### Relevant log/traceback output

Posted above

### Extra information or context

To reproduce this error, I created a topic and applied encryption simultaneously using the key alias
```
response = client.create_topic(Name='test123', Attributes={'KmsMasterKeyId': 'alias/tes/pratyush'})
```

**Comment by PratMis** [comment]
Did you use the key alias to encrypt your SNS? AWS converts it to keyid when you do it from the console. A good way would be to do this:
```
response = client.create_topic(Name='test123', Attributes={'KmsMasterKeyId': 'alias/tes/pratyush'})
```

**Comment by ajkerrigan** [comment]
Sorry, filter or no I'm still getting the same results :-/. Do the results change if you run multiple times or change the `--cache-period` option? Or if you remove that `kmskey-tagging` policy from the set you're running?

Might be helpful to have verbose output from the policy run to figure out where the issue is. Regarding the cache, this policy set should end up with cached resources for keys, aliases and topics. [In here](https://github.com/cloud-custodian/cloud-custodian/blob/c734cd08656cd332f3bac277693f08548bf2bfe6/c7n/filters/kms.py#L56-L65) the `kms-key` filter tries to make sure that it can identify related resources by alias or ID, but maybe that logic or one of its assumptions is subtly broken?

**Comment by ajkerrigan** [comment]
Ahh thanks for some help reproducing this. Looks like this issue shows up when we have resources that specify an encryption key by alias, and no other resources that use the same key by ID.

While trying to reproduce this I was creating new topics and encrypting by alias, but had a pre-existing topic that happened to use the same key by ID.

**Comment by PratMis** [comment]
> Looks like this issue shows up when we have resources that specify an encryption key by alias, and no other resources that use the same key by ID.
Thanks, this would very likely be the case. We also saw this happening only in 1 or 2% of our accounts and it was hard to reproduce the issue locally.
