### ISSUE TITLE
Airflow - Add update and delete actions

### ISSUE THREAD

**Issue by ahlgreno** [cloud-custodian/cloud-custodian#8513]
### Describe the feature

I'd like to be able to use a custodian action to enforce the use of `PRIVATE_ONLY` for the `WebserverAccessMode`. Ideally, something like an `update-environment` action might be able to be used as a corrective action but if that's not feasible, a `delete-environment` action could nuke the resource. 

### Extra information or context

I will be working on this issue

**Comment by PratMis** [comment]
You could potentially look at adding an `update-environment` action that would include `WebserverAccessMode` settings.
