### ISSUE TITLE
The action set-wafv2 doesn't seem to accept my regex in the web-acl parameter

### ISSUE THREAD

**Issue by caiquedestro** [cloud-custodian/cloud-custodian#8537]
### Describe the bug

I wrote a regex with the prefix of a webacl that I have in multiple accounts with different random strings at the end. But the lambda function fails to find said webacl

### What did you expect to happen?

For the lambda function to find the webacl that I need

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Collecting c7n==0.9.18
Collecting c7n-mailer==0.6.17
Collecting c7n-org==0.6.17
```

### Policy

```shell
- name: cloud-sec-waf-attach-evaluation-alb
    resource: app-elb
    description: Atribui uma WebACL a ALBs criados sem um atribuído
    mode:
      type: periodic
      schedule: "rate(1 hour)"
    filters:
      - and:
        - "tag:CloudSecEvaluation": "true"
        - "tag:CloudSecWAFOPTag": not-null
        - type: marked-for-op
          op: set-wafv2
          tag: CloudSecWAFOPTag
        - type: wafv2-enabled
          state: false
    actions:
      - type: set-wafv2
        state: true
        web-acl: FMManagedWebACLV2-BasicRegional-.*
```

### Relevant log/traceback output

```shell
{
  "errorMessage": "invalid web acl: FMManagedWebACLV2-BasicRegional-.*",
  "errorType": "ValueError",
  "requestId": "ba1c6695-1ba2-496c-812e-78f8dd7b2032",
  "stackTrace": [
    "  File \"/var/task/custodian_policy.py\", line 4, in run\n    return handler.dispatch_event(event, context)\n",
    "  File \"/var/task/c7n/handler.py\", line 165, in dispatch_event\n    p.push(event, context)\n",
    "  File \"/var/task/c7n/policy.py\", line 1245, in push\n    return mode.run(event, lambda_ctx)\n",
    "  File \"/var/task/c7n/policy.py\", line 545, in run\n    return PullMode.run(self)\n",
    "  File \"/var/task/c7n/policy.py\", line 327, in run\n    results = a.process(resources)\n",
    "  File \"/var/task/c7n/resources/appelb.py\", line 461, in process\n    raise ValueError(\"invalid web acl: %s\" % (target_acl_id))\n"
  ]
}
```

### Extra information or context

When I try putting the full web acl name, it works. The documentation shows this action being used with a regex string https://cloudcustodian.io/docs/aws/resources/app-elb.html#aws-app-elb-actions-set-wafv2

**Comment by ajkerrigan** [comment]
Thank you for including version info in your issue report! Looks like you're on `0.9.18.0` but regex matches for this action were added in #7706 which was part of the `0.9.19.0` release. For what it's worth, the latest release available today is `0.9.26.0` which has a few more wafv2-related updates/fixes.
