### ISSUE TITLE
Increased Memory Usage in Version 0.9.26

### ISSUE THREAD

**Issue by KISStian** [cloud-custodian/cloud-custodian#8581]
### Describe the bug

We are currently in the process of upgrading from version 0.9.19 to 0.9.26.  While testing our daily policies that run in a CodeBuild environment we experienced process termination failures as a result of memory exhaustion.  We are testing in our test AWS Organization that only has 5 accounts, with few resources.  Approximately 70 policies were executed against 16 regions.

Several runs were performed using version 0.9.26 along with several runs of 0.9.19.  All 0.9.19 runs completed successfully, but none of them completed for 0.9.26.

The screen shots below show the resource utilization for runs from both releases.  

v0.9.19
<img width="1132" alt="Screenshot 2023-05-22 at 4 30 56 PM" src="https://github.com/cloud-custodian/cloud-custodian/assets/35926785/23c1c088-79e8-455c-9e84-6a637b99f742">

v0.9.26
<img width="1123" alt="Screenshot 2023-05-22 at 4 31 44 PM" src="https://github.com/cloud-custodian/cloud-custodian/assets/35926785/40dda266-5274-4e7a-ad54-303ef480bed6">

### What did you expect to happen?

The execution for v0.9.26 would complete successfully and with similar (or less) memory utilization that v0.9.19.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.26
Python:      3.11.2 (main, Feb 16 2023, 02:55:59) [Clang 14.0.0 (clang-1400.0.29.202)]
Platform:    posix.uname_result(sysname='Darwin', nodename='DI3NC47XP2D73', release='22.4.0', version='Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020', machine='arm64')
Using venv:  True
Docker: False
Installed: 

PyJWT==2.6.0
adal==1.2.7
applicationinsights==0.11.10
apscheduler==3.10.1
argcomplete==3.0.5
attrs==22.2.0
azure-common==1.1.28
azure-core==1.26.4
azure-cosmos==3.2.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.13.3
azure-graphrbac==0.61.1
azure-identity==1.12.0
azure-keyvault==4.2.0
azure-keyvault-certificates==4.7.0
azure-keyvault-keys==4.8.0
azure-keyvault-secrets==4.7.0
azure-mgmt-advisor==9.0.0
azure-mgmt-apimanagement==1.0.0
azure-mgmt-applicationinsights==1.0.0
azure-mgmt-authorization==1.0.0
azure-mgmt-batch==15.0.0
azure-mgmt-cdn==10.0.0
azure-mgmt-cognitiveservices==11.0.0
azure-mgmt-compute==19.0.0
azure-mgmt-containerinstance==7.0.0
azure-mgmt-containerregistry==8.0.0b1
azure-mgmt-containerservice==15.1.0
azure-mgmt-core==1.4.0
azure-mgmt-cosmosdb==6.4.0
azure-mgmt-costmanagement==1.0.0
azure-mgmt-databricks==1.0.0b1
azure-mgmt-datafactory==1.1.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-dns==8.0.0b1
azure-mgmt-eventgrid==8.0.0
azure-mgmt-eventhub==8.0.0
azure-mgmt-frontdoor==1.0.1
azure-mgmt-hdinsight==7.0.0
azure-mgmt-iothub==1.0.0
azure-mgmt-keyvault==8.0.0
azure-mgmt-logic==9.0.0
azure-mgmt-managementgroups==1.0.0b1
azure-mgmt-monitor==2.0.0
azure-mgmt-msi==1.0.0
azure-mgmt-network==17.1.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==1.0.0
azure-mgmt-rdbms==8.1.0
azure-mgmt-redis==12.0.0
azure-mgmt-resource==16.1.0
azure-mgmt-resourcegraph==7.0.0
azure-mgmt-search==8.0.0
azure-mgmt-security==1.0.0
azure-mgmt-servicefabric==1.0.0
azure-mgmt-sql==1.0.0
azure-mgmt-storage==17.1.0
azure-mgmt-subscription==1.0.0
azure-mgmt-trafficmanager==0.51.0
azure-mgmt-web==2.0.0
azure-nspkg==3.0.2
azure-storage-blob==12.15.0
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-file-share==12.11.1
azure-storage-queue==12.6.0
boto3==1.26.109
botocore==1.29.109
c7n==0.9.26
cachetools==5.3.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
cryptography==40.0.1
distlib==0.3.6
docutils==0.18.1
google-api-core==2.11.0
google-api-python-client==2.84.0
google-auth==2.17.2
google-auth-httplib2==0.1.0
google-cloud-appengine-logging==1.3.0
google-cloud-audit-log==0.2.5
google-cloud-core==2.3.2
google-cloud-logging==3.5.0
google-cloud-monitoring==2.14.2
google-cloud-storage==2.8.0
google-crc32c==1.5.0
google-resumable-media==2.4.1
googleapis-common-protos==1.59.0
grpc-google-iam-v1==0.12.6
grpcio==1.53.0
grpcio-status==1.53.0
httplib2==0.22.0
idna==3.4
importlib-metadata==5.2.0
isodate==0.6.1
jmespath==1.0.1
jsonschema==4.17.3
msal==1.21.0
msal-extensions==1.0.0
msrest==0.7.1
msrestazure==0.6.4
netaddr==0.7.20
oauthlib==3.2.2
portalocker==2.7.0
proto-plus==1.22.2
protobuf==4.22.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pyjwt==2.6.0
pyparsing==3.0.9
pyrate-limiter==2.10.0
pyrsistent==0.19.3
python-dateutil==2.8.2
pytz==2023.3
pytz-deprecation-shim==0.1.0.post0
pyyaml==6.0
requests==2.28.2
requests-oauthlib==1.3.1
retrying==1.3.4
rsa==4.9
s3transfer==0.6.0
setuptools==67.6.1
six==1.16.0
tabulate==0.9.0
typing-extensions==4.5.0
tzdata==2023.3
tzlocal==4.3
uritemplate==4.1.1
urllib3==1.26.15
zipp==3.15.0
```

### Relevant log/traceback output

```shell
2023-05-22 21:17:46,015: c7n_org:INFO Ran account:CSO AWS TestProject3 region:us-west-1 policy:account-audit-ebs-default-encryption-periodic matched:1 time:3.72
2023-05-22 21:17:48,122: c7n_org:INFO Ran account:CSO AWS TestProject3 region:us-east-1 policy:ebs-audit-unencrypted-volumes-periodic matched:3 time:7.43
2023-05-22 21:17:57,505: c7n_org:INFO Ran account:CSO AWS TestProject2 region:us-east-1 policy:s3-audit-cross-account-bucket-replication-periodic matched:1 time:43.87
2023-05-22 21:18:00,455: c7n_org:INFO Ran account:CSO AWS TestProject3 region:us-east-1 policy:iam-audit-internal-cross-account-roles-periodic matched:1 time:19.77
2023-05-22 21:18:01,143: c7n_org:INFO Ran account:CSO AWS TestProject3 region:us-east-1 policy:iam-audit-external-cross-account-roles-periodic matched:1 time:20.45
2023-05-22 21:19:34,063: c7n_org:WARNING Error running policy in CSO AWS TestProject2 @ us-east-1 exception: A process in the process pool was terminated abruptly while the future was running or pending.
2023-05-22 21:19:34,066: c7n_org:WARNING Error running policy in CSO AWS TestProject3 @ ap-south-1 exception: A process in the process pool was terminated abruptly while the future was running or pending.
2023-05-22 21:19:34,067: c7n_org:WARNING Error running policy in CSO AWS TestProject3 @ ap-northeast-2 exception: A process in the process pool was terminated abruptly while the future was running or pending.
2023-05-22 21:19:34,067: c7n_org:WARNING Error running policy in CSO AWS TestProject3 @ ap-northeast-1 exception: A process in the process pool was terminated abruptly while the future was running or pending.
2023-05-22 21:19:34,067: c7n_org:WARNING Error running policy in CSO AWS TestProject3 @ ap-southeast-1 exception: A process in the process pool was terminated abruptly while the future was running or pending.
2023-05-22 21:19:34,067: c7n_org:WARNING Error running policy in CSO AWS TestProject3 @ ap-southeast-2 exception: A process in the process pool was terminated abruptly while the future was running or pending.
2023-05-22 21:19:34,067: c7n_org:WARNING Error running policy in CSO AWS TestProject3 @ eu-central-1 exception: A process in the process pool was terminated abruptly while the future was running or pending.
2023-05-22 21:19:34,067: c7n_org:WARNING Error running policy in CSO AWS TestProject3 @ us-east-1 exception: A process in the process pool was terminated abruptly while the future was running or pending.
2023-05-22 21:19:34,067: c7n_org:WARNING Error running policy in CSO AWS TestProject3 @ us-west-1 exception: A process in the process pool was terminated abruptly while the future was running or pending.
2023-05-22 21:19:34,067: c7n_org:WARNING Error running policy in CSO AWS TestProject3 @ us-west-2 exception: A process in the process pool was terminated abruptly while the future was running or pending.
```

### Extra information or context

The CodeBuild environment was the same for each version: 15Gb RAM / 8 vCPU / amazonlinux2-x86_64-standard:3.0 image

**Comment by kapilt** [comment]
Thanks for the details, we have a release scheduled for this week (hopefully tomorrow), this might probably won't make it, but definitely a blocker for the next release.

Can you share policies or resource types targeted? Reproduction case, it's already helpful on min/max revisions but a test case/policy is useful, alternatively narrowing on revision where growth occurs in extant env, aka dial back to .25, etc. curious which release this first exhibits in.

**Comment by KISStian** [comment]
I did some additional testing in order to pinpoint the exact version where the issue surfaced.  I am certain that v0.9.25 is it.  Versions 0.9.19-0.9.24 all completed successfully and with substantially less memory utilization.  I'll go ahead and merge all the policies I was executing into a single file and upload it for your review.

If there is anything else that I can provide, just let me know.

**Comment by kapilt** [comment]
just starting to dive into this, I'm not seeing anything obvious looking at the diff ` git diff 0.9.24.0...0.9.25.0 c7n` its possible we have a dependent package regression, although its a bit early to say anything definitive. what would be helpful is figuring out how to get a reproducible test case, to bisect further. if you have a metrics picture of 0.9.24.0 that would also be useful. 

also noting, there is a significant difference on disk writes here (294mb to 7gb) which seems odd. we switched out to sqlite for our disk cache for 0.9.19.0 which seems to pre-date the issue noted here. I also tried 0.9.24.0 and trunk with pytest-memray but not seeing anything of note. in tests at least, the biggest memory consumption is either json loading responses, or boto loading service models. tests don't typically run with disk cache though.

as a work around, you can control the number of worker processes c7n-org is using, via environment variable, default is 4x cpu, C7N_ORG_PARALLEL  .. I'd try matching your matching your cpu count to start.

**Comment by kapilt** [comment]
one other note if you have psutil installed, we record per policy memory usage into metadata.json for its output folder.

**Comment by kapilt** [comment]
thanks for the dm on the policies. I used that to extract out the unique non value filters used which resulted in this set

```
- account.default-ebs-encryption
- ami.cross-account
- cloudtrail.status
- ebs-snapshot.cross-account
- ec2.finding
- ec2.marked-for-op
- ec2.security-group
- ec2.ssm
- ecr-image.finding
- iam-group.has-specific-managed-policy
- iam-policy.has-allow-all
- iam-role.cross-account
- iam-role.has-specific-managed-policy
- iam-user.access-key
- iam-user.credential
- iam-user.policy
- rds-cluster-snapshot.cross-account
- rds-snapshot.cross-account
- s3.bucket-encryption
- s3.cross-account
- security-group.ingress
```

in general when examining memory, we can look for either something that affects across the board on memory consumption, or something specific to a particular filter/action. on the general side, I was thinking in terms of reproducing we would create a 1000 of some resource (log groups are relatively easy), and then run a set of policies on them, to compare memory utilization across different versions. if its specific to a particular filter, thats where the psutil and memory values in metadata.json would be useful. alternatively this also gives a set of filters that we can use when looking for changes between 0.9.24 to 0.9.25

**Comment by KISStian** [comment]
I've been OOO for a few days, but will start working on executing some tests with psutil, as suggested above.  I'll soon let you know what I find out.

**Comment by kapilt** [comment]
interesting, single data points are a little harder to read in graph form versus just the numbers, but it would be good to get see the run time for the builds here as well (BuildDuration re cw). I suspect we'll see they're also significantly faster with versions >= 0.9.25.0 which was the primary change I see between the two versions. The speed increase with the additional concurrency means processing more peak data. the primary change for 0.9.25.0 that I see as relevant for that hypothesis is https://github.com/cloud-custodian/cloud-custodian/pull/8456

That would mean needing to dial down on concurrency for c7n-org, and perhaps we should change the default. The other part that was brought up in DM, was the significant increase in memory growth when using s3 outputs, which is something we can track down.

**Comment by KISStian** [comment]
So sorry for the delayed response.  Now that 3 releases have have been pushed out since we last tested this, we did another round of testing with 0.9.29.  Oddly enough, I am not seeing the memory issue that existed was previously observed.  In other words, memory utilization between 0.9.19 and 0.9.29 is relatively similar.  Latest round of testing results are as follows:

0.9.19 (total runtime = 5m 17s)
<img width="873" alt="Screenshot 2023-07-28 at 5 29 13 PM" src="https://github.com/cloud-custodian/cloud-custodian/assets/35926785/aa5a5ad7-3bd2-4519-a6f8-5d0657ea40b9">

0.9.29 (total runtime = 5m 10s)
<img width="926" alt="Screenshot 2023-07-28 at 5 15 48 PM" src="https://github.com/cloud-custodian/cloud-custodian/assets/35926785/7932bf63-93c7-4a27-ab37-ed15477a4c2a">

As a result of this, I think we can close this issue.  We are going to move forward with upgrading to the latest version and adjust concurrency where necessary. 

However, something that I think should be investigated is the fact that memory utilization is still substantially less when output is written locally as opposed to S3.  If this could be improved we would be able to bump up our concurrency and/or run in a more cost-effective build environment.

**Comment by kapilt** [comment]
okay, I'll open another issue on s3, but will note it will likely be a tradeoff on upload time vs memory vs file size, albeit I do think we should consider options on both file size on the default format and opportunities to improve non default output formats.

https://github.com/cloud-custodian/cloud-custodian/issues/8791
