### ISSUE TITLE
aws - notify action batch_size flexibility

### ISSUE THREAD

**Issue by PratMis** [cloud-custodian/cloud-custodian#8592]
### Describe the feature

Currently, notify action batch_size is set to 250. Some of our policies are hitting `SNS:MessagetooLongError` error even after lowering the batch size to 100 especially on ecs-task-definition/ecs-services policies.
Does is make sense to have this as a parameter in the policy within the notify action? That way we could stick to the batch_size of 250 in general and modify policies to have lower values as needed. The lower batch_size then would apply to a fewer set of policies instead of having a lower threshold across the board

**Comment by kapilt** [comment]
ideally we would dynamically size the batch, by serializing each resource, track size, and then manually assemble them the json from the set of serialized resources, we would need to assume a default compression ratio for gzip and measure the b64 encoding on top of that.

**Comment by PratMis** [comment]
Thanks @kapilt. Sounds good, will try to give it a shot
