### ISSUE TITLE
Authentication issues using Azure CLI

### ISSUE THREAD

**Issue by NikhilDasu** [cloud-custodian/cloud-custodian#8630]
### Discussed in https://github.com/orgs/cloud-custodian/discussions/8629

<div type='discussions-op-text'>

<sup>Originally posted by **NikhilDasu** June  5, 2023</sup>
Hi community members,

I'm facing issues with the cloud custodian authentication to Azure cloud. 

However, I have logged in using Az login and set the subscription.

(custodian) PS C:\Users\NikhilDasu\Desktop\custodian> az account show
{
  "environmentName": "AzureCloud",
  "id": "xxxxxxxxxxxxxxxxx",
  "isDefault": true,
  "managedByTenants": [],
  "name": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "state": "Enabled",
  "tenantId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "user": {
    "name": "xxxxxx@xxxxxxx",
    "type": "user"
  }
}

Requesting your kind assistance in this regards.

custodian.azure.session:ERROR Failed to authenticate.
Traceback (most recent call last):
  File "C:\Users\NikhilDasu\Desktop\custodian\Lib\site-packages\c7n_azure\session.py", line 175, in _initialize_session                                                                                                                   on
    self.credentials = AzureCredential(
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\NikhilDasu\Desktop\custodian\Lib\site-packages\c7n_azure\session.py", line 93, in __init__
    account_info = _run_command('az account show --output json')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _run_command() missing 1 required positional argument: 'timeout'

</div>

**Comment by jamelachahbar** [comment]
Hi community,

I have the same issue. My custodian pipelines stopped working. Any idea how to mitigate this issue?

**Comment by kapilt** [comment]
its been addressed in trunk, at the moment its going back to a previous release, or using trunk, till the next release.

**Comment by kapilt** [comment]
fix is also available in the cloudcustodian/c7n:dev image

**Comment by kapilt** [comment]
0.9.28.0 scheduled for next week.
