### ISSUE TITLE
Allow pattern matching for vars

### ISSUE THREAD

**Issue by wmstjean** [cloud-custodian/cloud-custodian#8646]
### Describe the feature

As an organization that relies on IaC for provisioning infrastructure we utilize patterns in naming conventions. It would be extremely beneficial to apply policies e.g. aws-app-elb-waf-disabled-prevent using regex or partial string matching.

**Comment by ajkerrigan** [comment]
Custodian policies do often use regex matches as part of policy evaluation. A few examples from the documentation which also include policy snippets for reference:

- The `value` filter's [`glob` and `regex` operators](https://cloudcustodian.io/docs/filters.html#pattern-matching-operators)
- The [`value_regex`](https://cloudcustodian.io/docs/filters.html#value-regex) parameter that extracts a piece of a resource property based on a pattern group
- Particularly relevant to the ALB & WAF case, the [`wafv2-enabled` filter](https://cloudcustodian.io/docs/aws/resources/app-elb.html#aws-app-elb-filters-wafv2-enabled) which can look for web ACLs matching a certain pattern

I'm not sure if these features will cover what you're looking for or if they're solving a different problem. But hopefully it will be useful for the discussion.

**Comment by wmstjean** [comment]
I'll try this and follow up

**Comment by jtroberts83** [comment]
This has to do with the set-waf action on app-elbs not allowing a pattern
for the ACL to set

**Comment by ajkerrigan** [comment]
> This has to do with the set-waf action on app-elbs not allowing a pattern for the ACL to set

Gotcha, edited the previous response to include a link to the `set-wafv2` action which does support regex patterns. So if using wafv2 is an option, that sounds like a useful direction :+1: . If not, then this issue becomes a feature request for the original/v1 `waf-enabled` and `set-waf` operations.

**Comment by wmstjean** [comment]
Based on my understanding and an analysis of our  typical naming conventions, I'll submit the following regex for web ACL's containing "v2" and "pbs"

^.*v2.*pbs.*$

**Comment by wmstjean** [comment]
we can close this here.
