### ISSUE TITLE
AWS EBS io2 Support

### ISSUE THREAD

**Issue by neta1o** [cloud-custodian/cloud-custodian#8701]
### Describe the bug

When I run the following policy below I get the following error indicating a lack of support for io2

Error: Error on policy:ebs-io1-io2 resource:ebs
'io2' is not one of ['io1', 'gp2', 'gp3', 'st1', 'sc1']

It seems the code that needs to be updated may be here https://github.com/cloud-custodian/cloud-custodian/blob/9d48bcc97c5967bb7a0bba968e5d0d6c97a4c86b/c7n/resources/ebs.py

### What did you expect to happen?

I expected the solution to support the latest volume generations like io2. io2 has been an EBS volume option since approx 7/2021. 

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.28
Python:      3.9.16 (main, Feb 23 2023, 00:00:00)
             [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)]
Platform:    posix.uname_result(sysname='Linux', nodename='ip-172-31-89-148.ec2.internal', release='6.1.34-58.102.amzn2023.x86_64', version='#1 SMP PREEMPT_DYNAMIC Tue Jun 27 21:38:12 UTC 2023', machine='x86_64')
Using venv:  True
Docker: False
Installed:

argcomplete==3.1.1
attrs==23.1.0
boto3==1.26.157
botocore==1.29.157
docutils==0.18.1
importlib-metadata==5.2.0
jmespath==1.0.1
jsonschema==4.17.3
pyrsistent==0.19.3
python-dateutil==2.8.2
pyyaml==6.0
s3transfer==0.6.1
six==1.16.0
tabulate==0.9.0
urllib3==1.26.16
zipp==3.15.0
```

### Policy

```shell
policies:
 - name: ebs-io1-io2
   resource: ebs
   filters:
    - VolumeType: io1
    - modifyable
   actions:
    - type: modify
      volume-type: io2
```

**Comment by kapilt** [comment]
I put up a pr, but the modify case makes me want to have a closer look at the logic here for io1 -> io2, as previously it was from a non reserved iops allocation, and we're using an iops-percent calculation that feels like we would want a no-op in this case wrt to retaining the same allocation of iops.
