### ISSUE TITLE
ipv6 support for value_type: cidr

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#871]

**Comment by ProgrammingAce** [comment]
This would be great, I'd like to detect open SSH ports over IPv6 with something like:

`policies:
  - name: IPv6-open-login
    resource: security-group
    filters:
      - type: ingress
        Ports: [22, 3389, 3306]
      - type: ingress
        Cidr:
          value: 
            - "::/0"
      - used`

**Comment by jsvazic** [comment]
+1

**Comment by RazaHasan84** [comment]
I am new to cloud custodian, and I am also facing same issue. I want to filter out  wide open ipv6 rule, but it is not working:

filters:
    - type: ingress
      Cidr:
        value:
         - "::/0"

However it work fine with ipv4

filters:
    - type: ingress
      Cidr:
        value:
         - "0.0.0.0/0"

**Comment by lamyanba** [comment]
+1 on the IPV6 support for CIDR.

**Comment by johnculkin** [comment]
+1

**Comment by kirklatslalom** [comment]
Per https://cloudcustodian.io/docs/usecases/securitygroupsdetectremediate.html

filters:
      - or:
            - type: ingress
              Cidr:
                value: "0.0.0.0/0"
            - type: ingress
              CidrV6:
                value: "::/0"

I think this could be closed.

**Comment by kapilt** [comment]
thanks
