### ISSUE TITLE
Allow specifying Parquet file format when using the `set-flow-log` action for VPCs

### ISSUE THREAD

**Issue by ajkerrigan** [cloud-custodian/cloud-custodian#8723]
### Describe the feature

When VPC flow logs added [Parquet support](https://aws.amazon.com/blogs/big-data/optimize-performance-and-reduce-costs-for-network-analytics-with-vpc-flow-logs-in-apache-parquet-format/), the `[create_flow_logs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2/client/create_flow_logs.html#create-flow-logs)` call picked up some new parameters under `DestinationOptions`:

- Log file format (plain text or parquet)
- Hive-compatible partitions
- Daily or hourly partitions

It would be nice to expose these options through the `set-flow-log` action.

**Comment by kapilt** [comment]
yeah this is definitely one where we should have adopted a passthrough, as the api options on it have grown significantly over the years.

**Comment by kapilt** [comment]
we originally did a fairly custom implementation for flow logs on filters and actions, its worth revisiting to be more of a pass through. for filters we can reuse list item for much of the logic, for actions we can use shape validate and pass through. the open question is whether to make a new filter/action or try and retro fit this into the existing.
