### ISSUE TITLE
push tags to Docker hub

### ISSUE THREAD

**Issue by jason-riddle** [cloud-custodian/cloud-custodian#876]
If you go to https://hub.docker.com/r/capitalone/cloud-custodian/tags/ you'll see the only tag there is latest. It would be nice if you had the following.

- latest
- git sha sum (f88e52e)
- possibly a tagged release as well

**Comment by kapilt** [comment]
+1 for tagged versions

**Comment by whit537** [comment]
Seems like this is a [drone config](https://github.com/capitalone/cloud-custodian/blob/65f856a7bb28a06429055b7993bd2123af9acf51/.drone.yml#L74-L83) change.

**Comment by whit537** [comment]
Pretty sure this is just extending `tags` like so:

`tags: [ latest, 0.8.23.1, 0.8.23.0, 0.8.22.0, etc. ]`

Or:

```yaml
tags:
  - latest
  - 0.8.23.1 
  - 0.8.23.0
  - 0.8.22.0
  - etc.
```

However, two issues:

1. We have currently have 31 [releases](https://github.com/capitalone/cloud-custodian/releases) and will only ever have more. This will get quite verbose. Are we really going to name every release in the drone file?
1. This should be automated during our release process. What's our release process?

Ref:

 - http://readme.drone.io/questions/how-to-build-publish-docker-images/
 - http://plugins.drone.io/drone-plugins/drone-docker/
 - https://github.com/drone-plugins/drone-docker/blob/master/plugin.go
 - https://docs.docker.com/engine/reference/commandline/image_tag/

**Comment by scotwk** [comment]
@whit537 

> We currently have 31 releases and will only ever have more. This will get quite verbose. Are we really going to name every release in the drone file?

There is a `$$TAG` variable.  (http://readme.drone.io/0.4/usage/variables/).   Perhaps we can use that to avoid naming the tags.

**Comment by kapilt** [comment]
yeah intent was $$TAG with an event filter, not explicit modification of drone.yml per tag.

**Comment by kapilt** [comment]
docker images with tags are now being published automatically to
https://hub.docker.com/r/cloudcustodian/c7n
