### ISSUE TITLE
AWS Resources add rename-tag action

### ISSUE THREAD

**Issue by khapp** [cloud-custodian/cloud-custodian#8788]
Top Priority: 
- [ ] ECS Tasks
- [ ] RDS Instances
- [ ] RDS Cluster
- [ ] Lambda

Second priority: 
- [ ] Cloudwatch Log Group
- [ ] S3
- [ ] EBS Volume
- [ ] ALB
- [ ] Cloudfront
- [ ] ACM
- [ ] WAF

**Comment by kapilt** [comment]
pr up which should address across all resource types using resource group tagging (aka as universal in custodian code).

**Comment by kapilt** [comment]
I will note ecs-task and s3 are two that are not supported by the pr.
