### ISSUE TITLE
GCP - switch from "stop" to "pause" for stop actions in gcp.instances

### ISSUE THREAD

**Issue by ksonney** [cloud-custodian/cloud-custodian#8859]
### Describe the feature

In GCP, the "stop" action requires disks to be detached and essentially terminates the instance. Switching to a "pause" action will not require the disks to be detached, at least not until deletion of the paused/stopped instance. 

### Extra information or context

This has been VERY frustrating for my users, since they have to find and re-attach disks on instances that are stopped in this way and then fix any compliance policies. Additionally the "pause" action is more in line with AWS's "stop" action.

**Comment by kapilt** [comment]
should we just add a separate pause action?

**Comment by ksonney** [comment]
Adding a pause/resume would be OK, but I also think adding documentation that the stop action in GCP is different from what might be expected compared to AWS.

**Comment by kapilt** [comment]
pr up with suspend/resume, and added warning doc on stop action that's its behavior is closer to terminate.
