### ISSUE TITLE
RDS instance delete not working

### ISSUE THREAD

**Issue by linuxananth1976** [cloud-custodian/cloud-custodian#8886]
### Describe the bug

I'm not sure after 0.9.30 only it happened or not.  Earlier we had the working process of RDS instance deletion feature, but currently it seems not working.

### What did you expect to happen?

When I checked in general @ajkerrigan replied as follows 
#8713 aws - rds - delete - handle  InvalidParameterValue exception
Not sure this impact or anything I missed out.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
0.9.30
```

### Policy

```shell
- name: rds-delete
    resource: aws.rds
    actions:
      - type: modify-db
        update:
          - property: 'DeletionProtection'
            value: false
          - property: 'PubliclyAccessible'
            value: false
        immediate: true
      - type: delete
        skip-snapshot: true
```

### Relevant log/traceback output

```shell
2023-08-28 14:32:17,822: c7n_org:DEBUG Running policy:rds-delete account:acct_id region:us-east-1
2023-08-28 14:32:20,408: custodian.actions:WARNING delete implicitly filtered 0 of 1 resources key:DBClusterIdentifier on None
2023-08-28 14:32:20,420: c7n_org:INFO Ran account:acct_id region:us-east-1 policy:rds-delete matched:1 time:2.60
2023-08-28 14:32:20,446: c7n_org:INFO Policy resource counts Counter({'rds-delete': 1})
```

**Comment by linuxananth1976** [comment]
@kapilt  @ajkerrigan I tested and confirmed that 0.9.29 works for rds deleting.

**Comment by kapilt** [comment]
thanks for filing the report, treating this as a release blocker for the next release.

**Comment by linuxananth1976** [comment]
Thanks @kapilt @PratMis

**Comment by linuxananth1976** [comment]
Great guys.. Tested with the change and it works fine. Once again Thanks!!!!!
