### ISSUE TITLE
Black hole route cleanup

### ISSUE THREAD

**Issue by jeffastorey** [cloud-custodian/cloud-custodian#912]
Custodian should have a capability to clean up black hole routes.

**Comment by salwandhruvdev** [comment]
looks like #732 is also related (-kapil)

**Comment by kapilt** [comment]
detect on a number of network misconfigurations added in #925 .. that includes bad routes in a route table, bad/dead peers. also has a missing route filter for peering connections.

**Comment by kapilt** [comment]
i think we'll leave this at detection and notification which is implemented, modifying route tables feels like a bridge to far, i'd rather a human get involved to evaluate those.
