### ISSUE TITLE
Support for AWS Bedrock

### ISSUE THREAD

**Issue by PratMis** [cloud-custodian/cloud-custodian#9133]
### Describe the feature

Would love to have support for AWS Bedrock

**Comment by Johnlon** [comment]
@PratMis Hi I've just about gotten my head round the extension mechanism... just about.  I'm enquiring over on slack about adding support for something else. Maybe I could help you with Bedrock. Only thing is it's useful in testing to actually create instances of the resources and I'm not sure what the cost implications are of what you'd need. Never looked at Bedrock.

**Comment by PratMis** [comment]
oops, sorry missed your comment. Yes, I usually spin up a test resource and write policies against it to test. Apparently, bedrock is getting rolled out to customers slowly and I was lucky I got to play with it this week. Was able to create a custom model and am planning to use it to test the new custodian support.

**Comment by Johnlon** [comment]
Ok so there is support
