### ISSUE TITLE
terminate everything

### ISSUE THREAD

**Issue by rkochar** [cloud-custodian/cloud-custodian#9194]
### Describe the feature

I am always frustrated when ...
I would like to terminate everything in a project in GCP. We have an experiment project to build prototypes and want to acid wash it to prepare for the next experiment. Looking for something like `cloud-nuke aws --region <region>`. Thanks!

**Comment by ajkerrigan** [comment]
Custodian is not generally going to be useful for that sort of use case. You _might_ get some use out of other projects that are more focused on nuking, like https://github.com/arehmandev/gcp-nuke though.
