### ISSUE TITLE
Need help in resolving error in ECS service policy

### ISSUE THREAD

**Issue by niteshag123** [cloud-custodian/cloud-custodian#9212]
### Discussed in https://github.com/orgs/cloud-custodian/discussions/9211

<div type='discussions-op-text'>

<sup>Originally posted by **niteshag123** December 21, 2023</sup>
Hi,

Anyone can help me with the below issue, I'm getting "[ERROR] ValueError: not enough values to unpack (expected 2, got 1)". This error i got from cloud watch logs of lambda. My policy is to delete and notify when the ecs service launch in public subnet, Below is my policy

name: ecs-public-service-audit
description: |
  Cloud Custodian ECS public service Audit
resource: ecs-service
mode:
  type: cloudtrail
  events:
    - source: ecs.amazonaws.com
      event: CreateService
      ids: "requestParameters.serviceName"
filters:
    - type: subnet 
      key: "tag:Name"
      op: regex
      value: ".*pub"
actions:
  - type: delete
  - type: notify
    template: redefault.html
    transport:
      type: sqs
      queue: SQSQUEUE
    priority_header: 1
    subject: "ECS service terminated - Launched in Public subnet-[Reference Data Custodian {{ account }} - {{ account_id }} - {{ region }}]"
    violation_desc: "Launching resources in public subnet is prohibited Your new ECS service has been terminated."
    to:
      - event-owner
      - resource-owner
      - AppSupportNotification
    owner_absent_contact:
      - AppSupportNotification

Any help is appreciated. Thanks in advance.</div>

**Comment by kapilt** [comment]
in this case we want the service arn off the response elements because we need not just the service name, but the cluster name, which is in the arn. ie. updating your event ids expression to get the service arn.
