### ISSUE TITLE
support for AWS appmesh

### ISSUE THREAD

**Issue by Johnlon** [cloud-custodian/cloud-custodian#9219]
### Describe the feature

Added basic support for some AppMesh resources.
Perhaps more later.

https://github.com/cloud-custodian/cloud-custodian/pull/9260

**Comment by kapilt** [comment]
cool, thanks, looking forward to the pr, it might be good to add the extensive docs here to the custodian aws developer docs [1], or we maybe we just highlight this resource as a well documented one for other contributors in those docs.

[1] https://cloudcustodian.io/docs/aws/contribute.html

**Comment by Johnlon** [comment]
Hi I made the PR. Better to get what's there over the line than waiting.

Re doc yes - happy to help.
Please give me a pointer to where I could write something as a follow up PR.
I don't want my learning to go to no use.

**Comment by Johnlon** [comment]
Add appmesh virtual gateway and virtual node
