### ISSUE TITLE
Newly AWS enabled region in not available

### ISSUE THREAD

**Issue by viktor-kurchenko** [cloud-custodian/cloud-custodian#9263]
### Describe the bug

I have enabled a new region (`ca-west-1`) on AWS account but Custodian skip it when I run the following command:
`custodian run -r all -s log vpc-tag-policy.yaml`

So, I tried to specify the new region explicitly:
`custodian run -r ca-west-1 -s log vpc-tag-policy.yaml`

and got the following output:
```
2024-01-30 13:53:09,635: c7n.policies:WARNING policy:aws-vpc-tag resources:aws.vpc not available in region:ca-west-1
2024-01-30 13:53:09,635: custodian.commands:WARNING Empty policy file(s).  Nothing to do.
```

Also, I can confirm that `aws ec2 describe-regions` returns the new region:
```
{
            "Endpoint": "ec2.ca-west-1.amazonaws.com",
            "RegionName": "ca-west-1",
            "OptInStatus": "opted-in"
}
```

### What did you expect to happen?

I expected that Cloud Custodian will be able to find a new region and run the policy.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.34
Python:      3.12.1 (main, Dec  7 2023, 20:45:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]
Platform:    posix.uname_result(sysname='Darwin', nodename='MBP', release='23.2.0', version='Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000', machine='arm64')
Using venv:  True
Docker: False
Installed: 

argcomplete==3.2.1
attrs==23.2.0
boto3==1.34.22
botocore==1.34.22
docutils==0.18.1
importlib-metadata==6.11.0
jmespath==1.0.1
jsonschema==4.21.0
jsonschema-specifications==2023.12.1
python-dateutil==2.8.2
pyyaml==6.0.1
referencing==0.31.1
rpds-py==0.17.1
s3transfer==0.10.0
six==1.16.0
tabulate==0.0.0
urllib3==1.26.18
zipp==3.17.0
```

### Policy

```shell
policies:
  - name: aws-vpc-tag
    description: |
      Tag untagged and non-default VPCs with `created` date.
    resource: aws.vpc
    filters:
      - type: value
        key: IsDefault
        value: false
      - tag:created: absent
    actions:
      - type: tag
        tags:
          created: '{now}'
```

**Comment by kapilt** [comment]
we get available regions from the sdk, we typically pin our dependencies for each release, and upgrade them between releases, so it should be available in the next release of custodian automatically.

**Comment by viktor-kurchenko** [comment]
> we get available regions from the sdk, we typically pin our dependencies for each release, and upgrade them between releases, so it should be available in the next release of custodian automatically.

@kapilt thank you for the reply!
The same is true about the c7n-org tool, right?
