### ISSUE TITLE
Find Config retention settings

### ISSUE THREAD

**Issue by ajkerrigan** [cloud-custodian/cloud-custodian#9333]
### Describe the feature

It would be useful to expose [Config service retention settings](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/config/client/describe_retention_configurations.html#ConfigService.Client.describe_retention_configurations), either through a new resource/filter or as part of the existing account-level `check-config` filter.

**Comment by kapilt** [comment]
Config recorder filter ideally I think

**Comment by limacarvalho** [comment]
Hi everyone! I've started looking into this one.

**Comment by ajkerrigan** [comment]
Thanks!

**Comment by limacarvalho** [comment]
Hi @ajkerrigan and @kapilt I've just opened up the PR https://github.com/cloud-custodian/cloud-custodian/pull/9528
Thanks a lot!
