### ISSUE TITLE
Datetime representation in captured JSON files when recording api calls

### ISSUE THREAD

**Issue by Johnlon** [cloud-custodian/cloud-custodian#9376]
### Describe the bug

When I record data with for test purposes then the date values are serialised to JSON with the internal provate representation.

If you search for the value below then you will see tons of evidence .rom the placebo date data ...

      "__class__": "datetime"

Looks like everyone is just putting up with it.

### What did you expect to happen?

I expected datetimes to look like:

      "createdAt": "2024-03-22T23:14:07.869000+00:00",

What I get are serialised internal details of the datetime class - this isn't valid json but one should never serialise internal vals like this.

       {
       "status_code": 200,
       "data": {
           "ResponseMetadata": {},
           "meshes": [
               {
                   "arn": "arn:aws:appmesh:us-east-1:644160558196:mesh/m1",
                   "createdAt": {
                       "__class__": "datetime",
                       "year": 2024,
                       "month": 3,
                       "day": 22,
                       "hour": 23,
                       "minute": 11,
                       "second": 29,
                       "microsecond": 749000
                   },

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Latest trunk
```

**Comment by ajkerrigan** [comment]
This is working as designed ([by placebo](https://github.com/garnaat/placebo/blob/40a033d2b7fc2ba0a6a20799f4b1463658bd15cf/placebo/serializer.py#L90-L119)). It's aiming to faithfully record/replay boto3 responses, which include Python datetimes.

In other cases where we record lower level HTTP responses with vcr, the dates appear as strings.
