### ISSUE TITLE
Include c7n_awscc in the official docker image, use recent version

### ISSUE THREAD

**Issue by shantycode** [cloud-custodian/cloud-custodian#9417]
### Describe the feature

Hey folks,

in order to use the new functionality introduced [here](https://github.com/cloud-custodian/cloud-custodian/pull/9297) we would like to see the inclusion of c7n_awscc in the official docker image. 
We tried building it ourselves using `pip install c7n_awscc ` as RUN command in a Dockerfile but only got version `0.1.16` and not `0.1.20` on `aarch64` or `x86_64`.
 
If it is just as easy as copy&adapting this line [here](https://github.com/cloud-custodian/cloud-custodian/blob/db8cad56ed7a0f569742c77a75fc99cb44c8db34/tools/dev/dockerpkg.py#L183) I guess I could provide a PR for that :) 

Thanks in advance,
Florian

**Comment by syed-awais-ali** [comment]
I have opened a PR for this https://github.com/cloud-custodian/cloud-custodian/pull/9521

**Comment by kapilt** [comment]
closed in #9521
