### ISSUE TITLE
Cannot mix credential and access-key filters with delete action

### ISSUE THREAD

**Issue by Nithyu** [cloud-custodian/cloud-custodian#9472]
### Describe the bug

I have a use case, where I need to disable the IAM access keys of an IAM user that were never accessed even once for more than a year from its date of creation (**date of creation of the IAM Access key and not the date of creation of the IAM user**).

Also, kindly note that I'm just trying to disable the IAM Access keys and not delete. 

Hence, in my policy, I used two filters. The first filter is "credential" as it would help in getting the details for the last used date of the access keys. next, I used the "access key" filter as it would help us in getting the creation date of the access keys, then once I obtain the correct list, I set the disable flag to "true". 

I used two different filters as there is no other way to get the access keys last used date and its creation date using the same filter. Then, when I tried running the policy, I received the below message.

`2024-04-12 13:19:59,303: custodian.commands:ERROR invalid policy file: cc-issue.yaml error: policy:%s cant mix credential and access-key filters w/ delete action`

### What did you expect to happen?

The policy should be able to disable the list of IAM access keys keys that were created a year back (**the IAM keys that were created and not the IAM user**). I have attached the policy in the below section for reference. Kindly note in the policy that for below key :- 

```
key: access_keys.last_used_date
value: absent
```
I have set the value to "absent" because that is the only way to filter out the access keys that were never used at all.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
(custodian) nts@11518A-NTS ~ % custodian version --debug

Please copy/paste the following info along with any bug reports:

Custodian:   0.9.32
Python:      3.9.6 (default, May  7 2023, 23:32:44) 
             [Clang 14.0.3 (clang-1403.0.22.14.1)]
Platform:    posix.uname_result(sysname='Darwin', nodename='11518A-NTS', release='22.4.0', version='Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000', machine='arm64')
Using venv:  True
Docker: False
Installed: 

argcomplete==3.1.2
attrs==23.1.0
boto3==1.28.58
botocore==1.31.58
docutils==0.18.1
importlib-metadata==5.2.0
jmespath==1.0.1
jsonschema==4.19.1
jsonschema-specifications==2023.7.1
python-dateutil==2.8.2
pyyaml==6.0.1
referencing==0.30.2
rpds-py==0.10.3
s3transfer==0.7.0
six==1.16.0
tabulate==0.9.0
urllib3==1.26.17
zipp==3.17.0
```

### Policy

```shell
policies:
  - name: test-never-accessed-iam-keys
    resource: iam-user
    filters:
      - type: credential
        key: access_keys.last_used_date
        value: absent
      - type: access-key
        key: Status
        value: Active
      - type: access-key
        key: CreateDate
        value: 365
        op: ge
        value_type: age
    actions:
      - type: remove-keys
        disable: true
```

### Relevant log/traceback output

```shell
(custodian) nts@11518A-NTS cc-issue % custodian run --dryrun -s output cc-issue.yaml
2024-04-12 13:19:59,303: custodian.commands:ERROR invalid policy file: cc-issue.yaml error: policy:%s cant mix credential and access-key filters w/ delete action
2024-04-12 13:19:59,303: custodian.commands:ERROR Found 1 errors. Exiting.
```

### Extra information or context

I tried looking into the source code and found where the error is being handled. Below is the link :- 

https://cloudcustodian.io/docs/_modules/c7n/resources/iam.html#:~:text=%22policy%3A%25s%20cant%20mix%20credential%20and%20access%2Dkey%20filters%20w/%20delete%20action%22

I tried to comment out the "if" condition in the `def validate(self)` section where is raises the policy validation error. I then tried to deploy it on the test account and it was bale to work. Not the best way to do it but I was testing it out. Hence, kindly request you to look into this use case and kindly let me know if there is work around for this. Thank you.

**Comment by alfredgamulo** [comment]
This person pinged me directly, so I'll respond here:

Essentially, when I run your policy as attached, we can review the found resources in resources.json, example:
```
[
  {
    "Path": "/",
    "UserName": "<redacted>",
    "UserId": "<redacted>",
    "Arn": "arn:aws:iam::<redacted>:user/<redacted>",
    "CreateDate": "2024-04-10T08:26:27+00:00",
    "Tags": [
      {
        "Key": "Creator",
        "Value": "<redacted>"
      }
    ],
    "c7n:matched-keys": [],
    "c7n:credential-report": {
      "user": "<redacted>",
      "arn": "arn:aws:iam::<redacted>:user/<redacted>",
      "user_creation_time": "2024-04-10T08:26:27+00:00",
      "password_enabled": false,
      "password_last_used": null,
      "password_last_changed": null,
      "password_next_rotation": null,
      "mfa_active": false,
      "access_keys": [
        {
          "active": true,
          "last_rotated": "2024-04-10T08:26:47+00:00",
          "last_used_date": null,
          "last_used_region": null,
          "last_used_service": null,
          "c7n:match-type": "credential"
        }
      ]
    },
    "c7n:AccessKeys": [
      {
        "UserName": "<redacted>",
        "AccessKeyId": "<redacted>",
        "Status": "Active",
        "CreateDate": "2024-04-10T08:26:47+00:00",
        "c7n:match-type": "access"
      }
    ]
  },
```  

See how the `c7n:credential-report` is a separate object from `c7n:AccessKeys`.

If you were to select only one of the filter types then `c7n:matched-keys` would be populated via explicit filtering. Under the current policy, the filtering is ambiguous so that `c7n:matched-keys` cannot be identified. This is the field that actions are performed.

Try the policy as:
```
  - name: just-credentials
    resource: iam-user
    filters:
    - type: credential
      key: access_keys.last_used_date
      value: absent
    - type: credential
      key: access_keys.last_rotated
      value: 7
      op: ge
      value_type: age
```

This should be enough for you to find the keys that you want to disable.
