### ISSUE TITLE
Link to Johns Dumms Guide

### ISSUE THREAD

**Issue by Johnlon** [cloud-custodian/cloud-custodian#9494]
### Describe the feature

Had a few people tell me this was very useful to them, and it's been road tested now by someone else's extension.

https://gist.github.com/Johnlon/98e1e4b9aaedfedead428c89e7dab5bb

Could we have CC link to it and/or host it somewhere else if gist isn't ok.

**Comment by kapilt** [comment]
A link from the developer docs for AWS sounds great re pr

**Comment by Johnlon** [comment]
Added pr 

https://github.com/cloud-custodian/cloud-custodian/pull/9502/commits

**Comment by kapilt** [comment]
thanks, merged
