### ISSUE TITLE
0.9.37.0 causing nodes to go NotReady

### ISSUE THREAD

**Issue by waddles** [cloud-custodian/cloud-custodian#9554]
### Describe the bug

We use the image tag `cloudcustodian/c7n-org` which implies `cloudcustodian/c7n-org:latest`. About 4 hours ago, our nodes started going NotReady while running the cloud-custodian CronJob and this coincides with the release of [0.9.37.0](https://hub.docker.com/layers/cloudcustodian/c7n-org/0.9.37.0/images/sha256-056b4575f6725c7fb4ad28a92b118030570e8ced5524f2ec5b85c93ee7c95da5)

This problem also causes the pod to not terminate, though that may be unique to our cluster, which then causes the node termination to stall and I have to go into EC2 and terminate them manually.

### What did you expect to happen?

Something in the latest build is causing the problem. Reverting back to `cloudcustodian/c7n-org:0.9.36.0` allows the job to succeed again. I will try and get more information later.

### Cloud Provider

Amazon Web Services (AWS)

### Extra information or context

Probably worth noting the instance types used are all `c6a.2xlarge` (amd64) on nitro hypervisor and it has occurred on at least 9 instances.

**Comment by kapilt** [comment]
we had some aws client caching in 0.9.37 that seemed to be causing issues in certain setups #9558 has some details, that's been reverted and 0.9.38 is coming out shortly

**Comment by kapilt** [comment]
0.9.38 is released and should hopefully resolve this.

**Comment by waddles** [comment]
Confirmed this is now fixed in 0.9.38.0
