### ISSUE TITLE
config-rule mode for custodian policy errors out with keyerror

### ISSUE THREAD

**Issue by sujit-kulkarni** [cloud-custodian/cloud-custodian#9611]
### Describe the bug

Below is my policy for the config-rule

  - name: ec2-config-compliant-ami-age
    description: check for EC2's with ami older than 120 days
    resource: ec2
    mode:
      type: config-rule
      role: mylambda-role
      dead_letter_config:
        TargetArn: arn:aws:sqs:{region}:{account_id}:custodian-lambda-dlq
    filters:
      - type: image-age
        days: 120
        op: ge

I have similar policy for the "asg" resource as well. Both fail when executed in the lambda with the keyerror
[ERROR] KeyError: 'detail'
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 4, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 142, in dispatch_event
    event['detail'] = 
{}
 if event.get('detail') == '
{}
' else event['detail']

For asg also I key the Keyrror.

### What did you expect to happen?

I expected to to execute gracefully and list the ami's older than 120days

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
custodian version 0.0.38
```

**Comment by sujit-kulkarni** [comment]
Update - custodian version 0.9.38

**Comment by wilkei-ffma** [comment]
any fixes? comments? ideas? results? conclusions?

**Comment by snowiow** [comment]
we see the same problem with 0.9.38
