### ISSUE TITLE
Don't invoke AWS Lambda functions for failed operations

### ISSUE THREAD

**Issue by sergey-trukhin** [cloud-custodian/cloud-custodian#9648]
### Describe the feature

Hello everyone,

Currently, the behavior of Cloud Custodian in AWS **cloudtrail** execution mode is the following (please correct me if I'm wrong):
1. Some unsuccessful operations happens (e.g., somebody tried to create an EC2 AMI, but this operation finished with an error for whatever reason)
2. Corresponding CloudTrail event appears, and it's sent to EventBridge
3. CloudCustodian's rule in EventBridge looks like this, so it triggers the Lambda function:
```json
{
  "detail-type": ["AWS API Call via CloudTrail"],
  "detail": {
    "eventSource": ["ec2.amazonaws.com"],
    "eventName": ["CreateImage"]
  }
}
```
4. The Lambda function checks if the CloudTrail event has the **errorCode** field, and if so, it does nothing except some logging.

As a result, Lambda functions are invoked anyway. On a large scale, there could be many unnecessary Lambda function invocations that actually do nothing but are still billed for a couple of milliseconds each.

This behavior was probably implemented when there were no better options. However, nowadays, it seems to be possible to filter out failed operations on the AWS EventBridge level using [comparison operators](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-create-pattern-operators.html#eb-filtering-exists-matching) and avoid triggering Lambda functions when it's not necessary. For example:
```json
{
  "detail-type": ["AWS API Call via CloudTrail"],
  "detail": {
    "eventSource": ["ec2.amazonaws.com"],
    "eventName": ["CreateImage"],
    "errorCode": [{
      "exists": false
    }]
  }
}
```

I think the event pattern for the AWS EventBridge is generated by [this part of the code](https://github.com/cloud-custodian/cloud-custodian/blob/0.9.40.0/c7n/mu.py#L1121-L1123). However, it's probably not so easy to change that, as the behavior should be customizable and somehow aligned [with this feature](https://github.com/cloud-custodian/cloud-custodian/issues/3122). Some people want to run Lambda functions even for failed operations.

What do you think about this? Would it make sense to implement this earlier filtering on the AWS EventBridge side and save somebody a couple of cents?

Unfortunately, I don't know Cloud Custodian's code deeply enough to make the required changes myself.

**Comment by ajkerrigan** [comment]
Thanks for the discussion here, all your digging looks good. You're right that the current default is to allow errors to trigger the event, but then ignore those events at runtime.

> However, it's probably not so easy to change that, as the behavior should be customizable and somehow aligned https://github.com/cloud-custodian/cloud-custodian/issues/3122. Some people want to run Lambda functions even for failed operations.

I think that's why today if you want to ignore those errors earlier, you handle it with policy-level overrides as described [here](https://cloudcustodian.io/docs/aws/lambda.html#event-pattern-filtering). In your example, that could mean a policy like this:

```yaml
policies:
  - name: ami-create-skip-errors
    resource: aws.ami
    mode:
      type: cloudtrail
      events:
        - source: ec2.amazonaws.com
          event: CreateImage
          ids: "responseElements.imageId"
      pattern:
        detail:
          errorCode:
            - exists: false
```

Which leads to an EventBridge rule like this:

```json
{
  "detail": {
    "eventSource": ["ec2.amazonaws.com"],
    "eventName": ["CreateImage"],
    "errorCode": [{
      "exists": false
    }]
  },
  "detail-type": ["AWS API Call via CloudTrail"]
}
```

**Comment by sergey-trukhin** [comment]
@ajkerrigan, thank you for sharing that documentation!

I have checked the documentation for the "events" property and obviously didn't find how to ignore failed events using it. I didn't realize there is also a "pattern" property related to EventBridge (former CloudWatch Events).

With this, it's definitely possible to achieve the same results I mentioned above, and it's even more flexible.

Thank you!
