### ISSUE TITLE
cloudcustodian.io search is broken

### ISSUE THREAD

**Issue by cvitter** [cloud-custodian/cloud-custodian#9651]
### Describe the bug

Attempting to search on any term (example: https://cloudcustodian.io/docs/search.html?q=value_from&check_keywords=yes&area=default#) within the Cloud Custodian documentation fails to complete.

<img width="1108" alt="Screenshot 2024-08-01 at 3 07 45 PM" src="https://github.com/user-attachments/assets/327012c4-9faf-4d0f-922b-8ce0bf4f36a6">

### What did you expect to happen?

Expected the search to return a list of pages related to `value_from` in the example above.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
NA
```

**Comment by ajkerrigan** [comment]
Thanks for reporting! I just recently ran into this myself, coincidentally as I transitioned to a new machine so thought it was a weird local issue :sweat_smile: . Digging in a bit I see where the issue is, looking to address in #9655
