### ISSUE TITLE
Support required for ses-configuration-set Delete Action

### ISSUE THREAD

**Issue by archinksagar** [cloud-custodian/cloud-custodian#9773]
### Describe the feature

Need support for Delete Action for ses-configuration-set

### Extra information or context

https://docs.aws.amazon.com/ses/latest/APIReference/API_DeleteConfigurationSet.html

**Comment by zachlieberman** [comment]
I am working on this as my first contribution

**Comment by archinksagar** [comment]
@zachlieberman I have created a draft [PR](https://github.com/cloud-custodian/cloud-custodian/pull/9778) for this issue
