### ISSUE TITLE
Ability to filter all route53 rrsets

### ISSUE THREAD

**Issue by Sutto** [cloud-custodian/cloud-custodian#980]
The rrset call requires passing the AWS API a hosted zone id, which means you have to manually encode a rule for each hosted zone.

A potentially more useful approach would be to actually default to all zones, and potentially allow filtering to the `HostedZoneId`  if needed.

As an example use case of a rule, #762 would become more useful here.

I note that #584 exists to look into this better on a more generic level.

**Comment by kapilt** [comment]
looks like this was implemented `resource: aws.rrset` for resource record set.
