### ISSUE TITLE
Website for the project

### ISSUE THREAD

**Issue by mdziczkowski** [cloud-custodian/cloud-custodian#9815]
### Describe the feature

Since the offiicial website of the project is dead (not existing), it would be great if there would be a new website created with all needed info and documentation

**Comment by kapilt** [comment]
The website is alive and well https://cloudcustodian.io

Where did you find a dead link, or what do you find missing that you'd like to see?

**Comment by mdziczkowski** [comment]
First of, I want to let you know that you're doing a great job with the development and support. It's very appreciated 👍😉

#### Where I had Found it

[Cloud Custodian project on OpenHub](https://openhub.net/p/cloud-custodian)

#### What I would like to see

It would be great to see a

**Comment by kapilt** [comment]
that black duck page is a third party website and not affiliated to the project, and moreover contains much outdated information (custodian has been in the cncf foundation for over 5 yrs now).

**Comment by mdziczkowski** [comment]
Couldn't someone from the developers (or project owner) to take on this page as manager of the project page and update the informations? 🤔
